$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;Set-Location $root
function Assert($condition,[string]$message){if(-not $condition){throw "FAIL: $message"};Write-Host "PASS $message"}
function ReadyState{try{Invoke-RestMethod -Uri http://localhost:8080/health/ready -TimeoutSec 8}catch{$null}}
function WaitReady{for($attempt=0;$attempt-lt 45;$attempt++){if((ReadyState).status -eq 'ready'){return};Start-Sleep 1};throw 'Readiness did not recover'}
function Outage([string]$container,[string]$name,[string]$dependency,[bool]$required=$false){docker stop $container|Out-Null;Start-Sleep 2;$state=ReadyState;if($required){Assert ($null -eq $state -or $state.status -eq 'not_ready') "$name outage makes readiness fail"}else{Assert ($state.status -eq 'ready_degraded' -and $state.dependencies.$dependency -notmatch '^healthy$') "$name outage is reported as degraded"};docker start $container|Out-Null;WaitReady;Assert ((ReadyState).status -eq 'ready') "$name recovery restores readiness"}
$settings=@{};Get-Content .env|Where-Object{$_ -match '^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$settings[$p[0]]=$p[1]};$login=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$headers=@{Authorization="Bearer $($login.access_token)"}
$agentContainer=docker ps --filter ancestor=deployment-agent:latest --format '{{.Names}}'|Select-Object -First 1;Assert (-not [string]::IsNullOrWhiteSpace($agentContainer)) 'active mTLS agent is available for reconnect testing'
Outage deployment-postgres-1 PostgreSQL database $true
Outage deployment-nats-1 NATS messageBus
Outage deployment-opensearch-1 OpenSearch search
$rebuilt=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/endpoints/projections:rebuild -Headers $headers;Assert ($rebuilt.data.aliasSwitched -and $rebuilt.data.documents -gt 0) 'projection rebuild recovers after OpenSearch outage'
$persistId=[guid]::NewGuid();$persistBytes=[Text.Encoding]::UTF8.GetBytes('minio-restart-persistence');$persistHasher=[Security.Cryptography.SHA256]::Create();$persistHash=([BitConverter]::ToString($persistHasher.ComputeHash($persistBytes))).Replace('-','').ToLowerInvariant();$persistFile=[IO.Path]::GetTempFileName();[IO.File]::WriteAllBytes($persistFile,$persistBytes);Invoke-RestMethod -Method Put -Uri "http://localhost:8080/internal/v1/objects/$persistId" -Headers ($headers+@{'X-Content-SHA256'=$persistHash}) -ContentType application/octet-stream -InFile $persistFile|Out-Null;Remove-Item -LiteralPath $persistFile -Force
Outage deployment-minio-1 MinIO objectStorage
$persistDownload=[IO.Path]::GetTempFileName();Invoke-WebRequest -Uri "http://localhost:8080/internal/v1/objects/$persistId" -Headers $headers -OutFile $persistDownload;Assert ([IO.File]::ReadAllText($persistDownload) -eq 'minio-restart-persistence') 'MinIO object persists across restart';Remove-Item -LiteralPath $persistDownload -Force;Invoke-RestMethod -Method Delete -Uri "http://localhost:8080/internal/v1/objects/$persistId" -Headers $headers|Out-Null
$before=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select coalesce(max(sequence),0) from platform.agent_heartbeats");docker restart deployment-gateway-1|Out-Null;WaitReady;for($attempt=0;$attempt-lt 90;$attempt++){Start-Sleep 1;$after=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select coalesce(max(sequence),0) from platform.agent_heartbeats");if($after -gt $before){break}};if($after -le $before){Write-Host 'Reconnect agent diagnostics:';docker logs $agentContainer};Assert ($after -gt $before) "agent $agentContainer reconnects and heartbeats after gateway restart"
docker restart deployment-postgres-1 deployment-nats-1 deployment-minio-1 deployment-opensearch-1|Out-Null;WaitReady;Assert ((ReadyState).status -eq 'ready') 'combined infrastructure restart recovers'
$transaction=docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc "begin;select 1;commit";Assert ($transaction -contains '1') 'PostgreSQL accepts transactions after recovery'
$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?consumers=true'|ConvertFrom-Json;$projectionConsumer=$nats.account_details[0].stream_detail[0].consumer_detail|Where-Object name -Like 'endpoint-projection*'|Select-Object -First 1;Assert ($null-ne $projectionConsumer) 'durable versioned NATS consumer reconnects after restart'
Write-Host 'Failure-recovery suite passed.'
