[CmdletBinding()]
param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',[string]$QualificationRoot='C:\Sprint24Qualification',[int]$TimeoutSeconds=300)
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '../..');Set-Location $root
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();if(-not[Security.Principal.WindowsPrincipal]::new($identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Elevated host token required.'};if((Get-VM $VictimVmName).State-ne'Running'){throw 'Existing victim VM must be running.'}
$settings=@{};Get-Content .env|?{$_-match '^\s*([^#=\s]+)=(.*)$'}|%{$settings[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")};$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$admin=@{Authorization="Bearer $($login.access_token)"}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')};function Jwt{$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='large-artifact-isolation-approver';tid=$settings.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('platform:admin','isolation:approve','live:approve:elevated');pty='user';iat=$n;exp=$n+3600;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};@{Authorization="Bearer $h.$b.$s"}};$approver=Jwt
function Api($method,$path,$headers=$admin,$body=$null){$a=@{Method=$method;Uri="http://127.0.0.1:8080$path";Headers=$headers};if($null-ne$body){$a.ContentType='application/json';$a.Body=$body|ConvertTo-Json -Depth 30 -Compress};(Invoke-RestMethod @a).data}
function Guest($script,$arguments=@()){$c=Import-Clixml $CredentialPath;$s=New-PSSession -VMName $VictimVmName -Credential $c;try{Invoke-Command -Session $s -ScriptBlock $script -ArgumentList $arguments}finally{Remove-PSSession $s}}
function Wait-Action($id){$d=[DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 400;$x=Api GET "/api/v1/response-actions/$id"}while($x.state-notin@('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected')-and[DateTimeOffset]::UtcNow-lt$d);$x}
function Act($endpoint,$operation,$reason){$x=Api POST "/api/v1/endpoints/$endpoint`:$operation" $admin @{endpointId=$endpoint;reason=$reason;expiresInSeconds=300};if($x.approvalState-eq'Pending'){$x=Api POST "/api/v1/isolation-actions/$($x.responseActionId):approve" $approver @{parameterHash=$x.parameterHash;reason='Separated approval for victim-only large-artifact isolation qualification'}};Wait-Action $x.responseActionId}
function Wait-Session($id){$d=[DateTimeOffset]::UtcNow.AddSeconds(90);do{Start-Sleep -Milliseconds 400;$x=Api GET "/api/v1/live-response/sessions/$id"}while($x.state-notin@('Active','Rejected','Expired')-and[DateTimeOffset]::UtcNow-lt$d);$x}
function Run($session,$command){$x=Api POST "/api/v1/live-response/sessions/$session/commands" $admin @{commandType='BuiltIn';input=$command;timeoutSeconds=900};$d=[DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 400;$x=Api GET "/api/v1/live-response/sessions/$session/commands/$($x.commandId)"}while($x.state-notin@('Succeeded','Failed','TimedOut','Cancelled','Expired','Uncertain')-and[DateTimeOffset]::UtcNow-lt$d);$x}
$agent=$null;$isolated=$false;$endpoint=$null;$session=$null
try{
  $state=Guest{param($q)Add-Type -AssemblyName System.Security;$h=[Security.Cryptography.SHA256]::Create();try{$e=$h.ComputeHash([Text.Encoding]::UTF8.GetBytes('open-security-platform-agent-state-v1'))}finally{$h.Dispose()};$b=[Security.Cryptography.ProtectedData]::Unprotect([IO.File]::ReadAllBytes("$q\runtime-data\state.dat"),$e,[Security.Cryptography.DataProtectionScope]::LocalMachine);$v=[Text.Encoding]::UTF8.GetString($b)|ConvertFrom-Json;[pscustomobject]@{EndpointId=$v.endpointId;InstallationId=$v.installationId}}@($QualificationRoot);$endpoint=$state.EndpointId
  $agent=Guest{param($q)Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;$env:PLATFORM_CONTROL_PLANE_URL='https://gateway:8443';$env:PLATFORM_AGENT_DATA="$q\runtime-data";$env:PLATFORM_CA_CERT_PATH='C:\Sprint19Qualification\ca.crt';$env:PLATFORM_ENVIRONMENT='production';$env:PLATFORM_RESPONSE_ONLY='true';$env:PLATFORM_LIVE_RESPONSE_ROOTS=$q;$env:PLATFORM_ARTIFACT_TRANSFER_MIBPS='32';(Start-Process "$q\agent\Platform.Agent.exe" -PassThru -WindowStyle Hidden -RedirectStandardOutput "$q\isolated-agent.log" -RedirectStandardError "$q\isolated-agent-error.log").Id}@($QualificationRoot);Start-Sleep 3
  $verify=Api POST "/api/v1/endpoints/$endpoint/isolation:verify";$verify=Wait-Action $verify.responseActionId;if($verify.state-ne'Succeeded'-or$verify.result.structuredResult.effectiveState-ne'NotIsolated'){throw 'Victim was not cleanly unisolated before qualification.'}
  $before=Guest{[pscustomobject]@{management=Test-NetConnection gateway -Port 8443 -InformationLevel Quiet;controlled=Test-NetConnection 1.1.1.1 -Port 443 -InformationLevel Quiet}}
  $isolate=Act $endpoint isolate 'Victim-only isolated artifact transfer';if($isolate.state-ne'Succeeded'){throw "Isolation failed: $($isolate.state)"};$isolated=$true
  $during=Guest{[pscustomobject]@{management=Test-NetConnection gateway -Port 8443 -InformationLevel Quiet;controlled=Test-NetConnection 1.1.1.1 -Port 443 -InformationLevel Quiet}}
  $requested=Api POST '/api/v1/live-response/sessions' $admin @{endpointId=$endpoint;capabilities=@('builtin','file-download');idleTimeoutSeconds=600;absoluteLifetimeSeconds=1800;policyVersion='live-response-policy.v1'};if($requested.state-eq'PendingApproval'){$null=Api POST "/api/v1/live-response/sessions/$($requested.sessionId):approve" $approver @{capabilityHash=$requested.capabilityHash;reason='Separated approval for isolated artifact pull'}};$session=Wait-Session $requested.sessionId;if($session.state-ne'Active'){throw 'Isolated Live Response session did not activate.'}
  $get=Run $session.sessionId "get `"$QualificationRoot\large-artifact.bin`"";if($get.state-ne'Succeeded'){throw "Isolated get failed: $($get.state)"};$artifact=$get.result.artifacts[0];$transfer=(Api GET "/api/v1/artifact-transfers?ownerId=$($get.commandId)")[0];$download=Join-Path $root 'artifacts/isolated-artifact-download.bin';Invoke-WebRequest "http://127.0.0.1:8080/api/v1/artifact-transfers/$($transfer.transferId)/content" -Headers $admin -OutFile $download -UseBasicParsing|Out-Null;$downloadHash=(Get-FileHash $download -Algorithm SHA256).Hash.ToLowerInvariant()
  $null=Api POST "/api/v1/live-response/sessions/$($session.sessionId):close" $admin @{reason='isolated artifact qualification complete'};$session=$null
  $unisolate=Act $endpoint unisolate 'Restore victim connectivity after isolated artifact test';$isolated=$false;$after=Guest{[pscustomobject]@{management=Test-NetConnection gateway -Port 8443 -InformationLevel Quiet;controlled=Test-NetConnection 1.1.1.1 -Port 443 -InformationLevel Quiet}}
  $pass=$before.management-and$before.controlled-and$isolate.result.structuredResult.effectiveState-eq'Isolated'-and$during.management-and-not$during.controlled-and$transfer.state-eq'Completed'-and$transfer.totalChunks-eq3-and$artifact.sha256-eq$downloadHash-and$unisolate.state-eq'Succeeded'-and$after.management-and$after.controlled
  $report=[ordered]@{schemaVersion='isolated-artifact-rtr.v1';executedAt=[DateTimeOffset]::UtcNow;victimVm=$VictimVmName;endpointId=$endpoint;hostMutation='none';before=$before;isolationState=$isolate.result.structuredResult.effectiveState;during=$during;liveCommand=$get.state;transfer=$transfer;artifactSha256=$artifact.sha256;downloadSha256=$downloadHash;unisolationState=$unisolate.result.structuredResult.effectiveState;after=$after;result=if($pass){'PASS'}else{'FAIL'}};$report|ConvertTo-Json -Depth 20|Set-Content artifacts/isolated-artifact-rtr.json -Encoding utf8;$report|ConvertTo-Json -Depth 10;if(!$pass){exit 1}
}finally{
  if($session){try{$null=Api POST "/api/v1/live-response/sessions/$($session.sessionId):close" $admin @{reason='Isolated artifact qualification cleanup'}}catch{}}
  if($isolated-and$endpoint){try{$cleanup=Act $endpoint unisolate 'Mandatory isolated artifact cleanup';$isolated=$cleanup.result.structuredResult.effectiveState-ne'NotIsolated'}catch{}}
  try{Guest{Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force}|Out-Null}catch{}
  if($isolated){throw 'BLOCKER: victim could not be confirmed unisolated during mandatory cleanup.'}
}

