param([switch]$StartStack)
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Net.Http
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
Set-Location $root
function Assert($condition,[string]$message){if(-not $condition){throw "FAIL: $message"};Write-Host "PASS $message"}
function Settings{$values=@{};Get-Content .env|Where-Object{$_ -match '^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$values[$p[0]]=$p[1]};$values}
function B64Url([byte[]]$bytes){[Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt([string]$tenant,[hashtable]$settings){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$header=B64Url([Text.Encoding]::UTF8.GetBytes((@{alg='HS256';typ='JWT'}|ConvertTo-Json -Compress)));$payload=B64Url([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='integration';tid=$tenant;per=@('platform:admin','agent:enroll','endpoint:read');pty='user';iat=$now;exp=$now+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$hmac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));"$header.$payload.$(B64Url($hmac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$header.$payload"))))"}
if($StartStack){docker compose -f deployment/docker-compose.yml --env-file .env up -d --build postgres nats minio opensearch gateway|Out-Null;Get-Content storage/seeds/development.sql|docker exec -i deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform|Out-Null;docker compose -f deployment/docker-compose.yml --env-file .env build agent|Out-Null}
$settings=Settings
$ready=$null
1..60|ForEach-Object{if($ready){return};try{$candidate=Invoke-RestMethod -Uri http://localhost:8080/health/ready -TimeoutSec 2;if($candidate.status -eq 'ready'){$ready=$candidate}}catch{};if(-not $ready){Start-Sleep 1}}
Assert ($ready.status -eq 'ready') 'production readiness is healthy'
$poolClient=[Net.Http.HttpClient]::new();$poolTasks=[Collections.Generic.List[Threading.Tasks.Task[Net.Http.HttpResponseMessage]]]::new();1..80|ForEach-Object{$poolTasks.Add($poolClient.GetAsync('http://localhost:8080/health/ready'))};[Threading.Tasks.Task]::WaitAll([Threading.Tasks.Task[]]$poolTasks.ToArray());Assert (($poolTasks|Where-Object{$_.Result.StatusCode -ne 200}|Measure-Object).Count -eq 0) 'PostgreSQL connection pool handles 80 concurrent production requests';$poolClient.Dispose()
$migration=docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.schema_migrations where version in('0001_sprint_zero','0002_endpoint_enrollment','0003_endpoint_lifecycle')"
Assert ([int]$migration -eq 3) 'all Sprint 1 migrations are recorded'
$rollback=docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc "begin; create table platform.integration_rollback_probe(id int); rollback; select to_regclass('platform.integration_rollback_probe') is null"
Assert ($rollback[-1] -eq 't') 'PostgreSQL transaction rollback leaves no partial state'
$constraints=docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from pg_constraint where connamespace='platform'::regnamespace and contype in('p','f','u','c')"
Assert ([int]$constraints -ge 30) 'PostgreSQL constraints are active'
$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?consumers=true&config=true'|ConvertFrom-Json
$consumer=$nats.account_details[0].stream_detail[0].consumer_detail|Where-Object name -Like 'endpoint-projection*'|Sort-Object name -Descending|Select-Object -First 1;Assert ($null-ne $consumer) 'NATS durable versioned endpoint consumer exists';Assert ($consumer.config.ack_policy -eq 'explicit' -and $consumer.config.max_deliver -ge 1 -and $consumer.config.max_deliver -le 50) 'NATS consumer uses explicit ACK and bounded redelivery'
$aliases=docker exec deployment-opensearch-1 curl -fs http://localhost:9200/_alias/platform-endpoints|ConvertFrom-Json
Assert (($aliases.psobject.Properties.Name|Measure-Object).Count -eq 1) 'OpenSearch alias has one active versioned index'
$admin=Jwt $settings.PLATFORM_BOOTSTRAP_TENANT_ID $settings;$headers=@{Authorization="Bearer $admin"}
$rebuild=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/endpoints/projections:rebuild -Headers $headers;$progress=Invoke-RestMethod -Uri http://localhost:8080/api/v1/endpoints/projections:rebuild -Headers $headers;Assert (-not $progress.data.running -and $progress.data.completedDocuments -eq $rebuild.data.documents -and $progress.data.totalDocuments -eq $rebuild.data.documents) 'projection rebuild exposes verified progress and completion'
$endpoints=Invoke-RestMethod -Uri http://localhost:8080/api/v1/endpoints?pageSize=2 -Headers $headers
if($endpoints.data.items.Count -eq 0){$created=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/enrollment-tokens -Headers $headers -ContentType application/json -Body (@{expiresAt=[DateTimeOffset]::UtcNow.AddHours(1).ToString('o');maximumUses=1;allowedPlatforms=@('linux');endpointGroupId=$null;policyId=$null}|ConvertTo-Json);docker compose -f deployment/docker-compose.yml --env-file .env run -d --no-deps --name sprint1-integration-agent -e PLATFORM_PROCESS_COLLECTOR=procfs -e PLATFORM_FALCO_JSON_PATH=/data/falco-events.jsonl -e PLATFORM_FALCO_EVENT_PATH=/data/falco-events.jsonl -e PLATFORM_ENROLLMENT_TOKEN_ID=$($created.data.metadata.id) -e PLATFORM_ENROLLMENT_TOKEN_SECRET=$($created.data.secret) agent|Out-Null;1..60|ForEach-Object{$attempt=$_;if($endpoints.data.items.Count -gt 0){return};Start-Sleep 1;try{$candidate=Invoke-RestMethod -Uri http://localhost:8080/api/v1/endpoints?pageSize=2 -Headers $headers;if($candidate.data.items.Count -gt 0){$endpoints=$candidate}}catch{Write-Host "Endpoint projection not ready on attempt $attempt; retrying."}};if($endpoints.data.items.Count -eq 0){Write-Host 'Enrollment agent diagnostics:';docker inspect sprint1-integration-agent --format '{{.State.Status}} exit={{.State.ExitCode}} error={{.State.Error}}';docker logs sprint1-integration-agent}}
Assert ($endpoints.data.items.Count -gt 0) 'tenant endpoint REST/search projection returns data'
$objectId=[guid]::NewGuid();$bytes=[Text.Encoding]::UTF8.GetBytes('sprint-one-minio-acceptance');$sha=[Security.Cryptography.SHA256]::Create();$hash=([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant();$temp=[IO.Path]::GetTempFileName();[IO.File]::WriteAllBytes($temp,$bytes)
try{$meta=Invoke-RestMethod -Method Put -Uri "http://localhost:8080/internal/v1/objects/$objectId" -Headers ($headers+@{'X-Content-SHA256'=$hash}) -ContentType application/octet-stream -InFile $temp;Assert ($meta.sha256 -eq $hash -and $meta.size -eq $bytes.Length) 'MinIO upload metadata and SHA-256 match';$download=[IO.Path]::GetTempFileName();Invoke-WebRequest -Uri "http://localhost:8080/internal/v1/objects/$objectId" -Headers $headers -OutFile $download;Assert ([IO.File]::ReadAllText($download) -eq 'sprint-one-minio-acceptance') 'MinIO download matches uploaded content';Remove-Item -LiteralPath $download -Force}finally{Remove-Item -LiteralPath $temp -Force}
$isolationToken=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/enrollment-tokens -Headers $headers -ContentType application/json -Body (@{expiresAt=[DateTimeOffset]::UtcNow.AddHours(1).ToString('o');maximumUses=1;allowedPlatforms=@('linux');endpointGroupId=$null;policyId=$null}|ConvertTo-Json)
$tenantB=[guid]::NewGuid();docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$tenantB',organization_id,'Integration Tenant B','local','active' from platform.tenants limit 1 on conflict do nothing"|Out-Null;if($LASTEXITCODE-ne 0){throw 'Tenant fixture creation failed'};$tenantBToken=Jwt $tenantB $settings;$tenantBHeaders=@{Authorization="Bearer $tenantBToken"};$isolated=Invoke-RestMethod -Uri http://localhost:8080/api/v1/endpoints?pageSize=100 -Headers $tenantBHeaders
Assert ($isolated.data.items.Count -eq 0) 'OpenSearch and REST endpoint listing enforce tenant isolation'
$isolatedPage=Invoke-RestMethod -Uri http://localhost:8080/api/v1/endpoints?pageSize=1 -Headers $tenantBHeaders
Assert ($isolatedPage.data.items.Count -eq 0) 'paginated endpoint search cannot cross tenant boundaries'
$first=$endpoints.data.items[0].id;$status=0;try{Invoke-RestMethod -Uri "http://localhost:8080/api/v1/endpoints/$first" -Headers $tenantBHeaders|Out-Null;$status=200}catch{$status=[int]$_.Exception.Response.StatusCode};Assert ($status -eq 404) 'cross-tenant endpoint IDOR is denied'
$objectStatus=0;try{Invoke-RestMethod -Uri "http://localhost:8080/internal/v1/objects/$objectId" -Headers $tenantBHeaders|Out-Null;$objectStatus=200}catch{$objectStatus=[int]$_.Exception.Response.StatusCode};Assert ($objectStatus -eq 404) 'cross-tenant MinIO object access is denied'
$tenantBTokens=Invoke-RestMethod -Uri http://localhost:8080/api/v1/enrollment-tokens -Headers $tenantBHeaders
Assert (($tenantBTokens.data.items|Where-Object id -eq $isolationToken.data.metadata.id|Measure-Object).Count -eq 0) 'enrollment tokens are tenant isolated'
Invoke-RestMethod -Method Delete -Uri "http://localhost:8080/internal/v1/objects/$objectId" -Headers $headers|Out-Null
$missing=$false;try{Invoke-RestMethod -Uri "http://localhost:8080/internal/v1/objects/$objectId" -Headers $headers|Out-Null}catch{$missing=$true};Assert $missing 'MinIO delete removes the object'
Write-Host 'Integration acceptance suite passed.'
