$ErrorActionPreference='Stop'
$root=Resolve-Path (Join-Path $PSScriptRoot '../..');Set-Location $root
$settings=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$settings[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function ForeignJwt{$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$head=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$body=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='foreign-tenant';tid=[guid]::NewGuid().ToString('D');per=@('platform:admin');pty='user';iat=$now;exp=$now+600;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$h=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));try{$sig=B64($h.ComputeHash([Text.Encoding]::ASCII.GetBytes($head+'.'+$body)))}finally{$h.Dispose()};"$head.$body.$sig"}
function Status([string]$method,[string]$uri,$headers,$body=$null){try{$a=@{Method=$method;Uri=$uri;Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$a.ContentType='application/json';$a.Body=$body|ConvertTo-Json -Depth 20 -Compress};[int](Invoke-WebRequest @a).StatusCode}catch{[int]$_.Exception.Response.StatusCode}}
$endpoint=node -p "require('./artifacts/sprint21-windows-persistence-response.json').victim.endpointId";$entity=node -p "require('./artifacts/sprint21-windows-persistence-response.json').profiles.A.preview.target.persistenceEntityId";$backup=node -p "require('./artifacts/sprint21-windows-persistence-response.json').profiles.A.remove.result.structuredResult.backupId";$protected=node -p "require('./artifacts/sprint21-windows-persistence-response.json').profiles.E.protectedPreview.target.persistenceEntityId";$foreign=@{Authorization="Bearer $(ForeignJwt)"}
$checks=[ordered]@{}
$checks.authorizedPreview=Status GET "http://127.0.0.1:8080/api/v1/endpoints/$endpoint/persistence/$entity/remediation-preview" $admin
$checks.foreignTenantPreview=Status GET "http://127.0.0.1:8080/api/v1/endpoints/$endpoint/persistence/$entity/remediation-preview" $foreign
$checks.wrongEndpoint=Status GET "http://127.0.0.1:8080/api/v1/endpoints/$([guid]::NewGuid())/persistence/$entity/remediation-preview" $admin
$checks.nameOnlyTarget=Status GET "http://127.0.0.1:8080/api/v1/endpoints/$endpoint/persistence/EventLog/remediation-preview" $admin
$checks.forgedBackup=Status GET "http://127.0.0.1:8080/api/v1/persistence-remediation-backups/$([guid]::NewGuid())" $admin
$checks.foreignBackup=Status GET "http://127.0.0.1:8080/api/v1/persistence-remediation-backups/$backup" $foreign
$checks.restoredBackupReplay=Status POST "http://127.0.0.1:8080/api/v1/persistence-remediation-backups/$($backup):restore" $admin @{reason='replay must fail';expiresInSeconds=300}
$checks.protectedObject=Status POST "http://127.0.0.1:8080/api/v1/endpoints/$endpoint/persistence/$($protected):remediate" $admin @{actionType='service.delete';reason='protected bypass attempt';sourceEntityId=$protected;expiresInSeconds=300}
$checks.genericNameOnly=Status POST 'http://127.0.0.1:8080/api/v1/response-actions' $admin @{endpointId=$endpoint;actionType='service.delete';actionVersion=1;parameters=@{serviceName='EventLog'};reason='name-only forgery';executionTimeoutSeconds=180;expiresInSeconds=300}
$checks.forgedApproval=Status POST "http://127.0.0.1:8080/api/v1/persistence-remediation-actions/$([guid]::NewGuid()):approve" $admin @{parameterHash=('0'*64);reason='forged approval'}
$passed=$checks.authorizedPreview-eq200-and$checks.foreignTenantPreview-eq404-and$checks.wrongEndpoint-eq404-and$checks.nameOnlyTarget-eq400-and$checks.forgedBackup-eq404-and$checks.foreignBackup-eq404-and$checks.restoredBackupReplay-eq409-and$checks.protectedObject-eq409-and$checks.genericNameOnly-eq400-and$checks.forgedApproval-eq404
$report=[ordered]@{schemaVersion='sprint21-api-security.v1';capturedAt=[DateTimeOffset]::UtcNow;checks=$checks;passed=$passed};$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint21-api-security.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(!$passed){exit 1}
