param([string]$Output='artifacts/sprint7-windows-native/module-api-matrix.json')
$ErrorActionPreference='Stop'; Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
$cfg=@{};Get-Content .env|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]}
function B64([byte[]]$b){[Convert]::ToBase64String($b).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt($tenant){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint7-tenant-b';tid=$tenant;per=@('platform:admin');pty='user';iat=$now;exp=$now+3600;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$mac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));"$h.$p.$(B64($mac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$p"))))"}
function Req($method,$uri,$headers,$body=$null){$x=@{Method=$method;Uri=$uri;Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$x.ContentType='application/json';$x.Body=$body|ConvertTo-Json -Depth 15 -Compress};try{$r=Invoke-WebRequest @x;[pscustomobject]@{status=[int]$r.StatusCode;text=$r.Content;headers=$r.Headers}}catch{$s=if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{0};[pscustomobject]@{status=$s;text='';headers=@{}}}}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$a=@{Authorization="Bearer $($login.access_token)"}
$page=(Invoke-RestMethod 'http://localhost:8080/api/v1/module-events?pageSize=100' -Headers $a).data;$event=@($page.items|Where-Object process|Select-Object -First 1)[0];if(!$event){throw'populated module fixture missing'};$endpoint=$event.endpointId
$checks=[ordered]@{};$detail=Req GET "http://localhost:8080/api/v1/module-events/$($event.eventId)" $a;$checks.detail=$detail.status-eq200
$timeline=Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/module-timeline?pageSize=20" $a;$checks.timeline=$timeline.status-eq200-and@((ConvertFrom-Json $timeline.text).data.items).Count-gt0
$health=Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/module-telemetry-health" $a;$checks.health=$health.status-eq200
$processId=[uri]::EscapeDataString([string]$event.process.processEntityId);$history=Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/processes/$processId/modules?pageSize=20" $a;$checks.history=$history.status -eq 200
$sync=Req GET "http://localhost:8080/api/v1/module-events:export?endpointId=$endpoint&limit=100" $a;$checks.syncExport=$sync.status-eq200
$job=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/module-exports -Headers $a -ContentType application/json -Body(@{format='csv';query=@{endpointId=$endpoint};fields=@();maximumRecords=100}|ConvertTo-Json -Depth 8)).data;$limit=[DateTimeOffset]::UtcNow.AddSeconds(45);do{Start-Sleep -Milliseconds 300;$job=(Invoke-RestMethod "http://localhost:8080/api/v1/module-exports/$($job.id)" -Headers $a).data}while($job.state-in@('Pending','Running')-and[DateTimeOffset]::UtcNow-lt$limit);$manifest=Req GET "http://localhost:8080/api/v1/module-exports/$($job.id)/manifest" $a;$signed=(Invoke-RestMethod -Method Post "http://localhost:8080/api/v1/module-exports/$($job.id)/download-url" -Headers $a -ContentType application/json -Body '{"expiresInSeconds":30}').data;$download=Req GET $signed.url @{};$checks.asyncExport=$job.state-eq'Completed'-and$job.recordCount-gt0-and$job.outputSha256-match'^[0-9a-f]{64}$'-and$manifest.status-eq200-and$download.status-eq200
$tenantB=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$tenantB',organization_id,'Sprint7 Tenant B','local','active' from platform.tenants limit 1"|Out-Null;$b=@{Authorization="Bearer $(Jwt $tenantB)"};$bs=Req GET http://localhost:8080/api/v1/module-events $b;$bd=Req GET "http://localhost:8080/api/v1/module-events/$($event.eventId)" $b;$be=Req GET "http://localhost:8080/api/v1/module-exports/$($job.id)/content" $b;$checks.tenantIsolation=$bs.status-eq200-and@((ConvertFrom-Json $bs.text).data.items).Count-eq0-and$bd.status-eq404-and$be.status-eq404
$failed=@($checks.GetEnumerator()|Where-Object{-not$_.Value});$report=[ordered]@{schema='platform.sprint7.module-api-matrix.v1';executedAt=[DateTimeOffset]::UtcNow;endpointId=$endpoint;eventId=$event.eventId;exportId=$job.id;tenantB=$tenantB;checks=$checks;passed=$failed.Count-eq0};$report|ConvertTo-Json -Depth 10|Set-Content $Output;$report|ConvertTo-Json -Depth 6;if($failed.Count){exit 1}
