param([string]$BaseUrl='http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')};function Jwt([string]$tid){$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint29-test';tid=$tid;per=@('platform:admin','system:admin');pty='user';iat=$n;exp=$n+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};"$h.$b.$s"}
$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"};$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;$other=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$other',organization_id,'Sprint29 fairness tenant','local','active' from platform.tenants limit 1 on conflict do nothing"|Out-Null;$foreign=@{Authorization="Bearer $(Jwt $other)"}
$quota=@{ingestPerMinute=10;searchPerMinute=2;replayPerMinute=2;exportPerMinute=2;forensicPerMinute=2;playbookPerMinute=2;updatePerMinute=2;maxConcurrentForensic=1;maxConcurrentPlaybooks=1};$null=Invoke-RestMethod -Method Put "$BaseUrl/api/v1/capacity/quota" -Headers $admin -ContentType application/json -Body($quota|ConvertTo-Json)
$codes=@();1..4|ForEach-Object{try{$codes+=(Invoke-WebRequest "$BaseUrl/api/v1/capacity/storage" -Headers $admin -UseBasicParsing).StatusCode}catch{$codes+=[int]$_.Exception.Response.StatusCode}}
$foreignCode=(Invoke-WebRequest "$BaseUrl/api/v1/capacity/storage" -Headers $foreign -UseBasicParsing).StatusCode
$self=(Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/capacity-retention/self-test" -Headers $foreign).data
$policy=$self.policy
$wrongScope=try{$null=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/retention/previews" -Headers $foreign -ContentType application/json -Body(@{policyId=$policy.policyId;scope='all-production-data'}|ConvertTo-Json);false}catch{$true}
$overflow=try{$null=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/capacity/estimate" -Headers $foreign -ContentType application/json -Body(@{endpointCount=10000001;eventsPerEndpointDay=1;retentionDays=1;postgreSqlBytesPerEvent=1;openSearchBytesPerEvent=1;forensicBytesPerEndpointDay=0;redundancyFactor=1;requiredMarginPercent=0}|ConvertTo-Json);false}catch{$true}
$report=[ordered]@{schemaVersion='sprint29-security-fairness.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');tenantA=[ordered]@{responses=$codes;throttled=@($codes|Where-Object{$_-eq429}).Count-ge2};tenantB=[ordered]@{response=$foreignCode;notStarved=$foreignCode-eq200;isolatedPolicyTenant=$policy.tenantId-eq$other};security=[ordered]@{holdBypassRejected=$self.heldPreserved;productionScopeRejected=$wrongScope;forecastOverflowRejected=$overflow;previewHashBound=$self.passed;boundedBatch=$self.applied.deletedRows-le100;tenantEscape=$policy.tenantId-eq$other};passed=@($codes|Where-Object{$_-eq429}).Count-ge2-and$foreignCode-eq200-and$self.passed-and$wrongScope-and$overflow-and$policy.tenantId-eq$other}
$default=@{ingestPerMinute=120000;searchPerMinute=6000;replayPerMinute=60;exportPerMinute=300;forensicPerMinute=6000;playbookPerMinute=300;updatePerMinute=300;maxConcurrentForensic=4;maxConcurrentPlaybooks=8};$null=Invoke-RestMethod -Method Put "$BaseUrl/api/v1/capacity/quota" -Headers $admin -ContentType application/json -Body($default|ConvertTo-Json)
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint29-security-fairness.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 29 fairness/security validation failed.'}
