param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$domains=[ordered]@{process=@('platform.process_entities','platform-processes');file=@('platform.file_entities','platform-files');registry=@('platform.registry_events','platform-registry-events');network=@('platform.network_events','platform-network-events');dns=@('platform.dns_events','platform-dns-events');module=@('platform.module_events','platform-module-events');persistence=@('platform.persistence_events','platform-persistence-events');identity=@('platform.identity_events','platform-identity-events');execution=@('platform.execution_events','platform-execution-events');detection=@('platform.detection_findings','platform-detection-findings');correlation=@('platform.correlated_findings','platform-correlated-findings');indicators=@('platform.threat_indicators','platform-threat-indicators-v1');iocMatches=@('platform.threat_matches','platform-ioc-matches-v1');tunnelObservations=@('platform.tunnel_observations','platform-tunnel-observations');tunnelFindings=@('platform.tunnel_findings','platform-tunnel-findings')}
function Sql($query){(docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $query).Trim()}
function Os($index){[long]((docker exec deployment-opensearch-1 curl -sf "http://localhost:9200/$index/_count"|ConvertFrom-Json).count)}
$postgres=[ordered]@{};$openSearch=[ordered]@{};$differences=[ordered]@{};foreach($name in $domains.Keys){$postgres[$name]=[long](Sql "select count(*) from $($domains[$name][0]);");$openSearch[$name]=Os $domains[$name][1];$differences[$name]=$postgres[$name]-$openSearch[$name]}
$credential=Import-Clixml -LiteralPath $CredentialPath;$session=New-PSSession -VMName $VictimVmName -Credential $credential;try{$queues=Invoke-Command -Session $session -ScriptBlock{$roots=@('C:\Sprint22Qualification\runtime-data','C:\Sprint24Qualification\runtime-data');$value=[ordered]@{};foreach($root in $roots){foreach($name in 'process','file','registry','network','dns','module','persistence','identity','execution'){$path=Join-Path $root "$name-queue";$value["$([IO.Path]::GetFileName([IO.Path]::GetDirectoryName($root)))-$name"]=if(Test-Path $path){@(Get-ChildItem $path -File -Filter '*.json').Count}else{0}}};[pscustomobject]$value}}finally{Remove-PSSession $session}
$queueTotal=[long](($queues.psobject.Properties|Where-Object{$_.Name-notlike'PS*'-and$_.Name-ne'RunspaceId'}|ForEach-Object{[long]$_.Value}|Measure-Object -Sum).Sum)
$transport=(Sql "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Split('|')|ForEach-Object{[long]$_};$work=(Sql "select (select count(*) from platform.response_actions where state not in ('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected'))||'|'||(select count(*) from platform.playbook_work where state='pending');").Split('|')|ForEach-Object{[long]$_};$js=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($js.account_details.stream_detail.consumer_detail);$pending=[long](($consumers|Measure-Object num_pending -Sum).Sum);$ack=[long](($consumers|Measure-Object num_ack_pending -Sum).Sum);$redelivery=[long](($consumers|Measure-Object num_redelivered -Sum).Sum)
$report=[ordered]@{schemaVersion='sprint26-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');postgres=$postgres;openSearch=$openSearch;differences=$differences;victimQueues=$queues;queueTotal=$queueTotal;responseNonterminal=$work[0];orchestrationPending=$work[1];outbox=[ordered]@{pending=$transport[0];failed=$transport[1]};nats=[ordered]@{pending=$pending;ackPending=$ack;redelivered=$redelivery};passed=@($differences.Values|Where-Object{$_-ne0}).Count-eq0-and$queueTotal-eq0-and$work[0]-eq0-and$work[1]-eq0-and$transport[0]-eq0-and$transport[1]-eq0-and$pending-eq0-and$ack-eq0}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint26-final-reconciliation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){exit 1}
