$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
powershell.exe -NoProfile -ExecutionPolicy Bypass -File testing/integration/sprint14-final-reconciliation.ps1|Out-Host
$prior=Get-Content -Raw artifacts/sprint14-final-reconciliation.json|ConvertFrom-Json
function Sql([string]$q){(docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $q).Trim()}
$a=(Sql "select count(*)||'|'||count(distinct (tenant_id,alert_id))||'|'||count(*) filter(where jsonb_array_length(alert_data->'sourceFindingHistory')=0)||'|'||count(*) filter(where jsonb_array_length(alert_data->'evidence'->'evidenceReferences')=0)||'|'||count(*) filter(where alert_version<>(alert_data->>'version')::int) from platform.alerts;").Split('|')|ForEach-Object{[long]$_}
$i=(Sql "select count(*)||'|'||count(distinct (tenant_id,incident_id))||'|'||count(*) filter(where cardinality(alert_ids)=0)||'|'||count(*) filter(where jsonb_array_length(incident_data->'evidenceReferences')=0)||'|'||count(*) filter(where incident_version<>(incident_data->>'version')::int)||'|'||(select count(*) from platform.triage_incidents i cross join unnest(i.alert_ids) aid where not exists(select 1 from platform.alerts a where a.tenant_id=i.tenant_id and a.alert_id=aid)) from platform.triage_incidents;").Split('|')|ForEach-Object{[long]$_}
$u=(Sql "select (select count(*) from platform.lifecycle_audit)||'|'||(select count(distinct (tenant_id,audit_id)) from platform.lifecycle_audit)||'|'||(select count(*)-count(distinct (tenant_id,object_type,object_id,object_version,action)) from platform.lifecycle_audit)||'|'||(select count(*) from platform.analyst_notes)||'|'||(select count(distinct (tenant_id,note_id)) from platform.analyst_notes)||'|'||(select count(*) from platform.analyst_notes n where not exists(select 1 from platform.lifecycle_audit a where a.tenant_id=n.tenant_id and a.audit_id=n.audit_id))||'|'||(select count(*) from platform.lifecycle_audit a where a.object_type='alert' and not exists(select 1 from platform.alerts x where x.tenant_id=a.tenant_id and x.alert_id=a.object_id))||'|'||(select count(*) from platform.lifecycle_audit a where a.object_type='incident' and not exists(select 1 from platform.triage_incidents x where x.tenant_id=a.tenant_id and x.incident_id=a.object_id));").Split('|')|ForEach-Object{[long]$_}
$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$streams=@($nats.account_details|ForEach-Object{$_.stream_detail}|Where-Object{$_});$pending=[long](($streams|ForEach-Object{$_.consumer_detail|ForEach-Object{$_.num_pending}}|Measure-Object -Sum).Sum);$ack=[long](($streams|ForEach-Object{$_.consumer_detail|ForEach-Object{$_.num_ack_pending}}|Measure-Object -Sum).Sum)
$outbox=(Sql "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Split('|')|ForEach-Object{[long]$_}
$report=[ordered]@{schemaVersion='sprint15-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');prior=$prior;alerts=[ordered]@{postgres=$a[0];unique=$a[1];duplicates=$a[0]-$a[1];withoutSourceHistory=$a[2];withoutEvidence=$a[3];snapshotVersionMismatch=$a[4]};incidents=[ordered]@{postgres=$i[0];unique=$i[1];duplicates=$i[0]-$i[1];withoutAlerts=$i[2];withoutEvidence=$i[3];snapshotVersionMismatch=$i[4];missingAlertReferences=$i[5]};audit=[ordered]@{events=$u[0];uniqueEvents=$u[1];duplicateObjectVersions=$u[2];notes=$u[3];uniqueNotes=$u[4];notesWithoutAudit=$u[5];missingAlertObjects=$u[6];missingIncidentObjects=$u[7]};outbox=[ordered]@{pending=$outbox[0];failed=$outbox[1]};nats=[ordered]@{pending=$pending;ackPending=$ack};passed=($prior.passed-and$a[0]-eq$a[1]-and$a[2]-eq0-and$a[3]-eq0-and$a[4]-eq0-and$i[0]-eq$i[1]-and$i[2]-eq0-and$i[3]-eq0-and$i[4]-eq0-and$i[5]-eq0-and$u[0]-eq$u[1]-and$u[2]-eq0-and$u[3]-eq$u[4]-and$u[5]-eq0-and$u[6]-eq0-and$u[7]-eq0-and$outbox[0]-eq0-and$outbox[1]-eq0-and$pending-eq0-and$ack-eq0)}
$report|ConvertTo-Json -Depth 40|Set-Content artifacts/sprint15-final-reconciliation.json -Encoding utf8
$nats|ConvertTo-Json -Depth 40|Set-Content artifacts/sprint15-nats-jsz.json -Encoding utf8
$report|ConvertTo-Json -Depth 40
if(-not$report.passed){throw 'Sprint 15 final reconciliation failed.'}
