param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
& (Join-Path $PSScriptRoot 'sprint32-final-reconciliation.ps1') -VictimVmName $VictimVmName -CredentialPath $CredentialPath|Out-Null
$base=Get-Content artifacts/sprint32-final-reconciliation.json -Raw|ConvertFrom-Json
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$token=(Invoke-RestMethod -Method Post 'http://127.0.0.1:8080/api/v1/auth/token' -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress)).access_token;$h=@{Authorization="Bearer $token"}
$stateA=(Invoke-RestMethod 'http://127.0.0.1:8080/api/v1/admin/configurations' -Headers $h).data;$stateB=(Invoke-RestMethod 'http://127.0.0.1:8081/api/v1/admin/configurations' -Headers $h).data;$health=(Invoke-RestMethod 'http://127.0.0.1:8080/api/v1/admin/overview' -Headers $h).data;$campaign=(Invoke-RestMethod 'http://127.0.0.1:8080/api/v1/admin/permissions/routes' -Headers $h).data
$sql="select json_build_object('states',(select count(*) from platform.administration_states),'credentials',(select count(*) from platform.administration_api_credentials),'active_credentials',(select count(*) from platform.administration_api_credentials where revoked_at is null and expires_at>now()),'audit',(select count(*) from platform.administration_audit),'rls_tables',(select count(*) from pg_tables where schemaname='platform' and tablename like 'administration_%' and rowsecurity),'plaintext_secrets',(select count(*) from platform.administration_api_credentials where secret_hash not like 'pbkdf2-sha512`$%'))::text"
$admin=docker exec deployment-postgres-1 psql -U platform -d platform -tAc $sql|ConvertFrom-Json
$profiles=Get-Content artifacts/sprint33-administration-profiles.json -Raw|ConvertFrom-Json
$report=[ordered]@{schemaVersion='sprint33-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');postgres=$base.postgres;openSearch=$base.openSearch;differences=$base.differences;administration=[ordered]@{database=$admin;health=$health;gatewayStateEqual=(($stateA|ConvertTo-Json -Compress -Depth 30)-eq($stateB|ConvertTo-Json -Compress -Depth 30));permissionRoutes=$campaign.routes.Count;permissionGaps=$campaign.sensitiveWithoutExplicitPermission;profilesPassed=$profiles.passed};victimQueues=$base.victimQueues;queueTotal=$base.queueTotal;outbox=$base.outbox;nats=$base.nats;passed=$base.passed-and$profiles.passed-and$campaign.passed-and$admin.states-ge1-and$admin.credentials-ge1-and$admin.audit-ge1-and$admin.rls_tables-eq3-and$admin.plaintext_secrets-eq0-and(($stateA|ConvertTo-Json -Compress -Depth 30)-eq($stateB|ConvertTo-Json -Compress -Depth 30))}
$report|ConvertTo-Json -Depth 40|Set-Content artifacts/sprint33-final-reconciliation.json;$report|ConvertTo-Json -Depth 40;if(-not$report.passed){throw 'Sprint 33 final reconciliation failed.'}
