param([string]$BaseUrl = 'http://localhost:8080')
$ErrorActionPreference = 'Stop'
$config = @{}
Get-Content (Join-Path $PSScriptRoot '..\..\.env') | ForEach-Object { if ($_ -match '^([^#=]+)=(.*)$') { $config[$matches[1]] = $matches[2] } }
$login = @{ username=$config.PLATFORM_BOOTSTRAP_USER; password=$config.PLATFORM_BOOTSTRAP_PASSWORD; tenantId=$config.PLATFORM_BOOTSTRAP_TENANT_ID } | ConvertTo-Json
$token = (Invoke-RestMethod "$BaseUrl/api/v1/auth/token" -Method Post -ContentType application/json -Body $login).access_token
$headers = @{ Authorization="Bearer $token" }
$tenant = $config.PLATFORM_BOOTSTRAP_TENANT_ID
function Call([string]$path,[string]$method='Get',$body=$null) { $parameters=@{Uri="$BaseUrl$path";Method=$method;Headers=$headers};if($null-ne$body){$parameters.ContentType='application/json';$parameters.Body=($body|ConvertTo-Json -Depth 12 -Compress)};(Invoke-RestMethod @parameters).data }
function Event([string]$domain,[hashtable]$fields,[guid]$endpoint,[datetime]$at,[guid]$id=[guid]::NewGuid()) { @{eventId=$id;tenantId=$tenant;domain=$domain;eventTime=$at.ToUniversalTime().ToString('o');endpointId=$endpoint;processEntityId='fixture-process';entityId='fixture-entity';fields=$fields;evidenceReference="postgresql://platform/sprint12_fixture_events/$id";late=$false;incomplete=$false;missingTelemetry=@();quality=@('complete')} }
function Live($event) { Call '/internal/v1/detection-events:evaluate' 'Post' @{event=$event;productionFindings=$true} }
$null=Call '/internal/v1/detection-starter-fixtures:seed' 'Post' @{}
$rules=@(Call '/api/v1/detection-rules');if($rules.Count-lt9){throw "Expected at least the 9 Sprint 12 starter rules; found $($rules.Count)."}
$processRule=$rules|Where-Object{$_.domain-eq'Process'}|Select-Object -First 1
$identityRule=$rules|Where-Object{$_.domain-eq'Identity'}|Select-Object -First 1
$now=(Get-Date).ToUniversalTime();$endpointA=[guid]::NewGuid()
$aEvent=Event 'Process' @{path='C:\Sprint12Fixtures\profile-a.exe';processName='profile-a.exe';endpointId=$endpointA.ToString()} $endpointA $now
$a=Live $aEvent;if(-not$a.finding-or$a.finding.eventCount-ne1){throw'Profile A did not create exactly one finding.'}
$b=Live (Event 'Process' @{path='C:\Windows\System32\notepad.exe';processName='notepad.exe';endpointId=([guid]::NewGuid()).ToString()} ([guid]::NewGuid()) $now.AddSeconds(1));if($b.finding){throw'Profile B negative control created a finding.'}
$endpointC=[guid]::NewGuid();$userC="sprint12-profile-c-$([guid]::NewGuid().ToString('N'))";$cResults=@();1..3|ForEach-Object{$cResults+=Live (Event 'Identity' @{status='failed';user=$userC;endpointId=$endpointC.ToString()} $endpointC $now.AddSeconds(10+$_))};if(@($cResults|Where-Object{$_.finding}).Count-ne1-or-not$cResults[2].finding){throw'Profile C did not cross threshold exactly once.'}
$excluded=Live (Event 'Process' @{path='C:\Sprint12Fixtures\excluded.exe';processName='excluded.exe';endpointId=([guid]::NewGuid()).ToString()} ([guid]::NewGuid()) $now.AddSeconds(20));if(-not$excluded.excluded-or$excluded.finding){throw'Profile D exclusion failed.'}
$suppressed=Live (Event 'Process' @{path='C:\Sprint12Fixtures\profile-a-second.exe';processName='profile-a-second.exe';endpointId=$endpointA.ToString()} $endpointA $now.AddSeconds(21));if(-not$suppressed.suppressed-or-not$suppressed.finding){throw'Profile D suppression failed.'}
$endpointE=[guid]::NewGuid();$eventE=Event 'Process' @{path='C:\Sprint12Fixtures\replay.exe';processName='replay.exe';endpointId=$endpointE.ToString()} $endpointE $now.AddSeconds(30);$replayBody=@{detectionId=$processRule.detectionId;version=1;from=$now.AddMinutes(-1).ToString('o');to=$now.AddMinutes(2).ToString('o');productionFindings=$false;controlledFixtureEvents=@($eventE)};$e1=Call '/api/v1/detection-replays' 'Post' $replayBody;$e2=Call '/api/v1/detection-replays' 'Post' $replayBody;if($e1.run.eventsEvaluated-ne1-or$e1.run.findings-ne1-or$e2.run.eventsEvaluated-ne1-or$e2.run.findings-ne1-or$e1.resultFindingIds[0]-ne$e2.resultFindingIds[0]){throw'Profile E replay was not deterministic.'}
$endpointF=[guid]::NewGuid();$userF="sprint12-profile-f-$([guid]::NewGuid().ToString('N'))";$f1=Live (Event 'Identity' @{status='failed';user=$userF;endpointId=$endpointF.ToString()} $endpointF $now.AddSeconds(40));$f2=Live (Event 'Identity' @{status='failed';user=$userF;endpointId=$endpointF.ToString()} $endpointF $now.AddSeconds(41));if($f1.finding-or$f2.finding){throw'Profile F threshold fired before restart.'};docker restart deployment-gateway-1|Out-Null;$ready=$false;1..30|ForEach-Object{if(-not$ready){Start-Sleep -Seconds 1;try{$ready=(Invoke-RestMethod "$BaseUrl/health/ready" -TimeoutSec 3).status-eq'ready'}catch{}}};if(-not$ready){throw'Gateway failed to become ready after restart.'};$fEvent=Event 'Identity' @{status='failed';user=$userF;endpointId=$endpointF.ToString()} $endpointF $now.AddSeconds(42);$f3=Live $fEvent;$fDuplicate=Live $fEvent;if(-not$f3.finding-or-not$fDuplicate.duplicate){throw'Profile F restart state or duplicate safety failed.'};$processStatus=Invoke-WebRequest "$BaseUrl/api/v1/processes?pageSize=1" -Headers $headers -UseBasicParsing;if($processStatus.StatusCode-ne200){throw'Existing telemetry API stalled during Profile F.'}
$findingPage=Call '/api/v1/findings?pageSize=500';$result=[ordered]@{schemaVersion='sprint12-profiles.v1';completedAt=(Get-Date).ToUniversalTime().ToString('o');profileA=@{status='PASS';findingId=$a.finding.findingId};profileB=@{status='PASS';findings=0};profileC=@{status='PASS';events=3;findings=1};profileD=@{status='PASS';excluded=$true;suppressed=$true;evidencePreserved=($suppressed.finding.evidenceReferences.Count-gt0)};profileE=@{status='PASS';eventsEach=1;findingsEach=1;deterministicFindingId=$e1.resultFindingIds[0]};profileF=@{status='PASS';restart='gateway';stateSurvived=$true;duplicateSafe=$true;telemetryApiStatus=200};productionFindingCount=@($findingPage.items).Count}
$artifact=Join-Path $PSScriptRoot '..\..\artifacts\sprint12-profiles.json';$result|ConvertTo-Json -Depth 8|Set-Content $artifact -Encoding utf8
$result|ConvertTo-Json -Depth 8
