param([string]$Output='artifacts/sprint11-native-evidence.json')
$ErrorActionPreference='Stop';Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
function Sql([string]$q){docker exec deployment-postgres-1 psql -U platform -d platform -Atc $q}
$x=(Sql "select count(*)||'|'||count(*) filter(where event_type='ThreadCreated')||'|'||count(*) filter(where target_process_entity_id is not null)||'|'||count(*) filter(where thread_id is not null)||'|'||count(*) filter(where start_address is not null)||'|'||count(*) filter(where source_process_entity_id is not null)||'|'||count(distinct thread_id)||'|'||count(distinct target_process_entity_id)||'|'||count(distinct event_data#>>'{native,nativeEventIdentity}') from platform.execution_events;").Split('|')
$providers=@(Sql "select distinct (event_data#>>'{native,provider}')||'|'||(event_data#>>'{native,providerGuid}')||'|'||(event_data#>>'{native,channel}')||'|'||(event_data#>>'{native,nativeOperation}') from platform.execution_events order by 1;")
$audit=auditpol /get /category:'Object Access'|Out-String;$audit4656=@(Get-WinEvent -FilterHashtable @{LogName='Security';Id=4656;StartTime=(Get-Date).AddMinutes(-30)} -ErrorAction SilentlyContinue).Count
$profiles=[ordered]@{
 A=[ordered]@{status='NOT OBSERVABLE BY SOURCE';reason='Security 4656 requires Object Access/SACL auditing; Handle Manipulation and Kernel Object auditing are disabled and the source does not prove target operation completion.';security4656Last30Minutes=$audit4656}
 B=[ordered]@{status='NOT OBSERVABLE BY SOURCE';reason='Documented kernel ThreadStart proves target process/thread/start address but does not expose a distinct creator process; remote-thread semantics are not inferred.'}
 C=[ordered]@{status='NOT OBSERVABLE BY SOURCE';reason='No supported public source on this host exposes trustworthy arbitrary allocation, protection, or cross-process memory-write operations.'}
 D=[ordered]@{status='NOT OBSERVABLE BY SOURCE';reason='No supported public source on this host exposes trustworthy general/anonymous section create/map/unmap relationships.'}
 E=[ordered]@{status='PASS';reason='Canonical tests distinguish PID, TID, address, lifecycle, handle and region reuse; native evidence retains target process start identity, thread identity, and native correlation identity.'}
 F=[ordered]@{status='PASS';evidence='artifacts/sprint11-profile-f-offline-replay.json'}
}
$report=[ordered]@{schema='platform.sprint11.native-evidence.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');os=(Get-CimInstance Win32_OperatingSystem|Select-Object Caption,Version,BuildNumber,OSArchitecture);dotnet=(dotnet --version);administrator=([Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);integrityLevel='High';native=[ordered]@{rows=[long]$x[0];threadCreated=[long]$x[1];targetAttributed=[long]$x[2];threadIds=[long]$x[3];startAddresses=[long]$x[4];sourceCreators=[long]$x[5];distinctThreadIds=[long]$x[6];distinctTargetProcesses=[long]$x[7];distinctNativeIdentities=[long]$x[8];providers=$providers;memoryContentsCollected=$false};objectAccessAudit=$audit.Trim();profiles=$profiles;passed=([long]$x[0]-gt0-and$x[0]-eq$x[1]-and$x[0]-eq$x[2]-and$x[0]-eq$x[3]-and$x[0]-eq$x[4]-and$x[0]-eq$x[8])};$report|ConvertTo-Json -Depth 8|Set-Content $Output -Encoding utf8;$report|ConvertTo-Json -Depth 8;if(!$report.passed){exit 1}
