[CmdletBinding()]
param(
    [string] $VictimVmName = 'XDR-Victim-Sprint18',
    [string] $CredentialPath = 'D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',
    [string] $QualificationRoot = 'C:\Sprint22Qualification',
    [string] $FixtureRoot = 'C:\Sprint22Fixtures',
    [int] $TimeoutSeconds = 300
)
$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '../..'); Set-Location $root
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not [Security.Principal.WindowsPrincipal]::new($identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Elevated host token required.' }
if ((Get-VM -Name $VictimVmName).State -ne 'Running') { throw 'Existing victim VM must be running.' }
if ((docker ps --filter 'name=falco' --format '{{.Names}}') -or (docker ps --filter 'name=deployment-agent' --format '{{.Names}}')) { throw 'Falco and the Docker demo agent must remain stopped.' }
$settings=@{}; Get-Content .env|Where-Object{$_-match '^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$settings[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress)
$admin=@{Authorization="Bearer $($login.access_token)"}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt([string]$subject){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub=$subject;tid=$settings.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('platform:admin');pty='user';iat=$now;exp=$now+7200;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$mac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($mac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$mac.Dispose()};@{Authorization="Bearer $h.$b.$s"}}
$approver=Jwt 'sprint22-separated-approver'
function Api([string]$method,[string]$path,$headers=$admin,$body=$null){$a=@{Method=$method;Uri="http://127.0.0.1:8080$path";Headers=$headers;DisableKeepAlive=$true};if($null-ne$body){$a.ContentType='application/json';$a.Body=[Text.Encoding]::UTF8.GetBytes(($body|ConvertTo-Json -Depth 80 -Compress))};try{(Invoke-RestMethod @a).data}catch{$d='';try{$r=[IO.StreamReader]::new($_.Exception.Response.GetResponseStream());$d=$r.ReadToEnd();$r.Dispose()}catch{};throw "$method $path failed: $d"}}
function Session{$credential=Import-Clixml -LiteralPath $CredentialPath;$deadline=[DateTimeOffset]::UtcNow.AddMinutes(3);do{try{return New-PSSession -VMName $VictimVmName -Credential $credential -ErrorAction Stop}catch{Start-Sleep 2}}while([DateTimeOffset]::UtcNow-lt$deadline);throw 'PowerShell Direct unavailable.'}
function Victim([scriptblock]$script,[object[]]$arguments=@()){$s=Session;try{Invoke-Command -Session $s -ScriptBlock $script -ArgumentList $arguments}finally{Remove-PSSession $s}}
function Stop-Agent{Victim{Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;Start-Sleep 1}|Out-Null}
$script:token=Api POST '/api/v1/enrollment-tokens' $admin @{expiresAt=[DateTimeOffset]::UtcNow.AddHours(3).ToString('o');maximumUses=1;allowedPlatforms=@('windows')}
function Start-Agent{Victim{param($q,$id,$secret)Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;Start-Sleep 1;$env:PLATFORM_CONTROL_PLANE_URL='https://gateway:8443';$env:PLATFORM_ENROLLMENT_TOKEN_ID=$id;$env:PLATFORM_ENROLLMENT_TOKEN_SECRET=$secret;$env:PLATFORM_AGENT_DATA="$q\runtime-data";$env:PLATFORM_CA_CERT_PATH='C:\Sprint19Qualification\ca.crt';$env:PLATFORM_ENVIRONMENT='production';(Start-Process "$q\agent\Platform.Agent.exe" -PassThru -WindowStyle Hidden -RedirectStandardOutput "$q\agent.log" -RedirectStandardError "$q\agent-error.log").Id}@($QualificationRoot,$script:token.metadata.id,$script:token.secret)}
function Wait-Collection([guid]$id){$deadline=[DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 400;$x=Api GET "/api/v1/forensic-collections/$id"}while($x.state-notin@('Succeeded','Partial','Failed','Cancelled','CancelledWithEvidence','Expired')-and[DateTimeOffset]::UtcNow-lt$deadline);$x}
function Create-Collection([guid]$endpoint,[string]$profile,[object[]]$artifacts,[string]$reason,[bool]$approve=$true){$x=Api POST '/api/v1/forensic-collections' $admin @{endpointId=$endpoint;profileId=$profile;profileVersion=1;requestedArtifacts=$artifacts;reason=$reason;expiresInSeconds=900;saveAsDraft=$false;policyVersion='forensic-collection-policy.v1'};if($approve-and$x.approvalState-eq'Pending'){$x=Api POST "/api/v1/forensic-collections/$($x.collectionId):approve" $approver @{parameterHash=$x.parameterHash;reason='Separated review of exact immutable Sprint 22 scope'}};$x}
function Find-File([guid]$endpoint,[string]$path){$deadline=[DateTimeOffset]::UtcNow.AddSeconds(150);do{Start-Sleep 1;$f=(Api GET "/api/v1/files?endpointId=$endpoint&pageSize=200").items|Where-Object{$_.currentPath-eq$path-and$_.state-ne'Deleted'}|Sort-Object lastObserved -Descending|Select-Object -First 1}while(!$f-and[DateTimeOffset]::UtcNow-lt$deadline);if(!$f){throw "File entity not observed: $path"};$f}
function File-Artifact([string]$id,$file){@{requestId=$id;artifactType='File';fileTarget=@{fileEntityId=$file.fileEntityId;nativeIdentity=$file.nativeIdentity;canonicalPath=$file.currentPath;expectedSize=$file.metadata.size;expectedSha256=$file.hash.sha256;observedAt=$file.lastObserved};maximumItems=1;maximumBytes=[long]$file.metadata.size;maximumDepth=0;maximumRecords=0;lookbackMinutes=0;includeHidden=$false;metadataOnly=$false}}

$native=Victim{param($root)New-Item -ItemType Directory -Path $root -Force|Out-Null;New-Item -Path 'HKLM:\SOFTWARE\OpenSecurityPlatform\Sprint22' -Force|Out-Null;New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSecurityPlatform\Sprint22' -Name 'ControlledValue' -Value 'SENSITIVE-CONTENT-MUST-NOT-APPEAR' -PropertyType String -Force|Out-Null;$dotnet=if(Test-Path "$env:ProgramFiles\dotnet\dotnet.exe"){& "$env:ProgramFiles\dotnet\dotnet.exe" --version}else{'self-contained-agent'};[pscustomobject]@{Os=(Get-CimInstance Win32_OperatingSystem).Caption;Build=(Get-CimInstance Win32_OperatingSystem).BuildNumber;Architecture=$env:PROCESSOR_ARCHITECTURE;DotNet=$dotnet;Administrator=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);Integrity=(whoami /groups|Select-String 'Mandatory Label').Line}}@($FixtureRoot)
$started=[DateTimeOffset]::UtcNow;$agentPid=Start-Agent;$deadline=[DateTimeOffset]::UtcNow.AddSeconds(150);do{Start-Sleep 2;$endpoint=(Api GET '/api/v1/endpoints?pageSize=100').items|Where-Object{$_.platform-eq'windows'-and$_.lastSeenAt-and[DateTimeOffset]$_.lastSeenAt-ge$started}|Sort-Object lastSeenAt -Descending|Select-Object -First 1}while(!$endpoint-and[DateTimeOffset]::UtcNow-lt$deadline);if(!$endpoint){throw 'Victim agent did not enroll.'}
$effective=Api GET "/api/v1/endpoints/$($endpoint.id)/file-policy";$policy=$effective.policy.policy;$policy.includedPaths=@("$FixtureRoot\");$policy.excludedPaths=@();$policy.hashingEnabled=$true;$policy.maximumHashBytes=8388608;$policy.maximumBatchEvents=1000;$policy.maximumBatchBytes=4194304;$policy.flushSeconds=1;$created=Api POST '/api/v1/file-telemetry/policies' $admin @{name="sprint22-bounded-$([guid]::NewGuid().ToString('N'))";policy=$policy};Api POST "/api/v1/file-telemetry/policies/$($created.id):assign" $admin @{endpointId=$endpoint.id}|Out-Null;Stop-Agent;$agentPid=Start-Agent;Start-Sleep 12

$quick=@(@{requestId='system';artifactType='SystemInformation';maximumItems=1;maximumBytes=262144},@{requestId='processes';artifactType='ProcessInventory';maximumItems=32;maximumBytes=524288},@{requestId='users';artifactType='UserSessionInventory';maximumItems=32;maximumBytes=262144},@{requestId='services';artifactType='ServiceInventory';maximumItems=32;maximumBytes=524288},@{requestId='tasks';artifactType='ScheduledTaskInventory';maximumItems=32;maximumBytes=524288},@{requestId='network';artifactType='NetworkState';maximumItems=32;maximumBytes=524288})
$a=Wait-Collection (Create-Collection $endpoint.id 'quick-triage' $quick 'Profile A deterministic structured quick triage').collectionId
$profileA=$a.state-eq'Succeeded'-and$a.result.items.Count-eq6-and$a.result.items.Where({!$_.sha256}).Count-eq0

$events=@(@{requestId='system-evtx';artifactType='WindowsEventLog';source='System';maximumItems=1;maximumBytes=4194304;maximumRecords=1000;lookbackMinutes=1440;maximumDepth=0;includeHidden=$false;metadataOnly=$false})
$b=Wait-Collection (Create-Collection $endpoint.id 'windows-event-evidence' $events 'Profile B bounded native EVTX evidence').collectionId
$profileB=$b.state-eq'Succeeded'-and$b.result.items[0].sourceObject-eq'System'-and$b.result.items[0].sha256-and$b.result.manifestHash

$registry=@(@{requestId='controlled-registry';artifactType='Registry';source='HKLM\SOFTWARE\OpenSecurityPlatform\Sprint22';maximumDepth=2;maximumItems=32;maximumBytes=1048576;maximumRecords=0;lookbackMinutes=0;includeHidden=$false;metadataOnly=$true})
$c=Wait-Collection (Create-Collection $endpoint.id 'registry-triage' $registry 'Profile C controlled metadata-only Registry evidence').collectionId
$regItem=$c.result.items[0];$regContentPath='artifacts/sprint22-registry-evidence.json';Invoke-WebRequest -Uri "http://127.0.0.1:8080/api/v1/forensic-collections/$($c.collectionId)/items/$($regItem.evidenceItemId)/content" -Headers $admin -OutFile $regContentPath -UseBasicParsing;$regText=Get-Content $regContentPath -Raw
$profileC=$c.state-eq'Succeeded'-and$regText-notmatch'SENSITIVE-CONTENT-MUST-NOT-APPEAR'-and$regText-match'\[REDACTED\]'

$tag=[guid]::NewGuid().ToString('N');$stable="$FixtureRoot\stable-$tag.bin";$unicode="$FixtureRoot\evidence-$([char]0x0394)-$tag.txt";$changing="$FixtureRoot\changing-$tag.bin";Victim{param($root,$a,$b,$c)New-Item -ItemType Directory -Path $root -Force|Out-Null;[IO.File]::WriteAllBytes($a,[Text.Encoding]::UTF8.GetBytes('stable-forensic-evidence'));[IO.File]::WriteAllText($b,'unicode-forensic-evidence',[Text.UTF8Encoding]::new($false));$bytes=New-Object byte[] (8MB);$rng=[Security.Cryptography.RandomNumberGenerator]::Create();try{$rng.GetBytes($bytes)}finally{$rng.Dispose()};[IO.File]::WriteAllBytes($c,$bytes)}@($FixtureRoot,$stable,$unicode,$changing)|Out-Null
$stableFile=Find-File $endpoint.id $stable;$unicodeFile=Find-File $endpoint.id $unicode;$changingFile=Find-File $endpoint.id $changing
$modifier=Victim{param($p)$s=[IO.File]::Open($p,'Open','Write','ReadWrite');try{$s.Position=0;$s.WriteByte(42);$s.Flush($true)}finally{$s.Dispose()}}@($changing)
$d=Wait-Collection (Create-Collection $endpoint.id 'file-evidence' @((File-Artifact 'stable-file' $stableFile),(File-Artifact 'unicode-file' $unicodeFile),(File-Artifact 'changing-file' $changingFile)) 'Profile D exact stable, Unicode, and changing file evidence').collectionId
$profileD=$d.result.items.Where({$_.sourceObject-eq$stable-and$_.state-eq'Acquired'}).Count-eq1-and$d.result.items.Where({$_.sourceObject-eq$unicode-and$_.state-eq'Acquired'}).Count-eq1-and$d.result.items.Where({$_.sourceObject-eq$changing-and$_.raceState-eq'UnstableDuringAcquisition'}).Count-eq1

$partialPath="$FixtureRoot\missing-$tag.bin";Victim{param($p)[IO.File]::WriteAllText($p,'will-be-removed')}@($partialPath)|Out-Null;$partialFile=Find-File $endpoint.id $partialPath;Stop-Agent;$partial=Create-Collection $endpoint.id 'file-evidence' @((File-Artifact 'missing-after-approval' $partialFile)) 'Profile E truthful missing target partial';Victim{param($p)Remove-Item -LiteralPath $p -Force}@($partialPath)|Out-Null;$agentPid=Start-Agent;$partial=Wait-Collection $partial.collectionId
$cancelScope=@(@{requestId='pre-cancel-system';artifactType='SystemInformation';maximumItems=1;maximumBytes=262144},@{requestId='cancel-eventlog';artifactType='WindowsEventLog';source='Security';maximumItems=1;maximumBytes=8388608;maximumRecords=10000;lookbackMinutes=43200})
$cancel=Create-Collection $endpoint.id 'endpoint-investigation' $cancelScope 'Profile E cancellation preserves completed evidence';$deadline=[DateTimeOffset]::UtcNow.AddSeconds(60);do{Start-Sleep -Milliseconds 100;$cancelNow=Api GET "/api/v1/forensic-collections/$($cancel.collectionId)"}while($cancelNow.state-ne'Running'-and[DateTimeOffset]::UtcNow-lt$deadline);if($cancelNow.state-eq'Running'){Api POST "/api/v1/forensic-collections/$($cancel.collectionId):cancel" $admin @{reason='Controlled cancellation during bounded EVTX acquisition'}|Out-Null};$cancel=Wait-Collection $cancel.collectionId
$profileE=$partial.state-eq'Partial'-and$partial.result.failedItems-ge1-and$cancel.state-in@('CancelledWithEvidence','Cancelled')-and$cancel.result.cancellationObserved

Stop-Agent;$offline=Create-Collection $endpoint.id 'quick-triage' $quick 'Profile F offline queue, backend restart, reconnect and replay';docker compose --env-file .env -f deployment/docker-compose.yml restart gateway|Out-Null;$ready=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;try{$ok=(Invoke-WebRequest http://127.0.0.1:8080/health/ready -UseBasicParsing -TimeoutSec 3).StatusCode-eq200}catch{$ok=$false}}while(!$ok-and[DateTimeOffset]::UtcNow-lt$ready);$agentPid=Start-Agent;$f=Wait-Collection $offline.collectionId;$hashF=$f.result.manifestHash;Stop-Agent;$agentPid=Start-Agent;Start-Sleep 5;$replayed=Api GET "/api/v1/forensic-collections/$($f.collectionId)";$profileF=$ok-and$f.state-eq'Succeeded'-and$replayed.result.manifestHash-eq$hashF-and$replayed.result.items.Count-eq$f.result.items.Count

$health=Api GET '/api/v1/forensic-collection-health';$history=(Api GET "/api/v1/endpoints/$($endpoint.id)/forensic-collections").items
$responseQueue=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.response_actions where state not in ('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected');")
$outbox=((docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Trim()).Split('|')|ForEach-Object{[long]$_}
$report=[ordered]@{schemaVersion='sprint22-windows-forensic-collection.v1';executedAt=[DateTimeOffset]::UtcNow;victim=@{vm=$VictimVmName;endpointId=$endpoint.id;agentPid=$agentPid;native=$native};profiles=@{A=@{status=if($profileA){'PASS'}else{'FAIL'};collection=$a};B=@{status=if($profileB){'PASS'}else{'FAIL'};collection=$b};C=@{status=if($profileC){'PASS'}else{'FAIL'};collection=$c;secretRedacted=$regText-notmatch'SENSITIVE-CONTENT-MUST-NOT-APPEAR'};D=@{status=if($profileD){'PASS'}else{'FAIL'};collection=$d};E=@{status=if($profileE){'PASS'}else{'FAIL'};partial=$partial;cancellation=$cancel};F=@{status=if($profileF){'PASS'}else{'FAIL'};collection=$f;backendRestart=$ok;replayHashStable=$replayed.result.manifestHash-eq$hashF}};api=@{historyCount=$history.Count;health=$health};queues=@{response=$responseQueue;outboxPending=$outbox[0];outboxFailed=$outbox[1]};result=if($profileA-and$profileB-and$profileC-and$profileD-and$profileE-and$profileF-and$responseQueue-eq0-and$outbox[0]-eq0-and$outbox[1]-eq0){'PASS'}else{'FAIL'}}
$report|ConvertTo-Json -Depth 100|Set-Content artifacts/sprint22-windows-forensic-collection.json -Encoding utf8
$report|ConvertTo-Json -Depth 8
if($report.result-ne'PASS'){exit 1}
