param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
& (Join-Path $PSScriptRoot 'sprint26-final-reconciliation.ps1') -VictimVmName $VictimVmName -CredentialPath $CredentialPath|Out-Null
$prior=Get-Content artifacts/sprint26-final-reconciliation.json -Raw|ConvertFrom-Json
function Sql($q){(docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $q).Trim()}
$tenant=((Get-Content .env|Where-Object{$_-match'^PLATFORM_BOOTSTRAP_TENANT_ID='})-split'=',2)[1].Trim().Trim('"').Trim("'")
$counts=(Sql "select (select count(*) from platform.fleet_endpoint_metadata where tenant_id='$tenant')||'|'||(select count(*) from platform.fleet_groups where tenant_id='$tenant')||'|'||(select count(*) from platform.deployment_ring_policies where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_packages where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_policies where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_rollouts where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_assignments where tenant_id='$tenant')||'|'||(select count(*) from platform.fleet_update_audit where tenant_id='$tenant');").Split('|')
$active=[int](Sql "select count(*) from platform.agent_update_assignments where state in ('Assigned','WaitingForRing','WaitingForWindow','Downloading','Downloaded','Verifying','Staged','Installing','Restarting','VerifyingInstall','RollbackPending','RollingBack','Paused');")
$report=[ordered]@{schemaVersion='sprint27-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');postgres=$prior.postgres;openSearch=$prior.openSearch;differences=$prior.differences;fleet=[ordered]@{endpointMetadata=[int]$counts[0];groups=[int]$counts[1];ringPolicies=[int]$counts[2];packages=[int]$counts[3];policies=[int]$counts[4];rollouts=[int]$counts[5];assignments=[int]$counts[6];audit=[int]$counts[7];activeAssignments=$active};victimQueues=$prior.victimQueues;queueTotal=$prior.queueTotal;responseNonterminal=$prior.responseNonterminal;orchestrationPending=$prior.orchestrationPending;outbox=$prior.outbox;nats=$prior.nats;passed=$prior.passed-and$active-eq0-and[int]$counts[1]-ge1-and[int]$counts[3]-ge1-and[int]$counts[5]-ge1}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint27-final-reconciliation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){exit 1}
