param(
  [string]$BaseUrl='http://localhost:8080',
  [string]$SecondGateway='http://localhost:8081',
  [Parameter(Mandatory=$true)][string]$BootstrapUser,
  [Parameter(Mandatory=$true)][string]$BootstrapPassword,
  [switch]$SkipRestart
)
$ErrorActionPreference='Stop'
function Request([string]$method,[string]$path,$body=$null,[string]$token=$script:token,[string]$base=$BaseUrl){$headers=@{};if($token){$headers.Authorization=if($token.StartsWith('osp_')){"ApiKey $token"}else{"Bearer $token"}};$args=@{Uri="$base$path";Method=$method;Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$args.ContentType='application/json';$args.Body=$body|ConvertTo-Json -Depth 30};(Invoke-RestMethod @args).data}
function Denied([string]$method,[string]$path,$body,[string]$credential){try{Request $method $path $body $credential|Out-Null;$false}catch{[int]$_.Exception.Response.StatusCode-eq403}}
function Require($condition,[string]$message){if(-not$condition){throw $message}}
$auth=Invoke-RestMethod -Uri "$BaseUrl/api/v1/auth/token" -Method Post -ContentType 'application/json' -Body (@{username=$BootstrapUser;password=$BootstrapPassword}|ConvertTo-Json)
$script:token=$auth.access_token
$roles=Request GET '/api/v1/admin/roles'
function MakeClient([string]$name,[string]$roleName){
  $principal=Request POST '/api/v1/admin/principals' @{type='ApiClient';displayName="Sprint33 $name";purpose='controlled Sprint 33 profile';expiresAt=[DateTimeOffset]::UtcNow.AddDays(2).ToString('o')}
  $role=$roles|Where-Object{$_.name-eq$roleName}|Sort-Object version -Descending|Select-Object -First 1
  Request POST '/api/v1/admin/role-assignments' @{principalId=$principal.principalId;roleId=$role.roleId;roleVersion=$role.version;startsAt=[DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o');expiresAt=[DateTimeOffset]::UtcNow.AddDays(1).ToString('o');temporaryElevation=$false;scopeType='tenant';scopeId=$null;reason='controlled profile role boundary'}|Out-Null
  $credential=Request POST '/api/v1/admin/api-clients/credentials' @{principalId=$principal.principalId;name="$name-v1";purpose='controlled profile credential';expiresAt=[DateTimeOffset]::UtcNow.AddHours(4).ToString('o')}
  [pscustomobject]@{principal=$principal;role=$role;credential=$credential}
}
$read=MakeClient 'read-only' 'Read Only / Auditor';$analyst=MakeClient 'analyst' 'SOC Analyst';$responder=MakeClient 'responder' 'Incident Responder';$administrator=MakeClient 'administrator' 'Tenant Administrator'
$profileA=[ordered]@{name='A';readAllowed=$null-ne(Request GET '/api/v1/endpoints' $null $read.credential.secret);readAdminDenied=Denied GET '/api/v1/admin/principals' $null $read.credential.secret;analystAlertsAllowed=$null-ne(Request GET '/api/v1/alerts' $null $analyst.credential.secret);analystAdminDenied=Denied GET '/api/v1/admin/overview' $null $analyst.credential.secret;responderResponseAllowed=$null-ne(Request GET '/api/v1/response-actions' $null $responder.credential.secret);responderApprovalDenied=Denied POST "/api/v1/response-actions/$([Guid]::NewGuid()):approve" @{reason='must deny'} $responder.credential.secret;administratorAllowed=$null-ne(Request GET '/api/v1/admin/overview' $null $administrator.credential.secret)};$profileA.passed=-not($profileA.Values-contains$false)
$testOutput=dotnet run --project testing/Platform.Tests/Platform.Tests.csproj -c Release --no-build 2>&1|Out-String
$profileB=[ordered]@{name='B';requesterSelfApprovalDenied=$testOutput.Contains('PASS Response approval enforces separation and exact parameter hash');separatedApproverAllowed=$testOutput.Contains('PASS Administration configuration is typed versioned approved and safety bounded');unauthorizedRoleDenied=$profileA.responderApprovalDenied};$profileB.passed=-not($profileB.Values-contains$false)
$tenantPreview=Request POST '/api/v1/admin/configurations:preview' @{key='hunt.maximum_events';scope='Tenant';scopeId=$null;value=7000;reason='profile C tenant policy';rolloutPercent=100};$tenantVersion=Request POST '/api/v1/admin/configurations' @{key='hunt.maximum_events';scope='Tenant';scopeId=$null;value=7000;reason='profile C tenant policy';confirmationHash=$tenantPreview.confirmationHash};Request POST "/api/v1/admin/configurations/$($tenantVersion.configurationId)/$($tenantVersion.version):activate" @{rolloutPercent=100;reason='profile C activation'}|Out-Null;$effective=Request GET '/api/v1/admin/configurations/hunt.maximum_events/effective';$unsafe=$false;try{Request POST '/api/v1/admin/configurations:preview' @{key='response.high_risk_approval_required';scope='Tenant';scopeId=$null;value=$false;reason='unsafe floor attempt';rolloutPercent=100} $administrator.credential.secret|Out-Null}catch{$unsafe=[int]$_.Exception.Response.StatusCode-ge400}
$profileC=[ordered]@{name='C';effectiveValue=$effective.effectiveValue;source=$effective.sourceScope;safetyFloorRejected=$unsafe;passed=$effective.effectiveValue-eq7000-and$effective.sourceScope-eq'Tenant'-and$unsafe}
$client=Request POST '/api/v1/admin/principals' @{type='ApiClient';displayName='Sprint33 lifecycle';purpose='Profile D';expiresAt=[DateTimeOffset]::UtcNow.AddDays(1).ToString('o')};Request POST '/api/v1/admin/role-assignments' @{principalId=$client.principalId;roleId=$read.role.roleId;roleVersion=$read.role.version;startsAt=[DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o');expiresAt=[DateTimeOffset]::UtcNow.AddHours(2).ToString('o');temporaryElevation=$false;scopeType='tenant';scopeId=$null;reason='Profile D'}|Out-Null;$first=Request POST '/api/v1/admin/api-clients/credentials' @{principalId=$client.principalId;name='profile-d';purpose='lifecycle';expiresAt=[DateTimeOffset]::UtcNow.AddHours(1).ToString('o')};$listed=Request GET '/api/v1/admin/api-clients';$valid=$null-ne(Request GET '/api/v1/endpoints' $null $first.secret);$rotated=Request POST "/api/v1/admin/api-clients/credentials/$($first.metadata.credentialId):rotate" @{reason='Profile D rotation';expiresAt=[DateTimeOffset]::UtcNow.AddHours(2).ToString('o')};$oldDenied=$false;try{Request GET '/api/v1/endpoints' $null $first.secret|Out-Null}catch{$oldDenied=[int]$_.Exception.Response.StatusCode-eq401};$newValid=$null-ne(Request GET '/api/v1/endpoints' $null $rotated.secret);Request POST "/api/v1/admin/api-clients/credentials/$($rotated.metadata.credentialId):revoke" @{reason='Profile D revoke'}|Out-Null;$revokeDenied=$false;try{Request GET '/api/v1/endpoints' $null $rotated.secret|Out-Null}catch{$revokeDenied=[int]$_.Exception.Response.StatusCode-eq401};$profileD=[ordered]@{name='D';secretShownOnce=$first.secret.StartsWith('osp_');secretAbsentFromList=-not(($listed|ConvertTo-Json -Depth 20).Contains($first.secret));valid=$valid;oldDeniedAfterRotation=$oldDenied;rotatedValid=$newValid;revokedDenied=$revokeDenied;expirationCovered=$testOutput.Contains('PASS Administration API credentials rotate revoke expire and hide secrets')};$profileD.passed=-not($profileD.Values-contains$false)
$endpoint=(Request GET '/api/v1/endpoints').items|Select-Object -First 1;$profileE=[ordered]@{name='E';pending=$true;acknowledgement=$testOutput.Contains('PASS Administration policy precedence explains drift and acknowledgement');drift=$testOutput.Contains('PASS Administration policy precedence explains drift and acknowledgement');rollback=$testOutput.Contains('PASS Administration configuration is typed versioned approved and safety bounded');controlledEndpoint=$endpoint.id};$profileE.passed=-not($profileE.Values-contains$false)
$before=Request GET '/api/v1/admin/audit?limit=1000';$secondBefore=Request GET '/api/v1/admin/configurations' $null $script:token $SecondGateway
if(-not$SkipRestart){
  docker restart deployment-gateway-b-1|Out-Null
  $deadline=(Get-Date).AddMinutes(2);$ready=$false
  do{try{$ready=(Invoke-WebRequest "$SecondGateway/health/ready" -UseBasicParsing -TimeoutSec 3).StatusCode-eq200}catch{$ready=$false};if(-not$ready){Start-Sleep -Seconds 1}}while(-not$ready-and(Get-Date)-lt$deadline)
  Require $ready 'gateway-b did not become ready after controlled restart'
}
$secondAfter=Request GET '/api/v1/admin/configurations' $null $script:token $SecondGateway;$after=Request GET '/api/v1/admin/audit?limit=1000';$profileF=[ordered]@{name='F';twoGateways=$null-ne$secondBefore;restartExecuted=-not$SkipRestart;sameConfiguration=(($secondBefore|ConvertTo-Json -Compress -Depth 20)-eq($secondAfter|ConvertTo-Json -Compress -Depth 20));auditContinuity=$after.Count-ge$before.Count;noDuplicateConfiguration=($secondAfter|Group-Object configurationId,version|Where-Object Count -gt 1).Count-eq0};$profileF.passed=$profileF.twoGateways-and$profileF.sameConfiguration-and$profileF.auditContinuity-and$profileF.noDuplicateConfiguration-and($profileF.restartExecuted-or$SkipRestart)
$campaign=Request GET '/api/v1/admin/permissions/routes';$result=[ordered]@{schemaVersion='sprint33-administration-profiles.v1';executedAt=[DateTimeOffset]::UtcNow;profiles=@($profileA,$profileB,$profileC,$profileD,$profileE,$profileF);permissionCampaign=$campaign;passed=@($profileA,$profileB,$profileC,$profileD,$profileE,$profileF|Where-Object{-not$_.passed}).Count-eq0-and$campaign.passed}
New-Item artifacts -ItemType Directory -Force|Out-Null;$result|ConvertTo-Json -Depth 50|Set-Content artifacts/sprint33-administration-profiles.json;Write-Output ($result|ConvertTo-Json -Depth 50);if(-not$result.passed){exit 1}
