param([string]$BaseUrl='http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function Login{$x=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);@{Authorization="Bearer $($x.access_token)"}}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt([string]$tid,[string]$subject,[string[]]$permissions){$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub=$subject;tid=$tid;per=$permissions;pty='user';iat=$n;exp=$n+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};"$h.$b.$s"}
function Status([string]$path,$headers=$null,[string]$method='GET',$body=$null){try{$p=@{Uri="$BaseUrl$path";UseBasicParsing=$true;Method=$method};if($headers){$p.Headers=$headers};if($body){$p.ContentType='application/json';$p.Body=$body};(Invoke-WebRequest @p).StatusCode}catch{[int]$_.Exception.Response.StatusCode}}
function Sql($q){(docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $q).Trim()}
$admin=Login;$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;$endpoint=(Sql "select endpoint_id from platform.fleet_endpoint_metadata where tenant_id='$tenant' order by updated_at desc limit 1;");if(!$endpoint){throw'No Sprint 27 production endpoint metadata.'}
$seed=Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/agent-update/self-test?endpoint=$endpoint" -Headers $admin;if(-not$seed.data.passed){throw'Control-plane profiles failed.'};$package=$seed.data.production.packageId;$rollout=$seed.data.production.rollout;$assignment=$seed.data.production.assignment
$fleet=(Invoke-RestMethod "$BaseUrl/api/v1/fleet/endpoints" -Headers $admin).data;$packageBefore=(Invoke-RestMethod "$BaseUrl/api/v1/agent-update/packages/$package" -Headers $admin).data;$rolloutBefore=(Invoke-RestMethod "$BaseUrl/api/v1/agent-update/rollouts/$rollout" -Headers $admin).data;$health=(Invoke-RestMethod "$BaseUrl/api/v1/agent-update/health" -Headers $admin).data;$audit=@((Invoke-RestMethod "$BaseUrl/api/v1/agent-update/audit?limit=500" -Headers $admin).data);$metrics=(Invoke-WebRequest "$BaseUrl/metrics" -UseBasicParsing).Content
$other=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$other',organization_id,'Sprint27 isolation','local','active' from platform.tenants limit 1 on conflict do nothing"|Out-Null;$foreign=@{Authorization="Bearer $(Jwt $other 'sprint27-foreign' @('platform:admin','response:read'))"};$reader=@{Authorization="Bearer $(Jwt $tenant 'sprint27-reader' @('response:read'))"}
$security=[ordered]@{unauthPackage=(Status "/api/v1/agent-update/packages/$package")-eq401;foreignPackage=(Status "/api/v1/agent-update/packages/$package" $foreign)-eq404;foreignRollout=(Status "/api/v1/agent-update/rollouts/$rollout" $foreign)-eq404;foreignFleet=@((Invoke-RestMethod "$BaseUrl/api/v1/fleet/endpoints" -Headers $foreign).data.items).Count-eq0;readerMutation=(Status "/api/v1/agent-update/rollouts/$rollout`:pause" $reader 'POST' '{"reason":"forged"}')-eq403;randomPackage=(Status "/api/v1/agent-update/packages/$([guid]::NewGuid())" $admin)-eq404;arbitraryObjectGuess=(Status "/agent/v1/updates/packages/$assignment/content?endpointId=$endpoint&installationId=forged" $admin)-in@(401,403,404);metricsNoIdentifiers=-not$metrics.Contains($endpoint)-and-not$metrics.Contains($package);metricsPresent=$metrics.Contains('platform_agent_update_pending')-and$metrics.Contains('platform_agent_update_verification_failures_total')}
docker compose --env-file .env -f deployment/docker-compose.yml restart gateway|Out-Null;$deadline=(Get-Date).AddSeconds(90);do{Start-Sleep 2;try{$null=Invoke-RestMethod "$BaseUrl/health/ready" -TimeoutSec 5;break}catch{}}while((Get-Date)-lt$deadline);$admin=Login;$packageAfter=(Invoke-RestMethod "$BaseUrl/api/v1/agent-update/packages/$package" -Headers $admin).data;$rolloutAfter=(Invoke-RestMethod "$BaseUrl/api/v1/agent-update/rollouts/$rollout" -Headers $admin).data
$counts=(Sql "select (select count(*) from platform.fleet_endpoint_metadata where tenant_id='$tenant')||'|'||(select count(*) from platform.fleet_groups where tenant_id='$tenant')||'|'||(select count(*) from platform.deployment_ring_policies where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_packages where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_policies where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_rollouts where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_update_assignments where tenant_id='$tenant')||'|'||(select count(*) from platform.fleet_update_audit where tenant_id='$tenant');").Split('|')
$active=[int](Sql "select count(*) from platform.agent_update_assignments where state in ('Assigned','WaitingForRing','WaitingForWindow','Downloading','Downloaded','Verifying','Staged','Installing','Restarting','VerifyingInstall','RollbackPending','RollingBack','Paused');");$outbox=(Sql "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Split('|');$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($nats.account_details.stream_detail.consumer_detail);$pending=[long](($consumers|Measure-Object num_pending -Sum).Sum);$ack=[long](($consumers|Measure-Object num_ack_pending -Sum).Sum);$redelivered=[long](($consumers|Measure-Object num_redelivered -Sum).Sum)
$report=[ordered]@{schemaVersion='sprint27-control-plane-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');endpointId=$endpoint;profiles=$seed.data.profiles;packageRejection=$seed.data.packageRejection;canary=$seed.data.rollout;preview=$seed.data.preview;production=$seed.data.production;fleetCount=$fleet.count;health=$health;security=$security;restart=[ordered]@{packageRetained=$packageAfter.manifest.manifestSha256-eq$packageBefore.manifest.manifestSha256;rolloutRetained=$rolloutAfter.rollout.rolloutHash-eq$rolloutBefore.rollout.rolloutHash;assignmentRetained=@($rolloutAfter.assignments|Where-Object{$_.assignmentId-eq$assignment}).Count-eq1};postgres=[ordered]@{endpointMetadata=[int]$counts[0];groups=[int]$counts[1];ringPolicies=[int]$counts[2];packages=[int]$counts[3];policies=[int]$counts[4];rollouts=[int]$counts[5];assignments=[int]$counts[6];audit=[int]$counts[7];activeAssignments=$active};transport=[ordered]@{outboxPending=[int]$outbox[0];outboxFailed=[int]$outbox[1];natsPending=$pending;natsAckPending=$ack;natsRedelivered=$redelivered};passed=$seed.data.passed-and@($security.GetEnumerator()|Where-Object{-not$_.Value}).Count-eq0-and$packageAfter.manifest.manifestSha256-eq$packageBefore.manifest.manifestSha256-and$rolloutAfter.rollout.rolloutHash-eq$rolloutBefore.rollout.rolloutHash-and$active-eq0-and[int]$outbox[0]-eq0-and[int]$outbox[1]-eq0-and$pending-eq0-and$ack-eq0}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint27-control-plane-validation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){exit 1}
