param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
& (Join-Path $PSScriptRoot 'sprint30-final-reconciliation.ps1') -VictimVmName $VictimVmName -CredentialPath $CredentialPath
$base=Get-Content artifacts/sprint30-final-reconciliation.json -Raw|ConvertFrom-Json
function Sql($query){(docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $query).Trim()}
$ai=(Sql "select (select count(*) from platform.ai_hunt_proposals)||'|'||(select count(*) from platform.ai_rule_drafts)||'|'||(select count(*) from platform.ai_rule_simulations)||'|'||(select count(*) from platform.ai_rule_comparisons)||'|'||(select count(*) from platform.ai_engineering_audit);").Split('|')|ForEach-Object{[long]$_}
$rls=[int](Sql "select count(*) from pg_tables where schemaname='platform' and tablename in ('ai_hunt_proposals','ai_rule_drafts','ai_rule_simulations','ai_rule_comparisons','ai_engineering_audit') and rowsecurity;");$policies=[int](Sql "select count(*) from pg_policies where schemaname='platform' and tablename in ('ai_hunt_proposals','ai_rule_drafts','ai_rule_simulations','ai_rule_comparisons','ai_engineering_audit') and policyname='tenant_isolation';")
$report=[ordered]@{schemaVersion='sprint31-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');postgres=$base.postgres;openSearch=$base.openSearch;differences=$base.differences;aiInvestigation=$base.ai;aiEngineering=[ordered]@{huntProposals=$ai[0];ruleDrafts=$ai[1];simulations=$ai[2];comparisons=$ai[3];auditEvents=$ai[4];rlsTables=$rls;tenantPolicies=$policies};victimQueues=$base.victimQueues;queueTotal=$base.queueTotal;responseNonterminal=$base.responseNonterminal;orchestrationPending=$base.orchestrationPending;updatePending=$base.updatePending;outbox=$base.outbox;nats=$base.nats;ha=$base.ha;passed=$base.passed-and$ai[0]-gt0-and$ai[1]-gt0-and$ai[2]-gt0-and$ai[4]-gt0-and$rls-eq5-and$policies-eq5}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint31-final-reconciliation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 31 final reconciliation failed.'}
