param([string]$Output='artifacts/sprint5-network-failure-recovery.json')
$ErrorActionPreference='Stop';Set-Location (Resolve-Path (Join-Path $PSScriptRoot '..\..'));$compose=@('-f','deployment/docker-compose.yml','--env-file','.env');$cfg=@{};Get-Content .env|?{$_-match'^[^#].*='}|%{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]}
function B64([byte[]]$b){[Convert]::ToBase64String($b).TrimEnd('=').Replace('+','-').Replace('/','_')};function Jwt{$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint5-failure';tid=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('system:admin');pty='user';iat=$now;exp=$now+1800;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));"$h.$p.$(B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$p"))))"}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$h=@{Authorization="Bearer $($login.access_token)"};$system=@{Authorization="Bearer $(Jwt)"};$event=(Invoke-RestMethod 'http://localhost:8080/api/v1/network-events?pageSize=1' -Headers $h).data.items[0];$from=[DateTimeOffset]::UtcNow.AddHours(-12).ToString('O');$to=[DateTimeOffset]::UtcNow.AddMinutes(2).ToString('O');$rows=[Collections.Generic.List[object]]::new()
function Add($name,$expected,$actual,[bool]$passed){$rows.Add([ordered]@{failure=$name;expected=$expected;actual=$actual;recovered=$passed;passed=$passed})};function Ready([int]$seconds=120){$d=[DateTimeOffset]::UtcNow.AddSeconds($seconds);do{Start-Sleep 1;try{$ok=(Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing -TimeoutSec 2).StatusCode-eq200}catch{$ok=$false}}while((-not$ok)-and[DateTimeOffset]::UtcNow-lt$d);$ok};function Status($uri){try{[int](Invoke-WebRequest $uri -Headers $h -UseBasicParsing -TimeoutSec 4).StatusCode}catch{if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{0}}};function NewExport{(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/network-exports -Headers $h -ContentType application/json -Body (@{format='jsonl';query=@{endpointId=$event.endpointId;from=$from;to=$to};fields=@();maximumRecords=100}|ConvertTo-Json -Depth 8)).data};function WaitExport($job,[int]$seconds=45){$d=[DateTimeOffset]::UtcNow.AddSeconds($seconds);do{Start-Sleep -Milliseconds 500;$job=(Invoke-RestMethod "http://localhost:8080/api/v1/network-exports/$($job.id)" -Headers $h).data}while($job.state-in@('Pending','Running')-and[DateTimeOffset]::UtcNow-lt$d);$job}
try{
 $pg0=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc 'select count(*) from platform.network_events');$os0=[int]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-network-events/_count|ConvertFrom-Json).count)
 & docker compose @compose stop nats|Out-Null;Start-Sleep 2;try{$duringState=Invoke-RestMethod http://localhost:8080/health/ready -TimeoutSec 4}catch{$duringState=$null};& docker compose @compose up -d nats|Out-Null;$recovered=Ready;$degraded=$null-ne$duringState-and$duringState.status-eq'ready_degraded'-and$duringState.dependencies.messageBus-notmatch'^healthy$';Add 'NATS unavailable' 'readiness reports optional dependency degradation and restores' "during=$($duringState.status) messageBus=$($duringState.dependencies.messageBus) recovered=$recovered" ($degraded-and$recovered)
 & docker compose @compose stop opensearch|Out-Null;Start-Sleep 2;$during=Status 'http://localhost:8080/api/v1/network-events?pageSize=1';& docker compose @compose up -d opensearch|Out-Null;$d=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;$healthy=(docker inspect deployment-opensearch-1 --format '{{.State.Health.Status}}')-eq'healthy'}while((-not$healthy)-and[DateTimeOffset]::UtcNow-lt$d);$rebuild=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/network-events/projections:rebuild -Headers $system).data;Add 'OpenSearch unavailable' 'search fails safely and rebuild reconciles' "during=$during documents=$($rebuild.documents)" ($during-in@(0,500,502,503)-and$healthy-and$rebuild.aliasSwitched)
 & docker compose @compose stop minio|Out-Null;$failed=WaitExport (NewExport) 30;& docker compose @compose up -d minio|Out-Null;Start-Sleep 3;$recoveredJob=WaitExport (NewExport);Add 'MinIO unavailable' 'export fails bounded then completes' "failed=$($failed.state) recovered=$($recoveredJob.state)" ($failed.state-eq'Failed'-and$recoveredJob.state-eq'Completed')
 & docker compose @compose stop postgres|Out-Null;Start-Sleep 2;$during=Status 'http://localhost:8080/health/ready';& docker compose @compose up -d postgres|Out-Null;$recovered=Ready;Add 'PostgreSQL unavailable' 'authority degrades and restores' "during=$during recovered=$recovered" ($during-ne200-and$recovered)
 & docker compose @compose restart postgres nats opensearch minio gateway|Out-Null;$combined=Ready 150;$d=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;$healthy=(docker inspect deployment-opensearch-1 --format '{{.State.Health.Status}}')-eq'healthy'}while((-not$healthy)-and[DateTimeOffset]::UtcNow-lt$d);$final=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/network-events/projections:rebuild -Headers $system).data;$pg=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc 'select count(*) from platform.network_events');$os=[int]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-network-events/_count|ConvertFrom-Json).count);Add 'combined infrastructure restart' 'ready and exact reconciliation' "ready=$combined pg=$pg os=$os" ($combined-and$healthy-and$final.aliasSwitched-and$pg-eq$os)
 $drainDeadline=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;$outbox=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc 'select count(*) from platform.outbox where published_at is null and failed_at is null');$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$c=@($nats.account_details.stream_detail.consumer_detail);$pending=($c|Measure-Object num_pending -Sum).Sum;$ack=($c|Measure-Object num_ack_pending -Sum).Sum}while(($outbox-ne0-or$pending-ne0-or$ack-ne0)-and[DateTimeOffset]::UtcNow-lt$drainDeadline);Add 'outbox and projection recovery' 'all durable work drains within 120 seconds' "outbox=$outbox pending=$pending ack=$ack" ($outbox-eq0-and$pending-eq0-and$ack-eq0)
}finally{& docker compose @compose up -d postgres nats opensearch minio gateway|Out-Null;Ready|Out-Null}
$failed=@($rows|?{-not$_.passed});$report=[ordered]@{schema='platform.sprint5.network-failure-recovery.v1';executedAt=[DateTimeOffset]::UtcNow;baseline=@{postgres=$pg0;openSearch=$os0};cases=$rows;failed=$failed.Count;passed=$failed.Count-eq0};$report|ConvertTo-Json -Depth 10|Set-Content $Output;$report|ConvertTo-Json -Depth 5;if(-not$report.passed){exit 1}
