param([string]$GatewayA='http://127.0.0.1:8080',[string]$GatewayB='http://127.0.0.1:8081')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match '^([^#=]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Hash([byte[]]$v){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($v))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Jwt([string]$subject,[string[]]$permissions,[string]$type='user',[string]$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub=$subject;tid=$tenant;per=$permissions;pty=$type;iat=$now;exp=$now+3600;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$mac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{"$h.$p.$(B64($mac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$p"))))"}finally{$mac.Dispose()}}
function Api([string]$method,[string]$uri,$headers,$body=$null){$a=@{Method=$method;Uri=$uri;Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$a.ContentType='application/json';$a.Body=($body|ConvertTo-Json -Depth 30 -Compress)};((Invoke-WebRequest @a).Content|ConvertFrom-Json).data}
function Put([string]$base,[guid]$id,[int]$index,[byte[]]$bytes,[string]$hash,$headers){$h=@{};$headers.GetEnumerator()|ForEach-Object{$h[$_.Key]=$_.Value};$h['X-Chunk-SHA256']=$hash;((Invoke-WebRequest -Method Put -Uri "$base/agent/v1/artifact-transfers/$id/chunks/$index" -Headers $h -ContentType 'application/octet-stream' -Body $bytes -UseBasicParsing).Content|ConvertFrom-Json).data}
$login=Invoke-RestMethod -Method Post "$GatewayA/api/v1/auth/token" -ContentType application/json -Body (@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"}
$identity=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select e.id||'|'||a.id||'|'||a.instance_id from platform.endpoints e join platform.agents a on a.tenant_id=e.tenant_id and a.endpoint_id=e.id where e.os_type='windows' and lower(a.status)='active' order by a.last_checkin desc nulls last limit 1;").Trim().Split('|');if($identity.Count-ne3){throw 'Active Windows endpoint fixture is unavailable'}
$endpoint=[guid]$identity[0];$agentId=[guid]$identity[1];$installation=$identity[2];$agent=@{Authorization="Bearer $(Jwt "$endpoint`:$agentId" @('agent:heartbeat') 'agent')";'X-Agent-Installation-Id'=$installation}
$session=$null;$aStopped=$false;$download='artifacts\sprint28-transfer-download.bin'
try{
  $session=Api POST "$GatewayA/api/v1/live-response/sessions" $admin @{endpointId=$endpoint;capabilities=@('builtin');idleTimeoutSeconds=900;absoluteLifetimeSeconds=3600;policyVersion='live-response-policy.v1'}
  Api GET "$GatewayA/agent/v1/live-response/sessions" $agent|Out-Null
  Api POST "$GatewayA/agent/v1/live-response/sessions/$($session.sessionId):transition" $agent @{sessionId=$session.sessionId;agentInstallationId=$installation;nonce=$session.nonce;state='Active';occurredAt=[DateTimeOffset]::UtcNow.ToString('o');executionIdentity='pid:controlled';integrityLevel='high';workingDirectory='C:\Sprint28Fixture';reason='controlled HA transfer'}|Out-Null
  $command=Api POST "$GatewayA/api/v1/live-response/sessions/$($session.sessionId)/commands" $admin @{commandType='BuiltIn';input='pwd';timeoutSeconds=300}
  Api GET "$GatewayA/agent/v1/live-response/commands" $agent|Out-Null
  foreach($state in @('Acknowledged','Running')){Api POST "$GatewayA/agent/v1/live-response/commands/$($command.commandId):transition" $agent @{sessionId=$session.sessionId;commandId=$command.commandId;agentInstallationId=$installation;nonce=$command.nonce;inputHash=$command.inputHash;state=$state;occurredAt=[DateTimeOffset]::UtcNow.ToString('o');reason='controlled HA transfer'}|Out-Null}
  [byte[]]$bytes=New-Object byte[] (768KB);for($i=0;$i-lt$bytes.Length;$i++){$bytes[$i]=[byte](($i*31+17)%251)};$sha=Hash $bytes;$transfer=[guid]::NewGuid();$artifact=[guid]::NewGuid();$chunkSize=256KB
  $start=Api POST "$GatewayA/agent/v1/artifact-transfers" $agent @{transferId=$transfer;ownerType='live-response';ownerId=$command.commandId;artifactId=$artifact;name='sprint28-controlled.bin';mediaType='application/octet-stream';size=$bytes.Length;sha256=$sha;chunkSize=$chunkSize;nativeIdentity='controlled:sprint28'}
  [byte[]]$chunk0=$bytes[0..($chunkSize-1)];$h0=Hash $chunk0;Put $GatewayA $transfer 0 $chunk0 $h0 $agent|Out-Null
  $throughB=Api GET "$GatewayB/agent/v1/artifact-transfers/$transfer" $agent;if($throughB.receivedChunks-ne1){throw 'Gateway B did not observe shared transfer cursor'}
  docker stop deployment-gateway-1|Out-Null;$aStopped=$true
  $duplicate=Put $GatewayB $transfer 0 $chunk0 $h0 $agent
  [byte[]]$bad=$chunk0.Clone();$bad[0]=$bad[0]-bxor 0xff;$badHash=Hash $bad;$conflict=0;try{Put $GatewayB $transfer 0 $bad $badHash $agent|Out-Null}catch{$conflict=[int]$_.Exception.Response.StatusCode}
  for($index=1;$index-lt3;$index++){[byte[]]$chunk=$bytes[($index*$chunkSize)..(($index+1)*$chunkSize-1)];$hash=Hash $chunk;Put $GatewayB $transfer $index $chunk $hash $agent|Out-Null}
  $complete=Api POST "$GatewayB/agent/v1/artifact-transfers/$transfer`:complete" $agent @{transferId=$transfer;sha256=$sha;size=$bytes.Length}
  Invoke-WebRequest -Uri "$GatewayB/api/v1/artifact-transfers/$transfer/content" -Headers $admin -OutFile $download -UseBasicParsing;$downloadHash=(Get-FileHash $download -Algorithm SHA256).Hash.ToLowerInvariant()
  $started=[DateTimeOffset]::UtcNow.AddSeconds(-2).ToString('o');$empty=Hash ([byte[]]@());Api POST "$GatewayB/agent/v1/live-response/commands/$($command.commandId):complete" $agent @{sessionId=$session.sessionId;commandId=$command.commandId;agentInstallationId=$installation;nonce=$command.nonce;inputHash=$command.inputHash;result=@{startedAt=$started;completedAt=[DateTimeOffset]::UtcNow.ToString('o');state='Succeeded';exitCode=0;stdoutBytes=0;stderrBytes=0;truncated=$false;outputLimitHit=$false;outputHash=$empty;executionIdentity='pid:controlled';integrity='high';workingDirectory='C:\Sprint28Fixture';artifacts=@()};artifacts=@(@{artifactId=$artifact;name='sprint28-controlled.bin';mediaType='application/octet-stream';sha256=$sha;nativeIdentity='controlled:sprint28';consistent=$true;transferId=$transfer;size=$bytes.Length})}|Out-Null
  $result=if($start.receivedChunks-eq0-and$throughB.receivedChunks-eq1-and$duplicate.nextChunkIndex-eq1-and$conflict-in@(400,409)-and$complete.state-eq'Completed'-and$complete.receivedChunks-eq3-and$downloadHash-eq$sha){'PASS'}else{'FAIL'}
  $report=[ordered]@{schemaVersion='sprint28-multi-gateway-transfer.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');profile='D';result=$result;gatewayA='stopped after chunk 0';gatewayBObservedChunks=$throughB.receivedChunks;transferId=$transfer;sourceSha256=$sha;downloadSha256=$downloadHash;duplicateChunkIdempotent=($duplicate.nextChunkIndex-eq1);conflictingChunkStatus=$conflict;completedChunks=$complete.receivedChunks;size=$complete.size;state=$complete.state}
  $report|ConvertTo-Json -Depth 10|Set-Content artifacts/sprint28-multi-gateway-transfer.json -Encoding utf8;$report|ConvertTo-Json -Depth 10
  if($result-ne'PASS'){exit 1}
}finally{if($aStopped){docker start deployment-gateway-1|Out-Null;Start-Sleep -Seconds 3};if($session){try{Api POST "$GatewayB/api/v1/live-response/sessions/$($session.sessionId):close" $admin @{reason='Sprint 28 controlled HA transfer complete'}|Out-Null}catch{}};Remove-Item $download -Force -ErrorAction SilentlyContinue}



