param([string]$Output = 'artifacts/sprint9-final-reconciliation.json', [int]$TimeoutSeconds = 240, [string]$AgentData = 'artifacts/sprint5-windows-20260807063045')
$ErrorActionPreference = 'Stop'; Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
function Sql([string]$query) { docker exec deployment-postgres-1 psql -U platform -d platform -Atc $query }
function OsCount([string]$alias,[string]$body='') { if($body){[long]((docker exec deployment-opensearch-1 curl -sf -H 'Content-Type: application/json' -d $body "http://localhost:9200/$alias/_count"|ConvertFrom-Json).count)}else{[long]((docker exec deployment-opensearch-1 curl -sf "http://localhost:9200/$alias/_count"|ConvertFrom-Json).count)} }
$domains=@('process','file','registry','network','dns','module','persistence');$aliases=@('platform-processes','platform-files','platform-registry-events','platform-network-events','platform-dns-events','platform-module-events','platform-persistence-events');$queues=@('process','file','registry','network','dns','module','persistence')
$deadline=[DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds)
do{
    Start-Sleep -Seconds 5
    $values=(Sql "select (select count(*) from platform.process_entities)||'|'||(select count(*) from platform.file_entities)||'|'||(select count(*) from platform.registry_events)||'|'||(select count(*) from platform.network_events)||'|'||(select count(*) from platform.dns_events)||'|'||(select count(*) from platform.module_events)||'|'||(select count(*) from platform.persistence_events)||'|'||(select count(*) from platform.outbox where published_at is null and failed_at is null)||'|'||(select count(*) from platform.outbox where failed_at is not null);").Trim().Split('|')|ForEach-Object{[long]$_}
    $search=for($i=0;$i-lt$aliases.Count;$i++){OsCount $aliases[$i]}
    $queueState=[ordered]@{};foreach($q in $queues){$queueState[$q]=@(Get-ChildItem (Join-Path $AgentData "$q-queue") -File -Filter '*.json' -ErrorAction SilentlyContinue).Count}
    $js=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($js.account_details.stream_detail.consumer_detail);$pending=[long](($consumers|Measure-Object num_pending -Sum).Sum);$ack=[long](($consumers|Measure-Object num_ack_pending -Sum).Sum)
    $exact=$true;for($i=0;$i-lt$domains.Count;$i++){if($values[$i]-ne$search[$i]){$exact=$false}};$drained=@($queueState.Values|Where-Object{$_-ne0}).Count-eq0-and$values[7]-eq0-and$values[8]-eq0-and$pending-eq0-and$ack-eq0
}while((-not($exact-and$drained))-and[DateTimeOffset]::UtcNow-lt$deadline)
$pg=[ordered]@{};$os=[ordered]@{};$diff=[ordered]@{};for($i=0;$i-lt$domains.Count;$i++){$pg[$domains[$i]]=$values[$i];$os[$domains[$i]]=$search[$i];$diff[$domains[$i]]=$values[$i]-$search[$i]}
$pgKinds=(Sql "select object_kind||'='||count(*) from platform.persistence_events group by object_kind order by object_kind;") -split "`n";$osKinds=[ordered]@{Service=[long]((docker exec deployment-opensearch-1 curl -sf 'http://localhost:9200/platform-persistence-events/_count?q=object_kind%3AService'|ConvertFrom-Json).count);ScheduledTask=[long]((docker exec deployment-opensearch-1 curl -sf 'http://localhost:9200/platform-persistence-events/_count?q=object_kind%3AScheduledTask'|ConvertFrom-Json).count);PersistenceConfiguration=[long]((docker exec deployment-opensearch-1 curl -sf 'http://localhost:9200/platform-persistence-events/_count?q=object_kind%3APersistenceConfiguration'|ConvertFrom-Json).count)}
$report=[ordered]@{schema='platform.sprint9.final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');postgres=$pg;openSearch=$os;differences=$diff;persistencePostgresKinds=$pgKinds;persistenceOpenSearchKinds=$osKinds;queues=$queueState;outbox=[ordered]@{pending=$values[7];failed=$values[8]};nats=[ordered]@{pending=$pending;ackPending=$ack};passed=($exact-and$drained)}
$report|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $Output -Encoding utf8;$report|ConvertTo-Json -Depth 6;if(-not$report.passed){throw 'Sprint 9 final reconciliation did not drain exactly.'}
