param([string]$Output='artifacts/sprint3h-windows-administrative-lifecycle.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;Set-Location $root
$principal=[Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent();if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Administrator token required.'}
$cfg=@{};Get-Content .env|Where-Object{$_ -match '^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]};$session=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$headers=@{Authorization="Bearer $($session.access_token)"}
$exe=Join-Path $root 'agent/core/Platform.Agent/bin/Release/net8.0/Platform.Agent.exe'
function FindData([string]$endpoint){$match=Get-ChildItem artifacts -Directory -Filter 'sprint3e-windows-*'|ForEach-Object{$log=Join-Path $_.FullName 'agent.log';if(Test-Path $log){if(Select-String -Path $log -SimpleMatch $endpoint -Quiet){$_}}}|Select-Object -First 1;if(-not $match){throw "Agent data not found for $endpoint"};$match.FullName}
function StartAgent([string]$data,[string]$name){$env:PLATFORM_AGENT_DATA=$data;$env:PLATFORM_ENVIRONMENT='production';$env:PLATFORM_CONTROL_PLANE_URL='https://localhost:8443';$env:PLATFORM_CA_CERT_PATH=(Resolve-Path deployment/certificates/ca.crt).Path;$env:PLATFORM_ENROLLMENT_TOKEN_ID='';$env:PLATFORM_ENROLLMENT_TOKEN_SECRET='';Start-Process -FilePath $exe -RedirectStandardOutput (Join-Path $data "$name.log") -RedirectStandardError (Join-Path $data "$name.stderr.log") -PassThru -WindowStyle Hidden}
function Prepare{Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;foreach($n in @('OpenSecurityPlatform-FileLifecycle-v1','OpenSecurityPlatform-ProcessLifecycle-v1')){logman stop $n -ets 2>$null|Out-Null}}
function WaitHeartbeat([string]$log){$deadline=[DateTimeOffset]::UtcNow.AddSeconds(20);do{Start-Sleep 1;$ok=(Test-Path $log)-and(Select-String -Path $log -Pattern 'Authenticated heartbeat' -Quiet)}while(-not$ok-and[DateTimeOffset]::UtcNow-lt$deadline);if(-not$ok){throw "Heartbeat not observed in $log"}}
$disabledEndpoint='f810d8b8-b2a6-4665-8b7f-dd3dc1993f5d';$revokedEndpoint='b6ef5962-c69d-4724-8297-95b53c096ddc';$rows=@();$agent=$null
try{
  Prepare;$disabledData=FindData $disabledEndpoint;$agent=StartAgent $disabledData 'administrative-disable';WaitHeartbeat (Join-Path $disabledData 'administrative-disable.log')
  Invoke-RestMethod -Method Post -Uri "http://localhost:8080/api/v1/endpoints/${disabledEndpoint}:disable" -Headers $headers -ContentType application/json -Body (@{reason='Sprint 3H Windows disable acceptance'}|ConvertTo-Json)|Out-Null
  Start-Sleep 35;$status=(Invoke-RestMethod -Uri "http://localhost:8080/api/v1/endpoints/$disabledEndpoint" -Headers $headers).data.status;$log=Get-Content (Join-Path $disabledData 'administrative-disable.log') -Raw
  $rows+=@{name='endpoint-disable';endpointId=$disabledEndpoint;status=$status;authenticatedRequestsRejected=($log -match 'transient failure|Control plane unavailable');passed=[int]$status -eq 6 -and ($log -match 'transient failure|Control plane unavailable')}
  Stop-Process -Id $agent.Id -Force;$agent.WaitForExit();$agent=$null
  Prepare;$revokedData=FindData $revokedEndpoint;$agent=StartAgent $revokedData 'administrative-revoke';WaitHeartbeat (Join-Path $revokedData 'administrative-revoke.log')
  Invoke-RestMethod -Method Post -Uri "http://localhost:8080/api/v1/endpoints/${revokedEndpoint}:revoke" -Headers $headers -ContentType application/json -Body (@{reason='Sprint 3H Windows certificate revocation acceptance'}|ConvertTo-Json)|Out-Null
  Start-Sleep 35;$revokedStatus=(Invoke-RestMethod -Uri "http://localhost:8080/api/v1/endpoints/$revokedEndpoint" -Headers $headers).data.status;$credentialState=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) filter(where c.revoked_at is null)||'|'||count(*) filter(where c.revoked_at is not null) from platform.agent_credentials c join platform.agents a on a.id=c.agent_id where a.endpoint_id='$revokedEndpoint'").Trim();$revokeLog=Get-Content (Join-Path $revokedData 'administrative-revoke.log') -Raw
  $rows+=@{name='certificate-revocation';endpointId=$revokedEndpoint;status=$revokedStatus;credentialState=$credentialState;authenticatedRequestsRejected=($revokeLog -match 'transient failure|Control plane unavailable');passed=[int]$revokedStatus -eq 7 -and $credentialState -match '^0\|[1-9]' -and ($revokeLog -match 'transient failure|Control plane unavailable')}
  $rows+=@{name='endpoint-re-enable';status='NOT SUPPORTED';justification='The Sprint 1 administrative API exposes disable and irreversible revoke, but no endpoint re-enable operation.';passed=$true}
  $report=@{schema='platform.sprint3h.windows-administrative-lifecycle.v1';executedAt=[DateTimeOffset]::UtcNow;rows=$rows;passed=@($rows|Where-Object{-not$_.passed}).Count-eq 0};$report|ConvertTo-Json -Depth 7|Set-Content $Output;if(-not$report.passed){throw 'Administrative lifecycle acceptance failed.'}
}finally{if($agent -and -not $agent.HasExited){Stop-Process -Id $agent.Id -Force;$agent.WaitForExit()}}
