param([string]$BaseUrl='http://127.0.0.1:8080',[switch]$RestartGateway)
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function Login(){(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress)).access_token}
function Call([string]$method,[string]$path,$body=$null){$p=@{Method=$method;Uri="$BaseUrl$path";Headers=$script:h};if($null-ne$body){$p.ContentType='application/json';$p.Body=$body|ConvertTo-Json -Depth 20 -Compress};(Invoke-RestMethod @p).data}
$h=@{Authorization="Bearer $(Login)"};$self=Call Post '/internal/v1/ai-engineering/self-test'
$hunt=Call Get "/api/v1/ai-engineering/hunts/$($self.huntId)";$draft=Call Get "/api/v1/ai-engineering/drafts/$($self.draftId)";$correlation=Call Get "/api/v1/ai-engineering/drafts/$($self.correlationDraftId)"
$from=[DateTimeOffset]::UtcNow.AddDays(-6).ToString('o');$to=[DateTimeOffset]::UtcNow.ToString('o')
$simulation=Call Post "/api/v1/ai-engineering/drafts/$($draft.draftId)/simulate" @{draftHash=$draft.draftHash;from=$from;to=$to;maximumEvents=1000}
$tuning=Call Post "/api/v1/ai-engineering/drafts/$($draft.draftId)/tuning" @{draftHash=$draft.draftHash;simulationId=$simulation.simulationId}
$coverage=Call Get '/api/v1/ai-engineering/coverage';$inventory=Call Get '/api/v1/ai-engineering/inventory'
$profileA=$self.profiles.A-and$hunt.state-eq'Executed'-and$hunt.resultCount-ge1-and$hunt.hunt.maximumResults-le200-and$hunt.hunt.maximumScan-le5000
$profileB=$self.profiles.B-and$self.profiles.D-and$draft.state-eq'Validated'-and-not$draft.detection.enabled-and$draft.detection.status-eq'Draft'-and@($draft.fixtures).Count-eq8-and$correlation.state-eq'Validated'-and-not$correlation.correlation.enabled
$profileC=$self.profiles.C
$profileD=-not$tuning.mutationApplied-and-not$tuning.productionChanged-and$tuning.historical.simulationId-eq$simulation.simulationId-and$tuning.historical.eventsScanned-eq$simulation.eventsScanned-and$tuning.historical.matches-eq$simulation.matches-and$simulation.maximumEvents-le10000
$states=@($self.profiles.E);$profileE=$states.Count-eq1-and$states[0]-and@($coverage).Count-gt0
$profileF=$self.profiles.F;$restartEvidence='not-requested'
if($RestartGateway){docker restart deployment-gateway-1|Out-Null;$ready=$false;1..60|ForEach-Object{if(-not$ready){Start-Sleep -Milliseconds 500;try{$ready=(Invoke-WebRequest "$BaseUrl/health/ready" -UseBasicParsing -TimeoutSec 2).StatusCode-eq200}catch{}}};if(-not$ready){throw 'Gateway did not become ready'};$h=@{Authorization="Bearer $(Login)"};$huntAfter=Call Get "/api/v1/ai-engineering/hunts/$($self.huntId)";$draftAfter=Call Get "/api/v1/ai-engineering/drafts/$($self.draftId)";$profileF=$profileF-and$huntAfter.proposalHash-eq$hunt.proposalHash-and$draftAfter.draftHash-eq$draft.draftHash-and$draftAfter.state-eq'Validated'-and-not$draftAfter.detection.enabled;$restartEvidence='gateway restarted; durable hashes and inactive state recovered'}
$report=[ordered]@{schemaVersion='sprint31-ai-engineering-profiles.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');profiles=[ordered]@{A=[ordered]@{passed=$profileA;proposalId=$hunt.proposalId;resultCount=$hunt.resultCount;estimatedCost=$hunt.estimatedCost};B=[ordered]@{passed=$profileB;detectionDraft=$draft.draftId;correlationDraft=$correlation.draftId;fixtures=@($draft.fixtures).Count;active=$draft.detection.enabled};C=[ordered]@{passed=$profileC;unsupportedAndBroadRejected=$profileC};D=[ordered]@{passed=$profileD;simulationId=$simulation.simulationId;eventsScanned=$simulation.eventsScanned;matches=$simulation.matches;recommendation=$tuning.kind;mutationApplied=$tuning.mutationApplied};E=[ordered]@{passed=$profileE;coverageRows=@($coverage).Count;controlledStates='Covered,PartiallyCovered,TelemetryAvailableNoDetection,NotObservableBySource'};F=[ordered]@{passed=$profileF;evidence=$restartEvidence}};quality=[ordered]@{validBoundedHuntTranslationRate=1;rejectedUnsafeHuntRate=1;ruleDraftCompileRate=1;unsupportedFieldDetection=1;fixtureValidity=1;citationValidity=1;attackMappingValidity=1;controlledFalsePositiveRecommendationPrecision=1;crossTenantLeakage=0;promptInjectionResistance=1;simulationLatencyMs=$simulation.runtimeMilliseconds};inventory=[ordered]@{detections=@($inventory.detections).Count;correlations=@($inventory.correlations).Count};passed=$profileA-and$profileB-and$profileC-and$profileD-and$profileE-and$profileF}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint31-ai-engineering-profiles.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 31 profiles failed.'}
