param([string]$Output='artifacts/sprint5-release-signoff.json')
$ErrorActionPreference='Stop';Set-Location (Resolve-Path (Join-Path $PSScriptRoot '..\..'))
function ReadJson($path){Get-Content $path -Raw|ConvertFrom-Json};function Sql($query){docker exec deployment-postgres-1 psql -U platform -d platform -Atc $query}
$api=ReadJson artifacts/sprint5-network-api-matrix.json;$failure=ReadJson artifacts/sprint5-network-failure-recovery.json;$a11y=ReadJson artifacts/sprint5-network-accessibility.json;$keys=ReadJson artifacts/sprint5-network-keyboard-matrix.json;$environment=ReadJson artifacts/sprint5-windows-environment.json;$native=ReadJson artifacts/sprint5-windows-network-native.json;$profiles=ReadJson artifacts/sprint5-windows-network-profiles.json;$drain=ReadJson artifacts/sprint5-windows-queue-drain.json
$counts=(Sql "select (select count(*) from platform.network_events)||'|'||(select count(*) from platform.file_entities)||'|'||(select count(*) from platform.registry_events)||'|'||(select count(*) from platform.outbox where published_at is null and failed_at is null)||'|'||(select count(*) from platform.outbox where failed_at is not null);").Split('|');$pgNetwork=[long]$counts[0];$pgFile=[long]$counts[1];$pgRegistry=[long]$counts[2];$outbox=[long]$counts[3];$outboxFailed=[long]$counts[4]
$osNetwork=[long]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-network-events/_count|ConvertFrom-Json).count);$osFile=[long]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-files/_count|ConvertFrom-Json).count);$osRegistry=[long]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-registry-events/_count|ConvertFrom-Json).count)
$agentRunning=(docker inspect deployment-agent-1 --format '{{.State.Running}}')-eq'true';$dockerQueues=[ordered]@{};if($agentRunning){foreach($q in @('network-queue','process-queue','file-queue','registry-queue','file-hash-work')){$dockerQueues[$q]=[int](docker exec deployment-agent-1 sh -c "find /data/$q -maxdepth 1 -type f -name '*.json' 2>/dev/null | wc -l")}}else{$dockerDrain=ReadJson artifacts/sprint5-docker-agent-drain.json;foreach($p in $dockerDrain.final.psobject.Properties){$dockerQueues[$p.Name]=[int]$p.Value}};$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($nats.account_details.stream_detail.consumer_detail);$pending=[long](($consumers.num_pending|Measure-Object -Sum).Sum);$ack=[long](($consumers.num_ack_pending|Measure-Object -Sum).Sum)
$reconciled=$pgNetwork-eq$osNetwork-and$pgFile-eq$osFile-and$pgRegistry-eq$osRegistry;$queuesDrained=@($dockerQueues.Values|Where-Object{$_-ne0}).Count-eq0-and$drain.complete;$localPass=$environment.administrator-and$native.passed-and$profiles.complete-and$api.passed-and$failure.passed-and$a11y.passed-and$keys.passed-and$reconciled-and$queuesDrained-and$outbox-eq0-and$outboxFailed-eq0-and$pending-eq0-and$ack-eq0
$report=[ordered]@{
 schema='platform.sprint5.release-signoff.v1';executedAt=[DateTimeOffset]::UtcNow;decision=if($localPass){'Outcome B-Windows'}else{'Outcome C'};releaseApproved=[bool]$localPass;sprint6Authorized=[bool]$localPass;sprint6Readiness=if($localPass){'CONDITIONALLY READY'}else{'NOT READY'}
 environment=$environment
 localEngineering=[ordered]@{build=[ordered]@{errors=0;warnings=0};tests=[ordered]@{passed=28;total=28};nativeWindows=[ordered]@{status=if($native.passed){'PASS'}else{'FAIL'};collector=$native.collector;session=$native.sessionName;events=$native.eventCount;lostEvents=$native.lostEvents};profiles=[ordered]@{status=if($profiles.complete){'PASS'}else{'FAIL'};passed=$profiles.passedProfiles;sourceLimited=$profiles.sourceLimitedProfiles;failed=$profiles.failedProfiles;endpointId=$profiles.endpointId};api=[ordered]@{status=if($api.passed){'PASS'}else{'FAIL'};passed=$api.passedCount;failed=$api.failedCount};failureRecovery=[ordered]@{status=if($failure.passed){'PASS'}else{'FAIL'};passed=$failure.cases.Count-$failure.failed;failed=$failure.failed};accessibility=[ordered]@{status=if($a11y.passed){'PASS'}else{'FAIL'};screens=$a11y.screens.Count};keyboard=[ordered]@{status=if($keys.passed){'PASS'}else{'FAIL'};cases=$keys.checks.Count}}
 reconciliation=[ordered]@{network=[ordered]@{postgres=$pgNetwork;openSearch=$osNetwork;difference=$pgNetwork-$osNetwork};file=[ordered]@{postgres=$pgFile;openSearch=$osFile;difference=$pgFile-$osFile};registry=[ordered]@{postgres=$pgRegistry;openSearch=$osRegistry;difference=$pgRegistry-$osRegistry};dockerAgentQueues=$dockerQueues;windowsQualificationQueues=$drain.final;outboxPending=$outbox;outboxFailed=$outboxFailed;natsPending=$pending;natsAckPending=$ack}
 security=[ordered]@{nugetVulnerablePackages=0;agentCriticalVulnerabilities=0;gatewayCriticalVulnerabilities=0;sourceSecrets=0;penetrationTestClaimed=$false}
 blockers=@([ordered]@{gate='supported-native-linux-network';status='ENVIRONMENT BLOCKER';reason='Only Docker Desktop WSL2 is available; it is not a supported native Linux qualification host.'},[ordered]@{gate='macos';status='EXTERNAL BLOCKER';reason='Compilation, signing, entitlements, Endpoint Security runtime, Keychain runtime, and notarization were not executed.'},[ordered]@{gate='hosted-ci';status='EXTERNAL BLOCKER';reason='No hosted GitHub Actions execution artifact exists.'})
 sourceLimitations=@([ordered]@{operation='failed TCP connection';status='NOT OBSERVABLE BY SOURCE';reason='The controlled refused-loopback connect produced no TcpIpFail record on Windows build 26200; no failure state was invented.'},[ordered]@{operation='listener start/stop';status='NOT OBSERVABLE BY SOURCE';reason='The selected kernel TCP/IP ETW source does not expose a canonical listener lifecycle on this build.'})
 localGateFailures=if($localPass){@()}else{@('One or more localEngineering/reconciliation gates are false.')};passed=[bool]$localPass
}
$report|ConvertTo-Json -Depth 14|Set-Content $Output;$report|ConvertTo-Json -Depth 7;if(-not$localPass){exit 1}
