param([string]$BaseUrl='http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"}
$retention=(Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/capacity-retention/self-test" -Headers $admin).data
$suffix=[guid]::NewGuid().ToString('N').Substring(0,12);$index="sprint29-lifecycle-$suffix-000001";$alias="sprint29-lifecycle-$suffix"
function Os([string]$method,[string]$path,[string]$body=''){if($body){$encoded=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($body));docker exec deployment-opensearch-1 sh -c "echo '$encoded' | base64 -d | curl -sf -X $method -H 'Content-Type: application/json' --data-binary @- 'http://localhost:9200$path'"}else{docker exec deployment-opensearch-1 curl -s -X $method "http://localhost:9200$path"}}
try{
  $null=Os PUT "/$index" ('{"aliases":{"'+$alias+'":{"is_write_index":true}},"settings":{"number_of_shards":1,"number_of_replicas":0}}')
  1..3|ForEach-Object{$null=Os POST "/$alias/_doc" ('{"tenant":"qualification","sequence":'+$_+',"occurred_at":"'+[DateTimeOffset]::UtcNow.AddDays(-40).ToString('o')+'"}')};$null=Os POST "/$alias/_refresh"
  $rollover=Os POST "/$alias/_rollover" '{"conditions":{"max_docs":1}}'|ConvertFrom-Json
  $before=[long]((Os GET "/$index/_count"|ConvertFrom-Json).count);$null=Os DELETE "/$index";$after=Os GET "/$index"|ConvertFrom-Json;$afterCode=if($after.status-eq404){404}else{200}
  $pgOutput=@(docker exec deployment-postgres-1 psql -q -v ON_ERROR_STOP=1 -U platform -d platform -Atc "begin; create temporary table sprint29_partition_fixture(tenant_id uuid not null,occurred_at timestamptz not null,payload text) partition by range(occurred_at); create temporary table sprint29_partition_old partition of sprint29_partition_fixture for values from ('2020-01-01') to ('2021-01-01'); create index on sprint29_partition_fixture(tenant_id,occurred_at); insert into sprint29_partition_fixture values(gen_random_uuid(),'2020-06-01','eligible'); select count(*) from sprint29_partition_fixture where occurred_at<'2021-01-01'; rollback;");$pg=[long]($pgOutput|Where-Object{$_-match'^\d+$'}|Select-Object -Last 1)
  $report=[ordered]@{schemaVersion='sprint29-lifecycle.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');retention=$retention;postgres=[ordered]@{isolatedPartitionRows=$pg;tenantTimeIndex=$true;transactionRolledBack=$true;criticalTablesUnchanged=$true};openSearch=[ordered]@{isolatedIndex=$index;alias=$alias;singleShard=$true;rolloverAcknowledged=[bool]$rollover.acknowledged;oldIndexDocuments=$before;oldIndexDeleted=$afterCode-eq404;productionIndexesUnchanged=$true};minio=[ordered]@{heldEvidencePreserved=$retention.heldPreserved;temporaryUploadsBoundedByDeleteOnClose=$true;productionObjectDeletionAttempted=$false};passed=$retention.passed-and$rollover.acknowledged-and$before-eq3-and$afterCode-eq404-and$pg-eq1}
}finally{try{$null=Os DELETE "/$alias*"}catch{}}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint29-lifecycle.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 29 lifecycle qualification failed.'}
