$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '../..');Set-Location $root
$domains=[ordered]@{process=@('platform.process_entities','platform-processes');file=@('platform.file_entities','platform-files');registry=@('platform.registry_events','platform-registry-events');network=@('platform.network_events','platform-network-events');dns=@('platform.dns_events','platform-dns-events');module=@('platform.module_events','platform-module-events');persistence=@('platform.persistence_events','platform-persistence-events');identity=@('platform.identity_events','platform-identity-events');execution=@('platform.execution_events','platform-execution-events');detection=@('platform.detection_findings','platform-detection-findings');correlation=@('platform.correlated_findings','platform-correlated-findings');indicators=@('platform.threat_indicators','platform-threat-indicators-v1');iocMatches=@('platform.threat_matches','platform-ioc-matches-v1');tunnelObservations=@('platform.tunnel_observations','platform-tunnel-observations');tunnelFindings=@('platform.tunnel_findings','platform-tunnel-findings')}
function Sql($query){(docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $query).Trim()}
function Os($index){[long]((docker exec deployment-opensearch-1 curl -sf "http://localhost:9200/$index/_count"|ConvertFrom-Json).count)}
$postgres=[ordered]@{};$openSearch=[ordered]@{};$differences=[ordered]@{};foreach($name in $domains.Keys){$postgres[$name]=[long](Sql "select count(*) from $($domains[$name][0]);");$openSearch[$name]=Os $domains[$name][1];$differences[$name]=$postgres[$name]-$openSearch[$name]}
$transport=(Sql "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Split('|')|ForEach-Object{[long]$_}
$work=(Sql "select (select count(*) from platform.response_actions where state not in ('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected','Uncertain'))||'|'||(select count(*) from platform.playbook_work where state='pending')||'|'||(select count(*) from platform.agent_update_assignments where state in ('Assigned','WaitingForRing','WaitingForWindow','Downloading','Downloaded','Verifying','Staged','Installing','Restarting','VerifyingInstall','RollbackPending','RollingBack','Paused'))||'|'||(select count(*) from platform.artifact_transfers where state in ('Receiving','Verifying'));").Split('|')|ForEach-Object{[long]$_}
$js=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($js.account_details.stream_detail.consumer_detail);$pending=[long](($consumers|Measure-Object num_pending -Sum).Sum);$ack=[long](($consumers|Measure-Object num_ack_pending -Sum).Sum);$redelivery=[long](($consumers|Measure-Object num_redelivered -Sum).Sum)
$prior=Get-Content artifacts/sprint34-final-reconciliation.json -Raw|ConvertFrom-Json;$agentProcesses=@(Get-Process Platform.Agent -ErrorAction SilentlyContinue).Count
$report=[ordered]@{schemaVersion='sprint35-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');postgres=$postgres;openSearch=$openSearch;differences=$differences;endpointQueues=[ordered]@{lastNativeDrainAt=$prior.capturedAt;lastNativeQueueTotal=$prior.queueTotal;lastNativeAgentProcesses=$prior.victim.agentProcesses;currentHostAgentProcesses=$agentProcesses;qualification='No endpoint producer was started for this UI-only sprint; the prior exact native drain remains unchanged'};responseNonterminal=$work[0];orchestrationPending=$work[1];updatePending=$work[2];transferPending=$work[3];outbox=[ordered]@{pending=$transport[0];failed=$transport[1]};nats=[ordered]@{pending=$pending;ackPending=$ack;redelivered=$redelivery};passed=@($differences.Values|Where-Object{$_-ne0}).Count-eq0-and$prior.passed-and$prior.queueTotal-eq0-and$agentProcesses-eq0-and$work[0]-eq0-and$work[1]-eq0-and$work[2]-eq0-and$work[3]-eq0-and$transport[0]-eq0-and$transport[1]-eq0-and$pending-eq0-and$ack-eq0}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint35-final-reconciliation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 35 final reconciliation failed.'}
