[CmdletBinding()]
param(
    [string] $VictimVmName = 'XDR-Victim-Sprint18',
    [string] $CredentialPath = 'D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',
    [string] $QualificationRoot = 'C:\Sprint21Qualification',
    [int] $TimeoutSeconds = 240
)
$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '../..')
Set-Location $root
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not [Security.Principal.WindowsPrincipal]::new($identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Elevated host token required.' }
if ((Get-VM -Name $VictimVmName).State -ne 'Running') { throw 'The pre-existing victim VM must already be running.' }
if ((docker ps --filter 'name=falco' --format '{{.Names}}')) { throw 'Falco must remain stopped.' }
if ((docker ps --filter 'name=deployment-agent' --format '{{.Names}}')) { throw 'Docker agent must remain stopped.' }
if (@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction SilentlyContinue | Where-Object Group -Like 'OpenSecurityPlatform-Isolation-*').Count -ne 0) { throw 'Host platform firewall drift detected.' }

$settings = @{}
Get-Content .env | Where-Object { $_ -match '^\s*([^#=\s]+)=(.*)$' } | ForEach-Object { $settings[$matches[1]] = $matches[2].Trim().Trim('"').Trim("'") }
$login = Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body (@{ username=$settings.PLATFORM_BOOTSTRAP_USER; password=$settings.PLATFORM_BOOTSTRAP_PASSWORD } | ConvertTo-Json -Compress)
$admin = @{ Authorization = "Bearer $($login.access_token)" }
function B64([byte[]]$value) { [Convert]::ToBase64String($value).TrimEnd('=').Replace('+','-').Replace('/','_') }
function Jwt([string]$subject) { $now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$head=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$body=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub=$subject;tid=$settings.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('platform:admin','persistence-response:approve');pty='user';iat=$now;exp=$now+7200;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$h=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));try{$sig=B64($h.ComputeHash([Text.Encoding]::ASCII.GetBytes("$head.$body")))}finally{$h.Dispose()};@{Authorization="Bearer $head.$body.$sig"} }
$approver = Jwt 'sprint21-approver'
function Api([string]$method,[string]$path,$headers=$admin,$body=$null) { $args=@{Method=$method;Uri="http://127.0.0.1:8080$path";Headers=$headers;DisableKeepAlive=$true};if($null-ne$body){$args.ContentType='application/json';$args.Body=$body|ConvertTo-Json -Depth 60 -Compress};try{(Invoke-RestMethod @args).data}catch{$detail='';try{$reader=[IO.StreamReader]::new($_.Exception.Response.GetResponseStream());$detail=$reader.ReadToEnd();$reader.Dispose()}catch{};throw "$method $path failed: $detail"} }
function Session { $credential=Import-Clixml -LiteralPath $CredentialPath;$deadline=[DateTimeOffset]::UtcNow.AddMinutes(3);do{try{return New-PSSession -VMName $VictimVmName -Credential $credential -ErrorAction Stop}catch{Start-Sleep 3}}while([DateTimeOffset]::UtcNow-lt$deadline);throw 'PowerShell Direct unavailable.' }
function Victim([scriptblock]$script,[object[]]$arguments=@()) { $session=Session;try{Invoke-Command -Session $session -ScriptBlock $script -ArgumentList $arguments}finally{Remove-PSSession $session} }
function Stop-Agent { Victim { Get-Process Platform.Agent -ErrorAction SilentlyContinue | Stop-Process -Force; Start-Sleep 1 } | Out-Null }
$script:token = Api POST '/api/v1/enrollment-tokens' $admin @{expiresAt=[DateTimeOffset]::UtcNow.AddHours(3).ToString('o');maximumUses=1;allowedPlatforms=@('windows')}
$script:freshEnrollment=$true
function Start-Agent { $result=Victim { param($q,$id,$secret,$fresh) Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;Start-Sleep 1;if($fresh){Remove-Item "$q\runtime-data" -Recurse -Force -ErrorAction SilentlyContinue};@('OpenSecurityPlatform-ProcessLifecycle-v1','OpenSecurityPlatform-RegistryLifecycle-v1','OpenSecurityPlatform-FileLifecycle-v1','OpenSecurityPlatform-NetworkLifecycle-v1','OpenSecurityPlatform-DnsClient-v1','OpenSecurityPlatform-ModuleImageLoad-v1')|ForEach-Object{& logman stop $_ -ets 2>$null|Out-Null};$env:PLATFORM_CONTROL_PLANE_URL='https://gateway:8443';$env:PLATFORM_ENROLLMENT_TOKEN_ID=$id;$env:PLATFORM_ENROLLMENT_TOKEN_SECRET=$secret;$env:PLATFORM_AGENT_DATA="$q\runtime-data";$env:PLATFORM_CA_CERT_PATH='C:\Sprint19Qualification\ca.crt';$env:PLATFORM_ENVIRONMENT='production';(Start-Process "$q\agent\Platform.Agent.exe" -PassThru -WindowStyle Hidden -RedirectStandardOutput "$q\agent.log" -RedirectStandardError "$q\agent-error.log").Id } @($QualificationRoot,$script:token.metadata.id,$script:token.secret,$script:freshEnrollment);$script:freshEnrollment=$false;$result }
function Wait-Action([guid]$id) { $deadline=[DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 500;$action=Api GET "/api/v1/response-actions/$id"}while($action.state-notin@('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected')-and[DateTimeOffset]::UtcNow-lt$deadline);$action }
function Approve-Wait($action) { if($action.approvalState-eq'Pending'){$action=Api POST "/api/v1/persistence-remediation-actions/$($action.responseActionId):approve" $approver @{parameterHash=$action.parameterHash;reason='verified exact Sprint 21 generation, state hash and dependencies'}};Wait-Action $action.responseActionId }
function Request([guid]$endpoint,[string]$entity,[string]$action,[string]$reason) { $value=Api POST "/api/v1/endpoints/$endpoint/persistence/$entity`:remediate" $admin @{actionType=$action;reason=$reason;sourceEntityId=$entity;expiresInSeconds=300};Approve-Wait $value.action }
function Queue([guid]$endpoint,[string]$entity,[string]$action,[string]$reason) { $value=Api POST "/api/v1/endpoints/$endpoint/persistence/$($entity):remediate" $admin @{actionType=$action;reason=$reason;sourceEntityId=$entity;expiresInSeconds=300};Api POST "/api/v1/persistence-remediation-actions/$($value.action.responseActionId):approve" $approver @{parameterHash=$value.action.parameterHash;reason='exact offline target reviewed'} }
function Restore([guid]$backup,[string]$reason) { $value=Api POST "/api/v1/persistence-remediation-backups/$($backup):restore" $admin @{reason=$reason;expiresInSeconds=300};Approve-Wait $value.action }
function Wait-Entity([guid]$endpoint,[string]$kind,[string]$name) { $deadline=[DateTimeOffset]::UtcNow.AddSeconds(150);do{Start-Sleep 1;$path=if($kind-eq'service'){"/api/v1/service-events?endpointId=$endpoint&name=$([uri]::EscapeDataString($name))&pageSize=200"}elseif($kind-eq'task'){$leaf=$name.Split('\')[-1];"/api/v1/scheduled-task-events?endpointId=$endpoint&name=$([uri]::EscapeDataString($leaf))&pageSize=200"}else{"/api/v1/persistence-configurations?endpointId=$endpoint&name=$([uri]::EscapeDataString($name))&pageSize=500"};$items=(Api GET $path).items;$item=$items|Where-Object{if($kind-eq'service'){$_.service.name-eq$name-and-not$_.service.deletedAt}elseif($kind-eq'task'){$_.scheduledTask.path-eq$name-and-not$_.scheduledTask.deletedAt}else{$_.configuration.name-eq$name-and$_.configuration.currentState-ne'deleted'}}|Sort-Object observedAt -Descending|Select-Object -First 1}while(!$item-and[DateTimeOffset]::UtcNow-lt$deadline);if(!$item){throw "$kind entity not observed: $name"};$item }
function Wait-Binding([guid]$endpoint,[string]$tag) { $deadline=[DateTimeOffset]::UtcNow.AddSeconds(150);do{Start-Sleep 1;$items=(Api GET "/api/v1/persistence-configurations?endpointId=$endpoint&pageSize=200").items;$item=$items|Where-Object{$_.configuration.category-eq'wmi-binding'-and$_.configuration.nativeObjectIdentity-like"*$tag*"-and$_.configuration.currentState-ne'deleted'}|Sort-Object observedAt -Descending|Select-Object -First 1}while(!$item-and[DateTimeOffset]::UtcNow-lt$deadline);if(!$item){throw "WMI binding entity not observed: $tag"};$item }
function BackupId($action) { [guid]$action.result.structuredResult.backupId }

$started=[DateTimeOffset]::UtcNow; $agentPid=Start-Agent; $deadline=[DateTimeOffset]::UtcNow.AddSeconds(150)
do{Start-Sleep 2;$endpoint=(Api GET '/api/v1/endpoints?pageSize=100').items|Where-Object{$_.platform-eq'windows'-and$_.lastSeenAt-and[DateTimeOffset]$_.lastSeenAt-ge$started}|Sort-Object lastSeenAt -Descending|Select-Object -First 1}while(!$endpoint-and[DateTimeOffset]::UtcNow-lt$deadline)
if(!$endpoint){throw 'Victim agent did not enroll.'}
$effective=Api GET "/api/v1/endpoints/$($endpoint.id)/persistence-policy";$policy=$effective.policy.policy;$policy.servicesEnabled=$true;$policy.serviceCreation=$true;$policy.serviceDeletion=$true;$policy.serviceConfiguration=$true;$policy.serviceStateChanges=$true;$policy.tasksEnabled=$true;$policy.taskRegistration=$true;$policy.taskUpdates=$true;$policy.taskDeletion=$true;$policy.taskEnableDisable=$true;$policy.wmiSubscriptionsEnabled=$true;$policy.autorunStartupEnabled=$true;$policy.startupFolderEnabled=$true;$policy.captureTaskXml=$true;$policy.captureArguments=$true;$policy.maximumTaskXmlBytes=262144;$policy.flushSeconds=1;$policy.maximumBatchEvents=1000;$policy.maximumBatchBytes=4194304;$policy.includedServiceNames=$null;$policy.includedTaskPaths=$null;$policy.includedPersistenceCategories=$null;$policy.includedPersistencePaths=$null;$policy.excludedServiceNames=@();$policy.excludedTaskPaths=@();$policy.excludedPersistenceCategories=@();$policy.excludedPersistencePaths=@()
$created=Api POST '/api/v1/persistence-telemetry/policies' $admin @{name="sprint21-bounded-$([guid]::NewGuid().ToString('N'))";policy=$policy};Api POST "/api/v1/persistence-telemetry/policies/$($created.id):assign" $admin @{endpointId=$endpoint.id}|Out-Null
Stop-Agent;$agentPid=Start-Agent;Start-Sleep 50

$tag=[guid]::NewGuid().ToString('N');$regName="Sprint21-$tag";$serviceStop="Sprint21Stop$($tag.Substring(0,8))";$serviceDisable="Sprint21Disable$($tag.Substring(0,8))";$serviceDelete="Sprint21Delete$($tag.Substring(0,8))";$serviceRestart="Sprint21Restart$($tag.Substring(0,8))";$serviceRace="Sprint21Race$($tag.Substring(0,8))";$serviceProtected="OpenSecurityPlatformSprint21$($tag.Substring(0,8))";$taskDisable="\OpenSecurityPlatform\Sprint21\Disable-$tag";$taskDelete="\OpenSecurityPlatform\Sprint21\Delete-$tag";$taskRace="\OpenSecurityPlatform\Sprint21\Race-$tag";$wmiName="Sprint21-$tag"
$fixture=Victim { param($reg,$services,$tasks,$wmi)
    & wevtutil.exe sl Microsoft-Windows-TaskScheduler/Operational /e:true
    $run='HKLM:\Software\Microsoft\Windows\CurrentVersion\Run';New-Item -Path $run -Force|Out-Null;New-ItemProperty -Path $run -Name $reg -Value 'cmd.exe /c exit 0' -PropertyType String -Force|Out-Null
    foreach($name in $services){& sc.exe create $name binPath= 'C:\Windows\System32\cmd.exe /c exit 0' start= demand|Out-Null;if($LASTEXITCODE-ne0){throw "sc create failed: $name"}}
    foreach($path in $tasks){$action=New-ScheduledTaskAction -Execute 'cmd.exe' -Argument '/c exit 0';$trigger=New-ScheduledTaskTrigger -Once -At (Get-Date).AddYears(5);Register-ScheduledTask -TaskName ($path.Split('\')[-1]) -TaskPath (($path.Substring(0,$path.LastIndexOf('\')))+'\') -Action $action -Trigger $trigger -User 'SYSTEM' -RunLevel Highest -Force|Out-Null}
    $filterClass=[wmiclass]'\\.\root\subscription:__EventFilter';$filter=$filterClass.CreateInstance();$filter.Name="$wmi-filter";$filter.EventNamespace='root\cimv2';$filter.QueryLanguage='WQL';$filter.Query="SELECT * FROM __InstanceCreationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_Process' AND TargetInstance.Name = '__never_sprint21__.exe'";$filterPath=$filter.Put()
    $consumerClass=[wmiclass]'\\.\root\subscription:CommandLineEventConsumer';$consumer=$consumerClass.CreateInstance();$consumer.Name="$wmi-consumer";$consumer.CommandLineTemplate='cmd.exe /c exit 0';$consumerPath=$consumer.Put()
    $bindingClass=[wmiclass]'\\.\root\subscription:__FilterToConsumerBinding';$binding=$bindingClass.CreateInstance();$binding.Filter=$filterPath.Path;$binding.Consumer=$consumerPath.Path;$bindingPath=$binding.Put()
    [pscustomobject]@{Registry=(Get-ItemPropertyValue $run $reg);Services=@($services|ForEach-Object{(Get-Service $_).Name});Tasks=@($tasks|ForEach-Object{(Get-ScheduledTask -TaskPath (($_.Substring(0,$_.LastIndexOf('\')))+'\') -TaskName $_.Split('\')[-1]).TaskName});Filter=(Get-WmiObject -Namespace root\subscription -Query "SELECT * FROM __EventFilter WHERE Name='$wmi-filter'").__RELPATH;Consumer=(Get-WmiObject -Namespace root\subscription -Query "SELECT * FROM CommandLineEventConsumer WHERE Name='$wmi-consumer'").__RELPATH;Binding=(Get-WmiObject -Namespace root\subscription -Class __FilterToConsumerBinding|Where-Object {$_.Filter -like "*$wmi-filter*" -and $_.Consumer -like "*$wmi-consumer*"}|Select-Object -First 1 -ExpandProperty __RELPATH)}
} @($regName,@($serviceStop,$serviceDisable,$serviceDelete,$serviceRestart,$serviceRace,$serviceProtected),@($taskDisable,$taskDelete,$taskRace),$wmiName)
Start-Sleep 12

$reg=Wait-Entity $endpoint.id configuration $regName;$previewA=Api GET "/api/v1/endpoints/$($endpoint.id)/persistence/$($reg.configuration.entityId)/remediation-preview";$removeA=Request $endpoint.id $reg.configuration.entityId 'registry.value.remove' 'Profile A remove exact autorun value';$restoreA=Restore (BackupId $removeA) 'Profile A restore exact autorun value';$profileA=$removeA.state-eq'Succeeded'-and$restoreA.state-eq'Succeeded'

$stopEvent=Wait-Entity $endpoint.id service $serviceStop;$stopB=Request $endpoint.id $stopEvent.service.entityId 'service.stop' 'Profile B stop exact controlled service'
$disableEvent=Wait-Entity $endpoint.id service $serviceDisable;$disableB=Request $endpoint.id $disableEvent.service.entityId 'service.disable' 'Profile B disable exact controlled service';$restoreDisableB=Restore (BackupId $disableB) 'Profile B restore disabled service configuration'
$deleteEvent=Wait-Entity $endpoint.id service $serviceDelete;$deleteB=Request $endpoint.id $deleteEvent.service.entityId 'service.delete' 'Profile B delete exact controlled service';$restoreDeleteB=Restore (BackupId $deleteB) 'Profile B recreate exact supported service configuration'
$profileB=@($stopB,$disableB,$restoreDisableB,$deleteB,$restoreDeleteB).Where({$_.state-ne'Succeeded'}).Count-eq0

$taskDisableEvent=Wait-Entity $endpoint.id task $taskDisable;$disableC=Request $endpoint.id $taskDisableEvent.scheduledTask.entityId 'scheduled_task.disable' 'Profile C disable exact scheduled task';$restoreDisableC=Restore (BackupId $disableC) 'Profile C restore scheduled task enabled state'
$taskDeleteEvent=Wait-Entity $endpoint.id task $taskDelete;$deleteC=Request $endpoint.id $taskDeleteEvent.scheduledTask.entityId 'scheduled_task.delete' 'Profile C delete exact scheduled task';$restoreDeleteC=Restore (BackupId $deleteC) 'Profile C restore task from verified XML'
$profileC=@($disableC,$restoreDisableC,$deleteC,$restoreDeleteC).Where({$_.state-ne'Succeeded'}).Count-eq0

$bindingEvent=Wait-Binding $endpoint.id $wmiName;$consumerEvent=Wait-Entity $endpoint.id configuration "$wmiName-consumer";$filterEvent=Wait-Entity $endpoint.id configuration "$wmiName-filter"
$removeBinding=Request $endpoint.id $bindingEvent.configuration.entityId 'wmi.binding.remove' 'Profile D remove exact binding first';$removeConsumer=Request $endpoint.id $consumerEvent.configuration.entityId 'wmi.consumer.remove' 'Profile D remove now-unshared consumer';$removeFilter=Request $endpoint.id $filterEvent.configuration.entityId 'wmi.filter.remove' 'Profile D remove now-unshared filter'
$restoreFilter=Restore (BackupId $removeFilter) 'Profile D restore filter first';$restoreConsumer=Restore (BackupId $removeConsumer) 'Profile D restore consumer second';$restoreBinding=Restore (BackupId $removeBinding) 'Profile D restore binding last';$profileD=@($removeBinding,$removeConsumer,$removeFilter,$restoreFilter,$restoreConsumer,$restoreBinding).Where({$_.state-ne'Succeeded'}).Count-eq0

$protectedEvent=Wait-Entity $endpoint.id service $serviceProtected;$protectedPreview=Api GET "/api/v1/endpoints/$($endpoint.id)/persistence/$($protectedEvent.service.entityId)/remediation-preview"
$consumerEvent=Wait-Entity $endpoint.id configuration "$wmiName-consumer"
$sharedResult=Request $endpoint.id $consumerEvent.configuration.entityId 'wmi.consumer.remove' 'Profile E reject consumer with an active binding'
$staleName="Sprint21-Stale-$tag";Victim { param($name) New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run' -Name $name -Value 'original-A' -PropertyType String -Force|Out-Null } @($staleName)|Out-Null
$staleEvent=Wait-Entity $endpoint.id configuration $staleName;$serviceRaceEvent=Wait-Entity $endpoint.id service $serviceRace;$taskRaceEvent=Wait-Entity $endpoint.id task $taskRace;Stop-Agent
$queued=Queue $endpoint.id $staleEvent.configuration.entityId 'registry.value.remove' 'Profile E stale registry replacement rejection';$queuedService=Queue $endpoint.id $serviceRaceEvent.service.entityId 'service.delete' 'Profile E stale recreated service rejection';$queuedTask=Queue $endpoint.id $taskRaceEvent.scheduledTask.entityId 'scheduled_task.delete' 'Profile E stale recreated task rejection'
Victim { param($name,$service,$task) Set-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run' -Name $name -Value 'replacement-B';& sc.exe delete $service|Out-Null;Start-Sleep 1;& sc.exe create $service binPath= 'C:\Windows\System32\cmd.exe /c echo replacement-service' start= demand|Out-Null;$taskName=$task.Split('\')[-1];$taskPath=($task.Substring(0,$task.LastIndexOf('\')))+'\';Unregister-ScheduledTask -TaskName $taskName -TaskPath $taskPath -Confirm:$false;$action=New-ScheduledTaskAction -Execute 'cmd.exe' -Argument '/c echo replacement-task';$trigger=New-ScheduledTaskTrigger -Once -At (Get-Date).AddYears(6);Register-ScheduledTask -TaskName $taskName -TaskPath $taskPath -Action $action -Trigger $trigger -User 'SYSTEM' -RunLevel Highest|Out-Null } @($staleName,$serviceRace,$taskRace)|Out-Null
docker compose --env-file .env -f deployment/docker-compose.yml stop gateway|Out-Null;docker compose --env-file .env -f deployment/docker-compose.yml up -d gateway|Out-Null;$ready=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;try{$null=Invoke-WebRequest http://127.0.0.1:8080/health/ready -UseBasicParsing;$gatewayReady=$true}catch{$gatewayReady=$false}}while(!$gatewayReady-and[DateTimeOffset]::UtcNow-lt$ready);if(!$gatewayReady){throw 'Gateway did not become ready after controlled restart'};$agentPid=Start-Agent;$staleResult=Wait-Action $queued.responseActionId;$staleServiceResult=Wait-Action $queuedService.responseActionId;$staleTaskResult=Wait-Action $queuedTask.responseActionId
$replacement=Victim { param($name,$service,$task) [pscustomobject]@{Registry=(Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run' -Name $name);Service=(Get-CimInstance Win32_Service -Filter "Name='$service'").PathName;Task=(Get-ScheduledTask -TaskName $task.Split('\')[-1]|Select-Object -First 1).Actions.Arguments} } @($staleName,$serviceRace,$taskRace)
$profileE=$protectedPreview.protected-and$sharedResult.state-eq'Failed'-and$sharedResult.result.failureCategory-eq'Authorization'-and$staleResult.state-eq'Failed'-and$staleServiceResult.state-eq'Failed'-and$staleTaskResult.state-eq'Failed'-and$staleResult.result.failureCategory-eq'Integrity'-and$staleServiceResult.result.failureCategory-eq'Integrity'-and$staleTaskResult.result.failureCategory-eq'Integrity'-and$replacement.Registry-eq'replacement-B'-and$replacement.Service-like'*replacement-service*'-and$replacement.Task-eq'/c echo replacement-task'

$restartEvent=Wait-Entity $endpoint.id service $serviceRestart;$deleteF=Request $endpoint.id $restartEvent.service.entityId 'service.delete' 'Profile F durable backup before restart';$restartBackup=BackupId $deleteF;Stop-Agent;$agentPid=Start-Agent;Start-Sleep 4;$statusF=Api GET "/api/v1/persistence-remediation-backups/$restartBackup";$restoreF=Restore $restartBackup 'Profile F restore after agent restart';$profileF=$deleteF.state-eq'Succeeded'-and$statusF.backup.restoreEligible-and$restoreF.state-eq'Succeeded'

$history=(Api GET "/api/v1/endpoints/$($endpoint.id)/persistence-remediation-history").items;$health=Api GET '/api/v1/persistence-remediation-health';$backups=(Api GET "/api/v1/persistence-remediation-backups?endpointId=$($endpoint.id)").items
$responseQueue=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.response_actions where state not in ('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected');")
$outbox=((docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Trim()).Split('|')|ForEach-Object{[long]$_}
$native=Victim { param($q,$reg,$services,$tasks,$wmi) [pscustomobject]@{Admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);Integrity=(whoami /groups|Select-String 'Mandatory Label').Line;RegistryValue=(Get-ItemPropertyValue 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run' $reg -ErrorAction SilentlyContinue);Services=@($services|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'"|Select-Object Name,State,StartMode});Tasks=@($tasks|ForEach-Object{Get-ScheduledTask -TaskPath (($_.Substring(0,$_.LastIndexOf('\')))+'\') -TaskName $_.Split('\')[-1]|Select-Object TaskName,State});WmiFilters=@(Get-WmiObject -Namespace root\subscription -Class __EventFilter|Where-Object Name -Like "$wmi*"|Select-Object Name,__RELPATH);WmiConsumers=@(Get-WmiObject -Namespace root\subscription -Class CommandLineEventConsumer|Where-Object Name -Like "$wmi*"|Select-Object Name,__RELPATH);WmiBindings=@(Get-WmiObject -Namespace root\subscription -Class __FilterToConsumerBinding|Where-Object {$_.Filter-like"*$wmi*"}|Select-Object Filter,Consumer,__RELPATH);BackupFiles=(Get-ChildItem "$q\runtime-data\protected-persistence-backups-v1" -File -Recurse -Force -ErrorAction SilentlyContinue).Count;AgentError=(Get-Content "$q\agent-error.log" -Raw -ErrorAction SilentlyContinue)} } @($QualificationRoot,$regName,@($serviceStop,$serviceDisable,$serviceDelete,$serviceRestart,$serviceRace,$serviceProtected),@($taskDisable,$taskDelete,$taskRace),$wmiName)
$report=[ordered]@{schemaVersion='sprint21-windows-persistence-response.v1';executedAt=[DateTimeOffset]::UtcNow;victim=@{vm=$VictimVmName;endpointId=$endpoint.id;agentPid=$agentPid;native=$native};profiles=@{A=@{status=if($profileA){'PASS'}else{'FAIL'};preview=$previewA;remove=$removeA;restore=$restoreA};B=@{status=if($profileB){'PASS'}else{'FAIL'};actions=@($stopB,$disableB,$restoreDisableB,$deleteB,$restoreDeleteB)};C=@{status=if($profileC){'PASS'}else{'FAIL'};actions=@($disableC,$restoreDisableC,$deleteC,$restoreDeleteC)};D=@{status=if($profileD){'PASS'}else{'FAIL'};actions=@($removeBinding,$removeConsumer,$removeFilter,$restoreFilter,$restoreConsumer,$restoreBinding)};E=@{status=if($profileE){'PASS'}else{'FAIL'};protectedPreview=$protectedPreview;sharedDependency=$sharedResult;staleRegistry=$staleResult;staleService=$staleServiceResult;staleTask=$staleTaskResult;replacements=$replacement;gatewayRestart='PASS'};F=@{status=if($profileF){'PASS'}else{'FAIL'};delete=$deleteF;restartBackup=$statusF;restore=$restoreF}};api=@{historyCount=$history.Count;backupCount=$backups.Count;health=$health};queues=@{response=$responseQueue;outboxPending=$outbox[0];outboxFailed=$outbox[1]};result=if($profileA-and$profileB-and$profileC-and$profileD-and$profileE-and$profileF-and$responseQueue-eq0-and$outbox[0]-eq0-and$outbox[1]-eq0){'PASS'}else{'FAIL'}}
$report|ConvertTo-Json -Depth 80|Set-Content artifacts/sprint21-windows-persistence-response.json -Encoding utf8
$report|ConvertTo-Json -Depth 80
if($report.result-ne'PASS'){exit 1}
