param([string]$Output='artifacts/sprint11-profile-f-offline-replay.json',[string]$AgentData='artifacts/sprint5-windows-20260807063045')
$ErrorActionPreference='Stop'; Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
function Sql([string]$q){[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc $q)}
function Depth(){@(Get-ChildItem (Join-Path $AgentData 'execution-queue') -File -Filter '*.json' -ErrorAction SilentlyContinue).Count}
function StartAgent(){
  $p=[Diagnostics.ProcessStartInfo]::new('dotnet','agent/core/Platform.Agent/bin/Release/net8.0/Platform.Agent.dll');$p.UseShellExecute=$false;$p.CreateNoWindow=$true;$p.WorkingDirectory=(Get-Location).Path
  $p.Environment['PLATFORM_CONTROL_PLANE_URL']='https://localhost:8443';$p.Environment['PLATFORM_CA_CERT_PATH']='deployment/certificates/ca.crt';$p.Environment['PLATFORM_AGENT_DATA']=$AgentData;$p.Environment['PLATFORM_ENVIRONMENT']='production';$p.Environment['PLATFORM_AGENT_CREDENTIAL_STORE']='platform'
  [Diagnostics.Process]::Start($p)
}
function StopAgent($p){if($null -ne $p -and -not $p.HasExited){$p.Kill();$p.WaitForExit(10000)|Out-Null}}
$initial=Sql 'select count(*) from platform.execution_events;';$before=$initial;$beforeUnique=Sql 'select count(distinct event_id) from platform.execution_events;'
$offlineAgent=StartAgent;try{$readyBy=[DateTimeOffset]::UtcNow.AddSeconds(45);do{Start-Sleep -Seconds 1;$sessionActive=[bool](logman query -ets|Select-String 'OpenSecurityPlatform-ProcessLifecycle-v1')}while(-not$sessionActive-and[DateTimeOffset]::UtcNow-lt$readyBy);if(-not$sessionActive){throw'Native kernel session did not become ready.'};Start-Sleep -Seconds 2;1..5|ForEach-Object{$c=[Diagnostics.Process]::Start([Diagnostics.ProcessStartInfo]::new($env:ComSpec,'/d /c exit 0'));$c.WaitForExit();$c.Dispose()};$warmBy=[DateTimeOffset]::UtcNow.AddSeconds(45);do{Start-Sleep -Seconds 2;$warmCount=Sql 'select count(*) from platform.execution_events;'}while($warmCount-le$initial-and[DateTimeOffset]::UtcNow-lt$warmBy);if($warmCount-le$initial){throw'Execution pipeline did not pass end-to-end warm-up.'};docker stop deployment-gateway-1|Out-Null;$before=Sql 'select count(*) from platform.execution_events;';$beforeUnique=Sql 'select count(distinct event_id) from platform.execution_events;';1..5|ForEach-Object{1..10|ForEach-Object{$c=[Diagnostics.Process]::Start([Diagnostics.ProcessStartInfo]::new($env:ComSpec,'/d /c exit 0'));$c.WaitForExit();$c.Dispose()};Start-Sleep -Seconds 3};Start-Sleep -Seconds 15}finally{StopAgent $offlineAgent}
$offlineDepth=Depth;$offlineDatabase=Sql 'select count(*) from platform.execution_events;'
docker start deployment-gateway-1|Out-Null;Start-Sleep -Seconds 4
$replayAgent=StartAgent;try{$deadline=[DateTimeOffset]::UtcNow.AddSeconds(90);do{Start-Sleep -Seconds 2;$remaining=Depth}while($remaining-gt0-and[DateTimeOffset]::UtcNow-lt$deadline)}finally{StopAgent $replayAgent}
$after=Sql 'select count(*) from platform.execution_events;';$afterUnique=Sql 'select count(distinct event_id) from platform.execution_events;';$deadline=[DateTimeOffset]::UtcNow.AddSeconds(60);do{Start-Sleep -Seconds 2;$os=[long]((docker exec deployment-opensearch-1 curl -sf 'http://localhost:9200/platform-execution-events/_count'|ConvertFrom-Json).count)}while($os-ne$after-and[DateTimeOffset]::UtcNow-lt$deadline)
$report=[ordered]@{schema='platform.sprint11.profile-f.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');nativeSessionReady=$sessionActive;gatewayOffline=$true;databaseBefore=$before;databaseWhileOffline=$offlineDatabase;offlineQueueDepth=$offlineDepth;databaseAfter=$after;uniqueEventsAfter=$afterUnique;openSearchAfter=$os;finalQueueDepth=(Depth);replayedEvents=$after-$before;duplicatesAfter=$after-$afterUnique;passed=$sessionActive-and$offlineDepth-gt0-and$offlineDatabase-eq$before-and(Depth)-eq0-and$after-gt$before-and$after-eq$afterUnique-and$os-eq$after};$report|ConvertTo-Json -Depth 6|Set-Content $Output -Encoding utf8;$report|ConvertTo-Json -Depth 6;if(!$report.passed){exit 1}
