[CmdletBinding()]
param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',[int]$TimeoutSeconds=180)
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '../..');Set-Location $root
$settings=@{};Get-Content .env|Where-Object{$_-match '^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$settings[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')};function Approver{$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint22-profile-e-approver';tid=$settings.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('platform:admin');pty='user';iat=$n;exp=$n+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};@{Authorization="Bearer $h.$b.$s"}}
function Api([string]$method,[string]$path,$headers=$admin,$body=$null){$a=@{Method=$method;Uri="http://127.0.0.1:8080$path";Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$a.ContentType='application/json';$a.Body=[Text.Encoding]::UTF8.GetBytes(($body|ConvertTo-Json -Depth 50 -Compress))};try{$r=Invoke-WebRequest @a;[pscustomobject]@{status=[int]$r.StatusCode;data=($r.Content|ConvertFrom-Json).data}}catch{[pscustomobject]@{status=[int]$_.Exception.Response.StatusCode;data=$null}}}
$prior=Get-Content artifacts/sprint22-windows-forensic-collection.json -Raw|ConvertFrom-Json;$target=$prior.profiles.D.collection.requestedArtifacts|Where-Object requestId -eq stable|Select-Object -ExpandProperty fileTarget;$credential=Import-Clixml $CredentialPath;$session=New-PSSession -VMName $VictimVmName -Credential $credential
try {
    Invoke-Command -Session $session -ScriptBlock { Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force }
    $lockPid=Invoke-Command -Session $session -ScriptBlock { param($path) if(!(Test-Path -LiteralPath $path)-and(Test-Path -LiteralPath($path+'.gone'))){Move-Item -LiteralPath($path+'.gone') -Destination $path -Force};$escaped=$path.Replace("'","''");$code="`$f=[IO.File]::Open('$escaped',[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::None);try{Start-Sleep 120}finally{`$f.Dispose()}";$encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($code));(Start-Process powershell.exe -ArgumentList '-NoProfile','-EncodedCommand',$encoded -WindowStyle Hidden -PassThru).Id } -ArgumentList $target.canonicalPath
    Start-Sleep 2
    $request=@{endpointId=$prior.victim.endpoint;profileId='file-evidence';profileVersion=1;reason='Profile E exclusive-lock acquisition';expiresInSeconds=900;policyVersion='forensic-collection-policy.v1';requestedArtifacts=@(@{requestId='locked';artifactType='File';fileTarget=$target;maximumItems=1;maximumBytes=[long]$target.expectedSize})}
    $created=(Api POST '/api/v1/forensic-collections' $admin $request).data;$approved=(Api POST "/api/v1/forensic-collections/$($created.collectionId):approve" (Approver) @{parameterHash=$created.parameterHash;reason='Separated exact-scope approval'}).data
    Invoke-Command -Session $session -ScriptBlock { $q='C:\Sprint22Qualification';$env:PLATFORM_CONTROL_PLANE_URL='https://gateway:8443';$env:PLATFORM_AGENT_DATA="$q\runtime-data";$env:PLATFORM_CA_CERT_PATH='C:\Sprint19Qualification\ca.crt';$env:PLATFORM_ENVIRONMENT='production';Start-Process "$q\agent\Platform.Agent.exe" -WindowStyle Hidden -RedirectStandardOutput "$q\profile-e-agent.log" -RedirectStandardError "$q\profile-e-agent-error.log"|Out-Null }
    $deadline=[DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 300;$locked=(Api GET "/api/v1/forensic-collections/$($created.collectionId)").data}while($locked.state-notin@('Succeeded','Partial','Failed','Cancelled','Expired')-and[DateTimeOffset]::UtcNow-lt$deadline)
    Invoke-Command -Session $session -ScriptBlock { param($pidToStop) Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;Get-Process -Id $pidToStop -ErrorAction SilentlyContinue|Stop-Process -Force } -ArgumentList $lockPid
}
finally { Remove-PSSession $session }
$countArtifacts=1..17|ForEach-Object{@{requestId="count-$_";artifactType='SystemInformation';maximumItems=1;maximumBytes=1024}}
$countStatus=(Api POST '/api/v1/forensic-collections:preview' $admin @{endpointId=$prior.victim.endpoint;profileId='quick-triage';profileVersion=1;reason='Profile E count quota';expiresInSeconds=900;policyVersion='forensic-collection-policy.v1';requestedArtifacts=$countArtifacts}).status
$oversized=@{requestId='bytes';artifactType='File';fileTarget=$target;maximumItems=1;maximumBytes=12582913}
$bytesStatus=(Api POST '/api/v1/forensic-collections:preview' $admin @{endpointId=$prior.victim.endpoint;profileId='file-evidence';profileVersion=1;reason='Profile E byte quota';expiresInSeconds=900;policyVersion='forensic-collection-policy.v1';requestedArtifacts=@($oversized)}).status
$lockedPass=$locked.state-eq'Partial'-and$locked.result.failedItems-eq1-and$locked.result.items[0].failureReason-eq'IOException';$quotaPass=$countStatus-eq400-and$bytesStatus-eq400
$prior.profiles.E|Add-Member -Force NoteProperty locked $locked;$prior.profiles.E|Add-Member -Force NoteProperty quotas ([pscustomobject]@{maximumCountStatus=$countStatus;maximumBytesStatus=$bytesStatus;status=if($quotaPass){'PASS'}else{'FAIL'}});$prior.profiles.E.status=if($lockedPass-and$quotaPass-and$prior.profiles.E.cancellation.result.cancellationObserved-and$prior.profiles.E.partial.state-eq'Partial'){'PASS'}else{'FAIL'};$prior.result=if(@($prior.profiles.psobject.Properties.Value|Where-Object status -ne PASS).Count-eq0){'PASS'}else{'FAIL'};$prior|ConvertTo-Json -Depth 100|Set-Content artifacts/sprint22-windows-forensic-collection.json -Encoding utf8
[pscustomobject]@{lockedState=$locked.state;lockedFailure=$locked.result.items[0].failureReason;maximumCountStatus=$countStatus;maximumBytesStatus=$bytesStatus;result=$prior.profiles.E.status}|ConvertTo-Json
if($prior.profiles.E.status-ne'PASS'){exit 1}
