param([string]$BaseUrl='http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function Login{$x=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);@{Authorization="Bearer $($x.access_token)"}}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt([string]$tid,[string]$subject){$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub=$subject;tid=$tid;per=@('platform:admin','response:read');pty='user';iat=$n;exp=$n+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};"$h.$b.$s"}
function Status([string]$path,$headers=$null){try{$p=@{Uri="$BaseUrl$path";UseBasicParsing=$true};if($headers){$p.Headers=$headers};(Invoke-WebRequest @p).StatusCode}catch{[int]$_.Exception.Response.StatusCode}}
function GetApi($path,$headers){(Invoke-RestMethod "$BaseUrl$path" -Headers $headers).data}
$admin=Login;$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;$approver=@{Authorization="Bearer $(Jwt $tenant 'sprint26-separated-approver')"}
$endpoint=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select e.id from platform.endpoints e join platform.agents a on a.tenant_id=e.tenant_id and a.endpoint_id=e.id where e.tenant_id='$tenant' order by e.last_seen_at desc nulls last limit 1;").Trim();if(!$endpoint){throw'No controlled endpoint exists.'}
$first=(Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/self-protection/self-test?endpoint=$endpoint" -Headers $admin).data
$statusBefore=GetApi "/api/v1/endpoints/$endpoint/self-protection" $admin;$resources=GetApi "/api/v1/endpoints/$endpoint/self-protection/resources" $admin;$eventsBefore=@(GetApi "/api/v1/endpoints/$endpoint/self-protection/tamper-events?limit=100" $admin);$health=GetApi '/api/v1/self-protection/health' $admin
$maintenance=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/self-protection/maintenance" -Headers $admin -ContentType application/json -Body(@{endpointId=$endpoint;installationId=$statusBefore.installationId;reason='Controlled Sprint 26 maintenance authorization';capabilities=@('controlled-troubleshooting');startsAt=[DateTimeOffset]::UtcNow.ToString('o');expiresAt=[DateTimeOffset]::UtcNow.AddMinutes(5).ToString('o')}|ConvertTo-Json -Compress);$maintenance=$maintenance.data
$approved=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/self-protection/maintenance/$($maintenance.maintenanceId):approve" -Headers $approver -ContentType application/json -Body(@{requestHash=$maintenance.requestHash;reason='Separated exact-scope Sprint 26 approval'}|ConvertTo-Json -Compress)).data
$repair=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/self-protection/repairs" -Headers $admin -ContentType application/json -Body(@{endpointId=$endpoint;installationId=$statusBefore.installationId;resourceId='service';reason='Controlled bounded service repair request'}|ConvertTo-Json -Compress)).data
$second=(Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/self-protection/self-test?endpoint=$endpoint" -Headers $admin).data;$eventsAfter=@(GetApi "/api/v1/endpoints/$endpoint/self-protection/tamper-events?limit=100" $admin);$statusPreRestart=GetApi "/api/v1/endpoints/$endpoint/self-protection" $admin
$other=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$other',organization_id,'Sprint26 isolation','local','active' from platform.tenants limit 1 on conflict do nothing"|Out-Null;$foreign=@{Authorization="Bearer $(Jwt $other 'sprint26-foreign')"}
$security=[ordered]@{unauthenticated=(Status "/api/v1/endpoints/$endpoint/self-protection")-eq401;foreignTenant=(Status "/api/v1/endpoints/$endpoint/self-protection" $foreign)-eq404;randomEndpoint=(Status "/api/v1/endpoints/$([guid]::NewGuid())/self-protection" $admin)-eq404;separatedApproval=$approved.requester-ne$approved.approver;signedApproval=$approved.signature.Length-gt64;arbitraryRepairAbsent=$repair.result-eq'pending-agent-verification';privilegedPreventionNotOverclaimed=-not$first.security.privilegedTerminationPreventionClaimed;privateKeyNotExposed=-not$first.security.privateKeyExposed}
docker compose --env-file .env -f deployment/docker-compose.yml restart gateway|Out-Null;$deadline=(Get-Date).AddSeconds(90);do{Start-Sleep 2;try{$null=Invoke-RestMethod "$BaseUrl/health/ready" -TimeoutSec 2;break}catch{}}while((Get-Date)-lt$deadline);$admin=Login;$statusAfter=GetApi "/api/v1/endpoints/$endpoint/self-protection" $admin;$eventsRestart=@(GetApi "/api/v1/endpoints/$endpoint/self-protection/tamper-events?limit=100" $admin)
$sql=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select (select count(*) from platform.agent_protection_policies where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_protection_snapshots where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_tamper_events where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_maintenance_authorizations where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_protection_repairs where tenant_id='$tenant')||'|'||(select count(*) from platform.agent_protection_audit where tenant_id='$tenant')||'|'||(select count(*) from platform.alerts where tenant_id='$tenant' and alert_data->>'category'='agent-tamper');").Trim().Split('|')
$outbox=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Trim();$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($nats.account_details.stream_detail.consumer_detail);$pending=[long](($consumers|Measure-Object num_pending -Sum).Sum);$ack=[long](($consumers|Measure-Object num_ack_pending -Sum).Sum);$redelivered=[long](($consumers|Measure-Object num_redelivered -Sum).Sum)
$profiles=[ordered]@{};$first.profiles.psobject.Properties|ForEach-Object{$profiles[$_.Name]=[bool]$_.Value};$report=[ordered]@{schemaVersion='sprint26-self-protection-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');endpointId=$endpoint;profiles=$profiles;production=[ordered]@{policyVersion=$statusAfter.policyVersion;resources=$resources.resources.Count;observed=$resources.observed.Count;snapshot=$statusAfter.snapshotHash;state=$statusAfter.state;tamperPack=@($first.tamperPack);events=$eventsRestart.Count;alertCount=[int]$sql[6];restartRetained=$statusAfter.snapshotHash-eq$statusPreRestart.snapshotHash;duplicateEventStable=$eventsAfter.Count-eq$eventsBefore.Count-and$eventsRestart.Count-eq$eventsAfter.Count};maintenance=[ordered]@{id=$approved.maintenanceId;requester=$approved.requester;approver=$approved.approver;state=$approved.state;capabilities=$approved.capabilities;signed=$approved.signature.Length-gt64};repair=$repair;security=$security;postgres=[ordered]@{policies=[int]$sql[0];snapshots=[int]$sql[1];events=[int]$sql[2];maintenance=[int]$sql[3];repairs=[int]$sql[4];audit=[int]$sql[5]};transport=[ordered]@{outbox=$outbox;natsPending=$pending;natsAckPending=$ack;natsRedelivered=$redelivered};passed=@($profiles.GetEnumerator()|Where-Object{-not$_.Value}).Count-eq0-and@($security.GetEnumerator()|Where-Object{-not$_.Value}).Count-eq0-and$resources.resources.Count-eq19-and$resources.observed.Count-eq19-and$eventsRestart.Count-ge1-and[int]$sql[6]-ge1-and$statusAfter.snapshotHash-eq$statusPreRestart.snapshotHash-and$eventsAfter.Count-eq$eventsBefore.Count-and$outbox-eq'0|0'-and$pending-eq0-and$ack-eq0}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint26-self-protection-validation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 26 production self-protection validation failed.'}
