$ErrorActionPreference='Stop'
$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|ForEach-Object{if($_ -match '^([^#=]+)=(.*)$'){$cfg[$matches[1]]=$matches[2]}}
$startupDeadline=[DateTimeOffset]::UtcNow.AddMinutes(2);do{try{$startupReady=(Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing).StatusCode-eq 200}catch{$startupReady=$false};if(!$startupReady){Start-Sleep 1}}while(!$startupReady-and[DateTimeOffset]::UtcNow-lt$startupDeadline);if(!$startupReady){throw 'Gateway did not become ready'}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json)
$h=@{Authorization="Bearer $($login.access_token)"};$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID
function Api($method,$path,$body=$null,$headers=$h){$p=@{Method=$method;Uri="http://localhost:8080$path";Headers=$headers};if($null-ne$body){$p.ContentType='application/json';$p.Body=$body|ConvertTo-Json -Depth 40 -Compress};try{(Invoke-RestMethod @p).data}catch{throw "API $method $path failed: $($_.ErrorDetails.Message) body=$($p.Body)"}}
function Status($method,$path,$body=$null,$headers=$h){try{$p=@{Method=$method;Uri="http://localhost:8080$path";Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$p.ContentType='application/json';$p.Body=$body|ConvertTo-Json -Depth 40 -Compress};(Invoke-WebRequest @p).StatusCode}catch{[int]$_.Exception.Response.StatusCode}}
function Check($name,$ok,$evidence){[ordered]@{name=$name;status=if($ok){'PASS'}else{'FAIL'};evidence=$evidence}}
function B64([byte[]]$b){[Convert]::ToBase64String($b).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Token($tid,$permissions=@('platform:admin')){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$head=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$payload=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint15-security';tid=$tid;per=$permissions;pty='user';iat=$now;exp=$now+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$mac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{"$head.$payload.$(B64($mac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$head.$payload"))))"}finally{$mac.Dispose()}}
function TransitionAlert($id,$status,$reason){Api Post "/api/v1/alerts/$id`:status" @{status=$status;reason=$reason}}
function TransitionIncident($id,$status,$reason){Api Post "/api/v1/incidents/$id`:status" @{status=$status;reason=$reason}}

$profiles=[Collections.Generic.List[object]]::new();$checks=[Collections.Generic.List[object]]::new()
$run=[guid]::NewGuid().ToString('N');$seed=Api Post "/internal/v1/triage:seed-controlled?run=$run"
$dedup=Api Get "/api/v1/alerts/$($seed.duplicate.alertId)";$single=Api Get "/api/v1/alerts/$($seed.related.alertId)"
$profiles.Add((Check 'Profile A - production finding to exact alert' ($single.repeatCount-eq 1-and$single.sourceFindingHistory.Count-eq 1-and$single.evidence.rawEventIds.Count-eq 1-and$single.evidence.evidenceReferences.Count-eq 1-and$single.alertType-eq'DetectionFinding') @{alertId=$single.alertId;findingId=$single.sourceFindingId;evidence=$single.evidence.evidenceReferences}))
$profiles.Add((Check 'Profile B - bounded deterministic deduplication' ($seed.deduplicated-and$seed.exactEvidence-and$dedup.repeatCount-eq 2-and$dedup.sourceFindingHistory.Count-eq 2-and$dedup.evidence.rawEventIds.Count-eq 2-and$dedup.auditHistory.action-contains'alert.deduplicated') @{alertId=$dedup.alertId;repeatCount=$dedup.repeatCount;sourceFindings=$dedup.sourceFindingHistory;evidenceCount=$dedup.evidence.evidenceReferences.Count;key=$dedup.deduplicationKey;windowMinutes=$dedup.deduplicationWindowMinutes}))

$id=$single.alertId;$null=TransitionAlert $id Acknowledged 'profile-c acknowledge';$null=Api Post "/api/v1/alerts/$id`:assign" @{assignee='sprint15-analyst';team='soc';reason='profile-c assignment'};$null=TransitionAlert $id Investigating 'profile-c investigation';$null=Api Post "/api/v1/alerts/$id`:disposition" @{disposition='ConfirmedMalicious';reason='exact evidence verified'};$null=Api Post "/api/v1/alerts/$id/comments" @{kind='Investigation';content='Controlled evidence reviewed and preserved.'};$null=TransitionAlert $id Resolved 'profile-c resolved';$null=TransitionAlert $id Closed 'profile-c closed';$null=TransitionAlert $id Investigating 'profile-c reopened';$life=Api Get "/api/v1/alerts/$id";$audit=Api Get "/api/v1/alerts/$id/timeline"
$requiredActions=@('alert.created','alert.status.changed','alert.assignment.changed','alert.disposition.changed','alert.note.added');$missingActions=@($requiredActions|Where-Object{$_-notin$audit.action})
$profiles.Add((Check 'Profile C - complete alert lifecycle' ($life.currentStatus-eq'Investigating'-and$life.disposition-eq'ConfirmedMalicious'-and$life.reopenCount-eq 1-and$life.acknowledgedAt-and$life.assignedAt-and$life.investigationStartedAt-and$life.closedAt-eq$null-and$missingActions.Count-eq 0-and$life.comments.Count-eq 1) @{status=$life.currentStatus;disposition=$life.disposition;version=$life.version;reopens=$life.reopenCount;auditEvents=$audit.Count;missingActions=$missingActions}))

$incident=Api Post '/api/v1/incidents:auto-group' @{alertIds=@($dedup.alertId,$life.alertId);policy='strong-evidence.v1'};$incidentId=$incident.incidentId;$timeline=Api Get "/api/v1/incidents/$incidentId/timeline";$pivots=Api Get "/api/v1/incidents/$incidentId/pivots"
$profiles.Add((Check 'Profile D - strong-evidence incident grouping' ($incident.alertIds.Count-eq 2-and$incident.endpointIds.Count-eq 1-and$incident.evidenceReferences.Count-eq 3-and$incident.mitreTechniques-contains'T1204.002'-and$incident.groupingReason-like'same-endpoint*'-and$timeline.alerts.Count-eq 2-and$pivots.processTrees.Count-ge 1) @{incidentId=$incidentId;alerts=$incident.alertIds;groupingReason=$incident.groupingReason;evidence=$incident.evidenceReferences.Count;timelineAlerts=$timeline.alerts.Count;mitre=$incident.mitreTechniques}))

$other=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select id from platform.tenants where id<>'$tenant' limit 1;").Trim();$h2=@{Authorization="Bearer $(Token $other)"};$readOnly=@{Authorization="Bearer $(Token $tenant @('alert:read','incident:read'))"}
$tenantStatuses=[ordered]@{alert=(Status Get "/api/v1/alerts/$($dedup.alertId)" $null $h2);incident=(Status Get "/api/v1/incidents/$incidentId" $null $h2);comment=(Status Post "/api/v1/alerts/$($dedup.alertId)/comments" @{kind='Comment';content='foreign'} $h2);audit=(Status Get "/api/v1/alerts/$($dedup.alertId)/timeline" $null $h2);export=(Status Post '/api/v1/alert-exports' @{format='jsonl';objectId=$dedup.alertId;maximumRecords=1} $h2);unauthorizedAssign=(Status Post "/api/v1/alerts/$($dedup.alertId)`:assign" @{assignee='x';reason='forbidden'} $readOnly)}
$profiles.Add((Check 'Profile E - tenant and authorization isolation' ($tenantStatuses.alert-eq 404-and$tenantStatuses.incident-eq 404-and$tenantStatuses.comment-in@(403,404)-and$tenantStatuses.audit-eq 404-and$tenantStatuses.export-in@(403,404)-and$tenantStatuses.unauthorizedAssign-eq 403) $tenantStatuses))

$null=Api Post "/api/v1/incidents/$incidentId/comments" @{kind='Handoff';content='State must survive the controlled gateway restart.'};$beforeAlerts=(Api Get '/api/v1/alerts?pageSize=200').total;$beforeIncidents=(Api Get '/api/v1/incidents?pageSize=200').total
docker compose --env-file .env -f deployment/docker-compose.yml restart gateway|Out-Null;$deadline=[DateTimeOffset]::UtcNow.AddMinutes(2);do{try{$ready=(Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing).StatusCode-eq 200}catch{$ready=$false};if(!$ready){Start-Sleep 1}}while(!$ready-and[DateTimeOffset]::UtcNow-lt$deadline)
$afterAlert=Api Get "/api/v1/alerts/$($dedup.alertId)";$afterIncident=Api Get "/api/v1/incidents/$incidentId";$afterAlerts=(Api Get '/api/v1/alerts?pageSize=200').total;$afterIncidents=(Api Get '/api/v1/incidents?pageSize=200').total;$postAudit=Api Get "/api/v1/incidents/$incidentId/timeline"
$profiles.Add((Check 'Profile F - restart and pressure durability' ($ready-and$beforeAlerts-eq$afterAlerts-and$beforeIncidents-eq$afterIncidents-and$afterAlert.repeatCount-eq 2-and$afterIncident.alertIds.Count-eq 2-and$postAudit.auditHistory.action-contains'incident.note.added') @{ready=$ready;alertsBefore=$beforeAlerts;alertsAfter=$afterAlerts;incidentsBefore=$beforeIncidents;incidentsAfter=$afterIncidents;alertVersion=$afterAlert.version;incidentVersion=$afterIncident.version;auditEvents=$postAudit.auditHistory.Count}))

$checks.Add((Check 'invalid alert state transition rejected' ((Status Post "/api/v1/alerts/$($dedup.alertId)`:close" @{disposition='Benign';reason='invalid direct close'})-eq 400) @{}))
$checks.Add((Check 'forged finding reference rejected' ((Status Post "/internal/v1/alerts/from-finding/$([guid]::NewGuid())")-eq 404) @{}))
$checks.Add((Check 'forged evidence and alert membership rejected' ((Status Post '/api/v1/incidents' @{title='Forged';summary='Forged';alertIds=@([guid]::NewGuid());groupingReason='forged'})-eq 400) @{}))
$checks.Add((Check 'mass bulk action rejected' ((Status Post '/api/v1/alerts:bulk' @{alertIds=@(1..101|ForEach-Object{[guid]::NewGuid()});mutation=@{assignee='mass';reason='abuse'}})-eq 400) @{}))
$checks.Add((Check 'oversized comment rejected' ((Status Post "/api/v1/alerts/$($dedup.alertId)/comments" @{kind='Comment';content=('a'*4097)})-eq 400) @{}))
$checks.Add((Check 'HTML and script injection rejected' ((Status Post "/api/v1/alerts/$($dedup.alertId)/comments" @{kind='Comment';content='<script>alert(1)</script>'})-eq 400) @{}))
$checks.Add((Check 'markdown link injection rejected' ((Status Post "/api/v1/alerts/$($dedup.alertId)/comments" @{kind='Comment';content='[click](javascript:alert(1))'})-eq 400) @{}))
$checks.Add((Check 'assignment enumeration requires assignment permission' ((Status Get '/api/v1/triage-assignees' $null $readOnly)-eq 403) @{}))
$checks.Add((Check 'incident self-merge rejected' ((Status Post "/api/v1/incidents/$incidentId`:merge" @{sourceIncidentId=$incidentId;reason='abuse'})-eq 400) @{}))
$checks.Add((Check 'incident invalid split rejected' ((Status Post "/api/v1/incidents/$incidentId`:split" @{alertIds=$incident.alertIds;title='abuse';reason='all alerts'})-eq 400) @{}))
$firstPage=Api Get '/api/v1/alerts?pageSize=1';$checks.Add((Check 'cursor tampering rejected' ((Status Get '/api/v1/alerts?pageSize=1&cursor=forged')-eq 400) @{validCursor=$firstPage.nextCursor}))
$checks.Add((Check 'export guessing rejected' ((Status Get "/api/v1/triage-exports/$([guid]::NewGuid())/content")-eq 404) @{}))

$alertExport=Api Post '/api/v1/alert-exports' @{format='jsonl';objectId=$dedup.alertId;maximumRecords=1};$content=Invoke-WebRequest "http://localhost:8080/api/v1/triage-exports/$($alertExport.id)/content" -Headers $h -UseBasicParsing;$manifest=Invoke-RestMethod "http://localhost:8080/api/v1/triage-exports/$($alertExport.id)/manifest" -Headers $h;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=([BitConverter]::ToString($sha.ComputeHash($content.RawContentStream.ToArray()))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}
$checks.Add((Check 'tenant-bound SHA-256 alert export' ($manifest.tenantBinding-eq$tenant-and$manifest.sha256-eq$hash-and$alertExport.sha256-eq$hash) @{id=$alertExport.id;sha256=$hash;tenant=$manifest.tenantBinding}))
$incidentExport=Api Post '/api/v1/incident-exports' @{format='csv';objectId=$incidentId;maximumRecords=1};$incidentManifest=Invoke-RestMethod "http://localhost:8080/api/v1/triage-exports/$($incidentExport.id)/manifest" -Headers $h;$checks.Add((Check 'CSV-safe incident export' ($incidentManifest.tenantBinding-eq$tenant-and$incidentManifest.objectType-eq'incident') @{id=$incidentExport.id;sha256=$incidentExport.sha256}))

$previousErrorAction=$ErrorActionPreference;$ErrorActionPreference='Continue';$null=docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "update platform.lifecycle_audit set reason='tampered' where audit_id=(select audit_id from platform.lifecycle_audit limit 1);" 2>$null;$auditTamperExit=$LASTEXITCODE;$ErrorActionPreference=$previousErrorAction
$checks.Add((Check 'database audit tampering rejected' ($auditTamperExit-ne 0) @{psqlExit=$auditTamperExit}))
$checks.Add((Check 'simulation/replay promotion fails closed' ((Status Post "/internal/v1/alerts/from-correlated-finding/$([guid]::NewGuid())")-eq 404) @{unitTest='Production findings create evidence-preserving alerts'}))
$health=Api Get '/api/v1/triage-health';$checks.Add((Check 'triage health has no entity labels' ($null-ne$health.alertsCreated-and$null-ne$health.incidentsCreated-and$null-ne$health.invalidStateTransitions) $health))

$failed=@($profiles+$checks|Where-Object{$_.status-ne'PASS'}).Count
$report=[ordered]@{schemaVersion='sprint15-triage-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');seed=@{firstAlert=$dedup.alertId;relatedAlert=$life.alertId;incident=$incidentId;endpoint=$seed.endpoint};profiles=$profiles;checks=$checks;health=$health;failed=$failed;passed=$failed-eq 0}
$report|ConvertTo-Json -Depth 30|Set-Content artifacts/sprint15-triage-validation.json -Encoding utf8
$report|ConvertTo-Json -Depth 30
if($failed){throw "Sprint 15 validation failed: $failed"}
