$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
powershell -NoProfile -ExecutionPolicy Bypass -File testing/integration/sprint12-final-reconciliation.ps1|Out-Host
$prior=Get-Content -Raw artifacts/sprint12-final-reconciliation.json|ConvertFrom-Json
function Sql([string]$q){(docker exec deployment-postgres-1 psql -U platform -d platform -Atc $q).Trim()}
function Os([string]$a){[long]((docker exec deployment-opensearch-1 curl -sf "http://localhost:9200/$a/_count"|ConvertFrom-Json).count)}
$c=(Sql "select count(*)||'|'||count(distinct correlated_finding_id)||'|'||count(*) filter(where jsonb_array_length(finding_data->'evidenceEventIds')=0 and jsonb_array_length(finding_data->'childFindingIds')=0)||'|'||(select count(*) from platform.correlation_rules where status='Active' and enabled)||'|'||(select count(*) from platform.correlation_rule_tests where passed)||'|'||(select count(*) from platform.correlation_rule_tests where not passed) from platform.correlated_findings;").Split('|')|ForEach-Object{[long]$_}
$correlationOs=Os 'platform-correlated-findings'
$g=(Sql "select (select count(*) from platform.investigation_entities)||'|'||(select count(distinct(entity_id,entity_type)) from platform.investigation_entities)||'|'||(select count(*) from platform.investigation_relationships)||'|'||(select count(distinct relationship_id) from platform.investigation_relationships)||'|'||(select count(*) from platform.investigation_relationships where cardinality(evidence_ids)=0 or cardinality(evidence_references)=0)||'|'||(select count(*) from platform.investigation_relationships r where not exists(select 1 from platform.investigation_entities e where e.tenant_id=r.tenant_id and e.entity_id=r.source_entity_id and e.entity_type=r.source_type) or not exists(select 1 from platform.investigation_entities e where e.tenant_id=r.tenant_id and e.entity_id=r.destination_entity_id and e.entity_type=r.destination_type))||'|'||(select count(distinct hunt_id) from platform.saved_hunts)||'|'||(select count(*) from platform.hunt_runs);").Split('|')|ForEach-Object{[long]$_}
$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$nats|ConvertTo-Json -Depth 30|Set-Content artifacts/sprint14-nats-jsz.json -Encoding utf8
$report=[ordered]@{schemaVersion='sprint14-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');prior=$prior;correlation=[ordered]@{postgres=$c[0];openSearch=$correlationOs;difference=$c[0]-$correlationOs;unique=$c[1];duplicates=$c[0]-$c[1];withoutEvidence=$c[2];activeRules=$c[3];passingFixtures=$c[4];failingFixtures=$c[5]};investigation=[ordered]@{entities=$g[0];uniqueEntities=$g[1];duplicateEntities=$g[0]-$g[1];relationships=$g[2];uniqueRelationships=$g[3];duplicateRelationships=$g[2]-$g[3];relationshipsWithoutEvidence=$g[4];relationshipsWithMissingEndpoint=$g[5];savedHunts=$g[6];huntRuns=$g[7]};passed=($prior.passed-and$c[0]-eq$correlationOs-and$c[0]-eq$c[1]-and$c[2]-eq0-and$c[3]-eq15-and$c[4]-eq45-and$c[5]-eq0-and$g[0]-eq$g[1]-and$g[2]-eq$g[3]-and$g[4]-eq0-and$g[5]-eq0-and$prior.outbox.pending-eq0-and$prior.outbox.failed-eq0-and$prior.nats.pending-eq0-and$prior.nats.ackPending-eq0)}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint14-final-reconciliation.json -Encoding utf8
$report|ConvertTo-Json -Depth 20
if(-not$report.passed){throw 'Sprint 14 final reconciliation failed.'}
