param([string]$BaseUrl='http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"};$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')};function Jwt([string]$tid){$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint25-foreign';tid=$tid;per=@('platform:admin','response:read');pty='user';iat=$n;exp=$n+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};"$h.$b.$s"};function Status([string]$path,$headers=$null){try{$p=@{Uri="$BaseUrl$path";UseBasicParsing=$true};if($headers){$p.Headers=$headers};(Invoke-WebRequest @p).StatusCode}catch{[int]$_.Exception.Response.StatusCode}}
$self=(Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/playbooks/self-test" -Headers $admin).data;$books=@((Invoke-RestMethod "$BaseUrl/api/v1/playbooks" -Headers $admin).data);$book=$books|Where-Object{$_.name-eq'Confirmed malicious file'}|Select-Object -First 1
$key="sprint25-$([guid]::NewGuid().ToString('N'))";$request=@{playbookId=$book.playbookId;version=1;trigger='DetectionFinding';sourceType='finding';sourceObjectId=$key;endpointId=[guid]::NewGuid().ToString('D');targetEntityId='stable-controlled-target';expectedInstallationId='controlled-installation';mode='Simulation';idempotencyKey=$key;sourceFields=@{quality='complete';actionParametersJson='{}'};recursionDepth=0;triggerLineage=@()};$first=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/playbook-executions" -Headers $admin -ContentType application/json -Body($request|ConvertTo-Json -Depth 10)).data;$duplicate=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/playbook-executions" -Headers $admin -ContentType application/json -Body($request|ConvertTo-Json -Depth 10)).data
$before=(Invoke-RestMethod "$BaseUrl/api/v1/playbook-health" -Headers $admin).data;docker compose --env-file .env -f deployment/docker-compose.yml restart gateway|Out-Null;$deadline=(Get-Date).AddSeconds(60);do{try{$null=Invoke-RestMethod "$BaseUrl/health/ready" -TimeoutSec 2;break}catch{Start-Sleep 2}}while((Get-Date)-lt$deadline);$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"};$after=(Invoke-RestMethod "$BaseUrl/api/v1/playbook-executions/$($first.executionId)" -Headers $admin).data
$other=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$other',organization_id,'Sprint25 tenant isolation','local','active' from platform.tenants limit 1 on conflict do nothing"|Out-Null;$foreign=@{Authorization="Bearer $(Jwt $other)"}
$sql=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select (select count(*) from platform.playbook_definitions where tenant_id='$tenant')||'|'||(select count(*) from platform.playbook_executions where tenant_id='$tenant')||'|'||(select count(*) from platform.playbook_execution_audit where tenant_id='$tenant')||'|'||(select count(*) from platform.playbook_work where tenant_id='$tenant' and state='pending');").Trim();$outbox=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*)||'|'||count(*) filter(where attempts>=10) from platform.outbox where published_at is null;").Trim()
$security=[ordered]@{unauthenticated=(Status '/api/v1/playbooks')-eq401;tenantExecution=(Status "/api/v1/playbook-executions/$($first.executionId)" $foreign)-eq404;randomExecution=(Status "/api/v1/playbook-executions/$([guid]::NewGuid())" $admin)-eq404;arbitraryCodeRejected=$self.security.arbitraryCodeRejected;liveResponsePrimitiveAbsent=$self.security.liveResponsePrimitiveAbsent;simulationMutations=$self.security.simulationMutations-eq0;recursionDepth=$self.security.recursionDepth-eq0}
$restart=[ordered]@{sameExecution=$first.executionId-eq$duplicate.executionId;stateRetained=$after.executionId-eq$first.executionId;completed=$after.state-eq'Succeeded';allStepsSimulated=@($after.steps|Where-Object{$_.state-ne'Simulated'}).Count-eq0;countsNotReduced=$before.triggeredExecutions-le(Invoke-RestMethod "$BaseUrl/api/v1/playbook-health" -Headers $admin).data.triggeredExecutions}
$counts=$sql.Split('|');$report=[ordered]@{schemaVersion='sprint25-playbook-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');profiles=$self.profiles;starterPlaybooks=$self.starterPlaybooks;simulation=[ordered]@{executionId=$first.executionId;state=$after.state;zeroMutation=$self.security.simulationMutations-eq0};restart=$restart;security=$security;persistence=[ordered]@{definitions=[int]$counts[0];executions=[int]$counts[1];audit=[int]$counts[2];workPending=[int]$counts[3]};outbox=$outbox;passed=@($self.profiles.psobject.Properties|Where-Object{-not $_.Value}).Count-eq0-and@($security.GetEnumerator()|Where-Object{-not $_.Value}).Count-eq0-and@($restart.GetEnumerator()|Where-Object{-not $_.Value}).Count-eq0-and[int]$counts[0]-ge6-and[int]$counts[2]-gt0-and[int]$counts[3]-eq0-and$outbox-eq'0|0'};$report|ConvertTo-Json -Depth 15|Set-Content artifacts/sprint25-playbook-validation.json -Encoding utf8;$report|ConvertTo-Json -Depth 15;if(-not$report.passed){throw'Sprint 25 playbook validation failed.'}
