$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '../..');Set-Location $root;$settings=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$settings[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}function Jwt{$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint21-live-approver';tid=$settings.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('platform:admin');pty='user';iat=$now;exp=$now+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($settings.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes($h+'.'+$p)))}finally{$m.Dispose()};@{Authorization="Bearer $h.$p.$s"}}
function Api([string]$method,[string]$path,$headers=$admin,$body=$null){$a=@{Method=$method;Uri="http://127.0.0.1:8080$path";Headers=$headers};if($null-ne$body){$a.ContentType='application/json';$a.Body=$body|ConvertTo-Json -Depth 20 -Compress};try{(Invoke-RestMethod @a).data}catch{$detail='';try{$reader=[IO.StreamReader]::new($_.Exception.Response.GetResponseStream());$detail=$reader.ReadToEnd();$reader.Dispose()}catch{};throw "$method $path failed: $detail"}}
$endpoint=node -p "require('./artifacts/sprint21-windows-persistence-response.json').victim.endpointId";$entity=node -p "require('./artifacts/sprint21-windows-persistence-response.json').profiles.A.preview.target.persistenceEntityId"
$existing=Api GET "/api/v1/live-response/sessions?endpointId=$endpoint";foreach($item in @($existing|Where-Object{$_.state-notin@('Closed','Expired','Rejected')})){try{$null=Api POST "/api/v1/live-response/sessions/$($item.sessionId):close" $admin @{reason='close incomplete Sprint 21 qualification session'}}catch{}}
$session=Api POST '/api/v1/live-response/sessions' $admin @{endpointId=$endpoint;capabilities=@('builtin');idleTimeoutSeconds=300;absoluteLifetimeSeconds=600;sourceEntityId=$entity;policyVersion='live-response-policy.v1'};if($session.state-eq'PendingApproval'){$null=Api POST "/api/v1/live-response/sessions/$($session.sessionId):approve" (Jwt) @{capabilityHash=$session.capabilityHash;reason='Sprint 21 typed integration qualification'}};$deadline=(Get-Date).AddSeconds(90);do{Start-Sleep 1;$active=Api GET "/api/v1/live-response/sessions/$($session.sessionId)"}while($active.state-ne'Active'-and(Get-Date)-lt$deadline);if($active.state-ne'Active'){throw 'Live Response session did not activate'}
$preview=Api POST "/api/v1/live-response/sessions/$($session.sessionId)/commands" $admin @{commandType='BuiltIn';input="persistence-info $entity";timeoutSeconds=30};$null=Api POST "/api/v1/live-response/sessions/$($session.sessionId):close" $admin @{reason='Sprint 21 qualification complete'}
$passed=$preview.schemaVersion-eq'persistence-remediation.v1'-and$preview.target.persistenceEntityId-eq$entity;$report=[ordered]@{schemaVersion='sprint21-live-response-integration.v1';capturedAt=[DateTimeOffset]::UtcNow;sessionId=$session.sessionId;endpointId=$endpoint;entityId=$entity;typedCommand='persistence-info';returnedSchema=$preview.schemaVersion;returnedCanonicalIdentity=$preview.target.canonicalIdentity;passed=$passed};$report|ConvertTo-Json -Depth 10|Set-Content artifacts/sprint21-live-response.json -Encoding utf8;$report|ConvertTo-Json;if(!$passed){exit 1}
