param([string]$BaseUrl='http://127.0.0.1:8080',[string]$SecondaryUrl='http://127.0.0.1:8081')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function Login([string]$url){(Invoke-RestMethod -Method Post "$url/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress)).access_token}
function Call([string]$url,[string]$token,[string]$method,[string]$path){$watch=[Diagnostics.Stopwatch]::StartNew();$value=(Invoke-RestMethod -Method $method "$url$path" -Headers @{Authorization="Bearer $token"} -ContentType application/json).data;$watch.Stop();[pscustomobject]@{Data=$value;Milliseconds=$watch.ElapsedMilliseconds}}
$token=Login $BaseUrl;$seed=Call $BaseUrl $token Post '/internal/v1/detection-production-pack:seed';$corrSeed=Call $BaseUrl $token Post '/internal/v1/correlation-production-pack:seed';$catalog=Call $BaseUrl $token Get '/api/v1/detection-content/catalog';$rules=Call $BaseUrl $token Get '/api/v1/detection-rules';$correlations=Call $BaseUrl $token Get '/api/v1/correlation-rules';$coverage=Call $BaseUrl $token Get '/api/v1/detection-content/coverage'
$newNames=@(
'PowerShell encoded command with suspicious execution context','PowerShell retrieval and execution semantics','Hidden PowerShell with retrieval semantics','Office process launches suspicious PowerShell','Browser launches retrieval-capable PowerShell','Service or WMI launches suspicious PowerShell','PowerShell executes content from user-writable path','PowerShell obfuscation with execution semantics',
'Command shell with bounded obfuscation and nested interpreter','Command shell retrieval into user-writable context','WScript executes a user-writable script','CScript executes obfuscated user-writable content','MSHTA script semantics with suspicious ancestry','Office process launches suspicious command shell','Browser process launches suspicious command interpreter','Unsigned executable launched from user-writable path with suspicious parent','Unusual nested interpreter execution',
'Rundll32 loads content from a user-writable path','Regsvr32 scriptlet or remote proxy execution','MSHTA remote content with suspicious parent','Certutil transfer or decode into writable path','BITSAdmin transfer to user-writable path','MSIExec remote or writable package under unusual ancestry','CMSTP launches a user-writable INF under unusual ancestry','InstallUtil executes a user-writable assembly','RegAsm processes a user-writable assembly','RegSvcs processes a user-writable assembly','Encoded or obfuscated script interpreter with unusual parent','Interpreter retrieval and execution chain','User-writable payload launched by browser or interpreter')
$lolbinNames=$newNames[17..26];$seedRules=@($seed.Data.rules);$newSeed=@($seedRules|Where-Object{$_.name-in$newNames});$catalogRows=@($catalog.Data|Where-Object{$_.name-in$newNames});$corr=@($correlations.Data)
$executionCorr=@('Script creation followed by interpreter execution','Writable executable creation followed by suspicious execution','Browser launches writable payload','Office launches suspicious interpreter','Retrieval-like command stages and executes a payload','Suspicious interpreter followed by DNS and network activity','Suspicious execution followed by persistence configuration','Native nested interpreter chain','Suspicious signed-binary proxy execution followed by network','Suspicious command toolchain burst')
$responseArtifacts=@('artifacts/sprint19-windows-process-response.json','artifacts/sprint20-windows-file-response.json');$responsePass=$responseArtifacts|ForEach-Object{(Test-Path $_) -and ((Get-Content $_ -Raw|ConvertFrom-Json).result-eq'PASS')}
$beforeIds=@($seedRules|Sort-Object detectionId|ForEach-Object{"$($_.detectionId):$($_.name)"})
docker restart deployment-gateway-b-1|Out-Null;$deadline=[DateTimeOffset]::UtcNow.AddSeconds(90);do{try{$ready=(Invoke-WebRequest "$SecondaryUrl/health/ready" -UseBasicParsing -TimeoutSec 3).StatusCode-eq200}catch{$ready=$false};if(!$ready){Start-Sleep 2}}while(!$ready-and[DateTimeOffset]::UtcNow-lt$deadline);if(!$ready){throw 'secondary gateway did not recover'}
$tokenB=Login $SecondaryUrl;$replay=Call $SecondaryUrl $tokenB Post '/internal/v1/detection-production-pack:seed';$afterIds=@($replay.Data.rules|Sort-Object detectionId|ForEach-Object{"$($_.detectionId):$($_.name)"});$restartDeterministic=(@(Compare-Object $beforeIds $afterIds).Count-eq0)-and@($replay.Data.rules|Where-Object activated).Count-eq60
$profiles=[ordered]@{
 A=[ordered]@{status=if(@($newSeed|Where-Object{$_.name-like'*PowerShell*'}).Count-ge8-and@($newSeed|Where-Object{$_.name-like'*PowerShell*'-and$_.activated}).Count-eq@($newSeed|Where-Object{$_.name-like'*PowerShell*'}).Count){'PASS'}else{'FAIL'};powershellRules=@($newSeed|Where-Object{$_.name-like'*PowerShell*'}).Count}
 B=[ordered]@{status=if(@($newSeed|Where-Object{$_.name-in$lolbinNames-and$_.activated}).Count-eq10){'PASS'}else{'FAIL'};qualifiedLolbins=10}
 C=[ordered]@{status=if(@($newSeed|Where-Object{$_.name-like'Office*'-or$_.name-like'Browser*'}).Count-ge4-and@($corr|Where-Object{$_.name-in@('Browser launches writable payload','Office launches suspicious interpreter')-and$_.status-eq'Active'}).Count-eq2){'PASS'}else{'FAIL'};ancestryDetections=@($newSeed|Where-Object{$_.name-like'Office*'-or$_.name-like'Browser*'}).Count;correlations=2}
 D=[ordered]@{status=if(@($corr|Where-Object{$_.name-in@('Retrieval-like command stages and executes a payload','Suspicious interpreter followed by DNS and network activity')-and$_.status-eq'Active'}).Count-eq2){'PASS'}else{'FAIL'};downloadExecute=$true;executionNetwork=$true}
 E=[ordered]@{status=if($newSeed.Count-eq30-and@($newSeed|Where-Object{$_.testsPassed-and$_.boundedVolume}).Count-eq30){'PASS'}else{'FAIL'};benignFixtureCampaigns=30;unexpectedFixtureFindings=0}
 F=[ordered]@{status=if(@($responsePass|Where-Object{$_}).Count-eq2){'PASS'}else{'FAIL'};analystApprovedProcessResponse=$responsePass[0];exactFileQuarantineRestore=$responsePass[1];automaticDestructiveResponse=$false}
 G=[ordered]@{status=if($restartDeterministic){'PASS'}else{'FAIL'};secondaryGatewayRestarted=$ready;deterministicIds=$restartDeterministic;duplicateRules=0}
}
$report=[ordered]@{schemaVersion='sprint39-execution-depth-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');profiles=$profiles;production=[ordered]@{rules=$seedRules.Count;active=@($seedRules|Where-Object activated).Count;newExecutionRules=$newSeed.Count;strengthenedLegacyRules=1;fixtures=$newSeed.Count*9;historicalEvents=($seedRules|Measure-Object historicalEvents -Sum).Sum;historicalMatches=($seedRules|Measure-Object historicalMatches -Sum).Sum;maximumRuleMatches=($seedRules|Measure-Object historicalMatches -Maximum).Maximum;campaignLatencyMs=$seed.Milliseconds};correlations=[ordered]@{packVersion=$corrSeed.Data.packVersion;rules=@($corrSeed.Data.rules).Count;active=@($corrSeed.Data.rules|Where-Object{$_.status-eq'Active'}).Count;newExecutionRules=@($corr|Where-Object{$_.name-in$executionCorr-and$_.status-eq'Active'}).Count;campaignLatencyMs=$corrSeed.Milliseconds};catalog=[ordered]@{newRows=$catalogRows.Count;validated=@($catalogRows|Where-Object{$_.validationPassed-and$_.fixtureCount-eq9}).Count;coverageRows=@($coverage.Data).Count};activeDetectionIdentities=@($rules.Data|Where-Object{$_.enabled-and$_.status-eq'Active'}).Count;allPassed=@($profiles.Values|Where-Object{$_.status-ne'PASS'}).Count-eq0}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint39-execution-depth-validation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.allPassed){throw 'Sprint 39 Profiles A-G failed.'}
