param([string]$Output='artifacts/sprint11-execution-api-matrix.json')
$ErrorActionPreference='Stop'; Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
$cfg=@{}; Get-Content .env|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]}
function B64([byte[]]$b){[Convert]::ToBase64String($b).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt($tenant){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint11-tenant-b';tid=$tenant;per=@('platform:admin');pty='user';iat=$now;exp=$now+3600;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$mac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));"$h.$p.$(B64($mac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$p"))))"}
function Req($method,$uri,$headers,$body=$null){$x=@{Method=$method;Uri=$uri;Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$x.ContentType='application/json';$x.Body=$body|ConvertTo-Json -Depth 20 -Compress};try{$r=Invoke-WebRequest @x;[pscustomobject]@{status=[int]$r.StatusCode;text=$r.Content}}catch{$s=if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{0};[pscustomobject]@{status=$s;text=''}}}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$a=@{Authorization="Bearer $($login.access_token)"}
$page=(Invoke-RestMethod 'http://localhost:8080/api/v1/execution-events?pageSize=500' -Headers $a).data;$event=@($page.items|Where-Object{$_.thread-and$_.targetProcess}|Select-Object -First 1)[0];if(!$event){throw'Populated Sprint 11 native execution evidence is missing.'};$endpoint=$event.endpointId;$entity=$event.thread.threadEntityId;$process=$event.targetProcess.processEntityId
$checks=[ordered]@{}
$checks.search=@($page.items).Count-gt0-and(Req GET "http://localhost:8080/api/v1/execution-events?endpointId=$endpoint&targetPid=$($event.targetProcess.processId)&threadId=$($event.thread.threadId)&kind=ThreadCreated&pageSize=50" $a).status-eq200
$first=(Invoke-RestMethod 'http://localhost:8080/api/v1/execution-events?pageSize=1' -Headers $a).data;$second=(Invoke-RestMethod "http://localhost:8080/api/v1/execution-events?pageSize=1&cursor=$([uri]::EscapeDataString($first.nextCursor))" -Headers $a).data;$checks.cursorPagination=@($first.items).Count-eq1-and@($second.items).Count-eq1-and$first.items[0].eventId-ne$second.items[0].eventId
$checks.cursorTamper=(Req GET 'http://localhost:8080/api/v1/execution-events?pageSize=1&cursor=v1.tampered.invalid' $a).status-eq400
$checks.detail=(Req GET "http://localhost:8080/api/v1/execution-events/$($event.eventId)" $a).status-eq200
$checks.history=(Req GET "http://localhost:8080/api/v1/execution-entities/$entity/history?endpointId=$endpoint" $a).status-eq200
$checks.timeline=(Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/execution-timeline?pageSize=50" $a).status-eq200
$pv=Req GET "http://localhost:8080/api/v1/processes/$process/execution?endpointId=$endpoint&pageSize=50" $a;$checks.processView=$pv.status-eq200-and@((ConvertFrom-Json $pv.text).data.items).Count-gt0
$health=Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/execution-telemetry-health" $a;$hd=(ConvertFrom-Json $health.text).data;$checks.health=$health.status-eq200-and$hd.threadCreations-gt0-and$hd.PSObject.Properties.Name-contains'projectionLatencyMilliseconds'-and$hd.PSObject.Properties.Name-contains'searchLatencyMilliseconds'
$job=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/execution-exports -Headers $a -ContentType application/json -Body(@{format='jsonl';query=@{endpointId=$endpoint};fields=@();maximumRecords=10000}|ConvertTo-Json -Depth 8)).data;$limit=[DateTimeOffset]::UtcNow.AddSeconds(45);do{Start-Sleep -Milliseconds 300;$job=(Invoke-RestMethod "http://localhost:8080/api/v1/execution-exports/$($job.id)" -Headers $a).data}while($job.state-in@('Pending','Running')-and[DateTimeOffset]::UtcNow-lt$limit);$manifest=Req GET "http://localhost:8080/api/v1/execution-exports/$($job.id)/manifest" $a;$manifestData=$manifest.text|ConvertFrom-Json;$signed=(Invoke-RestMethod -Method Post "http://localhost:8080/api/v1/execution-exports/$($job.id)/download-url" -Headers $a -ContentType application/json -Body '{"expiresInSeconds":30}').data;$download=Req GET $signed.url @{};$checks.asyncExport=$job.state-eq'Completed'-and$job.recordCount-gt0-and$job.outputSha256-match'^[0-9a-f]{64}$'-and$manifest.status-eq200-and$manifestData.memoryContentsIncluded-eq$false-and$download.status-eq200
$tenantB=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$tenantB',organization_id,'Sprint11 Tenant B','local','active' from platform.tenants limit 1"|Out-Null;$b=@{Authorization="Bearer $(Jwt $tenantB)"};$bs=Req GET http://localhost:8080/api/v1/execution-events $b;$bd=Req GET "http://localhost:8080/api/v1/execution-events/$($event.eventId)" $b;$be=Req GET "http://localhost:8080/api/v1/execution-exports/$($job.id)/content" $b;$checks.tenantIsolation=$bs.status-eq200-and@((ConvertFrom-Json $bs.text).data.items).Count-eq0-and$bd.status-eq404-and$be.status-eq404
$invalidPolicy=@{name='invalid';policy=@{excludedSourceProcesses=@('*');maximumQueueBytes=134217728;maximumQueueAgeHours=24;maximumBatchEvents=200;maximumBatchBytes=1048576;flushSeconds=5;maximumEventsPerSecond=2000}};$checks.securityBoundaries=(Req GET http://localhost:8080/api/v1/execution-events @{}).status-eq401-and(Req GET "http://localhost:8080/api/v1/execution-entities/not-a-hash/history?endpointId=$endpoint" $a).status-eq400-and(Req POST http://localhost:8080/api/v1/execution-telemetry/policies $a $invalidPolicy).status-eq400
$failed=@($checks.GetEnumerator()|Where-Object{-not$_.Value});$report=[ordered]@{schema='platform.sprint11.execution-api-matrix.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');endpointId=$endpoint;eventId=$event.eventId;threadEntityId=$entity;processEntityId=$process;exportId=$job.id;tenantB=$tenantB;checks=$checks;passed=$failed.Count-eq0};$report|ConvertTo-Json -Depth 10|Set-Content $Output -Encoding utf8;$report|ConvertTo-Json -Depth 6;if($failed.Count){exit 1}
