param([string]$BaseUrl = 'http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"};$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt([string]$tid){$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint24-foreign';tid=$tid;per=@('platform:admin');pty='user';iat=$n;exp=$n+900;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{$s=B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b")))}finally{$m.Dispose()};"$h.$b.$s"}
function Status([string]$path,$headers=$null){try{$p=@{Uri="$BaseUrl$path";UseBasicParsing=$true};if($headers){$p.Headers=$headers};(Invoke-WebRequest @p).StatusCode}catch{[int]$_.Exception.Response.StatusCode}}
$self=(Invoke-RestMethod -Method Post "$BaseUrl/internal/v1/tunnels/self-test" -Headers $admin).data
$endpoint=$self.chain.endpointId;$findings=(Invoke-RestMethod "$BaseUrl/api/v1/tunnels/findings?endpointId=$endpoint&pageSize=100" -Headers $admin).data.items;$finding=$findings|Select-Object -First 1
$graph=(Invoke-RestMethod "$BaseUrl/api/v1/entities/TunnelFinding/$($finding.findingId)/neighbors" -Headers $admin).data;$graphQuery=@{rootEntityId=$finding.findingId;rootType='TunnelFinding';maximumDepth=3;maximumNodes=100;maximumEdges=200;maximumExpansionPerNode=50;timeoutMilliseconds=5000;pageSize=100};$story=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/attack-stories/$($finding.findingId)" -Headers $admin -ContentType application/json -Body($graphQuery|ConvertTo-Json)).data;$now=[DateTimeOffset]::UtcNow;$hunt=@{schemaVersion='threat-hunt.v1';huntId=[guid]::NewGuid().ToString('D');version=1;tenantId=$tenant;name='Sprint24 tunnel hunt';description='bounded tunnel finding hunt';entityTypes=@('TunnelFinding');from=$now.AddHours(-1).ToString('o');to=$now.AddHours(1).ToString('o');where=@{boolean='And';predicate=@{field='tunnelKind';operator='Exists';values=@('true')};children=@()};maximumResults=100;timeoutMilliseconds=5000;maximumJoinDepth=1;joinRelationships=@('evidence-for');enabled=$true;owner='sprint24';sharedWith=@();createdAt=$now.ToString('o')};$huntValidation=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/threat-hunts:validate" -Headers $admin -ContentType application/json -Body($hunt|ConvertTo-Json -Depth 12)).data;$alerts=@((Invoke-RestMethod "$BaseUrl/api/v1/alerts?pageSize=200" -Headers $admin).data.items|Where-Object{$_.category-eq'tunnel'})
$other=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$other',organization_id,'Sprint24 tenant isolation','local','active' from platform.tenants limit 1 on conflict do nothing"|Out-Null;$foreign=@{Authorization="Bearer $(Jwt $other)"}
$foreignSearchStatus=Status '/api/v1/tunnels/findings?pageSize=100' $foreign
$foreignSearchEmpty=$foreignSearchStatus-in@(403,404)
if($foreignSearchStatus-eq200){$foreignSearchEmpty=@((Invoke-RestMethod "$BaseUrl/api/v1/tunnels/findings?pageSize=100" -Headers $foreign).data.items).Count-eq0}
$foreignDetailStatus=Status "/api/v1/tunnels/findings/$($finding.findingId)" $foreign
$security=[ordered]@{unauthenticated=(Status '/api/v1/tunnels/findings')-eq401;tenantSearch=$foreignSearchEmpty;tenantDetail=$foreignDetailStatus-in@(403,404);cursorTamper=(Status '/api/v1/tunnels/findings?cursor=forged' $admin)-eq400;depthBound=(Status "/api/v1/tunnels/observations/$($self.chain.observationIds[0])/chain?maximumDepth=5" $admin)-eq400;randomId=(Status "/api/v1/tunnels/findings/$([guid]::NewGuid())" $admin)-eq404;exactEvidence=@($findings|Where-Object{@($_.evidenceIds).Count-eq0}).Count-eq0;noAutomaticResponse=$self.automaticResponse-eq$false;icmpHonest=$self.icmp-eq'NOT OBSERVABLE BY SOURCE'}
$before=(Invoke-RestMethod "$BaseUrl/api/v1/tunnels/reconciliation" -Headers $admin).data;docker compose --env-file .env -f deployment/docker-compose.yml restart gateway|Out-Null;$deadline=(Get-Date).AddSeconds(60);do{try{$null=Invoke-RestMethod "$BaseUrl/health/ready" -TimeoutSec 2;break}catch{Start-Sleep 2}}while((Get-Date)-lt$deadline);$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"};$after=(Invoke-RestMethod "$BaseUrl/api/v1/tunnels/reconciliation" -Headers $admin).data;$restartFinding=Invoke-RestMethod "$BaseUrl/api/v1/tunnels/findings/$($finding.findingId)" -Headers $admin
$limit=(Get-Date).AddSeconds(30);do{$out=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*)||'|'||count(*) filter(where attempts>=10) from platform.outbox where published_at is null;").Trim();if($out-eq'0|0'){break};Start-Sleep 1}while((Get-Date)-lt$limit)
$integration=[ordered]@{graphNodes=@($graph.nodes).Count;graphEdges=@($graph.edges).Count;storyEntities=@($story.entities).Count;storyRelationships=@($story.relationships).Count;storyTimeline=@($story.timeline).Count;huntValid=$huntValidation.valid;tunnelAlerts=$alerts.Count};$integrationPass=$integration.graphNodes-gt1-and$integration.graphEdges-gt0-and$integration.storyEntities-gt1-and$integration.storyRelationships-gt0-and$integration.storyTimeline-gt0-and$integration.huntValid-and$integration.tunnelAlerts-gt0
$report=[ordered]@{schemaVersion='sprint24-tunnel-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');tenant=$tenant;runKey=$self.runKey;profiles=$self.profiles;profileFRestart=[ordered]@{stateRetained=$restartFinding.data.findingId-eq$finding.findingId;countsStable=$before.postgres.observations-eq$after.postgres.observations-and$before.postgres.findings-eq$after.postgres.findings};dnsFeatures=$self.dnsFeatures;chain=$self.chain;integration=$integration;security=$security;reconciliation=$after;outbox=$out;passed=@($self.profiles.psobject.Properties|Where-Object{-not $_.Value}).Count-eq0-and@($security.GetEnumerator()|Where-Object{-not $_.Value}).Count-eq0-and$integrationPass-and$restartFinding.data.findingId-eq$finding.findingId-and$after.exact-and$out-eq'0|0'}
$report|ConvertTo-Json -Depth 15|Set-Content artifacts/sprint24-tunnel-validation.json -Encoding utf8;$report|ConvertTo-Json -Depth 15;if(-not$report.passed){throw'Sprint 24 tunnel validation failed.'}
