param([string]$Output='artifacts/sprint10-identity-api-matrix.json')
$ErrorActionPreference='Stop'; Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
$cfg=@{};Get-Content .env|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]}
function B64([byte[]]$b){[Convert]::ToBase64String($b).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt($tenant){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint10-tenant-b';tid=$tenant;per=@('platform:admin');pty='user';iat=$now;exp=$now+3600;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$mac=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));"$h.$p.$(B64($mac.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$p"))))"}
function Req($method,$uri,$headers,$body=$null){$x=@{Method=$method;Uri=$uri;Headers=$headers;UseBasicParsing=$true};if($null-ne$body){$x.ContentType='application/json';$x.Body=$body|ConvertTo-Json -Depth 20 -Compress};try{$r=Invoke-WebRequest @x;[pscustomobject]@{status=[int]$r.StatusCode;text=$r.Content}}catch{$s=if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{0};[pscustomobject]@{status=$s;text=''}}}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$a=@{Authorization="Bearer $($login.access_token)"}
$page=(Invoke-RestMethod 'http://localhost:8080/api/v1/identity-events?pageSize=500' -Headers $a).data;$event=@($page.items|Where-Object{$_.logon -or $_.token}|Select-Object -First 1)[0];if(!$event){throw'populated Sprint 10 identity fixture missing'};$endpoint=$event.endpointId;$entity=if($event.logon){$event.logon.entityId}elseif($event.session){$event.session.entityId}elseif($event.token){$event.token.entityId}else{$event.process.processEntityId};$process=@($page.items|Where-Object{$_.process.processEntityId}|Select-Object -First 1)[0].process.processEntityId
$checks=[ordered]@{}
$checks.search=$page.items.Count-gt0-and(Req GET 'http://localhost:8080/api/v1/identity-events?logonType=2&result=success&pageSize=50' $a).status-eq200
$firstPage=(Invoke-RestMethod 'http://localhost:8080/api/v1/identity-events?pageSize=1' -Headers $a).data;$secondPage=(Invoke-RestMethod "http://localhost:8080/api/v1/identity-events?pageSize=1&cursor=$([uri]::EscapeDataString($firstPage.nextCursor))" -Headers $a).data;$checks.cursorPagination=@($firstPage.items).Count-eq1-and@($secondPage.items).Count-eq1-and$firstPage.items[0].eventId-ne$secondPage.items[0].eventId
$checks.cursorTamper=(Req GET 'http://localhost:8080/api/v1/identity-events?pageSize=1&cursor=v1.tampered.invalid' $a).status-eq400
$checks.detail=(Req GET "http://localhost:8080/api/v1/identity-events/$($event.eventId)" $a).status-eq200
$checks.history=(Req GET "http://localhost:8080/api/v1/identity-entities/$entity/history?endpointId=$endpoint" $a).status-eq200
$checks.timeline=(Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/identity-timeline?pageSize=50" $a).status-eq200
$checks.processView=(Req GET "http://localhost:8080/api/v1/processes/$process/identity?endpointId=$endpoint" $a).status-eq200
$healthResponse=Req GET "http://localhost:8080/api/v1/endpoints/$endpoint/identity-telemetry-health" $a;$healthData=(ConvertFrom-Json $healthResponse.text).data;$checks.health=$healthResponse.status-eq200-and$healthData.searchLatencyMilliseconds-ge0-and$healthData.PSObject.Properties.Name-contains'projectionLatencyMilliseconds'
$job=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/identity-exports -Headers $a -ContentType application/json -Body(@{format='jsonl';query=@{endpointId=$endpoint};fields=@();maximumRecords=10000}|ConvertTo-Json -Depth 8)).data;$limit=[DateTimeOffset]::UtcNow.AddSeconds(45);do{Start-Sleep -Milliseconds 300;$job=(Invoke-RestMethod "http://localhost:8080/api/v1/identity-exports/$($job.id)" -Headers $a).data}while($job.state-in@('Pending','Running')-and[DateTimeOffset]::UtcNow-lt$limit);$manifest=Req GET "http://localhost:8080/api/v1/identity-exports/$($job.id)/manifest" $a;$signed=(Invoke-RestMethod -Method Post "http://localhost:8080/api/v1/identity-exports/$($job.id)/download-url" -Headers $a -ContentType application/json -Body '{"expiresInSeconds":30}').data;$download=Req GET $signed.url @{};$checks.asyncExport=$job.state-eq'Completed'-and$job.recordCount-gt0-and$job.outputSha256-match'^[0-9a-f]{64}$'-and$manifest.status-eq200-and$download.status-eq200
$tenantB=[guid]::NewGuid().ToString();docker exec deployment-postgres-1 psql -U platform -d platform -c "insert into platform.tenants(id,organization_id,name,region,status) select '$tenantB',organization_id,'Sprint10 Tenant B','local','active' from platform.tenants limit 1"|Out-Null;$b=@{Authorization="Bearer $(Jwt $tenantB)"};$bs=Req GET http://localhost:8080/api/v1/identity-events $b;$bd=Req GET "http://localhost:8080/api/v1/identity-events/$($event.eventId)" $b;$be=Req GET "http://localhost:8080/api/v1/identity-exports/$($job.id)/content" $b;$checks.tenantIsolation=$bs.status-eq200-and@((ConvertFrom-Json $bs.text).data.items).Count-eq0-and$bd.status-eq404-and$be.status-eq404
$unauthorized=Req GET http://localhost:8080/api/v1/identity-events @{};$invalidHistory=Req GET "http://localhost:8080/api/v1/identity-entities/not-a-hash/history?endpointId=$endpoint" $a;$malformedSid=Req POST http://localhost:8080/api/v1/identity-telemetry/policies $a @{name='invalid';policy=@{excludedSids=@('not-a-sid')}};$checks.securityBoundaries=$unauthorized.status-eq401-and$invalidHistory.status-eq400-and$malformedSid.status-eq400
$failed=@($checks.GetEnumerator()|Where-Object{-not$_.Value});$report=[ordered]@{schema='platform.sprint10.identity-api-matrix.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');endpointId=$endpoint;eventId=$event.eventId;exportId=$job.id;tenantB=$tenantB;checks=$checks;passed=$failed.Count-eq0};$report|ConvertTo-Json -Depth 10|Set-Content $Output -Encoding utf8;$report|ConvertTo-Json -Depth 6;if($failed.Count){exit 1}
