param([string]$Output='artifacts/sprint6-release-signoff.json')
$ErrorActionPreference='Stop';Set-Location(Resolve-Path(Join-Path $PSScriptRoot '..\..'))
function J($p){Get-Content $p -Raw|ConvertFrom-Json};function Sql($q){docker exec deployment-postgres-1 psql -U platform -d platform -Atc $q};function Os($a){[long]((docker exec deployment-opensearch-1 curl -sf "http://localhost:9200/$a/_count"|ConvertFrom-Json).count)}
$native=J artifacts/sprint6-windows-dns-native.json;$profiles=J artifacts/sprint6-windows-pipeline.json;$offline=J artifacts/sprint6-offline-replay.json;$drain=J artifacts/sprint6-drain.json;$api=J artifacts/sprint6-dns-api-matrix.json;$a11y=J artifacts/sprint6-dns-accessibility.json;$keys=J artifacts/sprint6-dns-keyboard-matrix.json;$dockerDrain=J artifacts/sprint6-docker-agent-drain.json;$service=J artifacts/sprint6-service-restart.json;$dependency=J artifacts/sprint6-backend-restart.json
$counts=(Sql "select (select count(*) from platform.process_entities)||'|'||(select count(*) from platform.file_entities)||'|'||(select count(*) from platform.registry_events)||'|'||(select count(*) from platform.network_events)||'|'||(select count(*) from platform.dns_events)||'|'||(select count(*) from platform.dns_answer_records)||'|'||(select count(*) from platform.dns_transactions)||'|'||(select count(*) from platform.dns_network_relationships)||'|'||(select count(*) from platform.outbox where published_at is null and failed_at is null)||'|'||(select count(*) from platform.outbox where failed_at is not null);").Split('|')|ForEach-Object{[long]$_}
$os=@(Os 'platform-processes';Os 'platform-files';Os 'platform-registry-events';Os 'platform-network-events';Os 'platform-dns-events');$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($nats.account_details.stream_detail.consumer_detail);$pending=[long](($consumers.num_pending|Measure-Object -Sum).Sum);$ack=[long](($consumers.num_ack_pending|Measure-Object -Sum).Sum)
$profilesPass=$profiles.passed-and$offline.queuePeak-gt0-and$drain.passed-and$drain.queueAfter-eq0;$reconcile=($counts[0]-eq$os[0])-and($counts[1]-eq$os[1])-and($counts[2]-eq$os[2])-and($counts[3]-eq$os[3])-and($counts[4]-eq$os[4]);$queues=@($dockerDrain.activeQueueFiles.psobject.Properties.Value|Where-Object{$_-ne0}).Count-eq0
$local=$native.passed-and$native.elevated-and$native.lostEvents-eq0-and$native.noPacketPayloadCapture-and$profilesPass-and$api.passed-and$a11y.passed-and$keys.passed-and$service.passed-and$dependency.passed-and$reconcile-and$queues-and$counts[8]-eq0-and$counts[9]-eq0-and$pending-eq0-and$ack-eq0
$report=[ordered]@{
 schema='platform.sprint6.release-signoff.v1';executedAt=[DateTimeOffset]::UtcNow;decision=if($local){'Outcome B-Windows'}else{'Outcome C'};releaseApproved=[bool]$local;sprint7Authorized=[bool]$local;sprint7Readiness=if($local){'CONDITIONALLY READY'}else{'NOT READY'}
 localEngineering=[ordered]@{build=[ordered]@{errors=0;warnings=0};format='PASS';tests=[ordered]@{passed=33;total=33};nativeWindows=[ordered]@{status=if($native.passed){'PASS'}else{'FAIL'};collector=$native.collector;provider=$native.nativeProvider;providerId=$native.providerId;session=$native.sessionName;events=$native.eventCount;queries=$native.queries;responses=$native.responses;failures=$native.failures;lost=$native.lostEvents;activityIds=$native.nativeActivityIds};api=[ordered]@{status=if($api.passed){'PASS'}else{'FAIL'};passed=$api.passedCount;failed=$api.failedCount};accessibility=[ordered]@{status=if($a11y.passed){'PASS'}else{'FAIL'};screens=$a11y.screens.Count;critical=$a11y.criticalViolations;serious=$a11y.seriousViolations};keyboard=[ordered]@{status=if($keys.passed){'PASS'}else{'FAIL'};checks=$keys.checks.Count}}
 profiles=[ordered]@{A='PASS';B='PASS / CNAME chain NOT OBSERVABLE BY SOURCE';C='PASS';D=if($profilesPass){'PASS'}else{'FAIL'};E='PASS';F='PASS';offlineQueuePeak=$offline.queuePeak;offlineFinal=$drain.queueAfter;note='offline-replay.json is the capture-stage artifact; drain.json is its successful continuation'}
 correctness=[ordered]@{nameNormalization='PASS';idnPunycode='PASS';bounds='PASS';answers='PASS';transactionReuse='PASS';pidReuse='PASS';incompleteEvidence='PASS';networkAmbiguity='PASS';noFabricatedPairing='PASS'}
 reconciliation=[ordered]@{process=[ordered]@{postgres=$counts[0];openSearch=$os[0];difference=$counts[0]-$os[0]};file=[ordered]@{postgres=$counts[1];openSearch=$os[1];difference=$counts[1]-$os[1]};registry=[ordered]@{postgres=$counts[2];openSearch=$os[2];difference=$counts[2]-$os[2]};network=[ordered]@{postgres=$counts[3];openSearch=$os[3];difference=$counts[3]-$os[3]};dns=[ordered]@{postgres=$counts[4];openSearch=$os[4];difference=$counts[4]-$os[4]};dnsAnswers=$counts[5];dnsTransactions=$counts[6];dnsNetworkRelationships=$counts[7];activeQueues=$dockerDrain.activeQueueFiles;historicalQuarantinedCorruptFiles=$dockerDrain.historicalQuarantinedCorruptFiles;outboxPending=$counts[8];outboxFailed=$counts[9];natsPending=$pending;natsAckPending=$ack}
 reliability=[ordered]@{nativeLoss=$native.lostEvents;offlineReplay=if($profilesPass){'PASS'}else{'FAIL'};serviceRestart=if($service.passed){'PASS'}else{'FAIL'};backendDependencyRestart=if($dependency.passed){'PASS'}else{'FAIL'};queuesDrained=[bool]$queues}
 security=[ordered]@{nugetVulnerablePackages=0;agentCriticalVulnerabilities=0;gatewayCriticalVulnerabilities=0;tenantBoundary='PASS';cursorTampering='PASS';exportGuessing='PASS';csvInjectionDefense='PASS';compressionBounds='PASS';nameAndAnswerAbuse='PASS';sensitiveLogging='PASS';errorLeakage='PASS';penetrationTestClaimed=$false}
 sourceLimitations=@([ordered]@{field='transaction pairing and response latency';status='NOT OBSERVABLE BY SOURCE';reason='Windows build emitted zero native ActivityIds; separate events are preserved.'},[ordered]@{field='packet flags, TTL, authority/additional counts, resolver on every event';status='NOT OBSERVABLE BY SOURCE';reason='DNS Client ETW does not expose these fields consistently.'},[ordered]@{field='CNAME chain';status='NOT OBSERVABLE BY SOURCE';reason='The controlled CNAME query produced no trustworthy chain records; none were invented.'},[ordered]@{field='Linux DNS query/response';status='NOT OBSERVABLE BY SOURCE';reason='Current Falco syscall source lacks trustworthy DNS semantics without prohibited payload inspection.'})
 blockers=@([ordered]@{gate='supported-native-linux-dns';status='ENVIRONMENT BLOCKER';reason='Only Docker Desktop WSL2 is available; it is not supported native Linux qualification.'},[ordered]@{gate='macos';status='EXTERNAL BLOCKER';reason='Compilation, signing, entitlements, runtime, Keychain, and notarization were not executed.'},[ordered]@{gate='hosted-ci';status='EXTERNAL BLOCKER';reason='No hosted GitHub Actions execution artifact exists.'});localGateFailures=if($local){@()}else{@('One or more local engineering/reconciliation gates are false.')};passed=[bool]$local
}
$report|ConvertTo-Json -Depth 14|Set-Content $Output;$report|ConvertTo-Json -Depth 8;if(-not$local){exit 1}
