$ErrorActionPreference='Stop'
$root=Resolve-Path(Join-Path $PSScriptRoot '../..');Set-Location $root
$settings=@{};Get-Content .env|Where-Object{$_-match'^[^#][^=]*='}|ForEach-Object{$i=$_.IndexOf('=');$settings[$_.Substring(0,$i)]=$_.Substring($i+1)}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$headers=@{Authorization="Bearer $($login.access_token)"};$tenant=$settings.PLATFORM_BOOTSTRAP_TENANT_ID
$health=(Invoke-RestMethod http://localhost:8080/api/v1/live-response/health -Headers $headers).data
$counts=((& docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select (select count(*) from platform.live_response_sessions where tenant_id='$tenant')||'|'||(select count(*) from platform.live_response_commands where tenant_id='$tenant')||'|'||(select count(*) from platform.live_response_transcript where tenant_id='$tenant')||'|'||(select count(*) from platform.live_response_artifacts where tenant_id='$tenant')||'|'||(select coalesce(sum(jsonb_array_length(session_data->'commands')),0) from platform.live_response_sessions where tenant_id='$tenant')||'|'||(select coalesce(sum(jsonb_array_length(session_data->'transcript')),0) from platform.live_response_sessions where tenant_id='$tenant')||'|'||(select count(*) from platform.live_response_sessions where tenant_id='$tenant' and state not in ('Closed','Expired','Rejected','Failed'));").Trim()).Split('|')|ForEach-Object{[long]$_}
$trigger=((& docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from pg_trigger where tgname='live_transcript_immutable' and not tgisinternal;").Trim())-eq'1'
$previousErrorActionPreference=$ErrorActionPreference;$ErrorActionPreference='Continue'
$tamperOutput=& docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -c "update platform.live_response_transcript set summary='tampered' where event_id=(select event_id from platform.live_response_transcript limit 1);" 2>&1;$tamperRejected=$LASTEXITCODE-ne0
$ErrorActionPreference=$previousErrorActionPreference
$outbox=((docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) filter(where published_at is null),count(*) filter(where failed_at is not null) from platform.outbox;").Trim()).Split('|')|ForEach-Object{[long]$_}
$nats=(& docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true')|ConvertFrom-Json;$consumer=@($nats.account_details.stream_detail.consumer_detail)
$report=[ordered]@{schemaVersion='sprint17-final-reconciliation.v1';capturedAt=[DateTimeOffset]::UtcNow;liveResponse=[ordered]@{sessions=$counts[0];commands=$counts[1];transcriptRows=$counts[2];artifacts=$counts[3];snapshotCommands=$counts[4];snapshotTranscript=$counts[5];nonterminalSessions=$counts[6];queue=$health.commandQueueDepth};transcriptImmutability=[ordered]@{trigger=$trigger;tamperRejected=$tamperRejected};outbox=[ordered]@{pending=$outbox[0];failed=$outbox[1]};nats=[ordered]@{pending=[long](($consumer|Measure-Object num_pending -Sum).Sum);ackPending=[long](($consumer|Measure-Object num_ack_pending -Sum).Sum)};prior=(Get-Content artifacts/sprint16-final-reconciliation.json|ConvertFrom-Json);passed=($counts[1]-eq$counts[4]-and$counts[2]-eq$counts[5]-and$counts[6]-eq0-and$health.commandQueueDepth-eq0-and$trigger-and$tamperRejected-and$outbox[0]-eq0-and$outbox[1]-eq0-and[long](($consumer|Measure-Object num_pending -Sum).Sum)-eq0-and[long](($consumer|Measure-Object num_ack_pending -Sum).Sum)-eq0-and(Get-Content artifacts/sprint16-final-reconciliation.json|ConvertFrom-Json).passed)}
$report|ConvertTo-Json -Depth 30|Set-Content artifacts/sprint17-final-reconciliation.json;$report|ConvertTo-Json -Depth 30;if(!$report.passed){exit 1}
