param([string]$BaseUrl='http://127.0.0.1:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$token=(Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress)).access_token;$h=@{Authorization="Bearer $token"}
function Call([string]$method,[string]$path,$body=$null){$p=@{Method=$method;Uri="$BaseUrl$path";Headers=$h};if($null-ne$body){$p.ContentType='application/json';$p.Body=$body|ConvertTo-Json -Depth 20 -Compress};(Invoke-RestMethod @p).data}
$before=Call Get '/api/v1/ai-engineering/inventory';$current=@($before.detections|Where-Object{$_.domain-eq'Process'})[0];if($null-eq$current){throw 'No current Process detection rule is available for comparison.'}
$draft=Call Post '/api/v1/ai-engineering/detection-drafts' @{prompt='Controlled repository workflow validation';domain='Process';field='path';operator='Contains';value='powershell';mitreTechnique='T1059.001';evidenceCitations=@('EVID-WORKFLOW-0001');evidencePackageHash='controlled-workflow'}
$to=[DateTimeOffset]::UtcNow;$simulation=Call Post "/api/v1/ai-engineering/drafts/$($draft.draftId)/simulate" @{draftHash=$draft.draftHash;from=$to.AddDays(-6).ToString('o');to=$to.ToString('o');maximumEvents=1000};$tuning=Call Post "/api/v1/ai-engineering/drafts/$($draft.draftId)/tuning" @{draftHash=$draft.draftHash;simulationId=$simulation.simulationId};$comparison=Call Post "/api/v1/ai-engineering/drafts/$($draft.draftId)/compare" @{draftHash=$draft.draftHash;currentRuleId=$current.detectionId;currentVersion=$current.detectionVersion;from=$to.AddDays(-6).ToString('o');to=$to.ToString('o');maximumEvents=1000}
$saved=Call Post "/api/v1/ai-engineering/drafts/$($draft.draftId)/save" @{proposalHash=$draft.draftHash;reason='Explicit detection-engineer acceptance for inactive repository validation'};$after=Call Get '/api/v1/ai-engineering/inventory';$repository=@($after.detections|Where-Object{$_.detectionId-eq$saved.repositoryRuleId-and$_.detectionVersion-eq$saved.repositoryRuleVersion})[0]
$beforeActive=@($before.detections|Where-Object{$_.enabled-and$_.status-eq'Active'}).Count;$afterActive=@($after.detections|Where-Object{$_.enabled-and$_.status-eq'Active'}).Count
$report=[ordered]@{schemaVersion='sprint31-workspace-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');draftId=$draft.draftId;draftHash=$draft.draftHash;simulation=$simulation;tuning=$tuning;comparison=$comparison;explicitSave=[ordered]@{state=$saved.state;decidedBy=$saved.decidedBy;repositoryRuleId=$saved.repositoryRuleId;repositoryVersion=$saved.repositoryRuleVersion;repositoryStatus=$repository.status;repositoryEnabled=$repository.enabled};activeRulesBefore=$beforeActive;activeRulesAfter=$afterActive;passed=$tuning.historical.simulationId-eq$simulation.simulationId-and-not$tuning.mutationApplied-and$comparison.tenantImpact-eq1-and$saved.state-eq'SavedDraft'-and$repository.status-eq'Draft'-and-not$repository.enabled-and$beforeActive-eq$afterActive}
$report|ConvertTo-Json -Depth 20|Set-Content artifacts/sprint31-workspace-validation.json -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(-not$report.passed){throw 'Sprint 31 workspace validation failed.'}
