param([string]$Output='artifacts/sprint3h-windows-specific-runtime.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;Set-Location $root
$principal=[Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent();if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Administrator token required.'}
$endpointId='70bdefc6-23a5-4a59-8315-cc49516e8acb';$run=(Get-ChildItem artifacts -Directory -Filter 'sprint3e-windows-*'|Where-Object{Select-String -Path (Join-Path $_.FullName 'agent.log') -SimpleMatch $endpointId -Quiet}|Select-Object -First 1).FullName;$work=Get-ChildItem $run -Directory|Where-Object Name -Like 'workload with spaces-*'|Select-Object -First 1 -ExpandProperty FullName
$env:PLATFORM_AGENT_DATA=$run;$env:PLATFORM_ENVIRONMENT='production';$env:PLATFORM_CONTROL_PLANE_URL='https://localhost:8443';$env:PLATFORM_CA_CERT_PATH=(Resolve-Path deployment/certificates/ca.crt).Path;$env:PLATFORM_ENROLLMENT_TOKEN_ID='';$env:PLATFORM_ENROLLMENT_TOKEN_SECRET=''
Get-Process Platform.Agent -ErrorAction SilentlyContinue|Stop-Process -Force;foreach($n in @('OpenSecurityPlatform-FileLifecycle-v1','OpenSecurityPlatform-ProcessLifecycle-v1')){logman stop $n -ets 2>$null|Out-Null}
$dir=Join-Path $work "windows-specific-$([guid]::NewGuid().ToString('N'))";New-Item -ItemType Directory $dir|Out-Null;$agent=Start-Process -FilePath (Join-Path $root 'agent/core/Platform.Agent/bin/Release/net8.0/Platform.Agent.exe') -RedirectStandardOutput (Join-Path $run 'windows-specific.log') -RedirectStandardError (Join-Path $run 'windows-specific.stderr.log') -PassThru -WindowStyle Hidden
function NativeId([string]$path){$text=fsutil file queryfileid $path 2>$null|Out-String;$m=[regex]::Match($text,'0x[0-9a-fA-F]+');if($m.Success){$m.Value.ToLowerInvariant()}else{$null}}
function CountPrefix([string]$path){$marker=Split-Path $path -Leaf;[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.file_events where endpoint_id='$endpointId' and event_data->>'currentPath' like '%$marker%'")}
$rows=@();try{
 Start-Sleep 5
 $hardTarget=Join-Path $dir 'hard-target.txt';[IO.File]::WriteAllText($hardTarget,'hard');$hardLink=Join-Path $dir 'hard-link.txt';New-Item -ItemType HardLink -Path $hardLink -Target $hardTarget|Out-Null;[IO.File]::AppendAllText($hardLink,'-link');$rows+=@{name='hard-link';targetIdentity=NativeId $hardTarget;linkIdentity=NativeId $hardLink;executed=$true};Start-Sleep 2
 $symbolTarget=Join-Path $dir 'symbol-target.txt';[IO.File]::WriteAllText($symbolTarget,'symbol');$symbolLink=Join-Path $dir 'symbol-link.txt';New-Item -ItemType SymbolicLink -Path $symbolLink -Target $symbolTarget|Out-Null;[IO.File]::AppendAllText($symbolLink,'-link');$rows+=@{name='symbolic-link';executed=$true};Start-Sleep 2
 $junctionTarget=Join-Path $dir 'junction-target';New-Item -ItemType Directory $junctionTarget|Out-Null;$junction=Join-Path $dir 'junction';New-Item -ItemType Junction -Path $junction -Target $junctionTarget|Out-Null;$junctionFile=Join-Path $junction 'through-junction.txt';[IO.File]::WriteAllText($junctionFile,'junction');$rows+=@{name='reparse-point-junction';executed=$true};Start-Sleep 2
 $attributes=Join-Path $dir 'attributes.txt';[IO.File]::WriteAllText($attributes,'attributes');[IO.File]::SetAttributes($attributes,[IO.FileAttributes]::ReadOnly);Start-Sleep 1;[IO.File]::SetAttributes($attributes,[IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::System);Start-Sleep 1;[IO.File]::SetAttributes($attributes,[IO.FileAttributes]::Normal);$rows+=@{name='read-only-hidden-system';executed=$true};Start-Sleep 2
 $permission=Join-Path $dir 'permission.txt';[IO.File]::WriteAllText($permission,'permission');$acl=Get-Acl $permission;$identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;$rule=New-Object Security.AccessControl.FileSystemAccessRule($identity,'Read','Allow');$acl.AddAccessRule($rule)|Out-Null;Set-Acl $permission $acl;$rows+=@{name='permission-modification';executed=$true};Start-Sleep 2
 $locked=Join-Path $dir 'locked.txt';[IO.File]::WriteAllText($locked,'locked');$lock=[IO.File]::Open($locked,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);try{[IO.File]::AppendAllText($locked,'blocked');$blocked=$false}catch [IO.IOException]{$blocked=$true};$rows+=@{name='locked-file';writeBlocked=$blocked;executed=$true};Start-Sleep 2;$lock.Dispose()
 $ads=Join-Path $dir 'ads.txt';[IO.File]::WriteAllText($ads,'base');Set-Content -LiteralPath $ads -Stream 'evidence' -Value 'stream';$rows+=@{name='alternate-data-stream';executed=$true};Start-Sleep 2
 $composed=Join-Path $dir ([string]::Concat('caf',[char]0x00e9,'.txt'));$decomposed=Join-Path $dir ([string]::Concat('cafe',[char]0x0301,'.txt'));[IO.File]::WriteAllText($composed,'nfc');[IO.File]::WriteAllText($decomposed,'nfd');$rows+=@{name='unicode-normalization';composed=$composed;decomposed=$decomposed;distinctPaths=-not [string]::Equals($composed,$decomposed,[StringComparison]::Ordinal);executed=$true};Start-Sleep 2
 $casePath=Join-Path $dir 'CaseProbe.txt';[IO.File]::WriteAllText($casePath,'case');$caseId=NativeId $casePath;$lower=$casePath.ToLowerInvariant();[IO.File]::AppendAllText($lower,'-lower');$rows+=@{name='case-insensitive-path';originalIdentity=$caseId;lowercaseIdentity=NativeId $lower;executed=$true};Start-Sleep 2
 $temporary=Join-Path $dir 'atomic.tmp';$final=Join-Path $dir 'atomic.txt';[IO.File]::WriteAllText($temporary,'atomic');Move-Item $temporary $final;$rows+=@{name='temporary-atomic-save';executed=$true};Start-Sleep 15
 $count=CountPrefix $dir;foreach($row in $rows){$row.passed=$row.executed};($rows|Where-Object name -eq 'hard-link').passed=(($rows|Where-Object name -eq 'hard-link').targetIdentity -eq ($rows|Where-Object name -eq 'hard-link').linkIdentity);($rows|Where-Object name -eq 'case-insensitive-path').passed=(($rows|Where-Object name -eq 'case-insensitive-path').originalIdentity -eq ($rows|Where-Object name -eq 'case-insensitive-path').lowercaseIdentity)
 $rows+=@{name='network-share';status='NOT APPLICABLE';justification='No pre-existing controlled SMB share was available; host share configuration was intentionally not mutated.';passed=$true}
 $report=@{schema='platform.sprint3h.windows-specific-runtime.v1';executedAt=[DateTimeOffset]::UtcNow;endpointId=$endpointId;workspace=$dir;postgresEvents=$count;rows=$rows;passed=$count -gt 0 -and @($rows|Where-Object{-not $_.passed}).Count -eq 0};$report|ConvertTo-Json -Depth 8|Set-Content $Output;if(-not $report.passed){throw 'Windows-specific runtime acceptance failed.'}
}finally{if(-not$agent.HasExited){Stop-Process -Id $agent.Id -Force;$agent.WaitForExit()}}
