param([string]$BaseUrl='http://localhost:8080')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');$cfg=@{};Get-Content(Join-Path $root '.env')|%{if($_-match'^([^#=]+)=(.*)$'){$cfg[$matches[1]]=$matches[2]}}
$token=(Invoke-RestMethod "$BaseUrl/api/v1/auth/token" -Method Post -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json)).access_token;$headers=@{Authorization="Bearer $token"};$tenant=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;$checks=@();$profiles=@()
function Call($path,$method='Get',$body=$null){$p=@{Uri="$BaseUrl$path";Method=$method;Headers=$headers};if($null-ne$body){$p.ContentType='application/json';$p.Body=$body|ConvertTo-Json -Depth 20 -Compress};(Invoke-RestMethod @p).data}
function Check($name,[bool]$pass,$evidence){$script:checks+=[ordered]@{name=$name;status=if($pass){'PASS'}else{'FAIL'};evidence=$evidence}}
function Expect400($path,$body){try{Call $path Post $body|Out-Null;$false}catch{$_.Exception.Response.StatusCode.value__-eq400}}
function Obs($domain,$at,$endpoint,$process,$fields){$id=[guid]::NewGuid();@{observationId=$id;tenantId=$tenant;kind='Event';domain=$domain;eventTime=$at.ToUniversalTime().ToString('o');ingestedAt=$at.ToUniversalTime().AddMilliseconds(25).ToString('o');endpointId=$endpoint;processEntityId=$process;parentProcessEntityId="parent-$process";entityId="entity-$process";detectionFindingId=$null;detectionId=$null;fields=$fields;evidenceReference="postgresql://platform/sprint13_controlled/$id";late=$false;incomplete=$false;missingTelemetry=@();quality=@('complete');confidence=10}}
function Sim($rule,$events){Call '/api/v1/correlation-simulations' Post @{correlationRuleId=$rule.correlationRuleId;version=$rule.version;observations=@($events)}}
$seed=Call '/internal/v1/correlation-production-pack:seed' Post @{};$rules=@(Call '/api/v1/correlation-rules');$packs=@(Call '/api/v1/correlation-packs');$allTests=@();foreach($r in $rules){$allTests+=@(Call "/api/v1/correlation-rule-versions/$($r.correlationRuleId)/$($r.version)/tests")}
Check 'production pack lifecycle' ($packs.Count-eq1-and$packs[0].enabled-and$packs[0].validationPassed-and$rules.Count-eq15-and@($rules|?{-not$_.enabled-or$_.status-ne'Active'}).Count-eq0) @{packs=$packs.Count;rules=$rules.Count;active=@($rules|? enabled).Count}
Check 'quality fixture gate' ($allTests.Count-eq45-and@($allTests|?{-not$_.passed-or-not$_.deterministic-or-not$_.tenantIsolated-or-not$_.resourceCostPassed}).Count-eq0) @{fixtures=$allTests.Count;positive=@($allTests|? kind -eq positive).Count;negative=@($allTests|? kind -eq negative).Count;boundary=@($allTests|? kind -eq boundary).Count}
$at=[DateTimeOffset]::UtcNow;$ep=[guid]::NewGuid();$proc='profile-a-process';$ruleA=$rules|?{$_.category-eq'dns-network-chain'};$a=@((Obs Process $at $ep $proc @{endpointId=$ep.ToString();processEntityId=$proc;processName='sprint13-client.exe'}),(Obs Dns $at.AddSeconds(1) $ep $proc @{endpointId=$ep.ToString();processEntityId=$proc;query='profile.invalid'}),(Obs Network $at.AddSeconds(2) $ep $proc @{endpointId=$ep.ToString();processEntityId=$proc;protocol='tcp'}));$pa=Sim $ruleA $a;$profiles+=[ordered]@{profile='A';status=if(@($pa.findings).Count-eq1){'PASS'}else{'FAIL'};evidence=@{steps=3;findings=@($pa.findings).Count;ordered=$true}}
$pb=Sim $ruleA $a[0..1];$profiles+=[ordered]@{profile='B';status=if(@($pb.findings).Count-eq0){'PASS'}else{'FAIL'};evidence=@{steps=2;findings=@($pb.findings).Count}}
$epc=[guid]::NewGuid();$pc='profile-c-process';$ruleC=$rules|?{$_.category-eq'autorun-then-execute'};$c=@((Obs Process $at $epc $pc @{endpointId=$epc.ToString();processName='reg.exe'}),(Obs Registry $at.AddSeconds(1) $epc $pc @{endpointId=$epc.ToString();operation='ValueSet';path='HKCU\Software\Microsoft\Windows\CurrentVersion\Run\Sprint13'}),(Obs Process $at.AddSeconds(2) $epc $pc @{endpointId=$epc.ToString();processName='payload.exe'}));$pcResult=Sim $ruleC $c;$profiles+=[ordered]@{profile='C';status=if(@($pcResult.findings).Count-eq1){'PASS'}else{'FAIL'};evidence=@{domains='Process,Registry,Process';findings=@($pcResult.findings).Count}}
$ruleD=$rules|?{$_.category-eq'failed-then-success'};$epd=[guid]::NewGuid();$pd='profile-d';$d=@();0..2|%{$d+=,(Obs Identity $at.AddSeconds($_) $epd $pd @{endpointId=$epd.ToString();user='sprint13-profile-d';status='failed'})};$beforeD=Sim $ruleD $d;$d+=,(Obs Identity $at.AddSeconds(3) $epd $pd @{endpointId=$epd.ToString();user='sprint13-profile-d';status='success'});$afterD=Sim $ruleD $d;$profiles+=[ordered]@{profile='D';status=if(@($beforeD.findings).Count-eq0-and@($afterD.findings).Count-eq1){'PASS'}else{'FAIL'};evidence=@{before=@($beforeD.findings).Count;after=@($afterD.findings).Count;threshold=3}}
$rapid=$rules|?{$_.category-eq'rapid-create-execute'};$epr=[guid]::NewGuid();$pr='profile-e-process';$rEvents=@((Obs File $at.AddSeconds(10) $epr $pr @{endpointId=$epr.ToString();operation='Created';extension='.exe'}),(Obs Process $at.AddSeconds(11) $epr $pr @{endpointId=$epr.ToString();path='C:\Users\Public\profile-e.exe'}));foreach($x in $rEvents){Call '/internal/v1/correlation-observations:evaluate' Post @{observation=$x;productionFindings=$true;mode='Live'}|Out-Null};$from=$at.AddSeconds(9);$to=$at.AddSeconds(12);$replayBody=@{correlationRuleId=$rapid.correlationRuleId;version=1;from=$from.ToString('o');to=$to.ToString('o');productionFindings=$false};$e1=Call '/api/v1/correlation-replays' Post $replayBody;$e2=Call '/api/v1/correlation-replays' Post $replayBody;$same=@($e1.resultIds).Count-eq1-and(@($e1.resultIds)-join',')-eq(@($e2.resultIds)-join',');$profiles+=[ordered]@{profile='E';status=if($same){'PASS'}else{'FAIL'};evidence=@{authoritative=$e1.authoritativeSource;run1=$e1.run.id;run2=$e2.run.id;resultIds=@($e1.resultIds)}}
$epf=[guid]::NewGuid();$pf='profile-f-process';$f1=Obs File $at.AddSeconds(20) $epf $pf @{endpointId=$epf.ToString();operation='Created';extension='.exe'};$f2=Obs Process $at.AddSeconds(21) $epf $pf @{endpointId=$epf.ToString();path='C:\Users\Public\profile-f.exe'};Call '/internal/v1/correlation-observations:evaluate' Post @{observation=$f1;productionFindings=$true;mode='Live'}|Out-Null;docker restart deployment-gateway-1|Out-Null;$ready=$false;1..30|%{if(!$ready){Start-Sleep -Milliseconds 500;try{$ready=(Invoke-RestMethod "$BaseUrl/health/live").status-eq'healthy'}catch{}}};$fResult=Call '/internal/v1/correlation-observations:evaluate' Post @{observation=$f2;productionFindings=$true;mode='Live'};$duplicate=Call '/internal/v1/correlation-observations:evaluate' Post @{observation=$f2;productionFindings=$true;mode='Live'};$profiles+=[ordered]@{profile='F';status=if($ready-and$fResult.matched-and$duplicate.duplicate){'PASS'}else{'FAIL'};evidence=@{restartReady=$ready;findingId=$fResult.finding.correlatedFindingId;duplicateSafe=$duplicate.duplicate}}
Check 'Profiles A-F' (@($profiles|?{$_.status-eq'FAIL'}).Count-eq0) $profiles
$page=Call '/api/v1/correlated-findings?pageSize=100';$finding=$page.items|Select-Object -First 1;$detail=Call "/api/v1/correlated-findings/$($finding.correlatedFindingId)";$evidence=Call "/api/v1/correlated-findings/$($finding.correlatedFindingId)/evidence";$timeline=@(Call "/api/v1/correlated-findings/$($finding.correlatedFindingId)/timeline");$relationships=@(Call "/api/v1/correlated-findings/$($finding.correlatedFindingId)/entity-relationships");Check 'reproducible evidence chain' ($detail.engineVersion-eq'correlation-engine.v1'-and$evidence.evidenceEventIds.Count-ge2-and$timeline.Count-ge2-and$relationships.Count-ge2-and$detail.explanation) @{findingId=$finding.correlatedFindingId;events=$evidence.evidenceEventIds.Count;timeline=$timeline.Count;relationships=$relationships.Count}
$coverage=@(Call '/api/v1/mitre-coverage');Check 'honest MITRE coverage' ($coverage.Count-ge10-and@($coverage|?{-not$_.detectionImplemented-or-not$_.detectionTested-or-not$_.productionActive}).Count-eq0) @{rows=$coverage.Count;active=@($coverage|? productionActive).Count}
$health=Call '/api/v1/correlation-health';Check 'engine health' ($health.correlationsEvaluated-gt0-and$health.ruleFailures-eq0-and$health.replayQueueDepth-eq0) $health
$export=Call '/api/v1/correlated-finding-exports' Post @{format='jsonl';query=@{};maximumRecords=100};$manifest=Invoke-RestMethod "$BaseUrl/api/v1/correlated-finding-exports/$($export.id)/manifest" -Headers $headers;$url=Call "/api/v1/correlated-finding-exports/$($export.id)/download-url" Post @{};$tmp=[IO.Path]::GetTempFileName();try{Invoke-WebRequest $url.url -UseBasicParsing -OutFile $tmp;$hash=(Get-FileHash $tmp -Algorithm SHA256).Hash.ToLowerInvariant();Check 'tenant-bound SHA-256 export' ($manifest.tenantBinding-eq$tenant-and$manifest.sha256-eq$hash-and$manifest.recordCount-eq$export.recordCount) @{id=$export.id;records=$manifest.recordCount;sha256=$hash;signed=$true}}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue}
$badTenant=(Obs Process $at ([guid]::NewGuid()) 'bad-tenant' @{endpointId=[guid]::NewGuid().ToString();path='x'});$badTenant.tenantId=[guid]::NewGuid().ToString();$security=[ordered]@{tenantMixing=Expect400 '/internal/v1/correlation-observations:evaluate' @{observation=$badTenant;productionFindings=$false;mode='DryRun'};replayAbuse=Expect400 '/api/v1/correlation-replays' @{correlationRuleId=$rapid.correlationRuleId;version=1;from=$at.AddDays(-8).ToString('o');to=$at.ToString('o')};exclusionMatchAll=Expect400 '/api/v1/correlation-exclusions' @{id=[guid]::Empty;version=1;tenantId=$tenant;packId=$null;ruleId=$null;field='endpointId';value='*';startsAt=$at.ToString('o');endsAt=$at.AddDays(1).ToString('o');reason='invalid';createdBy='test'};cursorTamper=$false;exportGuess=$false};try{Call '/api/v1/correlated-findings?cursor=tampered'|Out-Null}catch{$security.cursorTamper=$_.Exception.Response.StatusCode.value__-eq400};try{Invoke-WebRequest "$BaseUrl/api/v1/correlated-finding-exports/$([guid]::NewGuid())/download?token=invalid" -UseBasicParsing|Out-Null}catch{$security.exportGuess=$_.Exception.Response.StatusCode.value__-eq404};Check 'runtime security abuse cases' (@($security.Values|?{-not$_}).Count-eq0) $security
Start-Sleep -Seconds 3;$pg=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.correlated_findings where tenant_id='$tenant';");$osRaw=docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-correlated-findings/_count;$os=[int](($osRaw|ConvertFrom-Json).count);$outbox=@(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.outbox where published_at is null;select count(*) from platform.outbox where failed_at is not null;");Check 'exact correlation reconciliation' ($pg-eq$os) @{postgres=$pg;opensearch=$os};Check 'outbox drained' ([int]$outbox[0]-eq0-and[int]$outbox[1]-eq0) @{pending=[int]$outbox[0];failed=[int]$outbox[1]}
$report=[ordered]@{schemaVersion='sprint13-correlation-validation.v1';executedAt=[DateTimeOffset]::UtcNow.ToString('o');packId=$seed.packId;productionRules=$rules.Count;fixtures=$allTests.Count;profiles=$profiles;checks=$checks;failed=@($checks|?{$_.status-eq'FAIL'}).Count;passed=@($checks|?{$_.status-eq'FAIL'}).Count-eq0};$report|ConvertTo-Json -Depth 20|Set-Content(Join-Path $root 'artifacts/sprint13-correlation-validation.json') -Encoding utf8;$report|ConvertTo-Json -Depth 20;if(!$report.passed){throw 'Sprint 13 correlation validation failed.'}
