param([string]$Output='artifacts/sprint4-registry-failure-recovery.json')
$ErrorActionPreference='Stop';Set-Location (Resolve-Path (Join-Path $PSScriptRoot '..\..'))
$compose=@('-f','deployment/docker-compose.yml','--env-file','.env');$cfg=@{};Get-Content .env|?{$_-match'^[^#].*='}|%{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]}
function B64([byte[]]$b){[Convert]::ToBase64String($b).TrimEnd('=').Replace('+','-').Replace('/','_')};function Jwt([string[]]$permissions){$now=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$p=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub='sprint4-failure-recovery';tid=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;per=$permissions;pty='user';iat=$now;exp=$now+1800;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));"$h.$p.$(B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$p"))))"}
$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$h=@{Authorization="Bearer $($login.access_token)"};$system=@{Authorization="Bearer $(Jwt @('system:admin'))"};$runtime=Get-Content artifacts/sprint4-windows-registry-runtime.json -Raw|ConvertFrom-Json;$from=([DateTimeOffset]$runtime.manifest[0].at).AddMinutes(-2).ToString('O');$to=[DateTimeOffset]::UtcNow.AddMinutes(2).ToString('O');$rows=[Collections.Generic.List[object]]::new()
function Add($name,$expected,$actual,[bool]$passed){$rows.Add([ordered]@{failure=$name;expected=$expected;actual=$actual;recovered=$passed;passed=$passed})}
function Ready([int]$seconds=90){$d=[DateTimeOffset]::UtcNow.AddSeconds($seconds);do{Start-Sleep 1;try{$ok=(Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing -TimeoutSec 2).StatusCode -eq 200}catch{$ok=$false}}while((-not $ok) -and [DateTimeOffset]::UtcNow -lt $d);$ok}
function Status([string]$uri){try{[int](Invoke-WebRequest $uri -Headers $h -UseBasicParsing -TimeoutSec 4).StatusCode}catch{if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{0}}}
function NewExport{(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/registry-exports -Headers $h -ContentType application/json -Body (@{format='jsonl';query=@{endpointId=$runtime.endpointId;from=$from;to=$to};fields=@();maximumRecords=500}|ConvertTo-Json -Depth 8)).data}
function WaitExport($job,[int]$seconds=40){$d=[DateTimeOffset]::UtcNow.AddSeconds($seconds);do{Start-Sleep -Milliseconds 500;$job=(Invoke-RestMethod "http://localhost:8080/api/v1/registry-exports/$($job.id)" -Headers $h).data}while($job.state -in @('Pending','Running') -and [DateTimeOffset]::UtcNow -lt $d);$job}
try{
  $pg0=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc 'select count(*) from platform.registry_events');$os0=[int]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-registry-events/_count|ConvertFrom-Json).count)
  & docker compose @compose stop nats|Out-Null;Start-Sleep 2;$duringNats=Status 'http://localhost:8080/health/ready';& docker compose @compose up -d nats|Out-Null;$natsRecovered=Ready;Add 'NATS unavailable' 'readiness degrades; service restores' "during=$duringNats; recovered=$natsRecovered" ($duringNats -ne 200 -and $natsRecovered)
  & docker compose @compose stop opensearch|Out-Null;Start-Sleep 2;$duringSearch=Status "http://localhost:8080/api/v1/registry-events?from=$([uri]::EscapeDataString($from))&to=$([uri]::EscapeDataString($to))";& docker compose @compose up -d opensearch|Out-Null;$d=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;$healthy=(docker inspect deployment-opensearch-1 --format '{{.State.Health.Status}}') -eq 'healthy'}while((-not $healthy) -and [DateTimeOffset]::UtcNow -lt $d);$rebuilt=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/registry-events/projections:rebuild -Headers $system).data;Add 'OpenSearch unavailable' 'search fails safely; projection rebuilds' "during=$duringSearch; documents=$($rebuilt.documents)" ($duringSearch -in @(500,502,503) -and $healthy -and $rebuilt.aliasSwitched)
  & docker compose @compose stop minio|Out-Null;$failedJob=WaitExport (NewExport) 30;& docker compose @compose up -d minio|Out-Null;Start-Sleep 3;$recoveredJob=WaitExport (NewExport) 45;Add 'MinIO unavailable' 'export fails bounded then completes after restore' "failed=$($failedJob.state); recovered=$($recoveredJob.state)" ($failedJob.state -eq 'Failed' -and $recoveredJob.state -eq 'Completed')
  & docker compose @compose stop postgres|Out-Null;Start-Sleep 2;$duringPg=Status 'http://localhost:8080/health/ready';& docker compose @compose up -d postgres|Out-Null;$pgRecovered=Ready 120;Add 'PostgreSQL unavailable' 'readiness degrades; authority restores' "during=$duringPg; recovered=$pgRecovered" ($duringPg -ne 200 -and $pgRecovered)
  $offline=Get-Content artifacts/sprint4-registry-offline-replay.json -Raw|ConvertFrom-Json;Add 'Gateway unavailable and agent restart' 'durable queue replays exactly once' $offline ([bool]$offline.passed)
  $crash=Get-Content artifacts/sprint4-registry-crash-matrix.json -Raw|ConvertFrom-Json;Add 'queue corruption and crash boundaries' 'quarantine and recovery preserve valid evidence' $crash.cases ([bool]$crash.passed)
  $disk=Get-Content artifacts/sprint3g-full-disk-matrix.json -Raw|ConvertFrom-Json;Add 'full disk' 'shared bounded persistence fails safely and recovers' @{schema=$disk.schema;passed=$disk.passed} ([bool]$disk.passed)
  $security=Get-Content artifacts/sprint4-registry-security-matrix.json -Raw|ConvertFrom-Json;Add 'batch corruption, invalid gzip, field limits' 'requests rejected without secret leakage' @{tests=$security.tests.Count;passed=$security.passed} ([bool]$security.passed)
  & docker compose @compose restart postgres nats opensearch minio gateway|Out-Null;$combined=Ready 150;$d=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;$osHealthy=(docker inspect deployment-opensearch-1 --format '{{.State.Health.Status}}') -eq 'healthy'}while((-not $osHealthy) -and [DateTimeOffset]::UtcNow -lt $d);$final=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/registry-events/projections:rebuild -Headers $system).data;$pg=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc 'select count(*) from platform.registry_events');$os=[int]((docker exec deployment-opensearch-1 curl -s http://localhost:9200/platform-registry-events/_count|ConvertFrom-Json).count);Add 'combined infrastructure restart' 'readiness, rebuild, exact reconciliation' "ready=$combined; pg=$pg; os=$os" ($combined -and $osHealthy -and $final.aliasSwitched -and $pg -eq $os)
  $inherited=Get-Content artifacts/sprint3h-no-regression.json -Raw|ConvertFrom-Json;Add 'certificate revocation and endpoint disable' 'previous locked lifecycle gate remains passing' @{artifact='sprint3h-no-regression.json';passed=$inherited.passed} ([bool]$inherited.passed)
  $outbox=[int](docker exec deployment-postgres-1 psql -U platform -d platform -Atc 'select count(*) from platform.outbox where published_at is null and failed_at is null');$nats=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumer=$nats.account_details.stream_detail.consumer_detail;Add 'projection consumer/outbox restart' 'outbox and consumer drain' "outbox=$outbox; pending=$($consumer.num_pending); ack=$($consumer.num_ack_pending)" ($outbox -eq 0 -and $consumer.num_pending -eq 0 -and $consumer.num_ack_pending -eq 0)
}finally{& docker compose @compose up -d postgres nats opensearch minio gateway|Out-Null;Ready 120|Out-Null}
$failed=@($rows|?{-not$_.passed});$report=[ordered]@{schema='platform.sprint4.registry-failure-recovery.v1';executedAt=[DateTimeOffset]::UtcNow;baseline=@{postgres=$pg0;openSearch=$os0};cases=$rows;failed=$failed.Count;passed=$failed.Count -eq 0};$report|ConvertTo-Json -Depth 12|Set-Content $Output;$report|ConvertTo-Json -Depth 5;if(-not $report.passed){exit 1}
