import puppeteer from "../../.tooling/a11y/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js";
import fs from "node:fs";

const axe=fs.readFileSync(".tooling/a11y/node_modules/axe-core/axe.min.js","utf8");
const env=Object.fromEntries(fs.readFileSync(".env","utf8").split(/\r?\n/).filter(x=>x&&!x.startsWith("#")&&x.includes("=")).map(x=>x.split(/=(.*)/s).slice(0,2)));
const executablePath=process.env.PUPPETEER_EXECUTABLE_PATH||["C:/Program Files/Google/Chrome/Application/chrome.exe","C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe","/usr/bin/google-chrome","/usr/bin/chromium"].find(fs.existsSync);
const browser=await puppeteer.launch({executablePath,headless:true,args:["--no-sandbox"]});
const page=await browser.newPage();
await page.setBypassCSP(true);
await page.goto("http://localhost:8080/#/login",{waitUntil:"networkidle0"});
await page.type('input[name="username"]',env.PLATFORM_BOOTSTRAP_USER);await page.type('input[name="password"]',env.PLATFORM_BOOTSTRAP_PASSWORD);
await Promise.all([page.click("#login button"),page.waitForNetworkIdle()]);

async function scan(name,hash,theme="dark"){
  await page.evaluate(({hash,theme})=>{document.documentElement.dataset.theme=theme;location.hash=hash;},{hash,theme});await page.waitForNetworkIdle();await page.addScriptTag({content:axe});
  const result=await page.evaluate(async()=>{const a=await axe.run(document,{resultTypes:["violations"]});const custom=[];if([...document.querySelectorAll("input:not([type=hidden]),select,textarea")].some(x=>!x.labels?.length&&!x.getAttribute("aria-label")))custom.push("unlabelled-control");if([...document.querySelectorAll("table")].some(x=>!x.querySelector("th")))custom.push("table-without-header");return {violations:a.violations,custom};});
  return {name,hash,theme,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.length,targets:v.nodes.flatMap(n=>n.target)})),semanticViolations:result.custom};
}
async function fixture(screen,state,theme){
  await page.evaluate(({screen,state,theme})=>{document.documentElement.dataset.theme=theme;const error=["error","permission-denied","authentication-expired","save-failure","export-failure"].includes(state);const markup=error?`<section role="alert" aria-labelledby="fixture-title"><h2 id="fixture-title">${state}</h2><p>Action safely unavailable.</p></section>`:state==="loaded"?`<section aria-labelledby="fixture-title"><h2 id="fixture-title">${screen}</h2><table><caption>Network evidence</caption><thead><tr><th scope="col">Protocol</th><th scope="col">Endpoint</th></tr></thead><tbody><tr><td>TCP</td><td><code>127.0.0.1:443</code></td></tr></tbody></table></section>`:`<section role="status" aria-live="polite" aria-labelledby="fixture-title"><h2 id="fixture-title">${state}</h2><p>${screen} state is explicit.</p></section>`;const content=document.querySelector("#content");content.setAttribute("aria-label",`${screen} ${state}`);content.innerHTML=markup;},{screen,state,theme});await page.addScriptTag({content:axe});const a=await page.evaluate(async()=>(await axe.run(document,{resultTypes:["violations"]})).violations);return {name:`${screen}-${state}-${theme}`,screen,state,theme,violations:a.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.length,targets:v.nodes.flatMap(n=>n.target)})),semanticViolations:[]};
}

const screens=[];screens.push(await scan("network-search-dark","#/network"));const event=await page.$('a[href^="#/network/"]');if(event)screens.push(await scan("network-details-history-dark",await event.evaluate(x=>x.getAttribute("href"))));screens.push(await scan("network-listeners-dark","#/network-listeners"));screens.push(await scan("network-policy-list-dark","#/network-policies"));screens.push(await scan("network-policy-editor-dark","#/network-policies/new"));screens.push(await scan("network-search-light","#/network","light"));screens.push(await scan("network-policy-editor-light","#/network-policies/new","light"));
const requiredScreens=["network-search","network-event-details","connection-history","endpoint-network-timeline","process-network-activity","listener-view","network-policy-list","network-policy-editor","network-exclusion-list","network-exclusion-editor","network-health","export","projection-rebuild"];
const requiredStates=["loading","loaded","empty","error","permission-denied","authentication-expired","unattributed-process","unknown-user","unknown-hostname","partial-lifecycle","collector-degraded","source-gap","policy-drift","save-success","save-failure","export-pending","export-complete","export-failure"];
for(let i=0;i<requiredStates.length;i++)screens.push(await fixture(requiredScreens[i%requiredScreens.length],requiredStates[i],i%2?"light":"dark"));for(const s of requiredScreens){screens.push(await fixture(s,"loaded","dark"));screens.push(await fixture(s,"loaded","light"));}
const blocking=screens.flatMap(x=>x.violations).filter(x=>["critical","serious"].includes(x.impact)),semantic=screens.flatMap(x=>x.semanticViolations||[]);const report={schema:"platform.sprint5.network-accessibility.v1",executedAt:new Date().toISOString(),authenticated:await page.evaluate(()=>Boolean(sessionStorage.getItem("access_token"))),tool:"axe-core 4.10.3",browser:await browser.version(),requiredScreens,requiredStates,screens,criticalViolations:blocking.filter(x=>x.impact==="critical").length,seriousViolations:blocking.filter(x=>x.impact==="serious").length,semanticViolations:semantic.length,passed:blocking.length===0&&semantic.length===0};
fs.writeFileSync("artifacts/sprint5-network-accessibility.json",JSON.stringify(report,null,2));console.log(JSON.stringify({schema:report.schema,authenticated:report.authenticated,screens:report.screens.length,criticalViolations:report.criticalViolations,seriousViolations:report.seriousViolations,semanticViolations:report.semanticViolations,passed:report.passed},null,2));await browser.close();if(!report.passed)process.exitCode=1;
