using OpenSecurityPlatform.Foundation;
using OpenSecurityPlatform.Infrastructure;

static class AgentProtectionRoutes
{
    static string Tenant(HttpContext c) => c.Items["tenant"]!.ToString()!;
    static string Actor(HttpContext c) => ((PrincipalContext)c.Items["principal"]!).Subject;
    static IResult Ok(HttpContext c, object value) => Results.Ok(new ApiEnvelope<object>(value, new(c.TraceIdentifier, "1.0")));
    static IResult Problem(HttpContext c, string code, string detail, int status = 400) => Results.Problem(statusCode: status, title: code, detail: detail, extensions: new Dictionary<string, object?> { ["code"] = code, ["traceId"] = c.TraceIdentifier });
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/endpoints/{endpoint:guid}/self-protection", Status).RequirePermission("response:read");
        app.MapGet("/api/v1/endpoints/{endpoint:guid}/self-protection/resources", Resources).RequirePermission("response:read");
        app.MapGet("/api/v1/endpoints/{endpoint:guid}/self-protection/tamper-events", Events).RequirePermission("response:read");
        app.MapPost("/api/v1/endpoints/{endpoint:guid}/self-protection:verify", Verify).RequirePermission("platform:admin");
        app.MapGet("/api/v1/endpoints/{endpoint:guid}/self-protection/policy", Policy).RequirePermission("response:read");
        app.MapPut("/api/v1/endpoints/{endpoint:guid}/self-protection/policy", PutPolicy).RequirePermission("platform:admin");
        app.MapPost("/api/v1/self-protection/maintenance", RequestMaintenance).RequirePermission("platform:admin");
        app.MapPost("/api/v1/self-protection/maintenance/{id:guid}:approve", ApproveMaintenance).RequirePermission("platform:admin");
        app.MapGet("/api/v1/self-protection/maintenance/{id:guid}", Maintenance).RequirePermission("response:read");
        app.MapPost("/api/v1/self-protection/repairs", Repair).RequirePermission("platform:admin");
        app.MapGet("/api/v1/self-protection/repairs/{id:guid}", RepairStatus).RequirePermission("response:read");
        app.MapGet("/api/v1/self-protection/health", Health).RequirePermission("response:read");
        app.MapGet("/agent/v1/self-protection/policy", AgentPolicy).RequirePermission("agent:heartbeat");
        app.MapGet("/agent/v1/self-protection/maintenance", AgentMaintenance).RequirePermission("agent:heartbeat");
        app.MapPost("/agent/v1/self-protection/reports", AgentReport).RequirePermission("agent:heartbeat");
        app.MapPost("/internal/v1/self-protection/self-test", SelfTest).RequirePermission("platform:admin");
    }
    static async Task<IResult> Status(Guid endpoint, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => await r.SnapshotAsync(Tenant(c), endpoint, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> Resources(Guid endpoint, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) { var policy = await r.PolicyAsync(Tenant(c), endpoint, ct); var snapshot = await r.SnapshotAsync(Tenant(c), endpoint, ct); return policy is null ? Results.NotFound() : Ok(c, new { policy.Version, policy.Resources, observed = snapshot?.Resources ?? [] }); }
    static async Task<IResult> Events(Guid endpoint, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => Ok(c, await r.EventsAsync(Tenant(c), endpoint, ParseLimit(c), ct));
    static async Task<IResult> Verify(Guid endpoint, HttpContext c, IAgentProtectionRepository r, CancellationToken ct)
    {
        var policy = await r.PolicyAsync(Tenant(c), endpoint, ct); var snapshot = await r.SnapshotAsync(Tenant(c), endpoint, ct); if (policy is null) return Results.NotFound(); var stale = snapshot is null || DateTimeOffset.UtcNow - snapshot.VerifiedAt > TimeSpan.FromSeconds(policy.VerificationIntervalSeconds * 2); return Ok(c, new { requestedAt = DateTimeOffset.UtcNow, latest = snapshot, stale, result = stale ? "verification-required-from-agent" : "latest-agent-verification-current" });
    }
    static async Task<IResult> Policy(Guid endpoint, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => await r.PolicyAsync(Tenant(c), endpoint, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> PutPolicy(Guid endpoint, AgentProtectionPolicy input, HttpContext c, IAgentProtectionRepository r, IResponseActionRepository targets, CancellationToken ct)
    {
        var target = await targets.ResolveTargetAsync(Tenant(c), endpoint, ct); if (target is null) return Results.NotFound(); if (input.EndpointId != endpoint || input.InstallationId != target.AgentInstallationId) return Problem(c, "PROTECTION_POLICY_TARGET", "Policy must bind the active endpoint installation."); return Ok(c, await r.PutPolicyAsync(Tenant(c), Actor(c), input with { TenantId = Tenant(c) }, ct));
    }
    static async Task<IResult> RequestMaintenance(MaintenanceRequest input, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => Ok(c, await r.RequestMaintenanceAsync(Tenant(c), Actor(c), input, ct));
    static async Task<IResult> ApproveMaintenance(Guid id, MaintenanceApproval input, HttpContext c, IAgentProtectionRepository r, CertificateAuthority authority, CancellationToken ct)
    {
        var approved = await r.ApproveMaintenanceAsync(Tenant(c), id, Actor(c), input, ct); var signed = authority.SignMaintenance(approved); return Ok(c, await r.FinalizeMaintenanceAsync(Tenant(c), id, signed.Algorithm, signed.KeyId, signed.Signature, ct));
    }
    static async Task<IResult> Maintenance(Guid id, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => await r.MaintenanceAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> Repair(RepairRequest input, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => Ok(c, await r.RequestRepairAsync(Tenant(c), Actor(c), input, ct));
    static async Task<IResult> RepairStatus(Guid id, HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => await r.RepairAsync(Tenant(c), id, ct) is { } value ? Ok(c, value) : Results.NotFound();
    static async Task<IResult> Health(HttpContext c, IAgentProtectionRepository r, CancellationToken ct) => Ok(c, await r.HealthAsync(Tenant(c), ct));
    static async Task<IResult> AgentPolicy(Guid endpointId, string installationId, HttpContext c, IAgentProtectionRepository r, IResponseActionRepository targets, CertificateAuthority authority, CancellationToken ct)
    {
        if (!await AgentBinding(c, targets, endpointId, installationId, ct)) return Results.Unauthorized(); var policy = await r.PolicyAsync(Tenant(c), endpointId, ct); return policy is null ? Results.NotFound() : Ok(c, authority.SignProtectionPolicy(policy));
    }
    static async Task<IResult> AgentMaintenance(Guid endpointId, string installationId, HttpContext c, IAgentProtectionRepository r, IResponseActionRepository targets, CancellationToken ct)
    {
        if (!await AgentBinding(c, targets, endpointId, installationId, ct)) return Results.Unauthorized(); return Ok(c, await r.ActiveMaintenanceAsync(Tenant(c), endpointId, installationId, ct));
    }
    static async Task<IResult> AgentReport(Guid endpointId, string installationId, ProtectionReport input, HttpContext c, IAgentProtectionRepository r, IResponseActionRepository targets, IAlertIncidentRepository alerts, CancellationToken ct)
    {
        if (!await AgentBinding(c, targets, endpointId, installationId, ct)) return Results.Unauthorized(); var snapshot = await r.ReportAsync(Tenant(c), endpointId, installationId, input, ct); foreach (var e in input.Events.Where(x => AgentProtectionSafety.TamperPack.ContainsKey(x.EventType))) await CreateTamperAlert(e, alerts, ct); return Ok(c, snapshot);
    }
    static async Task<bool> AgentBinding(HttpContext c, IResponseActionRepository targets, Guid endpoint, string installation, CancellationToken ct)
    {
        var principal = (PrincipalContext)c.Items["principal"]!; var ids = principal.Subject.Split(':'); if (principal.Type != "agent" || ids.Length != 2 || !Guid.TryParse(ids[0], out var principalEndpoint) || !Guid.TryParse(ids[1], out var principalAgent) || principalEndpoint != endpoint) return false; var target = await targets.ResolveTargetAsync(Tenant(c), endpoint, ct); return target is not null && target.AgentId == principalAgent && target.AgentInstallationId == installation;
    }
    static int ParseLimit(HttpContext c) => int.TryParse(c.Request.Query["limit"], out var n) ? n : 100;
    static async Task<IResult> SelfTest(HttpContext c, IAgentProtectionRepository production, IResponseActionRepository targets, IAlertIncidentRepository alerts, CancellationToken ct)
    {
        var tenant = Tenant(c); var endpoint = Guid.TryParse(c.Request.Query["endpoint"], out var supplied) ? supplied : Guid.Empty; var target = endpoint == Guid.Empty ? null : await targets.ResolveTargetAsync(tenant, endpoint, ct); if (target is null) return Problem(c, "PROTECTION_SELF_TEST_TARGET", "An active controlled endpoint query parameter is required.");
        AgentProtectionPolicy Seed(int version, string prior = "") { var resources = new[] { new ProtectedResourceDefinition("agent-copy", ProtectedResourceType.AgentBinary, @"C:\Sprint26Fixtures\Platform.Agent.fixture.exe", "SYSTEM", "protected-fixture", new string('a', 64), "fixture-native-a", "repository-signed", "0.3.0", "sha256+native-file-id+acl", null), new("service", ProtectedResourceType.AgentService, "PlatformSprint26Fixture", "SYSTEM", null, null, null, null, null, "SCM-query", "service-startup"), new("policy", ProtectedResourceType.PolicyCache, @"C:\Sprint26Fixtures\policy.json", "SYSTEM", null, new string('b', 64), null, null, "26", "signed-envelope+monotonic-version", "signed-policy-cache"), new("identity", ProtectedResourceType.Certificate, "LocalMachine/My fixture", "SYSTEM", null, null, null, "platform-ca", "installation-bound", "chain+extension+key-acl", null), new("queue", ProtectedResourceType.TelemetryQueue, @"C:\Sprint26Fixtures\queue", "SYSTEM", "protected-fixture", null, null, null, null, "record-hash+length+acl", null), new("quarantine", ProtectedResourceType.QuarantineStore, @"C:\Sprint26Fixtures\quarantine", "SYSTEM", "protected-fixture", null, null, null, null, "manifest-hash+acl", null), new("isolation", ProtectedResourceType.IsolationControl, "PlatformSprint26FixtureRules", "SYSTEM", null, null, null, null, null, "owned-rule-manifest", "isolation-rules") }; var p = new AgentProtectionPolicy("agent-protection-policy.v1", version, tenant, endpoint, target.AgentInstallationId, true, 30, 16 * 1024 * 1024, 128, true, true, true, resources, DateTimeOffset.UtcNow, Actor(c), prior, ""); return p with { PolicyHash = AgentProtectionSafety.PolicyHash(p) }; }
        var policy = await production.PolicyAsync(tenant, endpoint, ct); if (policy is null) policy = await production.PutPolicyAsync(tenant, Actor(c), ExpandInventory(Seed(1), target.AgentInstallationId), ct); else if (policy.Resources.Length < 19) policy = await production.PutPolicyAsync(tenant, Actor(c), ExpandInventory(Seed(policy.Version + 1, policy.PolicyHash), target.AgentInstallationId), ct);
        using var repo = new FileAgentProtectionRepository(); var p = await repo.PutPolicyAsync(tenant, "author", Seed(1), ct); var now = DateTimeOffset.UtcNow; ResourceIntegrityResult R(string id, ProtectedResourceType type, IntegrityState state, string observed, TamperPreventionResult prevention = TamperPreventionResult.DetectedOnly, RepairState repair = RepairState.NotRequested) => new(id, type, state, id, "expected", observed, "controlled-fixture", AgentProtectionSafety.Hash(new { id, state, observed }), now, prevention, repair, null, [], "controlled-sprint26-fixture"); var healthy = p.Resources.Select(x => R(x.ResourceId, x.Type, IntegrityState.Healthy, "expected")).ToArray();
        ProtectionReport Report(ResourceIntegrityResult[] rr, params TamperEvent[] ee) { var s = new ProtectionSnapshot("agent-protection-snapshot.v1", tenant, endpoint, target.AgentInstallationId, p.Version, AgentProtectionSafety.State(rr, false, true), now, rr, ee.Length, rr.Count(x => x.State != IntegrityState.Healthy), rr.Any(x => x.Repair == RepairState.Succeeded) ? RepairState.Succeeded : RepairState.NotRequested, false, null, "0.3.0", ""); s = s with { SnapshotHash = AgentProtectionSafety.SnapshotHash(s) }; return new(s, ee); }
        TamperEvent E(ResourceIntegrityResult rr, string type) { var id = AgentProtectionSafety.StableId(tenant, endpoint.ToString("D"), type, rr.ResourceId, rr.EvidenceHash); var e = new TamperEvent("agent-tamper-event.v1", id, tenant, endpoint, target.AgentInstallationId, type, rr.ResourceId, rr.Type, rr.ExpectedState, rr.ObservedState, rr.EvidenceHash, rr.Prevention, rr.Repair, null, now, p.Version, [$"controlled://sprint26/{rr.ResourceId}"], "controlled-sprint26-fixture", ""); return e with { EventHash = AgentProtectionSafety.EventHash(e) }; }
        var service = R("service", ProtectedResourceType.AgentService, IntegrityState.Disabled, "startup=Disabled", TamperPreventionResult.DetectedOnly, RepairState.Succeeded); var a = await repo.ReportAsync(tenant, endpoint, target.AgentInstallationId, Report(healthy.Select(x => x.ResourceId == "service" ? service : x).ToArray(), E(service, "agent.service.disabled")), ct); var file = R("agent-copy", ProtectedResourceType.AgentBinary, IntegrityState.Replaced, "sha256/native mismatch"); var b = await repo.ReportAsync(tenant, endpoint, target.AgentInstallationId, Report(healthy.Select(x => x.ResourceId == "agent-copy" ? file : x).ToArray(), E(file, "agent.file.replaced")), ct);
        var cPolicy = true; try { await repo.PutPolicyAsync(tenant, "attacker", Seed(1, p.PolicyHash), ct); cPolicy = false; } catch (EnrollmentConflictException) { }
        var queue = R("queue", ProtectedResourceType.TelemetryQueue, IntegrityState.Corrupt, "truncated-record"); var isolation = R("isolation", ProtectedResourceType.IsolationControl, IntegrityState.Modified, "owned-rule-missing", TamperPreventionResult.DetectedOnly, RepairState.Succeeded); var d = await repo.ReportAsync(tenant, endpoint, target.AgentInstallationId, Report(healthy.Select(x => x.ResourceId == "queue" ? queue : x.ResourceId == "isolation" ? isolation : x).ToArray(), E(queue, "agent.queue.tampered"), E(isolation, "agent.isolation.drift")), ct);
        var mr = await repo.RequestMaintenanceAsync(tenant, "requester", new(endpoint, target.AgentInstallationId, "controlled maintenance", ["repair"], DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddMinutes(5)), ct); var ma = await repo.ApproveMaintenanceAsync(tenant, mr.MaintenanceId, "approver", new(mr.RequestHash, "approved controlled maintenance"), ct); var eProfile = ma.State == MaintenanceState.Approved && ma.ExpiresAt - ma.StartsAt <= TimeSpan.FromHours(1); var duplicate = await repo.ReportAsync(tenant, endpoint, target.AgentInstallationId, Report(healthy, E(file, "agent.file.replaced")), ct); var duplicateAgain = await repo.ReportAsync(tenant, endpoint, target.AgentInstallationId, Report(healthy, E(file, "agent.file.replaced")), ct); var f = (await repo.EventsAsync(tenant, endpoint, 500, ct)).Count(x => x.EventId == E(file, "agent.file.replaced").EventId) == 1 && duplicate.SnapshotHash == duplicateAgain.SnapshotHash;
        var productionResources = policy.Resources.Select(x => R(x.ResourceId, x.Type, IntegrityState.Healthy, "expected")).ToArray(); var tamperedResource = productionResources.First(x => x.Type == ProtectedResourceType.PolicyCache); var productionEvent = E(tamperedResource with { State = IntegrityState.Modified, ObservedState = "controlled-policy-signature-mismatch" }, "agent.policy.tampered") with { PolicyVersion = policy.Version, InstallationId = policy.InstallationId }; productionEvent = productionEvent with { EventHash = AgentProtectionSafety.EventHash(productionEvent) }; var productionSnapshot = new ProtectionSnapshot("agent-protection-snapshot.v1", tenant, endpoint, policy.InstallationId, policy.Version, ProtectionState.TamperDetected, now, productionResources.Select(x => x.ResourceId == tamperedResource.ResourceId ? x with { State = IntegrityState.Modified, ObservedState = "controlled-policy-signature-mismatch" } : x).ToArray(), 1, 1, RepairState.NotRequested, false, null, "0.3.0", ""); productionSnapshot = productionSnapshot with { SnapshotHash = AgentProtectionSafety.SnapshotHash(productionSnapshot) }; await production.ReportAsync(tenant, endpoint, policy.InstallationId, new(productionSnapshot, [productionEvent]), ct); await CreateTamperAlert(productionEvent, alerts, ct);
        var profiles = new { A = a.State == ProtectionState.TamperDetected && service.Repair == RepairState.Succeeded, B = b.State == ProtectionState.TamperDetected, C = cPolicy, D = d.State == ProtectionState.TamperDetected && d.Resources.Count(x => x.State != IntegrityState.Healthy) == 2, E = eProfile, F = f }; return Ok(c, new { profiles, policyVersion = policy.Version, resources = p.Resources.Length, tamperPack = AgentProtectionSafety.TamperPack.Keys, productionSnapshot = productionSnapshot.SnapshotHash, productionEvent = productionEvent.EventId, security = new { privilegedTerminationPreventionClaimed = false, arbitraryCode = false, maintenanceBounded = true, privateKeyExposed = false }, passed = profiles.A && profiles.B && profiles.C && profiles.D && profiles.E && profiles.F });
    }
    static async Task CreateTamperAlert(TamperEvent e, IAlertIncidentRepository triage, CancellationToken token)
    {
        var evidence = new AlertEvidence([e.EndpointId], [], [], (e.ResourceType is ProtectedResourceType.AgentBinary or ProtectedResourceType.RequiredLibrary) ? [e.ResourceId] : [], [], [], [e.EventId], e.Evidence, [], [], [], [e.Prevention.ToString()], []);
        var candidate = new AlertCandidate(e.TenantId, AlertSourceType.AnalystPromotion, e.EventId, null, null, AgentProtectionSafety.StableId("tamper-rule", e.EventType), 1, 1, AgentProtectionSafety.TamperPack[e.EventType], $"Expected {e.ExpectedState}; observed {e.ObservedState}; prevention {e.Prevention}", 90, 95, "agent-tamper", ["Defense Evasion"], ["T1562.001"], ["AgentHealth"], e.OccurredAt, e.OccurredAt, e.EndpointId, null, e.ResourceId, $"tamper:{e.EndpointId:D}:{e.EventType}:{e.ResourceId}", evidence, DetectionExecutionMode.Live, true); await triage.CreateAlertAsync(e.TenantId, "agent-self-protection", candidate, token);
    }
    static AgentProtectionPolicy ExpandInventory(AgentProtectionPolicy policy, string installation)
    {
        ProtectedResourceDefinition[] additional = [
            new("required-library", ProtectedResourceType.RequiredLibrary, @"C:\Sprint26Fixtures\Platform.Shared.fixture.dll", "SYSTEM", null, null, null, "repository-signed", "0.3.0", "sha256+native-file-id+acl", null),
            new("agent-config", ProtectedResourceType.Configuration, @"C:\Sprint26Fixtures\agent-config.json", "SYSTEM", null, null, null, null, "26", "signed-config+acl", "signed-policy-cache"),
            new("private-key", ProtectedResourceType.PrivateKey, "LocalMachine/PlatformAgentKey", "SYSTEM", null, null, null, "platform-ca", "installation-bound", "key-presence+non-exportability+acl", null, Sensitive: true),
            new("response-replay", ProtectedResourceType.ResponseReplayState, @"C:\Sprint26Fixtures\response-replay.json", "SYSTEM", null, null, null, null, null, "record-hash+monotonic-sequence+acl", null),
            new("orchestration-state", ProtectedResourceType.OrchestrationState, @"C:\Sprint26Fixtures\orchestration-state.json", "SYSTEM", null, null, null, null, null, "record-hash+acl", null),
            new("forensic-state", ProtectedResourceType.ForensicState, @"C:\Sprint26Fixtures\forensic-state", "SYSTEM", null, null, null, null, null, "manifest-hash+bounded-progress+acl", null),
            new("update-manifest", ProtectedResourceType.UpdateManifest, @"C:\Sprint26Fixtures\update-manifest.json", "SYSTEM", null, null, null, "repository-signed", "0.3.0", "signature+version+acl", null),
            new("installation-record", ProtectedResourceType.InstallationIdentity, @"C:\Sprint26Fixtures\installation.json", "SYSTEM", null, null, null, "platform-ca", installation, "certificate+endpoint+installation-binding", null),
            new("collector-config", ProtectedResourceType.CollectorConfiguration, @"C:\Sprint26Fixtures\collector-config.json", "SYSTEM", null, null, null, null, "26", "signed-policy+acl", "signed-policy-cache"),
            new("response-worker", ProtectedResourceType.Configuration, @"C:\Sprint26Fixtures\response-worker.json", "SYSTEM", null, null, null, null, null, "signed-policy+replay-state", null),
            new("live-response-worker", ProtectedResourceType.Configuration, @"C:\Sprint26Fixtures\live-response-worker.json", "SYSTEM", null, null, null, null, null, "signed-session+transcript-state", null),
            new("etw-session-state", ProtectedResourceType.CollectorConfiguration, @"C:\Sprint26Fixtures\etw-session-state.json", "SYSTEM", null, null, null, null, null, "owned-session-marker+acl", null)
        ];
        var value = policy with { Resources = policy.Resources.Concat(additional).ToArray(), PolicyHash = "" };
        return value with { PolicyHash = AgentProtectionSafety.PolicyHash(value) };
    }
}
