using System.Diagnostics;
using OpenSecurityPlatform.Foundation;

static class AiEngineeringRoutes
{
    public static void MapAiEngineeringRoutes(this WebApplication app)
    {
        app.MapGet("/api/v1/ai-engineering/hunts", async (int? limit, HttpContext c, IAiEngineeringRepository r, CancellationToken ct) => Ok(c, await r.HuntsAsync(Tenant(c), limit ?? 50, ct))).RequirePermission("hunt:execute");
        app.MapPost("/api/v1/ai-engineering/hunts", ProposeHunt).RequirePermission("ai:investigate");
        app.MapGet("/api/v1/ai-engineering/hunts/{id:guid}", async (Guid id, HttpContext c, IAiEngineeringRepository r, CancellationToken ct) => await r.HuntAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("hunt:execute");
        app.MapPost("/api/v1/ai-engineering/hunts/{id:guid}/execute", ExecuteHunt).RequirePermission("hunt:execute");
        app.MapGet("/api/v1/ai-engineering/drafts", async (int? limit, HttpContext c, IAiEngineeringRepository r, CancellationToken ct) => Ok(c, await r.DraftsAsync(Tenant(c), limit ?? 50, ct))).RequirePermission("detection:read");
        app.MapPost("/api/v1/ai-engineering/detection-drafts", DraftDetection).RequirePermission("detection:draft:manage");
        app.MapPost("/api/v1/ai-engineering/correlation-drafts", DraftCorrelation).RequirePermission("correlation:draft:manage");
        app.MapGet("/api/v1/ai-engineering/drafts/{id:guid}", async (Guid id, HttpContext c, IAiEngineeringRepository r, CancellationToken ct) => await r.DraftAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("detection:read");
        app.MapPost("/api/v1/ai-engineering/drafts/{id:guid}/save", SaveDraft).RequirePermission("detection:draft:manage");
        app.MapPost("/api/v1/ai-engineering/drafts/{id:guid}/reject", RejectDraft).RequirePermission("detection:draft:manage");
        app.MapPost("/api/v1/ai-engineering/drafts/{id:guid}/simulate", Simulate).RequirePermission("detection:simulation:run");
        app.MapPost("/api/v1/ai-engineering/drafts/{id:guid}/compare", Compare).RequirePermission("detection:simulation:run");
        app.MapPost("/api/v1/ai-engineering/drafts/{id:guid}/tuning", Tuning).RequirePermission("detection:simulation:run");
        app.MapPost("/api/v1/ai-engineering/drafts/{id:guid}/exclusion-review", ExclusionReview).RequirePermission("detection:exclusion:manage");
        app.MapGet("/api/v1/ai-engineering/detection-rules/{id:guid}/explain", ExplainRule).RequirePermission("detection:read");
        app.MapGet("/api/v1/ai-engineering/inventory", Inventory).RequirePermission("detection:read");
        app.MapGet("/api/v1/ai-engineering/coverage", Coverage).RequirePermission("correlation:coverage:read");
        app.MapGet("/api/v1/ai-engineering/audit", async (int? limit, HttpContext c, IAiEngineeringRepository r, CancellationToken ct) => Ok(c, await r.AuditAsync(Tenant(c), limit ?? 100, ct))).RequirePermission("ai:audit");
        app.MapPost("/internal/v1/ai-engineering/self-test", SelfTest).RequirePermission("system:admin");
    }

    static async Task<IResult> ProposeHunt(HuntProposalRequest x, HttpContext c, IAiEngineeringRepository r, CancellationToken ct)
    {
        var value = AiEngineeringSafety.TranslateHunt(Tenant(c), Actor(c), x.Prompt, x.EvidenceCitations ?? [], x.EvidencePackageHash ?? "none"); await r.SaveHuntAsync(value, ct); await Audit(r, value.TenantId, value.Analyst, "ai.hunt.proposed", "hunt-proposal", value.ProposalId, value.ProposalHash, new Dictionary<string, string?> { ["estimatedCost"] = S(value.EstimatedCost), ["promptHash"] = value.PromptHash }, ct); return Results.Created($"/api/v1/ai-engineering/hunts/{value.ProposalId:D}", new ApiEnvelope<object>(value, new(c.TraceIdentifier, "1.0")));
    }
    static async Task<IResult> ExecuteHunt(Guid id, ProposalDecision x, HttpContext c, IAiEngineeringRepository r, IInvestigationRepository investigations, CancellationToken ct)
    {
        var tenant = Tenant(c); var proposal = await r.HuntAsync(tenant, id, ct); if (proposal is null) return Results.NotFound(); if (proposal.ProposalHash != x.ProposalHash) throw new EnrollmentConflictException("AI_PROPOSAL_SUBSTITUTION", "The approved proposal hash does not match."); if (proposal.State == AiProposalState.Executed) return Ok(c, proposal);
        var validation = await investigations.ValidateHuntAsync(tenant, proposal.Hunt, ct); if (!validation.Valid) throw new EnrollmentConflictException("AI_HUNT_INVALID", string.Join(' ', validation.Errors.Values.SelectMany(v => v))); var run = await investigations.ExecuteHuntAsync(tenant, proposal.Hunt, ct); proposal = await r.UpdateHuntAsync(tenant, id, p => p with { State = AiProposalState.Executed, ExecutedAt = DateTimeOffset.UtcNow, HuntRunId = run.RunId, ResultCount = run.Returned }, ct); await Audit(r, tenant, Actor(c), "ai.hunt.execution.approved", "hunt-proposal", id, proposal.ProposalHash, new Dictionary<string, string?> { ["reason"] = x.Reason, ["runId"] = run.RunId.ToString("D"), ["results"] = S(run.Returned) }, ct); return Ok(c, new { proposal, run });
    }
    static async Task<IResult> DraftDetection(DetectionDraftRequest x, HttpContext c, IAiEngineeringRepository r, CancellationToken ct)
    {
        var value = AiEngineeringSafety.DraftDetection(Tenant(c), Actor(c), x.Prompt, x.Domain, x.Field, x.Operator, x.Value, x.MitreTechnique, x.EvidenceCitations ?? [], x.EvidencePackageHash ?? "none"); var fixtureErrors = AiEngineeringSafety.ValidateFixtures(value); if (fixtureErrors.Count > 0) throw new EnrollmentConflictException("AI_FIXTURE_VALIDATION_FAILED", string.Join(' ', fixtureErrors.Values.SelectMany(v => v))); await r.SaveDraftAsync(value, ct); await Audit(r, value.TenantId, value.Analyst, "ai.detection.draft.proposed", "rule-draft", value.DraftId, value.DraftHash, new Dictionary<string, string?> { ["promptHash"] = value.PromptHash, ["productionEnabled"] = "false" }, ct); return Results.Created($"/api/v1/ai-engineering/drafts/{value.DraftId:D}", new ApiEnvelope<object>(value, new(c.TraceIdentifier, "1.0")));
    }
    static async Task<IResult> DraftCorrelation(CorrelationDraftRequest x, HttpContext c, IAiEngineeringRepository r, ICorrelationRepository correlations, CancellationToken ct)
    {
        var value = AiEngineeringSafety.DraftCorrelation(Tenant(c), Actor(c), x.Prompt, x.Type, x.FirstDomain, x.SecondDomain, x.JoinKey, x.MitreTechnique, x.EvidenceCitations ?? [], x.EvidencePackageHash ?? "none"); var packs = await correlations.ListPacksAsync(Tenant(c), ct); var pack = packs.Count > 0 ? packs[0] : null; if (pack is not null) { value = value with { Correlation = value.Correlation! with { PackId = pack.PackId, PackVersion = pack.Version } }; value = value with { DraftHash = AiEngineeringSafety.Hash(value with { DraftHash = "" }) }; }
        await r.SaveDraftAsync(value, ct); await Audit(r, value.TenantId, value.Analyst, "ai.correlation.draft.proposed", "rule-draft", value.DraftId, value.DraftHash, new Dictionary<string, string?> { ["productionEnabled"] = "false" }, ct); return Results.Created($"/api/v1/ai-engineering/drafts/{value.DraftId:D}", new ApiEnvelope<object>(value, new(c.TraceIdentifier, "1.0")));
    }
    static async Task<IResult> SaveDraft(Guid id, ProposalDecision x, HttpContext c, IAiEngineeringRepository r, IDetectionRepository detections, ICorrelationRepository correlations, CancellationToken ct)
    {
        var tenant = Tenant(c); var actor = Actor(c); var draft = await r.DraftAsync(tenant, id, ct); if (draft is null) return Results.NotFound(); if (draft.DraftHash != x.ProposalHash) throw new EnrollmentConflictException("AI_DRAFT_SUBSTITUTION", "The approved AI draft hash does not match."); if (draft.State == AiProposalState.SavedDraft) return Ok(c, draft); Guid ruleId; int version;
        if (draft.Detection is { } detection) { var saved = await detections.CreateRuleAsync(tenant, actor, detection with { Status = DetectionRuleStatus.Draft, Enabled = false, LastValidationPassed = false }, ct); ruleId = saved.DetectionId; version = saved.DetectionVersion; }
        else if (draft.Correlation is { } correlation) { if ((await correlations.GetPackAsync(tenant, correlation.PackId, correlation.PackVersion, ct)) is null) throw new EnrollmentConflictException("AI_CORRELATION_PACK_REQUIRED", "A reviewed existing correlation pack is required before repository save."); var saved = await correlations.PutRuleAsync(tenant, actor, correlation with { Status = CorrelationStatus.Draft, Enabled = false, ValidationPassed = false }, false, ct); ruleId = saved.CorrelationRuleId; version = saved.Version; }
        else throw new EnrollmentConflictException("AI_DRAFT_EMPTY", "Draft contains no bounded rule.");
        draft = await r.UpdateDraftAsync(tenant, id, d => d with { State = AiProposalState.SavedDraft, DecidedAt = DateTimeOffset.UtcNow, DecidedBy = actor, DecisionReason = x.Reason, RepositoryRuleId = ruleId, RepositoryRuleVersion = version }, ct); await Audit(r, tenant, actor, "ai.rule.draft.saved.by-human", "rule-draft", id, draft.DraftHash, new Dictionary<string, string?> { ["reason"] = x.Reason, ["ruleId"] = ruleId.ToString("D"), ["active"] = "false" }, ct); return Ok(c, draft);
    }
    static async Task<IResult> RejectDraft(Guid id, ProposalDecision x, HttpContext c, IAiEngineeringRepository r, CancellationToken ct)
    {
        var tenant = Tenant(c); var draft = await r.DraftAsync(tenant, id, ct); if (draft is null) return Results.NotFound(); if (draft.DraftHash != x.ProposalHash) throw new EnrollmentConflictException("AI_DRAFT_SUBSTITUTION", "The rejected AI draft hash does not match."); draft = await r.UpdateDraftAsync(tenant, id, d => d with { State = AiProposalState.Rejected, DecidedAt = DateTimeOffset.UtcNow, DecidedBy = Actor(c), DecisionReason = x.Reason }, ct); await Audit(r, tenant, Actor(c), "ai.rule.draft.rejected", "rule-draft", id, draft.DraftHash, new Dictionary<string, string?> { ["reason"] = x.Reason }, ct); return Ok(c, draft);
    }
    static async Task<IResult> Simulate(Guid id, SimulationRequest x, HttpContext c, IAiEngineeringRepository r, IDetectionEventSource source, CancellationToken ct)
    {
        var tenant = Tenant(c); var draft = await r.DraftAsync(tenant, id, ct); if (draft?.Detection is not { } rule) return Results.NotFound(); if (draft.DraftHash != x.DraftHash) throw new EnrollmentConflictException("AI_DRAFT_SUBSTITUTION", "Simulation draft hash does not match."); if (x.To <= x.From || x.To - x.From > TimeSpan.FromDays(30) || x.MaximumEvents is < 1 or > AiEngineeringSafety.MaximumHistoricalEvents) throw new EnrollmentConflictException("AI_SIMULATION_BOUNDS", "Historical simulation range or event count exceeds bounds."); var sw = Stopwatch.StartNew(); var events = await source.LoadAsync(tenant, rule.Domain, x.From, x.To, x.MaximumEvents, ct); var matches = events.Where(e => DetectionDsl.Evaluate(rule, e).Matched).ToArray(); sw.Stop(); var result = new AiHistoricalSimulation(Guid.NewGuid(), tenant, id, x.From, x.To, x.MaximumEvents, events.Count, matches.Length, matches.Select(e => e.EndpointId).Where(v => v is not null).Distinct().Count(), matches.Take(20).Select(e => e.EvidenceReference).ToArray(), [], sw.ElapsedMilliseconds, matches.Length, matches.GroupBy(e => e.Fields.GetValueOrDefault("processPath") ?? e.Fields.GetValueOrDefault("user") ?? "unclassified").OrderByDescending(g => g.Count()).Take(10).Select(g => $"{g.Key}:{g.Count()}").ToArray(), DateTimeOffset.UtcNow); await r.SaveSimulationAsync(result, ct); await Audit(r, tenant, Actor(c), "ai.rule.historical-simulation", "rule-draft", id, draft.DraftHash, new Dictionary<string, string?> { ["events"] = S(events.Count), ["matches"] = S(matches.Length) }, ct); return Ok(c, result);
    }
    static async Task<IResult> Compare(Guid id, ComparisonRequest x, HttpContext c, IAiEngineeringRepository r, IDetectionRepository detections, IDetectionEventSource source, CancellationToken ct)
    {
        var tenant = Tenant(c); var draft = await r.DraftAsync(tenant, id, ct); if (draft?.Detection is not { } proposed) return Results.NotFound(); if (draft.DraftHash != x.DraftHash) throw new EnrollmentConflictException("AI_DRAFT_SUBSTITUTION", "Comparison draft hash does not match."); if (x.To <= x.From || x.To - x.From > TimeSpan.FromDays(30) || x.MaximumEvents is < 1 or > AiEngineeringSafety.MaximumHistoricalEvents) throw new EnrollmentConflictException("AI_COMPARISON_BOUNDS", "Comparison range or event count exceeds bounds."); var current = await detections.GetRuleAsync(tenant, x.CurrentRuleId, x.CurrentVersion, ct) ?? throw new KeyNotFoundException(); if (current.Domain != proposed.Domain) throw new EnrollmentConflictException("AI_COMPARISON_DOMAIN", "Rule versions must use the same telemetry domain."); var events = await source.LoadAsync(tenant, proposed.Domain, x.From, x.To, x.MaximumEvents, ct); var oldSet = events.Where(e => DetectionDsl.Evaluate(current, e).Matched).Select(e => e.EventId).ToHashSet(); var newSet = events.Where(e => DetectionDsl.Evaluate(proposed, e).Matched).Select(e => e.EventId).ToHashSet(); var result = new AiRuleComparison(Guid.NewGuid(), tenant, id, current.DetectionId, current.DetectionVersion, newSet.Except(oldSet).Count(), oldSet.Except(newSet).Count(), oldSet.Intersect(newSet).Count(), newSet.Count - oldSet.Count, events.Where(e => newSet.Contains(e.EventId) || oldSet.Contains(e.EventId)).Select(e => e.EndpointId).Distinct().Count(), 1, proposed.Severity - current.Severity, 0, DateTimeOffset.UtcNow); await r.SaveComparisonAsync(result, ct); await Audit(r, tenant, Actor(c), "ai.rule.version-compared", "rule-draft", id, draft.DraftHash, new Dictionary<string, string?> { ["currentRule"] = current.DetectionId.ToString("D") }, ct); return Ok(c, result);
    }
    static async Task<IResult> Tuning(Guid id, TuningRequest x, HttpContext c, IAiEngineeringRepository r, CancellationToken ct)
    {
        var tenant = Tenant(c); var draft = await r.DraftAsync(tenant, id, ct); if (draft?.Detection is not { } rule) return Results.NotFound(); if (draft.DraftHash != x.DraftHash) throw new EnrollmentConflictException("AI_DRAFT_SUBSTITUTION", "Tuning draft hash does not match."); var simulation = await r.SimulationAsync(tenant, x.SimulationId, ct); if (simulation is null || simulation.DraftId != id) throw new EnrollmentConflictException("AI_TUNING_EVIDENCE_INVALID", "Tuning requires an exact tenant-owned historical simulation for this draft.");
        var highVolume = simulation.EventsScanned > 0 && (double)simulation.Matches / simulation.EventsScanned >= 0.25; var recommendation = new { label = "AI proposed", kind = highVolume ? "field-constraint" : "threshold-review", currentThreshold = rule.Threshold, suggestedThreshold = highVolume ? Math.Max(2, rule.Threshold) : rule.Threshold, why = highVolume ? "The controlled historical result matched at least 25% of scanned events; add an identity-safe field constraint before considering activation." : "The bounded historical result does not justify an automatic threshold change.", evidence = simulation.ExampleEvidenceReferences, historical = new { simulation.SimulationId, simulation.EventsScanned, simulation.Matches, simulation.EndpointCount, simulation.FalsePositiveClusters, simulation.RuntimeMilliseconds }, expectedImpact = highVolume ? "Lower estimated benign alert volume after a separately reviewed constraint and re-simulation." : "No mutation; preserve the current draft pending more evidence.", risks = new[] { "Frequency does not prove benign intent.", "Any constraint can create false negatives and requires fixture plus historical comparison." }, mutationApplied = false, productionChanged = false };
        await Audit(r, tenant, Actor(c), "ai.rule.tuning.recommended", "rule-draft", id, draft.DraftHash, new Dictionary<string, string?> { ["simulationId"] = simulation.SimulationId.ToString("D"), ["events"] = S(simulation.EventsScanned), ["matches"] = S(simulation.Matches), ["mutationApplied"] = "false" }, ct); return Ok(c, recommendation);
    }
    static async Task<IResult> ExclusionReview(Guid id, ExclusionReviewRequest x, HttpContext c, IAiEngineeringRepository r, CancellationToken ct)
    {
        var draft = await r.DraftAsync(Tenant(c), id, ct); if (draft is null) return Results.NotFound(); if (draft.DraftHash != x.DraftHash) throw new EnrollmentConflictException("AI_DRAFT_SUBSTITUTION", "Exclusion review draft hash does not match."); if (!AiEngineeringSafety.NarrowExclusion(x.Field, x.Value)) throw new EnrollmentConflictException("AI_EXCLUSION_TOO_BROAD", "AI exclusions must combine narrow exact identity, path, signer, hash, or endpoint context."); var result = new { label = "AI proposed", field = x.Field, value = x.Value, reason = x.Reason, expectedImpact = "Requires bounded historical simulation.", risks = new[] { "May hide future malicious use of the same exact context." }, created = false }; await Audit(r, draft.TenantId, Actor(c), "ai.exclusion.recommended", "rule-draft", id, draft.DraftHash, new Dictionary<string, string?> { ["field"] = x.Field, ["valueHash"] = AiEngineeringSafety.Hash(x.Value), ["created"] = "false" }, ct); return Ok(c, result);
    }
    static async Task<IResult> ExplainRule(Guid id, int? version, HttpContext c, IDetectionRepository detections, CancellationToken ct)
    {
        var rule = await detections.GetRuleAsync(Tenant(c), id, version, ct); if (rule is null) return Results.NotFound(); var tests = await detections.ListTestsAsync(Tenant(c), rule.DetectionId, rule.DetectionVersion, ct); return Ok(c, new { authority = rule, explanation = new { purpose = rule.Description, telemetryDependencies = rule.DataSources, logic = rule.Condition, threshold = rule.Threshold, windowSeconds = rule.WindowSeconds, exclusions = rule.ExclusionReferences, suppression = rule.Suppression, attack = rule.MitreTechniques, limitations = rule.Prerequisites, expectedFalsePositives = "Environment-specific; validate with fixtures and bounded historical simulation.", exampleEvidence = tests.Select(x => x.Name).Take(10) }, review = AiEngineeringSafety.Review(rule), aiGenerated = true, readOnly = true });
    }
    static async Task<IResult> Inventory(HttpContext c, IDetectionRepository detections, ICorrelationRepository correlations, CancellationToken ct)
    {
        var tenant = Tenant(c); var dr = await detections.ListRulesAsync(tenant, ct); var cr = await correlations.ListRulesAsync(tenant, null, ct); return Ok(c, new { detections = dr.Select(x => new { x.DetectionId, x.DetectionVersion, x.Name, x.Status, x.Enabled, x.Domain, x.Severity, x.MitreTechniques, x.LastValidationPassed, x.LastValidatedAt }), correlations = cr.Select(x => new { x.CorrelationRuleId, x.Version, x.Name, x.Status, x.Enabled, x.RequiredTelemetry, x.Severity, technique = x.MitreTechnique, x.ValidationPassed, x.ValidatedAt }) });
    }
    static async Task<IResult> Coverage(HttpContext c, IDetectionRepository detections, ICorrelationRepository correlations, CancellationToken ct)
    {
        var tenant = Tenant(c); var detectionRules = await detections.ListRulesAsync(tenant, ct); var correlationRules = await correlations.ListRulesAsync(tenant, null, ct); var source = await correlations.CoverageAsync(tenant, ct); var rows = new List<AiCoverageRecord>(); foreach (var row in source) { var dr = detectionRules.Where(x => x.MitreTechniques.Contains(row.Technique)).ToArray(); var cr = correlationRules.Where(x => x.MitreTechnique == row.Technique || x.MitreSubTechnique == row.SubTechnique).ToArray(); var fields = dr.SelectMany(x => x.RequiredFields).Distinct().ToArray(); var fixtures = new List<string>(); foreach (var rule in dr) fixtures.AddRange((await detections.ListTestsAsync(tenant, rule.DetectionId, rule.DetectionVersion, ct)).Where(x => x.Result.Passed).Select(x => x.Name)); rows.Add(AiEngineeringSafety.Coverage(row, dr.Select(x => x.DetectionId).Distinct().ToArray(), cr.Select(x => x.CorrelationRuleId).Distinct().ToArray(), fields, fixtures.Distinct().ToArray(), dr.Select(x => x.LastValidatedAt).Concat(cr.Select(x => x.ValidatedAt)).Where(x => x is not null).Max(), cr.SelectMany(x => x.Quality.SupportLimitations).Distinct().ToArray())); }
        return Ok(c, rows.OrderBy(x => x.Tactic).ThenBy(x => x.Technique));
    }
    static async Task<IResult> SelfTest(HttpContext c, IAiEngineeringRepository r, IInvestigationRepository investigations, CancellationToken ct)
    {
        var tenant = Tenant(c); var actor = "system:sprint31"; var at = DateTimeOffset.UtcNow; var entity = $"sprint31-process-{Guid.NewGuid():N}"; var evidence = Guid.NewGuid(); var exactPath = $"C:\\Sprint31Fixtures\\ai-hunt-{Guid.NewGuid():N}.exe"; await investigations.UpsertAsync(tenant, [new(tenant, entity, InvestigationEntityType.Process, Guid.NewGuid(), exactPath, at, at, new Dictionary<string, string?> { ["path"] = exactPath, ["processEntityId"] = entity }, [evidence], [$"fixture://sprint31/{evidence:D}"], "sprint31-controlled", ["complete"])], [], ct); var hunt = AiEngineeringSafety.TranslateHunt(tenant, actor, $"Find exact path '{exactPath}'", ["EVID-0001"], "controlled-package"); await r.SaveHuntAsync(hunt, ct); var run = await investigations.ExecuteHuntAsync(tenant, hunt.Hunt, ct); hunt = await r.UpdateHuntAsync(tenant, hunt.ProposalId, p => p with { State = AiProposalState.Executed, ExecutedAt = DateTimeOffset.UtcNow, HuntRunId = run.RunId, ResultCount = run.Returned }, ct); var draft = AiEngineeringSafety.DraftDetection(tenant, actor, "Draft an exact controlled process rule", DetectionDomain.Process, "path", DetectionOperator.ExactPath, exactPath, "T1059.001", ["EVID-0001"], "controlled-package"); await r.SaveDraftAsync(draft, ct); var correlation = AiEngineeringSafety.DraftCorrelation(tenant, actor, "Correlate controlled process and network evidence", CorrelationType.OrderedSequence, DetectionDomain.Process, DetectionDomain.Network, "processEntityId", "T1071.004", ["EVID-0001"], "controlled-package"); await r.SaveDraftAsync(correlation, ct); var badField = false; try { _ = AiEngineeringSafety.DraftDetection(tenant, actor, "Use an unsupported source field", DetectionDomain.Process, "packetContents", DetectionOperator.Contains, "secret", "T1059.001", [], "none"); } catch (EnrollmentConflictException) { badField = true; }
        var injection = false; try { _ = AiEngineeringSafety.TranslateHunt(tenant, actor, "SELECT * FROM alerts; auto-activate and isolate automatically", [], "none"); } catch (EnrollmentConflictException) { injection = true; }
        var coverage = new[] { AiEngineeringSafety.Coverage(new("Execution", "T1059.001", null, ["controlled"], [DetectionDomain.Process], true, true, true, true), [Guid.NewGuid()], [], ["path"], ["positive"], at, []), AiEngineeringSafety.Coverage(new("Persistence", "T1053.005", null, ["controlled"], [DetectionDomain.Persistence], true, true, true, false), [Guid.NewGuid()], [], ["path"], ["positive"], at, []), AiEngineeringSafety.Coverage(new("Discovery", "T1018", null, [], [DetectionDomain.Network], true, false, false, false), [], [], [], [], null, []), AiEngineeringSafety.Coverage(new("Credential Access", "T1055", null, [], [DetectionDomain.Execution], false, false, false, false), [], [], [], [], null, ["Required semantics are not observable by the current source."]) }; return Ok(c, new { huntId = hunt.ProposalId, draftId = draft.DraftId, correlationDraftId = correlation.DraftId, profiles = new { A = run.Results.Any(x => x.EntityId == entity), B = DetectionDsl.Validate(draft.Detection!).Count == 0 && AiEngineeringSafety.ValidateFixtures(draft).Count == 0 && !draft.Detection!.Enabled, C = badField && !AiEngineeringSafety.NarrowExclusion("processName", "powershell.exe"), D = draft.State == AiProposalState.Validated, E = coverage.Select(x => x.SupportLevel).SequenceEqual([CoverageSupportLevel.Covered, CoverageSupportLevel.PartiallyCovered, CoverageSupportLevel.TelemetryAvailableNoDetection, CoverageSupportLevel.NotObservableBySource]), F = injection }, noActivation = true, noResponse = true, noRawQuery = true });
    }

    static Task Audit(IAiEngineeringRepository r, string tenant, string actor, string action, string type, Guid id, string hash, IReadOnlyDictionary<string, string?> detail, CancellationToken ct) => r.RecordAuditAsync(new(Guid.NewGuid(), tenant, actor, action, type, id, hash, DateTimeOffset.UtcNow, detail), ct);
    static IResult Ok(HttpContext c, object value) => Results.Ok(new ApiEnvelope<object>(value, new(c.TraceIdentifier, "1.0")));
    static string Tenant(HttpContext c) => c.Items["tenant"]?.ToString() ?? throw new UnauthorizedAccessException();
    static string Actor(HttpContext c) => c.Items["principal"] is PrincipalContext principal ? principal.Subject : "unknown";
    static string S(int value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    sealed record HuntProposalRequest(string Prompt, string[]? EvidenceCitations = null, string? EvidencePackageHash = null);
    sealed record DetectionDraftRequest(string Prompt, DetectionDomain Domain, string Field, DetectionOperator Operator, string Value, string MitreTechnique, string[]? EvidenceCitations = null, string? EvidencePackageHash = null);
    sealed record CorrelationDraftRequest(string Prompt, CorrelationType Type, DetectionDomain FirstDomain, DetectionDomain SecondDomain, string JoinKey, string MitreTechnique, string[]? EvidenceCitations = null, string? EvidencePackageHash = null);
    sealed record ProposalDecision(string ProposalHash, string Reason);
    sealed record SimulationRequest(string DraftHash, DateTimeOffset From, DateTimeOffset To, int MaximumEvents = 5000);
    sealed record ComparisonRequest(string DraftHash, Guid CurrentRuleId, int? CurrentVersion, DateTimeOffset From, DateTimeOffset To, int MaximumEvents = 5000);
    sealed record ExclusionReviewRequest(string DraftHash, string Field, string Value, string Reason);
    sealed record TuningRequest(string DraftHash, Guid SimulationId);
}
