using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Text;
using OpenSecurityPlatform.Foundation;

sealed class FileCapacityRetentionRepository : ICapacityRetentionRepository
{
    readonly ConcurrentDictionary<string, List<RetentionPolicy>> policies = new(); readonly ConcurrentDictionary<string, List<RetentionHold>> holds = new(); readonly ConcurrentDictionary<string, List<RetentionFixture>> fixtures = new(); readonly ConcurrentDictionary<string, List<RetentionRun>> runs = new(); readonly ConcurrentDictionary<string, TenantCapacityQuota> quotas = new(); readonly List<CapacitySample> samples = []; readonly object gate = new();
    public Task<RetentionPolicy> PutPolicyAsync(string t, string a, Guid? id, RetentionPolicyRequest r, CancellationToken ct) { CapacityRetentionSafety.Validate(r); lock (gate) { var list = policies.GetOrAdd(t, _ => []); var prior = list.Where(x => x.PolicyId == (id ?? Guid.Empty)).OrderByDescending(x => x.Version).FirstOrDefault(); var x = new RetentionPolicy(id ?? Guid.NewGuid(), t, (prior?.Version ?? 0) + 1, r.Category, r.AuthorityDays, r.ProjectionDays, r.BatchSize, r.ArchiveBeforeDelete, r.Enabled, DateTimeOffset.UtcNow, a, prior?.PolicyHash ?? "", ""); x = x with { PolicyHash = CapacityRetentionSafety.Hash(x with { PolicyHash = "", CreatedAt = default, CreatedBy = "" }) }; list.Add(x); return Task.FromResult(x); } }
    public Task<IReadOnlyList<RetentionPolicy>> PoliciesAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<RetentionPolicy>>(policies.GetValueOrDefault(t) ?? []);
    public Task<RetentionHold> PutHoldAsync(string t, string a, RetentionHoldRequest r, CancellationToken ct) { CapacityRetentionSafety.Validate(r, DateTimeOffset.UtcNow); var x = new RetentionHold(Guid.NewGuid(), t, r.HoldType, r.Category, r.TargetId, r.Reason, true, DateTimeOffset.UtcNow, r.ExpiresAt, a); lock (gate) holds.GetOrAdd(t, _ => []).Add(x); return Task.FromResult(x); }
    public Task<IReadOnlyList<RetentionHold>> HoldsAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<RetentionHold>>(holds.GetValueOrDefault(t) ?? []);
    public Task<RetentionHold> ReleaseHoldAsync(string t, Guid id, CancellationToken ct) { lock (gate) { var list = holds.GetValueOrDefault(t) ?? throw new KeyNotFoundException(); var index = list.FindIndex(x => x.HoldId == id && x.Active); if (index < 0) throw new KeyNotFoundException(); list[index] = list[index] with { Active = false }; return Task.FromResult(list[index]); } }
    public async Task<RetentionPreview> PreviewAsync(string t, Guid id, string scope, CancellationToken ct) { var p = (await PoliciesAsync(t, ct)).Where(x => x.PolicyId == id).OrderByDescending(x => x.Version).First(); var cutoff = DateTimeOffset.UtcNow.AddDays(-p.AuthorityDays); var old = (fixtures.GetValueOrDefault(t) ?? []).Where(x => x.Category == p.Category && x.OccurredAt < cutoff).ToArray(); var h = holds.GetValueOrDefault(t) ?? []; var eligible = old.Where(x => !x.ActiveReference && !h.Any(y => y.Active && y.Category == x.Category && (y.TargetId is null || y.TargetId == x.RecordId.ToString("D")))).ToArray(); var now = DateTimeOffset.UtcNow; var v = new RetentionPreview(Guid.NewGuid(), t, id, p.Version, scope, cutoff, eligible.Length, eligible.Sum(x => (long)x.PayloadBytes), old.Length - eligible.Length, "", now, now.AddMinutes(10)); return v with { PreviewHash = CapacityRetentionSafety.Hash(v with { PreviewHash = "", CreatedAt = default, ExpiresAt = default }) }; }
    public Task<RetentionRun> ExecuteAsync(string t, string a, Guid preview, string hash, bool dry, CancellationToken ct) { var x = new RetentionRun(Guid.NewGuid(), t, preview, Guid.Empty, 1, dry ? "Previewed" : "Completed", dry, 0, 0, 0, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow, a, "development adapter"); lock (gate) runs.GetOrAdd(t, _ => []).Add(x); return Task.FromResult(x); }
    public Task<IReadOnlyList<RetentionRun>> RunsAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<RetentionRun>>(runs.GetValueOrDefault(t) ?? []);
    public Task<IReadOnlyList<ArchiveJob>> ArchivesAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<ArchiveJob>>([]); public Task<IReadOnlyList<CleanupHistory>> CleanupAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<CleanupHistory>>([]); public Task<IReadOnlyList<StorageDomainUsage>> StorageAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<StorageDomainUsage>>([]);
    public Task<CapacitySample> RecordCapacityAsync(CapacitySample x, CancellationToken ct) { lock (gate) samples.Add(x); return Task.FromResult(x); }
    public Task<IReadOnlyList<CapacitySample>> CapacityAsync(int limit, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CapacitySample>>(samples.TakeLast(limit).Reverse().ToArray()); }
    public Task<CapacityOperationalMetrics> OperationalMetricsAsync(CancellationToken ct) => Task.FromResult(new CapacityOperationalMetrics(0, 0, 0, 0, 0, holds.Values.Sum(x => x.Count)));
    public Task<TenantCapacityQuota> PutQuotaAsync(string t, string a, TenantCapacityQuotaRequest r, CancellationToken ct) { CapacityRetentionSafety.Validate(r); var old = quotas.GetValueOrDefault(t) ?? CapacityRetentionSafety.DefaultQuota(t); var x = new TenantCapacityQuota(t, old.Version + 1, r.IngestPerMinute, r.SearchPerMinute, r.ReplayPerMinute, r.ExportPerMinute, r.ForensicPerMinute, r.PlaybookPerMinute, r.UpdatePerMinute, r.MaxConcurrentForensic, r.MaxConcurrentPlaybooks, DateTimeOffset.UtcNow, a, ""); x = x with { PolicyHash = CapacityRetentionSafety.Hash(x with { PolicyHash = "", CreatedAt = default, CreatedBy = "" }) }; quotas[t] = x; return Task.FromResult(x); }
    public Task<TenantCapacityQuota> QuotaAsync(string t, CancellationToken ct) => Task.FromResult(quotas.GetValueOrDefault(t) ?? CapacityRetentionSafety.DefaultQuota(t)); public async Task<TenantQuotaDecision> ConsumeAsync(string t, string category, int units, CancellationToken ct) { var q = await QuotaAsync(t, ct); var limit = category == "search" ? q.SearchPerMinute : q.IngestPerMinute; return new(true, category, limit, units, DateTimeOffset.UtcNow.AddMinutes(1)); }
    public Task SeedFixturesAsync(string t, IReadOnlyList<RetentionFixture> x, CancellationToken ct) { lock (gate) fixtures.GetOrAdd(t, _ => []).AddRange(x); return Task.CompletedTask; }
    public Task<IReadOnlyList<RetentionFixture>> FixturesAsync(string t, CancellationToken ct) => Task.FromResult<IReadOnlyList<RetentionFixture>>(fixtures.GetValueOrDefault(t) ?? []);
}

sealed class TenantFairnessMiddleware(RequestDelegate next)
{
    public async Task InvokeAsync(HttpContext c, ICapacityRetentionRepository repository)
    {
        var principal = (PrincipalContext?)c.Items["principal"]; if (principal is null) { await next(c); return; }
        var path = c.Request.Path.Value ?? ""; var category = Category(path, c.Request.Method); if (category is null) { await next(c); return; }
        var decision = await repository.ConsumeAsync(principal.TenantId, category, 1, c.RequestAborted); c.Response.Headers["X-RateLimit-Limit"] = decision.Limit.ToString(System.Globalization.CultureInfo.InvariantCulture); c.Response.Headers["X-RateLimit-Remaining"] = Math.Max(0, decision.Limit - decision.Used).ToString(System.Globalization.CultureInfo.InvariantCulture);
        if (!decision.Allowed) { c.Response.StatusCode = 429; c.Response.Headers.RetryAfter = Math.Max(1, (int)(decision.WindowEndsAt - DateTimeOffset.UtcNow).TotalSeconds).ToString(System.Globalization.CultureInfo.InvariantCulture); await c.Response.WriteAsJsonAsync(new ApiError("TENANT_CAPACITY_QUOTA", "Tenant capacity quota is exhausted for this bounded window", 429, c.TraceIdentifier, true)); return; }
        await next(c);
    }
    static string? Category(string path, string method) { if (path.StartsWith("/agent/v1/", StringComparison.Ordinal)) return path.Contains("artifact-transfer", StringComparison.Ordinal) ? "forensic" : "ingest"; if (path.Contains("replay", StringComparison.OrdinalIgnoreCase)) return "replay"; if (path.Contains("export", StringComparison.OrdinalIgnoreCase)) return "export"; if (path.Contains("forensic", StringComparison.OrdinalIgnoreCase) || path.Contains("artifact-transfer", StringComparison.OrdinalIgnoreCase)) return "forensic"; if (path.Contains("playbook", StringComparison.OrdinalIgnoreCase) && method != "GET") return "playbook"; if (path.Contains("agent-update", StringComparison.OrdinalIgnoreCase) && method != "GET") return "update"; if (method == "GET" && path.StartsWith("/api/v1/", StringComparison.Ordinal)) return "search"; return null; }
}

static class CapacityRetentionRoutes
{
    sealed record PreviewRequest(Guid PolicyId, string Scope); sealed record ExecuteRequest(Guid PreviewId, string PreviewHash, bool DryRun); sealed record PlannerRequest(long EndpointCount, long EventsPerEndpointDay, int RetentionDays, decimal PostgreSqlBytesPerEvent, decimal OpenSearchBytesPerEvent, long ForensicBytesPerEndpointDay, decimal RedundancyFactor, decimal RequiredMarginPercent);
    static string Tenant(HttpContext c) => c.Items["tenant"]!.ToString()!; static string Actor(HttpContext c) => ((PrincipalContext)c.Items["principal"]!).Subject; static IResult Ok(HttpContext c, object x) => Results.Ok(new ApiEnvelope<object>(x, new(c.TraceIdentifier, "1.0")));
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/retention/policies", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.PoliciesAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/retention/policies", async (RetentionPolicyRequest x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.PutPolicyAsync(Tenant(c), Actor(c), null, x, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/retention/policies/{id:guid}/versions", async (Guid id, RetentionPolicyRequest x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.PutPolicyAsync(Tenant(c), Actor(c), id, x, ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/retention/holds", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.HoldsAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/retention/holds", async (RetentionHoldRequest x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.PutHoldAsync(Tenant(c), Actor(c), x, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/retention/previews", async (PreviewRequest x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.PreviewAsync(Tenant(c), x.PolicyId, x.Scope, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/retention/runs", async (ExecuteRequest x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.ExecuteAsync(Tenant(c), Actor(c), x.PreviewId, x.PreviewHash, x.DryRun, ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/retention/runs", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.RunsAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/retention/archives", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.ArchivesAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/retention/cleanup", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.CleanupAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/capacity/storage", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.StorageAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/capacity/samples", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.CapacityAsync(100, ct))).RequirePermission("platform:admin");
        app.MapPost("/internal/v1/capacity/samples", async (CapacitySample x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.RecordCapacityAsync(x, ct))).RequirePermission("system:admin");
        app.MapGet("/api/v1/capacity/quota", async (HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.QuotaAsync(Tenant(c), ct))).RequirePermission("platform:admin");
        app.MapPut("/api/v1/capacity/quota", async (TenantCapacityQuotaRequest x, HttpContext c, ICapacityRetentionRepository r, CancellationToken ct) => Ok(c, await r.PutQuotaAsync(Tenant(c), Actor(c), x, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/capacity/estimate", (PlannerRequest x, HttpContext c) => Ok(c, CapacityRetentionSafety.Estimate(new(x.EndpointCount, x.EventsPerEndpointDay, x.RetentionDays, x.PostgreSqlBytesPerEvent, x.OpenSearchBytesPerEvent, x.ForensicBytesPerEndpointDay, x.RedundancyFactor, x.RequiredMarginPercent)))).RequirePermission("platform:admin");
        app.MapPost("/internal/v1/capacity-retention/self-test", SelfTest).RequirePermission("system:admin");
    }
    static async Task<IResult> SelfTest(HttpContext c, ICapacityRetentionRepository r, IObjectStorage objects, CancellationToken ct)
    {
        var t = Tenant(c); var now = DateTimeOffset.UtcNow; var p = (await r.PoliciesAsync(t, ct)).Where(x => x.Category == "raw-telemetry").OrderByDescending(x => x.Version).FirstOrDefault() ?? await r.PutPolicyAsync(t, Actor(c), null, new("raw-telemetry", 30, 14, 100, true, true), ct); var ids = Enumerable.Range(0, 5).Select(i => CapacityRetentionSafety.StableFixtureId(t, i)).ToArray();
        await r.SeedFixturesAsync(t, [CapacityRetentionSafety.Fixture(t, "raw-telemetry", ids[0], now.AddDays(-60), 100, false), CapacityRetentionSafety.Fixture(t, "raw-telemetry", ids[1], now.AddDays(-59), 200, false), CapacityRetentionSafety.Fixture(t, "raw-telemetry", ids[2], now.AddDays(-58), 300, true), CapacityRetentionSafety.Fixture(t, "raw-telemetry", ids[3], now.AddDays(-57), 400, false), CapacityRetentionSafety.Fixture(t, "raw-telemetry", ids[4], now.AddDays(-1), 500, false)], ct); if (!(await r.HoldsAsync(t, ct)).Any(x => x.Active && x.TargetId == ids[3].ToString("D"))) await r.PutHoldAsync(t, Actor(c), new("incident", "raw-telemetry", ids[3].ToString("D"), "controlled active incident hold", now.AddDays(2)), ct);
        var preview = await r.PreviewAsync(t, p.PolicyId, "qualification-fixture", ct); var dry = await r.ExecuteAsync(t, Actor(c), preview.PreviewId, preview.PreviewHash, true, ct); var applyPreview = await r.PreviewAsync(t, p.PolicyId, "qualification-fixture", ct); var applied = await r.ExecuteAsync(t, Actor(c), applyPreview.PreviewId, applyPreview.PreviewHash, false, ct); var remaining = await r.FixturesAsync(t, ct); var planner = CapacityRetentionSafety.Estimate(new(100, 1000, 30, 512, 256, 1048576, 1, 30));
        var temporaryId = CapacityRetentionSafety.StableFixtureId(t, 9001).ToString("D"); var heldObjectId = CapacityRetentionSafety.StableFixtureId(t, 9002).ToString("D"); var bytes = Encoding.UTF8.GetBytes("sprint29-bounded-object-lifecycle\n"); var hash = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
        async Task Put(string id) { if (await objects.HeadAsync(t, id, ct) is not null) return; await using var stream = new MemoryStream(bytes, false); await objects.UploadAsync(t, id, stream, "application/octet-stream", hash, ct); }
        await Put(temporaryId); await Put(heldObjectId); if (!(await r.HoldsAsync(t, ct)).Any(x => x.Active && x.Category == "temporary-data" && x.TargetId == heldObjectId)) await r.PutHoldAsync(t, Actor(c), new("forensic", "temporary-data", heldObjectId, "controlled MinIO evidence hold", now.AddDays(2)), ct);
        var activeObjectHolds = await r.HoldsAsync(t, ct); var temporaryHeld = activeObjectHolds.Any(x => x.Active && x.Category == "temporary-data" && (x.TargetId is null || x.TargetId == temporaryId)); if (!temporaryHeld) await objects.DeleteAsync(t, temporaryId, ct); var minioTemporaryDeleted = await objects.HeadAsync(t, temporaryId, ct) is null; var minioHeldPreserved = await objects.HeadAsync(t, heldObjectId, ct) is not null;
        var pass = preview.EligibleRows == 2 && preview.HeldRows == 2 && dry.DeletedRows == 0 && applied.DeletedRows == 2 && applied.ArchivedRows == 2 && remaining.Count == 3 && remaining.Any(x => x.RecordId == ids[2]) && remaining.Any(x => x.RecordId == ids[3]) && planner.DailyEvents == 100000 && minioTemporaryDeleted && minioHeldPreserved;
        return Ok(c, new { passed = pass, policy = p, preview, dryRun = dry, applied, remaining = remaining.Count, heldPreserved = new[] { ids[2], ids[3] }.All(id => remaining.Any(x => x.RecordId == id)), minioLifecycle = new { temporaryObjectId = temporaryId, temporaryDeleted = minioTemporaryDeleted, heldObjectId, heldPreserved = minioHeldPreserved, hash, bytes = bytes.Length }, planner });
    }
    public static async Task<string> Metrics(ICapacityRetentionRepository r, CancellationToken ct) { var values = await r.CapacityAsync(1, ct); var s = values.Count == 0 ? null : values[0]; var o = await r.OperationalMetricsAsync(ct); decimal M(string n) => s?.Measurements.GetValueOrDefault(n) ?? 0; return FormattableString.Invariant($"platform_capacity_events_per_second {s?.EventsPerSecond ?? 0}\nplatform_capacity_accepted_events_total {s?.AcceptedEvents ?? 0}\nplatform_capacity_rejected_events_total {s?.RejectedEvents ?? 0}\nplatform_capacity_unexplained_loss {s?.UnexplainedLoss ?? 0}\nplatform_capacity_queue_depth {M("queuePeak")}\nplatform_capacity_queue_age_seconds {M("queueAgeSeconds")}\nplatform_capacity_projection_backlog {M("projectionBacklog")}\nplatform_capacity_db_commit_latency_ms {M("dbCommitP95Ms")}\nplatform_capacity_search_latency_ms {M("searchP95Ms")}\nplatform_capacity_detection_latency_ms {M("detectionP95Ms")}\nplatform_capacity_correlation_latency_ms {M("correlationP95Ms")}\nplatform_capacity_postgres_bytes {s?.PostgreSqlBytes ?? 0}\nplatform_capacity_opensearch_bytes {s?.OpenSearchBytes ?? 0}\nplatform_capacity_minio_bytes {s?.MinioBytes ?? 0}\nplatform_retention_deleted_total {o.RetentionDeleted}\nplatform_retention_held_total {o.RetentionHeld}\nplatform_retention_active_holds {o.ActiveHolds}\nplatform_tenant_throttled_total {o.TenantThrottled}\nplatform_temporary_data_bytes {o.TemporaryBytes}\nplatform_cleanup_failures_total {o.CleanupFailures}\n"); }
}
