using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;

static class CorrelationRoutes
{
    sealed record ToggleRequest(int Version, bool Enabled = true);
    sealed record AssignRequest(int PackVersion, Guid? EndpointId, Guid? EndpointGroupId, bool Enabled = true);
    sealed record SimulationRequest(Guid CorrelationRuleId, int Version, CorrelationObservation[] Observations);
    sealed record EvaluationRequest(CorrelationObservation Observation, bool ProductionFindings = true, DetectionExecutionMode Mode = DetectionExecutionMode.Live);
    sealed record ReplayRequest(Guid CorrelationRuleId, int Version, DateTimeOffset From, DateTimeOffset To, bool ProductionFindings = false, CorrelationObservation[]? ControlledObservations = null);
    sealed record ExportRequest(string Format, CorrelatedFindingQuery Query, int MaximumRecords = 10_000);

    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/correlation-packs", Packs).RequirePermission("correlation:read");
        app.MapPost("/api/v1/correlation-packs", CreatePack).RequirePermission("correlation:pack:manage");
        app.MapGet("/api/v1/correlation-packs/{id:guid}", Pack).RequirePermission("correlation:read");
        app.MapGet("/api/v1/correlation-packs/{id:guid}/history", PackHistory).RequirePermission("correlation:read");
        app.MapPost("/api/v1/correlation-packs/{id:guid}:enable", EnablePack).RequirePermission("correlation:activate");
        app.MapPost("/api/v1/correlation-packs/{id:guid}:disable", DisablePack).RequirePermission("correlation:deactivate");
        app.MapPost("/api/v1/correlation-packs/{id:guid}:assign", AssignPack).RequirePermission("correlation:assignment:manage");
        app.MapGet("/api/v1/correlation-rules", Rules).RequirePermission("correlation:read");
        app.MapPost("/api/v1/correlation-rules", CreateRule).RequirePermission("correlation:draft:manage");
        app.MapGet("/api/v1/correlation-rules/{id:guid}", Rule).RequirePermission("correlation:read");
        app.MapGet("/api/v1/correlation-rules/{id:guid}/versions", RuleHistory).RequirePermission("correlation:read");
        app.MapPost("/api/v1/correlation-rules/{id:guid}/versions", VersionRule).RequirePermission("correlation:draft:manage");
        app.MapPost("/api/v1/correlation-rule-versions/{id:guid}/{version:int}:validate", Validate).RequirePermission("correlation:draft:manage");
        app.MapPost("/api/v1/correlation-rule-versions/{id:guid}/{version:int}:test", Test).RequirePermission("correlation:draft:manage");
        app.MapGet("/api/v1/correlation-rule-versions/{id:guid}/{version:int}/tests", Tests).RequirePermission("correlation:read");
        app.MapPost("/api/v1/correlation-rule-versions/{id:guid}/{version:int}:activate", Activate).RequirePermission("correlation:activate");
        app.MapPost("/api/v1/correlation-rules/{id:guid}:disable", Disable).RequirePermission("correlation:deactivate");
        app.MapPost("/api/v1/correlation-rules/{id:guid}:rollback", Rollback).RequirePermission("correlation:activate");
        app.MapPost("/api/v1/correlation-rules/{id:guid}:assign", AssignRule).RequirePermission("correlation:assignment:manage");
        app.MapPost("/api/v1/correlation-simulations", Simulate).RequirePermission("correlation:simulation:run");
        app.MapPost("/internal/v1/correlation-observations:evaluate", Evaluate).RequirePermission("system:admin");
        app.MapPost("/internal/v1/correlation-production-pack:seed", Seed).RequirePermission("system:admin");
        app.MapPost("/api/v1/correlation-replays", Replay).RequirePermission("correlation:replay:run");
        app.MapGet("/api/v1/correlation-replays/{id:guid}", ReplayStatus).RequirePermission("correlation:replay:run");
        app.MapPost("/api/v1/correlation-replays/{id:guid}:cancel", CancelReplay).RequirePermission("correlation:replay:run");
        app.MapGet("/api/v1/correlation-replays/{id:guid}/results", ReplayResults).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlated-findings", Findings).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlated-findings/{id:guid}", Finding).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlated-findings/{id:guid}/evidence", Evidence).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlated-findings/{id:guid}/timeline", Timeline).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlated-findings/{id:guid}/child-findings", Children).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlated-findings/{id:guid}/entity-relationships", Relationships).RequirePermission("correlated-finding:read");
        app.MapGet("/api/v1/correlation-health", Health).RequirePermission("correlation:health:read");
        app.MapGet("/api/v1/mitre-coverage", Coverage).RequirePermission("correlation:read");
        app.MapGet("/api/v1/correlation-exclusions", Exclusions).RequirePermission("correlation:exclusion:manage");
        app.MapPost("/api/v1/correlation-exclusions", CreateExclusion).RequirePermission("correlation:exclusion:manage");
        app.MapPost("/api/v1/correlated-finding-exports", Export).RequirePermission("correlated-finding:export");
        app.MapGet("/api/v1/correlated-finding-exports/{id:guid}/manifest", ExportManifest).RequirePermission("correlated-finding:export");
        app.MapGet("/api/v1/correlated-finding-exports/{id:guid}/content", ExportContent).RequirePermission("correlated-finding:export");
        app.MapPost("/api/v1/correlated-finding-exports/{id:guid}/download-url", ExportUrl).RequirePermission("correlated-finding:export");
        app.MapGet("/api/v1/correlated-finding-exports/{id:guid}/download", ExportDownload);
    }

    static string Tenant(HttpContext c) => c.Items["tenant"]!.ToString()!;
    static string Actor(HttpContext c) => c.Items.TryGetValue("subject", out var x) ? x?.ToString() ?? "unknown" : "unknown";
    static IResult Ok<T>(HttpContext c, T value) => Results.Ok(new ApiEnvelope<T>(value, new(c.TraceIdentifier, "1.0")));
    static IResult Problem(HttpContext c, string code, string message, int status = 400) => Results.Json(new ApiError(code, message, status, c.TraceIdentifier), statusCode: status);
    static async Task<IResult> Packs(HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.ListPacksAsync(Tenant(c), ct));
    static async Task<IResult> Pack(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetPackAsync(Tenant(c), id, null, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> PackHistory(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.PackHistoryAsync(Tenant(c), id, ct));
    static async Task<IResult> CreatePack(CorrelationPack input, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var x = await r.PutPackAsync(Tenant(c), Actor(c), input, ct); return Results.Created($"/api/v1/correlation-packs/{x.PackId}", new ApiEnvelope<CorrelationPack>(x, new(c.TraceIdentifier, "1.0"))); }
    static async Task<IResult> EnablePack(Guid id, ToggleRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.SetPackEnabledAsync(Tenant(c), Actor(c), id, input.Version, true, ct));
    static async Task<IResult> DisablePack(Guid id, ToggleRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.SetPackEnabledAsync(Tenant(c), Actor(c), id, input.Version, false, ct));
    static async Task<IResult> AssignPack(Guid id, AssignRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.AssignPackAsync(Tenant(c), Actor(c), new(Guid.Empty, Tenant(c), id, input.PackVersion, input.EndpointId, input.EndpointGroupId, input.Enabled, default, ""), ct));
    static async Task<IResult> Rules(HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.ListRulesAsync(Tenant(c), Guid.TryParse(c.Request.Query["packId"], out var id) ? id : null, ct));
    static async Task<IResult> Rule(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetRuleAsync(Tenant(c), id, null, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> RuleHistory(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.RuleHistoryAsync(Tenant(c), id, ct));
    static async Task<IResult> CreateRule(CorrelationRule input, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var x = await r.PutRuleAsync(Tenant(c), Actor(c), input, false, ct); return Results.Created($"/api/v1/correlation-rules/{x.CorrelationRuleId}", new ApiEnvelope<CorrelationRule>(x, new(c.TraceIdentifier, "1.0"))); }
    static async Task<IResult> VersionRule(Guid id, CorrelationRule input, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.PutRuleAsync(Tenant(c), Actor(c), input with { CorrelationRuleId = id }, true, ct));
    static async Task<IResult> Validate(Guid id, int version, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var rule = await r.GetRuleAsync(Tenant(c), id, version, ct); if (rule is null) return Results.NotFound(); var errors = CorrelationDsl.Validate(rule with { Status = CorrelationStatus.Testing, Enabled = false }); var value = await r.ValidateRuleAsync(Tenant(c), id, version, errors, ct); return errors.Count == 0 ? Ok(c, new { valid = true, rule = value, errors }) : Results.ValidationProblem(errors.ToDictionary()); }
    static async Task<IResult> Test(Guid id, int version, CorrelationFixture[] fixtures, HttpContext c, ICorrelationRepository r, CancellationToken ct)
    {
        if (fixtures.Length is < 1 or > 64 || fixtures.Sum(x => x.Observations.Length) > 10_000) return Problem(c, "CORRELATION_TEST_BOUNDS", "Tests are limited to 64 fixtures and 10,000 observations."); var rule = await r.GetRuleAsync(Tenant(c), id, version, ct); if (rule is null) return Results.NotFound(); var results = fixtures.Select(x => RunFixture(rule, x)).ToArray(); await r.RecordTestsAsync(Tenant(c), id, version, results, ct); return Ok(c, new { passed = results.All(x => x.Passed), results });
    }
    internal static CorrelationTestResult RunFixture(CorrelationRule rule, CorrelationFixture fixture)
    {
        static Guid[] Evaluate(CorrelationRule rule, CorrelationObservation[] observations, string tenant) { var state = new List<CorrelationObservation>(); var ids = new HashSet<Guid>(); foreach (var observation in observations.OrderBy(x => x.EventTime).ThenBy(x => x.ObservationId)) { if (observation.TenantId != tenant) continue; state.Add(observation); if (CorrelationDsl.Complete(rule, state, DetectionExecutionMode.Simulation) is { } finding) ids.Add(finding.CorrelatedFindingId); } return ids.Order().ToArray(); }
        var first = Evaluate(rule, fixture.Observations, rule.TenantId); var second = Evaluate(rule, fixture.Observations.Reverse().Reverse().ToArray(), rule.TenantId); var foreign = Evaluate(rule with { TenantId = Guid.NewGuid().ToString("D") }, fixture.Observations, Guid.NewGuid().ToString("D")); var failures = new List<string>(); if (first.Length != fixture.ExpectedFindings) failures.Add($"expected-{fixture.ExpectedFindings}-actual-{first.Length}"); if (!first.SequenceEqual(second)) failures.Add("nondeterministic"); if (foreign.Length != 0) failures.Add("tenant-isolation"); var cost = fixture.Observations.Length <= 10_000 && rule.Steps.Length <= CorrelationDsl.MaximumSteps; if (!cost) failures.Add("resource-cost"); return new(fixture.Name, fixture.Kind, failures.Count == 0, fixture.ExpectedFindings, first.Length, first.SequenceEqual(second), foreign.Length == 0, cost, DateTimeOffset.UtcNow, failures.ToArray());
    }
    static async Task<IResult> Tests(Guid id, int version, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.ListTestsAsync(Tenant(c), id, version, ct));
    static async Task<IResult> Activate(Guid id, int version, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.SetRuleEnabledAsync(Tenant(c), Actor(c), id, version, true, ct));
    static async Task<IResult> Disable(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var rule = await r.GetRuleAsync(Tenant(c), id, null, ct); return rule is null ? Results.NotFound() : Ok(c, await r.SetRuleEnabledAsync(Tenant(c), Actor(c), id, rule.Version, false, ct)); }
    static async Task<IResult> Rollback(Guid id, ToggleRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.SetRuleEnabledAsync(Tenant(c), Actor(c), id, input.Version, true, ct));
    static async Task<IResult> AssignRule(Guid id, AssignRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var rule = await r.GetRuleAsync(Tenant(c), id, input.PackVersion, ct) ?? await r.GetRuleAsync(Tenant(c), id, null, ct); return rule is null ? Results.NotFound() : Ok(c, await r.AssignPackAsync(Tenant(c), Actor(c), new(Guid.Empty, Tenant(c), rule.PackId, rule.PackVersion, input.EndpointId, input.EndpointGroupId, input.Enabled, default, ""), ct)); }
    static async Task<IResult> Simulate(SimulationRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) { if (input.Observations.Length is < 1 or > 10_000) return Problem(c, "CORRELATION_SIMULATION_BOUNDS", "Simulation requires 1-10,000 observations."); var run = Guid.NewGuid(); var output = new List<CorrelationEvaluationResult>(); foreach (var x in input.Observations.OrderBy(x => x.EventTime).ThenBy(x => x.ObservationId)) output.Add(await r.EvaluateAsync(Tenant(c), x, DetectionExecutionMode.Simulation, input.CorrelationRuleId, input.Version, run, false, ct)); return Ok(c, new { runId = run, mode = "Simulation", productionFindings = false, evaluated = output.Count, findings = output.Where(x => x.Finding is not null).Select(x => x.Finding).DistinctBy(x => x!.CorrelatedFindingId) }); }
    static async Task<IResult> Evaluate(EvaluationRequest input, HttpContext c, ICorrelationRepository r, IAlertIncidentRepository alerts, CancellationToken ct) { if (input.Mode is not (DetectionExecutionMode.Live or DetectionExecutionMode.DryRun)) return Problem(c, "CORRELATION_MODE_INVALID", "Only Live and DryRun are accepted."); var production = input.Mode == DetectionExecutionMode.Live && input.ProductionFindings; var result = await r.EvaluateAsync(Tenant(c), input.Observation, input.Mode, null, null, null, production, ct); if (result.Finding is { } finding && production) await alerts.CreateAlertAsync(Tenant(c), Actor(c), AlertIncidentSafety.FromCorrelation(finding), ct); return Ok(c, result); }
    static async Task<IResult> Seed(HttpContext c, ICorrelationRepository r, CancellationToken ct)
    {
        var tenant = Tenant(c); var production = CorrelationProductionPack.Create(tenant); var pack = await r.GetPackAsync(tenant, production.Pack.PackId, production.Pack.Version, ct) ?? await r.PutPackAsync(tenant, Actor(c), production.Pack, ct); var output = new List<object>(); foreach (var item in production.Rules) { var rule = await r.GetRuleAsync(tenant, item.Rule.CorrelationRuleId, null, ct); if (rule is null) { await r.PutExclusionAsync(tenant, Actor(c), item.Exclusion, ct); rule = await r.PutRuleAsync(tenant, Actor(c), item.Rule, false, ct); } else if (rule.PackVersion < item.Rule.PackVersion) { rule = await r.PutRuleAsync(tenant, Actor(c), item.Rule with { CorrelationRuleId = rule.CorrelationRuleId }, true, ct); } var errors = CorrelationDsl.Validate(rule); rule = await r.ValidateRuleAsync(tenant, rule.CorrelationRuleId, rule.Version, errors, ct); var results = item.Fixtures.Select(x => RunFixture(rule, x)).ToArray(); await r.RecordTestsAsync(tenant, rule.CorrelationRuleId, rule.Version, results, ct); rule = await r.SetRuleEnabledAsync(tenant, Actor(c), rule.CorrelationRuleId, rule.Version, true, ct); output.Add(new { rule.CorrelationRuleId, rule.Name, rule.Version, rule.Status, tests = results.Select(x => new { x.Kind, x.Passed }) }); }
        await r.SetPackEnabledAsync(tenant, Actor(c), production.Pack.PackId, pack.Version, true, ct); await r.AssignPackAsync(tenant, Actor(c), new(Guid.Empty, tenant, production.Pack.PackId, pack.Version, null, null, true, default, ""), ct); return Ok(c, new { packId = production.Pack.PackId, packVersion = pack.Version, rules = output, production = true });
    }
    static async Task<IResult> Replay(ReplayRequest input, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var rule = await r.GetRuleAsync(Tenant(c), input.CorrelationRuleId, input.Version, ct); if (rule is null) return Results.NotFound(); if (input.To <= input.From || input.To - input.From > TimeSpan.FromDays(7) || input.ControlledObservations?.Length > 10_000) return Problem(c, "CORRELATION_REPLAY_BOUNDS", "Replay is bounded to seven days and 10,000 observations."); var observations = input.ControlledObservations is { Length: > 0 } controlled ? controlled.Where(x => x.EventTime >= input.From && x.EventTime <= input.To).OrderBy(x => x.EventTime).ThenBy(x => x.ObservationId).ToArray() : (await r.LoadObservationsAsync(Tenant(c), input.From, input.To, 10_000, ct)).ToArray(); var run = new CorrelationRun(Guid.NewGuid(), Tenant(c), rule.CorrelationRuleId, rule.Version, rule.PackId, rule.PackVersion, DetectionExecutionMode.HistoricalReplay, input.From, input.To, "running", observations.Length, 0, 0, input.ProductionFindings, DateTimeOffset.UtcNow); await r.PutRunAsync(Tenant(c), run, rule, ct); var ids = new HashSet<Guid>(); foreach (var x in observations) if ((await r.EvaluateAsync(Tenant(c), x, run.Mode, rule.CorrelationRuleId, rule.Version, run.Id, input.ProductionFindings, ct)).Finding is { } finding) ids.Add(finding.CorrelatedFindingId); var done = await r.CompleteRunAsync(Tenant(c), run.Id, observations.Length, ids.Count, "completed", ct); return Results.Accepted($"/api/v1/correlation-replays/{run.Id}", new ApiEnvelope<object>(new { run = done, authoritativeSource = input.ControlledObservations is not { Length: > 0 }, resultIds = ids.Order().ToArray() }, new(c.TraceIdentifier, "1.0"))); }
    static async Task<IResult> ReplayStatus(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetRunAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> CancelReplay(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.CancelRunAsync(Tenant(c), id, ct));
    static async Task<IResult> ReplayResults(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) { var run = await r.GetRunAsync(Tenant(c), id, ct); return run is null ? Results.NotFound() : Ok(c, new { run, findings = await r.SearchFindingsAsync(Tenant(c), new(RuleId: run.RuleId, Mode: DetectionExecutionMode.HistoricalReplay), ct) }); }
    static CorrelatedFindingQuery Query(HttpContext c) { var q = c.Request.Query; return new(Guid.TryParse(q["ruleId"], out var r) ? r : null, Guid.TryParse(q["packId"], out var p) ? p : null, Guid.TryParse(q["endpointId"], out var e) ? e : null, int.TryParse(q["minimumSeverity"], out var s) ? s : null, bool.TryParse(q["suppressed"], out var z) ? z : null, Enum.TryParse<DetectionExecutionMode>(q["mode"], true, out var m) ? m : null, DateTimeOffset.TryParse(q["from"], out var f) ? f : null, DateTimeOffset.TryParse(q["to"], out var t) ? t : null, int.TryParse(q["pageSize"], out var n) ? n : 100, q["cursor"]); }
    static async Task<IResult> Findings(HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.SearchFindingsAsync(Tenant(c), Query(c), ct));
    static async Task<IResult> Finding(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetFindingAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> Evidence(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetFindingAsync(Tenant(c), id, ct) is { } x ? Ok(c, new { x.MatchedSteps, x.EvidenceEventIds, x.ChildFindingIds, x.MatchedValues, x.MissingRequiredTelemetry, x.TelemetryQuality }) : Results.NotFound();
    static async Task<IResult> Timeline(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetFindingAsync(Tenant(c), id, ct) is { } x ? Ok(c, x.Timeline) : Results.NotFound();
    static async Task<IResult> Children(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetFindingAsync(Tenant(c), id, ct) is { } x ? Ok(c, x.ChildFindingIds) : Results.NotFound();
    static async Task<IResult> Relationships(Guid id, HttpContext c, ICorrelationRepository r, CancellationToken ct) => await r.GetFindingAsync(Tenant(c), id, ct) is { } x ? Ok(c, x.EntityRelationships) : Results.NotFound();
    static async Task<IResult> Health(HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.HealthAsync(Tenant(c), ct));
    static async Task<IResult> Coverage(HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.CoverageAsync(Tenant(c), ct));
    static async Task<IResult> Exclusions(HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.ListExclusionsAsync(Tenant(c), ct));
    static async Task<IResult> CreateExclusion(CorrelationExclusion input, HttpContext c, ICorrelationRepository r, CancellationToken ct) => Ok(c, await r.PutExclusionAsync(Tenant(c), Actor(c), input, ct));
    static async Task<IResult> Export(ExportRequest input, HttpContext c, ICorrelationRepository r, IObjectStorage storage, CancellationToken ct) { var format = input.Format.ToLowerInvariant(); if (format is not ("jsonl" or "csv") || input.MaximumRecords is < 1 or > 10_000) return Problem(c, "CORRELATION_EXPORT_FORMAT", "Format or record bound is invalid."); var tenant = Tenant(c); var page = await r.SearchFindingsAsync(tenant, input.Query with { Cursor = null, PageSize = input.MaximumRecords }, ct); var values = page.Items.Take(input.MaximumRecords).ToArray(); var content = format == "jsonl" ? Encoding.UTF8.GetBytes(string.Join('\n', values.Select(x => JsonSerializer.Serialize(x))) + '\n') : CorrelationCsv(values); var hash = Convert.ToHexString(SHA256.HashData(content)).ToLowerInvariant(); var id = Guid.NewGuid(); var manifest = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "correlated-finding-export-manifest.v1", exportId = id, tenantBinding = tenant, format, recordCount = values.Length, query = input.Query, sha256 = hash, includes = new[] { "rule/version", "pack/version", "child findings", "raw evidence IDs", "timeline", "matched steps", "MITRE mapping", "confidence", "telemetry quality", "provenance" }, createdAt = DateTimeOffset.UtcNow }); await Put(storage, tenant, id.ToString("D"), content, format == "csv" ? "text/csv" : "application/x-ndjson", ct); await Put(storage, tenant, ManifestId(id).ToString("D"), manifest, "application/json", ct); return Results.Created($"/api/v1/correlated-finding-exports/{id:D}", new ApiEnvelope<object>(new { id, state = "Completed", format, recordCount = values.Length, sha256 = hash }, new(c.TraceIdentifier, "1.0"))); }
    static async Task<IResult> ExportManifest(Guid id, HttpContext c, IObjectStorage storage, CancellationToken ct) => await storage.HeadAsync(Tenant(c), ManifestId(id).ToString("D"), ct) is null ? Results.NotFound() : Results.Stream(await storage.DownloadAsync(Tenant(c), ManifestId(id).ToString("D"), ct), "application/json");
    static async Task<IResult> ExportContent(Guid id, HttpContext c, IObjectStorage storage, CancellationToken ct) => await storage.HeadAsync(Tenant(c), id.ToString("D"), ct) is { } meta ? Results.Stream(await storage.DownloadAsync(Tenant(c), id.ToString("D"), ct), meta.MediaType) : Results.NotFound();
    static async Task<IResult> ExportUrl(Guid id, HttpContext c, IObjectStorage storage, PlatformOptions options, CancellationToken ct) { if (await storage.HeadAsync(Tenant(c), id.ToString("D"), ct) is null) return Results.NotFound(); var expires = DateTimeOffset.UtcNow.AddMinutes(5); var token = FileExportDownloadToken.Create(Tenant(c), id, expires, options.JwtSigningKey); return Ok(c, new { url = $"{c.Request.Scheme}://{c.Request.Host}/api/v1/correlated-finding-exports/{id:D}/download?token={Uri.EscapeDataString(token)}", expiresAt = expires }); }
    static async Task<IResult> ExportDownload(Guid id, string token, IObjectStorage storage, PlatformOptions options, CancellationToken ct) { if (!FileExportDownloadToken.TryValidate(token, options.JwtSigningKey, out var tenant, out var export) || export != id || await storage.HeadAsync(tenant, id.ToString("D"), ct) is not { } meta) return Results.NotFound(); return Results.Stream(await storage.DownloadAsync(tenant, id.ToString("D"), ct), meta.MediaType); }
    static async Task Put(IObjectStorage storage, string tenant, string id, byte[] bytes, string media, CancellationToken ct) { await using var stream = new MemoryStream(bytes); await storage.UploadAsync(tenant, id, stream, media, Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), ct); }
    static Guid ManifestId(Guid id) => new(SHA256.HashData(Encoding.UTF8.GetBytes($"correlation-export-manifest:{id:D}")).AsSpan(0, 16));
    static byte[] CorrelationCsv(IEnumerable<CorrelatedFinding> values) { static string C(string? value) { var x = value ?? ""; if (x.Length > 0 && "=+-@\t\r".Contains(x[0])) x = "'" + x; return '"' + x.Replace("\"", "\"\"") + '"'; } var b = new StringBuilder("correlatedFindingId,correlationRuleId,ruleVersion,packId,packVersion,ruleName,severity,confidence,firstSeen,lastSeen,childFindings,evidenceEventIds,timeline,matchedSteps,mitre,quality,engineVersion,mode\n"); foreach (var x in values) b.AppendLine(string.Join(',', C(x.CorrelatedFindingId.ToString()), C(x.CorrelationRuleId.ToString()), C(x.CorrelationRuleVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)), C(x.PackId.ToString()), C(x.PackVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)), C(x.RuleName), C(x.Severity.ToString(System.Globalization.CultureInfo.InvariantCulture)), C(x.Confidence.ToString(System.Globalization.CultureInfo.InvariantCulture)), C(x.FirstSeen.ToString("O")), C(x.LastSeen.ToString("O")), C(string.Join(';', x.ChildFindingIds)), C(string.Join(';', x.EvidenceEventIds)), C(JsonSerializer.Serialize(x.Timeline)), C(JsonSerializer.Serialize(x.MatchedSteps)), C($"{x.MitreTactic}/{x.MitreTechnique}/{x.MitreSubTechnique}"), C(string.Join(';', x.TelemetryQuality)), C(x.EngineVersion), C(x.ExecutionMode.ToString()))); return Encoding.UTF8.GetBytes(b.ToString()); }
}
