using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;
sealed class DnsExportWorker(IDnsExportRepository exports, IDnsTelemetryRepository dns, IObjectStorage objects, ILogger<DnsExportWorker> logger) : BackgroundService
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    protected override async Task ExecuteAsync(CancellationToken ct) { while (!ct.IsCancellationRequested) { foreach (var x in await exports.ExpireDueAsync(ct)) foreach (var id in new[] { x.OutputObjectId, x.ManifestObjectId, x.MetadataObjectId }) try { await objects.DeleteAsync(x.TenantId, id.ToString("D"), ct); } catch (Exception e) when (e is IOException or HttpRequestException) { logger.LogWarning(e, "Expired DNS export cleanup failed for {ExportId}", x.Id); } var j = await exports.ClaimAsync(ct); if (j is null) { await Task.Delay(250, ct); continue; } try { var page = await dns.SearchAsync(j.TenantId, j.Query with { Cursor = null, PageSize = Math.Clamp(j.MaximumRecords, 1, 10000) }, ct); var selected = page.Items.Take(j.MaximumRecords).ToArray(); var output = j.Format == "csv" ? Csv(selected, j.Fields) : Jsonl(selected, j.Fields); var hash = Hash(output); var completed = DateTimeOffset.UtcNow; var fields = EffectiveFields(j.Fields); var manifest = new DnsExportManifest("dns-export-manifest.v1", j.Id, j.TenantId, j.Format, selected.Length, j.Query, fields, j.CreatedAt, completed, output.LongLength, hash, "0.6.0", "dns-event.v1", j.OutputObjectId, j.MetadataObjectId); var manifestBytes = JsonSerializer.SerializeToUtf8Bytes(manifest, Json); var metadata = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "dns-export-metadata.v1", exportId = j.Id, state = "completed", j.Format, recordCount = selected.Length, query = j.Query, fields, j.CreatedAt, completedAt = completed, j.ExpiresAt, j.OutputObjectId, j.ManifestObjectId, outputSha256 = hash, noPacketPayload = true }, Json); await Upload(j, j.OutputObjectId, output, j.Format == "csv" ? "text/csv" : "application/x-ndjson", ct); await Upload(j, j.ManifestObjectId, manifestBytes, "application/json", ct); await Upload(j, j.MetadataObjectId, metadata, "application/json", ct); await exports.CompleteAsync(j.Id, selected.Length, output.LongLength, hash, completed, ct); } catch (Exception e) when (e is not OperationCanceledException) { logger.LogError(e, "DNS export {ExportId} failed", j.Id); await exports.FailAsync(j.Id, "EXPORT_FAILED", e.GetType().Name, ct); } } }
    async Task Upload(DnsExportJob j, Guid id, byte[] bytes, string media, CancellationToken ct) { await using var s = new MemoryStream(bytes, false); await objects.UploadAsync(j.TenantId, id.ToString("D"), s, media, Hash(bytes), ct); }
    static byte[] Jsonl(IReadOnlyList<DnsObservation> v, string[] f) { var b = new StringBuilder(); foreach (var x in v) b.AppendLine(JsonSerializer.Serialize(Project(x, f), Json)); return Encoding.UTF8.GetBytes(b.ToString()); }
    static byte[] Csv(IReadOnlyList<DnsObservation> v, string[] r) { var f = EffectiveFields(r); var b = new StringBuilder(); b.AppendLine(string.Join(',', f.Select(Cell))); foreach (var x in v) { var p = Project(x, f); b.AppendLine(string.Join(',', f.Select(y => Cell(p[y]?.ToString())))); } return Encoding.UTF8.GetBytes(b.ToString()); }
    static Dictionary<string, object?> Project(DnsObservation x, string[] r) { var a = new Dictionary<string, object?>(StringComparer.Ordinal) { { "schemaVersion", "dns-export.v1" }, { "eventId", x.EventId }, { "endpointId", x.EndpointId }, { "observedAt", x.ObservedAt }, { "state", x.State.ToString() }, { "originalQueryName", x.OriginalQueryName }, { "canonicalQueryName", x.CanonicalQueryName }, { "recordType", x.RecordType }, { "responseCode", x.ResponseCode }, { "resolver", x.ResolverAddress }, { "answers", string.Join(';', x.Answers.Select(y => $"{y.RecordType}:{y.Value}:{y.Ttl}")) }, { "processEntityId", x.Process?.ProcessEntityId }, { "user", x.User }, { "collector", x.CollectorSource }, { "nativeProvider", x.NativeProvider }, { "dataQuality", string.Join(';', x.DataQualityFlags) } }; return EffectiveFields(r).ToDictionary(y => y, y => a[y], StringComparer.Ordinal); }
    internal static string[] EffectiveFields(string[] r) { string[] a = ["schemaVersion", "eventId", "endpointId", "observedAt", "state", "originalQueryName", "canonicalQueryName", "recordType", "responseCode", "resolver", "answers", "processEntityId", "user", "collector", "nativeProvider", "dataQuality"]; return r.Length == 0 ? a : r.Where(a.Contains).Distinct().ToArray(); }
    static string Cell(string? value) { var s = value ?? ""; if (s.Length > 0 && "=+-@\t\r".Contains(s[0])) s = "'" + s; return '"' + s.Replace("\"", "\"\"") + '"'; }
    static string Hash(byte[] b) => Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
}
