using System.IO.Compression;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;

static class DnsRoutes
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public static void Map(WebApplication app)
    {
        app.MapPost("/agent/v1/dns-event-batches", IngestAsync).RequirePermission("agent:heartbeat");
        app.MapGet("/agent/v1/dns-policy", EffectiveForAgentAsync).RequirePermission("agent:heartbeat");
        app.MapPost("/agent/v1/dns-policy:acknowledge", AcknowledgeForAgentAsync).RequirePermission("agent:heartbeat");
        app.MapGet("/api/v1/dns-events", SearchAsync).RequirePermission("dns:read");
        app.MapGet("/api/v1/dns-events/{eventId:guid}", EventAsync).RequirePermission("dns:details:read");
        app.MapGet("/api/v1/endpoints/{endpointId:guid}/dns-transactions/{transactionId}/history", HistoryAsync).RequirePermission("dns:read");
        app.MapGet("/api/v1/endpoints/{endpointId:guid}/processes/{processId}/dns", ProcessAsync).RequirePermission("dns:relationship:read");
        app.MapGet("/api/v1/endpoints/{endpointId:guid}/dns-timeline", TimelineAsync).RequirePermission("dns:read");
        app.MapGet("/api/v1/endpoints/{endpointId:guid}/dns-telemetry-health", HealthAsync).RequirePermission("dns:health:read");
        app.MapGet("/api/v1/dns-events:export", ExportAsync).RequirePermission("dns:export");
        app.MapPost("/api/v1/dns-exports", CreateExportAsync).RequirePermission("dns:export");
        app.MapGet("/api/v1/dns-exports/{id:guid}", ExportStatusAsync).RequirePermission("dns:export");
        app.MapGet("/api/v1/dns-exports/{id:guid}/manifest", ExportManifestAsync).RequirePermission("dns:export");
        app.MapGet("/api/v1/dns-exports/{id:guid}/metadata", ExportMetadataAsync).RequirePermission("dns:export");
        app.MapGet("/api/v1/dns-exports/{id:guid}/content", ExportContentAsync).RequirePermission("dns:export");
        app.MapPost("/api/v1/dns-exports/{id:guid}/download-url", ExportDownloadUrlAsync).RequirePermission("dns:export");
        app.MapGet("/api/v1/dns-exports/{id:guid}/download", ExportSignedDownloadAsync);
        app.MapGet("/api/v1/dns-telemetry/policies", ListPoliciesAsync).RequirePermission("dns:policy:manage");
        app.MapPost("/api/v1/dns-telemetry/policies", CreatePolicyAsync).RequirePermission("dns:policy:manage");
        app.MapGet("/api/v1/endpoints/{endpointId:guid}/dns-policy", EffectivePolicyAsync).RequirePermission("dns:policy:manage");
        app.MapPost("/api/v1/dns-telemetry/policies/{id:guid}:assign", AssignPolicyAsync).RequirePermission("dns:policy:manage");
        app.MapGet("/api/v1/dns-telemetry/policies/{id:guid}/exclusions", ListExclusionsAsync).RequirePermission("dns:exclusion:manage");
        app.MapPost("/api/v1/dns-telemetry/policies/{id:guid}/exclusions", AddExclusionAsync).RequirePermission("dns:exclusion:manage");
        app.MapDelete("/api/v1/dns-telemetry/policies/{id:guid}/exclusions/{ruleId:guid}", DeleteExclusionAsync).RequirePermission("dns:exclusion:manage");
    }
    static async Task<IResult> IngestAsync(HttpContext c, IDnsTelemetryRepository repository, PlatformMetrics metrics, CancellationToken ct)
    {
        if (!c.Request.IsHttps || c.Request.ContentLength is > 1048576) return Problem(c, "DNS_BATCH_SIZE", "Compressed DNS batch exceeds policy.", 413);
        if (c.Items["principal"] is not PrincipalContext { Type: "agent" } principal) return Results.Unauthorized();
        if (!long.TryParse(c.Request.Headers["X-Uncompressed-Length"], out var expected) || expected is < 1 or > 4194304 || !string.Equals(c.Request.Headers.ContentEncoding, "gzip", StringComparison.OrdinalIgnoreCase)) return Problem(c, "DNS_COMPRESSION_INVALID", "A bounded gzip DNS batch is required.", 400);
        try
        {
            await using var gzip = new GZipStream(c.Request.Body, CompressionMode.Decompress, false); await using var bounded = new MemoryStream(); var buffer = new byte[81920]; long total = 0; int read; while ((read = await gzip.ReadAsync(buffer, ct)) > 0) { total += read; if (total > expected || total > 4194304) return Problem(c, "DNS_DECOMPRESSION_LIMIT", "DNS batch exceeded its declared limit.", 413); await bounded.WriteAsync(buffer.AsMemory(0, read), ct); }
            if (total != expected) return Problem(c, "DNS_LENGTH_MISMATCH", "DNS batch length did not match its declaration.", 400);
            var batch = JsonSerializer.Deserialize<DnsEventBatch>(bounded.ToArray(), Json); if (batch is null || batch.Events.Count is < 1 or > 1000 || batch.FirstSequence != batch.Events.Min(x => x.Sequence) || batch.LastSequence != batch.Events.Max(x => x.Sequence)) return Problem(c, "DNS_BATCH_INVALID", "DNS batch contract is invalid.", 400);
            var ids = principal.Subject.Split(':'); if (ids.Length != 2 || !Guid.TryParse(ids[0], out var endpoint) || !Guid.TryParse(ids[1], out var agent) || batch.EndpointId != endpoint || batch.AgentId != agent) return Results.Unauthorized();
            var actual = Convert.ToHexString(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(batch.Events, Json))).ToLowerInvariant(); if (batch.ContentSha256.Length != 64 || !CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(actual), Encoding.ASCII.GetBytes(batch.ContentSha256.ToLowerInvariant()))) return Problem(c, "DNS_INTEGRITY_INVALID", "DNS event integrity validation failed.", 400);
            var h = Health(c, endpoint, batch); var started = System.Diagnostics.Stopwatch.GetTimestamp(); var result = await repository.IngestAsync(principal.TenantId, batch, h, ct); metrics.DnsIngest(result, System.Diagnostics.Stopwatch.GetElapsedTime(started)); return Results.Ok(result.Acknowledgement);
        }
        catch (Exception e) when (e is InvalidDataException or JsonException) { return Problem(c, "DNS_BATCH_INVALID", "DNS batch could not be parsed.", 400); }
    }
    static DnsTelemetryHealth Health(HttpContext c, Guid endpoint, DnsEventBatch b)
    { long H(string n) => long.TryParse(c.Request.Headers[n], out var v) ? Math.Max(0, v) : 0; var e = b.Events; return new(endpoint, true, e[0].CollectorSource, e[0].CollectorVersion, e[0].NativeProvider, e.Max(x => x.ObservedAt), null, H("X-Native-Source-Events"), e.LongCount(x => x.Kind == DnsEventKind.QueryObserved), e.LongCount(x => x.Kind is DnsEventKind.ResponseObserved or DnsEventKind.TransactionObserved), e.LongCount(x => x.Kind == DnsEventKind.QueryFailed), H("X-Normalized-Events"), H("X-Unanswered-Queries"), H("X-Unpaired-Responses"), H("X-Correlation-Failures"), H("X-Attribution-Failures"), H("X-Source-Losses"), H("X-Sequence-Gaps"), H("X-Queue-Depth"), H("X-Queue-Oldest-Age"), H("X-Dropped-Events"), H("X-Excluded-Events"), H("X-Batches"), H("X-Duplicate-Events"), H("X-Rejected-Events"), "accepted", c.Request.Headers["X-Policy-Version"].FirstOrDefault() ?? "dns-policy.v1", int.TryParse(c.Request.Headers["X-Applied-Policy-Version"], out var v) ? v : null, false, DateTimeOffset.UtcNow, b.LastSequence, (c.Request.Headers["X-Known-Limitations"].FirstOrDefault() ?? "").Split(';', StringSplitOptions.RemoveEmptyEntries)); }
    static async Task<IResult> SearchAsync(HttpContext c, IDnsProjection p, PlatformMetrics metrics, CancellationToken ct) { var started = System.Diagnostics.Stopwatch.GetTimestamp(); var value = await p.SearchAsync(Tenant(c), Query(c.Request), ct); metrics.DnsSearch(System.Diagnostics.Stopwatch.GetElapsedTime(started)); return Results.Ok(Envelope(c, value)); }
    static async Task<IResult> EventAsync(Guid eventId, HttpContext c, IDnsTelemetryRepository r, CancellationToken ct) => await r.GetEventAsync(Tenant(c), eventId, ct) is { } v ? Results.Ok(Envelope(c, v)) : Results.NotFound();
    static async Task<IResult> HistoryAsync(Guid endpointId, string transactionId, HttpContext c, IDnsTelemetryRepository r, CancellationToken ct) { var x = Range(c.Request); return Results.Ok(Envelope(c, await r.HistoryAsync(Tenant(c), endpointId, transactionId, x.From, x.To, Limit(c.Request), ct))); }
    static async Task<IResult> ProcessAsync(Guid endpointId, string processId, HttpContext c, IDnsTelemetryRepository r, CancellationToken ct) { var x = Range(c.Request); return Results.Ok(Envelope(c, await r.ProcessDnsAsync(Tenant(c), endpointId, processId, x.From, x.To, Limit(c.Request), ct))); }
    static async Task<IResult> TimelineAsync(Guid endpointId, HttpContext c, IDnsProjection p, PlatformMetrics metrics, CancellationToken ct) { var started = System.Diagnostics.Stopwatch.GetTimestamp(); var value = await p.SearchAsync(Tenant(c), Query(c.Request) with { EndpointId = endpointId }, ct); metrics.DnsSearch(System.Diagnostics.Stopwatch.GetElapsedTime(started)); return Results.Ok(Envelope(c, value)); }
    static async Task<IResult> HealthAsync(Guid endpointId, HttpContext c, IDnsTelemetryRepository r, CancellationToken ct) => await r.HealthAsync(Tenant(c), endpointId, ct) is { } v ? Results.Ok(Envelope(c, v)) : Results.NotFound();
    static async Task<IResult> ExportAsync(HttpContext c, IDnsProjection p, CancellationToken ct)
    { var q = Query(c.Request) with { PageSize = Math.Min(10000, Math.Max(1, Limit(c.Request))) }; var page = await p.SearchAsync(Tenant(c), q, ct); var csv = string.Equals(c.Request.Query["format"], "csv", StringComparison.OrdinalIgnoreCase); byte[] bytes; if (csv) { static string Safe(string? x) { var v = (x ?? "").Replace("\"", "\"\""); if (v.Length > 0 && v[0] is '=' or '+' or '-' or '@') v = "'" + v; return $"\"{v}\""; } var rows = new[] { "event_id,observed_at,endpoint_id,query_name,record_type,response_code,resolver,answers,collector,quality" }.Concat(page.Items.Select(x => string.Join(',', Safe(x.EventId.ToString()), Safe(x.ObservedAt.ToString("O")), Safe(x.EndpointId.ToString()), Safe(x.OriginalQueryName), Safe(x.RecordType), Safe(x.ResponseCode), Safe(x.ResolverAddress), Safe(string.Join(';', x.Answers.Select(a => a.Value))), Safe(x.CollectorSource), Safe(string.Join(';', x.DataQualityFlags))))); bytes = Encoding.UTF8.GetBytes(string.Join('\n', rows) + '\n'); } else bytes = Encoding.UTF8.GetBytes(string.Join('\n', page.Items.Select(x => JsonSerializer.Serialize(x, Json))) + '\n'); c.Response.Headers["X-Export-Schema"] = "dns-export.v1"; c.Response.Headers["X-Export-Records"] = page.Items.Count.ToString(System.Globalization.CultureInfo.InvariantCulture); c.Response.Headers["X-Content-SHA256"] = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(); return Results.File(bytes, csv ? "text/csv" : "application/x-ndjson", csv ? "dns-telemetry.csv" : "dns-telemetry.jsonl"); }
    static async Task<IResult> CreateExportAsync(DnsExportCreateRequest input, HttpContext c, IDnsExportRepository e, CancellationToken ct) { var format = input.Format.ToLowerInvariant(); if (format is not ("jsonl" or "csv")) return Problem(c, "EXPORT_FORMAT_INVALID", "Format must be jsonl or csv.", 400); if (input.MaximumRecords is < 1 or > 10000) return Problem(c, "EXPORT_LIMIT_INVALID", "Maximum records must be between 1 and 10000.", 400); var now = DateTimeOffset.UtcNow; var q = input.Query with { From = input.Query.From ?? now.AddHours(-24), To = input.Query.To ?? now, Cursor = null, PageSize = input.MaximumRecords }; if (q.To <= q.From || q.To - q.From > TimeSpan.FromDays(30)) return Problem(c, "TIME_RANGE_INVALID", "Export range must be positive and at most 30 days.", 400); var fields = input.Fields ?? []; if (fields.Length > 0 && fields.Distinct().Count() != DnsExportWorker.EffectiveFields(fields).Length) return Problem(c, "EXPORT_FIELDS_INVALID", "One or more DNS export fields are unsupported.", 400); var p = (PrincipalContext)c.Items["principal"]!; var v = await e.CreateAsync(p.TenantId, p.Subject, input with { Format = format, Query = q, Fields = fields }, ct); return Results.Accepted($"/api/v1/dns-exports/{v.Id}", Envelope(c, v)); }
    static async Task<IResult> ExportStatusAsync(Guid id, HttpContext c, IDnsExportRepository e, CancellationToken ct) => await e.GetAsync(Tenant(c), id, ct) is { } v ? Results.Ok(Envelope(c, v)) : Results.NotFound();
    static Task<IResult> ExportManifestAsync(Guid id, HttpContext c, IDnsExportRepository e, IObjectStorage o, CancellationToken ct) => ExportObject(id, c, e, o, true, ct);
    static Task<IResult> ExportMetadataAsync(Guid id, HttpContext c, IDnsExportRepository e, IObjectStorage o, CancellationToken ct) => ExportObject(id, c, e, o, false, ct);
    static async Task<IResult> ExportObject(Guid id, HttpContext c, IDnsExportRepository e, IObjectStorage o, bool manifest, CancellationToken ct) { if (await e.GetAsync(Tenant(c), id, ct) is not { State: FileExportState.Completed } v) return Results.NotFound(); return Results.Stream(await o.DownloadAsync(v.TenantId, (manifest ? v.ManifestObjectId : v.MetadataObjectId).ToString("D"), ct), "application/json"); }
    static async Task<IResult> ExportContentAsync(Guid id, HttpContext c, IDnsExportRepository e, IObjectStorage o, CancellationToken ct) { var p = (PrincipalContext)c.Items["principal"]!; if (await e.GetAsync(p.TenantId, id, ct) is not { State: FileExportState.Completed } v) return Results.NotFound(); await e.AuditDownloadAsync(p.TenantId, id, p.Subject, ct); return Results.Stream(await o.DownloadAsync(v.TenantId, v.OutputObjectId.ToString("D"), ct), v.Format == "csv" ? "text/csv" : "application/x-ndjson"); }
    static async Task<IResult> ExportDownloadUrlAsync(Guid id, FileExportDownloadRequest input, HttpContext c, IDnsExportRepository e, PlatformOptions options, CancellationToken ct) { var tenant = Tenant(c); if (await e.GetAsync(tenant, id, ct) is not { State: FileExportState.Completed } v) return Results.NotFound(); var expires = DateTimeOffset.UtcNow.AddSeconds(Math.Clamp(input.ExpiresInSeconds, 5, 300)); var token = FileExportDownloadToken.Create(tenant, v.Id, expires, options.JwtSigningKey); return Results.Ok(Envelope(c, new { url = $"{c.Request.Scheme}://{c.Request.Host}/api/v1/dns-exports/{id:D}/download?token={Uri.EscapeDataString(token)}", expiresAt = expires })); }
    static async Task<IResult> ExportSignedDownloadAsync(Guid id, string token, PlatformOptions options, IDnsExportRepository e, IObjectStorage o, CancellationToken ct) { if (!FileExportDownloadToken.TryValidate(token, options.JwtSigningKey, out var tenant, out var tokenId) || tokenId != id || await e.GetAsync(tenant, id, ct) is not { State: FileExportState.Completed } v) return Results.NotFound(); await e.AuditDownloadAsync(tenant, id, "signed-url", ct); return Results.Stream(await o.DownloadAsync(tenant, v.OutputObjectId.ToString("D"), ct), v.Format == "csv" ? "text/csv" : "application/x-ndjson"); }
    static async Task<IResult> EffectiveForAgentAsync(HttpContext c, IDnsPolicyRepository p, CancellationToken ct) { var principal = (PrincipalContext)c.Items["principal"]!; var ids = principal.Subject.Split(':'); return ids.Length == 2 && Guid.TryParse(ids[0], out var e) ? Results.Ok(await p.EffectiveAsync(principal.TenantId, e, ct)) : Results.Unauthorized(); }
    static async Task<IResult> AcknowledgeForAgentAsync(HttpContext c, DnsPolicyAcknowledgement a, IDnsPolicyRepository p, CancellationToken ct) { var principal = (PrincipalContext)c.Items["principal"]!; var ids = principal.Subject.Split(':'); if (ids.Length != 2 || !Guid.TryParse(ids[0], out var e)) return Results.Unauthorized(); if (a.PolicyId != Guid.Empty) await p.AcknowledgeAsync(principal.TenantId, e, a, ct); return Results.Accepted(); }
    static async Task<IResult> ListPoliciesAsync(HttpContext c, IDnsPolicyRepository p, CancellationToken ct) => Results.Ok(Envelope(c, await p.ListAsync(Tenant(c), ct)));
    static async Task<IResult> CreatePolicyAsync(DnsPolicyCreateRequest input, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) { var errors = DnsPolicyValidation.Validate(input.Policy); if (errors.Count > 0) return Results.ValidationProblem(errors.ToDictionary()); var principal = (PrincipalContext)c.Items["principal"]!; var v = await p.CreateAsync(principal.TenantId, principal.Subject, input.Name, input.Policy, ct); return Results.Created($"/api/v1/dns-telemetry/policies/{v.Id}", Envelope(c, v)); }
    static async Task<IResult> EffectivePolicyAsync(Guid endpointId, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) => Results.Ok(Envelope(c, await p.EffectiveAsync(Tenant(c), endpointId, ct)));
    static async Task<IResult> AssignPolicyAsync(Guid id, DnsPolicyAssignRequest input, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) { var principal = (PrincipalContext)c.Items["principal"]!; await p.AssignAsync(principal.TenantId, id, input.EndpointId, principal.Subject, ct); return Results.Accepted(); }
    static async Task<IResult> ListExclusionsAsync(Guid id, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) => (await p.ListAsync(Tenant(c), ct)).FirstOrDefault(x => x.Id == id) is { } v ? Results.Ok(Envelope(c, v.Policy.ExclusionRules?.ToArray() ?? [])) : Results.NotFound();
    static async Task<IResult> AddExclusionAsync(Guid id, DnsExclusionRule input, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) => await ChangeExclusion(id, input, null, c, p, ct);
    static async Task<IResult> DeleteExclusionAsync(Guid id, Guid ruleId, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) => await ChangeExclusion(id, null, ruleId, c, p, ct);
    static async Task<IResult> ChangeExclusion(Guid id, DnsExclusionRule? input, Guid? remove, HttpContext c, IDnsPolicyRepository p, CancellationToken ct) { var principal = (PrincipalContext)c.Items["principal"]!; var source = (await p.ListAsync(principal.TenantId, ct)).FirstOrDefault(x => x.Id == id); if (source is null) return Results.NotFound(); var rules = (source.Policy.ExclusionRules ?? []).ToList(); if (remove is { } rid) { if (rules.RemoveAll(x => x.Id == rid) == 0) return Results.NotFound(); } else rules.Add(input! with { Id = input!.Id == Guid.Empty ? Guid.NewGuid() : input.Id, Creator = principal.Subject, CreatedAt = DateTimeOffset.UtcNow }); var policy = source.Policy with { ExclusionRules = rules }; var errors = DnsPolicyValidation.Validate(policy); if (errors.Count > 0) return Results.ValidationProblem(errors.ToDictionary()); return Results.Ok(Envelope(c, await p.CreateAsync(principal.TenantId, principal.Subject, source.Name, policy, ct))); }
    static DnsSearchRequest Query(HttpRequest r) => new(Guid.TryParse(r.Query["endpointId"], out var e) ? e : null, DateTimeOffset.TryParse(r.Query["from"], out var f) ? f : null, DateTimeOffset.TryParse(r.Query["to"], out var t) ? t : null, r.Query["queryName"], r.Query["suffix"], r.Query["recordType"], r.Query["responseCode"], r.Query["resolvedIp"], r.Query["resolvedCidr"], r.Query["process"], r.Query["user"], r.Query["resolver"], r.Query["collector"], r.Query["quality"], Limit(r), r.Query["cursor"]);
    static (DateTimeOffset From, DateTimeOffset To) Range(HttpRequest r) { var now = DateTimeOffset.UtcNow; var from = DateTimeOffset.TryParse(r.Query["from"], out var f) ? f : now.AddHours(-24); var to = DateTimeOffset.TryParse(r.Query["to"], out var t) ? t : now; if (to <= from || to - from > TimeSpan.FromDays(30)) throw new EnrollmentConflictException("TIME_RANGE_INVALID", "Time range must be positive and at most 30 days."); return (from, to); }
    static int Limit(HttpRequest r) => int.TryParse(r.Query["limit"], out var n) ? Math.Clamp(n, 1, 10000) : 100;
    static string Tenant(HttpContext c) => c.Items["tenant"]!.ToString()!;
    static object Envelope(HttpContext c, object value) => new { traceId = c.TraceIdentifier, data = value };
    static IResult Problem(HttpContext c, string code, string message, int status) => Results.Json(new ApiError(code, message, status, c.TraceIdentifier), statusCode: status);
    public sealed record DnsPolicyCreateRequest(string Name, DnsTelemetryPolicy Policy);
    public sealed record DnsPolicyAssignRequest(Guid? EndpointId);
}
