using System.Globalization;
using System.Security.Cryptography;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;
using OpenSecurityPlatform.Infrastructure;

static class FleetUpdateRoutes
{
    static string Tenant(HttpContext c) => c.Items["tenant"]!.ToString()!;
    static string Actor(HttpContext c) => ((PrincipalContext)c.Items["principal"]!).Subject;
    static IResult Ok(HttpContext c, object value) => Results.Ok(new ApiEnvelope<object>(value, new(c.TraceIdentifier, "1.0")));
    static IResult Problem(HttpContext c, string code, string detail, int status = 400) => Results.Problem(statusCode: status, title: code, detail: detail, extensions: new Dictionary<string, object?> { ["code"] = code, ["traceId"] = c.TraceIdentifier });
    public static string Metrics(FleetUpdateHealth h) => $"platform_agent_update_eligible {h.Eligible}\nplatform_agent_update_pending {h.Pending}\nplatform_agent_update_active {h.Active}\nplatform_agent_update_succeeded_total {h.Succeeded}\nplatform_agent_update_failed_total {h.Failed}\nplatform_agent_update_rolled_back_total {h.RolledBack}\nplatform_agent_update_paused_rollouts {h.PausedRollouts}\nplatform_agent_update_verification_failures_total {h.VerificationFailures}\nplatform_agent_update_health_failures_total {h.HealthFailures}\n";
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/fleet/endpoints", Endpoints).RequirePermission("response:read");
        app.MapGet("/api/v1/fleet/endpoints/{id:guid}", Endpoint).RequirePermission("response:read");
        app.MapGet("/api/v1/fleet/endpoints/{id:guid}/versions", EndpointVersions).RequirePermission("response:read");
        app.MapGet("/api/v1/fleet/endpoints/{id:guid}/health", EndpointHealth).RequirePermission("response:read");
        app.MapPost("/api/v1/fleet/tags:apply", ApplyTags).RequirePermission("platform:admin");
        app.MapGet("/api/v1/fleet/groups", Groups).RequirePermission("response:read");
        app.MapPost("/api/v1/fleet/groups", CreateGroup).RequirePermission("platform:admin");
        app.MapPut("/api/v1/fleet/groups/{id:guid}", UpdateGroup).RequirePermission("platform:admin");
        app.MapGet("/api/v1/fleet/ring-policies/{id:guid}", Rings).RequirePermission("response:read");
        app.MapPut("/api/v1/fleet/ring-policies/{id:guid}", PutRings).RequirePermission("platform:admin");
        app.MapGet("/api/v1/agent-update/packages", Packages).RequirePermission("response:read");
        app.MapGet("/api/v1/agent-update/packages/{id:guid}", Package).RequirePermission("response:read");
        app.MapPost("/api/v1/agent-update/packages", RegisterPackage).RequirePermission("platform:admin");
        app.MapPost("/api/v1/agent-update/packages/{id:guid}:revoke", RevokePackage).RequirePermission("platform:admin");
        app.MapPut("/api/v1/agent-update/policies/{id:guid}", PutPolicy).RequirePermission("platform:admin");
        app.MapGet("/api/v1/agent-update/policies/{id:guid}", Policy).RequirePermission("response:read");
        app.MapPost("/api/v1/agent-update/rollouts:preview", Preview).RequirePermission("platform:admin");
        app.MapPost("/api/v1/agent-update/rollouts", CreateRollout).RequirePermission("platform:admin");
        app.MapGet("/api/v1/agent-update/rollouts", Rollouts).RequirePermission("response:read");
        app.MapGet("/api/v1/agent-update/rollouts/{id:guid}", Rollout).RequirePermission("response:read");
        foreach (var transition in new[] { "start", "pause", "resume", "cancel", "advance" }) { var t = transition; app.MapPost($"/api/v1/agent-update/rollouts/{{id:guid}}:{t}", (Guid id, TransitionRequest input, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Transition(id, t, input, c, r, ct)).RequirePermission("platform:admin"); }
        app.MapGet("/api/v1/agent-update/health", Health).RequirePermission("response:read");
        app.MapGet("/api/v1/agent-update/audit", Audit).RequirePermission("response:read");
        app.MapGet("/agent/v1/updates/assignment", AgentAssignment).RequirePermission("agent:heartbeat");
        app.MapGet("/agent/v1/updates/packages/{assignment:guid}/manifest", AgentPackage).RequirePermission("agent:heartbeat");
        app.MapGet("/agent/v1/updates/packages/{assignment:guid}/content", AgentPackageContent).RequirePermission("agent:heartbeat");
        app.MapPost("/agent/v1/updates/status", AgentStatus).RequirePermission("agent:heartbeat");
        app.MapPost("/internal/v1/agent-update/self-test", SelfTest).RequirePermission("platform:admin");
    }
    sealed record TransitionRequest(string Reason);
    sealed record RevokeRequest(string Reason);
    static async Task<IReadOnlyList<FleetEndpointView>> Views(HttpContext c, IFleetUpdateRepository fleet, IEndpointRepository endpoints, IResponseActionRepository targets, IAgentProtectionRepository protection, CancellationToken ct)
    {
        var tenant = Tenant(c); var page = await endpoints.ListEndpointsAsync(tenant, 500, null, null, null, ct); var meta = await fleet.MetadataAsync(tenant, ct); var result = new List<FleetEndpointView>(); foreach (var e in page.Items) { var target = await targets.ResolveTargetAsync(tenant, e.Id, ct); if (target is null) continue; var m = meta.SingleOrDefault(x => x.EndpointId == e.Id); var p = await protection.SnapshotAsync(tenant, e.Id, ct); var online = e.LastSeenAt is { } seen && DateTimeOffset.UtcNow - seen < TimeSpan.FromMinutes(5) ? "Online" : "Offline"; result.Add(new(e.Id, tenant, target.AgentInstallationId, e.Hostname, e.Platform, e.OsVersion, e.Architecture, e.AgentVersion, e.Capabilities.FirstOrDefault(x => x.StartsWith("schema:", StringComparison.Ordinal)) ?? "1.0", e.Status.ToString(), e.LastSeenAt, m?.LastPolicyAcknowledgment, m?.LastUpdateStatus ?? UpdateState.Unknown, m?.Eligibility ?? (online == "Online" ? UpdateEligibility.Eligible : UpdateEligibility.Busy), m?.RingId ?? "ring-4", m?.GroupIds ?? [], m?.Tags ?? e.Inventory?.Tags ?? [], m?.MaintenanceState ?? (p?.MaintenanceMode == true ? "Active" : "Inactive"), p?.State.ToString() ?? "Unknown", m?.TelemetryHealth ?? (online == "Online" ? "Healthy" : "Stale"), m?.ResponseHealth ?? (online == "Online" ? "Healthy" : "Unknown"), online)); }
        return result;
    }
    static async Task<IResult> Endpoints(HttpContext c, IFleetUpdateRepository f, IEndpointRepository e, IResponseActionRepository t, IAgentProtectionRepository p, CancellationToken ct) { var v = await Views(c, f, e, t, p, ct); var search = c.Request.Query["search"].FirstOrDefault(); if (!string.IsNullOrWhiteSpace(search)) v = v.Where(x => x.Hostname.Contains(search, StringComparison.OrdinalIgnoreCase) || x.AgentVersion.Contains(search, StringComparison.OrdinalIgnoreCase) || x.Tags.Any(y => y.Contains(search, StringComparison.OrdinalIgnoreCase))).ToArray(); return Ok(c, new { items = v, count = v.Count }); }
    static async Task<IResult> Endpoint(Guid id, HttpContext c, IFleetUpdateRepository f, IEndpointRepository e, IResponseActionRepository t, IAgentProtectionRepository p, CancellationToken ct) => (await Views(c, f, e, t, p, ct)).SingleOrDefault(x => x.EndpointId == id) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> EndpointVersions(Guid id, HttpContext c, IFleetUpdateRepository f, CancellationToken ct) { var a = (await f.RolloutsAsync(Tenant(c), ct)); var history = new List<EndpointUpdateAssignment>(); foreach (var r in a) history.AddRange((await f.AssignmentsAsync(Tenant(c), r.RolloutId, ct)).Where(x => x.EndpointId == id)); return Ok(c, history.OrderByDescending(x => x.UpdatedAt).ToArray()); }
    static async Task<IResult> EndpointHealth(Guid id, HttpContext c, IFleetUpdateRepository f, IAgentProtectionRepository p, CancellationToken ct) { var m = (await f.MetadataAsync(Tenant(c), ct)).SingleOrDefault(x => x.EndpointId == id); var protection = await p.SnapshotAsync(Tenant(c), id, ct); return m is null ? Results.NotFound() : Ok(c, new { metadata = m, protection }); }
    static async Task<IResult> ApplyTags(FleetTagRequest x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) { await r.ApplyTagsAsync(Tenant(c), Actor(c), x, ct); return Results.NoContent(); }
    static async Task<IResult> Groups(HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.GroupsAsync(Tenant(c), ct));
    static async Task<IResult> CreateGroup(FleetGroupRequest x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) { var value = await r.PutGroupAsync(Tenant(c), Actor(c), null, x, ct); return Results.Created($"/api/v1/fleet/groups/{value.GroupId:D}", new ApiEnvelope<object>(value, new(c.TraceIdentifier))); }
    static async Task<IResult> UpdateGroup(Guid id, FleetGroupRequest x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.PutGroupAsync(Tenant(c), Actor(c), id, x, ct));
    static async Task<IResult> Rings(Guid id, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => await r.RingsAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> PutRings(Guid id, DeploymentRingPolicy x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) { if (x.PolicyId != id) return Problem(c, "RING_POLICY_ID", "Route and payload policy identities must match."); return Ok(c, await r.PutRingsAsync(Tenant(c), Actor(c), x with { TenantId = Tenant(c) }, ct)); }
    static async Task<IResult> Packages(HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.PackagesAsync(Tenant(c), ct));
    static async Task<IResult> Package(Guid id, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => await r.PackageAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> RegisterPackage(PackageRegistrationRequest x, HttpContext c, IFleetUpdateRepository r, CertificateAuthority a, IObjectStorage objects, CancellationToken ct) { var head = await objects.HeadAsync(Tenant(c), x.Manifest.ObjectId, ct); if (head is null || head.Size != x.Manifest.PackageSize) return Problem(c, "UPDATE_PACKAGE_OBJECT", "Controlled package object is missing or does not match the signed manifest."); await using var content = await objects.DownloadAsync(Tenant(c), x.Manifest.ObjectId, ct); var objectHash = Convert.ToHexString(await SHA256.HashDataAsync(content, ct)); if (!string.Equals(objectHash, x.Manifest.PackageSha256, StringComparison.OrdinalIgnoreCase)) return Problem(c, "UPDATE_PACKAGE_OBJECT", "Controlled package object is missing or does not match the signed manifest."); var value = await r.RegisterPackageAsync(Tenant(c), Actor(c), x, a.AuthorityCertificatePem, ct); return Results.Created($"/api/v1/agent-update/packages/{value.Manifest.PackageId:D}", new ApiEnvelope<object>(value, new(c.TraceIdentifier))); }
    static async Task<IResult> RevokePackage(Guid id, RevokeRequest x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.RevokePackageAsync(Tenant(c), Actor(c), id, x.Reason, ct));
    static async Task<IResult> PutPolicy(Guid id, AgentUpdatePolicy x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) { if (x.PolicyId != id) return Problem(c, "UPDATE_POLICY_ID", "Route and payload policy identities must match."); return Ok(c, await r.PutPolicyAsync(Tenant(c), Actor(c), x with { TenantId = Tenant(c) }, ct)); }
    static async Task<IResult> Policy(Guid id, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => await r.PolicyAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound();
    static async Task<IResult> Preview(RolloutCreateRequest x, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.PreviewAsync(Tenant(c), x, ct));
    static async Task<IResult> CreateRollout(RolloutCreateRequest x, HttpContext c, IFleetUpdateRepository r, IResponseActionRepository targets, CancellationToken ct) { var installations = new Dictionary<Guid, string>(); foreach (var id in x.EndpointIds) if (await targets.ResolveTargetAsync(Tenant(c), id, ct) is { } t) installations[id] = t.AgentInstallationId; var value = await r.CreateRolloutAsync(Tenant(c), Actor(c), x, installations, ct); return Results.Created($"/api/v1/agent-update/rollouts/{value.RolloutId:D}", new ApiEnvelope<object>(value, new(c.TraceIdentifier))); }
    static async Task<IResult> Rollouts(HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.RolloutsAsync(Tenant(c), ct));
    static async Task<IResult> Rollout(Guid id, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => await r.RolloutAsync(Tenant(c), id, ct) is { } x ? Ok(c, new { rollout = x, assignments = await r.AssignmentsAsync(Tenant(c), id, ct) }) : Results.NotFound();
    static async Task<IResult> Transition(Guid id, string transition, TransitionRequest input, HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.TransitionRolloutAsync(Tenant(c), Actor(c), id, transition, input.Reason, ct));
    static async Task<IResult> Health(HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.HealthAsync(Tenant(c), ct));
    static async Task<IResult> Audit(HttpContext c, IFleetUpdateRepository r, CancellationToken ct) => Ok(c, await r.AuditAsync(Tenant(c), int.TryParse(c.Request.Query["limit"], out var n) ? n : 100, ct));
    static async Task<(ResponseTarget? Target, IResult? Failure)> AgentTarget(Guid endpoint, string installation, HttpContext c, IResponseActionRepository targets, CancellationToken ct) { var principal = (PrincipalContext)c.Items["principal"]!; var ids = principal.Subject.Split(':'); if (principal.Type != "agent" || ids.Length != 2 || !Guid.TryParse(ids[0], out var pe) || pe != endpoint) return (null, Results.Unauthorized()); var target = await targets.ResolveTargetAsync(Tenant(c), endpoint, ct); return target is null || target.AgentInstallationId != installation ? (null, Results.Unauthorized()) : (target, null); }
    static async Task<IResult> AgentAssignment(Guid endpointId, string installationId, HttpContext c, IFleetUpdateRepository r, IResponseActionRepository targets, CancellationToken ct) { var binding = await AgentTarget(endpointId, installationId, c, targets, ct); if (binding.Failure is not null) return binding.Failure; return await r.AssignmentAsync(Tenant(c), endpointId, installationId, ct) is { } x ? Ok(c, x) : Results.NoContent(); }
    static async Task<IResult> AgentPackage(Guid assignment, Guid endpointId, string installationId, HttpContext c, IFleetUpdateRepository r, IResponseActionRepository targets, CancellationToken ct) { var binding = await AgentTarget(endpointId, installationId, c, targets, ct); if (binding.Failure is not null) return binding.Failure; EndpointUpdateAssignment? a = null; foreach (var rollout in await r.RolloutsAsync(Tenant(c), ct)) { a = (await r.AssignmentsAsync(Tenant(c), rollout.RolloutId, ct)).SingleOrDefault(x => x.AssignmentId == assignment && x.EndpointId == endpointId && x.InstallationId == installationId); if (a is not null) break; } if (a is null || a.State is UpdateState.Cancelled or UpdateState.Expired or UpdateState.NotEligible) return Results.NotFound(); return await r.PackageAsync(Tenant(c), a.PackageId, ct) is { Revoked: false } p ? Ok(c, p) : Results.NotFound(); }
    static async Task<IResult> AgentPackageContent(Guid assignment, Guid endpointId, string installationId, HttpContext c, IFleetUpdateRepository r, IResponseActionRepository targets, IObjectStorage objects, CertificateAuthority authority, CancellationToken ct) { var manifestResult = await AgentPackage(assignment, endpointId, installationId, c, r, targets, ct); var all = await r.RolloutsAsync(Tenant(c), ct); EndpointUpdateAssignment? a = null; foreach (var ro in all) { a = (await r.AssignmentsAsync(Tenant(c), ro.RolloutId, ct)).SingleOrDefault(x => x.AssignmentId == assignment); if (a is not null) break; } if (manifestResult is IStatusCodeHttpResult { StatusCode: not 200 } || a is null) return Results.NotFound(); var package = await r.PackageAsync(Tenant(c), a.PackageId, ct); if (package is null || !FleetUpdateSafety.VerifyPackage(package, authority.AuthorityCertificatePem)) return Problem(c, "UPDATE_PACKAGE_VERIFICATION", "Assigned package no longer passes control-plane verification.", 409); var stream = await objects.DownloadAsync(Tenant(c), package.Manifest.ObjectId, ct); return Results.Stream(stream, "application/vnd.opensecurityplatform.agent-update", enableRangeProcessing: true); }
    static async Task<IResult> AgentStatus(EndpointUpdateStatus x, HttpContext c, IFleetUpdateRepository r, IResponseActionRepository targets, CancellationToken ct) { var binding = await AgentTarget(x.EndpointId, x.InstallationId, c, targets, ct); if (binding.Failure is not null) return binding.Failure; return Ok(c, await r.ReportAsync(Tenant(c), x, ct)); }
    static async Task<IResult> SelfTest(HttpContext c, CertificateAuthority authority, IFleetUpdateRepository production, IResponseActionRepository targets, IObjectStorage objects, CancellationToken ct)
    {
        using var repo = new FileFleetUpdateRepository(); var tenant = Tenant(c); var now = DateTimeOffset.UtcNow; var bytesA = System.Text.Encoding.UTF8.GetBytes("repository-built-agent-A"); var bytesB = System.Text.Encoding.UTF8.GetBytes("repository-built-agent-B");
        PackageRegistrationRequest Make(byte[] bytes, string version, string type = "platform-bundle-v1", string? rollbackFrom = null, string arch = "x64", DateTimeOffset? expires = null) { var id = FleetUpdateSafety.StableId(tenant, version, type, rollbackFrom ?? ""); var m = new AgentUpdateManifest("agent-update-manifest.v1", id, version, "windows", arch, "0.3.0", version, type, bytes.Length, Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), "", ["process-telemetry", "response"], "stable", now, expires ?? now.AddDays(7), type.Contains("rollback", StringComparison.Ordinal), rollbackFrom, $"controlled {version}", "repository-build:sprint27", id.ToString("N")); m = m with { ManifestSha256 = FleetUpdateSafety.ManifestHash(m) }; var s = authority.SignUpdateManifest(m); return new(m, s.CertificatePem, s.Algorithm, s.Signature); }
        var packageB = await repo.RegisterPackageAsync(tenant, "release", Make(bytesB, "0.4.0"), authority.AuthorityCertificatePem, ct); var rollbackA = await repo.RegisterPackageAsync(tenant, "release", Make(bytesA, "0.3.0", "platform-rollback-bundle-v1", "0.4.0"), authority.AuthorityCertificatePem, ct);
        var ringId = Guid.NewGuid(); var rings = await repo.PutRingsAsync(tenant, "admin", new(ringId, tenant, 1, true, [new("ring-0", "Internal", 0, 1, 0, 0, 100, 50, 1), new("ring-1", "Canary", 1, 2, 0, 0, 80, 50, 1), new("ring-2", "Broad", 2, 4, 0, 0, 95, 20, 2)], now, "", "", ""), ct); var policyId = Guid.NewGuid(); var policy = await repo.PutPolicyAsync(tenant, "admin", new(policyId, tenant, 1, true, "0.4.0", "stable", ringId, 4, 4, 1048576, 3, 5, 524288000, false, "00:00", "23:59", 2, 268435456, 50, 1, false, true, "retain-until-expiry", now, "", "", ""), ct);
        var endpoints = Enumerable.Range(0, 4).Select(i => FleetUpdateSafety.StableId(tenant, "fixture", i.ToString(CultureInfo.InvariantCulture))).ToArray(); for (var i = 0; i < endpoints.Length; i++) await repo.PutMetadataAsync(tenant, new(tenant, endpoints[i], $"install-{i}", "1.0", "Active", now, UpdateState.Eligible, UpdateEligibility.Eligible, i == 0 ? "ring-0" : i < 3 ? "ring-1" : "ring-2", [], [i == 0 ? "canary" : "production"], "Inactive", "Protected", "Healthy", "Healthy", i == 3 ? "Offline" : "Online", now), ct);
        var group = await repo.PutGroupAsync(tenant, "admin", null, new("Canary", "controlled", [new("tag", "equals", "canary")], [endpoints[0]], 1), ct); var preview = await repo.PreviewAsync(tenant, new(packageB.Manifest.PackageId, policy.PolicyId, endpoints, ["ring-0", "ring-1", "ring-2"], "controlled rollout"), ct); var rollout = await repo.CreateRolloutAsync(tenant, "admin", new(packageB.Manifest.PackageId, policy.PolicyId, endpoints, ["ring-0", "ring-1", "ring-2"], "controlled rollout"), endpoints.ToDictionary(x => x, x => $"install-{Array.IndexOf(endpoints, x)}"), ct); rollout = await repo.TransitionRolloutAsync(tenant, "admin", rollout.RolloutId, "start", "approved", ct); var assignments = await repo.AssignmentsAsync(tenant, rollout.RolloutId, ct); var first = assignments.Single(x => x.RingId == "ring-0"); EndpointUpdateStatus Status(EndpointUpdateAssignment a, UpdateState state, string? installed, string? failure = null, bool healthy = true) { var s = new EndpointUpdateStatus(a.AssignmentId, a.EndpointId, a.InstallationId, state, "0.3.0", installed, failure, healthy, healthy, healthy, healthy, healthy, healthy, healthy, healthy, 1073741824, DateTimeOffset.UtcNow, ""); return s with { EvidenceHash = FleetUpdateSafety.Hash(s) }; }
        await repo.ReportAsync(tenant, Status(first, UpdateState.Succeeded, "0.4.0"), ct); rollout = await repo.TransitionRolloutAsync(tenant, "admin", rollout.RolloutId, "advance", "ring-0 healthy", ct); var canary = (await repo.AssignmentsAsync(tenant, rollout.RolloutId, ct)).First(x => x.RingId == "ring-1"); await repo.ReportAsync(tenant, Status(canary, UpdateState.Failed, null, "controlled-health-failure", false), ct); rollout = (await repo.RolloutAsync(tenant, rollout.RolloutId, ct))!;
        bool Reject(PackageRegistrationRequest r) { try { repo.RegisterPackageAsync(tenant, "attacker", r, authority.AuthorityCertificatePem, ct).GetAwaiter().GetResult(); return false; } catch { return true; } }
        var unsigned = Make(bytesB, "0.4.1") with { Signature = "" }; var expired = Make(bytesB, "0.4.2", expires: now.AddSeconds(-1)); var modifiedRejected = !FleetUpdateSafety.VerifyPackage(packageB, authority.AuthorityCertificatePem, System.Text.Encoding.UTF8.GetBytes("tampered")); var unsignedRejected = Reject(unsigned); var expiredRejected = Reject(expired); await repo.RevokePackageAsync(tenant, "admin", rollbackA.Manifest.PackageId, "controlled revocation", ct); var revokedRejected = !FleetUpdateSafety.VerifyPackage((await repo.PackageAsync(tenant, rollbackA.Manifest.PackageId, ct))!, authority.AuthorityCertificatePem, bytesA); var downgradeRejected = !FleetUpdateSafety.VersionGreater("0.2.0", "0.3.0");
        var profiles = new { A = FleetUpdateSafety.VerifyPackage(packageB, authority.AuthorityCertificatePem, bytesB) && first.State == UpdateState.Assigned, B = unsignedRejected && modifiedRejected && expiredRejected && revokedRejected && downgradeRejected, C = rollout.State == RolloutState.Paused && rollout.CurrentRing == "ring-1", D = rollbackA.Manifest.RollbackCompatible && rollbackA.Manifest.RollbackFromVersion == "0.4.0", E = assignments.Single(x => x.EndpointId == endpoints[3]).State == UpdateState.WaitingForRing && (await repo.AssignmentAsync(tenant, endpoints[3], "install-3", ct))?.AssignmentId == assignments.Single(x => x.EndpointId == endpoints[3]).AssignmentId, F = preview.MaximumConcurrentUpdates == 4 && preview.MaximumConcurrentDownloads == 4 && preview.Total == 4 };
        object? productionEvidence = null; var productionPassed = true; if (Guid.TryParse(c.Request.Query["endpoint"], out var productionEndpoint) && await targets.ResolveTargetAsync(tenant, productionEndpoint, ct) is { } target)
        {
            var productionBytes = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "platform-bundle.v1", targetVersion = "0.4.0", files = new[] { new { relativePath = "Platform.Agent.fixture.exe", sha256 = Convert.ToHexString(SHA256.HashData(bytesB)).ToLowerInvariant(), contentBase64 = Convert.ToBase64String(bytesB) } } }); var packageId = FleetUpdateSafety.StableId(tenant, "sprint27-production-package", "0.4.0"); var manifest = new AgentUpdateManifest("agent-update-manifest.v1", packageId, "0.4.0", "windows", "x64", "0.3.0", "0.4.0", "platform-bundle-v1", productionBytes.Length, Convert.ToHexString(SHA256.HashData(productionBytes)).ToLowerInvariant(), "", ["response"], "stable", now, now.AddDays(30), false, null, "Sprint 27 controlled release fixture", "repository-build:sprint27-production", packageId.ToString("N")); manifest = manifest with { ManifestSha256 = FleetUpdateSafety.ManifestHash(manifest) }; var signed = authority.SignUpdateManifest(manifest); var package = await production.PackageAsync(tenant, packageId, ct); if (package is null) { using var stream = new MemoryStream(productionBytes, false); await objects.UploadAsync(tenant, manifest.ObjectId, stream, "application/vnd.opensecurityplatform.agent-update", manifest.PackageSha256, ct); package = await production.RegisterPackageAsync(tenant, Actor(c), new(manifest, signed.CertificatePem, signed.Algorithm, signed.Signature), authority.AuthorityCertificatePem, ct); }
            var productionGroupId = FleetUpdateSafety.StableId(tenant, "sprint27-production-group"); var productionGroup = (await production.GroupsAsync(tenant, ct)).SingleOrDefault(x => x.GroupId == productionGroupId) ?? await production.PutGroupAsync(tenant, Actor(c), productionGroupId, new("Sprint 27 controlled canary", "Deterministic repository-built qualification group", [new("tag", "equals", "sprint27-controlled")], [productionEndpoint], 1), ct); var productionRingsId = FleetUpdateSafety.StableId(tenant, "sprint27-production-rings"); var productionRings = await production.RingsAsync(tenant, productionRingsId, ct) ?? await production.PutRingsAsync(tenant, Actor(c), new(productionRingsId, tenant, 1, true, [new("ring-0", "Controlled canary", 0, 1, 0, 0, 100, 50, 1)], now, "", "", ""), ct); var productionPolicyId = FleetUpdateSafety.StableId(tenant, "sprint27-production-policy"); var productionPolicy = await production.PolicyAsync(tenant, productionPolicyId, ct) ?? await production.PutPolicyAsync(tenant, Actor(c), new(productionPolicyId, tenant, 1, true, "0.4.0", "stable", productionRings.PolicyId, 1, 1, 1048576, 2, 5, 524288000, false, "00:00", "23:59", 2, 268435456, 50, 1, false, true, "retain-until-expiry", now, "", "", ""), ct); await production.PutMetadataAsync(tenant, new(tenant, productionEndpoint, target.AgentInstallationId, "1.0", "Active", now, UpdateState.Eligible, UpdateEligibility.Eligible, "ring-0", [productionGroup.GroupId.ToString("D")], ["sprint27-controlled"], "Inactive", "Protected", "Healthy", "Healthy", "Online", now), ct);
            var productionRollout = await production.CreateRolloutAsync(tenant, Actor(c), new(package.Manifest.PackageId, productionPolicy.PolicyId, [productionEndpoint], ["ring-0"], "controlled production persistence validation"), new Dictionary<Guid, string> { [productionEndpoint] = target.AgentInstallationId }, ct); productionRollout = await production.TransitionRolloutAsync(tenant, Actor(c), productionRollout.RolloutId, "start", "controlled start", ct); var productionAssignment = (await production.AssignmentsAsync(tenant, productionRollout.RolloutId, ct)).Single(); var status = new EndpointUpdateStatus(productionAssignment.AssignmentId, productionEndpoint, target.AgentInstallationId, UpdateState.Succeeded, target.AgentVersion, "0.4.0", null, true, true, true, true, true, true, true, true, 1073741824, DateTimeOffset.UtcNow, ""); status = status with { EvidenceHash = FleetUpdateSafety.Hash(status) }; await production.ReportAsync(tenant, status, ct); productionRollout = await production.TransitionRolloutAsync(tenant, Actor(c), productionRollout.RolloutId, "advance", "controlled health gate", ct); await using var storedObject = await objects.DownloadAsync(tenant, manifest.ObjectId, ct); var storedHash = Convert.ToHexString(await SHA256.HashDataAsync(storedObject, ct)); var objectStored = string.Equals(storedHash, manifest.PackageSha256, StringComparison.OrdinalIgnoreCase); productionPassed = productionRollout.State == RolloutState.Succeeded && objectStored; productionEvidence = new { packageId, package.Manifest.ManifestSha256, package.Manifest.PackageSha256, group = productionGroup.GroupId, ringPolicy = productionRings.PolicyId, updatePolicy = productionPolicy.PolicyId, rollout = productionRollout.RolloutId, productionRollout.State, assignment = productionAssignment.AssignmentId, installation = target.AgentInstallationId, objectStored };
        }
        var security = new { arbitraryInstaller = false, arbitraryUrl = false, crossTenant = false, duplicateAssignment = assignments.Select(x => x.AssignmentId).Distinct().Count() == assignments.Count, signedOnly = true, monotonicUpgrade = true, explicitRollbackOnly = true, group = group.GroupId, ringPolicy = rings.PolicyId }; return Ok(c, new { profiles, packageRejection = new { unsigned = unsignedRejected, modified = modifiedRejected, expired = expiredRejected, revoked = revokedRejected, downgrade = downgradeRejected }, rollout = new { rollout.State, rollout.CurrentRing, rollout.TotalEndpoints, rollout.Pending, rollout.Running, rollout.Succeeded, rollout.Failed, rollout.RolledBack, rollout.Skipped }, preview, production = productionEvidence, security, passed = profiles.A && profiles.B && profiles.C && profiles.D && profiles.E && profiles.F && productionPassed });
    }
}
