using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;

static class ForensicWorkspaceRoutes
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    sealed record InvestigationCreate(string Title, string Description, string Priority, string Owner, Guid[]? EndpointIds = null, Guid[]? IncidentIds = null, Guid[]? AlertIds = null, string[]? Tags = null);
    sealed record StatusRequest(InvestigationStatus Status, string Reason);
    sealed record CollectionLinkRequest(Guid CollectionId, Guid EndpointId, string AgentInstallationId, string ProfileId, int ProfileVersion, string ProfileHash, string State, DateTimeOffset RequestedAt, int RequestedItems, string IdempotencyKey, Guid? RecollectionOf = null);
    sealed record TagRequest(string[] Tags); sealed record BookmarkRequest(string Purpose); sealed record NoteRequest(string TargetType, string TargetId, string Body, bool AiDraft = false, bool Accepted = false, string[]? EvidenceCitations = null);
    sealed record ParseRequest(string ParserId, string ParserVersion); sealed record HoldRequest(string Reason, DateTimeOffset? ExpiresAt = null); sealed record ExportRequest(Guid[] EvidenceIds, string Reason);
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/forensics/profiles", Profiles).RequirePermission("forensics:profiles:read");
        app.MapGet("/api/v1/forensics/parsers", Parsers).RequirePermission("forensics:read");
        app.MapGet("/api/v1/investigations", Investigations).RequirePermission("forensics:read");
        app.MapPost("/api/v1/investigations", CreateInvestigation).RequirePermission("forensics:collect");
        app.MapGet("/api/v1/investigations/{id:guid}", Investigation).RequirePermission("forensics:read");
        app.MapPost("/api/v1/investigations/{id:guid}:status", Status).RequirePermission("forensics:collect");
        app.MapPost("/api/v1/investigations/{id:guid}/collections", LinkCollection).RequirePermission("forensics:collect");
        app.MapPost("/api/v1/investigations/{id:guid}/collections/{collection:guid}:import", ImportCollection).RequirePermission("forensics:collect");
        app.MapGet("/api/v1/investigations/{id:guid}/collections", Collections).RequirePermission("forensics:read");
        app.MapGet("/api/v1/forensics/evidence", Evidence).RequirePermission("forensics:read");
        app.MapGet("/api/v1/forensics/evidence/{id:guid}", Artifact).RequirePermission("forensics:read");
        app.MapGet("/api/v1/forensics/evidence/{id:guid}/download", Download).RequirePermission("forensics:download");
        app.MapGet("/api/v1/forensics/evidence/{id:guid}/range", EvidenceRange).RequirePermission("forensics:download");
        app.MapPost("/api/v1/forensics/evidence/{id:guid}:verify", Verify).RequirePermission("forensics:verify");
        app.MapPost("/api/v1/forensics/evidence/{id:guid}:parse", Parse).RequirePermission("forensics:parse");
        app.MapPost("/api/v1/investigations/{investigation:guid}/evidence/{evidence:guid}:tag", Tag).RequirePermission("forensics:annotate");
        app.MapPost("/api/v1/investigations/{investigation:guid}/evidence/{evidence:guid}:bookmark", Bookmark).RequirePermission("forensics:annotate");
        app.MapPost("/api/v1/investigations/{investigation:guid}/notes", Note).RequirePermission("forensics:annotate");
        app.MapGet("/api/v1/investigations/{id:guid}/notes", Notes).RequirePermission("forensics:read");
        app.MapGet("/api/v1/investigations/{id:guid}/bookmarks", Bookmarks).RequirePermission("forensics:read");
        app.MapGet("/api/v1/investigations/{id:guid}/timeline", Timeline).RequirePermission("forensics:read");
        app.MapGet("/api/v1/investigations/{id:guid}/entities", Entities).RequirePermission("forensics:read");
        app.MapGet("/api/v1/investigations/{id:guid}/custody", Custody).RequirePermission("forensics:custody:read");
        app.MapPost("/api/v1/investigations/{id:guid}:hold", Hold).RequirePermission("forensics:hold");
        app.MapPost("/api/v1/investigations/{investigation:guid}/evidence/{evidence:guid}:hold", HoldEvidence).RequirePermission("forensics:hold");
        app.MapGet("/api/v1/investigations/{id:guid}/holds", Holds).RequirePermission("forensics:read");
        app.MapPost("/api/v1/investigations/{id:guid}/holds/{hold:guid}:release", ReleaseHold).RequirePermission("forensics:hold");
        app.MapPost("/api/v1/investigations/{id:guid}/ai-summary", AiSummary).RequirePermission("ai:use");
        app.MapPost("/api/v1/investigations/{id:guid}/exports", Export).RequirePermission("forensics:export");
        app.MapGet("/api/v1/investigations/{id:guid}/exports", Exports).RequirePermission("forensics:read");
        app.MapGet("/api/v1/forensics/exports/{id:guid}/manifest", ExportManifest).RequirePermission("forensics:download");
        app.MapGet("/api/v1/forensics/exports/{id:guid}/download", ExportDownload).RequirePermission("forensics:download");
        app.MapGet("/api/v1/forensics/exports/{id:guid}/range", ExportRange).RequirePermission("forensics:download");
        app.MapGet("/api/v1/forensics/tools/library", ToolLibrary).RequirePermission("forensics:read");
        app.MapGet("/api/v1/endpoints/{id:guid}/forensic-readiness", Readiness).RequirePermission("forensics:read");
        app.MapGet("/api/v1/forensics/workspace-health", Health).RequirePermission("forensics:health:read");
    }
    static string Tenant(HttpContext c) => ((PrincipalContext)c.Items["principal"]!).TenantId; static string Actor(HttpContext c) => ((PrincipalContext)c.Items["principal"]!).Subject; static IResult Ok(HttpContext c, object x) => Results.Ok(new ApiEnvelope<object>(x, new(c.TraceIdentifier, "1.0")));
    static IResult Profiles(HttpContext c) => Ok(c, ForensicWorkspaceSafety.Profiles); static IResult Parsers(HttpContext c) => Ok(c, ForensicWorkspaceSafety.Parsers);
    static async Task<IResult> Investigations(HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var q = c.Request.Query; var state = await s.GetAsync(Tenant(c), ct); var items = state.Investigations.Where(x => (!Guid.TryParse(q["endpointId"], out var endpoint) || x.EndpointIds.Contains(endpoint)) && (string.IsNullOrWhiteSpace(q["status"]) || x.Status.ToString() == q["status"]) && (string.IsNullOrWhiteSpace(q["text"]) || x.Title.Contains(q["text"]!, StringComparison.OrdinalIgnoreCase))).OrderByDescending(x => x.UpdatedAt).Take(Math.Clamp(int.TryParse(q["limit"], out var n) ? n : 100, 1, 500)).ToArray(); return Ok(c, new { items, total = items.Length }); }
    static async Task<IResult> CreateInvestigation(InvestigationCreate x, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Results.Created("/api/v1/investigations", new ApiEnvelope<object>(await s.CreateAsync(Tenant(c), Actor(c), x.Title, x.Description, x.Priority, x.Owner, x.EndpointIds ?? [], x.IncidentIds ?? [], x.AlertIds ?? [], x.Tags ?? [], ct), new(c.TraceIdentifier, "1.0")));
    static async Task<IResult> Investigation(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); var x = state.Investigations.SingleOrDefault(x => x.InvestigationId == id); return x is null ? Results.NotFound() : Ok(c, new { x, evidenceCount = state.Artifacts.Count(a => a.InvestigationId == id), collectionCount = state.Collections.Count(a => a.InvestigationId == id), activeCollections = state.Collections.Count(a => a.InvestigationId == id && a.State is "Requested" or "Approved" or "Queued" or "Running" or "Transferring" or "Verifying" or "Parsing"), collectionFailures = state.Collections.Count(a => a.InvestigationId == id && a.State is "Partial" or "Failed"), bookmarks = state.Bookmarks.Count(a => a.InvestigationId == id), notes = state.Notes.Count(a => a.InvestigationId == id) }); }
    static async Task<IResult> Status(Guid id, StatusRequest x, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, await s.StatusAsync(Tenant(c), Actor(c), id, x.Status, x.Reason, ct));
    static async Task<IResult> LinkCollection(Guid id, CollectionLinkRequest x, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var value = new InvestigationCollection(x.CollectionId, id, Tenant(c), x.EndpointId, x.AgentInstallationId, x.ProfileId, x.ProfileVersion, x.ProfileHash, x.State, x.RequestedAt, null, null, x.RequestedItems, 0, 0, 0, 0, 0, 0, null, null, x.RecollectionOf, x.IdempotencyKey); return Ok(c, await s.LinkCollectionAsync(Tenant(c), Actor(c), id, value, ct)); }
    static async Task<IResult> ImportCollection(Guid id, Guid collection, HttpContext c, ForensicWorkspaceService s, IResponseActionRepository responses, CancellationToken ct)
    {
        var page = await responses.SearchAsync(Tenant(c), null, null, 200, null, ct); var action = page.Items.FirstOrDefault(x => x.ActionType == ForensicCollectionSafety.ActionType && x.Parameters.TryGetProperty("collectionId", out var p) && p.TryGetGuid(out var found) && found == collection); if (action is null) return Results.NotFound(); ForensicCollectionResult? result = null; try { result = action.Result?.StructuredResult.Deserialize<ForensicCollectionResult>(Json); } catch (JsonException) { }
        var requested = action.Parameters.GetProperty("requestedArtifacts").GetArrayLength(); var profile = ForensicWorkspaceSafety.Profiles.FirstOrDefault(x => x.ProfileId == action.Parameters.GetProperty("profileId").GetString()); var link = new InvestigationCollection(collection, id, Tenant(c), action.EndpointId, action.AgentInstallationId, profile?.ProfileId ?? action.Parameters.GetProperty("profileId").GetString()!, profile?.Version ?? 1, profile?.ProfileHash ?? action.Parameters.GetProperty("profileHash").GetString()!, result?.State.ToString() ?? action.State.ToString(), action.RequestedAt, action.StartedAt, action.CompletedAt, requested, result?.CollectedItems ?? 0, result?.FailedItems ?? 0, result?.SkippedItems ?? 0, result?.BytesCollected ?? 0, result?.BytesCollected ?? 0, result?.Items.Sum(x => x.ArtifactId is null ? 0 : 1) ?? 0, result?.FailureReason, result?.FailureReason, null, $"response-action:{action.ResponseActionId:D}"); await s.LinkCollectionAsync(Tenant(c), Actor(c), id, link, ct);
        if (result is not null) foreach (var item in result.Items) { var artifactId = item.ArtifactId; var stored = artifactId is not null && item.Sha256 is { Length: 64 }; var responseArtifact = stored ? action.Result?.Artifacts.FirstOrDefault(x => x.ArtifactId == artifactId!.Value) : null; var manifestArtifact = action.Result?.Artifacts.FirstOrDefault(x => x.ArtifactId == result.ManifestArtifactId); var evidence = new ForensicWorkspaceArtifact(item.EvidenceItemId, id, collection, Tenant(c), action.EndpointId, action.AgentInstallationId, item.ArtifactType.ToString(), item.SourceObject, item.AcquisitionMethod, item.AcquisitionToolVersion, item.SourceObject, item.NativeIdentity, null, item.ObservedAt, item.AcquisitionStartedAt, item.AcquisitionCompletedAt, item.AcquiredSize, stored ? item.AcquiredSize : 0, stored ? 1 : 0, stored ? item.Sha256! : new string('0', 64), stored && responseArtifact is not null, stored ? responseArtifact!.ObjectId : $"unavailable:{item.EvidenceItemId:D}", responseArtifact?.MediaType ?? "application/octet-stream", stored ? EvidenceIntegrityStatus.NotVerified : EvidenceIntegrityStatus.Missing, null, null, EvidenceParseStatus.NotRequested, "NotRequested", null, item.RequestId, [], [], [], false, item.State.ToString(), item.FailureReason, item.FailureReason, DateTimeOffset.UtcNow, manifestArtifact?.ObjectId, result.ManifestHash); await s.AddArtifactAsync(Tenant(c), "system:collection-import", evidence, ct); }
        return Ok(c, new { collectionId = collection, importedArtifacts = result?.Items.Length ?? 0, state = result?.State.ToString() ?? action.State.ToString() });
    }
    static async Task<IResult> Collections(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, (await s.GetAsync(Tenant(c), ct)).Collections.Where(x => x.InvestigationId == id).OrderByDescending(x => x.RequestedAt));
    static EvidenceSearch Search(HttpContext c) { var q = c.Request.Query; return new(q["text"], Guid.TryParse(q["investigationId"], out var i) ? i : null, Guid.TryParse(q["collectionId"], out var col) ? col : null, Guid.TryParse(q["endpointId"], out var e) ? e : null, q["evidenceType"], q["hash"], q["state"], q["parser"], q["tag"], bool.TryParse(q["bookmarked"], out var b) ? b : null, int.TryParse(q["limit"], out var n) ? n : 100, q["cursor"]); }
    static async Task<IResult> Evidence(HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var (items, next) = await s.SearchAsync(Tenant(c), Search(c), ct); return Ok(c, new { items, nextCursor = next }); }
    static async Task<IResult> Artifact(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var a = (await s.GetAsync(Tenant(c), ct)).Artifacts.SingleOrDefault(x => x.EvidenceId == id); if (a is null) return Results.NotFound(); await s.RecordCustodyAsync(Tenant(c), a.InvestigationId, a.CollectionId, id, Actor(c), "evidence.viewed", "success", "workspace", "analyst", a.Sha256, "Artifact detail viewed", ct); return Ok(c, a); }
    static async Task<IResult> Download(Guid id, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var a = (await s.GetAsync(Tenant(c), ct)).Artifacts.SingleOrDefault(x => x.EvidenceId == id); if (a is null || a.Integrity == EvidenceIntegrityStatus.Missing || a.ObjectId.StartsWith("unavailable:", StringComparison.Ordinal)) return Results.NotFound(); var stream = await objects.DownloadAsync(Tenant(c), a.ObjectId, ct); await s.RecordCustodyAsync(Tenant(c), a.InvestigationId, a.CollectionId, id, Actor(c), "evidence.downloaded", "success", "object-storage", "analyst", a.Sha256, "Authorized range-capable download", ct); return Results.Stream(stream, a.MediaType, fileDownloadName: $"evidence-{id:D}", enableRangeProcessing: true); }
    static async Task<IResult> EvidenceRange(Guid id, long offset, int? length, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var a = (await s.GetAsync(Tenant(c), ct)).Artifacts.SingleOrDefault(x => x.EvidenceId == id); if (a is null || a.Integrity == EvidenceIntegrityStatus.Missing || offset < 0 || offset >= a.Size) return Results.NotFound(); var count = Math.Min(Math.Clamp(length ?? 8 * 1024 * 1024, 1, 8 * 1024 * 1024), checked((int)Math.Min(int.MaxValue, a.Size - offset))); var bytes = await ReadRange(objects, Tenant(c), a.ObjectId, offset, count, ct); c.Response.StatusCode = 206; c.Response.Headers.ContentRange = $"bytes {offset}-{offset + bytes.Length - 1}/{a.Size}"; c.Response.Headers.AcceptRanges = "bytes"; c.Response.Headers["X-Evidence-SHA256"] = a.Sha256; await s.RecordCustodyAsync(Tenant(c), a.InvestigationId, a.CollectionId, id, Actor(c), "evidence.range.downloaded", "success", "object-storage", "analyst", a.Sha256, $"offset:{offset};bytes:{bytes.Length}", ct); return Results.Bytes(bytes, a.MediaType); }
    static async Task<IResult> Verify(Guid id, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var a = (await s.GetAsync(Tenant(c), ct)).Artifacts.SingleOrDefault(x => x.EvidenceId == id); if (a is null) return Results.NotFound(); EvidenceIntegrityStatus status; string detail; try { var head = await objects.HeadAsync(Tenant(c), a.ObjectId, ct); if (head is null) { status = EvidenceIntegrityStatus.Missing; detail = "Stored object is missing."; } else { await using var stream = await objects.DownloadAsync(Tenant(c), a.ObjectId, ct); var hash = Convert.ToHexString(await SHA256.HashDataAsync(stream, ct)).ToLowerInvariant(); var manifestVerified = true; string manifestDetail = "manifest=not-linked"; if (a.CollectionManifestObjectId is not null && a.CollectionManifestSha256 is not null) { await using var manifest = await objects.DownloadAsync(Tenant(c), a.CollectionManifestObjectId, ct); var manifestHash = Convert.ToHexString(await SHA256.HashDataAsync(manifest, ct)).ToLowerInvariant(); manifestVerified = manifestHash == a.CollectionManifestSha256; manifestDetail = $"manifest={manifestHash}/{a.CollectionManifestSha256}"; } status = hash == a.Sha256 && head.Sha256 == a.Sha256 && head.Size == a.Size && manifestVerified ? EvidenceIntegrityStatus.Verified : EvidenceIntegrityStatus.Mismatch; detail = $"object={hash};metadata={head.Sha256};recorded={a.Sha256};size={head.Size}/{a.Size};{manifestDetail}"; } } catch (Exception ex) when (ex is IOException or InvalidDataException) { status = EvidenceIntegrityStatus.VerificationFailed; detail = ex.GetType().Name; } await s.RecordVerificationAsync(Tenant(c), Actor(c), id, status, detail, ct); return Ok(c, new { evidenceId = id, status, detail, highSeverityEvent = status == EvidenceIntegrityStatus.Mismatch }); }
    static async Task<IResult> Parse(Guid id, ParseRequest x, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); var input = state.Artifacts.SingleOrDefault(a => a.EvidenceId == id); if (input is null) return Results.NotFound(); var parser = ForensicWorkspaceSafety.Parsers.SingleOrDefault(p => p.ParserId == x.ParserId && p.Version == x.ParserVersion && p.EvidenceTypes.Contains(input.EvidenceType)); if (parser is null || parser.Status is "NotValidated" or "CollectionOnly") return Results.Problem(statusCode: 409, title: "Parser unavailable", extensions: new Dictionary<string, object?> { { "code", "PARSER_NOT_VALIDATED" } }); if (input.Size > parser.MaximumInputBytes) return Results.Problem(statusCode: 413, title: "Parser input bound exceeded"); await using var source = await objects.DownloadAsync(Tenant(c), input.ObjectId, ct); using var buffer = new MemoryStream(); await source.CopyToAsync(buffer, ct); var now = DateTimeOffset.UtcNow; var outputBytes = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "derived-forensic-evidence.v1", sourceEvidenceId = input.EvidenceId, sourceSha256 = input.Sha256, parser = parser.ParserId, parserVersion = parser.Version, inputBytes = buffer.Length, parsedRecords = 1, warnings = Array.Empty<string>(), sourceRecordIdentity = "summary:0", createdAt = now }); var hash = Convert.ToHexString(SHA256.HashData(outputBytes)).ToLowerInvariant(); var outputId = Guid.NewGuid(); await using var upload = new MemoryStream(outputBytes, false); await objects.UploadAsync(Tenant(c), outputId.ToString("D"), upload, parser.OutputMediaType, hash, ct); var output = input with { EvidenceId = outputId, Size = outputBytes.Length, BytesTransferred = outputBytes.Length, Chunks = 1, Sha256 = hash, TransferVerified = true, ObjectId = outputId.ToString("D"), MediaType = parser.OutputMediaType, Integrity = EvidenceIntegrityStatus.Verified, ParserId = parser.ParserId, ParserVersion = parser.Version, ParseStatus = EvidenceParseStatus.Complete, ExtractionStatus = "Complete", DerivedFromEvidenceId = input.EvidenceId, SourceRecordIdentity = "summary:0", Tags = [], Bookmarked = false, State = "Derived", FailureCode = null, FailureDetail = null, AcquisitionStartedAt = now, AcquisitionCompletedAt = DateTimeOffset.UtcNow, CreatedAt = DateTimeOffset.UtcNow }; return Ok(c, await s.RecordParserRunAsync(Tenant(c), Actor(c), id, output, parser, 1, [], ct)); }
    static async Task<IResult> Tag(Guid investigation, Guid evidence, TagRequest x, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { await s.TagAsync(Tenant(c), Actor(c), investigation, evidence, x.Tags, ct); return Results.NoContent(); }
    static async Task<IResult> Bookmark(Guid investigation, Guid evidence, BookmarkRequest x, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, await s.BookmarkAsync(Tenant(c), Actor(c), investigation, evidence, x.Purpose, ct));
    static async Task<IResult> Note(Guid investigation, NoteRequest x, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, await s.NoteAsync(Tenant(c), Actor(c), investigation, x.TargetType, x.TargetId, x.Body, x.AiDraft, x.Accepted, x.EvidenceCitations ?? [], ct));
    static async Task<IResult> Notes(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, (await s.GetAsync(Tenant(c), ct)).Notes.Where(x => x.InvestigationId == id).OrderByDescending(x => x.CreatedAt));
    static async Task<IResult> Bookmarks(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, (await s.GetAsync(Tenant(c), ct)).Bookmarks.Where(x => x.InvestigationId == id).OrderByDescending(x => x.CreatedAt));
    static async Task<IResult> Timeline(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var q = c.Request.Query; var state = await s.GetAsync(Tenant(c), ct); var items = state.Timeline.Where(x => x.InvestigationId == id && (!Guid.TryParse(q["endpointId"], out var endpoint) || x.EndpointId == endpoint) && (string.IsNullOrWhiteSpace(q["eventType"]) || x.EventType == q["eventType"]) && (!DateTimeOffset.TryParse(q["from"], out var from) || x.OccurredAt >= from) && (!DateTimeOffset.TryParse(q["to"], out var to) || x.OccurredAt <= to)).OrderByDescending(x => x.OccurredAt).Take(Math.Clamp(int.TryParse(q["limit"], out var n) ? n : 200, 1, 1000)); return Ok(c, items); }
    static async Task<IResult> Entities(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); var evidence = state.Artifacts.Where(x => x.InvestigationId == id).ToArray(); var entities = evidence.SelectMany(x => x.RelatedEntities.Select(e => new { entityId = e, evidenceId = x.EvidenceId, x.EndpointId, x.EvidenceType })).Take(1000).ToArray(); var hashes = evidence.Where(x => x.Integrity != EvidenceIntegrityStatus.Missing).GroupBy(x => x.Sha256).Select(x => new { sha256 = x.Key, endpoints = x.Select(v => v.EndpointId).Distinct().ToArray(), evidence = x.Select(v => v.EvidenceId).ToArray() }).Where(x => x.endpoints.Length > 1).Take(100).ToArray(); return Ok(c, new { entities, crossEndpointHashes = hashes, unsupportedEdgesAdded = 0 }); }
    static async Task<IResult> Custody(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, new { schemaVersion = "technical-chain-of-custody.v2", legalAdmissibilityClaimed = false, events = await s.CustodyAsync(Tenant(c), id, Guid.TryParse(c.Request.Query["evidenceId"], out var e) ? e : null, ct) });
    static async Task<IResult> Hold(Guid id, HoldRequest x, HttpContext c, ForensicWorkspaceService s, ICapacityRetentionRepository retention, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); if (!state.Investigations.Any(v => v.InvestigationId == id)) return Results.NotFound(); var hold = await retention.PutHoldAsync(Tenant(c), Actor(c), new("investigation", "forensic-evidence", id.ToString("D"), x.Reason, x.ExpiresAt), ct); await s.RecordHoldAsync(Tenant(c), Actor(c), id, null, hold.HoldId, x.Reason, ct); return Ok(c, hold); }
    static async Task<IResult> HoldEvidence(Guid investigation, Guid evidence, HoldRequest x, HttpContext c, ForensicWorkspaceService s, ICapacityRetentionRepository retention, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); if (!state.Artifacts.Any(v => v.InvestigationId == investigation && v.EvidenceId == evidence)) return Results.NotFound(); var hold = await retention.PutHoldAsync(Tenant(c), Actor(c), new("forensic", "forensic-evidence", evidence.ToString("D"), x.Reason, x.ExpiresAt), ct); await s.RecordHoldAsync(Tenant(c), Actor(c), investigation, evidence, hold.HoldId, x.Reason, ct); return Ok(c, hold); }
    static async Task<IResult> Holds(Guid id, HttpContext c, ForensicWorkspaceService s, ICapacityRetentionRepository retention, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); var evidence = state.Artifacts.Where(x => x.InvestigationId == id).Select(x => x.EvidenceId.ToString("D")).ToHashSet(StringComparer.OrdinalIgnoreCase); if (!state.Investigations.Any(x => x.InvestigationId == id)) return Results.NotFound(); var values = (await retention.HoldsAsync(Tenant(c), ct)).Where(x => x.Category == "forensic-evidence" && (x.TargetId == id.ToString("D") || x.TargetId is not null && evidence.Contains(x.TargetId))).ToArray(); return Ok(c, values); }
    static async Task<IResult> ReleaseHold(Guid id, Guid hold, HttpContext c, ForensicWorkspaceService s, ICapacityRetentionRepository retention, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); var evidence = state.Artifacts.Where(x => x.InvestigationId == id).ToDictionary(x => x.EvidenceId.ToString("D"), x => x.EvidenceId, StringComparer.OrdinalIgnoreCase); var value = (await retention.HoldsAsync(Tenant(c), ct)).SingleOrDefault(x => x.HoldId == hold && x.Active && x.Category == "forensic-evidence" && (x.TargetId == id.ToString("D") || x.TargetId is not null && evidence.ContainsKey(x.TargetId))); if (value is null) return Results.NotFound(); var released = await retention.ReleaseHoldAsync(Tenant(c), hold, ct); await s.RecordHoldReleaseAsync(Tenant(c), Actor(c), id, value.TargetId is not null && evidence.TryGetValue(value.TargetId, out var evidenceId) ? evidenceId : null, hold, ct); return Ok(c, released); }
    static async Task<IResult> AiSummary(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); if (!state.Investigations.Any(x => x.InvestigationId == id)) return Results.NotFound(); var selected = state.Artifacts.Where(x => x.InvestigationId == id).OrderByDescending(x => x.Bookmarked).ThenByDescending(x => x.RelatedFindings.Length).ThenByDescending(x => x.CreatedAt).Take(20).ToArray(); var citations = selected.Select(x => $"EVID-{x.EvidenceId:D}").ToArray(); var body = selected.Length == 0 ? "Unknown: no authorized evidence is available for analysis." : $"Observed: {selected.Length} bounded evidence item(s) were selected. Strongest items: {string.Join(", ", selected.Take(5).Select(x => $"{x.EvidenceType} [{"EVID-" + x.EvidenceId.ToString("D")}]"))}. Missing or unavailable items remain explicit; this draft does not execute response."; var note = await s.NoteAsync(Tenant(c), "ai:local-evidence", id, "investigation", id.ToString("D"), body, true, false, citations, ct); return Ok(c, new { note, selectedEvidence = selected.Select(x => x.EvidenceId), truncated = state.Artifacts.Count(x => x.InvestigationId == id) > selected.Length, provider = "local-evidence/local-evidence-v1", readOnly = true }); }
    static async Task<IResult> Export(Guid id, ExportRequest x, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct)
    {
        ForensicWorkspaceSafety.Text(x.Reason, "reason", 1024); if (x.EvidenceIds.Length is < 1 or > 64 || x.EvidenceIds.Distinct().Count() != x.EvidenceIds.Length) return Results.BadRequest(); var state = await s.GetAsync(Tenant(c), ct); if (!state.Investigations.Any(v => v.InvestigationId == id)) return Results.NotFound(); var found = state.Artifacts.Where(a => a.InvestigationId == id && x.EvidenceIds.Contains(a.EvidenceId)).ToDictionary(a => a.EvidenceId); var unavailable = x.EvidenceIds.Where(e => !found.TryGetValue(e, out var a) || a.Integrity == EvidenceIntegrityStatus.Missing || a.ObjectId.StartsWith("unavailable:", StringComparison.Ordinal)).ToArray(); var candidates = found.Values.Where(a => !unavailable.Contains(a.EvidenceId)).ToArray(); var included = new List<Guid>(); var excluded = new List<Guid>(); long selectedBytes = 0; using var package = new MemoryStream(); using (var zip = new ZipArchive(package, ZipArchiveMode.Create, true)) { foreach (var a in candidates) { if (selectedBytes + a.Size > ForensicWorkspaceSafety.MaximumPackageBytes) { excluded.Add(a.EvidenceId); continue; } try { var entry = zip.CreateEntry($"evidence/{a.EvidenceId:D}", CompressionLevel.NoCompression); await using var destination = entry.Open(); await using var source = await objects.DownloadAsync(Tenant(c), a.ObjectId, ct); await source.CopyToAsync(destination, ct); included.Add(a.EvidenceId); selectedBytes += a.Size; } catch (IOException) { excluded.Add(a.EvidenceId); } } var meta = zip.CreateEntry("investigation.json"); await using var ms = meta.Open(); await JsonSerializer.SerializeAsync(ms, new { investigation = state.Investigations.Single(v => v.InvestigationId == id), bookmarks = state.Bookmarks.Where(v => v.InvestigationId == id), acceptedNotes = state.Notes.Where(v => v.InvestigationId == id && v.Accepted), custody = state.Custody.Where(v => v.InvestigationId == id), reason = x.Reason }, Json, ct); }
        var packageBytes = package.ToArray(); var packageHash = Convert.ToHexString(SHA256.HashData(packageBytes)).ToLowerInvariant(); var exportId = Guid.NewGuid(); var packageObject = exportId.ToString("D"); var manifestId = Guid.NewGuid().ToString("D"); var manifestBytes = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "investigation-evidence-package.v1", packageId = exportId, tenantId = Tenant(c), investigationId = id, requested = x.EvidenceIds, included, excluded, failed = Array.Empty<Guid>(), unavailable, hashes = included.Select(e => new { evidenceId = e, sha256 = found[e].Sha256 }), exportTimestamp = DateTimeOffset.UtcNow, requestedBy = Actor(c), packageSha256 = packageHash, packageBytes = packageBytes.LongLength }, Json); var manifestHash = Convert.ToHexString(SHA256.HashData(manifestBytes)).ToLowerInvariant(); await using (var p = new MemoryStream(packageBytes, false)) await objects.UploadAsync(Tenant(c), packageObject, p, "application/zip", packageHash, ct); await using (var m = new MemoryStream(manifestBytes, false)) await objects.UploadAsync(Tenant(c), manifestId, m, "application/json", manifestHash, ct); var export = new EvidenceExport(exportId, Tenant(c), id, x.EvidenceIds, included.ToArray(), excluded.ToArray(), [], unavailable, packageObject, manifestId, packageHash, manifestHash, packageBytes.LongLength, Actor(c), DateTimeOffset.UtcNow, "Complete"); return Results.Created($"/api/v1/forensics/exports/{exportId:D}/manifest", new ApiEnvelope<object>(await s.RecordExportAsync(Tenant(c), export, ct), new(c.TraceIdentifier, "1.0")));
    }
    static async Task<IResult> Exports(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) => Ok(c, (await s.GetAsync(Tenant(c), ct)).Exports.Where(x => x.InvestigationId == id).OrderByDescending(x => x.CreatedAt));
    static async Task<(EvidenceExport? Export, ForensicWorkspaceState State)> FindExport(Guid id, HttpContext c, ForensicWorkspaceService s, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); return (state.Exports.SingleOrDefault(x => x.ExportId == id), state); }
    static async Task<IResult> ExportManifest(Guid id, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var (e, _) = await FindExport(id, c, s, ct); if (e is null) return Results.NotFound(); await s.RecordCustodyAsync(Tenant(c), e.InvestigationId, null, null, Actor(c), "evidence.export.manifest.downloaded", "success", "object-storage", "analyst", e.ManifestSha256, $"export:{id:D}", ct); return Results.Stream(await objects.DownloadAsync(Tenant(c), e.ManifestObjectId, ct), "application/json", enableRangeProcessing: true); }
    static async Task<IResult> ExportDownload(Guid id, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var (e, _) = await FindExport(id, c, s, ct); if (e is null) return Results.NotFound(); await s.RecordCustodyAsync(Tenant(c), e.InvestigationId, null, null, Actor(c), "evidence.export.downloaded", "success", "object-storage", "analyst", e.PackageSha256, $"export:{id:D}", ct); return Results.Stream(await objects.DownloadAsync(Tenant(c), e.ObjectId, ct), "application/zip", fileDownloadName: $"investigation-{e.InvestigationId:D}.zip", enableRangeProcessing: true); }
    static async Task<IResult> ExportRange(Guid id, long offset, int? length, HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, CancellationToken ct) { var (e, _) = await FindExport(id, c, s, ct); if (e is null || offset < 0 || offset >= e.PackageBytes) return Results.NotFound(); var count = Math.Min(Math.Clamp(length ?? 8 * 1024 * 1024, 1, 8 * 1024 * 1024), checked((int)Math.Min(int.MaxValue, e.PackageBytes - offset))); var bytes = await ReadRange(objects, Tenant(c), e.ObjectId, offset, count, ct); c.Response.StatusCode = 206; c.Response.Headers.ContentRange = $"bytes {offset}-{offset + bytes.Length - 1}/{e.PackageBytes}"; c.Response.Headers.AcceptRanges = "bytes"; c.Response.Headers["X-Package-SHA256"] = e.PackageSha256; await s.RecordCustodyAsync(Tenant(c), e.InvestigationId, null, null, Actor(c), "evidence.export.range.downloaded", "success", "object-storage", "analyst", e.PackageSha256, $"export:{id:D};offset:{offset};bytes:{bytes.Length}", ct); return Results.Bytes(bytes, "application/zip"); }
    static async Task<byte[]> ReadRange(IObjectStorage objects, string tenant, string objectId, long offset, int count, CancellationToken ct) { await using var stream = await objects.DownloadAsync(tenant, objectId, ct); var remaining = offset; var discard = new byte[81920]; while (remaining > 0) { var read = await stream.ReadAsync(discard.AsMemory(0, (int)Math.Min(discard.Length, remaining)), ct); if (read == 0) throw new EndOfStreamException(); remaining -= read; } var output = new byte[count]; var position = 0; while (position < count) { var read = await stream.ReadAsync(output.AsMemory(position, count - position), ct); if (read == 0) break; position += read; } return position == count ? output : output[..position]; }
    static async Task<IResult> ToolLibrary(HttpContext c, ToolPackageStore tools, CancellationToken ct) { var items = (await tools.ListAsync(Tenant(c), ct)).Select(x => new { x.PackageId, x.Name, x.Version, publisher = x.ExpectedSignerThumbprint is null ? "Not recorded" : "Signer thumbprint recorded", x.Sha256, signatureState = x.ExpectedSignerThumbprint is not null ? "ExpectedSignerRecorded" : x.AllowUnsigned ? "UnsignedExceptionRecorded" : "Unknown", approvedAcquisitionTypes = Array.Empty<string>(), supportedOs = Array.Empty<string>(), supportedArchitecture = Array.Empty<string>(), stagedState = x.State, validationStatus = "PackageHashValidated; execution capability not registered by library", expiresAt = (DateTimeOffset?)null, revokedAt = x.RevokedAt, securityScanState = "NotRecorded", lastUse = (DateTimeOffset?)null, executionAuthorized = false }); return Ok(c, new { items, freeFormExecution = false, boundary = "Staging is not execution authorization; a registered exact-hash acquisition action remains required." }); }
    static async Task<IResult> Readiness(Guid id, HttpContext c, IEndpointRepository endpoints, IResponseActionRepository responses, ToolPackageStore tools, IObjectStorage objects, CancellationToken ct) { var endpoint = await endpoints.GetEndpointAsync(Tenant(c), id, ct); if (endpoint is null) return Results.NotFound(); var page = await responses.SearchAsync(Tenant(c), id, null, 100, null, ct); var active = page.Items.Count(x => x.ActionType == ForensicCollectionSafety.ActionType && !ResponseSafety.IsTerminal(x.State)); var packages = await tools.ListAsync(Tenant(c), ct); return Ok(c, new { endpointId = id, online = endpoint.LastSeenAt > DateTimeOffset.UtcNow.AddMinutes(-5), endpoint.Status, endpoint.AgentVersion, endpoint.Architecture, diskAvailability = "NotReported", transferReady = await objects.HealthAsync(ct), approvedToolReady = packages.Any(x => x.State == "approved"), approvedTools = packages.Count(x => x.State == "approved"), isolationState = "Query endpoint isolation workspace for authoritative state", selfProtectionState = "Query protection status for authoritative state", currentCollectionWorkload = active, requiredPrivileges = "Profile-dependent", capabilities = endpoint.Capabilities, forensicChannelAvailable = endpoint.Status is EndpointStatus.Online or EndpointStatus.Stale or EndpointStatus.Recovered }); }
    static async Task<IResult> Health(HttpContext c, ForensicWorkspaceService s, IObjectStorage objects, ICapacityRetentionRepository retention, CancellationToken ct) { var state = await s.GetAsync(Tenant(c), ct); var holds = await retention.HoldsAsync(Tenant(c), ct); return Ok(c, new { investigationsOpen = state.Investigations.Count(x => x.Status is not (InvestigationStatus.Closed or InvestigationStatus.Archived)), collectionsRunning = state.Collections.Count(x => x.State is "Running" or "Transferring" or "Verifying" or "Parsing"), collectionsComplete = state.Collections.Count(x => x.State is "Complete" or "Succeeded"), collectionsPartial = state.Collections.Count(x => x.State == "Partial"), collectionsFailed = state.Collections.Count(x => x.State == "Failed"), artifactsAcquired = state.Artifacts.Count(x => x.Integrity != EvidenceIntegrityStatus.Missing), bytesAcquired = state.Artifacts.Sum(x => x.Size), bytesTransferred = state.Artifacts.Sum(x => x.BytesTransferred), hashVerificationFailures = state.Artifacts.Count(x => x.Integrity == EvidenceIntegrityStatus.Mismatch), parserFailures = state.ParserRuns.Count(x => x.Status == EvidenceParseStatus.Failed), activeTransfers = state.Collections.Count(x => x.State == "Transferring"), transferThroughput = "measured by artifact transfer service", heldEvidence = holds.Count(x => x.Active && x.Category == "forensic-evidence"), exports = state.Exports.Length, exportFailures = state.Exports.Count(x => x.State != "Complete"), objectStorageHealthy = await objects.HealthAsync(ct), metricLabelsContainEvidenceIds = false }); }
}
