using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;
sealed class PersistenceExportWorker(IPersistenceExportRepository jobs, IPersistenceTelemetryRepository telemetry, IObjectStorage objects, ILogger<PersistenceExportWorker> log) : BackgroundService
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    protected override async Task ExecuteAsync(CancellationToken ct) { while (!ct.IsCancellationRequested) { foreach (var expired in await jobs.ExpireDueAsync(ct)) foreach (var id in new[] { expired.OutputObjectId, expired.ManifestObjectId, expired.MetadataObjectId }) try { await objects.DeleteAsync(expired.TenantId, id.ToString("D"), ct); } catch (IOException) { } var job = await jobs.ClaimAsync(ct); if (job is null) { await Task.Delay(250, ct); continue; } try { var page = await telemetry.SearchAsync(job.TenantId, job.Query with { Cursor = null, PageSize = Math.Clamp(job.MaximumRecords, 1, 10000) }, ct); var values = page.Items.Take(job.MaximumRecords).ToArray(); var output = job.Format == "csv" ? Csv(values) : Encoding.UTF8.GetBytes(string.Join('\n', values.Select(x => JsonSerializer.Serialize(x, Json))) + '\n'); var hash = Convert.ToHexString(SHA256.HashData(output)).ToLowerInvariant(); var at = DateTimeOffset.UtcNow; var manifest = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "persistence-export-manifest.v1", exportId = job.Id, tenantBinding = job.TenantId, job.Format, recordCount = values.Length, job.Query, job.Fields, sha256 = hash, eventSchemaVersion = "persistence-event.v1", job.OutputObjectId, job.MetadataObjectId, completedAt = at }, Json); var metadata = JsonSerializer.SerializeToUtf8Bytes(new { schemaVersion = "persistence-export-metadata.v1", exportId = job.Id, job.Query, job.Fields, job.CreatedAt, job.ExpiresAt, outputSha256 = hash }, Json); await Put(job, job.OutputObjectId, output, job.Format == "csv" ? "text/csv" : "application/x-ndjson", ct); await Put(job, job.ManifestObjectId, manifest, "application/json", ct); await Put(job, job.MetadataObjectId, metadata, "application/json", ct); await jobs.CompleteAsync(job.Id, values.Length, output.Length, hash, at, ct); } catch (Exception exception) when (exception is not OperationCanceledException) { log.LogError(exception, "Persistence export failed"); await jobs.FailAsync(job.Id, "EXPORT_FAILED", exception.GetType().Name, ct); } } }
    async Task Put(PersistenceExportJob job, Guid id, byte[] bytes, string media, CancellationToken ct) { await using var stream = new MemoryStream(bytes); await objects.UploadAsync(job.TenantId, id.ToString("D"), stream, media, Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), ct); }
    static byte[] Csv(IEnumerable<PersistenceObservation> values) { static string Cell(string? value) { var text = value ?? ""; if (text.Length > 0 && "=+-@\t\r".Contains(text[0])) text = "'" + text; return '"' + text.Replace("\"", "\"\"") + '"'; } var result = new StringBuilder("eventId,endpointId,observedAt,objectKind,eventType,name,path,account,process,collector,quality\n"); foreach (var value in values) result.AppendLine(string.Join(',', Cell(value.EventId.ToString()), Cell(value.EndpointId.ToString()), Cell(value.ObservedAt.ToString("O")), Cell(value.ObjectKind.ToString()), Cell(value.Kind.ToString()), Cell(value.Service?.Name ?? value.ScheduledTask?.Name), Cell(value.Service?.BinaryPath ?? value.ScheduledTask?.Path), Cell(value.Service?.Account ?? value.ScheduledTask?.Principal), Cell(value.Service?.Process?.ProcessEntityId ?? value.ScheduledTask?.Process?.ProcessEntityId), Cell(value.CollectorSource), Cell(string.Join(';', value.DataQualityFlags)))); return Encoding.UTF8.GetBytes(result.ToString()); }
}
