using OpenSecurityPlatform.Foundation;

static class PlaybookRoutes
{
    sealed record StateRequest(PlaybookState State);
    sealed record ReasonRequest(string Reason);
    sealed record TestsRequest(PlaybookFixtureResult[] Results);
    static string Tenant(HttpContext c) => c.Items["tenant"]!.ToString()!;
    static string Actor(HttpContext c) => ((PrincipalContext)c.Items["principal"]!).Subject;
    static IResult Ok<T>(HttpContext c, T value) => Results.Ok(new ApiEnvelope<T>(value, new(c.TraceIdentifier, "1.0")));
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/playbooks/actions", (HttpContext c) => Ok(c, ResponseSafety.Definitions.Values.OrderBy(x => x.ActionType).Select(x => new { x.ActionType, x.ActionVersion, risk = PlaybookSafety.Actions[x.ActionType], x.ApprovalRequired, x.Reversible, x.Idempotency, x.RequiredPermission }).ToArray())).RequirePermission("response:read");
        app.MapGet("/api/v1/playbooks", async (HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.ListAsync(Tenant(c), ct))).RequirePermission("response:read");
        app.MapGet("/api/v1/playbooks/{id:guid}/versions/{version:int}", async (Guid id, int version, HttpContext c, IPlaybookRepository r, CancellationToken ct) => await r.GetAsync(Tenant(c), id, version, ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("response:read");
        app.MapPost("/api/v1/playbooks", async (PlaybookDefinition input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Results.Created("/api/v1/playbooks", new ApiEnvelope<object>(await r.PutAsync(Tenant(c), Actor(c), input, false, ct), new(c.TraceIdentifier, "1.0")))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbooks/{id:guid}/versions", async (Guid id, PlaybookDefinition input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.PutAsync(Tenant(c), Actor(c), input with { PlaybookId = id }, true, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbooks:validate", async (PlaybookDefinition input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.ValidateAsync(Tenant(c), input, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbooks/{id:guid}/versions/{version:int}/tests", async (Guid id, int version, TestsRequest input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.RecordTestsAsync(Tenant(c), id, version, input.Results, Actor(c), ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbooks/{id:guid}/versions/{version:int}/state", async (Guid id, int version, StateRequest input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.SetStateAsync(Tenant(c), id, version, input.State, Actor(c), ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/playbook-executions", async (HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.ExecutionsAsync(Tenant(c), c.Request.Query["sourceType"].FirstOrDefault(), c.Request.Query["sourceObjectId"].FirstOrDefault(), ct))).RequirePermission("response:read");
        app.MapGet("/api/v1/playbook-executions/{id:guid}", async (Guid id, HttpContext c, IPlaybookRepository r, CancellationToken ct) => await r.GetExecutionAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("response:read");
        app.MapPost("/api/v1/playbook-executions", async (PlaybookStartRequest input, HttpContext c, IPlaybookRepository r, IPlaybookActionExecutor e, CancellationToken ct) => Results.Created("/api/v1/playbook-executions", new ApiEnvelope<object>(await r.StartAsync(Tenant(c), Actor(c), input, e, ct), new(c.TraceIdentifier, "1.0")))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbook-executions/{id:guid}:advance", async (Guid id, HttpContext c, IPlaybookRepository r, IPlaybookActionExecutor e, CancellationToken ct) => Ok(c, await r.AdvanceAsync(Tenant(c), id, e, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbook-executions/{id:guid}:approve", async (Guid id, PlaybookApprovalRequest input, HttpContext c, IPlaybookRepository r, IPlaybookActionExecutor e, CancellationToken ct) => Ok(c, await r.ApproveAsync(Tenant(c), id, Actor(c), input, e, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbook-executions/{id:guid}:deny", async (Guid id, PlaybookApprovalRequest input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.DenyAsync(Tenant(c), id, Actor(c), input, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbook-executions/{id:guid}:decide", async (Guid id, PlaybookDecisionRequest input, HttpContext c, IPlaybookRepository r, IPlaybookActionExecutor e, CancellationToken ct) => Ok(c, await r.DecideAsync(Tenant(c), id, Actor(c), input, e, ct))).RequirePermission("platform:admin");
        app.MapPost("/api/v1/playbook-executions/{id:guid}:cancel", async (Guid id, ReasonRequest input, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.CancelAsync(Tenant(c), id, Actor(c), input.Reason, ct))).RequirePermission("platform:admin");
        app.MapGet("/api/v1/playbook-approvals", async (HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, (await r.ExecutionsAsync(Tenant(c), null, null, ct)).Where(x => x.State == PlaybookExecutionState.WaitingForApproval))).RequirePermission("response:read");
        app.MapGet("/api/v1/playbook-health", async (HttpContext c, IPlaybookRepository r, CancellationToken ct) => Ok(c, await r.HealthAsync(Tenant(c), ct))).RequirePermission("response:read");
        app.MapGet("/api/v1/alerts/{id:guid}/playbooks", (Guid id, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Context("alert", id.ToString("D"), c, r, ct)).RequirePermission("response:read");
        app.MapGet("/api/v1/incidents/{id:guid}/playbooks", (Guid id, HttpContext c, IPlaybookRepository r, CancellationToken ct) => Context("incident", id.ToString("D"), c, r, ct)).RequirePermission("response:read");
        app.MapPost("/internal/v1/playbooks/self-test", SelfTest).RequirePermission("platform:admin");
    }
    static async Task<IResult> Context(string source, string id, HttpContext c, IPlaybookRepository r, CancellationToken ct) { var definitions = await r.ListAsync(Tenant(c), ct); var executions = await r.ExecutionsAsync(Tenant(c), source, id, ct); return Ok(c, new { recommended = definitions.Where(x => x.State == PlaybookState.Active && x.SupportedSourceTypes.Contains(source, StringComparer.OrdinalIgnoreCase)), executions, pendingApprovals = executions.Where(x => x.State == PlaybookExecutionState.WaitingForApproval) }); }
    static async Task<IResult> SelfTest(HttpContext c, IPlaybookRepository production, CancellationToken ct)
    {
        var tenant = Tenant(c); var actor = Actor(c); foreach (var seed in PlaybookStarterPack.Create(tenant, actor)) { if (await production.GetAsync(tenant, seed.PlaybookId, 1, ct) is null) { var added = await production.PutAsync(tenant, actor, seed, false, ct); await production.RecordTestsAsync(tenant, added.PlaybookId, added.Version, PlaybookStarterPack.PassingFixtures(), actor, ct); await production.SetStateAsync(tenant, added.PlaybookId, added.Version, PlaybookState.Active, actor, ct); } }
        using var repo = new FilePlaybookRepository(); var pack = PlaybookStarterPack.Create(tenant, "requester"); foreach (var seed in pack) { var added = await repo.PutAsync(tenant, "requester", seed, false, ct); await repo.RecordTestsAsync(tenant, added.PlaybookId, 1, PlaybookStarterPack.PassingFixtures(), "requester", ct); await repo.SetStateAsync(tenant, added.PlaybookId, 1, PlaybookState.Active, "requester", ct); }
        PlaybookStartRequest Start(PlaybookDefinition p, string key, PlaybookMode mode = PlaybookMode.ApprovalGated, string install = "installation-a") => new(p.PlaybookId, 1, p.Triggers[0].Type, p.SupportedSourceTypes[0], key, Guid.NewGuid(), "stable-target", install, mode, key, new Dictionary<string, string?> { ["quality"] = "complete", ["iocValid"] = "true" });
        var triageExecutor = new ControlledPlaybookActionExecutor(); var a = await repo.StartAsync(tenant, "requester", Start(pack[0], "profile-a", PlaybookMode.SafeAutomatic), triageExecutor, ct);
        var bExecutor = new ControlledPlaybookActionExecutor(); var b = await repo.StartAsync(tenant, "requester", Start(pack[1], "profile-b"), bExecutor, ct); var bs = b.Steps.Single(x => x.State == PlaybookStepState.WaitingForApproval); b = await repo.ApproveAsync(tenant, b.ExecutionId, "approver", new(bs.StepId, bs.InputHash, "controlled approval"), bExecutor, ct);
        var cExecutor = new ControlledPlaybookActionExecutor(); var denied = await repo.StartAsync(tenant, "requester", Start(pack[1], "profile-c"), cExecutor, ct); var cs = denied.Steps.Single(x => x.State == PlaybookStepState.WaitingForApproval); denied = await repo.DenyAsync(tenant, denied.ExecutionId, "approver", new(cs.StepId, cs.InputHash, "controlled denial"), ct);
        var dSeed = pack[1] with { PlaybookId = Guid.NewGuid(), Steps = pack[1].Steps.Select(s => s.StepId == "quarantine" ? s with { Retry = new(2), FailureNext = "safe-recovery" } : s).Concat([new PlaybookStep("safe-recovery", PlaybookStepType.InternalNotification, "safe recovery", [], new Dictionary<string, string?>())]).ToArray(), VersionHash = "" }; dSeed = dSeed with { VersionHash = PlaybookSafety.DefinitionHash(dSeed) }; var dBook = await repo.PutAsync(tenant, "requester", dSeed, false, ct); await repo.RecordTestsAsync(tenant, dBook.PlaybookId, 1, PlaybookStarterPack.PassingFixtures(), "requester", ct); dBook = await repo.SetStateAsync(tenant, dBook.PlaybookId, 1, PlaybookState.Active, "requester", ct);
        var dExecutor = new ControlledPlaybookActionExecutor("failure"); var failed = await repo.StartAsync(tenant, "requester", Start(dBook, "profile-d"), dExecutor, ct); var ds = failed.Steps.Single(x => x.State == PlaybookStepState.WaitingForApproval); failed = await repo.ApproveAsync(tenant, failed.ExecutionId, "approver", new(ds.StepId, ds.InputHash, "controlled failure"), dExecutor, ct); failed = await repo.AdvanceAsync(tenant, failed.ExecutionId, dExecutor, ct); failed = await repo.AdvanceAsync(tenant, failed.ExecutionId, dExecutor, ct);
        var simulationExecutor = new ControlledPlaybookActionExecutor(); var first = await repo.StartAsync(tenant, "requester", Start(pack[1], "profile-e", PlaybookMode.Simulation), simulationExecutor, ct); var duplicate = await repo.StartAsync(tenant, "requester", Start(pack[1], "profile-e", PlaybookMode.Simulation), simulationExecutor, ct);
        var raceExecutor = new ControlledPlaybookActionExecutor("success", "replacement-installation"); var race = await repo.StartAsync(tenant, "requester", Start(pack[1], "profile-f"), raceExecutor, ct); var fs = race.Steps.Single(x => x.State == PlaybookStepState.WaitingForApproval); race = await repo.ApproveAsync(tenant, race.ExecutionId, "approver", new(fs.StepId, fs.InputHash, "controlled identity race"), raceExecutor, ct);
        var bad = pack[0] with { PlaybookId = Guid.NewGuid(), Steps = [new("shell", PlaybookStepType.StructuredResponse, "shell", [], new Dictionary<string, string?> { ["actionType"] = "powershell" }, Approval: new(true, true))], VersionHash = "" }; bad = bad with { VersionHash = PlaybookSafety.DefinitionHash(bad) }; var security = PlaybookSafety.Validate(bad);
        var profiles = new { A = a.State == PlaybookExecutionState.WaitingForApproval && triageExecutor.MutationCalls == 0, B = b.State == PlaybookExecutionState.Succeeded && bExecutor.MutationCalls == 1, C = denied.State == PlaybookExecutionState.Cancelled && cExecutor.MutationCalls == 0, D = failed.State == PlaybookExecutionState.Partial && failed.Steps.Single(x => x.StepId == "safe-recovery").State == PlaybookStepState.Succeeded && failed.AuditHistory.Any(x => x.Action == "playbook.failure-branch.selected"), E = first.ExecutionId == duplicate.ExecutionId && simulationExecutor.MutationCalls == 0, F = race.State == PlaybookExecutionState.Failed && race.Result == "TARGET_IDENTITY_MISMATCH" && raceExecutor.MutationCalls == 0 }; var passed = profiles.A && profiles.B && profiles.C && profiles.D && profiles.E && profiles.F && security.ContainsKey("action.shell"); return Ok(c, new { profiles, security = new { arbitraryCodeRejected = security.ContainsKey("action.shell"), liveResponsePrimitiveAbsent = !PlaybookSafety.Actions.Keys.Any(x => x.Contains("live", StringComparison.OrdinalIgnoreCase)), recursionDepth = 0, simulationMutations = simulationExecutor.MutationCalls }, starterPlaybooks = pack.Select(x => x.Name), passed });
    }
}
