using System.Text;
using OpenSecurityPlatform.Foundation;

static class ThreatIntelligenceRoutes
{
    sealed record IndicatorStateRequest(bool? Revoked, DateTimeOffset? ValidUntil);
    sealed record BackmatchRequest(Guid IndicatorId, int Version, DateTimeOffset From,
        DateTimeOffset To, ThreatMatchMode Mode = ThreatMatchMode.Simulation);

    public static void Map(WebApplication app)
    {
        app.MapGet("/api/v1/intelligence/sources", async (HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Ok(c, await r.SourcesAsync(Tenant(c), ct))).RequirePermission("intelligence:read");
        app.MapPost("/api/v1/intelligence/sources", async (IntelligenceSource x, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Results.Created("/api/v1/intelligence/sources", Envelope(c, await r.CreateSourceAsync(Tenant(c), x, Actor(c), ct)))).RequirePermission("intelligence:write");
        app.MapGet("/api/v1/intelligence/indicators", async (ThreatIndicatorType? type, string? query, Guid? sourceId, bool? active, int? pageSize, string? cursor, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Ok(c, await r.SearchAsync(Tenant(c), new(type, query, sourceId, active, pageSize ?? 100, cursor), ct))).RequirePermission("intelligence:read");
        app.MapGet("/api/v1/intelligence/indicators/{id:guid}", async (Guid id, int? version, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => await r.GetAsync(Tenant(c), id, version, ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("intelligence:read");
        app.MapPost("/api/v1/intelligence/indicators", async (ThreatIndicatorInput x, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => { var value = await r.AddAsync(Tenant(c), x, Actor(c), ct); return Results.Created($"/api/v1/intelligence/indicators/{value.IndicatorId:D}?version={value.Version}", Envelope(c, value)); }).RequirePermission("intelligence:write");
        app.MapPost("/api/v1/intelligence/indicators/{id:guid}/state", async (Guid id, IndicatorStateRequest x, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Ok(c, await r.SetStateAsync(Tenant(c), id, x.Revoked, x.ValidUntil, Actor(c), ct))).RequirePermission("intelligence:write");
        app.MapPost("/api/v1/intelligence/sources/{sourceId:guid}/imports", Import).RequirePermission("intelligence:import");
        app.MapGet("/api/v1/intelligence/matches", async (Guid? indicatorId, Guid? endpointId, Guid? evidenceEventId, ThreatMatchMode? mode, int? pageSize, string? cursor, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Ok(c, await r.SearchMatchesAsync(Tenant(c), new(indicatorId, endpointId, evidenceEventId, mode, pageSize ?? 100, cursor), ct))).RequirePermission("intelligence:read");
        app.MapPost("/api/v1/intelligence/exclusions", async (ThreatExclusion x, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Results.Created("/api/v1/intelligence/exclusions", Envelope(c, await r.AddExclusionAsync(Tenant(c), x, Actor(c), ct)))).RequirePermission("intelligence:write");
        app.MapGet("/api/v1/intelligence/exclusions", async (HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Ok(c, await r.ExclusionsAsync(Tenant(c), ct))).RequirePermission("intelligence:read");
        app.MapPost("/api/v1/intelligence/backmatches", async (BackmatchRequest x, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => { var job = await r.QueueBackmatchAsync(Tenant(c), x.IndicatorId, x.Version, x.From, x.To, x.Mode, Actor(c), ct); return Results.Accepted($"/api/v1/intelligence/backmatches/{job.JobId:D}", Envelope(c, job)); }).RequirePermission("intelligence:hunt");
        app.MapGet("/api/v1/intelligence/backmatches/{id:guid}", async (Guid id, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => await r.GetJobAsync(Tenant(c), id, ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("intelligence:read");
        app.MapPost("/api/v1/intelligence/backmatches/{id:guid}/cancel", async (Guid id, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => await r.CancelJobAsync(Tenant(c), id, Actor(c), ct) is { } x ? Ok(c, x) : Results.NotFound()).RequirePermission("intelligence:hunt");
        app.MapGet("/api/v1/intelligence/health", async (HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct) => Ok(c, await r.HealthAsync(Tenant(c), ct))).RequirePermission("intelligence:read");
        app.MapGet("/api/v1/intelligence/reconciliation", async (HttpContext c, IThreatIntelligenceRepository r, IThreatIntelligenceProjection p, CancellationToken ct) => { var authoritative = await r.CountsAsync(Tenant(c), ct); var projected = await p.CountsAsync(Tenant(c), ct); return Ok(c, new { postgres = new { indicators = authoritative.IndicatorVersions, matches = authoritative.Matches }, openSearch = new { indicators = projected.Indicators, matches = projected.Matches }, exact = authoritative.IndicatorVersions == projected.Indicators && authoritative.Matches == projected.Matches }); }).RequirePermission("system:admin");
        app.MapPost("/internal/v1/intelligence/self-test", SelfTest).RequirePermission("system:admin");
    }

    static async Task<IResult> Import(Guid sourceId, HttpRequest request, HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct)
    {
        if (!request.HasFormContentType) return Problem(c, "INTEL_IMPORT_CONTENT_TYPE", "Multipart form data is required."); var form = await request.ReadFormAsync(ct); var file = form.Files.GetFile("file"); if (file is null) return Problem(c, "INTEL_IMPORT_FILE", "Import file is required."); if (file.Length > ThreatIntelligenceSafety.MaximumImportBytes) return Problem(c, "INTEL_IMPORT_TOO_LARGE", "Import exceeds 5 MiB."); var format = form["format"].ToString(); await using var stream = file.OpenReadStream(); return Ok(c, await r.ImportAsync(Tenant(c), sourceId, format, stream, Actor(c), ct));
    }
    static async Task<IResult> SelfTest(HttpContext c, IThreatIntelligenceRepository r, CancellationToken ct)
    {
        var tenant = Tenant(c); var key = Guid.NewGuid().ToString("N"); var source = await r.CreateSourceAsync(tenant, new(Guid.Empty, tenant, $"Sprint23 controlled {key}", IntelligenceSourceType.Manual, 90, 80, true, false, null, null, 60, "controlled", "TLP:CLEAR", null, default, default), "system:sprint23", ct);
        var hash = new string('a', 64); var indicator = await r.AddAsync(tenant, new(source.SourceId, ThreatIndicatorType.Sha256, hash, SourceRecordId: $"controlled-{key}", SourceVersion: "1", Provenance: "sprint23-profile-a"), "system:sprint23", ct); var eventId = ThreatIntelligenceSafety.StableId(tenant, key, "event"); var endpoint = ThreatIntelligenceSafety.StableId(tenant, key, "endpoint"); var evidence = new ThreatEvidence(eventId, endpoint, $"process-{key}", $"file-{key}", DateTimeOffset.UtcNow, ThreatIndicatorType.Sha256, "file.hash", hash, $"postgresql://platform/sprint23_controlled/{eventId:D}", ["controlled"]); var first = await r.MatchAsync(tenant, [evidence], ThreatMatchMode.Live, ct); var second = await r.MatchAsync(tenant, [evidence], ThreatMatchMode.Live, ct);
        var domain = await r.AddAsync(tenant, new(source.SourceId, ThreatIndicatorType.Domain, $"Bad.{key}.Example.", Provenance: "sprint23-profile-b"), "system:sprint23", ct); var domainEvidence = evidence with { EventId = ThreatIntelligenceSafety.StableId(tenant, key, "dns"), Type = ThreatIndicatorType.Domain, Field = "dns.query", Value = $"bad.{key}.example", EvidenceReference = $"postgresql://platform/sprint23_controlled/{key}/dns" }; var domainMatches = await r.MatchAsync(tenant, [domainEvidence], ThreatMatchMode.Live, ct);
        await r.SetStateAsync(tenant, domain.IndicatorId, true, DateTimeOffset.UtcNow, "system:sprint23", ct); var afterRevocation = await r.MatchAsync(tenant, [domainEvidence with { EventId = Guid.NewGuid() }], ThreatMatchMode.Live, ct);
        var csv = Encoding.UTF8.GetBytes($"type,value\nIPv4,192.0.2.23\nSha256,{hash}\n"); await using var csvStream = new MemoryStream(csv); var imported = await r.ImportAsync(tenant, source.SourceId, "csv", csvStream, "system:sprint23", ct); var from = DateTimeOffset.UtcNow.AddMinutes(-10); var to = DateTimeOffset.UtcNow; var job1 = await r.QueueBackmatchAsync(tenant, indicator.IndicatorId, indicator.Version, from, to, ThreatMatchMode.Simulation, "system:sprint23", ct); var job2 = await r.QueueBackmatchAsync(tenant, indicator.IndicatorId, indicator.Version, from, to, ThreatMatchMode.Simulation, "system:sprint23", ct);
        return Ok(c, new { runKey = key, profiles = new { A = first.Count == 1 && first[0].EvidenceEventId == eventId && second.Single().MatchId == first[0].MatchId, B = domainMatches.Count == 1, C = afterRevocation.Count == 0, D = imported.Read == 2 && imported.Rejected == 0, E = job1.JobId == job2.JobId, F = second.Count == 1 }, exactEvidence = first.Single().EvidenceReference, exactIndicatorVersion = first.Single().IndicatorVersion, noAutomaticResponse = true });
    }
    static string Tenant(HttpContext c) => c.Items["tenant"]?.ToString() ?? throw new UnauthorizedAccessException();
    static string Actor(HttpContext c) => c.User.Identity?.Name ?? "unknown";
    static ApiEnvelope<T> Envelope<T>(HttpContext c, T data) => new(data, new(c.TraceIdentifier, "1.0"));
    static IResult Ok<T>(HttpContext c, T data) => Results.Ok(Envelope(c, data));
    static IResult Problem(HttpContext c, string code, string detail) => Results.Problem(statusCode: 400, title: code, detail: detail, extensions: new Dictionary<string, object?> { ["traceId"] = c.TraceIdentifier });
}
