param([int]$Iterations=30)
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;Set-Location $root
$settings=@{};Get-Content .env|Where-Object{$_ -match '^[^#].*='}|ForEach-Object{$p=$_.Split('=',2);$settings[$p[0]]=$p[1]}
$login=Invoke-RestMethod -Method Post -Uri http://localhost:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$settings.PLATFORM_BOOTSTRAP_USER;password=$settings.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json);$headers=@{Authorization="Bearer $($login.access_token)"}
function Measure-Request($script){$values=1..$Iterations|ForEach-Object{$sw=[Diagnostics.Stopwatch]::StartNew();&$script|Out-Null;$sw.Stop();$sw.Elapsed.TotalMilliseconds};$sorted=$values|Sort-Object;[pscustomobject]@{samples=$Iterations;min_ms=[math]::Round($sorted[0],2);mean_ms=[math]::Round(($values|Measure-Object -Average).Average,2);p95_ms=[math]::Round($sorted[[math]::Min($sorted.Count-1,[math]::Ceiling($sorted.Count*.95)-1)],2);max_ms=[math]::Round($sorted[-1],2)}}
$ready=Measure-Request {Invoke-RestMethod http://localhost:8080/health/ready};$search=Measure-Request {Invoke-RestMethod 'http://localhost:8080/api/v1/endpoints?pageSize=100' -Headers $headers}
$gateway=docker stats deployment-gateway-1 --no-stream --format '{{json .}}'|ConvertFrom-Json;$agentName=(docker ps --format '{{.Names}}'|Where-Object{$_ -match 'agent'}|Select-Object -First 1);$agent=docker stats $agentName --no-stream --format '{{json .}}'|ConvertFrom-Json;$db=docker stats deployment-postgres-1 --no-stream --format '{{json .}}'|ConvertFrom-Json;$openSearch=docker stats deployment-opensearch-1 --no-stream --format '{{json .}}'|ConvertFrom-Json;$nats=docker exec deployment-nats-1 wget -qO- http://localhost:8222/jsz|ConvertFrom-Json
$heartbeatDb=docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select coalesce(round(avg(extract(epoch from(received_at-occurred_at))*1000)::numeric,2),0) from platform.agent_heartbeats where received_at>now()-interval '1 hour'";$projectionDb=docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select coalesce(round(avg(extract(epoch from(published_at-created_at))*1000)::numeric,2),0) from platform.outbox where published_at is not null and created_at>now()-interval '1 hour'";$queue=docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.outbox where published_at is null and failed_at is null"
$strict=$ErrorActionPreference;$ErrorActionPreference='Continue';$logLines=docker logs deployment-gateway-1 2>&1;$ErrorActionPreference=$strict;$requests=$logLines|ForEach-Object{try{$_|ConvertFrom-Json}catch{}}|Where-Object{$_.State.ElapsedMilliseconds};$enroll=($requests|Where-Object{$_.State.Path -eq '/agent/v1/register'}|Select-Object -Last 1).State.ElapsedMilliseconds;$heartbeat=($requests|Where-Object{$_.State.Path -eq '/agent/v1/checkins'}|Select-Object -Last 1).State.ElapsedMilliseconds
$report=[ordered]@{measured_at=[DateTimeOffset]::UtcNow.ToString('o');iterations=$Iterations;readiness=$ready;endpoint_search=$search;latest_enrollment_http_ms=$enroll;latest_heartbeat_http_ms=$heartbeat;heartbeat_received_clock_delta_mean_ms=[double]$heartbeatDb;outbox_publish_latency_mean_ms=[double]$projectionDb;outbox_pending=[int]$queue;gateway=@{cpu=$gateway.CPUPerc;memory=$gateway.MemUsage};agent=@{cpu=$agent.CPUPerc;memory=$agent.MemUsage};database=@{cpu=$db.CPUPerc;memory=$db.MemUsage};opensearch=@{cpu=$openSearch.CPUPerc;memory=$openSearch.MemUsage};nats=@{messages=$nats.messages;bytes=$nats.bytes}}
$report|ConvertTo-Json -Depth 5
