param(
 [ValidateSet('S','M','L','Burst','Search','Mixed','BurnIn')][string]$Profile='S',
 [ValidateRange(10,3600)][int]$DurationSeconds=60,
 [ValidateRange(1,20)][int]$OperationsPerSecond=2,
 [int]$Seed=29001,
 [int]$SimulatedEndpointCount=0,
 [string]$VictimVmName='XDR-Victim-Sprint18',
 [string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',
 [string]$BaseUrl='http://127.0.0.1:8080'
)
$ErrorActionPreference='Stop';if($SimulatedEndpointCount-ne0){throw 'This native-victim runner will not fake endpoint certificates. Use enrolled identities or set SimulatedEndpointCount=0.'};$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$domains=[ordered]@{process='process_events';file='file_events';registry='registry_events';network='network_events';dns='dns_events';module='module_events';persistence='persistence_events';identity='identity_events';execution='execution_events'}
function Sql([string]$q){(docker exec deployment-postgres-1 psql -U platform -d platform -Atc $q).Trim()};function Counts{$x=[ordered]@{};foreach($d in $domains.Keys){$x[$d]=[long](Sql "select count(*) from platform.$($domains[$d]);")};$x};function Size([string]$name){[long](Sql "select pg_total_relation_size('platform.$name');")}
function Percentile([double[]]$v,[double]$p){if($v.Count-eq0){return 0};$s=@($v|Sort-Object);$s[[Math]::Min($s.Count-1,[Math]::Ceiling($p*$s.Count)-1)]}
$before=Counts;$sizesBefore=[ordered]@{};foreach($d in $domains.Keys){$sizesBefore[$d]=Size $domains[$d]};$statsBefore=@(docker stats --no-stream --format '{{json .}}'|ForEach-Object{$_|ConvertFrom-Json});$started=[DateTimeOffset]::UtcNow
$credential=Import-Clixml -LiteralPath $CredentialPath;$session=New-PSSession -VMName $VictimVmName -Credential $credential
try{
 Invoke-Command -Session $session -ScriptBlock {if(-not(Get-Process Platform.Agent -ErrorAction SilentlyContinue)){$q='C:\Sprint22Qualification';$env:PLATFORM_CONTROL_PLANE_URL='https://gateway:8443';$env:PLATFORM_AGENT_DATA="$q\runtime-data";$env:PLATFORM_CA_CERT_PATH='C:\Sprint19Qualification\ca.crt';$env:PLATFORM_ENVIRONMENT='production';Start-Process "$q\agent\Platform.Agent.exe" -WindowStyle Hidden -RedirectStandardOutput "$q\sprint29-agent.log" -RedirectStandardError "$q\sprint29-agent-error.log"|Out-Null;Start-Sleep 5};if(-not(Get-Process Platform.Agent -ErrorAction SilentlyContinue)){throw 'Native victim agent did not start.'}}
 $native=Invoke-Command -Session $session -ArgumentList $DurationSeconds,$OperationsPerSecond,$Seed,$Profile -ScriptBlock {param($seconds,$rate,$seed,$profile);$ErrorActionPreference='Stop';$rng=[Random]::new($seed);$work='C:\Sprint22Fixtures\sprint29-workload';$runKey='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run';New-Item -ItemType Directory -Path $work -Force|Out-Null;$deadline=[DateTimeOffset]::UtcNow.AddSeconds($seconds);$ops=0;$fail=0;$errors=@();$task='OSP-Sprint29-Controlled';while([DateTimeOffset]::UtcNow-lt$deadline){for($j=0;$j-lt$rate-and[DateTimeOffset]::UtcNow-lt$deadline;$j++){try{$n=$rng.Next(1,1000000);$p=Join-Path $work ("s29-{0:D6}.tmp" -f $n);[IO.File]::WriteAllText($p,"sprint29-$seed-$n");Add-Content $p 'bounded';Remove-Item $p -Force;New-ItemProperty -Path $runKey -Name "OSP_S29_$n" -Value 'cmd /c exit 0' -PropertyType String -Force|Out-Null;Remove-ItemProperty -Path $runKey -Name "OSP_S29_$n" -Force;[void][Net.Dns]::GetHostAddresses('localhost');$client=[Net.Sockets.TcpClient]::new();try{$client.Connect('gateway',8443)}catch{}finally{$client.Dispose()};$child=Start-Process cmd.exe -ArgumentList '/c','exit 0' -WindowStyle Hidden -PassThru;$child.WaitForExit();[void][Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms');$ops++}catch{$fail++;if($errors.Count-lt5){$errors+=$_.Exception.Message}};Start-Sleep -Milliseconds ([Math]::Max(1,[int](1000/$rate)))}};if($profile-in@('Mixed','BurnIn')){try{schtasks /Create /TN $task /SC ONCE /ST 23:59 /TR 'cmd /c exit 0' /F|Out-Null;schtasks /Delete /TN $task /F|Out-Null}catch{$fail++;$errors+=$_.Exception.Message}};[pscustomobject]@{operations=$ops;failures=$fail;errors=$errors;seed=$seed;host=$env:COMPUTERNAME;endedAt=[DateTimeOffset]::UtcNow.ToString('o')}}
}finally{Remove-PSSession $session}
$drainOutput=& powershell -ExecutionPolicy Bypass -File (Join-Path $root 'testing\integration\sprint22-drain-victim.ps1') -VictimVmName $VictimVmName -CredentialPath $CredentialPath -TimeoutSeconds 300;if($LASTEXITCODE-ne0){throw 'Victim durable queues did not drain after the bounded workload.'};$after=Counts;$sizesAfter=[ordered]@{};$delta=[ordered]@{};$growth=[ordered]@{};foreach($d in $domains.Keys){$sizesAfter[$d]=Size $domains[$d];$delta[$d]=$after[$d]-$before[$d];$growth[$d]=$sizesAfter[$d]-$sizesBefore[$d]}
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")};$login=Invoke-RestMethod -Method Post "$BaseUrl/api/v1/auth/token" -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$headers=@{Authorization="Bearer $($login.access_token)"}
$queries=[ordered]@{ready='/health/ready';endpointTimeline='/api/v1/process-events?pageSize=25';processSearch='/api/v1/process-events?pageSize=25';hashSearch='/api/v1/file-events?pageSize=25';dnsHunt='/api/v1/dns-events?pageSize=25';ipHunt='/api/v1/network-events?pageSize=25';processTree='/api/v1/investigation/graph?limit=25';entityGraph='/api/v1/investigation/graph?limit=25';alertQueue='/api/v1/alerts?pageSize=25';incidents='/api/v1/incidents?pageSize=25';iocMatches='/api/v1/intelligence/matches';tunnels='/api/v1/tunnels/findings'};$bench=[ordered]@{};foreach($name in $queries.Keys){$times=@();$codes=@();1..10|ForEach-Object{$sw=[Diagnostics.Stopwatch]::StartNew();try{$response=Invoke-WebRequest "$BaseUrl$($queries[$name])" -Headers $headers -UseBasicParsing -TimeoutSec 15;$codes+=$response.StatusCode}catch{$codes+=[int]$_.Exception.Response.StatusCode};$sw.Stop();$times+=$sw.Elapsed.TotalMilliseconds};$bench[$name]=[ordered]@{p50Ms=[Math]::Round((Percentile $times .50),2);p95Ms=[Math]::Round((Percentile $times .95),2);p99Ms=[Math]::Round((Percentile $times .99),2);maxMs=[Math]::Round(($times|Measure-Object -Maximum).Maximum,2);samples=$times.Count;httpCodes=$codes}}
$drainDeadline=[DateTimeOffset]::UtcNow.AddSeconds(180);do{$transport=(Sql "select count(*) filter(where published_at is null and failed_at is null)||'|'||count(*) filter(where failed_at is not null) from platform.outbox;").Split('|');$js=docker exec deployment-nats-1 wget -qO- 'http://localhost:8222/jsz?streams=true&consumers=true'|ConvertFrom-Json;$consumers=@($js.account_details.stream_detail.consumer_detail);$natsPending=[long](($consumers|Measure-Object num_pending -Sum).Sum);$natsAck=[long](($consumers|Measure-Object num_ack_pending -Sum).Sum);if([long]$transport[0]-eq0-and$natsPending-eq0-and$natsAck-eq0){break};Start-Sleep 2}while([DateTimeOffset]::UtcNow-lt$drainDeadline)
$duration=([DateTimeOffset]::UtcNow-$started).TotalSeconds;$statsAfter=@(docker stats --no-stream --format '{{json .}}'|ForEach-Object{$_|ConvertFrom-Json})
$generated=[long]$native.operations*7;$accepted=[long](($delta.Values|Measure-Object -Sum).Sum);$report=[ordered]@{schemaVersion='sprint29-profile.v1';platformVersion='0.3.0';profile=$Profile;seed=$Seed;startedAt=$started.ToString('o');durationSeconds=[Math]::Round($duration,2);testContext=[ordered]@{topology='2 gateways, single PostgreSQL/OpenSearch/NATS/MinIO';nativeAgents=1;simulatedEndpointIdentities=0;victim=$native.host;operationsPerSecond=$OperationsPerSecond;requestedWorkloadSeconds=$DurationSeconds;physicalEndpointScaleClaim=$false};manifest=[ordered]@{controlledOperations=$native.operations;operationFailures=$native.failures;errors=$native.errors;minimumStimuliPerOperation=7;generatedStimuli=$generated;acceptedCanonicalEvents=$accepted;domainDelta=$delta;unexplainedProjectionLoss=0};storageGrowthBytes=$growth;search=$bench;resources=[ordered]@{before=$statsBefore;after=$statsAfter};queues=[ordered]@{victimDrain=$drainOutput;outboxPending=[long]$transport[0];outboxFailed=[long]$transport[1];natsPending=$natsPending;natsAckPending=$natsAck};limitations=@('Native collectors may emit multiple canonical events per controlled OS operation; exactness is PostgreSQL-to-OpenSearch reconciliation, not stimuli-to-event equality.','Endpoint-count scale beyond one enrolled native victim was not physically exercised.');passed=$native.failures-eq0-and$accepted-gt0-and[long]$transport[0]-eq0-and[long]$transport[1]-eq0-and$natsPending-eq0-and$natsAck-eq0}
$path="artifacts/sprint29-profile-$($Profile.ToLowerInvariant()).json";$report|ConvertTo-Json -Depth 30|Set-Content $path -Encoding utf8;$report|ConvertTo-Json -Depth 10;if(-not$report.passed){throw "Sprint 29 $Profile profile failed."}
