param([string]$Output='artifacts/sprint5-windows-network-profiles.json')
$ErrorActionPreference='Stop';$principal=[Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent();if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Administrator token required.'};Set-Location (Resolve-Path (Join-Path $PSScriptRoot '..\..'))
$cfg=@{};Get-Content .env|?{$_-match'^[^#].*='}|%{$p=$_.Split('=',2);$cfg[$p[0]]=$p[1]};$d=[DateTimeOffset]::UtcNow.AddSeconds(90);do{try{$login=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/auth/token -ContentType application/json -Body (@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json)}catch{$login=$null};if(-not$login){Start-Sleep 1}}while((-not$login)-and[DateTimeOffset]::UtcNow-lt$d);if(-not$login){throw 'Gateway login readiness timed out'};$headers=@{Authorization="Bearer $($login.access_token)"};$before=@((Invoke-RestMethod 'http://localhost:8080/api/v1/endpoints?pageSize=500' -Headers $headers).data.items.id)
$token=Invoke-RestMethod -Method Post http://localhost:8080/api/v1/enrollment-tokens -Headers $headers -ContentType application/json -Body (@{expiresAt=[DateTimeOffset]::UtcNow.AddHours(2).ToString('O');maximumUses=1;allowedPlatforms=@('windows');endpointGroupId=$null;policyId=$null}|ConvertTo-Json)
$run=Join-Path (Resolve-Path artifacts) "sprint5-windows-$([DateTimeOffset]::UtcNow.ToString('yyyyMMddHHmmss'))";New-Item -ItemType Directory -Force $run|Out-Null;$agentPath=(Resolve-Path agent/core/Platform.Agent/bin/Release/net8.0/Platform.Agent.exe).Path
$env:PLATFORM_AGENT_DATA=$run;$env:PLATFORM_ENVIRONMENT='production';$env:PLATFORM_CONTROL_PLANE_URL='https://localhost:8443';$env:PLATFORM_CA_CERT_PATH=(Resolve-Path deployment/certificates/ca.crt).Path;$env:PLATFORM_ENROLLMENT_TOKEN_ID=$token.data.metadata.id;$env:PLATFORM_ENROLLMENT_TOKEN_SECRET=$token.data.secret
$agent=Start-Process $agentPath -RedirectStandardOutput (Join-Path $run agent.log) -RedirectStandardError (Join-Path $run agent.stderr.log) -PassThru -WindowStyle Hidden;$env:PLATFORM_ENROLLMENT_TOKEN_ID='';$env:PLATFORM_ENROLLMENT_TOKEN_SECRET='';$endpoint=$null;$profiles=[Collections.Generic.List[object]]::new();$rows=[Collections.Generic.List[object]]::new()
function Sql($q){$v=docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $q;if($LASTEXITCODE-ne0){throw 'SQL failed'};$v};function Add($name,$status,$evidence){$rows.Add([ordered]@{criterion=$name;status=$status;evidence=$evidence})}
function Ready([int]$seconds=120){$d=[DateTimeOffset]::UtcNow.AddSeconds($seconds);do{Start-Sleep 1;try{$ok=(Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing -TimeoutSec 2).StatusCode-eq200}catch{$ok=$false}}while((-not$ok)-and[DateTimeOffset]::UtcNow-lt$d);$ok}
function Events([DateTimeOffset]$start,[int[]]$ports,[int]$minimum=1){$from=[uri]::EscapeDataString($start.AddSeconds(-2).ToString('O'));$to=[uri]::EscapeDataString([DateTimeOffset]::UtcNow.AddMinutes(1).ToString('O'));$d=[DateTimeOffset]::UtcNow.AddSeconds(90);do{Start-Sleep 1;$byId=@{};foreach($port in $ports){foreach($field in @('localPort','remotePort')){@((Invoke-RestMethod "http://localhost:8080/api/v1/network-events?endpointId=$endpoint&$field=$port&from=$from&to=$to&pageSize=500" -Headers $headers).data.items)|%{$byId[$_.eventId]=$_}}};$matched=@($byId.Values);$stable=if($matched.Count-eq$script:lastCount){$script:stable+1}else{0};$script:lastCount=$matched.Count;$script:stable=$stable}while(($matched.Count-lt$minimum-or$stable-lt2)-and[DateTimeOffset]::UtcNow-lt$d);$matched}
function TcpSuccess([int]$count,[bool]$burst,[bool]$v6){$ip=if($v6){[Net.IPAddress]::IPv6Loopback}else{[Net.IPAddress]::Loopback};$family=if($v6){[Net.Sockets.AddressFamily]::InterNetworkV6}else{[Net.Sockets.AddressFamily]::InterNetwork};$listener=[Net.Sockets.TcpListener]::new($ip,0);$listener.Start(256);$port=([Net.IPEndPoint]$listener.LocalEndpoint).Port;$clients=[Collections.Generic.List[Net.Sockets.TcpClient]]::new();if($burst){$tasks=[Collections.Generic.List[Threading.Tasks.Task]]::new();1..$count|%{$c=[Net.Sockets.TcpClient]::new($family);$clients.Add($c);$tasks.Add($c.ConnectAsync($ip,$port))};$null=[Threading.Tasks.Task]::WhenAll($tasks.ToArray()).GetAwaiter().GetResult();1..$count|%{$s=$listener.AcceptTcpClient();$s.Dispose()}}else{1..$count|%{$a=$listener.AcceptTcpClientAsync();$c=[Net.Sockets.TcpClient]::new($family);$c.Connect($ip,$port);$clients.Add($c);$s=$a.GetAwaiter().GetResult();$s.Dispose();$c.Dispose()}};$clients|%{$_.Dispose()};$listener.Stop();,$port}
function TcpFail([int]$count){$l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,0);$l.Start();$port=([Net.IPEndPoint]$l.LocalEndpoint).Port;$l.Stop();1..$count|%{$c=$null;try{$c=[Net.Sockets.TcpClient]::new();$c.Connect([Net.IPAddress]::Loopback,$port)}catch [Net.Sockets.SocketException]{}finally{if($c){$c.Dispose()}}};,$port}
function Udp([int]$count){$receiver=[Net.Sockets.UdpClient]::new([Net.IPEndPoint]::new([Net.IPAddress]::Loopback,0));$port=([Net.IPEndPoint]$receiver.Client.LocalEndPoint).Port;$sender=[Net.Sockets.UdpClient]::new();1..$count|%{$sender.Send([byte[]](1,2,3),3,[Net.IPEndPoint]::new([Net.IPAddress]::Loopback,$port))|Out-Null};1..$count|%{$remote=[Net.IPEndPoint]::new([Net.IPAddress]::Any,0);$null=$receiver.Receive([ref]$remote)};$sender.Dispose();$receiver.Dispose();,$port}
function Profile($letter,$mode,[int]$logical,[scriptblock]$work,[scriptblock]$assert){$script:lastCount=-1;$script:stable=0;$start=[DateTimeOffset]::UtcNow;$cpu0=$agent.TotalProcessorTime.TotalMilliseconds;$watch=[Diagnostics.Stopwatch]::StartNew();$ports=@(&$work);$watch.Stop();$ev=@(Events $start $ports 1);$health=(Invoke-RestMethod "http://localhost:8080/api/v1/endpoints/$endpoint/network-telemetry-health" -Headers $headers).data;$kinds=@{};$ev|Group-Object kind|%{$kinds[$_.Name]=$_.Count};$result=&$assert $ev $kinds;$status=if($result-is[string]){$result}elseif($result){'PASS'}else{'FAIL'};$profiles.Add([ordered]@{profile=$letter;mode=$mode;logicalOperations=$logical;ports=$ports;durationMs=[math]::Round($watch.Elapsed.TotalMilliseconds,2);nativeEvents=$ev.Count;uniqueEvents=@($ev.eventId|Sort-Object -Unique).Count;connectionEntities=@($ev.connectionEntityId|Sort-Object -Unique).Count;processAttributed=@($ev|?{$_.process.processId-gt0}).Count;IPv4=@($ev|?{$_.local.addressFamily-eq'IPv4'}).Count;IPv6=@($ev|?{$_.local.addressFamily-eq'IPv6'}).Count;operations=$kinds;lostEvents=$health.sourceLosses;queueDepth=$health.queueDepth;agentCpuDeltaMs=[math]::Round($agent.TotalProcessorTime.TotalMilliseconds-$cpu0,2);agentWorkingSetBytes=$agent.WorkingSet64;sourceMultiplicity='native ETW operations are not asserted one-to-one with application calls';unexplainedLoss=if($status-eq'FAIL'){$logical}else{0};status=$status})}
try{
 $d=[DateTimeOffset]::UtcNow.AddSeconds(75);do{Start-Sleep 1;$items=@((Invoke-RestMethod 'http://localhost:8080/api/v1/endpoints?pageSize=500' -Headers $headers).data.items);$endpoint=($items|?{$_.id-notin$before}|Select-Object -First 1).id}while((-not$endpoint)-and[DateTimeOffset]::UtcNow-lt$d);if(-not$endpoint){throw 'Windows endpoint enrollment timed out'}
 Start-Sleep 2;$effective=(Invoke-RestMethod "http://localhost:8080/api/v1/endpoints/$endpoint/network-policy" -Headers $headers).data;if($effective.policy.name-ne'safe-default'){throw 'Unexpected effective network policy'}
 # The qualification workstation has measured, unrelated QUIC and mDNS floods on UDP 443/5353.
 # Exclude only those ports so controlled ephemeral TCP/UDP traffic remains fully observable.
 $qualificationPolicy=(Invoke-RestMethod -Method Post http://localhost:8080/api/v1/network-telemetry/policies -Headers $headers -ContentType application/json -Body (@{name="sprint5-windows-qualification-$([guid]::NewGuid().ToString('N'))";policy=@{enabled=$true;tcpEnabled=$true;udpEnabled=$true;ipv4Enabled=$true;ipv6Enabled=$true;attemptsEnabled=$true;establishedEnabled=$true;failedEnabled=$true;closedEnabled=$true;inboundEnabled=$true;listenerEnabled=$true;excludedPorts=@('443','5353');maximumQueueBytes=134217728;maximumQueueAgeHours=24;maximumBatchEvents=500;maximumBatchBytes=1048576;flushSeconds=2;collectorSource='auto'}}|ConvertTo-Json -Depth 10)).data
 Invoke-RestMethod -Method Post "http://localhost:8080/api/v1/network-telemetry/policies/$($qualificationPolicy.id):assign" -Headers $headers -ContentType application/json -Body (@{endpointId=$endpoint}|ConvertTo-Json)|Out-Null
 if($agent-and-not$agent.HasExited){Stop-Process $agent.Id -Force;$agent.WaitForExit()};@('OpenSecurityPlatform-NetworkLifecycle-v1','OpenSecurityPlatform-RegistryLifecycle-v1','OpenSecurityPlatform-ProcessLifecycle-v1','OpenSecurityPlatform-FileLifecycle-v1')|%{& logman stop $_ -ets 2>$null|Out-Null};Get-ChildItem (Join-Path $run 'network-queue') -Filter '*.json' -ErrorAction SilentlyContinue|Remove-Item -Force
 $agent=Start-Process $agentPath -RedirectStandardOutput (Join-Path $run agent-restarted.log) -RedirectStandardError (Join-Path $run agent-restarted.stderr.log) -PassThru -WindowStyle Hidden
 $d=[DateTimeOffset]::UtcNow.AddSeconds(75);do{Start-Sleep 1;$effective=(Invoke-RestMethod "http://localhost:8080/api/v1/endpoints/$endpoint/network-policy" -Headers $headers).data}while(($effective.policy.id-ne$qualificationPolicy.id-or$effective.appliedVersion-ne$qualificationPolicy.version)-and[DateTimeOffset]::UtcNow-lt$d);if($effective.policy.id-ne$qualificationPolicy.id-or$effective.appliedVersion-ne$qualificationPolicy.version){throw 'Qualification policy acknowledgement timed out'};Add 'background-noise-exclusion-policy' 'PASS' @{policyId=$qualificationPolicy.id;version=$qualificationPolicy.version;excludedPorts=@('443','5353');reason='measured unrelated QUIC and mDNS saturation'}
 Profile A 'normal-workstation-ipv4-tcp' 10 {TcpSuccess 10 $false $false} {param($e,$k)@($e|?{$_.kind-eq'ConnectionAttempted'}).Count-gt0-and@($e|?{$_.kind-eq'ConnectionEstablished'}).Count-gt0}
 Profile B 'concurrent-ipv4-tcp' 30 {TcpSuccess 30 $true $false} {param($e,$k)@($e|?{$_.kind-eq'ConnectionAttempted'}).Count-gt0-and@($e|?{$_.kind-eq'ConnectionEstablished'}).Count-gt0}
 Profile C 'ipv4-and-ipv6-tcp' 10 {$p=@();$p+=TcpSuccess 5 $false $false;$p+=TcpSuccess 5 $false $true;$p} {param($e,$k)@($e|?{$_.local.addressFamily-eq'IPv4'}).Count-gt0-and@($e|?{$_.local.addressFamily-eq'IPv6'}).Count-gt0}
 Profile D 'failed-ipv4-tcp-source-semantics' 10 {TcpFail 10} {param($e,$k)if(@($e|?{$_.kind-eq'ConnectionFailed'}).Count-gt0){'PASS'}else{'NOT OBSERVABLE BY SOURCE'}}
 Profile E 'bounded-udp-operation-observation' 50 {Udp 50} {param($e,$k)@($e|?{$_.kind-eq'DatagramObserved'}).Count-gt0}
 Profile F 'bounded-mixed-volume-and-fairness' 150 {$p=@();$p+=TcpSuccess 50 $true $false;$p+=Udp 100;$tmp=Join-Path $run "fairness-$([guid]::NewGuid().ToString('N')).txt";1..10|%{Set-Content $tmp "fairness-$_";Remove-Item $tmp -ErrorAction SilentlyContinue;&reg.exe add 'HKCU\Software\OpenSecurityPlatform\Sprint4\Sprint5Fairness' /v Probe /t REG_SZ /d "pass-$_" /f|Out-Null};$generator=(Resolve-Path 'tools/ProcessGenerator/bin/Release/net8.0/ProcessGenerator.exe').Path;1..5|%{Start-Process $generator -ArgumentList @('--child','--registry-path','Software\OpenSecurityPlatform\Sprint4\Sprint5Fairness','--registry-value',"ProcessProbe$_",'--lifetime-ms','250') -Wait -WindowStyle Hidden};&reg.exe delete 'HKCU\Software\OpenSecurityPlatform\Sprint4\Sprint5Fairness' /f|Out-Null;1..10|%{Start-Process cmd.exe -ArgumentList '/c','exit 0' -Wait};$p} {param($e,$k)@($e|?{$_.kind-eq'ConnectionAttempted'}).Count-gt0-and@($e|?{$_.kind-eq'DatagramObserved'}).Count-gt0}
 $tupleStart=[DateTimeOffset]::UtcNow;$tuplePort=TcpSuccess 2 $false $false;$tupleEvents=@(Events $tupleStart @($tuplePort) 2);$tupleEntities=@($tupleEvents|?{$_.kind-eq'ConnectionAttempted'}|Select-Object -Expand connectionEntityId -Unique);Add 'tuple-reuse-protection' $(if($tupleEntities.Count-ge2){'PASS'}else{'FAIL'}) @{entities=$tupleEntities.Count;port=$tuplePort}
 $fairFrom=[DateTimeOffset]::UtcNow.AddMinutes(-5).UtcDateTime.ToString('O');$d=[DateTimeOffset]::UtcNow.AddSeconds(90);do{Start-Sleep 2;$counts=(Sql "select (select count(*) from platform.process_events where endpoint_id='$endpoint' and received_at>='$fairFrom')||'|'||(select count(*) from platform.file_events where endpoint_id='$endpoint' and received_at>='$fairFrom')||'|'||(select count(*) from platform.registry_events where endpoint_id='$endpoint' and received_at>='$fairFrom')").Split('|')}while(@($counts|%{[long]$_}|?{$_-eq0}).Count-gt0-and[DateTimeOffset]::UtcNow-lt$d);Add 'telemetry-partition-fairness' $(if(@($counts|%{[long]$_}|?{$_-eq0}).Count-eq0){'PASS'}else{'FAIL'}) @{process=[long]$counts[0];file=[long]$counts[1];registry=[long]$counts[2]}
 $offlineStart=[DateTimeOffset]::UtcNow;$ErrorActionPreference='Continue';docker compose --env-file .env -f deployment/docker-compose.yml stop gateway 2>&1|Out-Null;$ErrorActionPreference='Stop';Start-Sleep 3;$offlinePorts=@();$offlinePorts+=TcpSuccess 20 $false $false;$offlinePorts+=Udp 20;$queue=Join-Path $run 'network-queue';$d=[DateTimeOffset]::UtcNow.AddSeconds(60);$peak=0;do{Start-Sleep 1;$depth=@(Get-ChildItem $queue -Filter '*.json' -ErrorAction SilentlyContinue).Count;$peak=[math]::Max($peak,$depth)}while($peak-eq0-and[DateTimeOffset]::UtcNow-lt$d);$ErrorActionPreference='Continue';docker compose --env-file .env -f deployment/docker-compose.yml up -d gateway 2>&1|Out-Null;$ErrorActionPreference='Stop';if(-not(Ready)){throw 'Gateway did not recover'};$d=[DateTimeOffset]::UtcNow.AddSeconds(120);do{Start-Sleep 2;$depth=@(Get-ChildItem $queue -Filter '*.json' -ErrorAction SilentlyContinue).Count}while($depth-gt0-and[DateTimeOffset]::UtcNow-lt$d);$offlineEvents=@(Events $offlineStart $offlinePorts);$offlinePass=$peak-gt0-and$depth-eq0-and$offlineEvents.Count-gt0;Add 'offline-buffering-replay' $(if($offlinePass){'PASS'}else{'FAIL'}) @{queuePeak=$peak;queueFinal=$depth;replayedEvents=$offlineEvents.Count;maximumQueueBytes=$effective.policy.policy.maximumQueueBytes}
 $health=(Invoke-RestMethod "http://localhost:8080/api/v1/endpoints/$endpoint/network-telemetry-health" -Headers $headers).data;Add 'lost-event-counters' $(if($health.sourceLosses-eq0-and$health.droppedEvents-eq0){'PASS'}else{'FAIL'}) @{sourceLosses=$health.sourceLosses;droppedEvents=$health.droppedEvents;sequenceGaps=$health.sequenceGaps};Add 'process-attribution' $(if(@($profiles|% processAttributed|?{$_-gt0}).Count-eq6){'PASS'}else{'FAIL'}) @{profileCounts=@($profiles|% processAttributed)}
}finally{if($agent-and-not$agent.HasExited){$d=[DateTimeOffset]::UtcNow.AddSeconds(180);do{Start-Sleep 2;$remaining=@('network-queue','process-queue','file-queue','registry-queue','file-hash-work')|%{@(Get-ChildItem (Join-Path $run $_) -Filter '*.json' -ErrorAction SilentlyContinue).Count}|Measure-Object -Sum}while($remaining.Sum-gt0-and[DateTimeOffset]::UtcNow-lt$d);Stop-Process $agent.Id -Force;$agent.WaitForExit()};@('OpenSecurityPlatform-NetworkLifecycle-v1','OpenSecurityPlatform-RegistryLifecycle-v1','OpenSecurityPlatform-ProcessLifecycle-v1','OpenSecurityPlatform-FileLifecycle-v1')|%{& logman stop $_ -ets 2>$null|Out-Null};$ErrorActionPreference='Continue';docker compose --env-file .env -f deployment/docker-compose.yml up -d gateway 2>&1|Out-Null;$ErrorActionPreference='Stop';Ready|Out-Null}
$profilePass=@($profiles|?{$_.status-eq'FAIL'}).Count-eq0;$rowPass=@($rows|?{$_.status-eq'FAIL'}).Count-eq0;$report=[ordered]@{schema='platform.sprint5.windows-network-profiles.v1';executedAt=[DateTimeOffset]::UtcNow;endpointId=$endpoint;run=$run;profiles=$profiles;qualification=$rows;passedProfiles=@($profiles|?{$_.status-eq'PASS'}).Count;sourceLimitedProfiles=@($profiles|?{$_.status-eq'NOT OBSERVABLE BY SOURCE'}).Count;failedProfiles=@($profiles|?{$_.status-eq'FAIL'}).Count;complete=$profiles.Count-eq6-and$profilePass-and$rowPass};$report|ConvertTo-Json -Depth 12|Set-Content $Output;$report|ConvertTo-Json -Depth 6;if(-not$report.complete){exit 1}
