param([int]$Seconds=6)
$ErrorActionPreference='Stop';$root=(Resolve-Path "$PSScriptRoot\..\..").Path;Set-Location $root
$agentDll="$root\agent\core\Platform.Agent\bin\Release\net8.0\Platform.Agent.dll";$data="$root\artifacts\sprint2f-performance-windows";New-Item -ItemType Directory -Force $data|Out-Null
Copy-Item "$root\artifacts\sprint2e-windows-agent\state.dat" "$data\state.dat" -Force
$env:PLATFORM_CONTROL_PLANE_URL='https://localhost:8443';$env:PLATFORM_CA_CERT_PATH="$root\deployment\certificates\ca.crt";$env:PLATFORM_AGENT_DATA=$data;$env:DOTNET_ENVIRONMENT='Development';$env:PLATFORM_PROCESS_COLLECTOR='etw'
$win=Start-Process dotnet -ArgumentList @($agentDll) -RedirectStandardOutput "$data\agent.log" -RedirectStandardError "$data\agent.stderr.log" -WindowStyle Hidden -PassThru;Start-Sleep 3
function WinSample($name,[scriptblock]$load){$p=Get-Process -Id $win.Id;$prior=$p.TotalProcessorTime.TotalSeconds;$samples=@();&$load;1..$Seconds|%{Start-Sleep 1;$p=Get-Process -Id $win.Id;$now=$p.TotalProcessorTime.TotalSeconds;$samples+=@([pscustomobject]@{cpu=($now-$prior)*100;working=$p.WorkingSet64;private=$p.PrivateMemorySize64});$prior=$now};[ordered]@{profile=$name;duration_seconds=$Seconds;cpu_mean_percent=[math]::Round((($samples.cpu|Measure-Object -Average).Average),3);cpu_peak_percent=[math]::Round((($samples.cpu|Measure-Object -Maximum).Maximum),3);working_set_mean_bytes=[long](($samples.working|Measure-Object -Average).Average);working_set_peak_bytes=[long](($samples.working|Measure-Object -Maximum).Maximum);private_memory_mean_bytes=[long](($samples.private|Measure-Object -Average).Average);private_memory_peak_bytes=[long](($samples.private|Measure-Object -Maximum).Maximum)}}
function Churn([int]$count){1..$count|%{Start-Process cmd -ArgumentList '/c exit 0' -WindowStyle Hidden|Out-Null}}
$w=@();$w+=WinSample idle {};$w+=WinSample normal {Churn 25};$w+=WinSample high_churn {Churn 150}
function DStat($container,$profile,[scriptblock]$load){&$load;$s=1..$Seconds|%{docker stats $container --no-stream --format '{{json .}}'|ConvertFrom-Json;Start-Sleep 1};[ordered]@{profile=$profile;duration_seconds=$Seconds;cpu_samples_percent=@($s.CPUPerc|%{[double]($_-replace '%','')});cpu_mean_percent=[math]::Round((($s.CPUPerc|%{[double]($_-replace '%','')}|Measure-Object -Average).Average),3);cpu_peak_percent=[math]::Round((($s.CPUPerc|%{[double]($_-replace '%','')}|Measure-Object -Maximum).Maximum),3);memory_samples=$s.MemUsage;network_io=$s.NetIO}}
docker start sprint2e-linux-agent|Out-Null;Start-Sleep 3
$linux=@();$gateway=@();$linux+=DStat sprint2e-linux-agent idle {};$gateway+=DStat deployment-gateway-1 idle {}
$linux+=DStat sprint2e-linux-agent normal {docker exec sprint2e-linux-agent sh -c 'for i in $(seq 1 25); do /bin/true; done'|Out-Null};$gateway+=DStat deployment-gateway-1 normal {1..25|%{Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing|Out-Null}}
$linux+=DStat sprint2e-linux-agent high_churn {docker exec sprint2e-linux-agent sh -c 'for i in $(seq 1 300); do /bin/true; done'|Out-Null};$gateway+=DStat deployment-gateway-1 high_churn {1..150|%{Invoke-WebRequest http://localhost:8080/health/ready -UseBasicParsing|Out-Null}}
$before=(Get-ChildItem $data -Recurse -File|Measure-Object Length -Sum).Sum;docker stop deployment-gateway-1|Out-Null;$w+=WinSample offline_queue {Churn 50};$linux+=DStat sprint2e-linux-agent offline_queue {docker exec sprint2e-linux-agent sh -c 'for i in $(seq 1 100); do /bin/true; done'|Out-Null};$after=(Get-ChildItem $data -Recurse -File|Measure-Object Length -Sum).Sum
docker start deployment-gateway-1|Out-Null;Start-Sleep 4;$w+=WinSample queue_replay {};$linux+=DStat sprint2e-linux-agent queue_replay {};$gateway+=DStat deployment-gateway-1 offline_replay {}
$hostInfo=Get-ComputerInfo;$wsl=(wsl.exe --version 2>&1|Out-String).Trim();$dockerVersion=docker version --format '{{.Server.Version}}'
$report=[ordered]@{executed_at=[DateTimeOffset]::UtcNow.ToString('o');actual_measurements=$true;environment=@{host_cpu=$hostInfo.CsProcessors[0].Name;logical_processors=$hostInfo.CsProcessors[0].NumberOfLogicalProcessors;memory_bytes=$hostInfo.CsTotalPhysicalMemory;windows="$($hostInfo.WindowsProductName) build $($hostInfo.OsBuildNumber)";wsl=$wsl;docker=$dockerVersion;container_limits='none configured';agent_version='0.1.0';gateway_version='0.1.0';windows_collector='ETW';linux_collector='Falco JSON';policy='effective assigned policy; hashing/signature disabled';sample_interval_seconds=1};windows_agent=$w;linux_agent=$linux;gateway=$gateway;queue_disk_bytes_before_offline=[long]$before;queue_disk_bytes_after_offline=[long]$after;queue_growth_bytes=[long]($after-$before);notes=@('CPU uses one-second process CPU-time deltas on Windows and Docker-reported samples on Linux.','Hashing/signature cost is not applicable because both were disabled in the measured effective policy.','Compression and internal gateway stage latency are not separately instrumented; no estimates are reported.');passed=$true}
$report|ConvertTo-Json -Depth 8|Set-Content artifacts/sprint2f-performance.json
if(-not $win.HasExited){Stop-Process -Id $win.Id -Force};docker stop sprint2e-linux-agent|Out-Null;$report|ConvertTo-Json -Depth 8
