$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match'^\s*([^#=\s]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
function Sql($query){$v=docker exec deployment-postgres-1 psql -v ON_ERROR_STOP=1 -U platform -d platform -Atc $query;if($null-eq$v){''}else{($v|Out-String).Trim()}}
function Percentiles([double[]]$values){$s=@($values|Sort-Object);function P($n){if(!$s.Count){return 0};$s[[math]::Min($s.Count-1,[math]::Floor(($s.Count-1)*$n))]};[ordered]@{count=$s.Count;p50=[math]::Round((P .50),2);p95=[math]::Round((P .95),2);p99=[math]::Round((P .99),2);max=[math]::Round($s[-1],2)}}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$headers=@{Authorization="Bearer $($login.access_token)"}
$latencies=[ordered]@{ready=@();endpoints=@();processSearch=@()};1..20|ForEach-Object{foreach($x in @(@{name='ready';uri='http://127.0.0.1:8080/health/ready';headers=$null},@{name='endpoints';uri='http://127.0.0.1:8080/api/v1/endpoints?pageSize=25';headers=$headers},@{name='processSearch';uri='http://127.0.0.1:8080/api/v1/processes?pageSize=25';headers=$headers})){$w=[Diagnostics.Stopwatch]::StartNew();$null=Invoke-WebRequest -UseBasicParsing $x.uri -Headers $x.headers -TimeoutSec 15;$w.Stop();$latencies[$x.name]+=$w.Elapsed.TotalMilliseconds}}
$tables=Sql "select schemaname||'.'||relname||'|'||pg_total_relation_size(relid)||'|'||n_live_tup from pg_stat_user_tables where schemaname='platform' order by pg_total_relation_size(relid) desc;"
$indices=(docker exec deployment-opensearch-1 curl -sf 'http://localhost:9200/_cat/indices?format=json&bytes=b&s=store.size:desc'|Out-String|ConvertFrom-Json)
$js=(docker exec deployment-nats-1 wget -qO- 'http://127.0.0.1:8222/jsz?consumers=true'|Out-String|ConvertFrom-Json)
$hostCpu=Get-CimInstance Win32_Processor;$hostOs=Get-CimInstance Win32_OperatingSystem;$drive=Get-PSDrive D;$disks=@(Get-PhysicalDisk -ErrorAction SilentlyContinue|Select-Object FriendlyName,MediaType,BusType,Size,HealthStatus);$adapters=@(Get-NetAdapter -Physical -ErrorAction SilentlyContinue|Where-Object Status -eq Up|Select-Object Name,LinkSpeed)
$containerStats=@(docker stats --no-stream --format '{{json .}}'|ForEach-Object{$_|ConvertFrom-Json})
$domainTables=@('process_entities','file_entities','registry_events','network_events','dns_events','module_events','persistence_events','identity_events','execution_events','detection_findings','correlated_findings','alerts','incidents','threat_indicators','threat_matches','tunnel_observations','tunnel_findings')
$domain=[ordered]@{};foreach($name in $domainTables){$v=(Sql "select count(*)||'|'||pg_total_relation_size('platform.$name') from platform.$name;").Split('|');$domain[$name]=[ordered]@{records=[long]$v[0];postgresBytes=[long]$v[1]}}
$report=[ordered]@{schemaVersion='sprint29-baseline.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');platformVersion='1.0.0-sprint28';topology=[ordered]@{gatewayInstances=2;workerLeases=23;postgresql='16 single instance';nats='2.10 single-node JetStream';openSearch='2.19.2 single node, 512 MiB JVM';minio='single node';nativeAgents=1;simulatedEndpointIdentities=0};host=[ordered]@{cpuName=$hostCpu[0].Name;logicalCores=($hostCpu|Measure-Object NumberOfLogicalProcessors -Sum).Sum;ramBytes=[long]$hostOs.TotalVisibleMemorySize*1024;freeRamBytes=[long]$hostOs.FreePhysicalMemory*1024;dAvailableBytes=[long]$drive.Free;disks=$disks;network=$adapters};postgres=[ordered]@{databaseBytes=[long](Sql "select pg_database_size('platform');");settings=(Sql "select name||'='||setting from pg_settings where name in ('max_connections','shared_buffers','work_mem','maintenance_work_mem','effective_cache_size','wal_level') order by name;");largestTables=$tables;domains=$domain};openSearch=[ordered]@{indices=$indices;totalBytes=[long](($indices|Measure-Object store.size -Sum).Sum)};nats=[ordered]@{streams=$js.streams;messages=$js.messages;bytes=$js.bytes;pending=[long](($js.account_details.stream_detail.consumer_detail.num_pending|Measure-Object -Sum).Sum);ackPending=[long](($js.account_details.stream_detail.consumer_detail.num_ack_pending|Measure-Object -Sum).Sum)};minio=[ordered]@{bytes=[long]((docker exec deployment-minio-1 du -sb /data|Out-String).Split()[0]);inventory=[long](Sql 'select count(*) from platform.object_recovery_inventory;')};apiLatencyMilliseconds=[ordered]@{ready=Percentiles $latencies.ready;endpoints=Percentiles $latencies.endpoints;processSearch=Percentiles $latencies.processSearch};containers=$containerStats;queues=[ordered]@{outboxPending=[long](Sql "select count(*) from platform.outbox where published_at is null and failed_at is null;");activeTransfers=[long](Sql "select count(*) from platform.artifact_transfers where state in ('Receiving','Verifying');")}}
$report|ConvertTo-Json -Depth 30|Set-Content artifacts/sprint29-baseline.json -Encoding utf8;$report|ConvertTo-Json -Depth 6
