namespace OpenSecurityPlatform.Foundation;

public sealed record DetectionStarterFixture(DetectionDefinition Rule, DetectionExclusion Exclusion, DetectionRuleTestCase[] Tests);

public static class DetectionStarterFixtures
{
    public static IReadOnlyList<DetectionStarterFixture> Create(string tenant)
    {
        var root = @"C:\Sprint12Fixtures"; var now = DateTimeOffset.UtcNow;
        return
        [
            Fixture("A",tenant,DetectionDomain.Process,new(Field:"path",Operator:DetectionOperator.StartsWith,Value:root+@"\",CaseInsensitive:true),"path",root+@"\excluded.exe",new(){["path"]=root+@"\suspicious.exe",["processName"]="suspicious.exe"},new(){["path"]=@"C:\Windows\notepad.exe",["processName"]="notepad.exe"},["path"],now),
            Fixture("B",tenant,DetectionDomain.File,new(DetectionLogic.And,Children:[new(Field:"path",Operator:DetectionOperator.StartsWith,Value:root+@"\",CaseInsensitive:true),new(Field:"operation",Value:"Created",CaseInsensitive:true)]),"path",root+@"\excluded-file.exe",new(){["path"]=root+@"\created.exe",["operation"]="Created",["extension"]=".exe"},new(){["path"]=@"C:\Temp\benign.txt",["operation"]="Created"},["path","operation"],now),
            Fixture("C",tenant,DetectionDomain.Registry,new(Field:"path",Operator:DetectionOperator.StartsWith,Value:@"HKCU\Software\Sprint12Fixtures\",CaseInsensitive:true),"path",@"HKCU\Software\Sprint12Fixtures\Excluded",new(){["path"]=@"HKCU\Software\Sprint12Fixtures\Run",["operation"]="ValueSet",["valueName"]="Controlled"},new(){["path"]=@"HKCU\Software\Benign",["operation"]="ValueSet"},["path"],now),
            Fixture("D",tenant,DetectionDomain.Network,new(DetectionLogic.And,Children:[new(Field:"destinationIp",Operator:DetectionOperator.Cidr,Value:"127.0.0.0/8"),new(Field:"destinationPort",Value:"4317")]),"destinationIp","127.0.0.2",new(){["destinationIp"]="127.0.0.1",["destinationPort"]="4317",["protocol"]="tcp"},new(){["destinationIp"]="192.0.2.10",["destinationPort"]="443"},["destinationIp","destinationPort"],now),
            Fixture("E",tenant,DetectionDomain.Dns,new(Field:"query",Operator:DetectionOperator.EndsWith,Value:".test.invalid",CaseInsensitive:true),"query","excluded.test.invalid",new(){["query"]="controlled.test.invalid",["recordType"]="A"},new(){["query"]="example.com",["recordType"]="A"},["query"],now),
            Fixture("F",tenant,DetectionDomain.Module,new(DetectionLogic.And,Children:[new(Field:"path",Operator:DetectionOperator.StartsWith,Value:root+@"\",CaseInsensitive:true),new(Field:"signerState",Value:"unsigned",CaseInsensitive:true)]),"path",root+@"\excluded.dll",new(){["path"]=root+@"\unsigned-test.dll",["basename"]="unsigned-test.dll",["signerState"]="unsigned"},new(){["path"]=@"C:\Windows\System32\kernel32.dll",["signerState"]="signed"},["path","signerState"],now),
            Fixture("G",tenant,DetectionDomain.Persistence,new(Field:"name",Operator:DetectionOperator.StartsWith,Value:"Sprint12Fixture",CaseInsensitive:true),"name","Sprint12FixtureExcluded",new(){["name"]="Sprint12FixtureTask",["kind"]="ScheduledTask",["operation"]="Created"},new(){["name"]="MicrosoftMaintenance",["kind"]="ScheduledTask"},["name"],now),
            Fixture("H",tenant,DetectionDomain.Identity,new(Field:"status",Value:"failed",CaseInsensitive:true),"user","sprint12-excluded",new(){["status"]="failed",["user"]="sprint12-test"},new(){["status"]="success",["user"]="sprint12-test"},["status","user"],now,true),
            Fixture("I",tenant,DetectionDomain.Execution,new(Field:"operation",Value:"thread-start",CaseInsensitive:true),"targetProcess","fixture-excluded-process",new(){["operation"]="thread-start",["targetProcess"]="fixture-target",["threadId"]="1201"},new(){["operation"]="process-handle-requested",["targetProcess"]="fixture-target"},["operation"],now)
        ];
    }
    static DetectionStarterFixture Fixture(string letter, string tenant, DetectionDomain domain, DetectionCondition condition, string exclusionField, string exclusionValue, Dictionary<string, string?> positive, Dictionary<string, string?> negative, string[] required, DateTimeOffset now, bool threshold = false)
    {
        var id = DetectionDsl.DeterministicId($"sprint12-starter-{letter}"); var exclusionId = DetectionDsl.DeterministicId($"sprint12-exclusion-{letter}"); var endpoint = DetectionDsl.DeterministicId($"sprint12-endpoint-{letter}"); positive["endpointId"] = endpoint.ToString("D"); negative["endpointId"] = endpoint.ToString("D"); var exclusionFields = new Dictionary<string, string?>(positive, StringComparer.Ordinal) { [exclusionField] = exclusionValue }; var rule = new DetectionDefinition("detection-rule.v1", id, 1, tenant, $"Sprint 12 starter {letter} — {domain}", "Controlled repository-owned fixture proving the detection engine; not production detection content.", DetectionRuleStatus.Draft, false, "system:sprint12", now, now, 60, 95, "controlled-engine-fixture", ["sprint12", "controlled-fixture", "not-production-content"], ["Execution"], [], [domain.ToString()], threshold ? DetectionRuleType.Threshold : DetectionRuleType.Event, domain, [], required, threshold ? 60 : 30, threshold ? new[] { "user" } : [], threshold ? 3 : 1, false, null, condition, DetectionExecutionMode.Live, new("detection+endpoint", 5), [exclusionId]); var exclusion = new DetectionExclusion(exclusionId, tenant, 1, $"Sprint 12 {letter} exact exclusion", exclusionField, exclusionValue, true, now.AddMinutes(-5), now.AddDays(7), "Controlled exclusion fixture", "system:sprint12"); DetectionEvidenceEvent Event(Dictionary<string, string?> fields, int offset = 0) => new(Guid.NewGuid(), tenant, domain, now.AddSeconds(offset), endpoint, "fixture-process", "fixture-entity", fields, $"postgresql://platform/sprint12_fixture_events/{letter}/{Guid.NewGuid():D}", Quality: ["complete"]); DetectionEvidenceEvent[] positives = threshold ? [Event(new(positive), 0), Event(new(positive), 1), Event(new(positive), 2)] : [Event(new(positive))]; DetectionEvidenceEvent[] suppression = threshold ? [Event(new(positive), 10), Event(new(positive), 11), Event(new(positive), 12), Event(new(positive), 20), Event(new(positive), 21), Event(new(positive), 22)] : [Event(new(positive), 0), Event(new(positive), 1)]; var missing = new Dictionary<string, string?>(positive, StringComparer.Ordinal); missing.Remove(required[0]); return new(rule, exclusion, [new($"{letter}-positive", "positive", positives, 1), new($"{letter}-negative", "negative", [Event(negative)], 0), new($"{letter}-boundary", "boundary", positives, 1), new($"{letter}-missing", "missing-field", [Event(missing)], 0), new($"{letter}-exclusion", "exclusion", [Event(exclusionFields)], 0, exclusionId), new($"{letter}-suppression", "suppression", suppression, 1)]);
    }
}
