namespace OpenSecurityPlatform.Foundation;
public sealed record DnsExportCreateRequest(string Format, DnsSearchRequest Query, string[]? Fields = null, int MaximumRecords = 500);
public sealed record DnsExportJob(Guid Id, string TenantId, string CreatedBy, FileExportState State, string Format, DnsSearchRequest Query, string[] Fields, int MaximumRecords, Guid OutputObjectId, Guid ManifestObjectId, Guid MetadataObjectId, DateTimeOffset CreatedAt, DateTimeOffset UpdatedAt, DateTimeOffset ExpiresAt, DateTimeOffset? StartedAt = null, DateTimeOffset? CompletedAt = null, int? RecordCount = null, long? OutputSize = null, string? OutputSha256 = null, string? ErrorCode = null, string? ErrorSummary = null);
public sealed record DnsExportManifest(string SchemaVersion, Guid ExportId, string TenantBinding, string Format, int RecordCount, DnsSearchRequest Query, string[] Fields, DateTimeOffset CreatedAt, DateTimeOffset CompletedAt, long ObjectSize, string Sha256, string SourceApplicationVersion, string DnsEventSchemaVersion, Guid OutputObjectId, Guid MetadataObjectId);
public interface IDnsExportRepository
{ Task<DnsExportJob> CreateAsync(string tenantId, string actor, DnsExportCreateRequest request, CancellationToken ct); Task<DnsExportJob?> GetAsync(string tenantId, Guid id, CancellationToken ct); Task<DnsExportJob?> ClaimAsync(CancellationToken ct); Task CompleteAsync(Guid id, int records, long size, string sha256, DateTimeOffset completedAt, CancellationToken ct); Task FailAsync(Guid id, string code, string summary, CancellationToken ct); Task<IReadOnlyList<DnsExportJob>> ExpireDueAsync(CancellationToken ct); Task AuditDownloadAsync(string tenantId, Guid id, string actor, CancellationToken ct); }

public sealed class FileDnsExportRepository : IDnsExportRepository
{
    readonly object _gate = new(); readonly List<DnsExportJob> _jobs = [];
    public Task<DnsExportJob> CreateAsync(string t, string a, DnsExportCreateRequest r, CancellationToken ct) { lock (_gate) { var n = DateTimeOffset.UtcNow; var j = new DnsExportJob(Guid.NewGuid(), t, a, FileExportState.Pending, r.Format, r.Query, r.Fields ?? [], r.MaximumRecords, Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), n, n, n.AddMinutes(15)); _jobs.Add(j); return Task.FromResult(j); } }
    public Task<DnsExportJob?> GetAsync(string t, Guid id, CancellationToken ct) { lock (_gate) return Task.FromResult(_jobs.FirstOrDefault(x => x.TenantId == t && x.Id == id)); }
    public Task<DnsExportJob?> ClaimAsync(CancellationToken ct) { lock (_gate) { var j = _jobs.FirstOrDefault(x => x.State == FileExportState.Pending); if (j is null) return Task.FromResult<DnsExportJob?>(null); var v = j with { State = FileExportState.Running, StartedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }; _jobs[_jobs.IndexOf(j)] = v; return Task.FromResult<DnsExportJob?>(v); } }
    public Task CompleteAsync(Guid id, int records, long size, string hash, DateTimeOffset at, CancellationToken ct) { lock (_gate) { var i = _jobs.FindIndex(x => x.Id == id); if (i >= 0) _jobs[i] = _jobs[i] with { State = FileExportState.Completed, RecordCount = records, OutputSize = size, OutputSha256 = hash, CompletedAt = at, UpdatedAt = at }; } return Task.CompletedTask; }
    public Task FailAsync(Guid id, string code, string summary, CancellationToken ct) { lock (_gate) { var i = _jobs.FindIndex(x => x.Id == id); if (i >= 0) _jobs[i] = _jobs[i] with { State = FileExportState.Failed, ErrorCode = code, ErrorSummary = summary }; } return Task.CompletedTask; }
    public Task<IReadOnlyList<DnsExportJob>> ExpireDueAsync(CancellationToken ct) { lock (_gate) { var x = _jobs.Where(x => x.State == FileExportState.Completed && x.ExpiresAt <= DateTimeOffset.UtcNow).ToArray(); foreach (var j in x) _jobs[_jobs.IndexOf(j)] = j with { State = FileExportState.Expired }; return Task.FromResult<IReadOnlyList<DnsExportJob>>(x); } }
    public Task AuditDownloadAsync(string t, Guid id, string a, CancellationToken ct) => Task.CompletedTask;
}
