using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace OpenSecurityPlatform.Foundation;

[JsonConverter(typeof(JsonStringEnumConverter<ExecutionEventKind>))]
public enum ExecutionEventKind { ProcessHandleOpened, ThreadHandleOpened, ThreadCreated, RemoteThreadCreated, MemoryAllocated, MemoryProtectionChanged, MemoryWritten, SectionCreated, SectionMapped, SectionUnmapped, ApcQueued, MemoryStateObserved }
public sealed record ExecutionNativeEvidence(string Provider, string? ProviderGuid, string Channel, int EventId, byte? Version, short? Opcode, int? Task, string NativeEventIdentity, string NativeOperation, string? NativeStatus, string RawEvidenceSha256);
public sealed record ExecutionProcessRef(string ProcessEntityId, int ProcessId, DateTimeOffset ProcessStartTime, string? ImagePath, string? UserSid, int? SessionId, string Evidence, string Confidence, bool PidReuseProtected);
public sealed record HandleEvidence(string HandleType, ulong? HandleValue, uint DesiredAccess, uint? GrantedAccess, string[] DesiredAccessFlags, string[] GrantedAccessFlags, string? Origin, bool OperationConfirmed);
public sealed record ThreadEvidence(string ThreadEntityId, int ThreadId, int? TargetThreadId, ulong? StartAddress, string? StartModuleEntityId, bool? CrossProcess, string LifecycleState, string? NativeStatus, bool TidReuseProtected);
public sealed record MemoryEvidence(string RegionEntityId, ulong BaseAddress, ulong Size, uint? AllocationType, uint? State, uint? ProtectionBefore, uint? ProtectionAfter, string[] ProtectionFlags, bool Readable, bool Writable, bool Executable, bool Guard, bool NoAccess, string Provenance, DateTimeOffset FirstObserved, DateTimeOffset LastObserved);
public sealed record SectionEvidence(string SectionEntityId, ulong? HandleValue, ulong? Size, uint? Protection, string? FileEntityId, string? BackingPath, bool? Anonymous, ulong? MappedBase, int? SharedProcessCount, string LifecycleState);
public sealed record ExecutionRelationship(string Relation, string Source, string Confidence, string? NativeCorrelationId, bool Ambiguous, DateTimeOffset FirstObserved, DateTimeOffset LastObserved);
public sealed record ExecutionObservation(Guid EventId, string SchemaVersion, ExecutionEventKind Kind, Guid EndpointId, Guid AgentId, string InstallationId, string CollectorId, string CollectorSource, string CollectorVersion, string SourcePlatform, ExecutionNativeEvidence Native, long Sequence, DateTimeOffset ObservedAt, DateTimeOffset? ReceivedAt, DateTimeOffset? IngestedAt, string NormalizationVersion, string EvidenceSha256, string[] DataQualityFlags, string QualityState, ExecutionProcessRef? SourceProcess, ExecutionProcessRef? TargetProcess, HandleEvidence? Handle, ThreadEvidence? Thread, MemoryEvidence? Memory, SectionEvidence? Section, ExecutionRelationship[] Relationships, bool Late = false, bool OutOfOrder = false);
public sealed record ExecutionEventBatch(Guid BatchId, Guid EndpointId, Guid AgentId, string InstallationId, long FirstSequence, long LastSequence, IReadOnlyList<ExecutionObservation> Events, string ContentSha256, string SchemaVersion = "execution-batch.v1", string Compression = "gzip");
public sealed record ExecutionBatchAcknowledgement(Guid BatchId, IReadOnlyList<Guid> AcceptedEventIds, IReadOnlyList<Guid> DuplicateEventIds, IReadOnlyDictionary<Guid, string> RejectedEventIds, long AcknowledgedThrough, bool GapDetected);
public sealed record ExecutionIngestResult(ExecutionBatchAcknowledgement Acknowledgement, int Accepted, int Duplicates, int Rejected, int SequenceGaps);
public sealed record ExecutionSearchRequest(Guid? EndpointId = null, string? SourceProcess = null, string? TargetProcess = null, int? SourcePid = null, int? TargetPid = null, string? Operation = null, string? HandleType = null, string? AccessFlag = null, uint? MemoryProtection = null, bool? ExecutableMemory = null, int? ThreadId = null, ulong? StartAddress = null, string? SectionIdentity = null, DateTimeOffset? From = null, DateTimeOffset? To = null, string? Quality = null, ExecutionEventKind? Kind = null, int PageSize = 100, string? Cursor = null);
public sealed record ExecutionEventPage(IReadOnlyList<ExecutionObservation> Items, string? NextCursor);
public sealed record ExecutionTelemetryHealth(Guid EndpointId, bool Enabled, string HandleCollectorState, string ThreadCollectorState, string MemoryCollectorState, string SectionCollectorState, DateTimeOffset? LastSourceEvent, DateTimeOffset? LastAcceptedEvent, long ProcessHandleEvents, long ThreadHandleEvents, long ThreadCreations, long CrossProcessThreadEvents, long Allocations, long ProtectionChanges, long MemoryWriteEvents, long SectionMappings, long ApcEvents, long RelationshipFailures, long SourceDrops, long SequenceGaps, long QueueDepth, long OldestQueuedSeconds, long QueueDrops, long ExcludedEvents, long Duplicates, long Rejections, string PolicyVersion, int? AppliedVersion, bool Drift, DateTimeOffset? LastUpload, long LastSequence, bool Elevated, string[] KnownLimitations, double? ProjectionLatencyMilliseconds = null, double? SearchLatencyMilliseconds = null);
public sealed record ExecutionExclusionRule(Guid Id, string Category, string Pattern, bool Enabled = true, string Reason = "", string Creator = "", DateTimeOffset? CreatedAt = null, long MatchCount = 0);
public sealed record ExecutionTelemetryPolicy(string Version = "execution-policy.v1", bool Enabled = true, bool HandleTelemetry = true, bool ProcessHandles = true, bool ThreadHandles = true, bool ThreadCreation = true, bool RemoteThreadEvents = true, bool MemoryAllocation = false, bool MemoryProtectionChanges = false, bool CrossProcessWriteMetadata = false, bool SectionMapping = false, bool ApcTelemetry = false, bool StartAddressMetadata = true, uint[]? IncludedAccessMasks = null, uint[]? ExcludedAccessMasks = null, string[]? IncludedSourceProcesses = null, string[]? IncludedTargetProcesses = null, string[]? ExcludedSourceProcesses = null, string[]? ExcludedTargetProcesses = null, string[]? ExcludedExactPaths = null, string[]? ExcludedOperations = null, bool ExcludeSameProcess = false, bool ExcludeSystemNoise = true, long MaximumQueueBytes = 128 * 1024 * 1024, int MaximumQueueAgeHours = 24, int MaximumBatchEvents = 200, int MaximumBatchBytes = 1024 * 1024, int FlushSeconds = 5, int MaximumEventsPerSecond = 2000, bool DiagnosticMode = false, bool ElevatedWholeTelemetryDisableConfirmed = false, IReadOnlyList<ExecutionExclusionRule>? ExclusionRules = null);
public sealed record ExecutionPolicyVersion(Guid Id, string TenantId, string Name, int Version, ExecutionTelemetryPolicy Policy, string Sha256, string Status, DateTimeOffset CreatedAt, string CreatedBy);
public sealed record EffectiveExecutionPolicy(ExecutionPolicyVersion Policy, string AssignmentSource, Guid EndpointId, DateTimeOffset? AcknowledgedAt, int? AppliedVersion, int? RejectedVersion, string? ValidationError, bool Drift);
public sealed record ExecutionPolicyAcknowledgement(Guid PolicyId, int Version, bool Applied, string? ValidationError, DateTimeOffset AcknowledgedAt);
public sealed record ExecutionExportCreateRequest(string Format, ExecutionSearchRequest Query, string[]? Fields = null, int MaximumRecords = 10000);
public sealed record ExecutionExportJob(Guid Id, string TenantId, string RequestedBy, FileExportState State, string Format, ExecutionSearchRequest Query, string[] Fields, int MaximumRecords, Guid OutputObjectId, Guid ManifestObjectId, Guid MetadataObjectId, DateTimeOffset CreatedAt, DateTimeOffset UpdatedAt, DateTimeOffset ExpiresAt, DateTimeOffset? StartedAt = null, DateTimeOffset? CompletedAt = null, int RecordCount = 0, long OutputSize = 0, string? OutputSha256 = null, string? ErrorCode = null, string? ErrorSummary = null);

public static partial class ExecutionSafety
{
    static readonly string[] Categories = ["source-process", "target-process", "exact-path", "signer-state", "access-mask", "operation", "same-process", "system-category"];
    [GeneratedRegex("^[a-z][a-z0-9._-]{1,63}$", RegexOptions.CultureInvariant)] private static partial Regex OperationPattern();
    public static string Hash(string value) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value.Normalize(NormalizationForm.FormKC)))).ToLowerInvariant();
    public static string EvidenceHash<T>(T value) => Hash(JsonSerializer.Serialize(value));
    public static string ThreadEntityId(Guid endpoint, string process, int tid, DateTimeOffset observed, string? native) => Hash($"{endpoint:D}:thread:{process}:{tid}:{native ?? observed.UtcTicks.ToString(System.Globalization.CultureInfo.InvariantCulture)}");
    public static string RegionEntityId(Guid endpoint, string process, ulong address, ulong size, long generation) => Hash($"{endpoint:D}:region:{process}:{address:x16}:{size:x16}:{generation}");
    public static string SectionEntityId(Guid endpoint, string installation, ulong? handle, string native) => Hash($"{endpoint:D}:{installation}:section:{handle:x}:{native}");
    public static bool ValidHash(string? value) => value is { Length: 64 } && value.All(Uri.IsHexDigit);
    public static bool ValidRange(ulong address, ulong size) => size is > 0 and <= 0x4000000000UL && address <= ulong.MaxValue - size;
    public static string[] AccessFlags(uint mask) { var values = new List<string>(); (uint Mask, string Name)[] known = [(0x0001, "PROCESS_TERMINATE"), (0x0002, "PROCESS_CREATE_THREAD"), (0x0008, "PROCESS_VM_OPERATION"), (0x0010, "PROCESS_VM_READ"), (0x0020, "PROCESS_VM_WRITE"), (0x0040, "PROCESS_DUP_HANDLE"), (0x0400, "PROCESS_QUERY_INFORMATION"), (0x0800, "PROCESS_SUSPEND_RESUME"), (0x1000, "PROCESS_QUERY_LIMITED_INFORMATION")]; foreach (var flag in known) if ((mask & flag.Mask) != 0) values.Add(flag.Name); return values.ToArray(); }
    public static string[] ProtectionFlags(uint mask) { var values = new List<string>(); if ((mask & 0xff) is 0x02 or 0x04 or 0x20 or 0x40) values.Add("READ"); if ((mask & 0xff) is 0x04 or 0x08 or 0x40 or 0x80) values.Add("WRITE"); if ((mask & 0xff) is 0x10 or 0x20 or 0x40 or 0x80) values.Add("EXECUTE"); if ((mask & 0x100) != 0) values.Add("GUARD"); if ((mask & 0xff) == 0x01) values.Add("NOACCESS"); return values.ToArray(); }
    public static IReadOnlyDictionary<string, string[]> Validate(ExecutionTelemetryPolicy policy) { var errors = new Dictionary<string, string[]>(); if (!policy.Enabled && !policy.ElevatedWholeTelemetryDisableConfirmed) errors["enabled"] = ["Disabling all execution telemetry requires elevated confirmation."]; if (policy.MaximumQueueBytes is < 1048576 or > 4294967296L || policy.MaximumQueueAgeHours is < 1 or > 720) errors["queue"] = ["Queue bounds are invalid."]; if (policy.MaximumBatchEvents is < 1 or > 1000 || policy.MaximumBatchBytes is < 1024 or > 4194304 || policy.FlushSeconds is < 1 or > 300 || policy.MaximumEventsPerSecond is < 1 or > 100000) errors["rate"] = ["Batch or rate bounds are invalid."]; foreach (var value in (policy.IncludedSourceProcesses ?? []).Concat(policy.IncludedTargetProcesses ?? []).Concat(policy.ExcludedSourceProcesses ?? []).Concat(policy.ExcludedTargetProcesses ?? []).Concat(policy.ExcludedExactPaths ?? []).Concat(policy.ExcludedOperations ?? [])) if (Unsafe(value)) errors[$"pattern.{Hash(value ?? "")[..8]}"] = ["Unsafe exclusion pattern."]; foreach (var rule in policy.ExclusionRules ?? []) if (!Categories.Contains(rule.Category, StringComparer.Ordinal) || Unsafe(rule.Pattern)) errors[$"exclusion.{rule.Id}"] = ["Unsafe execution exclusion."]; return errors; }
    public static bool ValidObservation(ExecutionObservation value, Guid endpoint, Guid agent, string installation) { var entity = value.Thread?.ThreadEntityId ?? value.Memory?.RegionEntityId ?? value.Section?.SectionEntityId ?? value.TargetProcess?.ProcessEntityId ?? value.SourceProcess?.ProcessEntityId; return value.EventId != Guid.Empty && value.SchemaVersion == "execution-event.v1" && value.EndpointId == endpoint && value.AgentId == agent && value.InstallationId == installation && value.Sequence > 0 && value.ObservedAt != default && ValidHash(entity) && ValidHash(value.EvidenceSha256) && ValidHash(value.Native.RawEvidenceSha256) && (value.SourceProcess is null || ValidProcess(value.SourceProcess)) && (value.TargetProcess is null || ValidProcess(value.TargetProcess)) && (value.Thread is null || value.Thread.ThreadId > 0 && ValidHash(value.Thread.ThreadEntityId)) && (value.Memory is null || ValidHash(value.Memory.RegionEntityId) && ValidRange(value.Memory.BaseAddress, value.Memory.Size)) && (value.Section is null || ValidHash(value.Section.SectionEntityId)); }
    static bool ValidProcess(ExecutionProcessRef value) => value.ProcessId > 0 && value.ProcessStartTime != default && ValidHash(value.ProcessEntityId) && Safe(value.ImagePath, 32767) && (value.UserSid is null || IdentitySafety.ValidSid(value.UserSid));
    static bool Unsafe(string? value) => string.IsNullOrWhiteSpace(value) || value.Trim() is "*" or "**" or "\\" or "/" || value.Length > 512 || value.Any(char.IsControl) || value.Count(x => x is '*' or '?') > 4;
    static bool Safe(string? value, int max) => value is null || value.Length <= max && !value.Any(char.IsControl);
}

public interface IExecutionTelemetryRepository { Task<ExecutionIngestResult> IngestAsync(string tenant, ExecutionEventBatch batch, ExecutionTelemetryHealth health, CancellationToken ct); Task<ExecutionEventPage> SearchAsync(string tenant, ExecutionSearchRequest request, CancellationToken ct); Task<ExecutionObservation?> GetAsync(string tenant, Guid eventId, CancellationToken ct); Task<ExecutionEventPage> EntityHistoryAsync(string tenant, Guid endpoint, string entity, int limit, CancellationToken ct); Task<ExecutionTelemetryHealth?> HealthAsync(string tenant, Guid endpoint, CancellationToken ct); Task<IReadOnlyList<ExecutionObservation>> ListAllAsync(CancellationToken ct); }
public interface IExecutionProjection { Task EnsureAsync(CancellationToken ct); Task UpsertAsync(string tenant, ExecutionObservation value, CancellationToken ct); Task<ExecutionEventPage> SearchAsync(string tenant, ExecutionSearchRequest request, CancellationToken ct); Task<bool> HealthAsync(CancellationToken ct); }
public interface IExecutionPolicyRepository { Task<IReadOnlyList<ExecutionPolicyVersion>> ListAsync(string tenant, CancellationToken ct); Task<ExecutionPolicyVersion> CreateAsync(string tenant, string actor, string name, ExecutionTelemetryPolicy policy, CancellationToken ct); Task AssignAsync(string tenant, Guid policyId, Guid? endpoint, string actor, CancellationToken ct); Task<EffectiveExecutionPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct); Task AcknowledgeAsync(string tenant, Guid endpoint, ExecutionPolicyAcknowledgement acknowledgement, CancellationToken ct); }
public interface IExecutionExportRepository { Task<ExecutionExportJob> CreateAsync(string tenant, string actor, ExecutionExportCreateRequest request, CancellationToken ct); Task<ExecutionExportJob?> GetAsync(string tenant, Guid id, CancellationToken ct); Task<ExecutionExportJob?> ClaimAsync(CancellationToken ct); Task CompleteAsync(Guid id, int count, long size, string sha256, DateTimeOffset at, CancellationToken ct); Task FailAsync(Guid id, string code, string summary, CancellationToken ct); }
