namespace OpenSecurityPlatform.Foundation;

public sealed class FileTunnelAnalyticsRepository : ITunnelAnalyticsRepository, ITunnelAnalyticsProjection
{
    readonly object gate = new(); readonly List<TunnelObservation> observations = []; readonly List<TunnelFinding> findings = []; readonly List<TunnelExclusion> exclusions = []; long relationshipRejects, queryRejects, failures;
    public Task<IReadOnlyList<TunnelFinding>> IngestAsync(string tenant, IReadOnlyList<TunnelObservation> values, CancellationToken ct)
    {
        if (values.Count is < 1 or > TunnelAnalyticsSafety.MaximumBatch) throw new EnrollmentConflictException("TUNNEL_BATCH_BOUNDS", "Observation batches contain 1-256 items.");
        lock (gate) { var created = new List<TunnelFinding>(); foreach (var x in values) { TunnelAnalyticsSafety.Validate(x, tenant); if (observations.Any(y => y.TenantId == tenant && y.ObservationId == x.ObservationId)) continue; observations.Add(x); try { var f = TunnelAnalyticsEngine.Evaluate(x, exclusions); if (f is not null) { findings.Add(f); created.Add(f); } } catch { failures++; throw; } } return Task.FromResult<IReadOnlyList<TunnelFinding>>(created); }
    }
    public Task<TunnelPage<TunnelObservation>> SearchObservationsAsync(string tenant, TunnelSearchRequest q, CancellationToken ct) { try { TunnelAnalyticsSafety.ValidateQuery(q); } catch { queryRejects++; throw; } lock (gate) return Task.FromResult(Page(observations.Where(x => x.TenantId == tenant && Match(x, q)).OrderByDescending(x => x.LastObserved), tenant, q)); }
    public Task<TunnelPage<TunnelFinding>> SearchFindingsAsync(string tenant, TunnelSearchRequest q, CancellationToken ct) { try { TunnelAnalyticsSafety.ValidateQuery(q); } catch { queryRejects++; throw; } lock (gate) return Task.FromResult(Page(findings.Where(x => x.TenantId == tenant && Match(x, q)).OrderByDescending(x => x.LastObserved), tenant, q)); }
    public Task<TunnelObservation?> GetObservationAsync(string tenant, Guid id, CancellationToken ct) { lock (gate) return Task.FromResult(observations.FirstOrDefault(x => x.TenantId == tenant && x.ObservationId == id)); }
    public Task<TunnelFinding?> GetFindingAsync(string tenant, Guid id, CancellationToken ct) { lock (gate) return Task.FromResult(findings.FirstOrDefault(x => x.TenantId == tenant && x.FindingId == id)); }
    public Task<TunnelChain> BuildChainAsync(string tenant, Guid id, int maximumDepth, CancellationToken ct)
    {
        if (maximumDepth is < 1 or > TunnelAnalyticsSafety.MaximumChainDepth) { relationshipRejects++; throw new EnrollmentConflictException("TUNNEL_CHAIN_BOUNDS", "Chain depth must be 1-4."); }
        lock (gate)
        {
            var root = observations.FirstOrDefault(x => x.TenantId == tenant && x.ObservationId == id) ?? throw new KeyNotFoundException(); var candidates = observations.Where(x => x.TenantId == tenant && x.EndpointId == root.EndpointId).OrderBy(x => x.FirstObserved).Take(TunnelAnalyticsSafety.MaximumChainNodes).ToArray(); var selected = new List<TunnelObservation> { root }; var edges = new List<TunnelRelationship>(); var current = root;
            for (var depth = 1; depth < maximumDepth; depth++) { var next = candidates.FirstOrDefault(x => x.ObservationId != current.ObservationId && !selected.Any(s => s.ObservationId == x.ObservationId) && x.FirstObserved <= current.LastObserved && x.LastObserved >= current.FirstObserved && SameEndpoint(current.Remote, x.Listener)); if (next is null) break; var evidence = current.EvidenceIds.Concat(next.EvidenceIds).Distinct().ToArray(); if (evidence.Length == 0) { relationshipRejects++; break; } edges.Add(new(TunnelAnalyticsSafety.StableId(tenant, current.ObservationId.ToString("D"), next.ObservationId.ToString("D")), tenant, current.ObservationId.ToString("D"), next.ObservationId.ToString("D"), TunnelRelationshipType.TunnelUsesUpstreamTunnel, evidence, current.EvidenceReferences.Concat(next.EvidenceReferences).Distinct().ToArray(), new[] { current.FirstObserved, next.FirstObserved }.Min(), new[] { current.LastObserved, next.LastObserved }.Max(), 80, "temporal-endpoint-evidence", false)); selected.Add(next); current = next; }
            return Task.FromResult(new TunnelChain(TunnelAnalyticsSafety.StableId(tenant, id.ToString("D"), "chain"), tenant, root.EndpointId, selected.Select(x => x.ObservationId).ToArray(), edges.ToArray(), edges.Count, selected.Count >= TunnelAnalyticsSafety.MaximumChainNodes, edges.Count == 0 ? ["No source-backed adjacent tunnel hop was observable."] : []));
        }
    }
    public Task<TunnelExclusion> AddExclusionAsync(string tenant, TunnelExclusion x, string actor, CancellationToken ct) { if (x.TenantId != tenant || x.ExclusionId == Guid.Empty || x.EndsAt <= x.StartsAt || x.EndsAt - x.StartsAt > TimeSpan.FromDays(365) || !new[] { "processEntityId", "kind", "remoteAddress", "hostname" }.Contains(x.Field, StringComparer.OrdinalIgnoreCase)) throw new EnrollmentConflictException("TUNNEL_EXCLUSION_INVALID", "Exclusion is invalid or unbounded."); lock (gate) { var v = x with { Version = Math.Max(1, x.Version), CreatedBy = actor, CreatedAt = DateTimeOffset.UtcNow }; exclusions.Add(v); return Task.FromResult(v); } }
    public Task<IReadOnlyList<TunnelExclusion>> ExclusionsAsync(string tenant, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<TunnelExclusion>>(exclusions.Where(x => x.TenantId == tenant).ToArray()); }
    public Task<TunnelHealth> HealthAsync(string tenant, CancellationToken ct) { lock (gate) { var o = observations.Where(x => x.TenantId == tenant).ToArray(); var f = findings.Where(x => x.TenantId == tenant).ToArray(); return Task.FromResult(new TunnelHealth(o.LongLength, f.LongLength, f.LongCount(x => x.Excluded), relationshipRejects, queryRejects, failures, TunnelAnalyticsSafety.MaximumChainDepth, "NOT OBSERVABLE BY SOURCE", DateTimeOffset.UtcNow, f.LongCount(x => x.Confidence == TunnelConfidence.High), o.LongCount(x => x.Listener is not null), o.LongCount(x => x.Kind == TunnelKind.NestedTunnel), o.LongCount(x => x.Kind == TunnelKind.DnsTunnel), o.LongCount(x => x.ProcessEntityId is null))); } }
    public Task<(long Observations, long Findings)> CountsAsync(string tenant, CancellationToken ct) { lock (gate) return Task.FromResult((observations.LongCount(x => x.TenantId == tenant), findings.LongCount(x => x.TenantId == tenant))); }
    public Task EnsureAsync(CancellationToken ct) => Task.CompletedTask; public Task UpsertObservationAsync(TunnelObservation x, CancellationToken ct) => Task.CompletedTask; public Task UpsertFindingAsync(TunnelFinding x, CancellationToken ct) => Task.CompletedTask;
    static bool Match(TunnelObservation x, TunnelSearchRequest q) => (q.EndpointId is null || x.EndpointId == q.EndpointId) && (q.ProcessEntityId is null || x.ProcessEntityId == q.ProcessEntityId) && (q.Kind is null || x.Kind == q.Kind) && (q.From is null || x.LastObserved >= q.From) && (q.To is null || x.FirstObserved <= q.To);
    static bool Match(TunnelFinding x, TunnelSearchRequest q) => (q.EndpointId is null || x.EndpointId == q.EndpointId) && (q.ProcessEntityId is null || x.ProcessEntityId == q.ProcessEntityId) && (q.Kind is null || x.Kind == q.Kind) && (q.MinimumConfidence is null || x.Confidence >= q.MinimumConfidence) && (q.From is null || x.LastObserved >= q.From) && (q.To is null || x.FirstObserved <= q.To);
    static bool SameEndpoint(TunnelEndpoint? remote, TunnelEndpoint? listener) => remote is not null && listener is not null && remote.Port is not null && remote.Port == listener.Port && string.Equals(remote.Address, listener.Address, StringComparison.OrdinalIgnoreCase) && (remote.Protocol is null || listener.Protocol is null || string.Equals(remote.Protocol, listener.Protocol, StringComparison.OrdinalIgnoreCase));
    static TunnelPage<T> Page<T>(IEnumerable<T> source, string tenant, TunnelSearchRequest q) { var offset = TunnelAnalyticsSafety.Cursor(tenant, q.Cursor); var page = source.Skip(offset).Take(q.PageSize + 1).ToArray(); return new(page.Take(q.PageSize).ToArray(), page.Length > q.PageSize ? TunnelAnalyticsSafety.Cursor(tenant, offset + q.PageSize) : null); }
    public TunnelObservation[] SnapshotObservations(string tenant) { lock (gate) return observations.Where(x => x.TenantId == tenant).ToArray(); }
    public TunnelFinding[] SnapshotFindings(string tenant) { lock (gate) return findings.Where(x => x.TenantId == tenant).ToArray(); }
    public TunnelExclusion[] SnapshotExclusions(string tenant) { lock (gate) return exclusions.Where(x => x.TenantId == tenant).ToArray(); }
}
