namespace OpenSecurityPlatform.Foundation;

public sealed class FileExecutionTelemetryRepository : IExecutionTelemetryRepository, IExecutionProjection
{
    readonly object _gate = new(); readonly Dictionary<string, ExecutionObservation> _events = []; readonly Dictionary<string, ExecutionTelemetryHealth> _health = [];
    public Task<ExecutionIngestResult> IngestAsync(string tenant, ExecutionEventBatch batch, ExecutionTelemetryHealth health, CancellationToken ct) { lock (_gate) { var accepted = new List<Guid>(); var duplicates = new List<Guid>(); var rejected = new Dictionary<Guid, string>(); foreach (var value in batch.Events) { if (!ExecutionSafety.ValidObservation(value, batch.EndpointId, batch.AgentId, batch.InstallationId)) { rejected[value.EventId] = "invalid-event"; continue; } var key = $"{tenant}:{value.EventId}"; if (_events.ContainsKey(key)) duplicates.Add(value.EventId); else { _events[key] = value with { ReceivedAt = DateTimeOffset.UtcNow, IngestedAt = DateTimeOffset.UtcNow }; accepted.Add(value.EventId); } } _health[$"{tenant}:{health.EndpointId}"] = health; var ack = new ExecutionBatchAcknowledgement(batch.BatchId, accepted, duplicates, rejected, batch.LastSequence, false); return Task.FromResult(new ExecutionIngestResult(ack, accepted.Count, duplicates.Count, rejected.Count, 0)); } }
    public Task<ExecutionEventPage> SearchAsync(string tenant, ExecutionSearchRequest r, CancellationToken ct) { lock (_gate) { IEnumerable<ExecutionObservation> q = _events.Where(x => x.Key.StartsWith(tenant + ':', StringComparison.Ordinal)).Select(x => x.Value); if (r.EndpointId is { } e) q = q.Where(x => x.EndpointId == e); if (r.SourceProcess is { } sp) q = q.Where(x => x.SourceProcess?.ProcessEntityId == sp || (x.SourceProcess?.ImagePath ?? "").Contains(sp, StringComparison.OrdinalIgnoreCase)); if (r.TargetProcess is { } tp) q = q.Where(x => x.TargetProcess?.ProcessEntityId == tp || (x.TargetProcess?.ImagePath ?? "").Contains(tp, StringComparison.OrdinalIgnoreCase)); if (r.SourcePid is { } s) q = q.Where(x => x.SourceProcess?.ProcessId == s); if (r.TargetPid is { } t) q = q.Where(x => x.TargetProcess?.ProcessId == t); if (r.Operation is { } o) q = q.Where(x => x.Native.NativeOperation.Equals(o, StringComparison.OrdinalIgnoreCase)); if (r.HandleType is { } h) q = q.Where(x => x.Handle?.HandleType.Equals(h, StringComparison.OrdinalIgnoreCase) == true); if (r.AccessFlag is { } a) q = q.Where(x => x.Handle?.DesiredAccessFlags.Contains(a, StringComparer.OrdinalIgnoreCase) == true || x.Handle?.GrantedAccessFlags.Contains(a, StringComparer.OrdinalIgnoreCase) == true); if (r.MemoryProtection is { } p) q = q.Where(x => x.Memory?.ProtectionAfter == p || x.Memory?.ProtectionBefore == p); if (r.ExecutableMemory is { } ex) q = q.Where(x => x.Memory?.Executable == ex); if (r.ThreadId is { } tid) q = q.Where(x => x.Thread?.ThreadId == tid || x.Thread?.TargetThreadId == tid); if (r.StartAddress is { } sa) q = q.Where(x => x.Thread?.StartAddress == sa); if (r.SectionIdentity is { } si) q = q.Where(x => x.Section?.SectionEntityId == si); if (r.From is { } f) q = q.Where(x => x.ObservedAt >= f); if (r.To is { } to) q = q.Where(x => x.ObservedAt <= to); if (r.Quality is { } quality) q = q.Where(x => x.QualityState.Equals(quality, StringComparison.OrdinalIgnoreCase) || x.DataQualityFlags.Contains(quality, StringComparer.OrdinalIgnoreCase)); if (r.Kind is { } kind) q = q.Where(x => x.Kind == kind); return Task.FromResult(new ExecutionEventPage(q.OrderByDescending(x => x.ObservedAt).Take(Math.Clamp(r.PageSize, 1, 500)).ToArray(), null)); } }
    public Task<ExecutionObservation?> GetAsync(string tenant, Guid eventId, CancellationToken ct) { lock (_gate) return Task.FromResult(_events.GetValueOrDefault($"{tenant}:{eventId}")); }
    public Task<ExecutionEventPage> EntityHistoryAsync(string tenant, Guid endpoint, string entity, int limit, CancellationToken ct) { lock (_gate) return Task.FromResult(new ExecutionEventPage(_events.Where(x => x.Key.StartsWith(tenant + ':', StringComparison.Ordinal)).Select(x => x.Value).Where(x => x.EndpointId == endpoint && (x.Thread?.ThreadEntityId == entity || x.Memory?.RegionEntityId == entity || x.Section?.SectionEntityId == entity || x.SourceProcess?.ProcessEntityId == entity || x.TargetProcess?.ProcessEntityId == entity)).OrderByDescending(x => x.ObservedAt).Take(Math.Clamp(limit, 1, 500)).ToArray(), null)); }
    public Task<ExecutionTelemetryHealth?> HealthAsync(string tenant, Guid endpoint, CancellationToken ct) { lock (_gate) return Task.FromResult(_health.GetValueOrDefault($"{tenant}:{endpoint}")); }
    public Task<IReadOnlyList<ExecutionObservation>> ListAllAsync(CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<ExecutionObservation>>(_events.Values.ToArray()); }
    public Task EnsureAsync(CancellationToken ct) => Task.CompletedTask; public Task UpsertAsync(string tenant, ExecutionObservation value, CancellationToken ct) { lock (_gate) _events[$"{tenant}:{value.EventId}"] = value; return Task.CompletedTask; }
    public Task<bool> HealthAsync(CancellationToken ct) => Task.FromResult(true);
}

public sealed class FileExecutionPolicyRepository : IExecutionPolicyRepository
{
    readonly object _gate = new(); readonly List<ExecutionPolicyVersion> _versions = []; readonly Dictionary<string, Guid> _assignments = []; readonly Dictionary<string, ExecutionPolicyAcknowledgement> _acks = [];
    public Task<IReadOnlyList<ExecutionPolicyVersion>> ListAsync(string tenant, CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<ExecutionPolicyVersion>>(_versions.Where(x => x.TenantId == tenant).ToArray()); }
    public Task<ExecutionPolicyVersion> CreateAsync(string tenant, string actor, string name, ExecutionTelemetryPolicy policy, CancellationToken ct) { var errors = ExecutionSafety.Validate(policy); if (errors.Count > 0) throw new EnrollmentConflictException("EXECUTION_POLICY_INVALID", string.Join(' ', errors.SelectMany(x => x.Value))); lock (_gate) { var value = new ExecutionPolicyVersion(Guid.NewGuid(), tenant, name, _versions.Where(x => x.TenantId == tenant && x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1, policy, ExecutionSafety.EvidenceHash(policy), "active", DateTimeOffset.UtcNow, actor); _versions.Add(value); return Task.FromResult(value); } }
    public Task AssignAsync(string tenant, Guid policyId, Guid? endpoint, string actor, CancellationToken ct) { lock (_gate) { if (!_versions.Any(x => x.TenantId == tenant && x.Id == policyId)) throw new EnrollmentConflictException("EXECUTION_POLICY_NOT_FOUND", "Policy unavailable."); _assignments[$"{tenant}:{endpoint?.ToString() ?? "default"}"] = policyId; return Task.CompletedTask; } }
    public async Task<EffectiveExecutionPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct) { var all = await ListAsync(tenant, ct); lock (_gate) { var id = _assignments.GetValueOrDefault($"{tenant}:{endpoint}", _assignments.GetValueOrDefault($"{tenant}:default")); var value = all.FirstOrDefault(x => x.Id == id) ?? new(Guid.Empty, tenant, "safe-default", 0, new(), ExecutionSafety.EvidenceHash(new ExecutionTelemetryPolicy()), "default", DateTimeOffset.UnixEpoch, "system"); var ack = _acks.GetValueOrDefault($"{tenant}:{endpoint}"); return new(value, id == Guid.Empty ? "default" : "assigned", endpoint, ack?.AcknowledgedAt, ack?.Applied == true ? ack.Version : null, ack?.Applied == false ? ack.Version : null, ack?.ValidationError, ack is null || ack.Version != value.Version); } }
    public Task AcknowledgeAsync(string tenant, Guid endpoint, ExecutionPolicyAcknowledgement acknowledgement, CancellationToken ct) { lock (_gate) { _acks[$"{tenant}:{endpoint}"] = acknowledgement; return Task.CompletedTask; } }
}

public sealed class FileExecutionExportRepository : IExecutionExportRepository
{
    readonly object _gate = new(); readonly Dictionary<Guid, ExecutionExportJob> _jobs = []; public Task<ExecutionExportJob> CreateAsync(string tenant, string actor, ExecutionExportCreateRequest request, CancellationToken ct) { lock (_gate) { var now = DateTimeOffset.UtcNow; var job = new ExecutionExportJob(Guid.NewGuid(), tenant, actor, FileExportState.Pending, request.Format, request.Query with { Cursor = null }, request.Fields ?? [], request.MaximumRecords, Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), now, now, now.AddMinutes(15)); _jobs[job.Id] = job; return Task.FromResult(job); } }
    public Task<ExecutionExportJob?> GetAsync(string tenant, Guid id, CancellationToken ct) { lock (_gate) return Task.FromResult(_jobs.GetValueOrDefault(id) is { } x && x.TenantId == tenant ? x : null); }
    public Task<ExecutionExportJob?> ClaimAsync(CancellationToken ct) { lock (_gate) { var value = _jobs.Values.FirstOrDefault(x => x.State == FileExportState.Pending); if (value is null) return Task.FromResult<ExecutionExportJob?>(null); var changed = value with { State = FileExportState.Running, StartedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }; _jobs[value.Id] = changed; return Task.FromResult<ExecutionExportJob?>(changed); } }
    public Task CompleteAsync(Guid id, int count, long size, string sha256, DateTimeOffset at, CancellationToken ct) { lock (_gate) _jobs[id] = _jobs[id] with { State = FileExportState.Completed, RecordCount = count, OutputSize = size, OutputSha256 = sha256, CompletedAt = at, UpdatedAt = at }; return Task.CompletedTask; }
    public Task FailAsync(Guid id, string code, string summary, CancellationToken ct) { lock (_gate) _jobs[id] = _jobs[id] with { State = FileExportState.Failed, ErrorCode = code, ErrorSummary = summary[..Math.Min(512, summary.Length)], UpdatedAt = DateTimeOffset.UtcNow }; return Task.CompletedTask; }
}
