namespace OpenSecurityPlatform.Foundation;

public sealed class FileNetworkTelemetryRepository : INetworkTelemetryRepository, INetworkProjection
{
    readonly object _gate = new(); readonly List<(string Tenant, NetworkObservation Event)> _events = [];
    readonly HashSet<(string, Guid)> _ids = []; readonly Dictionary<string, NetworkConnectionView> _connections = [];
    readonly Dictionary<(string, Guid), NetworkTelemetryHealth> _health = [];
    NetworkProjectionRebuildProgress _progress = new(Guid.Empty, "filesystem", "global", "idle", DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch, null, 0, 0, 0, "filesystem", null, false);
    public Task EnsureAsync(CancellationToken ct) => Task.CompletedTask;
    public Task<NetworkIngestResult> IngestAsync(string tenant, NetworkEventBatch batch, NetworkTelemetryHealth health, CancellationToken ct) { lock (_gate) { var a = new List<Guid>(); var d = new List<Guid>(); foreach (var x in batch.Events.OrderBy(x => x.Sequence)) { if (!_ids.Add((tenant, x.EventId))) { d.Add(x.EventId); continue; } a.Add(x.EventId); _events.Add((tenant, x)); Apply(tenant, x); } _health[(tenant, batch.EndpointId)] = health; return Task.FromResult(new NetworkIngestResult(new(batch.BatchId, a, d, new Dictionary<Guid, string>(), batch.LastSequence, false), a.Count, d.Count, 0, 0)); } }
    void Apply(string tenant, NetworkObservation x) { var id = $"{tenant}:{x.EndpointId}:{x.ConnectionEntityId}"; var p = _connections.GetValueOrDefault(id); _connections[id] = new(tenant, x.EndpointId, x.ConnectionEntityId, x.Process?.ProcessEntityId, x.Protocol, x.Local.AddressFamily, x.Local, x.Remote, x.Direction, p?.FirstObserved ?? x.ObservedAt, x.ObservedAt, x.Kind == NetworkEventKind.ConnectionAttempted ? x.ObservedAt : p?.AttemptedAt, x.Kind == NetworkEventKind.ConnectionEstablished ? x.ObservedAt : p?.EstablishedAt, x.Kind == NetworkEventKind.ConnectionFailed ? x.ObservedAt : p?.FailedAt, x.Kind == NetworkEventKind.ConnectionClosed ? x.ObservedAt : p?.ClosedAt, x.DurationMilliseconds, x.State, x.EventId, x.SourceConfidence, x.DataQualityFlags, x.LifecycleCompleteness, x.Process, x.User, x.Hostname); }
    IEnumerable<NetworkObservation> Filter(string tenant, NetworkSearchRequest q) => _events.Where(x => x.Tenant == tenant).Select(x => x.Event).Where(x => (q.EndpointId is null || x.EndpointId == q.EndpointId) && (q.From is null || x.ObservedAt >= q.From) && (q.To is null || x.ObservedAt <= q.To) && (string.IsNullOrWhiteSpace(q.LocalAddress) || x.Local.Address.Contains(q.LocalAddress, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(q.RemoteAddress) || (x.Remote?.Address.Contains(q.RemoteAddress, StringComparison.OrdinalIgnoreCase) ?? false)) && (q.LocalPort is null || x.Local.Port == q.LocalPort) && (q.RemotePort is null || x.Remote?.Port == q.RemotePort) && (string.IsNullOrWhiteSpace(q.Protocol) || x.Protocol.Equals(q.Protocol, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(q.AddressFamily) || x.Local.AddressFamily.Equals(q.AddressFamily, StringComparison.OrdinalIgnoreCase)) && (q.Direction is null || x.Direction == q.Direction) && (q.State is null || x.State == q.State) && (q.Operation is null || x.Kind == q.Operation) && (string.IsNullOrWhiteSpace(q.Process) || x.Process?.ProcessEntityId == q.Process || (x.Process?.Image?.Contains(q.Process, StringComparison.OrdinalIgnoreCase) ?? false)) && (string.IsNullOrWhiteSpace(q.User) || x.User == q.User) && (string.IsNullOrWhiteSpace(q.Collector) || x.CollectorSource == q.Collector) && (string.IsNullOrWhiteSpace(q.DataQuality) || x.DataQualityFlags.Contains(q.DataQuality)) && (q.Listener is null || q.Listener == (x.Kind is NetworkEventKind.ListenerStarted or NetworkEventKind.ListenerStopped)));
    public Task<NetworkEventPage> SearchAsync(string tenant, NetworkSearchRequest q, CancellationToken ct) { lock (_gate) return Task.FromResult(new NetworkEventPage(Filter(tenant, q).OrderByDescending(x => x.ObservedAt).ThenByDescending(x => x.EventId).Take(Math.Clamp(q.PageSize, 1, 500)).ToArray(), null)); }
    public Task<NetworkObservation?> GetEventAsync(string tenant, Guid id, CancellationToken ct) { lock (_gate) return Task.FromResult(_events.Where(x => x.Tenant == tenant && x.Event.EventId == id).Select(x => (NetworkObservation?)x.Event).FirstOrDefault()); }
    public Task<NetworkConnectionView?> GetConnectionAsync(string tenant, Guid endpoint, string id, CancellationToken ct) { lock (_gate) return Task.FromResult(_connections.GetValueOrDefault($"{tenant}:{endpoint}:{id}")); }
    Task<NetworkEventPage> History(string tenant, Guid endpoint, DateTimeOffset from, DateTimeOffset to, int limit, Func<NetworkObservation, bool> predicate) { lock (_gate) return Task.FromResult(new NetworkEventPage(_events.Where(x => x.Tenant == tenant && x.Event.EndpointId == endpoint && x.Event.ObservedAt >= from && x.Event.ObservedAt <= to && predicate(x.Event)).Select(x => x.Event).OrderBy(x => x.ObservedAt).ThenBy(x => x.EventId).Take(Math.Clamp(limit, 1, 500)).ToArray(), null)); }
    public Task<NetworkEventPage> ConnectionHistoryAsync(string tenant, Guid endpoint, string id, DateTimeOffset from, DateTimeOffset toInclusive, int limit, CancellationToken ct) => History(tenant, endpoint, from, toInclusive, limit, x => x.ConnectionEntityId == id);
    public Task<NetworkEventPage> EndpointTimelineAsync(string tenant, Guid endpoint, NetworkSearchRequest q, CancellationToken ct) => SearchAsync(tenant, q with { EndpointId = endpoint }, ct);
    public Task<NetworkEventPage> ProcessNetworkAsync(string tenant, Guid endpoint, string id, DateTimeOffset from, DateTimeOffset toInclusive, int limit, CancellationToken ct) => History(tenant, endpoint, from, toInclusive, limit, x => x.Process?.ProcessEntityId == id);
    public Task<NetworkConnectionPage> ListenersAsync(string tenant, Guid endpoint, int limit, CancellationToken ct) { lock (_gate) return Task.FromResult(new NetworkConnectionPage(_connections.Values.Where(x => x.TenantId == tenant && x.EndpointId == endpoint && x.State == NetworkConnectionState.Listening).OrderByDescending(x => x.LastObserved).Take(Math.Clamp(limit, 1, 500)).ToArray(), null)); }
    public Task<NetworkTelemetryHealth?> HealthAsync(string tenant, Guid endpoint, CancellationToken ct) { lock (_gate) return Task.FromResult(_health.GetValueOrDefault((tenant, endpoint))); }
    public Task<IReadOnlyList<NetworkObservation>> ListAllAsync(CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<NetworkObservation>>(_events.Select(x => x.Event).ToArray()); }
    public Task UpsertAsync(string tenant, NetworkObservation x, CancellationToken ct) { lock (_gate) { if (_ids.Add((tenant, x.EventId))) _events.Add((tenant, x)); Apply(tenant, x); } return Task.CompletedTask; }
    Task<NetworkEventPage> INetworkProjection.SearchAsync(string tenant, NetworkSearchRequest q, CancellationToken ct) => SearchAsync(tenant, q, ct);
    public Task<ProcessProjectionRebuildResult> RebuildAsync(IReadOnlyList<NetworkObservation> events, CancellationToken ct) { var n = DateTimeOffset.UtcNow; _progress = new(Guid.NewGuid(), "filesystem", "global", "completed", n, n, n, events.Count, events.Count, 0, "filesystem", null, false); return Task.FromResult(new ProcessProjectionRebuildResult("filesystem", events.Count, TimeSpan.Zero, true)); }
    public NetworkProjectionRebuildProgress GetRebuildProgress() => _progress;
    public Task<bool> HealthAsync(CancellationToken ct) => Task.FromResult(true);
}
