namespace OpenSecurityPlatform.Foundation;
public sealed class FileNetworkPolicyRepository : INetworkPolicyRepository
{
    readonly object _gate = new(); readonly List<NetworkPolicyVersion> _versions = []; readonly Dictionary<(string, Guid?), Guid> _assignments = []; readonly Dictionary<(string, Guid), NetworkPolicyAcknowledgement> _acks = [];
    public Task<IReadOnlyList<NetworkPolicyVersion>> ListAsync(string tenant, CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<NetworkPolicyVersion>>(_versions.Where(x => x.TenantId == tenant).OrderBy(x => x.Name).ThenByDescending(x => x.Version).ToArray()); }
    public Task<NetworkPolicyVersion> CreateAsync(string tenant, string actor, string name, NetworkTelemetryPolicy policy, CancellationToken ct) { if (NetworkPolicyValidation.Validate(policy).Count > 0) throw new EnrollmentConflictException("NETWORK_POLICY_INVALID", "Network policy invalid."); lock (_gate) { var version = _versions.Where(x => x.TenantId == tenant && x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1; var p = policy with { Version = $"network-policy.v{version}" }; var v = new NetworkPolicyVersion(Guid.NewGuid(), tenant, name, version, p, NetworkEvidence.CanonicalSha256(p), "active", DateTimeOffset.UtcNow, actor); _versions.Add(v); return Task.FromResult(v); } }
    public Task AssignAsync(string tenant, Guid id, Guid? endpoint, string actor, CancellationToken ct) { lock (_gate) { if (!_versions.Any(x => x.TenantId == tenant && x.Id == id)) throw new EnrollmentConflictException("NETWORK_POLICY_NOT_FOUND", "Network policy not found."); _assignments[(tenant, endpoint)] = id; } return Task.CompletedTask; }
    public Task<EffectiveNetworkPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct) { lock (_gate) { var key = _assignments.ContainsKey((tenant, endpoint)) ? (tenant, (Guid?)endpoint) : (tenant, (Guid?)null); if (_assignments.TryGetValue(key, out var id) && _versions.FirstOrDefault(x => x.TenantId == tenant && x.Id == id) is { } v) { _acks.TryGetValue((tenant, endpoint), out var a); return Task.FromResult(new EffectiveNetworkPolicy(v, key.Item2 is null ? "tenant-default" : "endpoint", endpoint, a?.PolicyId == v.Id ? a.AcknowledgedAt : null, a?.PolicyId == v.Id && a.Applied ? a.Version : null, a?.PolicyId == v.Id && !a.Applied ? a.Version : null, a?.PolicyId == v.Id ? a.ValidationError : null, a?.PolicyId != v.Id || a.Applied != true || a.Version != v.Version)); } var p = new NetworkTelemetryPolicy(); var fallback = new NetworkPolicyVersion(Guid.Empty, tenant, "safe-default", 1, p, new string('0', 64), "implicit", DateTimeOffset.UnixEpoch, "system"); return Task.FromResult(new EffectiveNetworkPolicy(fallback, "implicit-default", endpoint, null, null, null, null, true)); } }
    public Task AcknowledgeAsync(string tenant, Guid endpoint, NetworkPolicyAcknowledgement a, CancellationToken ct) { lock (_gate) _acks[(tenant, endpoint)] = a; return Task.CompletedTask; }
    public async Task<NetworkPolicyVersion> RollbackAsync(string tenant, Guid id, int version, string actor, CancellationToken ct) { var source = (await ListAsync(tenant, ct)).SingleOrDefault(x => x.Id == id && x.Version == version) ?? throw new EnrollmentConflictException("NETWORK_POLICY_NOT_FOUND", "Rollback version not found."); return await CreateAsync(tenant, actor, source.Name, source.Policy, ct); }
}
