namespace OpenSecurityPlatform.Foundation;

public sealed class FileRegistryPolicyRepository : IRegistryPolicyRepository
{
    private readonly object _gate = new(); private readonly List<RegistryPolicyVersion> _versions = []; private readonly Dictionary<(string, Guid?), Guid> _assignments = []; private readonly Dictionary<(string, Guid), RegistryPolicyAcknowledgement> _acks = [];
    public Task<IReadOnlyList<RegistryPolicyVersion>> ListAsync(string tenant, CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<RegistryPolicyVersion>>(_versions.Where(x => x.TenantId == tenant).OrderBy(x => x.Name).ThenByDescending(x => x.Version).ToArray()); }
    public Task<RegistryPolicyVersion> CreateAsync(string tenant, string actor, string name, RegistryTelemetryPolicy policy, CancellationToken ct) { if (RegistryPolicyValidation.Validate(policy).Count > 0) throw new EnrollmentConflictException("REGISTRY_POLICY_INVALID", "Registry policy invalid."); lock (_gate) { var version = _versions.Where(x => x.TenantId == tenant && x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1; var p = policy with { Version = $"registry-policy.v{version}" }; var value = new RegistryPolicyVersion(Guid.NewGuid(), tenant, name, version, p, RegistryEvidence.CanonicalSha256(p), "active", DateTimeOffset.UtcNow, actor); _versions.Add(value); return Task.FromResult(value); } }
    public Task AssignAsync(string tenant, Guid id, Guid? endpoint, string actor, CancellationToken ct) { lock (_gate) { if (!_versions.Any(x => x.TenantId == tenant && x.Id == id)) throw new EnrollmentConflictException("REGISTRY_POLICY_NOT_FOUND", "Registry policy not found."); _assignments[(tenant, endpoint)] = id; } return Task.CompletedTask; }
    public Task<EffectiveRegistryPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct) { lock (_gate) { var key = _assignments.ContainsKey((tenant, endpoint)) ? (tenant, (Guid?)endpoint) : (tenant, (Guid?)null); if (_assignments.TryGetValue(key, out var id) && _versions.FirstOrDefault(x => x.TenantId == tenant && x.Id == id) is { } v) { _acks.TryGetValue((tenant, endpoint), out var ack); return Task.FromResult(new EffectiveRegistryPolicy(v, key.Item2 is null ? "tenant-default" : "endpoint", endpoint, ack?.PolicyId == v.Id ? ack.AcknowledgedAt : null, ack?.PolicyId == v.Id && ack.Applied ? ack.Version : null, ack?.PolicyId == v.Id && !ack.Applied ? ack.Version : null, ack?.PolicyId == v.Id ? ack.ValidationError : null, ack?.PolicyId != v.Id || ack.Applied != true || ack.Version != v.Version)); } var fallback = new RegistryPolicyVersion(Guid.Empty, tenant, "safe-default", 1, new(IncludedPaths: [@"\Software\OpenSecurityPlatform\Sprint4"]), new string('0', 64), "implicit", DateTimeOffset.UnixEpoch, "system"); return Task.FromResult(new EffectiveRegistryPolicy(fallback, "implicit-default", endpoint, null, null, null, null, true)); } }
    public Task AcknowledgeAsync(string tenant, Guid endpoint, RegistryPolicyAcknowledgement a, CancellationToken ct) { lock (_gate) _acks[(tenant, endpoint)] = a; return Task.CompletedTask; }
    public async Task<RegistryPolicyVersion> RollbackAsync(string tenant, Guid id, int version, string actor, CancellationToken ct) { var source = (await ListAsync(tenant, ct)).SingleOrDefault(x => x.Id == id && x.Version == version) ?? throw new EnrollmentConflictException("REGISTRY_POLICY_NOT_FOUND", "Rollback version not found."); return await CreateAsync(tenant, actor, source.Name, source.Policy, ct); }
}
