namespace OpenSecurityPlatform.Foundation;

public sealed class FilePersistenceTelemetryRepository : IPersistenceTelemetryRepository, IPersistenceProjection
{
    readonly object _gate = new(); readonly Dictionary<string, PersistenceObservation> _events = [];
    readonly Dictionary<string, PersistenceTelemetryHealth> _health = [];
    public Task<PersistenceIngestResult> IngestAsync(string tenant, PersistenceEventBatch batch, PersistenceTelemetryHealth health, CancellationToken ct)
    { lock (_gate) { var accepted = new List<Guid>(); var duplicates = new List<Guid>(); foreach (var value in batch.Events) { var key = $"{tenant}:{value.EventId}"; if (_events.ContainsKey(key)) duplicates.Add(value.EventId); else { _events[key] = value with { ReceivedAt = DateTimeOffset.UtcNow, IngestedAt = DateTimeOffset.UtcNow }; accepted.Add(value.EventId); } } _health[$"{tenant}:{health.EndpointId}"] = health; return Task.FromResult(new PersistenceIngestResult(new(batch.BatchId, accepted, duplicates, new Dictionary<Guid, string>(), batch.LastSequence, false), accepted.Count, duplicates.Count, 0, 0)); } }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1310:Specify StringComparison", Justification = "Tenant identifiers use invariant UUID text.")]
    public Task<PersistenceEventPage> SearchAsync(string tenant, PersistenceSearchRequest request, CancellationToken ct)
    { lock (_gate) { IEnumerable<PersistenceObservation> values = _events.Where(x => x.Key.StartsWith(tenant + ':')).Select(x => x.Value); if (request.ObjectKind is { } k) values = values.Where(x => x.ObjectKind == k); if (request.EndpointId is { } e) values = values.Where(x => x.EndpointId == e); if (request.Name is { } n) values = values.Where(x => (x.Service?.Name ?? x.ScheduledTask?.Name ?? x.Configuration?.Name ?? "").Contains(n, StringComparison.OrdinalIgnoreCase)); if (request.Path is { } p) values = values.Where(x => (x.Service?.BinaryPath ?? x.ScheduledTask?.Path ?? x.Configuration?.RegistryPath ?? x.Configuration?.FilePath ?? "").Contains(p, StringComparison.OrdinalIgnoreCase)); if (request.Account is { } a) values = values.Where(x => (x.Service?.Account ?? x.ScheduledTask?.Principal ?? x.Configuration?.Principal ?? "").Contains(a, StringComparison.OrdinalIgnoreCase)); if (request.Process is { } process) values = values.Where(x => (x.Service?.Process?.ProcessEntityId ?? x.ScheduledTask?.Process?.ProcessEntityId ?? "").Contains(process, StringComparison.OrdinalIgnoreCase)); if (request.Category is { } category) values = values.Where(x => x.Configuration?.Category.Equals(category, StringComparison.OrdinalIgnoreCase) == true); if (request.Subtype is { } subtype) values = values.Where(x => x.Configuration?.Subtype.Equals(subtype, StringComparison.OrdinalIgnoreCase) == true); if (request.Scope is { } scope) values = values.Where(x => x.Configuration?.Scope?.Equals(scope, StringComparison.OrdinalIgnoreCase) == true); if (request.From is { } f) values = values.Where(x => x.ObservedAt >= f); if (request.To is { } to) values = values.Where(x => x.ObservedAt <= to); return Task.FromResult(new PersistenceEventPage(values.OrderByDescending(x => x.ObservedAt).Take(Math.Clamp(request.PageSize, 1, 500)).ToArray(), null)); } }
    public Task<PersistenceObservation?> GetAsync(string tenant, Guid eventId, CancellationToken ct) { lock (_gate) return Task.FromResult(_events.GetValueOrDefault($"{tenant}:{eventId}")); }
    public Task<PersistenceEventPage> EntityHistoryAsync(string tenant, Guid endpoint, string entityId, int limit, CancellationToken ct) { lock (_gate) return Task.FromResult(new PersistenceEventPage(_events.Where(x => x.Key.StartsWith(tenant + ':', StringComparison.Ordinal)).Select(x => x.Value).Where(x => x.EndpointId == endpoint && (x.Service?.EntityId == entityId || x.ScheduledTask?.EntityId == entityId || x.Configuration?.EntityId == entityId)).OrderByDescending(x => x.ObservedAt).Take(Math.Clamp(limit, 1, 500)).ToArray(), null)); }
    public Task<PersistenceTelemetryHealth?> HealthAsync(string tenant, Guid endpoint, CancellationToken ct) { lock (_gate) return Task.FromResult(_health.GetValueOrDefault($"{tenant}:{endpoint}")); }
    public Task<IReadOnlyList<PersistenceObservation>> ListAllAsync(CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<PersistenceObservation>>(_events.Values.ToArray()); }
    public Task<int> ReconcileEvidenceAsync(int limit, CancellationToken ct) => Task.FromResult(0);
    public Task EnsureAsync(CancellationToken ct) => Task.CompletedTask; public Task UpsertAsync(string tenant, PersistenceObservation value, CancellationToken ct) { lock (_gate) _events[$"{tenant}:{value.EventId}"] = value; return Task.CompletedTask; }
    public Task<bool> HealthAsync(CancellationToken ct) => Task.FromResult(true);
}

public sealed class FilePersistencePolicyRepository : IPersistencePolicyRepository
{
    readonly object _gate = new(); readonly List<PersistencePolicyVersion> _versions = [];
    readonly Dictionary<string, Guid> _assignments = []; readonly Dictionary<string, PersistencePolicyAcknowledgement> _acks = [];
    public Task<IReadOnlyList<PersistencePolicyVersion>> ListAsync(string tenant, CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<PersistencePolicyVersion>>(_versions.Where(x => x.TenantId == tenant).ToArray()); }
    public Task<PersistencePolicyVersion> CreateAsync(string tenant, string actor, string name, PersistenceTelemetryPolicy policy, CancellationToken ct) { var errors = PersistenceSafety.Validate(policy); if (errors.Count > 0) throw new EnrollmentConflictException("PERSISTENCE_POLICY_INVALID", string.Join(' ', errors.SelectMany(x => x.Value))); lock (_gate) { var value = new PersistencePolicyVersion(Guid.NewGuid(), tenant, name, _versions.Where(x => x.TenantId == tenant && x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1, policy, PersistenceSafety.EvidenceHash(policy), "active", DateTimeOffset.UtcNow, actor); _versions.Add(value); return Task.FromResult(value); } }
    public Task AssignAsync(string tenant, Guid policyId, Guid? endpoint, string actor, CancellationToken ct) { lock (_gate) { if (!_versions.Any(x => x.TenantId == tenant && x.Id == policyId)) throw new EnrollmentConflictException("PERSISTENCE_POLICY_NOT_FOUND", "Policy unavailable."); _assignments[$"{tenant}:{endpoint?.ToString() ?? "default"}"] = policyId; return Task.CompletedTask; } }
    public async Task<EffectivePersistencePolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct) { var all = await ListAsync(tenant, ct); lock (_gate) { var id = _assignments.GetValueOrDefault($"{tenant}:{endpoint}", _assignments.GetValueOrDefault($"{tenant}:default")); var value = all.FirstOrDefault(x => x.Id == id) ?? new(Guid.Empty, tenant, "safe-default", 0, new(), PersistenceSafety.EvidenceHash(new PersistenceTelemetryPolicy()), "default", DateTimeOffset.UnixEpoch, "system"); var ack = _acks.GetValueOrDefault($"{tenant}:{endpoint}"); return new(value, id == Guid.Empty ? "default" : "assigned", endpoint, ack?.AcknowledgedAt, ack?.Applied == true ? ack.Version : null, ack?.Applied == false ? ack.Version : null, ack?.ValidationError, ack is null || ack.Version != value.Version); } }
    public Task AcknowledgeAsync(string tenant, Guid endpoint, PersistencePolicyAcknowledgement acknowledgement, CancellationToken ct) { lock (_gate) { _acks[$"{tenant}:{endpoint}"] = acknowledgement; return Task.CompletedTask; } }
}

public sealed class FilePersistenceExportRepository : IPersistenceExportRepository
{
    readonly object _gate = new(); readonly Dictionary<Guid, PersistenceExportJob> _jobs = [];
    public Task<PersistenceExportJob> CreateAsync(string tenant, string actor, PersistenceExportCreateRequest request, CancellationToken ct) { lock (_gate) { var now = DateTimeOffset.UtcNow; var job = new PersistenceExportJob(Guid.NewGuid(), tenant, actor, FileExportState.Pending, request.Format, request.Query with { Cursor = null }, request.Fields ?? [], request.MaximumRecords, Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), now, now, now.AddMinutes(15)); _jobs[job.Id] = job; return Task.FromResult(job); } }
    public Task<PersistenceExportJob?> GetAsync(string tenant, Guid id, CancellationToken ct) { lock (_gate) return Task.FromResult(_jobs.GetValueOrDefault(id) is { } x && x.TenantId == tenant ? x : null); }
    public Task<PersistenceExportJob?> ClaimAsync(CancellationToken ct) { lock (_gate) { var value = _jobs.Values.FirstOrDefault(x => x.State == FileExportState.Pending); if (value is null) return Task.FromResult<PersistenceExportJob?>(null); var changed = value with { State = FileExportState.Running, StartedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }; _jobs[value.Id] = changed; return Task.FromResult<PersistenceExportJob?>(changed); } }
    public Task CompleteAsync(Guid id, int count, long size, string sha256, DateTimeOffset at, CancellationToken ct) { lock (_gate) _jobs[id] = _jobs[id] with { State = FileExportState.Completed, RecordCount = count, OutputSize = size, OutputSha256 = sha256, CompletedAt = at, UpdatedAt = at }; return Task.CompletedTask; }
    public Task FailAsync(Guid id, string code, string summary, CancellationToken ct) { lock (_gate) _jobs[id] = _jobs[id] with { State = FileExportState.Failed, ErrorCode = code, ErrorSummary = summary[..Math.Min(512, summary.Length)] }; return Task.CompletedTask; }
    public Task<IReadOnlyList<PersistenceExportJob>> ExpireDueAsync(CancellationToken ct) { lock (_gate) { var due = _jobs.Values.Where(x => x.State == FileExportState.Completed && x.ExpiresAt <= DateTimeOffset.UtcNow).ToArray(); foreach (var x in due) _jobs[x.Id] = x with { State = FileExportState.Expired }; return Task.FromResult<IReadOnlyList<PersistenceExportJob>>(due); } }
}
