namespace OpenSecurityPlatform.Foundation;

public sealed class FileModuleTelemetryRepository : IModuleTelemetryRepository, IModuleProjection
{
    readonly object _gate = new(); readonly Dictionary<string, ModuleObservation> _events = []; readonly Dictionary<string, ModuleTelemetryHealth> _health = [];
    public Task<ModuleIngestResult> IngestAsync(string t, ModuleEventBatch b, ModuleTelemetryHealth h, CancellationToken ct)
    { lock (_gate) { var a = new List<Guid>(); var d = new List<Guid>(); foreach (var x in b.Events) { var k = $"{t}:{x.EventId}"; if (_events.ContainsKey(k)) d.Add(x.EventId); else { _events[k] = x with { ReceivedAt = DateTimeOffset.UtcNow, IngestedAt = DateTimeOffset.UtcNow }; a.Add(x.EventId); } } _health[$"{t}:{h.EndpointId}"] = h; return Task.FromResult(new ModuleIngestResult(new(b.BatchId, a, d, new Dictionary<Guid, string>(), b.LastSequence, false), a.Count, d.Count, 0, 0)); } }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1310:Specify StringComparison", Justification = "Tenant identifiers use invariant UUID text.")]
    public Task<ModuleEventPage> SearchAsync(string t, ModuleSearchRequest q, CancellationToken ct)
    { lock (_gate) { IEnumerable<ModuleObservation> x = _events.Where(v => v.Key.StartsWith(t + ':')).Select(v => v.Value); if (q.EndpointId is { } e) x = x.Where(v => v.EndpointId == e); if (q.Process is { } p) x = x.Where(v => v.Process?.ProcessEntityId?.Contains(p, StringComparison.OrdinalIgnoreCase) == true || v.Process?.Image?.Contains(p, StringComparison.OrdinalIgnoreCase) == true); if (q.Path is { } path) x = x.Where(v => v.NormalizedPath.Contains(path, StringComparison.OrdinalIgnoreCase)); if (q.Basename is { } n) x = x.Where(v => v.Basename.Equals(n, StringComparison.OrdinalIgnoreCase)); if (q.Sha256 is { } s) x = x.Where(v => v.Hash.Value == s); if (q.Signer is { } g) x = x.Where(v => v.Signer.Subject?.Contains(g, StringComparison.OrdinalIgnoreCase) == true); if (q.ImageType is { } i) x = x.Where(v => v.ImageType.Equals(i, StringComparison.OrdinalIgnoreCase)); if (q.Mode is { } m) x = x.Where(v => v.Mode == m); if (q.Driver is { } dr) x = x.Where(v => v.Driver == dr); if (q.From is { } f) x = x.Where(v => v.ObservedAt >= f); if (q.To is { } to) x = x.Where(v => v.ObservedAt <= to); return Task.FromResult(new ModuleEventPage(x.OrderByDescending(v => v.ObservedAt).Take(Math.Clamp(q.PageSize, 1, 500)).ToArray(), null)); } }
    public Task<ModuleObservation?> GetAsync(string t, Guid id, CancellationToken ct) { lock (_gate) return Task.FromResult(_events.GetValueOrDefault($"{t}:{id}")); }
    public Task<ModuleEventPage> ProcessHistoryAsync(string t, Guid e, string p, DateTimeOffset f, DateTimeOffset to, int l, CancellationToken ct) => SearchAsync(t, new(e, p, From: f, To: to, PageSize: l), ct);
    public Task<ModuleTelemetryHealth?> HealthAsync(string t, Guid e, CancellationToken ct) { lock (_gate) return Task.FromResult(_health.GetValueOrDefault($"{t}:{e}")); }
    public Task<IReadOnlyList<ModuleObservation>> ListAllAsync(CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<ModuleObservation>>(_events.Values.ToArray()); }
    public Task EnsureAsync(CancellationToken ct) => Task.CompletedTask; public Task UpsertAsync(string t, ModuleObservation v, CancellationToken ct) { lock (_gate) _events[$"{t}:{v.EventId}"] = v; return Task.CompletedTask; }
    public Task<bool> HealthAsync(CancellationToken ct) => Task.FromResult(true);
}

public sealed class FileModulePolicyRepository : IModulePolicyRepository
{
    readonly object _gate = new(); readonly List<ModulePolicyVersion> _versions = []; readonly Dictionary<string, Guid> _assign = []; readonly Dictionary<string, ModulePolicyAcknowledgement> _acks = [];
    public Task<IReadOnlyList<ModulePolicyVersion>> ListAsync(string t, CancellationToken ct) { lock (_gate) return Task.FromResult<IReadOnlyList<ModulePolicyVersion>>(_versions.Where(x => x.TenantId == t).ToArray()); }
    public Task<ModulePolicyVersion> CreateAsync(string t, string actor, string name, ModuleTelemetryPolicy p, CancellationToken ct) { var e = ModulePolicyValidation.Validate(p); if (e.Count > 0) throw new EnrollmentConflictException("MODULE_POLICY_INVALID", string.Join(' ', e.SelectMany(x => x.Value))); lock (_gate) { var v = new ModulePolicyVersion(Guid.NewGuid(), t, name, _versions.Where(x => x.TenantId == t && x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1, p, ModuleEvidence.Sha256(p), "active", DateTimeOffset.UtcNow, actor); _versions.Add(v); return Task.FromResult(v); } }
    public Task AssignAsync(string t, Guid id, Guid? e, string actor, CancellationToken ct) { lock (_gate) { if (!_versions.Any(x => x.TenantId == t && x.Id == id)) throw new EnrollmentConflictException("MODULE_POLICY_NOT_FOUND", "Policy unavailable."); _assign[$"{t}:{e?.ToString() ?? "default"}"] = id; return Task.CompletedTask; } }
    public async Task<EffectiveModulePolicy> EffectiveAsync(string t, Guid e, CancellationToken ct) { var all = await ListAsync(t, ct); lock (_gate) { var id = _assign.GetValueOrDefault($"{t}:{e}", _assign.GetValueOrDefault($"{t}:default")); var v = all.FirstOrDefault(x => x.Id == id) ?? new(Guid.Empty, t, "safe-default", 0, new(), ModuleEvidence.Sha256(new ModuleTelemetryPolicy()), "default", DateTimeOffset.UnixEpoch, "system"); var a = _acks.GetValueOrDefault($"{t}:{e}"); return new(v, id == Guid.Empty ? "default" : "assigned", e, a?.AcknowledgedAt, a?.Applied == true ? a.Version : null, a?.Applied == false ? a.Version : null, a?.ValidationError, a is null || a.Version != v.Version); } }
    public Task AcknowledgeAsync(string t, Guid e, ModulePolicyAcknowledgement a, CancellationToken ct) { lock (_gate) { _acks[$"{t}:{e}"] = a; return Task.CompletedTask; } }
}
