using System.Collections.Concurrent;

namespace OpenSecurityPlatform.Foundation;

public sealed class FileCorrelationRepository : ICorrelationRepository, ICorrelationProjection
{
    readonly object gate = new();
    readonly List<CorrelationPack> packs = [];
    readonly List<CorrelationRule> rules = [];
    readonly List<CorrelationAssignment> assignments = [];
    readonly List<CorrelationExclusion> exclusions = [];
    readonly Dictionary<string, List<CorrelationTestResult>> tests = [];
    readonly Dictionary<string, List<CorrelationObservation>> state = [];
    readonly HashSet<string> processed = [];
    readonly List<CorrelatedFinding> findings = [];
    readonly List<CorrelationObservation> observations = [];
    readonly ConcurrentDictionary<string, CorrelationRun> runs = new();
    long evaluated, expired, completed, incomplete, late, duplicates, missing, suppressed, excluded;

    public Task<IReadOnlyList<CorrelationPack>> ListPacksAsync(string tenant, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CorrelationPack>>(packs.Where(x => x.TenantId == tenant).GroupBy(x => x.PackId).Select(x => x.MaxBy(v => v.Version)!).ToArray()); }
    public Task<CorrelationPack?> GetPackAsync(string tenant, Guid id, int? version, CancellationToken ct) { lock (gate) return Task.FromResult(packs.Where(x => x.TenantId == tenant && x.PackId == id && (version is null || x.Version == version)).MaxBy(x => x.Version)); }
    public Task<IReadOnlyList<CorrelationPack>> PackHistoryAsync(string tenant, Guid id, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CorrelationPack>>(packs.Where(x => x.TenantId == tenant && x.PackId == id).OrderByDescending(x => x.Version).ToArray()); }
    public Task<CorrelationPack> PutPackAsync(string tenant, string actor, CorrelationPack input, CancellationToken ct) { lock (gate) { var id = input.PackId == Guid.Empty ? Guid.NewGuid() : input.PackId; var version = packs.Where(x => x.TenantId == tenant && x.PackId == id).Select(x => x.Version).DefaultIfEmpty(input.Version - 1).Max() + 1; var value = input with { PackId = id, Version = Math.Max(1, version), TenantId = tenant, Enabled = false, CreatedAt = DateTimeOffset.UtcNow, CreatedBy = actor }; packs.Add(value); return Task.FromResult(value); } }
    public Task<CorrelationPack> SetPackEnabledAsync(string tenant, string actor, Guid id, int version, bool enabled, CancellationToken ct) { lock (gate) { var index = packs.FindIndex(x => x.TenantId == tenant && x.PackId == id && x.Version == version); if (index < 0) throw new KeyNotFoundException(); if (enabled && !packs[index].ValidationPassed) throw new EnrollmentConflictException("CORRELATION_PACK_INVALID", "Pack validation must pass before activation."); return Task.FromResult(packs[index] = packs[index] with { Enabled = enabled }); } }
    public Task<CorrelationAssignment> AssignPackAsync(string tenant, string actor, CorrelationAssignment input, CancellationToken ct) { lock (gate) { if (!packs.Any(x => x.TenantId == tenant && x.PackId == input.PackId && x.Version == input.PackVersion)) throw new EnrollmentConflictException("CORRELATION_ASSIGNMENT_INVALID", "Pack version is not in this tenant."); var value = input with { Id = input.Id == Guid.Empty ? Guid.NewGuid() : input.Id, TenantId = tenant, CreatedAt = DateTimeOffset.UtcNow, CreatedBy = actor }; assignments.Add(value); return Task.FromResult(value); } }
    public Task<IReadOnlyList<CorrelationRule>> ListRulesAsync(string tenant, Guid? packId, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CorrelationRule>>(rules.Where(x => x.TenantId == tenant && (packId is null || x.PackId == packId)).GroupBy(x => x.CorrelationRuleId).Select(x => x.MaxBy(v => v.Version)!).ToArray()); }
    public Task<CorrelationRule?> GetRuleAsync(string tenant, Guid id, int? version, CancellationToken ct) { lock (gate) return Task.FromResult(rules.Where(x => x.TenantId == tenant && x.CorrelationRuleId == id && (version is null || x.Version == version)).MaxBy(x => x.Version)); }
    public Task<IReadOnlyList<CorrelationRule>> RuleHistoryAsync(string tenant, Guid id, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CorrelationRule>>(rules.Where(x => x.TenantId == tenant && x.CorrelationRuleId == id).OrderByDescending(x => x.Version).ToArray()); }
    public Task<CorrelationRule> PutRuleAsync(string tenant, string actor, CorrelationRule input, bool newVersion, CancellationToken ct) { lock (gate) { var id = input.CorrelationRuleId == Guid.Empty ? Guid.NewGuid() : input.CorrelationRuleId; var history = rules.Where(x => x.TenantId == tenant && x.CorrelationRuleId == id).ToArray(); if (!newVersion && history.Length > 0) throw new EnrollmentConflictException("CORRELATION_RULE_EXISTS", "Rule already exists."); var value = input with { SchemaVersion = "correlation-rule.v1", CorrelationRuleId = id, Version = history.Select(x => x.Version).DefaultIfEmpty(input.Version - 1).Max() + 1, TenantId = tenant, Status = CorrelationStatus.Draft, Enabled = false, ValidationPassed = false, ValidatedAt = null, CreatedAt = DateTimeOffset.UtcNow, CreatedBy = actor, ActivatedAt = null, DeactivatedAt = null }; rules.Add(value); return Task.FromResult(value); } }
    public Task<CorrelationRule> ValidateRuleAsync(string tenant, Guid id, int version, IReadOnlyDictionary<string, string[]> errors, CancellationToken ct) { lock (gate) { var i = rules.FindIndex(x => x.TenantId == tenant && x.CorrelationRuleId == id && x.Version == version); if (i < 0) throw new KeyNotFoundException(); return Task.FromResult(rules[i] = rules[i] with { ValidationPassed = errors.Count == 0, ValidatedAt = DateTimeOffset.UtcNow, Status = errors.Count == 0 ? CorrelationStatus.Testing : CorrelationStatus.Draft }); } }
    public Task RecordTestsAsync(string tenant, Guid id, int version, IReadOnlyList<CorrelationTestResult> values, CancellationToken ct) { lock (gate) tests[$"{tenant}:{id}:{version}"] = values.ToList(); return Task.CompletedTask; }
    public Task<IReadOnlyList<CorrelationTestResult>> ListTestsAsync(string tenant, Guid id, int version, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CorrelationTestResult>>(tests.GetValueOrDefault($"{tenant}:{id}:{version}", []).ToArray()); }
    public Task<CorrelationRule> SetRuleEnabledAsync(string tenant, string actor, Guid id, int version, bool enabled, CancellationToken ct) { lock (gate) { var i = rules.FindIndex(x => x.TenantId == tenant && x.CorrelationRuleId == id && x.Version == version); if (i < 0) throw new KeyNotFoundException(); var checks = tests.GetValueOrDefault($"{tenant}:{id}:{version}", []); if (enabled && (!rules[i].ValidationPassed || checks.Count < 3 || checks.Any(x => !x.Passed || !x.Deterministic || !x.TenantIsolated || !x.ResourceCostPassed))) throw new EnrollmentConflictException("CORRELATION_ACTIVATION_BLOCKED", "Validation and all quality gates must pass."); return Task.FromResult(rules[i] = rules[i] with { Enabled = enabled, Status = enabled ? CorrelationStatus.Active : CorrelationStatus.Disabled, ActivatedAt = enabled ? DateTimeOffset.UtcNow : rules[i].ActivatedAt, DeactivatedAt = enabled ? null : DateTimeOffset.UtcNow }); } }

    public Task<CorrelationEvaluationResult> EvaluateAsync(string tenant, CorrelationObservation observation, DetectionExecutionMode mode, Guid? ruleId, int? version, Guid? runId, bool production, CancellationToken ct)
    {
        lock (gate)
        {
            if (observation.TenantId != tenant) throw new EnrollmentConflictException("CORRELATION_TENANT_MISMATCH", "Observation tenant is invalid.");
            if (observations.All(x => x.TenantId != tenant || x.ObservationId != observation.ObservationId)) observations.Add(observation);
            var applicable = rules.Where(x => x.TenantId == tenant && (ruleId is null ? x.Enabled && x.Status == CorrelationStatus.Active && assignments.Any(a => a.TenantId == tenant && a.PackId == x.PackId && a.PackVersion == x.PackVersion && a.Enabled && (a.EndpointId is null || a.EndpointId == observation.EndpointId)) && packs.Any(p => p.TenantId == tenant && p.PackId == x.PackId && p.Version == x.PackVersion && p.Enabled) : x.CorrelationRuleId == ruleId && (version is null || x.Version == version))).ToArray();
            CorrelationEvaluationResult? result = null; CorrelationEvaluationResult? completedResult = null;
            foreach (var rule in applicable)
            {
                var unique = $"{tenant}:{rule.CorrelationRuleId}:{rule.Version}:{mode}:{runId}:{observation.ObservationId}"; var key = CorrelationDsl.Key(rule, observation);
                if (!processed.Add(unique)) { duplicates++; result = new(true, false, false, false, key, [], null, "duplicate-observation"); continue; }
                var exclusion = exclusions.FirstOrDefault(x => x.TenantId == tenant && (x.PackId is null || x.PackId == rule.PackId) && (x.RuleId is null || x.RuleId == rule.CorrelationRuleId) && x.StartsAt <= observation.EventTime && x.EndsAt >= observation.EventTime && string.Equals(CorrelationDsl.Value(observation, x.Field), x.Value, StringComparison.OrdinalIgnoreCase));
                if (exclusion is not null) { excluded++; result = new(false, false, true, false, key, [], null, exclusion.Reason); continue; }
                var stateKey = $"{tenant}:{rule.CorrelationRuleId}:{rule.Version}:{mode}:{runId}:{key}"; var values = state.GetValueOrDefault(stateKey, []); expired += values.RemoveAll(x => x.EventTime < observation.EventTime.AddSeconds(-rule.WindowSeconds)); values.Add(observation); state[stateKey] = values;
                var prior = findings.LastOrDefault(x => x.TenantId == tenant && x.CorrelationRuleId == rule.CorrelationRuleId && x.CorrelationKey == key && x.CreatedAt >= observation.EventTime.AddMinutes(-rule.Suppression.DurationMinutes)); var finding = CorrelationDsl.Complete(rule, values, mode, prior); evaluated++; late += observation.Late ? 1 : 0; missing += observation.MissingTelemetry?.Length ?? 0;
                if (finding is null) incomplete++; else { completed++; suppressed += finding.Suppressed ? 1 : 0; if (production && mode is DetectionExecutionMode.Live or DetectionExecutionMode.HistoricalReplay && findings.All(x => x.CorrelatedFindingId != finding.CorrelatedFindingId)) findings.Add(finding); }
                result = new(false, finding is not null, false, finding?.Suppressed ?? false, key, rule.Steps.Where(s => s.Required && !values.Any(v => CorrelationDsl.Matches(rule, s, v, out _))).Select(s => s.Id).ToArray(), finding, finding is null ? "sequence-incomplete" : "all-required-steps-satisfied"); if (finding is not null) completedResult = result;
            }
            return Task.FromResult(completedResult ?? result ?? new(false, false, false, false, "none", [], null, "no-applicable-rule"));
        }
    }
    public Task<IReadOnlyList<CorrelationObservation>> LoadObservationsAsync(string tenant, DateTimeOffset from, DateTimeOffset until, int maximum, CancellationToken ct) { if (until <= from || until - from > TimeSpan.FromDays(7) || maximum is < 1 or > 100_000) throw new EnrollmentConflictException("CORRELATION_REPLAY_BOUNDS", "Authoritative replay query is out of bounds."); lock (gate) return Task.FromResult<IReadOnlyList<CorrelationObservation>>(observations.Where(x => x.TenantId == tenant && x.EventTime >= from && x.EventTime <= until).OrderBy(x => x.EventTime).ThenBy(x => x.ObservationId).Take(maximum).ToArray()); }
    public Task<CorrelatedFindingPage> SearchFindingsAsync(string tenant, CorrelatedFindingQuery q, CancellationToken ct) { lock (gate) return Task.FromResult(new CorrelatedFindingPage(findings.Where(x => x.TenantId == tenant && (q.RuleId is null || x.CorrelationRuleId == q.RuleId) && (q.PackId is null || x.PackId == q.PackId) && (q.EndpointId is null || x.EndpointId == q.EndpointId) && (q.MinimumSeverity is null || x.Severity >= q.MinimumSeverity) && (q.Suppressed is null || x.Suppressed == q.Suppressed) && (q.Mode is null || x.ExecutionMode == q.Mode) && (q.From is null || x.CreatedAt >= q.From) && (q.To is null || x.CreatedAt <= q.To)).OrderByDescending(x => x.CreatedAt).Take(Math.Clamp(q.PageSize, 1, 500)).ToArray(), null)); }
    public Task<CorrelatedFinding?> GetFindingAsync(string tenant, Guid id, CancellationToken ct) { lock (gate) return Task.FromResult(findings.FirstOrDefault(x => x.TenantId == tenant && x.CorrelatedFindingId == id)); }
    public Task<IReadOnlyList<CorrelationExclusion>> ListExclusionsAsync(string tenant, CancellationToken ct) { lock (gate) return Task.FromResult<IReadOnlyList<CorrelationExclusion>>(exclusions.Where(x => x.TenantId == tenant).ToArray()); }
    public Task<CorrelationExclusion> PutExclusionAsync(string tenant, string actor, CorrelationExclusion input, CancellationToken ct) { if (string.IsNullOrWhiteSpace(input.Field) || input.Value.Trim() is "*" or "**" || input.EndsAt <= input.StartsAt || input.EndsAt - input.StartsAt > TimeSpan.FromDays(90)) throw new EnrollmentConflictException("CORRELATION_EXCLUSION_INVALID", "Exclusion must be exact and bounded."); lock (gate) { var value = input with { Id = input.Id == Guid.Empty ? Guid.NewGuid() : input.Id, Version = Math.Max(1, input.Version), TenantId = tenant, CreatedBy = actor }; exclusions.Add(value); return Task.FromResult(value); } }
    public Task<CorrelationRun> PutRunAsync(string tenant, CorrelationRun run, CorrelationRule rule, CancellationToken ct) { if (run.TenantId != tenant || run.To <= run.From || run.To - run.From > TimeSpan.FromDays(7)) throw new EnrollmentConflictException("CORRELATION_REPLAY_BOUNDS", "Replay is bounded to seven days."); runs[$"{tenant}:{run.Id}"] = run; return Task.FromResult(run); }
    public Task<CorrelationRun?> GetRunAsync(string tenant, Guid id, CancellationToken ct) => Task.FromResult(runs.GetValueOrDefault($"{tenant}:{id}"));
    public Task<CorrelationRun> CompleteRunAsync(string tenant, Guid id, long count, long findingCount, string status, CancellationToken ct) { if (!runs.TryGetValue($"{tenant}:{id}", out var run)) throw new KeyNotFoundException(); var value = run with { Status = status, ObservationsEvaluated = count, Findings = findingCount, CompletedAt = DateTimeOffset.UtcNow }; runs[$"{tenant}:{id}"] = value; return Task.FromResult(value); }
    public Task<CorrelationRun> CancelRunAsync(string tenant, Guid id, CancellationToken ct) { if (!runs.TryGetValue($"{tenant}:{id}", out var run)) throw new KeyNotFoundException(); var value = run with { Status = "cancelled", CompletedAt = DateTimeOffset.UtcNow }; runs[$"{tenant}:{id}"] = value; return Task.FromResult(value); }
    public Task<CorrelationHealth> HealthAsync(string tenant, CancellationToken ct) { lock (gate) return Task.FromResult(new CorrelationHealth(evaluated, state.Where(x => x.Key.StartsWith(tenant + ":", StringComparison.Ordinal)).Sum(x => x.Value.Count), expired, completed, incomplete, late, duplicates, 0, 0, 0, 0, missing, suppressed, excluded, runs.Count(x => x.Key.StartsWith(tenant + ":", StringComparison.Ordinal) && x.Value.Status is "queued" or "running"), DateTimeOffset.UtcNow)); }
    public async Task<IReadOnlyList<MitreCoverageRow>> CoverageAsync(string tenant, CancellationToken ct) { var values = await ListRulesAsync(tenant, null, ct); return values.GroupBy(x => new { x.MitreTactic, x.MitreTechnique, x.MitreSubTechnique }).Select(g => new MitreCoverageRow(g.Key.MitreTactic, g.Key.MitreTechnique, g.Key.MitreSubTechnique, g.Select(x => x.Name).ToArray(), g.SelectMany(x => x.RequiredTelemetry).Distinct().ToArray(), true, true, g.All(x => tests.GetValueOrDefault($"{tenant}:{x.CorrelationRuleId}:{x.Version}", []).All(t => t.Passed)), g.Any(x => x.Enabled))).ToArray(); }
    public Task EnsureAsync(CancellationToken ct) => Task.CompletedTask;
    public Task UpsertAsync(CorrelatedFinding finding, CancellationToken ct) { lock (gate) if (findings.All(x => x.CorrelatedFindingId != finding.CorrelatedFindingId)) findings.Add(finding); return Task.CompletedTask; }
    public Task<long> CountAsync(string tenant, CancellationToken ct) { lock (gate) return Task.FromResult((long)findings.Count(x => x.TenantId == tenant)); }
    public Task<bool> HealthAsync(CancellationToken ct) => Task.FromResult(true);
}
