using System.Collections.Concurrent;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenSecurityPlatform.Foundation;

[JsonConverter(typeof(JsonStringEnumConverter<InvestigationStatus>))]
public enum InvestigationStatus { Open, Investigating, Waiting, Contained, Closed, Archived }
[JsonConverter(typeof(JsonStringEnumConverter<EvidenceAvailability>))]
public enum EvidenceAvailability { CollectionAndParsingSupported, CollectionSupported, ParsingSupported, CollectionOnly, ToolRequired, PermissionRequired, EndpointUnavailable, SourceUnavailable, NotSupported, NotValidated }
[JsonConverter(typeof(JsonStringEnumConverter<EvidenceIntegrityStatus>))]
public enum EvidenceIntegrityStatus { Verified, Mismatch, Missing, VerificationFailed, NotVerified }
[JsonConverter(typeof(JsonStringEnumConverter<EvidenceParseStatus>))]
public enum EvidenceParseStatus { NotRequested, Queued, Running, Complete, Partial, Failed }

public sealed record EvidenceProfileItem(string EvidenceType, EvidenceAvailability Availability, bool Sensitive,
    bool ApprovalRequired, string AcquisitionMechanism, string? RequiredTool, string Limitation);
public sealed record InvestigationCollectionProfile(string ProfileId, int Version, string Name, string Description,
    EvidenceProfileItem[] Items, long MaximumBytes, int MaximumItems, int MaximumDurationSeconds,
    bool ApprovalRequired, string ProfileHash);
public sealed record ForensicInvestigation(Guid InvestigationId, string TenantId, string Title, string Description,
    InvestigationStatus Status, string Priority, string Owner, string[] AssignedAnalysts, Guid[] IncidentIds,
    Guid[] AlertIds, Guid[] EndpointIds, DateTimeOffset CreatedAt, DateTimeOffset UpdatedAt, DateTimeOffset? ClosedAt,
    string[] Tags, Guid[] CollectionIds, Guid[] EvidenceIds, Guid[] HoldIds, string CreatedBy);
[SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Canonical DFIR domain term")]
public sealed record InvestigationCollection(Guid CollectionId, Guid InvestigationId, string TenantId, Guid EndpointId,
    string AgentInstallationId, string ProfileId, int ProfileVersion, string ProfileHash, string State,
    DateTimeOffset RequestedAt, DateTimeOffset? StartedAt, DateTimeOffset? CompletedAt, int RequestedItems,
    int SuccessfulItems, int FailedItems, int UnavailableItems, long BytesAcquired, long BytesTransferred,
    int ChunksVerified, string? FailureCode, string? FailureDetail, Guid? RecollectionOf, string IdempotencyKey);
public sealed record ForensicWorkspaceArtifact(Guid EvidenceId, Guid InvestigationId, Guid CollectionId, string TenantId,
    Guid EndpointId, string AgentInstallationId, string EvidenceType, string Source, string AcquisitionMechanism,
    string AcquisitionVersion, string? RequestedPath, string? NativeIdentity, DateTimeOffset? SourceCreatedAt,
    DateTimeOffset? SourceModifiedAt, DateTimeOffset AcquisitionStartedAt, DateTimeOffset AcquisitionCompletedAt,
    long Size, long BytesTransferred, int Chunks, string Sha256, bool TransferVerified, string ObjectId,
    string MediaType, EvidenceIntegrityStatus Integrity, string? ParserId, string? ParserVersion,
    EvidenceParseStatus ParseStatus, string ExtractionStatus, Guid? DerivedFromEvidenceId, string? SourceRecordIdentity,
    string[] RelatedEntities, Guid[] RelatedFindings, string[] Tags, bool Bookmarked, string State,
    string? FailureCode, string? FailureDetail, DateTimeOffset CreatedAt,
    string? CollectionManifestObjectId = null, string? CollectionManifestSha256 = null);
public sealed record EvidenceCustodyEvent(Guid EventId, string TenantId, Guid InvestigationId, Guid? CollectionId,
    Guid? EvidenceId, DateTimeOffset OccurredAt, string Actor, string Operation, string Result,
    string Source, string Destination, string? Sha256, string Detail, string RequestId);
public sealed record EvidenceParser(string ParserId, string Version, string[] EvidenceTypes, int MaximumInputBytes,
    int MaximumRecords, string OutputMediaType, string Status, string Provenance);
public sealed record EvidenceParserRun(Guid RunId, string TenantId, Guid InvestigationId, Guid InputEvidenceId,
    Guid OutputEvidenceId, string ParserId, string ParserVersion, DateTimeOffset StartedAt, DateTimeOffset CompletedAt,
    EvidenceParseStatus Status, string[] Warnings, int ParsedRecords, int MaximumRecords, string OutputSha256);
public sealed record InvestigationBookmark(Guid BookmarkId, string TenantId, Guid InvestigationId, Guid EvidenceId,
    string Purpose, string Actor, DateTimeOffset CreatedAt);
public sealed record InvestigationNote(Guid NoteId, string TenantId, Guid InvestigationId, string TargetType,
    string TargetId, int Version, string Body, string Author, DateTimeOffset CreatedAt, bool AiDraft, bool Accepted,
    string[] EvidenceCitations);
public sealed record InvestigationTimelineItem(Guid TimelineId, Guid InvestigationId, DateTimeOffset OccurredAt,
    string EventType, string Summary, Guid? EvidenceId, Guid? CollectionId, Guid? EndpointId, string? User,
    string Confidence, string Source, string[] RelatedEntities, Guid[] FindingIds);
public sealed record EvidenceExport(Guid ExportId, string TenantId, Guid InvestigationId, Guid[] RequestedEvidence,
    Guid[] Included, Guid[] Excluded, Guid[] Failed, Guid[] Unavailable, string ObjectId, string ManifestObjectId,
    string PackageSha256, string ManifestSha256, long PackageBytes, string RequestedBy, DateTimeOffset CreatedAt,
    string State);
public sealed record ForensicWorkspaceState(long Revision, ForensicInvestigation[] Investigations,
    InvestigationCollection[] Collections, ForensicWorkspaceArtifact[] Artifacts, EvidenceCustodyEvent[] Custody,
    EvidenceParserRun[] ParserRuns, InvestigationBookmark[] Bookmarks, InvestigationNote[] Notes,
    InvestigationTimelineItem[] Timeline, EvidenceExport[] Exports);
public sealed record EvidenceSearch(string? Text = null, Guid? InvestigationId = null, Guid? CollectionId = null,
    Guid? EndpointId = null, string? EvidenceType = null, string? Hash = null, string? State = null,
    string? Parser = null, string? Tag = null, bool? Bookmarked = null, int Limit = 100, string? Cursor = null);

public interface IForensicWorkspaceStore
{
    Task<ForensicWorkspaceState> LoadAsync(string tenant, CancellationToken ct);
    Task SaveAsync(string tenant, long expectedRevision, ForensicWorkspaceState state, CancellationToken ct);
}

public sealed class FileForensicWorkspaceStore : IForensicWorkspaceStore
{
    readonly ConcurrentDictionary<string, ForensicWorkspaceState> values = new(); readonly object gate = new();
    public Task<ForensicWorkspaceState> LoadAsync(string tenant, CancellationToken ct) => Task.FromResult(values.GetValueOrDefault(tenant, Empty()));
    public Task SaveAsync(string tenant, long expected, ForensicWorkspaceState state, CancellationToken ct)
    { lock (gate) { var current = values.GetValueOrDefault(tenant, Empty()); if (current.Revision != expected) throw new EnrollmentConflictException("FORENSIC_WORKSPACE_STALE", "Workspace changed; reload and retry."); values[tenant] = state with { Revision = expected + 1 }; } return Task.CompletedTask; }
    static ForensicWorkspaceState Empty() => new(0, [], [], [], [], [], [], [], [], []);
}

public static class ForensicWorkspaceSafety
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public const int MaximumInvestigations = 10_000, MaximumPage = 500, MaximumTags = 32, MaximumNotes = 10_000;
    public const long MaximumPackageBytes = 2L * 1024 * 1024 * 1024;
    public static readonly EvidenceParser[] Parsers =
    [
        new("structured-json-summary", "1.0.0", ["SystemInformation","ProcessInventory","UserSessionInventory","ServiceInventory","ScheduledTaskInventory","NetworkState","DnsState","PersistenceSnapshot","Registry"], 16 * 1024 * 1024, 100_000, "application/json", "Validated", "platform-bounded-parser"),
        new("windows-event-records", "1.0.0", ["WindowsEventLog"], 64 * 1024 * 1024, 100_000, "application/x-ndjson", "NotValidated", "platform-bounded-parser"),
        new("file-metadata", "1.0.0", ["File","Directory"], 1024 * 1024, 10_000, "application/json", "CollectionOnly", "metadata-only-no-content-execution")
    ];
    public static readonly InvestigationCollectionProfile[] Profiles = BuildProfiles();
    static InvestigationCollectionProfile[] BuildProfiles()
    {
        EvidenceProfileItem I(string type, EvidenceAvailability status, bool sensitive = false, bool approval = false, string method = "windows-native-structured", string? tool = null, string limitation = "") => new(type, status, sensitive, approval, method, tool, limitation);
        InvestigationCollectionProfile P(string id, string name, string description, EvidenceProfileItem[] items, long bytes, int count, int seconds, bool approval) { var hash = Hash(new { id, version = 1, items, bytes, count, seconds, approval }); return new(id, 1, name, description, items, bytes, count, seconds, approval, hash); }
        var quick = new[] { I("SystemInformation", EvidenceAvailability.CollectionAndParsingSupported), I("ProcessInventory", EvidenceAvailability.CollectionAndParsingSupported), I("UserSessionInventory", EvidenceAvailability.CollectionAndParsingSupported), I("ServiceInventory", EvidenceAvailability.CollectionAndParsingSupported), I("ScheduledTaskInventory", EvidenceAvailability.CollectionAndParsingSupported), I("NetworkState", EvidenceAvailability.CollectionAndParsingSupported), I("PersistenceSnapshot", EvidenceAvailability.CollectionAndParsingSupported) };
        return [
            P("quick-triage","Quick Triage","Native bounded endpoint overview.",quick,4*1024*1024,16,120,false),
            P("standard-incident","Standard Incident Package","Quick triage plus supported event and registry evidence.",[..quick,I("WindowsEventLog",EvidenceAvailability.CollectionOnly,true,true,"windows-eventlog-export"),I("Registry",EvidenceAvailability.CollectionAndParsingSupported,true,true,"windows-registry-structured-export")],64*1024*1024,32,900,true),
            P("malware-investigation","Malware Investigation","Native context plus identity-bound file evidence; memory is not implied.",[..quick,I("File",EvidenceAvailability.CollectionOnly,true,true,"identity-bound-handle-copy")],8L*1024*1024*1024,48,14400,true),
            P("persistence-investigation","Persistence Investigation","Persistence, service, task, Registry and event evidence.",[I("PersistenceSnapshot",EvidenceAvailability.CollectionAndParsingSupported),I("ServiceInventory",EvidenceAvailability.CollectionAndParsingSupported),I("ScheduledTaskInventory",EvidenceAvailability.CollectionAndParsingSupported),I("Registry",EvidenceAvailability.CollectionAndParsingSupported,true,true,"windows-registry-structured-export"),I("WindowsEventLog",EvidenceAvailability.CollectionOnly,true,true,"windows-eventlog-export")],128*1024*1024,32,1800,true),
            P("account-compromise","Account Compromise","Sessions and supported authentication/security logs.",[I("UserSessionInventory",EvidenceAvailability.CollectionAndParsingSupported),I("WindowsEventLog",EvidenceAvailability.CollectionOnly,true,true,"windows-eventlog-export",limitation:"Exact approved channels only"),I("BrowserArtifacts",EvidenceAvailability.NotSupported,true,true,limitation:"No registered browser parser/acquirer")],128*1024*1024,24,1800,true),
            P("ransomware-investigation","Ransomware Investigation","Supported endpoint context and selected identity-bound files.",[..quick,I("WindowsEventLog",EvidenceAvailability.CollectionOnly,true,true,"windows-eventlog-export"),I("File",EvidenceAvailability.CollectionOnly,true,true,"identity-bound-handle-copy"),I("NTFSMetadata",EvidenceAvailability.ToolRequired,true,true,"approved-tool", "approved-ntfs-acquirer","No native raw-volume acquisition")],8L*1024*1024*1024,64,14400,true),
            P("network-investigation","Network Investigation","Network, DNS, process and event context.",[I("NetworkState",EvidenceAvailability.CollectionAndParsingSupported),I("DnsState",EvidenceAvailability.CollectionAndParsingSupported),I("ProcessInventory",EvidenceAvailability.CollectionAndParsingSupported),I("WindowsEventLog",EvidenceAvailability.CollectionOnly,true,true,"windows-eventlog-export")],64*1024*1024,24,1800,true),
            P("full-disk-artifacts","Full Disk Artifacts","Selected filesystem/NTFS artifacts only through an approved registered acquisition tool.",[I("NTFSMetadata",EvidenceAvailability.ToolRequired,true,true,"approved-tool","approved-ntfs-acquirer","Not raw disk imaging"),I("File",EvidenceAvailability.CollectionOnly,true,true,"identity-bound-handle-copy")],8L*1024*1024*1024,32,14400,true),
            P("memory-acquisition","Memory Acquisition","Requires an approved exact-hash memory acquisition tool; unavailable by default.",[I("Memory",EvidenceAvailability.ToolRequired,true,true,"approved-tool","approved-memory-acquirer","No native memory collector and no arbitrary memory scraping")],8L*1024*1024*1024,1,14400,true),
            P("custom","Custom","Bounded selection from registered evidence types; no unrestricted recursion.",[..quick,I("WindowsEventLog",EvidenceAvailability.CollectionOnly,true,true,"windows-eventlog-export"),I("Registry",EvidenceAvailability.CollectionAndParsingSupported,true,true,"windows-registry-structured-export"),I("File",EvidenceAvailability.CollectionOnly,true,true,"identity-bound-handle-copy"),I("Directory",EvidenceAvailability.CollectionOnly,true,true,"bounded-directory-copy",limitation:"Explicit path/extensions/depth/item/byte bounds")],8L*1024*1024*1024,32,14400,true)
        ];
    }
    public static string Hash(object value) => Convert.ToHexString(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(value, Json))).ToLowerInvariant();
    public static void Text(string? value, string field, int max, bool required = true) { if ((required && string.IsNullOrWhiteSpace(value)) || value?.Length > max || value?.Any(char.IsControl) == true) throw new EnrollmentConflictException("FORENSIC_WORKSPACE_TEXT", $"{field} is invalid."); }
    public static string[] Tags(IEnumerable<string> tags) { var v = tags.Distinct(StringComparer.OrdinalIgnoreCase).ToArray(); if (v.Length > MaximumTags || v.Any(x => string.IsNullOrWhiteSpace(x) || x.Length > 64 || x.Any(c => !char.IsLetterOrDigit(c) && c is not '-' and not '_'))) throw new EnrollmentConflictException("FORENSIC_TAG_INVALID", "Tags are bounded alphanumeric metadata."); return v; }
    public static string Cursor(DateTimeOffset at, Guid id) => Convert.ToBase64String(Encoding.UTF8.GetBytes($"{at.UtcTicks}|{id:D}"));
    public static (DateTimeOffset At, Guid Id)? ParseCursor(string? value) { if (string.IsNullOrWhiteSpace(value)) return null; try { var p = Encoding.UTF8.GetString(Convert.FromBase64String(value)).Split('|'); return (new DateTimeOffset(long.Parse(p[0], CultureInfo.InvariantCulture), TimeSpan.Zero), Guid.Parse(p[1])); } catch { throw new EnrollmentConflictException("FORENSIC_CURSOR_INVALID", "Cursor is malformed."); } }
}

public sealed class ForensicWorkspaceService(IForensicWorkspaceStore store)
{
    static ForensicWorkspaceState Empty() => new(0, [], [], [], [], [], [], [], [], []);
    public Task<ForensicWorkspaceState> GetAsync(string tenant, CancellationToken ct) => store.LoadAsync(tenant, ct);
    async Task<ForensicWorkspaceState> Mutate(string tenant, Func<ForensicWorkspaceState, ForensicWorkspaceState> change, CancellationToken ct) { for (var i = 0; i < 3; i++) { var s = await store.LoadAsync(tenant, ct); try { var n = change(s); await store.SaveAsync(tenant, s.Revision, n, ct); return await store.LoadAsync(tenant, ct); } catch (EnrollmentConflictException ex) when (ex.Code == "FORENSIC_WORKSPACE_STALE" && i < 2) { } } throw new EnrollmentConflictException("FORENSIC_WORKSPACE_STALE", "Concurrent workspace change; retry."); }
    static EvidenceCustodyEvent C(string t, Guid i, Guid? c, Guid? e, string actor, string op, string result, string src, string dst, string? hash, string detail) => new(Guid.NewGuid(), t, i, c, e, DateTimeOffset.UtcNow, actor, op, result, src, dst, hash, detail, Guid.NewGuid().ToString("N"));
    public async Task<ForensicInvestigation> CreateAsync(string t, string actor, string title, string description, string priority, string owner, Guid[] endpoints, Guid[] incidents, Guid[] alerts, string[] tags, CancellationToken ct) { ForensicWorkspaceSafety.Text(title, "title", 200); ForensicWorkspaceSafety.Text(description, "description", 4000); ForensicWorkspaceSafety.Text(owner, "owner", 256); if (priority is not ("Low" or "Medium" or "High" or "Critical") || endpoints.Length > 256 || incidents.Length > 256 || alerts.Length > 1024) throw new EnrollmentConflictException("INVESTIGATION_INVALID", "Priority or relationship bounds are invalid."); var now = DateTimeOffset.UtcNow; var x = new ForensicInvestigation(Guid.NewGuid(), t, title, description, InvestigationStatus.Open, priority, owner, [owner], incidents.Distinct().ToArray(), alerts.Distinct().ToArray(), endpoints.Distinct().ToArray(), now, now, null, ForensicWorkspaceSafety.Tags(tags), [], [], [], actor); await Mutate(t, s => { if (s.Investigations.Length >= ForensicWorkspaceSafety.MaximumInvestigations) throw new EnrollmentConflictException("INVESTIGATION_LIMIT", "Tenant investigation bound reached."); return s with { Investigations = [.. s.Investigations, x], Custody = [.. s.Custody, C(t, x.InvestigationId, null, null, actor, "investigation.created", "success", "analyst", "workspace", null, "DFIR investigation created")] }; }, ct); return x; }
    public async Task<ForensicInvestigation> StatusAsync(string t, string actor, Guid id, InvestigationStatus status, string reason, CancellationToken ct) { ForensicWorkspaceSafety.Text(reason, "reason", 1024); ForensicInvestigation? result = null; await Mutate(t, s => { var old = s.Investigations.SingleOrDefault(x => x.InvestigationId == id) ?? throw new KeyNotFoundException(); result = old with { Status = status, UpdatedAt = DateTimeOffset.UtcNow, ClosedAt = status is InvestigationStatus.Closed or InvestigationStatus.Archived ? DateTimeOffset.UtcNow : null }; return s with { Investigations = s.Investigations.Select(x => x.InvestigationId == id ? result : x).ToArray(), Custody = [.. s.Custody, C(t, id, null, null, actor, "investigation.status.changed", "success", "workspace", "workspace", null, reason)] }; }, ct); return result!; }
    public async Task<InvestigationCollection> LinkCollectionAsync(string t, string actor, Guid investigation, InvestigationCollection value, CancellationToken ct) { if (value.TenantId != t || value.InvestigationId != investigation || value.CollectionId == Guid.Empty || string.IsNullOrWhiteSpace(value.IdempotencyKey) || value.IdempotencyKey.Length > 128) throw new EnrollmentConflictException("COLLECTION_LINK_INVALID", "Collection link binding is invalid."); InvestigationCollection? result = null; await Mutate(t, s => { _ = s.Investigations.SingleOrDefault(x => x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); var duplicate = s.Collections.SingleOrDefault(x => x.InvestigationId == investigation && x.IdempotencyKey == value.IdempotencyKey); if (duplicate is not null) { if (duplicate.CollectionId != value.CollectionId) { result = duplicate; return s; } result = value; return s with { Collections = s.Collections.Select(x => x.CollectionId == value.CollectionId ? value : x).ToArray() }; } if (s.Collections.Any(x => x.CollectionId == value.CollectionId)) throw new EnrollmentConflictException("COLLECTION_DUPLICATE", "Collection is already linked."); result = value; return s with { Collections = [.. s.Collections, value], Investigations = s.Investigations.Select(x => x.InvestigationId == investigation ? x with { CollectionIds = [.. x.CollectionIds, value.CollectionId], EndpointIds = x.EndpointIds.Append(value.EndpointId).Distinct().ToArray(), UpdatedAt = DateTimeOffset.UtcNow } : x).ToArray(), Custody = [.. s.Custody, C(t, investigation, value.CollectionId, null, actor, "collection.linked", "success", "forensic-collector", "workspace", null, "Immutable acquisition relationship recorded")] }; }, ct); return result!; }
    public async Task<ForensicWorkspaceArtifact> AddArtifactAsync(string t, string actor, ForensicWorkspaceArtifact value, CancellationToken ct) { if (value.TenantId != t || value.EvidenceId == Guid.Empty || value.InvestigationId == Guid.Empty || value.CollectionId == Guid.Empty || value.Sha256.Length != 64 || !value.Sha256.All(Uri.IsHexDigit) || value.Size < 0 || value.ObjectId.Length > 256) throw new EnrollmentConflictException("EVIDENCE_INVALID", "Evidence identity, hash, size, or storage abstraction is invalid."); await Mutate(t, s => { if (!s.Investigations.Any(x => x.InvestigationId == value.InvestigationId) || !s.Collections.Any(x => x.CollectionId == value.CollectionId && x.InvestigationId == value.InvestigationId)) throw new EnrollmentConflictException("EVIDENCE_BINDING_INVALID", "Evidence must bind to a tenant investigation and collection."); if (s.Artifacts.Any(x => x.EvidenceId == value.EvidenceId)) return s; var custody = C(t, value.InvestigationId, value.CollectionId, value.EvidenceId, actor, "evidence.stored", value.State, value.Source, "object-storage", value.Sha256, "Source bytes are immutable; metadata is separate."); var timeline = new InvestigationTimelineItem(Guid.NewGuid(), value.InvestigationId, value.AcquisitionCompletedAt, "EvidenceAcquired", $"{value.EvidenceType} acquired: {value.Source}", value.EvidenceId, value.CollectionId, value.EndpointId, null, "Observed", "forensic-evidence", value.RelatedEntities, value.RelatedFindings); return s with { Artifacts = [.. s.Artifacts, value], Custody = [.. s.Custody, custody], Timeline = [.. s.Timeline, timeline], Investigations = s.Investigations.Select(x => x.InvestigationId == value.InvestigationId ? x with { EvidenceIds = [.. x.EvidenceIds, value.EvidenceId], UpdatedAt = DateTimeOffset.UtcNow } : x).ToArray() }; }, ct); return value; }
    public async Task<(ForensicWorkspaceArtifact[] Items, string? Next)> SearchAsync(string t, EvidenceSearch q, CancellationToken ct) { if (q.Limit is < 1 or > ForensicWorkspaceSafety.MaximumPage || q.Text?.Length > 256 || q.Hash?.Length > 64) throw new EnrollmentConflictException("EVIDENCE_SEARCH_BOUNDS", "Evidence search is bounded to 500 rows and safe fields."); var s = await store.LoadAsync(t, ct); var c = ForensicWorkspaceSafety.ParseCursor(q.Cursor); var values = s.Artifacts.Where(x => (q.InvestigationId is null || x.InvestigationId == q.InvestigationId) && (q.CollectionId is null || x.CollectionId == q.CollectionId) && (q.EndpointId is null || x.EndpointId == q.EndpointId) && (q.EvidenceType is null || x.EvidenceType == q.EvidenceType) && (q.Hash is null || x.Sha256.Equals(q.Hash, StringComparison.OrdinalIgnoreCase)) && (q.State is null || x.State == q.State) && (q.Parser is null || x.ParserId == q.Parser) && (q.Tag is null || x.Tags.Contains(q.Tag, StringComparer.OrdinalIgnoreCase)) && (q.Bookmarked is null || x.Bookmarked == q.Bookmarked) && (q.Text is null || x.Source.Contains(q.Text, StringComparison.OrdinalIgnoreCase) || x.RequestedPath?.Contains(q.Text, StringComparison.OrdinalIgnoreCase) == true || x.Sha256.Contains(q.Text, StringComparison.OrdinalIgnoreCase))).OrderByDescending(x => x.CreatedAt).ThenByDescending(x => x.EvidenceId); if (c is { } cursor) values = values.Where(x => x.CreatedAt < cursor.At || x.CreatedAt == cursor.At && x.EvidenceId.CompareTo(cursor.Id) < 0).OrderByDescending(x => x.CreatedAt).ThenByDescending(x => x.EvidenceId); var page = values.Take(q.Limit + 1).ToArray(); return (page.Take(q.Limit).ToArray(), page.Length > q.Limit ? ForensicWorkspaceSafety.Cursor(page[q.Limit - 1].CreatedAt, page[q.Limit - 1].EvidenceId) : null); }
    public async Task TagAsync(string t, string actor, Guid investigation, Guid evidence, string[] tags, CancellationToken ct) { var safe = ForensicWorkspaceSafety.Tags(tags); await Mutate(t, s => { var a = s.Artifacts.SingleOrDefault(x => x.EvidenceId == evidence && x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); return s with { Artifacts = s.Artifacts.Select(x => x.EvidenceId == evidence ? x with { Tags = safe } : x).ToArray(), Custody = [.. s.Custody, C(t, investigation, a.CollectionId, evidence, actor, "evidence.tagged", "success", "analyst-metadata", "workspace", a.Sha256, string.Join(',', safe))] }; }, ct); }
    public async Task<InvestigationBookmark> BookmarkAsync(string t, string actor, Guid investigation, Guid evidence, string purpose, CancellationToken ct) { ForensicWorkspaceSafety.Text(purpose, "purpose", 256); InvestigationBookmark? b = null; await Mutate(t, s => { var a = s.Artifacts.SingleOrDefault(x => x.EvidenceId == evidence && x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); b = new(Guid.NewGuid(), t, investigation, evidence, purpose, actor, DateTimeOffset.UtcNow); return s with { Bookmarks = [.. s.Bookmarks, b], Artifacts = s.Artifacts.Select(x => x.EvidenceId == evidence ? x with { Bookmarked = true } : x).ToArray(), Custody = [.. s.Custody, C(t, investigation, a.CollectionId, evidence, actor, "evidence.bookmarked", "success", "analyst-metadata", "workspace", a.Sha256, purpose)] }; }, ct); return b!; }
    public async Task<InvestigationNote> NoteAsync(string t, string actor, Guid investigation, string targetType, string targetId, string body, bool aiDraft, bool accepted, string[] citations, CancellationToken ct) { ForensicWorkspaceSafety.Text(body, "body", 8000); if (targetType is not ("investigation" or "collection" or "artifact" or "timeline" or "entity") || citations.Length > 64 || citations.Any(x => x.Length > 128) || aiDraft && accepted) throw new EnrollmentConflictException("INVESTIGATION_NOTE_INVALID", "Note target, citation bounds, or AI state is invalid."); InvestigationNote? note = null; await Mutate(t, s => { if (!s.Investigations.Any(x => x.InvestigationId == investigation)) throw new KeyNotFoundException(); var prior = s.Notes.Where(x => x.InvestigationId == investigation && x.TargetType == targetType && x.TargetId == targetId).Select(x => x.Version).DefaultIfEmpty(0).Max(); note = new(Guid.NewGuid(), t, investigation, targetType, targetId, prior + 1, body, actor, DateTimeOffset.UtcNow, aiDraft, accepted, citations); return s with { Notes = [.. s.Notes, note], Custody = [.. s.Custody, C(t, investigation, null, null, actor, aiDraft ? "ai.note.drafted" : "analyst.note.appended", "success", "analyst-metadata", "workspace", ForensicWorkspaceSafety.Hash(note), "Append-only note version")] }; }, ct); return note!; }
    public async Task<EvidenceIntegrityStatus> RecordVerificationAsync(string t, string actor, Guid evidence, EvidenceIntegrityStatus status, string detail, CancellationToken ct) { await Mutate(t, s => { var a = s.Artifacts.SingleOrDefault(x => x.EvidenceId == evidence) ?? throw new KeyNotFoundException(); return s with { Artifacts = s.Artifacts.Select(x => x.EvidenceId == evidence ? x with { Integrity = status } : x).ToArray(), Custody = [.. s.Custody, C(t, a.InvestigationId, a.CollectionId, evidence, actor, "evidence.integrity.verified", status.ToString(), "object-storage", "verifier", a.Sha256, detail)] }; }, ct); return status; }
    public async Task<EvidenceParserRun> RecordParserRunAsync(string t, string actor, Guid input, ForensicWorkspaceArtifact output, EvidenceParser parser, int records, string[] warnings, CancellationToken ct) { EvidenceParserRun? run = null; await Mutate(t, s => { var source = s.Artifacts.SingleOrDefault(x => x.EvidenceId == input) ?? throw new KeyNotFoundException(); if (output.DerivedFromEvidenceId != input || output.InvestigationId != source.InvestigationId || output.CollectionId != source.CollectionId || output.TenantId != t) throw new EnrollmentConflictException("PARSER_PROVENANCE_INVALID", "Derived evidence must retain exact source binding."); run = new(Guid.NewGuid(), t, source.InvestigationId, input, output.EvidenceId, parser.ParserId, parser.Version, output.AcquisitionStartedAt, output.AcquisitionCompletedAt, EvidenceParseStatus.Complete, warnings, records, parser.MaximumRecords, output.Sha256); return s with { Artifacts = [.. s.Artifacts.Select(x => x.EvidenceId == input ? x with { ParserId = parser.ParserId, ParserVersion = parser.Version, ParseStatus = EvidenceParseStatus.Complete } : x), output], ParserRuns = [.. s.ParserRuns, run], Investigations = s.Investigations.Select(x => x.InvestigationId == source.InvestigationId ? x with { EvidenceIds = [.. x.EvidenceIds, output.EvidenceId], UpdatedAt = DateTimeOffset.UtcNow } : x).ToArray(), Custody = [.. s.Custody, C(t, source.InvestigationId, source.CollectionId, input, actor, "parser.invoked", "success", "evidence", "parser", source.Sha256, $"{parser.ParserId}/{parser.Version}"), C(t, source.InvestigationId, source.CollectionId, output.EvidenceId, "system:parser", "derived.evidence.created", "success", "parser", "object-storage", output.Sha256, $"source:{input:D}")] }; }, ct); return run!; }
    public async Task<IReadOnlyList<EvidenceCustodyEvent>> CustodyAsync(string t, Guid investigation, Guid? evidence, CancellationToken ct) { var s = await store.LoadAsync(t, ct); return s.Custody.Where(x => x.InvestigationId == investigation && (evidence is null || x.EvidenceId == evidence)).OrderBy(x => x.OccurredAt).Take(5000).ToArray(); }
    public async Task<EvidenceCustodyEvent> RecordCustodyAsync(string t, Guid investigation, Guid? collection, Guid? evidence, string actor, string operation, string result, string source, string destination, string? hash, string detail, CancellationToken ct) { ForensicWorkspaceSafety.Text(operation, "operation", 128); ForensicWorkspaceSafety.Text(detail, "detail", 2048, false); var e = C(t, investigation, collection, evidence, actor, operation, result, source, destination, hash, detail); await Mutate(t, s => { if (!s.Investigations.Any(x => x.InvestigationId == investigation) || collection is { } c && !s.Collections.Any(x => x.CollectionId == c && x.InvestigationId == investigation) || evidence is { } a && !s.Artifacts.Any(x => x.EvidenceId == a && x.InvestigationId == investigation)) throw new EnrollmentConflictException("CUSTODY_BINDING_INVALID", "Custody must bind to an existing tenant investigation and related evidence."); return s with { Custody = [.. s.Custody, e] }; }, ct); return e; }
    public async Task RecordHoldAsync(string t, string actor, Guid investigation, Guid? evidence, Guid holdId, string reason, CancellationToken ct) { await Mutate(t, s => { var inv = s.Investigations.SingleOrDefault(x => x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); var artifact = evidence is null ? null : s.Artifacts.SingleOrDefault(x => x.EvidenceId == evidence && x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); return s with { Investigations = s.Investigations.Select(x => x.InvestigationId == investigation ? inv with { HoldIds = inv.HoldIds.Append(holdId).Distinct().ToArray(), UpdatedAt = DateTimeOffset.UtcNow } : x).ToArray(), Custody = [.. s.Custody, C(t, investigation, artifact?.CollectionId, evidence, actor, "hold.applied", "success", "retention-policy", evidence is null ? "investigation" : "evidence", artifact?.Sha256, $"hold:{holdId:D};reason:{reason}")] }; }, ct); }
    public async Task RecordHoldReleaseAsync(string t, string actor, Guid investigation, Guid? evidence, Guid holdId, CancellationToken ct) { await Mutate(t, s => { var inv = s.Investigations.SingleOrDefault(x => x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); var artifact = evidence is null ? null : s.Artifacts.SingleOrDefault(x => x.EvidenceId == evidence && x.InvestigationId == investigation) ?? throw new KeyNotFoundException(); if (!inv.HoldIds.Contains(holdId)) throw new EnrollmentConflictException("FORENSIC_HOLD_BINDING", "Hold is not bound to this investigation."); return s with { Investigations = s.Investigations.Select(x => x.InvestigationId == investigation ? inv with { HoldIds = inv.HoldIds.Where(x => x != holdId).ToArray(), UpdatedAt = DateTimeOffset.UtcNow } : x).ToArray(), Custody = [.. s.Custody, C(t, investigation, artifact?.CollectionId, evidence, actor, "hold.released", "success", "retention-policy", evidence is null ? "investigation" : "evidence", artifact?.Sha256, $"hold:{holdId:D}")] }; }, ct); }
    public async Task<EvidenceExport> RecordExportAsync(string t, EvidenceExport export, CancellationToken ct) { if (export.TenantId != t) throw new EnrollmentConflictException("EXPORT_TENANT_INVALID", "Export tenant binding is invalid."); await Mutate(t, s => { if (!s.Investigations.Any(x => x.InvestigationId == export.InvestigationId) || export.Included.Any(e => !s.Artifacts.Any(a => a.EvidenceId == e && a.InvestigationId == export.InvestigationId))) throw new EnrollmentConflictException("EXPORT_BINDING_INVALID", "Export must bind to tenant investigation evidence."); return s with { Exports = [.. s.Exports, export], Custody = [.. s.Custody, C(t, export.InvestigationId, null, null, export.RequestedBy, "evidence.package.exported", export.State, "workspace", "object-storage", export.PackageSha256, $"included:{export.Included.Length};excluded:{export.Excluded.Length};failed:{export.Failed.Length};unavailable:{export.Unavailable.Length}")] }; }, ct); return export; }
}
