using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace OpenSecurityPlatform.Foundation;

[JsonConverter(typeof(JsonStringEnumConverter<ResponseActionState>))]
public enum ResponseActionState { Draft, PendingApproval, Approved, Queued, Delivered, Acknowledged, Running, Succeeded, Partial, Failed, TimedOut, CancelRequested, Cancelled, CancelledWithEvidence, Expired, Rejected }
[JsonConverter(typeof(JsonStringEnumConverter<ResponseApprovalState>))]
public enum ResponseApprovalState { NotRequired, Pending, Approved, Rejected, Invalidated }
[JsonConverter(typeof(JsonStringEnumConverter<ResponseIdempotency>))]
public enum ResponseIdempotency { Idempotent, QueryOnly, NonIdempotent }
[JsonConverter(typeof(JsonStringEnumConverter<ResponseFailureCategory>))]
public enum ResponseFailureCategory { None, Validation, Authorization, Integrity, Unsupported, Timeout, Cancelled, Execution, OutputLimit, EndpointOffline }

public sealed record ResponseRetryPolicy(int MaximumDeliveries, int InitialDelaySeconds, int MaximumDelaySeconds);
public sealed record ResponseOutputBounds(int MaximumStructuredBytes, int MaximumStdoutBytes, int MaximumStderrBytes, int MaximumRecords, int MaximumArtifacts, long MaximumArtifactBytes, long MaximumTotalBytes);
public sealed record ResponseActionDefinition(string SchemaVersion, string ActionType, int ActionVersion, string Name, string Description, string RequiredPermission, string[] SupportedPlatforms, string MinimumAgentVersion, string PrivilegeRequirement, string InputSchema, string OutputSchema, int MinimumTimeoutSeconds, int MaximumTimeoutSeconds, ResponseOutputBounds OutputBounds, ResponseRetryPolicy RetryPolicy, bool ApprovalRequired, ResponseIdempotency Idempotency, bool Reversible, string AuditSensitivity, bool Enabled = true);
public sealed record ResponseActionCreate(Guid EndpointId, string ActionType, int ActionVersion, JsonElement Parameters, int TimeoutSeconds = 30, int ExpiresInSeconds = 900, string? CorrelationId = null, Guid? SourceAlertId = null, Guid? SourceIncidentId = null, string? SourceEntityId = null, bool SaveAsDraft = false, string PolicyVersion = "response-policy.v1", [property: JsonIgnore] bool? ApprovalRequiredOverride = null);
public sealed record ResolvedResponseActionCreate(string TenantId, Guid EndpointId, Guid AgentId, string AgentInstallationId, string AnalystId, ResponseActionCreate Input);
public sealed record ResponseApprovalRequest(string ParameterHash, string Reason);
public sealed record ResponseRejectRequest(string Reason);
public sealed record ResponseCancelRequest(string Reason);
public sealed record ResponseArtifact(Guid ArtifactId, string Name, string MediaType, long Size, string Sha256, string ObjectId, Guid ManifestObjectId, DateTimeOffset CreatedAt, DateTimeOffset ExpiresAt);
public sealed record ExpiredResponseArtifact(string TenantId, Guid ActionId, ResponseArtifact Artifact);
public sealed record ResponseResult(Guid ActionId, Guid EndpointId, string AgentInstallationId, string ActionType, int ActionVersion, DateTimeOffset StartedAt, DateTimeOffset CompletedAt, ResponseActionState State, int? ResultCode, JsonElement StructuredResult, string StdoutState, string StderrState, int StdoutBytes, int StderrBytes, bool Truncated, int ResultRecords, string ResultHash, ResponseArtifact[] Artifacts, ResponseFailureCategory FailureCategory, string? FailureReason, string AgentVersion, string ExecutionIdentity, string Integrity, string AuditCorrelation);
public sealed record ResponseAuditEvent(Guid AuditId, string TenantId, Guid ActionId, int ObjectVersion, string Action, string Actor, DateTimeOffset OccurredAt, string ParameterHash, string Reason, IReadOnlyDictionary<string, string?> Before, IReadOnlyDictionary<string, string?> After, string Provenance = "response-control-plane");
public sealed record ResponseActionRecord(string SchemaVersion, Guid ResponseActionId, string TenantId, Guid EndpointId, Guid AgentId, string AgentInstallationId, string ActionType, int ActionVersion, string AnalystId, DateTimeOffset RequestedAt, DateTimeOffset ExpiresAt, JsonElement Parameters, string ParameterHash, string Nonce, string CorrelationId, Guid? SourceAlertId, Guid? SourceIncidentId, string? SourceEntityId, ResponseApprovalState ApprovalState, string? ApproverId, DateTimeOffset? ApprovedAt, string? ApprovalReason, string? ApprovedParameterHash, string PolicyVersion, int TimeoutSeconds, ResponseActionState State, DateTimeOffset? IssuedAt, DateTimeOffset? DeliveredAt, DateTimeOffset? AcknowledgedAt, DateTimeOffset? StartedAt, DateTimeOffset? CompletedAt, DateTimeOffset? CancelRequestedAt, int DeliveryAttempts, int Version, ResponseResult? Result, ResponseAuditEvent[] AuditHistory);
public sealed record SignedResponseActionEnvelope(string SchemaVersion, string TenantId, Guid EndpointId, Guid AgentId, string AgentInstallationId, Guid ActionId, string ActionType, int ActionVersion, JsonElement Parameters, string ParameterHash, DateTimeOffset IssuedAt, DateTimeOffset ExpiresAt, string Nonce, string PolicyVersion, int TimeoutSeconds, string SignatureAlgorithm, string SignatureKeyId, string Signature);
public sealed record ResponseAgentTransition(Guid ActionId, string AgentInstallationId, string Nonce, string ParameterHash, ResponseActionState State, DateTimeOffset OccurredAt, string Reason);
public sealed record ResponseCancellationInstruction(string TenantId, Guid EndpointId, Guid AgentId, string AgentInstallationId, Guid ActionId, string Nonce, string ParameterHash, DateTimeOffset RequestedAt);
public sealed record ResponseArtifactUpload(Guid ArtifactId, string Name, string MediaType, string Sha256,
    string? ContentBase64, Guid? TransferId = null, long Size = 0, [property: JsonIgnore] string? LocalPath = null);
public sealed record ResponseAgentResultUpload(ResponseResult Result, ResponseArtifactUpload[] Artifacts);
public sealed record ResponsePage(IReadOnlyList<ResponseActionRecord> Items, string? NextCursor, long Total);
public sealed record ResponseTarget(Guid EndpointId, Guid AgentId, string AgentInstallationId, string Platform, string AgentVersion, EndpointStatus Status);
public sealed record ResponseHealth(long Requested, long Approvals, long Rejections, long Queued, long Delivered, long Acknowledged, long Running, long Succeeded, long Failed, long TimedOut, long Expired, long Cancelled, long ReplayRejections, long IntegrityFailures, long WorkerQueue, double ExecutionLatencyMilliseconds, double ResultUploadLatencyMilliseconds, DateTimeOffset UpdatedAt);

public static partial class ResponseSafety
{
    public const int MaximumQueuePage = 200;
    public const int MaximumPendingDelivery = 10;
    public const int MaximumParameterBytes = 16 * 1024;
    static readonly Regex SafeName = SafeNameRegex();
    public static readonly IReadOnlyDictionary<string, ResponseActionDefinition> Definitions = new[]
    {
        Definition("endpoint.status", "Endpoint status", "Return bounded agent/platform health.", "response:request:safe", ["windows","linux"], false, 5, 30, 128 * 1024, 100, 0, 0),
        Definition("process.list", "Process inventory", "Return a bounded process snapshot without command execution.", "response:request:safe", ["windows","linux"], false, 5, 60, 1024 * 1024, 500, 0, 0),
        Definition("network.connections", "Network connections", "Return bounded current socket state.", "response:request:safe", ["windows","linux"], false, 5, 60, 1024 * 1024, 500, 0, 0),
        Definition("service.status", "Service status", "Query one strictly named Windows service.", "response:request:safe", ["windows"], false, 5, 30, 128 * 1024, 1, 0, 0),
        Definition("file.metadata", "File metadata", "Query one policy-authorized platform path.", "response:request:safe", ["windows","linux"], false, 5, 60, 256 * 1024, 1, 0, 0),
        Definition("collect.diagnostic", "Platform diagnostic", "Generate one bounded platform-health artifact.", "response:request:safe", ["windows","linux"], true, 5, 60, 256 * 1024, 100, 1, 256 * 1024),
        IsolationDefinition("endpoint.isolate", "Endpoint isolation", "Apply and verify platform-owned Windows network containment.", "isolation:request", true),
        IsolationDefinition("endpoint.unisolate", "Endpoint unisolation", "Remove only platform-owned Windows containment and verify restoration.", "isolation:unisolate", true),
        IsolationDefinition("endpoint.isolation_status", "Endpoint isolation status", "Rediscover and verify effective endpoint isolation state.", "isolation:status:read", false),
        ProcessDefinition("process.terminate", "Terminate exact process", "Terminate one stable process entity after native identity revalidation.", "process-response:terminate", true, false),
        ProcessDefinition("process.suspend", "Suspend exact process", "Apply one bounded response-owned suspension to an exact process.", "process-response:suspend", true, true),
        ProcessDefinition("process.resume", "Resume exact process", "Remove only a response-owned suspension from an exact process.", "process-response:resume", true, true),
        ProcessDefinition("process_tree.terminate", "Terminate pinned process tree", "Terminate a bounded approved process graph snapshot deepest-first.", "process-response:tree-terminate", true, false),
        ProcessDefinition("process.response_status", "Process response status", "Revalidate and return the current state of an exact process entity.", "process-response:read", false, false),
        FileResponseDefinition("file.quarantine", "Quarantine exact file", "Acquire and verify one stable file entity before removing its source path.", "file-response:quarantine", true, true),
        FileResponseDefinition("file.restore", "Restore quarantined file", "Restore one verified quarantine record without overwriting an occupied destination.", "file-response:restore", true, true),
        FileResponseDefinition("file.delete", "Delete exact file", "Permanently delete one stable file entity after separate approval and verification.", "file-response:delete", true, false),
        FileResponseDefinition("file.quarantine_status", "Quarantine status", "Return bounded state for one quarantine identity.", "file-response:read", false, false),
        FileResponseDefinition("file.quarantine_metadata", "Quarantine metadata", "Return bounded metadata for one quarantine identity.", "file-response:read", false, false),
        PersistenceResponseDefinition("registry.value.remove", "Remove persistence registry value", "Back up and remove one exact persistence registry value.", "persistence-response:registry:remove", true, true),
        PersistenceResponseDefinition("registry.value.restore", "Restore persistence registry value", "Restore one exact value from a verified response backup.", "persistence-response:registry:restore", true, true),
        PersistenceResponseDefinition("registry.key.remove", "Remove controlled persistence registry key", "Back up and remove one exact empty controlled persistence key.", "persistence-response:registry:remove", true, true),
        PersistenceResponseDefinition("registry.remediation_status", "Registry remediation status", "Return one bounded remediation backup state.", "persistence-response:read", false, false),
        PersistenceResponseDefinition("service.stop", "Stop exact service", "Stop one exact non-protected service generation.", "persistence-response:service:stop", false, true),
        PersistenceResponseDefinition("service.disable", "Disable exact service", "Back up and disable one exact non-protected service generation.", "persistence-response:service:disable", false, true),
        PersistenceResponseDefinition("service.delete", "Delete exact service", "Back up and delete one exact non-protected service generation.", "persistence-response:service:delete", true, true),
        PersistenceResponseDefinition("service.restore", "Restore supported service", "Restore one supported service configuration from a verified backup.", "persistence-response:service:restore", true, true),
        PersistenceResponseDefinition("scheduled_task.disable", "Disable exact scheduled task", "Back up and disable one exact scheduled-task generation.", "persistence-response:task:disable", false, true),
        PersistenceResponseDefinition("scheduled_task.delete", "Delete exact scheduled task", "Back up and delete one exact scheduled-task generation.", "persistence-response:task:delete", true, true),
        PersistenceResponseDefinition("scheduled_task.restore", "Restore scheduled task", "Restore one exact task from a verified sanitized XML backup.", "persistence-response:task:restore", true, true),
        PersistenceResponseDefinition("wmi.binding.remove", "Remove exact WMI binding", "Back up and remove one exact WMI FilterToConsumerBinding.", "persistence-response:wmi:remove", true, true),
        PersistenceResponseDefinition("wmi.consumer.remove", "Remove exact WMI consumer", "Remove one exact unshared permanent consumer after backup.", "persistence-response:wmi:remove", true, true),
        PersistenceResponseDefinition("wmi.filter.remove", "Remove exact WMI filter", "Remove one exact unshared event filter after backup.", "persistence-response:wmi:remove", true, true),
        PersistenceResponseDefinition("wmi.persistence.restore", "Restore WMI persistence", "Restore supported WMI objects from a verified backup in dependency-safe order.", "persistence-response:wmi:restore", true, true),
        PersistenceResponseDefinition("persistence.remove", "Remove exact persistence configuration", "Orchestrate the authoritative domain action for one exact persistence entity.", "persistence-response:remove", true, true),
        PersistenceResponseDefinition("persistence.restore", "Restore persistence configuration", "Restore one supported persistence configuration from verified backup.", "persistence-response:restore", true, true),
        PersistenceResponseDefinition("persistence.remediation_status", "Persistence remediation status", "Return one bounded persistence remediation state.", "persistence-response:read", false, false),
        ForensicCollectionDefinition(),
    }.ToDictionary(x => x.ActionType, StringComparer.Ordinal);

    static ResponseActionDefinition Definition(string type, string name, string description, string permission, string[] platforms, bool approval, int minTimeout, int maxTimeout, int structured, int records, int artifacts, long artifactBytes) => new("response-action-definition.v1", type, 1, name, description, permission, platforms, ProductRelease.Version, "standard-user", $"{type}.input.v1", $"{type}.output.v1", minTimeout, maxTimeout, new(structured, 0, 0, records, artifacts, artifactBytes, structured + artifactBytes), new(5, 2, 30), approval, ResponseIdempotency.QueryOnly, false, type == "collect.diagnostic" ? "restricted-health" : "standard");
    static ResponseActionDefinition IsolationDefinition(string type, string name, string description, string permission, bool approval) => new("response-action-definition.v1", type, 1, name, description, permission, ["windows"], ProductRelease.Version, "administrator", $"{type}.input.v1", $"{type}.output.v1", 10, 120, new(256 * 1024, 0, 0, 32, 0, 0, 256 * 1024), new(5, 2, 30), approval, type == "endpoint.isolation_status" ? ResponseIdempotency.QueryOnly : ResponseIdempotency.Idempotent, type != "endpoint.isolation_status", "elevated-containment");
    static ResponseActionDefinition ProcessDefinition(string type, string name, string description, string permission, bool approval, bool reversible) => new("response-action-definition.v1", type, 1, name, description, permission, ["windows"], ProductRelease.Version, "administrator", $"{type}.input.v1", $"{type}.output.v1", 5, 120, new(512 * 1024, 0, 0, ProcessResponseSafety.MaximumTreeProcesses, 0, 0, 512 * 1024), new(3, 2, 15), approval, type == "process.response_status" ? ResponseIdempotency.QueryOnly : ResponseIdempotency.NonIdempotent, reversible, "elevated-process-response");
    static ResponseActionDefinition FileResponseDefinition(string type, string name, string description, string permission, bool approval, bool reversible) => new("response-action-definition.v1", type, 1, name, description, permission, ["windows"], ProductRelease.Version, "administrator", $"{type}.input.v1", $"{type}.output.v1", 5, 180, new(512 * 1024, 0, 0, 1, type == "file.quarantine" ? 1 : 0, type == "file.quarantine" ? FileResponseSafety.MaximumFileBytes : 0, 512 * 1024 + (type == "file.quarantine" ? FileResponseSafety.MaximumFileBytes : 0)), new(3, 2, 15), approval, type is "file.quarantine_status" or "file.quarantine_metadata" ? ResponseIdempotency.QueryOnly : ResponseIdempotency.NonIdempotent, reversible, "elevated-file-response");
    static ResponseActionDefinition PersistenceResponseDefinition(string type, string name, string description, string permission, bool approval, bool reversible) => new("response-action-definition.v1", type, 1, name, description, permission, ["windows"], ProductRelease.Version, "administrator", $"{type}.input.v1", $"{type}.output.v1", 5, 180, new(1024 * 1024, 0, 0, 128, PersistenceResponseSafety.IsStatus(type) ? 0 : 1, PersistenceResponseSafety.MaximumBackupBytes, 1024 * 1024 + PersistenceResponseSafety.MaximumBackupBytes), new(3, 2, 15), approval, PersistenceResponseSafety.IsStatus(type) ? ResponseIdempotency.QueryOnly : ResponseIdempotency.NonIdempotent, reversible, "elevated-persistence-remediation");
    static ResponseActionDefinition ForensicCollectionDefinition() => new("response-action-definition.v1", ForensicCollectionSafety.ActionType, 1, "Bounded forensic collection", "Acquire only the immutable profile-bound forensic scope.", "forensics:request:quick", ["windows"], ProductRelease.Version, "profile-dependent", "forensic.collect.input.v1", "forensic.collect.output.v1", 10, ForensicCollectionSafety.MaximumRuntimeSeconds, new(2 * 1024 * 1024, 0, 0, ForensicCollectionSafety.MaximumEvidenceItems, ForensicCollectionSafety.MaximumEvidenceItems + 1, ForensicCollectionSafety.MaximumCollectionBytes, ForensicCollectionSafety.MaximumCollectionBytes + 2 * 1024 * 1024), new(5, 2, 30), true, ResponseIdempotency.NonIdempotent, false, "high-forensic-evidence");

    public static ResponseActionDefinition GetDefinition(string type, int version)
    {
        if (!Definitions.TryGetValue(type, out var definition) || definition.ActionVersion != version || !definition.Enabled) throw new EnrollmentConflictException("RESPONSE_ACTION_UNSUPPORTED", "The action type or version is unsupported or disabled.");
        return definition;
    }

    public static void ValidateParameters(ResponseActionDefinition definition, JsonElement parameters)
    {
        if (parameters.ValueKind != JsonValueKind.Object || JsonSerializer.SerializeToUtf8Bytes(parameters).Length > MaximumParameterBytes) throw new EnrollmentConflictException("RESPONSE_PARAMETERS_INVALID", "Parameters must be a bounded object.");
        var properties = parameters.EnumerateObject().ToArray();
        static void Unknown(JsonProperty[] values, params string[] allowed) { var unknown = values.Select(x => x.Name).Except(allowed, StringComparer.Ordinal).FirstOrDefault(); if (unknown is not null) throw new EnrollmentConflictException("RESPONSE_PARAMETER_UNKNOWN", "An unknown action parameter was rejected."); }
        static int Integer(JsonElement p, string name, int fallback, int min, int max) { if (!p.TryGetProperty(name, out var x)) return fallback; if (x.ValueKind != JsonValueKind.Number || !x.TryGetInt32(out var v) || v < min || v > max) throw new EnrollmentConflictException("RESPONSE_PARAMETER_BOUNDS", $"{name} is outside its allowed range."); return v; }
        static string Text(JsonElement p, string name, int max) { if (!p.TryGetProperty(name, out var x) || x.ValueKind != JsonValueKind.String || x.GetString() is not { } value || value.Length is < 1 || value.Length > max || value.Any(char.IsControl)) throw new EnrollmentConflictException("RESPONSE_PARAMETER_TEXT", $"{name} is invalid."); return value; }
        switch (definition.ActionType)
        {
            case ForensicCollectionSafety.ActionType: ForensicCollectionSafety.ValidateActionParameters(parameters); break;
            case "endpoint.status": Unknown(properties); break;
            case "process.list": Unknown(properties, "maximumRecords"); _ = Integer(parameters, "maximumRecords", 100, 1, definition.OutputBounds.MaximumRecords); break;
            case "network.connections": Unknown(properties, "maximumRecords", "protocol"); _ = Integer(parameters, "maximumRecords", 100, 1, definition.OutputBounds.MaximumRecords); if (parameters.TryGetProperty("protocol", out var protocol) && protocol.GetString() is not ("tcp" or "udp" or "all")) throw new EnrollmentConflictException("RESPONSE_PARAMETER_ENUM", "protocol must be tcp, udp, or all."); break;
            case "service.status": Unknown(properties, "serviceName"); if (!SafeName.IsMatch(Text(parameters, "serviceName", 128))) throw new EnrollmentConflictException("RESPONSE_PARAMETER_NAME", "Service name contains unsupported characters."); break;
            case "file.metadata": Unknown(properties, "path", "includeHash", "maximumHashBytes"); var path = Text(parameters, "path", 1024); var absolute = Path.IsPathFullyQualified(path) || Regex.IsMatch(path, "^[A-Za-z]:[\\\\/]") || path.StartsWith("\\\\\\\\", StringComparison.Ordinal); if (!absolute || path.Contains("..", StringComparison.Ordinal) || path.IndexOfAny(['*', '?', '\0']) >= 0) throw new EnrollmentConflictException("RESPONSE_PATH_INVALID", "File metadata requires one absolute non-traversing path."); if (parameters.TryGetProperty("includeHash", out var hash) && hash.ValueKind is not (JsonValueKind.True or JsonValueKind.False)) throw new EnrollmentConflictException("RESPONSE_PARAMETER_TYPE", "includeHash must be Boolean."); _ = Integer(parameters, "maximumHashBytes", 1024 * 1024, 1, 10 * 1024 * 1024); break;
            case "collect.diagnostic": Unknown(properties, "includeQueueHealth"); if (parameters.TryGetProperty("includeQueueHealth", out var queue) && queue.ValueKind is not (JsonValueKind.True or JsonValueKind.False)) throw new EnrollmentConflictException("RESPONSE_PARAMETER_TYPE", "includeQueueHealth must be Boolean."); break;
            case "endpoint.isolate":
            case "endpoint.unisolate":
            case "endpoint.isolation_status": IsolationSafety.ValidateActionParameters(definition.ActionType, parameters); break;
            case "process.terminate":
            case "process.suspend":
            case "process.resume":
            case "process_tree.terminate":
            case "process.response_status": ProcessResponseSafety.ValidateActionParameters(definition.ActionType, parameters); break;
            case "file.quarantine":
            case "file.restore":
            case "file.delete":
            case "file.quarantine_status":
            case "file.quarantine_metadata": FileResponseSafety.ValidateActionParameters(definition.ActionType, parameters); break;
            case "registry.value.remove":
            case "registry.value.restore":
            case "registry.key.remove":
            case "registry.remediation_status":
            case "service.stop":
            case "service.disable":
            case "service.delete":
            case "service.restore":
            case "scheduled_task.disable":
            case "scheduled_task.delete":
            case "scheduled_task.restore":
            case "wmi.binding.remove":
            case "wmi.consumer.remove":
            case "wmi.filter.remove":
            case "wmi.persistence.restore":
            case "persistence.remove":
            case "persistence.restore":
            case "persistence.remediation_status": PersistenceResponseSafety.ValidateActionParameters(definition.ActionType, parameters); break;
            default: throw new EnrollmentConflictException("RESPONSE_ACTION_UNSUPPORTED", "Unknown action type.");
        }
    }

    public static string ParameterHash(JsonElement parameters) => Convert.ToHexString(SHA256.HashData(CanonicalJson(parameters))).ToLowerInvariant();
    public static byte[] CanonicalJson(JsonElement value)
    {
        using var stream = new MemoryStream(); using (var writer = new Utf8JsonWriter(stream)) WriteCanonical(writer, value); return stream.ToArray();
    }
    static void WriteCanonical(Utf8JsonWriter writer, JsonElement value)
    {
        switch (value.ValueKind) { case JsonValueKind.Object: writer.WriteStartObject(); foreach (var p in value.EnumerateObject().OrderBy(x => x.Name, StringComparer.Ordinal)) { writer.WritePropertyName(p.Name); WriteCanonical(writer, p.Value); } writer.WriteEndObject(); break; case JsonValueKind.Array: writer.WriteStartArray(); foreach (var x in value.EnumerateArray()) WriteCanonical(writer, x); writer.WriteEndArray(); break; default: value.WriteTo(writer); break; }
    }
    public static string EnvelopePayload(SignedResponseActionEnvelope e) => string.Join('\n', e.SchemaVersion, e.TenantId, e.EndpointId.ToString("D"), e.AgentId.ToString("D"), e.AgentInstallationId, e.ActionId.ToString("D"), e.ActionType, e.ActionVersion.ToString(System.Globalization.CultureInfo.InvariantCulture), e.ParameterHash, e.IssuedAt.ToUniversalTime().ToString("O"), e.ExpiresAt.ToUniversalTime().ToString("O"), e.Nonce, e.PolicyVersion, e.TimeoutSeconds.ToString(System.Globalization.CultureInfo.InvariantCulture));
    public static bool VerifyEnvelope(SignedResponseActionEnvelope e, string authorityCertificatePem)
    {
        try { using var certificate = X509Certificate2.CreateFromPem(authorityCertificatePem); using var rsa = certificate.GetRSAPublicKey(); return rsa is not null && e.SignatureAlgorithm == "rsa-sha256-ca-v1" && CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(ParameterHash(e.Parameters)), Encoding.ASCII.GetBytes(e.ParameterHash)) && rsa.VerifyData(Encoding.UTF8.GetBytes(EnvelopePayload(e)), Convert.FromBase64String(e.Signature), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1); } catch (Exception x) when (x is CryptographicException or FormatException) { return false; }
    }
    public static bool IsTerminal(ResponseActionState state) => state is ResponseActionState.Succeeded or ResponseActionState.Partial or ResponseActionState.Failed or ResponseActionState.TimedOut or ResponseActionState.Cancelled or ResponseActionState.CancelledWithEvidence or ResponseActionState.Expired or ResponseActionState.Rejected;
    [GeneratedRegex("^[A-Za-z0-9_.-]{1,128}$", RegexOptions.CultureInvariant)] private static partial Regex SafeNameRegex();
}

public interface IResponseActionRepository
{
    Task<ResponseTarget?> ResolveTargetAsync(string tenant, Guid endpoint, CancellationToken ct);
    Task<ResponseActionRecord> CreateAsync(ResolvedResponseActionCreate input, CancellationToken ct);
    Task<ResponseActionRecord?> GetAsync(string tenant, Guid id, CancellationToken ct);
    Task<ResponsePage> SearchAsync(string tenant, Guid? endpoint, ResponseActionState? state, int pageSize, string? cursor, CancellationToken ct);
    Task<ResponseActionRecord> ApproveAsync(string tenant, Guid id, string approver, ResponseApprovalRequest input, CancellationToken ct);
    Task<ResponseActionRecord> RejectAsync(string tenant, Guid id, string actor, ResponseRejectRequest input, CancellationToken ct);
    Task<ResponseActionRecord> CancelAsync(string tenant, Guid id, string actor, ResponseCancelRequest input, CancellationToken ct);
    Task<IReadOnlyList<ResponseActionRecord>> DeliverAsync(string tenant, Guid endpoint, Guid agent, string installation, CancellationToken ct);
    Task<IReadOnlyList<ResponseCancellationInstruction>> ListCancellationsAsync(string tenant, Guid endpoint, Guid agent, string installation, CancellationToken ct);
    Task<ResponseActionRecord> AgentTransitionAsync(string tenant, Guid endpoint, Guid agent, ResponseAgentTransition input, CancellationToken ct);
    Task<ResponseActionRecord> CompleteAsync(string tenant, Guid endpoint, Guid agent, ResponseAgentResultUpload input, ResponseArtifact[] artifacts, CancellationToken ct);
    Task RecordArtifactDownloadAsync(string tenant, Guid actionId, Guid artifactId, string actor, CancellationToken ct);
    Task<IReadOnlyList<ExpiredResponseArtifact>> ListExpiredArtifactsAsync(CancellationToken ct);
    Task MarkArtifactCleanedAsync(string tenant, Guid artifactId, CancellationToken ct);
    Task SweepAsync(CancellationToken ct);
    Task<ResponseHealth> HealthAsync(string tenant, CancellationToken ct);
}

public class FileResponseActionRepository : IResponseActionRepository, IDisposable
{
    readonly ConcurrentDictionary<(string Tenant, Guid Id), ResponseActionRecord> _values = new(); readonly SemaphoreSlim _gate = new(1, 1); readonly ConcurrentDictionary<string, long[]> _metrics = new();
    readonly ConcurrentDictionary<(string Tenant, Guid Artifact), byte> _cleanedArtifacts = new();
    protected virtual Task<IReadOnlyList<ResponseActionRecord>> LoadAsync(string tenant, CancellationToken ct) => Task.FromResult<IReadOnlyList<ResponseActionRecord>>(_values.Where(x => x.Key.Tenant == tenant).Select(x => x.Value).ToArray());
    protected virtual Task<IReadOnlyList<ResponseActionRecord>> LoadAllAsync(CancellationToken ct) => Task.FromResult<IReadOnlyList<ResponseActionRecord>>(_values.Values.ToArray());
    protected virtual Task PersistAsync(ResponseActionRecord value, IReadOnlyList<ResponseAuditEvent> audit, CancellationToken ct) { _values[(value.TenantId, value.ResponseActionId)] = value; return Task.CompletedTask; }
    public virtual Task<ResponseTarget?> ResolveTargetAsync(string tenant, Guid endpoint, CancellationToken ct) => Task.FromResult<ResponseTarget?>(null);
    static ResponseAuditEvent Audit(ResponseActionRecord x, int version, string action, string actor, string reason, Dictionary<string, string?>? before = null, Dictionary<string, string?>? after = null) => new(Guid.NewGuid(), x.TenantId, x.ResponseActionId, version, action, actor, DateTimeOffset.UtcNow, x.ParameterHash, reason, before ?? [], after ?? []);
    static ResponseActionRecord Add(ResponseActionRecord x, int version, params ResponseAuditEvent[] events) => x with { Version = version, AuditHistory = x.AuditHistory.Concat(events).ToArray() };
    public async Task<ResponseActionRecord> CreateAsync(ResolvedResponseActionCreate request, CancellationToken ct)
    {
        var d = ResponseSafety.GetDefinition(request.Input.ActionType, request.Input.ActionVersion); ResponseSafety.ValidateParameters(d, request.Input.Parameters); if (request.Input.TimeoutSeconds < d.MinimumTimeoutSeconds || request.Input.TimeoutSeconds > d.MaximumTimeoutSeconds || request.Input.ExpiresInSeconds is < 30 or > 86400) throw new EnrollmentConflictException("RESPONSE_TIME_BOUNDS", "Timeout or expiration is outside policy.");
        await _gate.WaitAsync(ct); try { var all = await LoadAsync(request.TenantId, ct); var nonce = Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant(); while (all.Any(x => x.Nonce == nonce)) nonce = Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant(); var now = DateTimeOffset.UtcNow; var hash = ResponseSafety.ParameterHash(request.Input.Parameters); var approvalRequired = IsolationSafety.IsIsolationAction(d.ActionType) && request.Input.ApprovalRequiredOverride.HasValue ? request.Input.ApprovalRequiredOverride.Value : d.ApprovalRequired; var state = request.Input.SaveAsDraft ? ResponseActionState.Draft : approvalRequired ? ResponseActionState.PendingApproval : ResponseActionState.Queued; var approval = approvalRequired ? ResponseApprovalState.Pending : ResponseApprovalState.NotRequired; var id = Guid.NewGuid(); var seed = new ResponseActionRecord("response-action.v1", id, request.TenantId, request.EndpointId, request.AgentId, request.AgentInstallationId, d.ActionType, d.ActionVersion, request.AnalystId, now, now.AddSeconds(request.Input.ExpiresInSeconds), request.Input.Parameters.Clone(), hash, nonce, request.Input.CorrelationId ?? Guid.NewGuid().ToString("N"), request.Input.SourceAlertId, request.Input.SourceIncidentId, request.Input.SourceEntityId, approval, null, null, null, null, request.Input.PolicyVersion, request.Input.TimeoutSeconds, state, state == ResponseActionState.Queued ? now : null, null, null, null, null, null, 0, 1, null, []); var audits = new[] { Audit(seed, 1, "response.requested", request.AnalystId, "authorized typed action request"), Audit(seed, 1, "response.authorization.allowed", request.AnalystId, d.RequiredPermission), Audit(seed, 1, state == ResponseActionState.Queued ? "response.queued" : state == ResponseActionState.PendingApproval ? "response.approval.pending" : "response.draft.saved", request.AnalystId, request.Input.PolicyVersion) }; var value = seed with { AuditHistory = audits }; await PersistAsync(value, audits, ct); _metrics.GetOrAdd(request.TenantId, _ => new long[16])[0]++; return value; } finally { _gate.Release(); }
    }
    public async Task<ResponseActionRecord?> GetAsync(string tenant, Guid id, CancellationToken ct) => (await LoadAsync(tenant, ct)).FirstOrDefault(x => x.ResponseActionId == id);
    public async Task<ResponsePage> SearchAsync(string tenant, Guid? endpoint, ResponseActionState? state, int pageSize, string? cursor, CancellationToken ct) { if (pageSize is < 1 or > ResponseSafety.MaximumQueuePage) throw new EnrollmentConflictException("PAGE_BOUNDS", "Response page size is invalid."); var v = (await LoadAsync(tenant, ct)).Where(x => endpoint is null || x.EndpointId == endpoint).Where(x => state is null || x.State == state).OrderByDescending(x => x.RequestedAt).ThenBy(x => x.ResponseActionId).ToArray(); var offset = cursor is null ? 0 : int.TryParse(TenantCursor.Unprotect(tenant, cursor), out var n) ? n : throw new EnrollmentConflictException("CURSOR_INVALID", "Response cursor is invalid."); var page = v.Skip(offset).Take(pageSize).ToArray(); return new(page, offset + page.Length < v.Length ? TenantCursor.Protect(tenant, (offset + page.Length).ToString(System.Globalization.CultureInfo.InvariantCulture)) : null, v.Length); }
    public async Task<ResponseActionRecord> ApproveAsync(string tenant, Guid id, string approver, ResponseApprovalRequest input, CancellationToken ct) { await _gate.WaitAsync(ct); try { var x = await GetAsync(tenant, id, ct) ?? throw new KeyNotFoundException(); if (x.State != ResponseActionState.PendingApproval || x.ApprovalState != ResponseApprovalState.Pending) throw new EnrollmentConflictException("RESPONSE_APPROVAL_STATE", "Action is not pending approval."); if (x.AnalystId == approver) throw new EnrollmentConflictException("RESPONSE_APPROVER_SEPARATION", "Requester cannot provide required second approval."); if (!CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(x.ParameterHash), Encoding.ASCII.GetBytes(input.ParameterHash))) throw new EnrollmentConflictException("RESPONSE_APPROVAL_HASH", "Approval parameter hash does not match."); var now = DateTimeOffset.UtcNow; var a = Audit(x, x.Version + 1, "response.approved", approver, input.Reason, after: new() { { "parameterHash", x.ParameterHash } }); var q = Audit(x, x.Version + 1, "response.queued", approver, "approved exact action hash"); var v = Add(x with { ApprovalState = ResponseApprovalState.Approved, ApproverId = approver, ApprovedAt = now, ApprovalReason = input.Reason, ApprovedParameterHash = x.ParameterHash, State = ResponseActionState.Queued, IssuedAt = now }, x.Version + 1, a, q); await PersistAsync(v, [a, q], ct); _metrics.GetOrAdd(tenant, _ => new long[16])[1]++; return v; } finally { _gate.Release(); } }
    public async Task<ResponseActionRecord> RejectAsync(string tenant, Guid id, string actor, ResponseRejectRequest input, CancellationToken ct) { await _gate.WaitAsync(ct); try { var x = await GetAsync(tenant, id, ct) ?? throw new KeyNotFoundException(); if (x.State != ResponseActionState.PendingApproval) throw new EnrollmentConflictException("RESPONSE_REJECT_STATE", "Only pending approval may be rejected."); var a = Audit(x, x.Version + 1, "response.rejected", actor, input.Reason); var v = Add(x with { State = ResponseActionState.Rejected, ApprovalState = ResponseApprovalState.Rejected, ApproverId = actor, CompletedAt = DateTimeOffset.UtcNow }, x.Version + 1, a); await PersistAsync(v, [a], ct); _metrics.GetOrAdd(tenant, _ => new long[16])[2]++; return v; } finally { _gate.Release(); } }
    public async Task<ResponseActionRecord> CancelAsync(string tenant, Guid id, string actor, ResponseCancelRequest input, CancellationToken ct) { await _gate.WaitAsync(ct); try { var x = await GetAsync(tenant, id, ct) ?? throw new KeyNotFoundException(); if (ResponseSafety.IsTerminal(x.State)) throw new EnrollmentConflictException("RESPONSE_CANCEL_TERMINAL", "Completed action cannot be cancelled."); var now = DateTimeOffset.UtcNow; var direct = x.State is ResponseActionState.Draft or ResponseActionState.PendingApproval or ResponseActionState.Approved or ResponseActionState.Queued; var next = direct ? ResponseActionState.Cancelled : ResponseActionState.CancelRequested; var a = Audit(x, x.Version + 1, direct ? "response.cancelled" : "response.cancel.requested", actor, input.Reason, new() { { "state", x.State.ToString() } }, new() { { "state", next.ToString() } }); var v = Add(x with { State = next, CancelRequestedAt = now, CompletedAt = direct ? now : x.CompletedAt }, x.Version + 1, a); await PersistAsync(v, [a], ct); if (direct) _metrics.GetOrAdd(tenant, _ => new long[16])[11]++; return v; } finally { _gate.Release(); } }
    public async Task<IReadOnlyList<ResponseActionRecord>> DeliverAsync(string tenant, Guid endpoint, Guid agent, string installation, CancellationToken ct) { await _gate.WaitAsync(ct); try { var all = (await LoadAsync(tenant, ct)).Where(x => x.EndpointId == endpoint && x.AgentId == agent && x.AgentInstallationId == installation && (x.State == ResponseActionState.Queued || x.State == ResponseActionState.Delivered || (x.ActionType == "forensic.collect" && x.State == ResponseActionState.Running)) && x.ExpiresAt > DateTimeOffset.UtcNow).OrderBy(x => x.RequestedAt).Take(ResponseSafety.MaximumPendingDelivery).ToArray(); var result = new List<ResponseActionRecord>(); foreach (var x in all) { if (x.State is ResponseActionState.Delivered or ResponseActionState.Running) { result.Add(x); continue; } var a = Audit(x, x.Version + 1, "response.delivered", "endpoint-channel", "bounded authenticated delivery"); var v = Add(x with { State = ResponseActionState.Delivered, DeliveredAt = DateTimeOffset.UtcNow, DeliveryAttempts = x.DeliveryAttempts + 1 }, x.Version + 1, a); await PersistAsync(v, [a], ct); result.Add(v); _metrics.GetOrAdd(tenant, _ => new long[16])[4]++; } return result; } finally { _gate.Release(); } }
    public async Task<IReadOnlyList<ResponseCancellationInstruction>> ListCancellationsAsync(string tenant, Guid endpoint, Guid agent, string installation, CancellationToken ct) => (await LoadAsync(tenant, ct)).Where(x => x.EndpointId == endpoint && x.AgentId == agent && x.AgentInstallationId == installation && x.State == ResponseActionState.CancelRequested && x.CancelRequestedAt is not null).OrderBy(x => x.CancelRequestedAt).Take(ResponseSafety.MaximumPendingDelivery).Select(x => new ResponseCancellationInstruction(x.TenantId, x.EndpointId, x.AgentId, x.AgentInstallationId, x.ResponseActionId, x.Nonce, x.ParameterHash, x.CancelRequestedAt!.Value)).ToArray();
    public async Task<ResponseActionRecord> AgentTransitionAsync(string tenant, Guid endpoint, Guid agent, ResponseAgentTransition input, CancellationToken ct) { await _gate.WaitAsync(ct); try { var x = await GetAsync(tenant, input.ActionId, ct) ?? throw new KeyNotFoundException(); if (x.EndpointId != endpoint || x.AgentId != agent || x.AgentInstallationId != input.AgentInstallationId || x.Nonce != input.Nonce || x.ParameterHash != input.ParameterHash) throw new EnrollmentConflictException("RESPONSE_BINDING_INVALID", "Endpoint action binding is invalid."); if (x.ActionType == "forensic.collect" && x.State == ResponseActionState.Running && input.State is ResponseActionState.Acknowledged or ResponseActionState.Running) return x; ResponseActionState next; if (input.State == ResponseActionState.Acknowledged && x.State == ResponseActionState.Delivered) next = ResponseActionState.Acknowledged; else if (input.State == ResponseActionState.Running && x.State == ResponseActionState.Acknowledged) next = ResponseActionState.Running; else if (input.State == ResponseActionState.Cancelled && x.State == ResponseActionState.CancelRequested) next = ResponseActionState.Cancelled; else { _metrics.GetOrAdd(tenant, _ => new long[16])[12]++; throw new EnrollmentConflictException("RESPONSE_REPLAY_OR_TRANSITION", "Duplicate, replayed, or invalid endpoint transition rejected."); } var now = DateTimeOffset.UtcNow; var a = Audit(x, x.Version + 1, next == ResponseActionState.Acknowledged ? "response.acknowledged" : next == ResponseActionState.Running ? "response.execution.started" : "response.cancelled", "agent", input.Reason); var v = Add(x with { State = next, AcknowledgedAt = next == ResponseActionState.Acknowledged ? now : x.AcknowledgedAt, StartedAt = next == ResponseActionState.Running ? now : x.StartedAt, CompletedAt = next == ResponseActionState.Cancelled ? now : x.CompletedAt }, x.Version + 1, a); await PersistAsync(v, [a], ct); return v; } finally { _gate.Release(); } }
    public async Task<ResponseActionRecord> CompleteAsync(string tenant, Guid endpoint, Guid agent, ResponseAgentResultUpload upload, ResponseArtifact[] artifacts, CancellationToken ct) { await _gate.WaitAsync(ct); try { var result = upload.Result; var x = await GetAsync(tenant, result.ActionId, ct) ?? throw new KeyNotFoundException(); if (x.EndpointId != endpoint || x.AgentId != agent || x.AgentInstallationId != result.AgentInstallationId || result.ActionType != x.ActionType || result.ActionVersion != x.ActionVersion) throw new EnrollmentConflictException("RESPONSE_RESULT_BINDING", "Result binding is invalid."); if (ResponseSafety.IsTerminal(x.State)) { if (x.Result?.ResultHash == result.ResultHash) return x; throw new EnrollmentConflictException("RESPONSE_RESULT_SPOOF", "Conflicting terminal result rejected."); } if (x.State is not (ResponseActionState.Running or ResponseActionState.CancelRequested)) throw new EnrollmentConflictException("RESPONSE_RESULT_STATE", "Action is not running."); var d = ResponseSafety.GetDefinition(x.ActionType, x.ActionVersion); var structured = JsonSerializer.SerializeToUtf8Bytes(result.StructuredResult).Length; if (structured > d.OutputBounds.MaximumStructuredBytes || result.StdoutBytes > d.OutputBounds.MaximumStdoutBytes || result.StderrBytes > d.OutputBounds.MaximumStderrBytes || result.ResultRecords > d.OutputBounds.MaximumRecords || artifacts.Length > d.OutputBounds.MaximumArtifacts || artifacts.Sum(a => a.Size) > d.OutputBounds.MaximumArtifactBytes || structured + result.StdoutBytes + result.StderrBytes + artifacts.Sum(a => a.Size) > d.OutputBounds.MaximumTotalBytes) throw new EnrollmentConflictException("RESPONSE_OUTPUT_BOUNDS", "Result exceeded action output policy."); if (result.State is not (ResponseActionState.Succeeded or ResponseActionState.Failed or ResponseActionState.Cancelled)) throw new EnrollmentConflictException("RESPONSE_RESULT_STATE", "Result final state is invalid."); var normalized = result with { Artifacts = artifacts }; var expected = Convert.ToHexString(SHA256.HashData(ResponseSafety.CanonicalJson(normalized.StructuredResult))).ToLowerInvariant(); if (expected != normalized.ResultHash) throw new EnrollmentConflictException("RESPONSE_RESULT_INTEGRITY", "Structured result hash is invalid."); var a = Audit(x, x.Version + 1, "response.completed", "agent", normalized.FailureReason ?? normalized.State.ToString(), after: new() { { "resultHash", normalized.ResultHash }, { "state", normalized.State.ToString() } }); var v = Add(x with { State = normalized.State, CompletedAt = normalized.CompletedAt, Result = normalized }, x.Version + 1, a); await PersistAsync(v, [a], ct); return v; } finally { _gate.Release(); } }
    public async Task RecordArtifactDownloadAsync(string tenant, Guid actionId, Guid artifactId, string actor, CancellationToken ct) { await _gate.WaitAsync(ct); try { var x = await GetAsync(tenant, actionId, ct) ?? throw new KeyNotFoundException(); if (x.Result?.Artifacts.All(a => a.ArtifactId != artifactId) != false) throw new KeyNotFoundException(); var a = Audit(x, x.Version + 1, "response.artifact.downloaded", actor, $"artifact:{artifactId:D}"); var v = Add(x, x.Version + 1, a); await PersistAsync(v, [a], ct); } finally { _gate.Release(); } }
    public virtual async Task<IReadOnlyList<ExpiredResponseArtifact>> ListExpiredArtifactsAsync(CancellationToken ct) => (await LoadAllAsync(ct)).SelectMany(x => (x.Result?.Artifacts ?? []).Where(a => a.ExpiresAt <= DateTimeOffset.UtcNow && !_cleanedArtifacts.ContainsKey((x.TenantId, a.ArtifactId))).Select(a => new ExpiredResponseArtifact(x.TenantId, x.ResponseActionId, a))).Take(100).ToArray();
    public virtual Task MarkArtifactCleanedAsync(string tenant, Guid artifactId, CancellationToken ct) { _cleanedArtifacts[(tenant, artifactId)] = 0; return Task.CompletedTask; }
    public async Task SweepAsync(CancellationToken ct) { await _gate.WaitAsync(ct); try { foreach (var x in await LoadAllAsync(ct)) { if (ResponseSafety.IsTerminal(x.State)) continue; ResponseActionState? state = null; string action = ""; if (x.ExpiresAt <= DateTimeOffset.UtcNow && x.State is not ResponseActionState.Running) { state = ResponseActionState.Expired; action = "response.expired"; } else if (x.State == ResponseActionState.Running && x.StartedAt is { } started && started.AddSeconds(x.TimeoutSeconds) <= DateTimeOffset.UtcNow) { state = ResponseActionState.TimedOut; action = "response.timedout"; } if (state is null) continue; var a = Audit(x, x.Version + 1, action, "response-lifecycle-worker", "bounded lifecycle deadline"); var v = Add(x with { State = state.Value, CompletedAt = DateTimeOffset.UtcNow }, x.Version + 1, a); await PersistAsync(v, [a], ct); } } finally { _gate.Release(); } }
    public async Task<ResponseHealth> HealthAsync(string tenant, CancellationToken ct) { var all = await LoadAsync(tenant, ct); long C(ResponseActionState s) => all.LongCount(x => x.State == s); long A(string action) => all.Sum(x => x.AuditHistory.LongCount(a => a.Action == action)); var m = _metrics.GetOrAdd(tenant, _ => new long[16]); var completed = all.Where(x => x.StartedAt is not null && x.CompletedAt is not null).ToArray(); var latency = completed.Length == 0 ? 0 : completed.Average(x => (x.CompletedAt!.Value - x.StartedAt!.Value).TotalMilliseconds); return new(A("response.requested"), A("response.approved"), A("response.rejected"), C(ResponseActionState.Queued), A("response.delivered"), A("response.acknowledged"), C(ResponseActionState.Running), C(ResponseActionState.Succeeded), C(ResponseActionState.Failed), C(ResponseActionState.TimedOut), C(ResponseActionState.Expired), C(ResponseActionState.Cancelled), m[12], m[13], C(ResponseActionState.Queued) + C(ResponseActionState.Delivered), latency, latency, DateTimeOffset.UtcNow); }
    public void Dispose() { _gate.Dispose(); GC.SuppressFinalize(this); }
}
