namespace OpenSecurityPlatform.Foundation;

public static class WindowsExecutionDetectionPack
{
    sealed record Spec(string Key, string Name, string Family, string Technique, int Severity, int Confidence,
        DetectionCondition Condition, string Rationale, string[] Benign, string[] Tuning, string[] Limits);

    public static IReadOnlyList<DetectionProductionFixture> Create(string tenant)
    {
        var specs = new[]
        {
            S("ps-encoded-context", "PowerShell encoded command with suspicious execution context", "PowerShell", "T1059.001", 78, 86, A(E("interpreterType","powershell"),E("encodedArgument","true"),E("suspiciousSwitch","true"),E("hiddenIndicator","true")), "Encoded PowerShell is combined with suspicious switches and hidden/non-interactive context.", Admin, ["allow exact approved script hash, parent and service identity"], CmdLimits),
            S("ps-retrieval-execution", "PowerShell retrieval and execution semantics", "PowerShell", "T1059.001", 88, 92, A(E("interpreterType","powershell"),E("retrievalIndicator","true"),E("executionIndicator","true")), "The command line exposes both retrieval and execution semantics.", Admin, ["allow exact internal repository and signed automation lineage"], CmdLimits),
            S("ps-hidden-retrieval", "Hidden PowerShell with retrieval semantics", "PowerShell", "T1059.001", 80, 87, A(E("interpreterType","powershell"),E("hiddenIndicator","true"),E("retrievalIndicator","true")), "Hidden or non-interactive PowerShell also exposes retrieval behavior.", Admin, ["scope to exact management agent ancestry"], CmdLimits),
            S("ps-office-parent", "Office process launches suspicious PowerShell", "Office/Browser Chains", "T1204.002", 84, 90, A(E("interpreterType","powershell"),I("parentName","winword.exe","excel.exe","powerpnt.exe","outlook.exe"),E("suspiciousSwitch","true")), "Authoritative parent identity links an Office-capable process to suspicious PowerShell arguments.", Office, ["allow exact signed add-in workflow and command hash"], ParentLimits),
            S("ps-browser-parent", "Browser launches retrieval-capable PowerShell", "Office/Browser Chains", "T1059.001", 86, 91, A(E("interpreterType","powershell"),I("parentName","chrome.exe","msedge.exe","firefox.exe","brave.exe"),E("retrievalIndicator","true")), "Browser ancestry and retrieval semantics jointly increase confidence.", Browser, ["allow exact managed browser helper lineage"], ParentLimits),
            S("ps-service-wmi-parent", "Service or WMI launches suspicious PowerShell", "PowerShell", "T1047", 78, 84, A(E("interpreterType","powershell"),I("parentName","services.exe","wmiprvse.exe","taskeng.exe","taskhostw.exe"),E("suspiciousSwitch","true")), "Service, WMI or task ancestry is combined with suspicious PowerShell arguments.", Automation, ["allow exact task/service identity and signer"], ParentLimits),
            S("ps-writable-execution", "PowerShell executes content from user-writable path", "PowerShell", "T1059.001", 76, 84, A(E("interpreterType","powershell"),E("userWritableArgument","true"),E("executionIndicator","true")), "PowerShell execution semantics reference a user-writable location.", Developer, ["allow exact developer/build roots and script hashes"], CmdLimits),
            S("ps-obfuscated-execution", "PowerShell obfuscation with execution semantics", "Encoded/Obfuscated Execution", "T1027", 82, 89, A(E("interpreterType","powershell"),E("obfuscationIndicator","true"),E("executionIndicator","true")), "Bounded token analysis finds obfuscation plus execution semantics.", Admin, ["allow exact approved encoded automation"], CmdLimits),

            S("cmd-obfuscated-chain", "Command shell with bounded obfuscation and nested interpreter", "Script Interpreters", "T1059.003", 72, 82, A(E("interpreterType","cmd"),E("obfuscationIndicator","true"),E("interpreterNestingDepth","2")), "Command shell syntax is obfuscated and nests another interpreter.", Developer, ["allow exact build command and parent identity"], CmdLimits),
            S("cmd-writable-retrieval", "Command shell retrieval into user-writable context", "Script Interpreters", "T1059.003", 78, 86, A(E("interpreterType","cmd"),E("retrievalIndicator","true"),E("userWritableArgument","true")), "Command shell exposes retrieval semantics and a writable destination.", Admin, ["allow exact deployment repository and destination"], CmdLimits),
            S("wscript-writable-script", "WScript executes a user-writable script", "Script Interpreters", "T1059.005", 70, 81, A(E("interpreterType","wscript"),E("userWritableArgument","true"),E("suspiciousSwitch","true")), "WScript combines writable script context with hidden/background semantics.", LoginScripts, ["allow signed enterprise login script identity"], CmdLimits),
            S("cscript-writable-script", "CScript executes obfuscated user-writable content", "Script Interpreters", "T1059.005", 74, 83, A(E("interpreterType","cscript"),E("userWritableArgument","true"),E("obfuscationIndicator","true")), "CScript references writable content with bounded obfuscation indicators.", LoginScripts, ["allow exact administration script hash"], CmdLimits),
            S("mshta-script-context", "MSHTA script semantics with suspicious ancestry", "Script Interpreters", "T1218.005", 82, 89, A(E("interpreterType","mshta"),E("executionIndicator","true"),I("parentName","winword.exe","excel.exe","chrome.exe","msedge.exe","cmd.exe")), "MSHTA exposes script semantics under unusual document, browser or shell ancestry.", ["legacy intranet HTA application"], ["allow exact HTA path, publisher and parent"], CmdLimits),

            S("office-shell-chain", "Office process launches suspicious command shell", "Office/Browser Chains", "T1204.002", 80, 87, A(E("interpreterType","cmd"),I("parentName","winword.exe","excel.exe","powerpnt.exe","outlook.exe"),E("suspiciousSwitch","true")), "Native parent identity proves Office-to-shell ancestry plus suspicious arguments.", Office, ["allow exact signed add-in automation"], ParentLimits),
            S("browser-shell-chain", "Browser process launches suspicious command interpreter", "Office/Browser Chains", "T1059.003", 78, 85, A(I("interpreterType","cmd","powershell","wscript","cscript","mshta"),I("parentName","chrome.exe","msedge.exe","firefox.exe","brave.exe"),E("userWritableArgument","true")), "Browser ancestry combines with a writable script or payload argument.", Browser, ["allow exact browser helper and destination"], ParentLimits),
            S("unsigned-writable-execution", "Unsigned executable launched from user-writable path with suspicious parent", "User-Writable Execution", "T1204.002", 76, 84, A(E("signed","false"),C("path",@"\Users\"),I("parentName","chrome.exe","msedge.exe","powershell.exe","cmd.exe")), "Unsigned state is used only with writable path and suspicious ancestry.", Developer, ["allow exact build output hash and parent"], ["unsigned alone is never sufficient"]),
            S("nested-interpreters", "Unusual nested interpreter execution", "Encoded/Obfuscated Execution", "T1059", 72, 81, A(I("interpreterType","cmd","powershell","mshta"),I("parentName","cmd.exe","powershell.exe","pwsh.exe","mshta.exe"),E("interpreterNestingDepth","2")), "Bounded features and native ancestry identify nested interpreters.", Developer, ["allow exact developer shell chain"], ParentLimits),

            S("rundll32-writable", "Rundll32 loads content from a user-writable path", "LOLBins", "T1218.011", 78, 87, A(E("processName","rundll32.exe"),E("userWritableArgument","true"),I("parentName","cmd.exe","powershell.exe","winword.exe","chrome.exe")), "Rundll32 is combined with writable content and unusual ancestry.", ["portable application setup"], ["allow exact DLL hash, signer and parent"], ProxyLimits),
            S("regsvr32-scriptlet", "Regsvr32 scriptlet or remote proxy execution", "LOLBins", "T1218.010", 86, 92, A(E("processName","regsvr32.exe"),E("retrievalIndicator","true"),E("executionIndicator","true")), "Both remote retrieval and scriptlet execution indicators are exposed.", ["legacy component registration"], ["allow exact signed installer lineage"], ProxyLimits),
            S("mshta-remote-context", "MSHTA remote content with suspicious parent", "LOLBins", "T1218.005", 84, 90, A(E("processName","mshta.exe"),E("retrievalIndicator","true"),I("parentName","cmd.exe","powershell.exe","winword.exe","chrome.exe")), "Remote MSHTA content is joined to unusual ancestry.", ["approved intranet HTA"], ["allow exact internal URL, HTA hash and parent"], ProxyLimits),
            S("certutil-transfer-decode", "Certutil transfer or decode into writable path", "LOLBins", "T1105", 76, 85, A(E("processName","certutil.exe"),E("retrievalIndicator","true"),E("userWritableArgument","true")), "Certutil retrieval/decode syntax identifies a writable destination.", ["certificate administration", "PKI automation"], ["allow exact CA workflow, parent and destination"], ProxyLimits),
            S("bitsadmin-transfer", "BITSAdmin transfer to user-writable path", "LOLBins", "T1197", 74, 83, A(E("processName","bitsadmin.exe"),E("retrievalIndicator","true"),E("userWritableArgument","true")), "BITS command-line transfer semantics and destination are visible.", ["legacy software distribution"], ["allow exact management service and repository"], ["persistent BITS job state is not observable"]),
            S("msiexec-remote", "MSIExec remote or writable package under unusual ancestry", "LOLBins", "T1218.007", 74, 82, A(E("processName","msiexec.exe"),E("retrievalIndicator","true"),I("parentName","cmd.exe","powershell.exe","winword.exe","chrome.exe")), "Remote package semantics and unusual ancestry distinguish this from ordinary deployment.", Deployment, ["allow signed deployment agent and approved repository"], ProxyLimits),
            S("cmstp-writable-inf", "CMSTP launches a user-writable INF under unusual ancestry", "LOLBins", "T1218.003", 76, 84, A(E("processName","cmstp.exe"),E("userWritableArgument","true"),I("parentName","cmd.exe","powershell.exe","winword.exe")), "CMSTP is tied to writable content and suspicious ancestry.", ["legacy connection-profile deployment"], ["allow exact signed INF and deployment parent"], ProxyLimits),
            S("installutil-writable", "InstallUtil executes a user-writable assembly", "LOLBins", "T1218.004", 76, 84, A(E("processName","installutil.exe"),E("userWritableArgument","true"),I("parentName","cmd.exe","powershell.exe","msbuild.exe")), "InstallUtil targets writable content under command/developer ancestry.", Developer, ["allow exact build output, signer and CI identity"], ProxyLimits),
            S("regasm-writable", "RegAsm processes a user-writable assembly", "LOLBins", "T1218.009", 72, 82, A(E("processName","regasm.exe"),E("userWritableArgument","true"),I("parentName","cmd.exe","powershell.exe","msbuild.exe")), "RegAsm target location and ancestry provide context beyond tool name.", Developer, ["allow exact assembly hash and build identity"], ProxyLimits),
            S("regsvcs-writable", "RegSvcs processes a user-writable assembly", "LOLBins", "T1218.009", 74, 83, A(E("processName","regsvcs.exe"),E("userWritableArgument","true"),I("parentName","cmd.exe","powershell.exe","msbuild.exe")), "RegSvcs target location and ancestry provide context beyond tool name.", Developer, ["allow exact assembly hash and build identity"], ProxyLimits),

            S("generic-encoded-interpreter", "Encoded or obfuscated script interpreter with unusual parent", "Encoded/Obfuscated Execution", "T1027", 74, 83, A(I("interpreterType","powershell","cmd","wscript","cscript","mshta"),E("obfuscationIndicator","true"),I("parentName","winword.exe","excel.exe","chrome.exe","msedge.exe","services.exe","wmiprvse.exe")), "Bounded obfuscation features are joined to an unusual parent.", Automation, ["allow exact management workflow"], CmdLimits),
            S("retrieval-execute-interpreter", "Interpreter retrieval and execution chain", "Payload Execution", "T1105", 88, 93, A(I("interpreterType","powershell","cmd","mshta"),E("retrievalIndicator","true"),E("executionIndicator","true")), "One process command exposes retrieval plus execution behavior.", Deployment, ["allow exact signed deployment workflow"], CmdLimits),
            S("writable-payload-parent", "User-writable payload launched by browser or interpreter", "Payload Execution", "T1204.002", 82, 89, A(C("path",@"\Users\"),I("parentName","chrome.exe","msedge.exe","firefox.exe","powershell.exe","cmd.exe","wscript.exe","cscript.exe"),E("signed","false")), "Writable path, unsigned state and suspicious ancestry form a multi-signal payload analytic.", Developer, ["allow exact hash, signer exception and build root"], ["requires all three context signals"])
        };
        return specs.Select((x, i) => Build(tenant, x, i)).ToArray();
    }

    static DetectionProductionFixture Build(string tenant, Spec spec, int index)
    {
        var now = DateTimeOffset.UtcNow; var version = spec.Key == "ps-encoded-context" ? 2 : 1; var id = DetectionDsl.DeterministicId($"sprint39-execution-{spec.Key}"); var exclusionId = DetectionDsl.DeterministicId($"sprint39-exclusion-{spec.Key}-v{version}"); var endpoint = DetectionDsl.DeterministicId($"sprint39-endpoint-{index}"); var excluded = DetectionDsl.DeterministicId($"sprint39-excluded-{index}");
        var leaves = Leaves(spec.Condition).ToArray(); var required = leaves.Select(x => x.Field!).Append("endpointId").Distinct(StringComparer.Ordinal).ToArray();
        var rule = new DetectionDefinition("detection-rule.v1", id, version, tenant, spec.Name, $"Sprint 39 Windows execution analytic. {spec.Rationale} Response recommendation: investigate and collect context; for exact high-confidence payload evidence, consider analyst-approved process response or quarantine.", DetectionRuleStatus.Draft, false, "system:sprint39", now, now, spec.Severity, spec.Confidence, spec.Family, ["production", "windows", "sprint39", "execution-depth"], ["Execution"], [spec.Technique], ["Process"], DetectionRuleType.Event, DetectionDomain.Process, ["canonical process command line", "stable process and parent identity", "bounded versioned command-line features"], required, 120, ["endpointId"], 1, false, null, spec.Condition, DetectionExecutionMode.Live, new("detection+process", 15), [exclusionId], "detection-fixture.v2");
        var exclusion = new DetectionExclusion(exclusionId, tenant, version, $"{spec.Name} exact fixture exclusion", "endpointId", excluded.ToString("D"), true, now.AddMinutes(-5), now.AddDays(30), "Exact and time-bounded Sprint 39 quality fixture", "system:sprint39");
        Dictionary<string, string?> Fields(Guid e) { var f = new Dictionary<string, string?>(StringComparer.Ordinal) { ["endpointId"] = e.ToString("D"), ["processEntityId"] = $"sprint39-process-{index}" }; Add(spec.Condition, f); return f; }
        DetectionEvidenceEvent Ev(Dictionary<string, string?> f, int n, string? overrideTenant = null) { var eid = DetectionDsl.DeterministicId($"{tenant}:{spec.Key}:{n}:{overrideTenant}"); return new(eid, overrideTenant ?? tenant, DetectionDomain.Process, now.AddSeconds(n), Guid.Parse(f["endpointId"]!), f["processEntityId"], f["processEntityId"], f, $"postgresql://platform/sprint39_execution_fixtures/{eid:D}", Quality: ["complete", "source-command-line-preserved"]); }
        var positive = Fields(endpoint); var negative = new Dictionary<string, string?>(positive, StringComparer.Ordinal); foreach (var leaf in leaves) negative[leaf.Field!] = "benign-nonmatch"; var missing = new Dictionary<string, string?>(positive, StringComparer.Ordinal); missing.Remove(required[0]); var benign = new Dictionary<string, string?>(negative, StringComparer.Ordinal); var excludedFields = Fields(excluded); var p = Ev(positive, 1); return new(rule, exclusion, [new($"{spec.Key}-positive", "positive", [p], 1), new($"{spec.Key}-negative", "negative", [Ev(negative, 2)], 0), new($"{spec.Key}-benign", "benign", [Ev(benign, 3)], 0), new($"{spec.Key}-boundary", "boundary", [Ev(positive, 4)], 1), new($"{spec.Key}-missing", "missing-field", [Ev(missing, 5)], 0), new($"{spec.Key}-replay", "replay-duplicate", [p, p], 1), new($"{spec.Key}-suppression", "suppression", [p, p], 1), new($"{spec.Key}-tenant", "tenant-isolation", [Ev(positive, 6, Guid.NewGuid().ToString("D"))], 0), new($"{spec.Key}-exclusion", "exclusion", [Ev(excludedFields, 7)], 0, exclusionId)], spec.Family, spec.Rationale, spec.Benign, ["missing ancestry, signer or command context", "legitimate administration with superficially similar arguments"], spec.Tuning, spec.Limits);
    }

    static Spec S(string key, string name, string family, string technique, int severity, int confidence, DetectionCondition condition, string rationale, string[] benign, string[] tuning, string[] limits) => new(key, name, family, technique, severity, confidence, condition, rationale, benign, tuning, limits);
    static DetectionCondition E(string f, string v) => new(Field: f, Value: v, CaseInsensitive: true);
    static DetectionCondition C(string f, string v) => new(Field: f, Operator: DetectionOperator.Contains, Value: v, CaseInsensitive: true);
    static DetectionCondition I(string f, params string[] v) => new(Field: f, Operator: DetectionOperator.In, Values: v, CaseInsensitive: true);
    static DetectionCondition A(params DetectionCondition[] c) => new(DetectionLogic.And, Children: c);
    static IEnumerable<DetectionCondition> Leaves(DetectionCondition c) { if (c.Logic == DetectionLogic.Predicate) { yield return c; yield break; } foreach (var x in c.Children ?? []) foreach (var y in Leaves(x)) yield return y; }
    static void Add(DetectionCondition c, IDictionary<string, string?> f) { if (c.Logic == DetectionLogic.Predicate && c.Field is not null) { f[c.Field] = c.Operator == DetectionOperator.In ? c.Values![0] : c.Value; return; } foreach (var x in c.Children ?? []) Add(x, f); }
    static readonly string[] Admin = ["PowerShell remoting administration", "signed configuration-management automation"];
    static readonly string[] Office = ["approved Office add-in automation"];
    static readonly string[] Browser = ["managed browser helper workflow"];
    static readonly string[] Automation = ["scheduled administration", "signed management agent"];
    static readonly string[] Developer = ["developer build and test automation", "package manager operation"];
    static readonly string[] LoginScripts = ["enterprise login scripts"];
    static readonly string[] Deployment = ["enterprise software deployment", "Windows servicing"];
    static readonly string[] CmdLimits = ["command line is capped at 16,384 characters and 256 tokens", "features do not decode or execute content"];
    static readonly string[] ParentLimits = ["requires authoritative stable parent identity", "does not claim a document exploit or payload intent"];
    static readonly string[] ProxyLimits = ["tool name alone never matches", "payload success and content are not inferred"];
}
