param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',[int]$TimeoutSeconds=240)
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match '^([^#=]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$admin=@{Authorization="Bearer $($login.access_token)"}
function B64([byte[]]$v){[Convert]::ToBase64String($v).TrimEnd('=').Replace('+','-').Replace('/','_')}
function Jwt($subject){$n=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds();$h=B64([Text.Encoding]::UTF8.GetBytes('{"alg":"HS256","typ":"JWT"}'));$b=B64([Text.Encoding]::UTF8.GetBytes((@{iss='security-platform';aud='security-platform-api';sub=$subject;tid=$cfg.PLATFORM_BOOTSTRAP_TENANT_ID;per=@('platform:admin','forensics:approve:sensitive','forensics:collect','forensics:read');pty='user';iat=$n;exp=$n+1800;jti=[guid]::NewGuid().ToString('N')}|ConvertTo-Json -Compress)));$m=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($cfg.PLATFORM_JWT_SIGNING_KEY));try{"$h.$b.$(B64($m.ComputeHash([Text.Encoding]::ASCII.GetBytes("$h.$b"))))"}finally{$m.Dispose()}}
$approver=@{Authorization="Bearer $(Jwt 'sprint38-release-approver')"}
function Api($method,$path,$body=$null,$headers=$admin){$a=@{Method=$method;Uri="http://127.0.0.1:8080$path";Headers=$headers};if($null-ne$body){$a.ContentType='application/json';$a.Body=$body|ConvertTo-Json -Depth 15 -Compress};(Invoke-RestMethod @a).data}
$row=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select e.id||'|'||e.last_seen_at||'|'||a.version from platform.endpoints e join platform.agents a on a.tenant_id=e.tenant_id and a.endpoint_id=e.id where e.hostname='XDR-VICTIM18' and e.status='online' order by e.last_seen_at desc limit 1;");if(!$row){throw 'Final installed victim endpoint is not online'};$p=$row.Split('|');$endpoint=[ordered]@{id=$p[0];lastSeenAt=$p[1];agentVersion=$p[2]}
$before=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.detection_findings where endpoint_id='$($endpoint.id)';")
$cred=Import-Clixml $CredentialPath;Invoke-Command -VMName $VictimVmName -Credential $cred -ScriptBlock {& systeminfo.exe|Out-Null;& whoami.exe /all|Out-Null;Start-Process "$env:WINDIR\System32\whoami.exe" -Wait -WindowStyle Hidden}
$detectionDeadline=(Get-Date).AddSeconds($TimeoutSeconds);do{Start-Sleep 2;$after=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.detection_findings where endpoint_id='$($endpoint.id)';")}while($after-le$before-and(Get-Date)-lt$detectionDeadline)
$alertId=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select alert_id from platform.alerts order by created_at desc limit 1;").Trim();if(!$alertId){throw 'Controlled alert is unavailable'}
$alert=Api GET "/api/v1/alerts/$alertId"
$incident=Api POST '/api/v1/incidents' @{title='Sprint 38 final release smoke';summary='Final artifact evidence chain';alertIds=@($alert.alertId);groupingReason='controlled Sprint 38 final smoke'}
$action=Api POST '/api/v1/response-actions' @{endpointId=$endpoint.id;actionType='endpoint.status';actionVersion=1;parameters=@{};timeoutSeconds=30;expiresInSeconds=300;correlationId="sprint38-$([guid]::NewGuid().ToString('N'))"}
$responseDeadline=(Get-Date).AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 500;$action=Api GET "/api/v1/response-actions/$($action.responseActionId)"}while($action.state-notin@('Succeeded','Failed','TimedOut','Cancelled','Expired','Rejected')-and(Get-Date)-lt$responseDeadline)
$items=@(@{requestId='system';artifactType='SystemInformation';maximumItems=1;maximumBytes=262144},@{requestId='processes';artifactType='ProcessInventory';maximumItems=32;maximumBytes=524288},@{requestId='network';artifactType='NetworkState';maximumItems=32;maximumBytes=524288})
$collection=Api POST '/api/v1/forensic-collections' @{endpointId=$endpoint.id;profileId='quick-triage';profileVersion=1;requestedArtifacts=$items;reason='Sprint 38 final bounded Quick Triage';expiresInSeconds=900;saveAsDraft=$false;policyVersion='forensic-collection-policy.v1'}
if($collection.approvalState-eq'Pending'){$collection=Api POST "/api/v1/forensic-collections/$($collection.collectionId):approve" @{parameterHash=$collection.parameterHash;reason='Separated Sprint 38 exact-scope approval'} $approver}
$collectionDeadline=(Get-Date).AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 500;$collection=Api GET "/api/v1/forensic-collections/$($collection.collectionId)"}while($collection.state-notin@('Succeeded','Partial','Failed','Cancelled','Expired')-and(Get-Date)-lt$collectionDeadline)
$ui=Invoke-WebRequest http://127.0.0.1:8080/ -UseBasicParsing;$evidenceHashes=@($collection.result.items.sha256|Where-Object{$_});$audit=[long](docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select count(*) from platform.response_action_audit where response_action_id='$($action.responseActionId)';")
$passed=$after-gt$before-and$alert.alertId-and$incident.incidentId-and$action.state-eq'Succeeded'-and$collection.state-eq'Succeeded'-and$evidenceHashes.Count-gt0-and$audit-gt0-and$ui.StatusCode-eq200
$r=[ordered]@{schemaVersion='sprint38-final-smoke.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');endpoint=@{id=$endpoint.id;version=$endpoint.agentVersion;lastSeenAt=$endpoint.lastSeenAt};telemetryToDetection=@{findingsBefore=$before;findingsAfter=$after};alertId=$alert.alertId;incidentId=$incident.incidentId;response=@{id=$action.responseActionId;state=$action.state;auditRows=$audit};forensics=@{collectionId=$collection.collectionId;state=$collection.state;items=$collection.result.items.Count;evidenceHashes=$evidenceHashes};ui=@{status=$ui.StatusCode;bytes=$ui.RawContentLength};passed=$passed};$r|ConvertTo-Json -Depth 10|Set-Content artifacts/sprint38-final-smoke.json -Encoding utf8;$r|ConvertTo-Json -Depth 10;if(-not$passed){exit 1}
