param([string]$VictimVmName='XDR-Victim-Sprint18',[string]$CredentialPath='D:\VMs\XDR-Victim-Sprint18\victim-credential.xml',[string]$Msi='artifacts\sprint38-build-probe8\OpenSecurityPlatform-Agent-1.0.0-x64.msi')
$ErrorActionPreference='Stop';$root=Resolve-Path(Join-Path $PSScriptRoot '..\..');Set-Location $root
$cfg=@{};Get-Content .env|Where-Object{$_-match '^([^#=]+)=(.*)$'}|ForEach-Object{$cfg[$matches[1]]=$matches[2]}
$login=Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/auth/token -ContentType application/json -Body(@{username=$cfg.PLATFORM_BOOTSTRAP_USER;password=$cfg.PLATFORM_BOOTSTRAP_PASSWORD}|ConvertTo-Json -Compress);$headers=@{Authorization="Bearer $($login.access_token)"}
$token=(Invoke-RestMethod -Method Post http://127.0.0.1:8080/api/v1/enrollment-tokens -Headers $headers -ContentType application/json -Body(@{expiresAt=[DateTimeOffset]::UtcNow.AddHours(2).ToString('o');maximumUses=1;allowedPlatforms=@('windows')}|ConvertTo-Json)).data
$credential=Import-Clixml $CredentialPath;$deadline=(Get-Date).AddMinutes(2);do{try{$session=New-PSSession -VMName $VictimVmName -Credential $credential -ErrorAction Stop;break}catch{Start-Sleep 3}}while((Get-Date)-lt$deadline);if(-not$session){throw 'Victim unavailable'}
try{
  $installStartedAt=[DateTimeOffset]::UtcNow
  Invoke-Command $session {New-Item C:\Sprint38Qualification -ItemType Directory -Force|Out-Null;New-Item C:\ProgramData\OpenSecurityPlatform\Agent -ItemType Directory -Force|Out-Null;$hosts="$env:SystemRoot\System32\drivers\etc\hosts";if(-not(Select-String $hosts -Pattern '^172\.18\.128\.1\s+gateway$' -Quiet)){Add-Content $hosts "`r`n172.18.128.1 gateway"}}
  Copy-Item $Msi C:\Sprint38Qualification\agent.msi -ToSession $session;Copy-Item deployment/certificates/ca.crt C:\ProgramData\OpenSecurityPlatform\Agent\ca.crt -ToSession $session
  $native=Invoke-Command $session -ArgumentList $token.metadata.id,$token.secret {param($id,$secret)
    [ordered]@{controlPlaneUrl='https://gateway:8443';enrollmentTokenId=$id.ToString();enrollmentTokenSecret=$secret;dataDirectory='C:\ProgramData\OpenSecurityPlatform\Agent\data';caCertificatePath='C:\ProgramData\OpenSecurityPlatform\Agent\ca.crt';environment='production';credentialStore='platform';forceCertificateRotation=$false}|ConvertTo-Json|Set-Content C:\ProgramData\OpenSecurityPlatform\Agent\agent-config.json -Encoding utf8
    & icacls.exe C:\ProgramData\OpenSecurityPlatform\Agent /inheritance:r /grant:r 'SYSTEM:(OI)(CI)F' 'Administrators:(OI)(CI)F'|Out-Null
    $p=Start-Process msiexec.exe -ArgumentList '/i C:\Sprint38Qualification\agent.msi /qn /norestart /l*v C:\Sprint38Qualification\install.log' -Wait -PassThru
    [pscustomobject]@{installerExit=$p.ExitCode;serviceState=(Get-Service OpenSecurityPlatformAgent -ErrorAction SilentlyContinue).Status.ToString();payloadFiles=@(Get-ChildItem 'C:\Program Files\Open Security Platform\Agent' -File -ErrorAction SilentlyContinue).Count;msiLog='C:\Sprint38Qualification\install.log'}
  }
  $deadline=(Get-Date).AddMinutes(3);do{Start-Sleep 3;$row=(docker exec deployment-postgres-1 psql -U platform -d platform -Atc "select e.id||'|'||e.tenant_id||'|'||e.device_identity||'|'||e.hostname||'|'||e.os_type||'|'||e.os_version||'|'||e.architecture||'|'||e.status||'|'||e.last_seen_at||'|'||a.version||'|'||a.id||'|'||a.instance_id from platform.endpoints e join platform.agents a on a.tenant_id=e.tenant_id and a.endpoint_id=e.id where e.hostname='XDR-VICTIM18' and e.last_seen_at>'$($installStartedAt.UtcDateTime.ToString('o'))'::timestamptz order by e.last_seen_at desc limit 1;");if($row){$p=$row.Split('|');$endpoint=[ordered]@{id=$p[0];tenantId=$p[1];deviceIdentity=$p[2];hostname=$p[3];platform=$p[4];osVersion=$p[5];architecture=$p[6];status=$p[7];lastSeenAt=$p[8];agentVersion=$p[9];agentId=$p[10];installationId=$p[11]}}}while(!$endpoint-and(Get-Date)-lt$deadline)
  $post=Invoke-Command $session {[pscustomobject]@{service=(Get-Service OpenSecurityPlatformAgent).Status.ToString();stateProtected=Test-Path C:\ProgramData\OpenSecurityPlatform\Agent\data\state.dat;oneTimeSecretRemoved=-not((Get-Content C:\ProgramData\OpenSecurityPlatform\Agent\agent-config.json -Raw|ConvertFrom-Json).PSObject.Properties.Name-contains'enrollmentTokenSecret');version=(Get-Item 'C:\Program Files\Open Security Platform\Agent\Platform.Agent.exe').VersionInfo.ProductVersion}}
  $report=[ordered]@{schemaVersion='sprint38-clean-install.v1';capturedAt=[DateTimeOffset]::UtcNow.ToString('o');victim=$VictimVmName;native=$native;endpoint=$endpoint;post=$post;passed=$native.installerExit-eq0-and$native.serviceState-eq'Running'-and$endpoint-and$post.stateProtected-and$post.oneTimeSecretRemoved-and$post.version-like'1.0.0*'}
  $report|ConvertTo-Json -Depth 10|Set-Content artifacts/sprint38-clean-install.json -Encoding utf8;$report|ConvertTo-Json -Depth 10;if(-not$report.passed){exit 1}
}finally{Remove-PSSession $session}
