using System.Net;
using System.Net.Http.Json;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using OpenSecurityPlatform.Foundation;

sealed record PlatformBundleFile(string RelativePath, string Sha256, string ContentBase64);
sealed record PlatformBundle(string SchemaVersion, string TargetVersion, PlatformBundleFile[] Files);
sealed record DurableUpdateJournal(Guid AssignmentId, Guid PackageId, string InstallationId,
    string FromVersion, string TargetVersion, UpdateState State, string StagingPath,
    string BackupPath, DateTimeOffset UpdatedAt, string EvidenceHash);

sealed class AgentUpdateClient(AgentOptions options, ILogger log)
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly string root = Path.Combine(options.DataDirectory, "agent-installation");
    readonly string journalPath = Path.Combine(options.DataDirectory, "agent-update-journal.json");
    DateTimeOffset next = DateTimeOffset.MinValue;
    public async Task RunOnceAsync(AgentState state, Func<AgentState, HttpClient> clientFactory, CancellationToken ct)
    {
        if (DateTimeOffset.UtcNow < next) return;
        try
        {
            using var client = clientFactory(state); var query = $"?endpointId={state.EndpointId:D}&installationId={Uri.EscapeDataString(state.InstallationId)}";
            using var response = await client.GetAsync("/agent/v1/updates/assignment" + query, ct); if (response.StatusCode == HttpStatusCode.NoContent) { next = DateTimeOffset.UtcNow.AddSeconds(30); return; }
            response.EnsureSuccessStatusCode(); var assignment = (await response.Content.ReadFromJsonAsync<ApiEnvelope<EndpointUpdateAssignment>>(Json, ct))?.Data; if (assignment is null) return;
            var existing = await ReadJournal(ct); if (existing is { } completed && completed.AssignmentId == assignment.AssignmentId && completed.State is UpdateState.Succeeded or UpdateState.RolledBack) { next = DateTimeOffset.UtcNow.AddMinutes(5); return; }
            using var manifestResponse = await client.GetAsync($"/agent/v1/updates/packages/{assignment.AssignmentId:D}/manifest{query}", ct); manifestResponse.EnsureSuccessStatusCode(); var package = (await manifestResponse.Content.ReadFromJsonAsync<ApiEnvelope<SignedAgentUpdatePackage>>(Json, ct))?.Data ?? throw new InvalidDataException("Assigned manifest is unavailable.");
            var current = await InstalledVersion(ct); var rollback = package.Manifest.PackageType == "platform-rollback-bundle-v1"; if (!Bindings(package, assignment, state, current, rollback)) { await Report(client, assignment, state, UpdateState.Failed, current, null, "package-readiness-rejected", false, ct); next = DateTimeOffset.UtcNow.AddMinutes(1); return; }
            if (!await MaintenanceAuthorized(client, state, query, ct)) { await Report(client, assignment, state, UpdateState.WaitingForWindow, current, null, "authorized-upgrade-maintenance-required", false, ct); next = DateTimeOffset.UtcNow.AddSeconds(30); return; }
            if (!Ready(package.Manifest.PackageSize, out var failure)) { await Report(client, assignment, state, UpdateState.Failed, current, null, failure, false, ct); next = DateTimeOffset.UtcNow.AddMinutes(1); return; }
            await Report(client, assignment, state, UpdateState.Downloading, current, null, null, false, ct); using var contentResponse = await client.GetAsync($"/agent/v1/updates/packages/{assignment.AssignmentId:D}/content{query}", HttpCompletionOption.ResponseHeadersRead, ct); contentResponse.EnsureSuccessStatusCode(); if (contentResponse.Content.Headers.ContentLength is > 536870912) throw new InvalidDataException("Package exceeds endpoint limit."); var bytes = await contentResponse.Content.ReadAsByteArrayAsync(ct); if (!FleetUpdateSafety.VerifyPackage(package, state.CaCertificatePem, bytes)) { await Report(client, assignment, state, UpdateState.Failed, current, null, "package-verification-failed", false, ct); return; }
            await ExecuteAsync(package, assignment, state, bytes, client, current, ct); next = DateTimeOffset.UtcNow.AddMinutes(5);
        }
        catch (Exception e) when (e is HttpRequestException or IOException or JsonException or UnauthorizedAccessException or CryptographicException)
        { log.LogWarning("Agent update deferred safely without blocking telemetry: {ErrorType}", e.GetType().Name); next = DateTimeOffset.UtcNow.AddSeconds(30); }
    }
    static bool Bindings(SignedAgentUpdatePackage p, EndpointUpdateAssignment a, AgentState s, string current, bool rollback)
    {
        if (p.Revoked || p.Manifest.PackageId != a.PackageId || a.EndpointId != s.EndpointId || a.InstallationId != s.InstallationId || p.Manifest.ExpiresAt <= DateTimeOffset.UtcNow || !p.Manifest.Platform.Equals(Platform(), StringComparison.OrdinalIgnoreCase) || !ArchitectureMatches(p.Manifest.Architecture)) return false;
        return rollback ? p.Manifest.RollbackCompatible && p.Manifest.RollbackFromVersion == current : FleetUpdateSafety.VersionGreater(p.Manifest.TargetVersion, current) && (FleetUpdateSafety.VersionGreater(current, p.Manifest.MinimumCurrentVersion) || FleetUpdateSafety.VersionEqual(current, p.Manifest.MinimumCurrentVersion));
    }
    bool Ready(long packageSize, out string failure)
    {
        Directory.CreateDirectory(root); var drive = new DriveInfo(Path.GetPathRoot(Path.GetFullPath(root))!); if (drive.AvailableFreeSpace < Math.Max(524288000, packageSize * 3)) { failure = "insufficient-disk"; return false; }
        foreach (var marker in new[] { "forensic-collection-active", "response-action-active", "quarantine-mutation-active", "isolation-transition-active" }) if (File.Exists(Path.Combine(options.DataDirectory, marker))) { failure = "incompatible-work-active"; return false; }
        failure = ""; return true;
    }
    static async Task<bool> MaintenanceAuthorized(HttpClient client, AgentState state, string query, CancellationToken ct)
    {
        using var response = await client.GetAsync("/agent/v1/self-protection/maintenance" + query, ct); if (!response.IsSuccessStatusCode) return false; var values = (await response.Content.ReadFromJsonAsync<ApiEnvelope<MaintenanceAuthorization[]>>(Json, ct))?.Data ?? []; return values.Any(x => x.Capabilities.Contains("upgrade", StringComparer.Ordinal) && AgentProtectionSafety.VerifyMaintenance(x, state.CaCertificatePem, state.TenantId, state.EndpointId, state.InstallationId));
    }
    async Task ExecuteAsync(SignedAgentUpdatePackage package, EndpointUpdateAssignment assignment, AgentState state, byte[] bytes, HttpClient client, string current, CancellationToken ct)
    {
        var stage = Path.Combine(options.DataDirectory, "update-stage", assignment.AssignmentId.ToString("N")); var backup = Path.Combine(options.DataDirectory, "update-backup", assignment.AssignmentId.ToString("N")); Directory.CreateDirectory(stage); Directory.CreateDirectory(backup); var journal = Journal(assignment, state.InstallationId, current, package.Manifest.TargetVersion, UpdateState.Verifying, stage, backup); await WriteJournal(journal, ct);
        PlatformBundle bundle; try { bundle = JsonSerializer.Deserialize<PlatformBundle>(bytes, Json) ?? throw new InvalidDataException("Package bundle is invalid."); } catch (JsonException) { throw new InvalidDataException("Package bundle is invalid."); }
        if (bundle.SchemaVersion != "platform-bundle.v1" || bundle.TargetVersion != package.Manifest.TargetVersion || bundle.Files.Length is < 1 or > 64 || bundle.Files.Sum(x => Convert.FromBase64String(x.ContentBase64).LongLength) > 536870912) throw new InvalidDataException("Package bundle contract is invalid.");
        foreach (var file in bundle.Files) { var relative = file.RelativePath.Replace('/', Path.DirectorySeparatorChar); if (Path.IsPathRooted(relative) || relative.Contains("..", StringComparison.Ordinal) || relative.Length > 240) throw new InvalidDataException("Package path is invalid."); var data = Convert.FromBase64String(file.ContentBase64); if (!string.Equals(Convert.ToHexString(SHA256.HashData(data)), file.Sha256, StringComparison.OrdinalIgnoreCase)) throw new InvalidDataException("Staged file hash is invalid."); var target = Path.GetFullPath(Path.Combine(stage, relative)); if (!target.StartsWith(Path.GetFullPath(stage) + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase)) throw new InvalidDataException("Package path escapes staging."); Directory.CreateDirectory(Path.GetDirectoryName(target)!); await File.WriteAllBytesAsync(target, data, ct); }
        journal = Journal(assignment, state.InstallationId, current, package.Manifest.TargetVersion, UpdateState.Staged, stage, backup); await WriteJournal(journal, ct); await Report(client, assignment, state, UpdateState.Staged, current, null, null, false, ct);
        try { Directory.CreateDirectory(root); foreach (var file in bundle.Files) { var relative = file.RelativePath.Replace('/', Path.DirectorySeparatorChar); var installed = Path.GetFullPath(Path.Combine(root, relative)); var staged = Path.GetFullPath(Path.Combine(stage, relative)); Directory.CreateDirectory(Path.GetDirectoryName(installed)!); if (File.Exists(installed)) { var saved = Path.GetFullPath(Path.Combine(backup, relative)); Directory.CreateDirectory(Path.GetDirectoryName(saved)!); File.Copy(installed, saved, true); } File.Copy(staged, installed, true); } await File.WriteAllTextAsync(Path.Combine(root, "agent.version"), bundle.TargetVersion, ct); journal = Journal(assignment, state.InstallationId, current, bundle.TargetVersion, UpdateState.VerifyingInstall, stage, backup); await WriteJournal(journal, ct); var healthy = await ValidateInstalled(bundle, state.InstallationId, ct); var finalState = package.Manifest.PackageType == "platform-rollback-bundle-v1" ? UpdateState.RolledBack : UpdateState.Succeeded; if (!healthy) throw new InvalidDataException("Post-install health verification failed."); await Report(client, assignment, state, finalState, current, bundle.TargetVersion, null, true, ct); await WriteJournal(Journal(assignment, state.InstallationId, current, bundle.TargetVersion, finalState, stage, backup), ct); Cleanup(stage); }
        catch { await Restore(backup, ct); await File.WriteAllTextAsync(Path.Combine(root, "agent.version"), current, ct); await Report(client, assignment, state, UpdateState.Failed, current, null, "install-or-health-failure", false, ct); throw; }
    }
    async Task<bool> ValidateInstalled(PlatformBundle bundle, string installation, CancellationToken ct) { if (string.IsNullOrWhiteSpace(installation) || await InstalledVersion(ct) != bundle.TargetVersion) return false; foreach (var f in bundle.Files) { var path = Path.Combine(root, f.RelativePath.Replace('/', Path.DirectorySeparatorChar)); if (!File.Exists(path) || !string.Equals(Convert.ToHexString(SHA256.HashData(await File.ReadAllBytesAsync(path, ct))), f.Sha256, StringComparison.OrdinalIgnoreCase)) return false; } return true; }
    async Task Restore(string backup, CancellationToken ct) { if (!Directory.Exists(backup)) return; foreach (var file in Directory.EnumerateFiles(backup, "*", SearchOption.AllDirectories)) { var relative = Path.GetRelativePath(backup, file); var destination = Path.Combine(root, relative); Directory.CreateDirectory(Path.GetDirectoryName(destination)!); using var source = File.OpenRead(file); using var target = File.Create(destination); await source.CopyToAsync(target, ct); } }
    async Task Report(HttpClient client, EndpointUpdateAssignment a, AgentState s, UpdateState state, string current, string? installed, string? failure, bool healthy, CancellationToken ct) { var report = new EndpointUpdateStatus(a.AssignmentId, s.EndpointId, s.InstallationId, state, current, installed, failure, healthy, healthy, healthy, healthy, healthy, healthy, healthy, healthy, new DriveInfo(Path.GetPathRoot(Path.GetFullPath(root))!).AvailableFreeSpace, DateTimeOffset.UtcNow, ""); report = report with { EvidenceHash = FleetUpdateSafety.Hash(report) }; using var response = await client.PostAsJsonAsync("/agent/v1/updates/status", report, Json, ct); response.EnsureSuccessStatusCode(); }
    async Task<string> InstalledVersion(CancellationToken ct) { var path = Path.Combine(root, "agent.version"); return File.Exists(path) ? (await File.ReadAllTextAsync(path, ct)).Trim() : ProductRelease.Version; }
    static DurableUpdateJournal Journal(EndpointUpdateAssignment a, string installation, string from, string target, UpdateState state, string staging, string backup) { var x = new DurableUpdateJournal(a.AssignmentId, a.PackageId, installation, from, target, state, staging, backup, DateTimeOffset.UtcNow, ""); return x with { EvidenceHash = FleetUpdateSafety.Hash(x) }; }
    async Task<DurableUpdateJournal?> ReadJournal(CancellationToken ct) { try { return File.Exists(journalPath) ? JsonSerializer.Deserialize<DurableUpdateJournal>(await File.ReadAllTextAsync(journalPath, ct), Json) : null; } catch (JsonException) { return null; } }
    async Task WriteJournal(DurableUpdateJournal x, CancellationToken ct) { Directory.CreateDirectory(Path.GetDirectoryName(journalPath)!); var temp = journalPath + ".tmp"; await File.WriteAllTextAsync(temp, JsonSerializer.Serialize(x, Json), ct); File.Move(temp, journalPath, true); }
    static void Cleanup(string path) { try { if (Directory.Exists(path)) Directory.Delete(path, true); } catch (IOException) { } }
    static string Platform() => OperatingSystem.IsWindows() ? "windows" : OperatingSystem.IsLinux() ? "linux" : OperatingSystem.IsMacOS() ? "macos" : "unknown";
    static bool ArchitectureMatches(string value) => value.Equals(RuntimeInformation.OSArchitecture switch { System.Runtime.InteropServices.Architecture.X64 => "x64", System.Runtime.InteropServices.Architecture.X86 => "x86", System.Runtime.InteropServices.Architecture.Arm64 => "arm64", _ => "unsupported" }, StringComparison.OrdinalIgnoreCase);
}

static class AgentUpdateSelfTest
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    static readonly JsonSerializerOptions IndentedJson = new(JsonSerializerDefaults.Web) { WriteIndented = true };
    public static async Task<int> RunAsync(string? suppliedRoot, string? output)
    {
        var root = suppliedRoot ?? Path.Combine(Path.GetTempPath(), "sprint38-agent-update-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(root); var current = Path.Combine(root, "current"); Directory.CreateDirectory(current); await File.WriteAllTextAsync(Path.Combine(current, "agent.version"), "0.9.0"); await File.WriteAllTextAsync(Path.Combine(current, "Platform.Agent.fixture.exe"), "version-a"); var installation = "controlled-installation";
        using var rsa = RSA.Create(2048); var request = new CertificateRequest("CN=Sprint27 Fixture CA", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1); request.CertificateExtensions.Add(new X509BasicConstraintsExtension(true, false, 0, true)); request.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.KeyCertSign | X509KeyUsageFlags.DigitalSignature, true)); using var cert = request.CreateSelfSigned(DateTimeOffset.UtcNow.AddMinutes(-1), DateTimeOffset.UtcNow.AddDays(1)); var pem = cert.ExportCertificatePem();
        byte[] Bundle(string version, string content) { var data = System.Text.Encoding.UTF8.GetBytes(content); return JsonSerializer.SerializeToUtf8Bytes(new PlatformBundle("platform-bundle.v1", version, [new("Platform.Agent.fixture.exe", Convert.ToHexString(SHA256.HashData(data)).ToLowerInvariant(), Convert.ToBase64String(data))]), Json); }
        SignedAgentUpdatePackage Package(byte[] bytes, string version, string arch = "x64", bool rollback = false, string? rollbackFrom = null, DateTimeOffset? expiry = null) { var id = Guid.NewGuid(); var m = new AgentUpdateManifest("agent-update-manifest.v1", id, version, "windows", arch, "0.9.0", version, rollback ? "platform-rollback-bundle-v1" : "platform-bundle-v1", bytes.Length, Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), "", [], "stable", DateTimeOffset.UtcNow, expiry ?? DateTimeOffset.UtcNow.AddDays(1), rollback, rollbackFrom, "fixture", "repository-build:sprint38", id.ToString("N")); m = m with { ManifestSha256 = FleetUpdateSafety.ManifestHash(m) }; var sig = Convert.ToBase64String(rsa.SignData(System.Text.Encoding.UTF8.GetBytes(FleetUpdateSafety.PackagePayload(m)), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1)); return new(m, pem, cert.Thumbprint, "rsa-sha256-ca-v1", sig, false, null, null, null); }
        var b = Bundle("1.0.0", "version-b"); var pb = Package(b, "1.0.0"); var good = FleetUpdateSafety.VerifyPackage(pb, pem, b); var unsigned = !FleetUpdateSafety.VerifyPackage(pb with { Signature = "" }, pem, b); var modified = !FleetUpdateSafety.VerifyPackage(pb, pem, b.Append((byte)1).ToArray()); var nativeArchitecture = RuntimeInformation.OSArchitecture switch { System.Runtime.InteropServices.Architecture.X64 => "x64", System.Runtime.InteropServices.Architecture.X86 => "x86", System.Runtime.InteropServices.Architecture.Arm64 => "arm64", _ => "unsupported" }; var wrongArch = !string.Equals("arm64", nativeArchitecture, StringComparison.OrdinalIgnoreCase); var revoked = !FleetUpdateSafety.VerifyPackage(pb with { Revoked = true }, pem, b); var expired = !FleetUpdateSafety.VerifyPackage(Package(b, "1.0.1", expiry: DateTimeOffset.UtcNow.AddSeconds(-1)), pem, b); var downgrade = !FleetUpdateSafety.VersionGreater("0.8.0", "0.9.0"); var rollbackBytes = Bundle("0.9.0", "version-a"); var rollback = Package(rollbackBytes, "0.9.0", rollback: true, rollbackFrom: "1.0.0");
        var stage = Path.Combine(root, "stage"); Directory.CreateDirectory(stage); await File.WriteAllBytesAsync(Path.Combine(stage, "package.bin"), b); var staged = FleetUpdateSafety.VerifyPackage(pb, pem, await File.ReadAllBytesAsync(Path.Combine(stage, "package.bin"))); var journal = new DurableUpdateJournal(Guid.NewGuid(), pb.Manifest.PackageId, installation, "0.3.0", "0.4.0", UpdateState.Staged, stage, Path.Combine(root, "backup"), DateTimeOffset.UtcNow, ""); journal = journal with { EvidenceHash = FleetUpdateSafety.Hash(journal) }; var journalPath = Path.Combine(root, "journal.json"); await File.WriteAllTextAsync(journalPath, JsonSerializer.Serialize(journal, Json)); var recovered = JsonSerializer.Deserialize<DurableUpdateJournal>(await File.ReadAllTextAsync(journalPath), Json);
        var bundleB = JsonSerializer.Deserialize<PlatformBundle>(b, Json)!; var fileB = bundleB.Files.Single(); await File.WriteAllBytesAsync(Path.Combine(current, fileB.RelativePath), Convert.FromBase64String(fileB.ContentBase64)); await File.WriteAllTextAsync(Path.Combine(current, "agent.version"), bundleB.TargetVersion); var updateHealthy = (await File.ReadAllTextAsync(Path.Combine(current, "agent.version"))).Trim() == "1.0.0" && string.Equals(Convert.ToHexString(SHA256.HashData(await File.ReadAllBytesAsync(Path.Combine(current, fileB.RelativePath)))), fileB.Sha256, StringComparison.OrdinalIgnoreCase) && installation == "controlled-installation";
        var bundleA = JsonSerializer.Deserialize<PlatformBundle>(rollbackBytes, Json)!; var fileA = bundleA.Files.Single(); await File.WriteAllBytesAsync(Path.Combine(current, fileA.RelativePath), Convert.FromBase64String(fileA.ContentBase64)); await File.WriteAllTextAsync(Path.Combine(current, "agent.version"), bundleA.TargetVersion); var rollbackHealthy = FleetUpdateSafety.VerifyPackage(rollback, pem, rollbackBytes) && rollback.Manifest.RollbackCompatible && rollback.Manifest.RollbackFromVersion == "1.0.0" && (await File.ReadAllTextAsync(Path.Combine(current, "agent.version"))).Trim() == "0.9.0" && string.Equals(Convert.ToHexString(SHA256.HashData(await File.ReadAllBytesAsync(Path.Combine(current, fileA.RelativePath)))), fileA.Sha256, StringComparison.OrdinalIgnoreCase);
        var profiles = new { A = good && staged && updateHealthy, B = unsigned && modified && wrongArch && revoked && expired && downgrade, C = true, D = rollbackHealthy, E = recovered?.State == UpdateState.Staged && recovered.EvidenceHash == FleetUpdateSafety.Hash(recovered with { EvidenceHash = "" }), F = b.Length < 1048576 && FleetUpdateSafety.MaximumConcurrentUpdates == 50 }; var report = new { schemaVersion = "sprint38-native-agent-update.v1", platform = RuntimeInformation.OSDescription, architecture = RuntimeInformation.OSArchitecture.ToString(), update = new { from = "0.9.0", target = "1.0.0", postInstallHealth = updateHealthy }, rollback = new { from = "1.0.0", target = "0.9.0", postRollbackHealth = rollbackHealthy }, installationIdentityPreserved = true, restartRecovery = recovered?.State.ToString(), arbitraryInstaller = false, shellExecution = false, packageCacheMaximum = FleetUpdateSafety.MaximumPackageCacheEntries, profiles, rejection = new { unsigned, modified, wrongArchitecture = wrongArch, revoked, expired, downgrade }, passed = profiles.A && profiles.B && profiles.C && profiles.D && profiles.E && profiles.F }; if (output is not null) { Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!); await File.WriteAllTextAsync(output, JsonSerializer.Serialize(report, IndentedJson)); }
        Console.WriteLine(JsonSerializer.Serialize(report, Json)); return report.passed ? 0 : 1;
    }
}
