using System.Collections.Concurrent;
using System.Diagnostics;
using System.Diagnostics.Eventing.Reader;
using System.Globalization;
using System.IO.Compression;
using System.Net.Http.Json;
using System.Runtime.Versioning;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text.Json;
using System.Xml.Linq;
using Microsoft.Diagnostics.Tracing.Parsers;
using Microsoft.Diagnostics.Tracing.Session;
using OpenSecurityPlatform.Foundation;

sealed record NativeExecutionProcess(int ProcessId, DateTimeOffset StartedAt, string? ImagePath, int? SessionId);
sealed record NativeExecutionEvent(ExecutionEventKind Kind, DateTimeOffset ObservedAt, ExecutionNativeEvidence Native, int? SourcePid, int? TargetPid, int? ThreadId, ulong? StartAddress, string? HandleType, ulong? HandleValue, uint? DesiredAccess, string[] Quality, NativeExecutionProcess? TargetSnapshot = null);
interface IExecutionCollector : IAsyncDisposable { string HandleState { get; } string ThreadState { get; } string MemoryState { get; } string SectionState { get; } bool Elevated { get; } long LostEvents { get; } string[] KnownLimitations { get; } Task StartAsync(CancellationToken ct); Task<IReadOnlyList<NativeExecutionEvent>> PollAsync(CancellationToken ct); }

[SupportedOSPlatform("windows")]
sealed class WindowsExecutionCollector(string dataDirectory) : IExecutionCollector
{
    internal const string SessionName = "OpenSecurityPlatform-ProcessLifecycle-v1";
    const int MaximumBuffered = 100000;
    readonly ConcurrentQueue<NativeExecutionEvent> _events = [];
    readonly string _dataDirectory = dataDirectory;
    EventLogWatcher? _handles;
    long _queued, _overflow, _native;
    public string HandleState { get; private set; } = "stopped";
    public string ThreadState { get; private set; } = "stopped";
    public string MemoryState => "not-observable-by-source";
    public string SectionState => "not-observable-by-source";
    public bool Elevated => new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator);
    public long LostEvents => Interlocked.Read(ref _overflow);
    public string[] KnownLimitations => ["Security event 4656 proves requested object access, not that the requested operation completed.", "Kernel thread-start ETW identifies the target process/thread but does not reliably expose a distinct creator process.", "Public supported sources on this host do not expose trustworthy arbitrary VirtualAlloc/VirtualProtect/WriteProcessMemory/APC/anonymous-section events.", "Microsoft-Windows-Threat-Intelligence is not accessible to this ordinary protected level and is not claimed."];
    public Task StartAsync(CancellationToken ct)
    {
        if (!OperatingSystem.IsWindows()) { HandleState = ThreadState = "unsupported"; return Task.CompletedTask; }
        try { _handles = new(new EventLogQuery("Security", PathType.LogName, "*[System[(EventID=4656)]]")); _handles.EventRecordWritten += OnHandle; _handles.Enabled = true; HandleState = "healthy:audit-policy-dependent"; }
        catch (Exception e) when (e is EventLogException or UnauthorizedAccessException) { HandleState = $"failed:{e.GetType().Name}"; }
        WindowsKernelThreadHub.Subscribe(OnThreadStart);
        ThreadState = WindowsKernelThreadHub.Active ? "healthy:shared-kernel-session" : "waiting:shared-kernel-session";
        return Task.CompletedTask;
    }
    void OnThreadStart(Microsoft.Diagnostics.Tracing.Parsers.Kernel.ThreadTraceData d)
    {
        ThreadState = "healthy:shared-kernel-session";
        EmitThread(d.ProcessID, d.ThreadID, Address(() => d.StartAddr), new DateTimeOffset(d.TimeStamp.ToUniversalTime()), $"{SessionName}:thread-start:{d.ProcessID}:{d.ThreadID}:{d.TimeStampRelativeMSec:F6}:{Interlocked.Increment(ref _native)}", Snapshot(d.ProcessID));
    }
    void EmitThread(int pid, int tid, ulong? address, DateTimeOffset at, string nativeId, NativeExecutionProcess? target) { if (pid <= 0 || tid <= 0) return; var native = new ExecutionNativeEvidence("Microsoft-Windows-Kernel-Thread", "{3D6FA8D1-FE05-11D0-9DDA-00C04FD7BA7C}", "ETW Kernel Session", 1, null, null, null, nativeId, "thread-start", null, ExecutionSafety.EvidenceHash(new { nativeId, pid, tid, address, at })); Enqueue(new(ExecutionEventKind.ThreadCreated, at, native, null, pid, tid, address, null, null, null, ["creator-process-not-observable-by-source"], target)); }
    static NativeExecutionProcess? Snapshot(int pid) { try { using var p = Process.GetProcessById(pid); string? path; try { path = p.MainModule?.FileName; } catch { path = null; } int? session; try { session = p.SessionId; } catch { session = null; } return new(pid, new DateTimeOffset(p.StartTime.ToUniversalTime()), path, session); } catch (Exception e) when (e is ArgumentException or InvalidOperationException or System.ComponentModel.Win32Exception) { return null; } }
    void OnHandle(object? sender, EventRecordWrittenEventArgs args) { if (args.EventException is not null) { Interlocked.Increment(ref _overflow); return; } using var record = args.EventRecord; if (record is null) return; try { var fields = Fields(record); var type = Get(fields, "ObjectType"); if (type is null || !(type.Equals("Process", StringComparison.OrdinalIgnoreCase) || type.Equals("Thread", StringComparison.OrdinalIgnoreCase))) return; var pid = Number(Get(fields, "ProcessId")); var access = Unsigned(Get(fields, "AccessMask")); var handle = Unsigned64(Get(fields, "HandleId")); var at = record.TimeCreated is { } t ? new DateTimeOffset(t.ToUniversalTime()) : DateTimeOffset.UtcNow; var nativeId = $"Security:4656:{record.RecordId}:{pid}:{handle:x}"; var native = new ExecutionNativeEvidence(record.ProviderName ?? "Microsoft-Windows-Security-Auditing", record.ProviderId?.ToString(), "Security", 4656, record.Version, record.Opcode, null, nativeId, "object-handle-requested", Get(fields, "Status"), ExecutionSafety.EvidenceHash(new { nativeId, type, pid, access, handle, at })); Enqueue(new(type.Equals("Process", StringComparison.OrdinalIgnoreCase) ? ExecutionEventKind.ProcessHandleOpened : ExecutionEventKind.ThreadHandleOpened, at, native, pid, null, null, null, type, handle, access, ["target-process-not-observable-by-source", "access-request-not-operation-proof"])); } catch (Exception e) when (e is EventLogException or InvalidOperationException or System.Xml.XmlException or FormatException) { Interlocked.Increment(ref _overflow); } }
    void Enqueue(NativeExecutionEvent value) { if (Interlocked.Increment(ref _queued) > MaximumBuffered) { Interlocked.Decrement(ref _queued); Interlocked.Increment(ref _overflow); return; } _events.Enqueue(value); }
    public Task<IReadOnlyList<NativeExecutionEvent>> PollAsync(CancellationToken ct) { var list = new List<NativeExecutionEvent>(); while (list.Count < 500 && _events.TryDequeue(out var value)) { Interlocked.Decrement(ref _queued); list.Add(value); } return Task.FromResult<IReadOnlyList<NativeExecutionEvent>>(list); }
    static Dictionary<string, string> Fields(EventRecord record) { var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase); var root = XElement.Parse(record.ToXml()); XNamespace ns = "http://schemas.microsoft.com/win/2004/08/events/event"; foreach (var item in root.Descendants(ns + "Data")) { var name = item.Attribute("Name")?.Value; if (!string.IsNullOrWhiteSpace(name)) result[name] = item.Value; } return result; }
    static string? Get(Dictionary<string, string> d, string key) => d.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value) && value != "-" ? value : null; static int? Number(string? value) { if (value is null) return null; if (value.StartsWith("0x", StringComparison.OrdinalIgnoreCase) && int.TryParse(value[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var hex)) return hex; return int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var number) ? number : null; }
    static uint? Unsigned(string? value) { if (value is null) return null; if (value.StartsWith("0x", StringComparison.OrdinalIgnoreCase) && uint.TryParse(value[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var hex)) return hex; return uint.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var number) ? number : null; }
    static ulong? Unsigned64(string? value) { if (value is null) return null; if (value.StartsWith("0x", StringComparison.OrdinalIgnoreCase) && ulong.TryParse(value[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var hex)) return hex; return ulong.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var number) ? number : null; }
    static ulong? Address(Func<ulong> value) { try { var address = value(); return address == 0 ? null : address; } catch { return null; } }
    public ValueTask DisposeAsync()
    {
        WindowsKernelThreadHub.Unsubscribe(OnThreadStart);
        if (_handles is not null) { _handles.Enabled = false; _handles.Dispose(); }
        HandleState = ThreadState = "stopped";
        GC.KeepAlive(_dataDirectory);
        return ValueTask.CompletedTask;
    }
}
sealed class UnsupportedExecutionCollector : IExecutionCollector { public string HandleState => "unsupported"; public string ThreadState => "unsupported"; public string MemoryState => "unsupported"; public string SectionState => "unsupported"; public bool Elevated => false; public long LostEvents => 0; public string[] KnownLimitations => ["Windows execution telemetry is unsupported on this platform."]; public Task StartAsync(CancellationToken ct) => Task.CompletedTask; public Task<IReadOnlyList<NativeExecutionEvent>> PollAsync(CancellationToken ct) => Task.FromResult<IReadOnlyList<NativeExecutionEvent>>([]); public ValueTask DisposeAsync() => ValueTask.CompletedTask; }

sealed class ExecutionTelemetryPipeline : IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web); readonly AgentOptions _options; readonly IExecutionCollector _collector; readonly string _queue, _checkpoint; ExecutionTelemetryPolicy _policy = new(); long _sequence, _queueBytes, _drops, _excluded, _processHandles, _threadHandles, _threads, _relationshipFailures, _rateWindowSecond, _rateCount; DateTimeOffset? _lastSource, _lastUpload; public string CurrentPolicyKey { get; private set; } = "implicit"; public long QueueDepth => Directory.Exists(_queue) ? Directory.EnumerateFiles(_queue, "*.json").LongCount() : 0;
    public ExecutionTelemetryPipeline(AgentOptions options, long sequence) { _options = options; _sequence = sequence; _collector = string.Equals(Environment.GetEnvironmentVariable("PLATFORM_TELEMETRY_DRAIN_ONLY"), "true", StringComparison.OrdinalIgnoreCase) ? new UnsupportedExecutionCollector() : OperatingSystem.IsWindows() ? new WindowsExecutionCollector(options.DataDirectory) : new UnsupportedExecutionCollector(); _queue = Path.Combine(options.DataDirectory, "execution-queue"); _checkpoint = Path.Combine(_queue, "sequence.chk"); Directory.CreateDirectory(_queue); Recover(); _queueBytes = Directory.EnumerateFiles(_queue, "*.json").Sum(x => new FileInfo(x).Length); _sequence = Math.Max(_sequence, ReadCheckpoint()); _sequence = Math.Max(_sequence, Directory.EnumerateFiles(_queue, "*.json").Select(x => long.TryParse(Path.GetFileName(x).Split('-')[0], out var n) ? n : 0).DefaultIfEmpty().Max()); _collector.StartAsync(default).GetAwaiter().GetResult(); }
    public Task<IReadOnlyDictionary<string, string[]>> ApplyPolicyAsync(ExecutionTelemetryPolicy policy, Guid id, int version) { var errors = ExecutionSafety.Validate(policy).ToDictionary(x => x.Key, x => x.Value); if (errors.Count == 0) { _policy = policy; CurrentPolicyKey = $"{id:D}:{version}"; } return Task.FromResult<IReadOnlyDictionary<string, string[]>>(errors); }
    public async Task<long> RunOnceAsync(AgentState state, Func<AgentState, HttpClient> clientFactory, Func<long, CancellationToken, Task> checkpoint, CancellationToken ct) { foreach (var native in await _collector.PollAsync(ct)) { _lastSource = native.ObservedAt; if (!WithinRate()) { Interlocked.Increment(ref _drops); continue; } if (!_policy.Enabled || !Allowed(native)) { Interlocked.Increment(ref _excluded); continue; } var value = Normalize(state, native, Interlocked.Increment(ref _sequence)); if (value is null) continue; try { await Persist(value, ct); await WriteCheckpoint(_sequence, ct); await checkpoint(_sequence, ct); } catch (IOException) { Interlocked.Increment(ref _drops); } } if (QueueDepth > 0 && (_lastUpload is null || DateTimeOffset.UtcNow - _lastUpload >= TimeSpan.FromSeconds(_policy.FlushSeconds))) for (var drain = 0; drain < 8 && QueueDepth > 0; drain++) await Upload(state, clientFactory, ct); return _sequence; }
    bool Allowed(NativeExecutionEvent n) { if (n.Kind == ExecutionEventKind.ProcessHandleOpened && !_policy.ProcessHandles || n.Kind == ExecutionEventKind.ThreadHandleOpened && !_policy.ThreadHandles || n.Kind is ExecutionEventKind.ThreadCreated or ExecutionEventKind.RemoteThreadCreated && !_policy.ThreadCreation) return false; if (n.DesiredAccess is { } mask && (_policy.IncludedAccessMasks is { Length: > 0 } && !_policy.IncludedAccessMasks.Contains(mask) || _policy.ExcludedAccessMasks?.Contains(mask) == true)) return false; return true; }
    bool WithinRate() { var second = DateTimeOffset.UtcNow.ToUnixTimeSeconds(); if (_rateWindowSecond != second) { _rateWindowSecond = second; _rateCount = 0; } return ++_rateCount <= _policy.MaximumEventsPerSecond; }
    bool AllowedResolved(ExecutionProcessRef? source, ExecutionProcessRef? target, NativeExecutionEvent native)
    {
        if (_policy.IncludedSourceProcesses is { Length: > 0 } includeSource && !includeSource.Any(x => Match(x, source?.ImagePath))) return false;
        if (_policy.IncludedTargetProcesses is { Length: > 0 } includeTarget && !includeTarget.Any(x => Match(x, target?.ImagePath))) return false;
        if ((_policy.ExcludedSourceProcesses ?? []).Any(x => Match(x, source?.ImagePath)) || (_policy.ExcludedTargetProcesses ?? []).Any(x => Match(x, target?.ImagePath))) return false;
        if ((_policy.ExcludedExactPaths ?? []).Any(x => string.Equals(x, source?.ImagePath, StringComparison.OrdinalIgnoreCase) || string.Equals(x, target?.ImagePath, StringComparison.OrdinalIgnoreCase))) return false;
        if ((_policy.ExcludedOperations ?? []).Any(x => Match(x, native.Native.NativeOperation))) return false;
        if (_policy.ExcludeSameProcess && source is not null && target is not null && source.ProcessEntityId == target.ProcessEntityId) return false;
        if (_policy.ExcludeSystemNoise && (source?.ProcessId is > 0 and <= 4 || target?.ProcessId is > 0 and <= 4)) return false;
        return !(_policy.ExclusionRules ?? []).Any(x => x.Enabled && RuleMatches(x, source, target, native));
    }
    static bool RuleMatches(ExecutionExclusionRule rule, ExecutionProcessRef? source, ExecutionProcessRef? target, NativeExecutionEvent native) => rule.Category switch
    {
        "source-process" => Match(rule.Pattern, source?.ImagePath),
        "target-process" => Match(rule.Pattern, target?.ImagePath),
        "exact-path" => string.Equals(rule.Pattern, source?.ImagePath, StringComparison.OrdinalIgnoreCase) || string.Equals(rule.Pattern, target?.ImagePath, StringComparison.OrdinalIgnoreCase),
        "operation" => Match(rule.Pattern, native.Native.NativeOperation),
        "access-mask" => native.DesiredAccess is { } mask && (rule.Pattern.Equals(mask.ToString(CultureInfo.InvariantCulture), StringComparison.Ordinal) || rule.Pattern.Equals($"0x{mask:x}", StringComparison.OrdinalIgnoreCase)),
        "same-process" => source is not null && target is not null && source.ProcessEntityId == target.ProcessEntityId,
        "system-category" => source?.ProcessId is > 0 and <= 4 || target?.ProcessId is > 0 and <= 4,
        _ => false
    };
    static bool Match(string pattern, string? value) => !string.IsNullOrWhiteSpace(value) && System.IO.Enumeration.FileSystemName.MatchesSimpleExpression(pattern, value, true);
    ExecutionObservation? Normalize(AgentState state, NativeExecutionEvent n, long sequence) { var source = Resolve(state, n.SourcePid); var target = Resolve(state, n.TargetPid, n.TargetSnapshot); var quality = new List<string>(n.Quality); if (n.SourcePid is not null && source is null) { quality.Add("source-process-unavailable"); Interlocked.Increment(ref _relationshipFailures); } if (n.TargetPid is not null && target is null) { Interlocked.Increment(ref _relationshipFailures); Interlocked.Increment(ref _drops); return null; } if (!AllowedResolved(source, target, n)) { Interlocked.Increment(ref _excluded); return null; } HandleEvidence? handle = null; if (n.HandleType is { } type && n.DesiredAccess is { } access) { handle = new(type, n.HandleValue, access, null, ExecutionSafety.AccessFlags(access), [], "user-mode-request", false); if (n.Kind == ExecutionEventKind.ProcessHandleOpened) Interlocked.Increment(ref _processHandles); else Interlocked.Increment(ref _threadHandles); } ThreadEvidence? thread = null; var relationships = new List<ExecutionRelationship>(); if (n.ThreadId is { } tid && target is { } process) { var entity = ExecutionSafety.ThreadEntityId(state.EndpointId, process.ProcessEntityId, tid, n.ObservedAt, n.Native.NativeEventIdentity); thread = new(entity, tid, null, n.StartAddress, null, null, "created", n.Native.NativeStatus, true); relationships.Add(new("process-thread", n.Native.Provider, "high", n.Native.NativeEventIdentity, false, n.ObservedAt, n.ObservedAt)); Interlocked.Increment(ref _threads); } if (source is not null && target is not null) relationships.Add(new("source-target", n.Native.Provider, "high", n.Native.NativeEventIdentity, false, n.ObservedAt, n.ObservedAt)); var evidence = ExecutionSafety.EvidenceHash(new { n.Native, n.SourcePid, n.TargetPid, n.ThreadId, n.StartAddress, n.HandleType, n.HandleValue, n.DesiredAccess }); return new(Guid.NewGuid(), "execution-event.v1", n.Kind, state.EndpointId, state.AgentId, state.InstallationId, $"{_collector.GetType().Name}:{Environment.MachineName}", n.Native.Provider, "1.0.0", "windows", n.Native, sequence, n.ObservedAt, null, null, "execution-normalization.v1", evidence, quality.Distinct(StringComparer.Ordinal).ToArray(), quality.Count == 0 ? "complete" : "partial", source, target, handle, thread, null, null, relationships.ToArray()); }
    static ExecutionProcessRef? Resolve(AgentState state, int? pid, NativeExecutionProcess? snapshot = null) { if (pid is null or <= 0) return null; if (snapshot is { } captured && captured.ProcessId == pid.Value) { var capturedEntity = ProcessIdentity.Create(state.EndpointId, pid.Value, captured.StartedAt, $"windows:{captured.StartedAt.UtcTicks}"); return new(capturedEntity, pid.Value, captured.StartedAt, captured.ImagePath, null, captured.SessionId, "native-pid-plus-process-start-at-source", "high", true); } try { using var p = Process.GetProcessById(pid.Value); var started = new DateTimeOffset(p.StartTime.ToUniversalTime()); var entity = ProcessIdentity.Create(state.EndpointId, pid.Value, started, $"windows:{started.UtcTicks}"); string? path; try { path = p.MainModule?.FileName; } catch { path = null; } int? session; try { session = p.SessionId; } catch { session = null; } return new(entity, pid.Value, started, path, null, session, "native-pid-plus-process-start", "high", true); } catch (Exception e) when (e is ArgumentException or InvalidOperationException or System.ComponentModel.Win32Exception) { return null; } }
    public ExecutionTelemetryHealth Health(Guid endpoint) => new(endpoint, _policy.Enabled, _collector.HandleState, _collector.ThreadState, _collector.MemoryState, _collector.SectionState, _lastSource, null, _processHandles, _threadHandles, _threads, 0, 0, 0, 0, 0, 0, _relationshipFailures, _collector.LostEvents, 0, QueueDepth, Oldest(), _drops, _excluded, 0, 0, CurrentPolicyKey, ParseVersion(), false, _lastUpload, _sequence, _collector.Elevated, _collector.KnownLimitations);
    async Task Persist(ExecutionObservation value, CancellationToken ct) { var bytes = JsonSerializer.SerializeToUtf8Bytes(value, Json); if (Interlocked.Read(ref _queueBytes) + bytes.Length > _policy.MaximumQueueBytes) throw new IOException("execution-queue-capacity-exceeded"); var final = Path.Combine(_queue, $"{value.Sequence:D20}-{value.EventId:N}.json"); var temp = final + ".tmp"; await using (var stream = new FileStream(temp, FileMode.CreateNew, FileAccess.Write, FileShare.None, 4096, FileOptions.WriteThrough)) { await stream.WriteAsync(bytes, ct); await stream.FlushAsync(ct); stream.Flush(true); } File.Move(temp, final + ".committing"); File.Move(final + ".committing", final); Interlocked.Add(ref _queueBytes, bytes.Length); }
    async Task Upload(AgentState state, Func<AgentState, HttpClient> clientFactory, CancellationToken ct) { var items = new List<(string Path, ExecutionObservation Event)>(); foreach (var path in Directory.EnumerateFiles(_queue, "*.json").OrderBy(x => x)) { var value = ReadQueued(path); if (value is not null) items.Add((path, value)); if (items.Count >= _policy.MaximumBatchEvents) break; } if (items.Count == 0) return; var events = items.Select(x => x.Event).ToArray(); var draft = new ExecutionEventBatch(Guid.NewGuid(), state.EndpointId, state.AgentId, state.InstallationId, events.Min(x => x.Sequence), events.Max(x => x.Sequence), events, Convert.ToHexString(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(events, Json))).ToLowerInvariant()); var canonical = JsonSerializer.SerializeToUtf8Bytes(draft, Json); await using var compressed = new MemoryStream(); await using (var gzip = new GZipStream(compressed, CompressionLevel.Fastest, true)) await gzip.WriteAsync(canonical, ct); using var content = new ByteArrayContent(compressed.ToArray()); content.Headers.ContentType = new("application/json"); content.Headers.ContentEncoding.Add("gzip"); content.Headers.Add("X-Uncompressed-Length", canonical.Length.ToString(CultureInfo.InvariantCulture)); content.Headers.Add("X-Execution-Health", Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(Health(state.EndpointId), Json))); using var client = clientFactory(state); using var response = await client.PostAsync("/agent/v1/execution-event-batches", content, ct); response.EnsureSuccessStatusCode(); var payload = await response.Content.ReadAsByteArrayAsync(ct); if (payload.Length == 0) return; ExecutionBatchAcknowledgement? ack; try { ack = JsonSerializer.Deserialize<ExecutionBatchAcknowledgement>(payload, Json); } catch (JsonException) { return; } if (ack is null) return; var done = ack.AcceptedEventIds.Concat(ack.DuplicateEventIds).ToHashSet(); foreach (var item in items.Where(x => done.Contains(x.Event.EventId))) { var length = new FileInfo(item.Path).Length; File.Delete(item.Path); Interlocked.Add(ref _queueBytes, -length); } foreach (var item in items.Where(x => ack.RejectedEventIds.ContainsKey(x.Event.EventId))) { var length = new FileInfo(item.Path).Length; var quarantine = Path.Combine(_queue, "quarantine"); Directory.CreateDirectory(quarantine); var reason = new string(ack.RejectedEventIds[item.Event.EventId].Where(char.IsLetterOrDigit).Take(64).ToArray()); File.Move(item.Path, Path.Combine(quarantine, $"{Path.GetFileNameWithoutExtension(item.Path)}.rejected-{reason}.json"), true); Interlocked.Add(ref _queueBytes, -length); } _lastUpload = DateTimeOffset.UtcNow; }
    ExecutionObservation? ReadQueued(string path)
    {
        try { return JsonSerializer.Deserialize<ExecutionObservation>(File.ReadAllBytes(path), Json); }
        catch (Exception ex) when (ex is JsonException or IOException)
        {
            var quarantine = Path.Combine(_queue, "quarantine"); Directory.CreateDirectory(quarantine);
            try { var length = new FileInfo(path).Length; File.Move(path, Path.Combine(quarantine, $"{Path.GetFileNameWithoutExtension(path)}.invalid.json"), true); Interlocked.Add(ref _queueBytes, -length); } catch (IOException) { }
            return null;
        }
    }
    long ReadCheckpoint() { try { return long.TryParse(File.ReadAllText(_checkpoint), NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? Math.Max(0, value) : 0; } catch (IOException) { return 0; } }
    async Task WriteCheckpoint(long value, CancellationToken ct) { var temp = _checkpoint + ".tmp"; await File.WriteAllTextAsync(temp, value.ToString(CultureInfo.InvariantCulture), ct); File.Move(temp, _checkpoint, true); }
    void Recover() { foreach (var path in Directory.EnumerateFiles(_queue, "*.tmp").Concat(Directory.EnumerateFiles(_queue, "*.committing")).ToArray()) try { var final = path.EndsWith(".committing", StringComparison.Ordinal) ? path[..^11] : path[..^4]; if (!File.Exists(final)) File.Move(path, final); else File.Delete(path); } catch (IOException) { } }
    long Oldest() { var files = Directory.EnumerateFiles(_queue, "*.json").Select(x => new FileInfo(x)).ToArray(); return files.Length == 0 ? 0 : (long)Math.Max(0, (DateTimeOffset.UtcNow - files.Min(x => x.CreationTimeUtc)).TotalSeconds); }
    int? ParseVersion() => int.TryParse(CurrentPolicyKey.Split(':').LastOrDefault(), out var value) ? value : null; public async ValueTask DisposeAsync() => await _collector.DisposeAsync();
}
