using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class OpenSearchCorrelationProjection(HttpClient client, string url, string user, string password) : ICorrelationProjection
{
    const string Alias = "platform-correlated-findings"; const string Index = "platform-correlated-findings-v1"; readonly JsonSerializerOptions _json = new(JsonSerializerDefaults.Web);
    public async Task EnsureAsync(CancellationToken ct) { using var request = new HttpRequestMessage(HttpMethod.Put, $"{url}/{Index}") { Content = new StringContent("{\"settings\":{\"index.mapping.total_fields.limit\":512},\"mappings\":{\"dynamic\":\"strict\",\"properties\":{\"tenantId\":{\"type\":\"keyword\"},\"correlatedFindingId\":{\"type\":\"keyword\"},\"correlationRuleId\":{\"type\":\"keyword\"},\"correlationRuleVersion\":{\"type\":\"integer\"},\"packId\":{\"type\":\"keyword\"},\"packVersion\":{\"type\":\"integer\"},\"endpointId\":{\"type\":\"keyword\"},\"severity\":{\"type\":\"integer\"},\"confidence\":{\"type\":\"integer\"},\"firstSeen\":{\"type\":\"date\"},\"lastSeen\":{\"type\":\"date\"},\"suppressed\":{\"type\":\"boolean\"},\"executionMode\":{\"type\":\"keyword\"},\"finding\":{\"type\":\"object\",\"enabled\":false}}},\"aliases\":{\"platform-correlated-findings\":{}}}", Encoding.UTF8, "application/json") }; Auth(request); using var response = await client.SendAsync(request, ct); if (!response.IsSuccessStatusCode && response.StatusCode != System.Net.HttpStatusCode.BadRequest) response.EnsureSuccessStatusCode(); }
    public async Task UpsertAsync(CorrelatedFinding f, CancellationToken ct) { var doc = new { f.TenantId, f.CorrelatedFindingId, f.CorrelationRuleId, CorrelationRuleVersion = f.CorrelationRuleVersion, f.PackId, f.PackVersion, f.EndpointId, f.Severity, f.Confidence, f.FirstSeen, f.LastSeen, f.Suppressed, ExecutionMode = f.ExecutionMode.ToString(), finding = f }; using var request = new HttpRequestMessage(HttpMethod.Put, $"{url}/{Alias}/_doc/{f.TenantId}:{f.CorrelatedFindingId:D}") { Content = new StringContent(JsonSerializer.Serialize(doc, _json), Encoding.UTF8, "application/json") }; Auth(request); using var response = await client.SendAsync(request, ct); response.EnsureSuccessStatusCode(); }
    public async Task<long> CountAsync(string tenant, CancellationToken ct) { using var request = new HttpRequestMessage(HttpMethod.Post, $"{url}/{Alias}/_count") { Content = new StringContent(JsonSerializer.Serialize(new { query = new { term = new { tenantId = tenant } } }), Encoding.UTF8, "application/json") }; Auth(request); using var response = await client.SendAsync(request, ct); response.EnsureSuccessStatusCode(); using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct)); return doc.RootElement.GetProperty("count").GetInt64(); }
    public async Task<bool> HealthAsync(CancellationToken ct) { try { using var request = new HttpRequestMessage(HttpMethod.Head, $"{url}/{Alias}"); Auth(request); using var response = await client.SendAsync(request, ct); return response.IsSuccessStatusCode; } catch { return false; } }
    void Auth(HttpRequestMessage request) => request.Headers.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(Encoding.UTF8.GetBytes($"{user}:{password}")));
}
