using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;
namespace OpenSecurityPlatform.Infrastructure;
public sealed class OpenSearchPersistenceProjection : IPersistenceProjection
{
    public const string Alias = "platform-persistence-events"; static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web); readonly HttpClient _client;
    public OpenSearchPersistenceProjection(HttpClient client, string url, string? user, string? password) { client.BaseAddress = new(url); client.Timeout = TimeSpan.FromSeconds(15); if (!string.IsNullOrWhiteSpace(user)) client.DefaultRequestHeaders.Authorization = new("Basic", Convert.ToBase64String(Encoding.UTF8.GetBytes($"{user}:{password}"))); _client = client; }
    public async Task EnsureAsync(CancellationToken ct) { using var found = await _client.GetAsync($"_alias/{Alias}", ct); if (!found.IsSuccessStatusCode) { var index = $"{Alias}-v1"; using (var create = await _client.PutAsJsonAsync(index, Definition(), ct)) create.EnsureSuccessStatusCode(); using var alias = await _client.PostAsJsonAsync("_aliases", new { actions = new[] { new { add = new { index, alias = Alias } } } }, ct); alias.EnsureSuccessStatusCode(); } using var mapping = await _client.PutAsJsonAsync($"{Alias}/_mapping", MappingUpdate(), ct); mapping.EnsureSuccessStatusCode(); }
    public async Task UpsertAsync(string tenant, PersistenceObservation value, CancellationToken ct) { using var response = await _client.PutAsJsonAsync($"{Alias}/_doc/{tenant}-{value.EventId}", Doc(tenant, value), ct); response.EnsureSuccessStatusCode(); }
    public async Task<PersistenceEventPage> SearchAsync(string tenant, PersistenceSearchRequest request, CancellationToken ct) { var filters = new List<object> { new { term = new { tenant_id = tenant } } }; if (request.ObjectKind is { } kind) filters.Add(new { term = new { object_kind = kind.ToString() } }); if (request.EndpointId is { } endpoint) filters.Add(new { term = new { endpoint_id = endpoint } }); if (request.State is { } state) filters.Add(new { term = new { state } }); if (request.Type is { } type) filters.Add(new { term = new { object_type = type } }); if (request.Quality is { } quality) filters.Add(new { term = new { data_quality = quality } }); if (request.Category is { } category) filters.Add(new { term = new { category } }); if (request.Subtype is { } subtype) filters.Add(new { term = new { subtype } }); if (request.Scope is { } scope) filters.Add(new { term = new { scope } }); if (request.ConsumerType is { } consumerType) filters.Add(new { term = new { consumer_type = consumerType } }); if (request.From is not null || request.To is not null) filters.Add(new { range = new { observed_at = new { gte = request.From, lte = request.To } } }); var terms = new[] { request.Name, request.Path, request.Account, request.Process, request.User, request.Namespace }.Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => (object)new { simple_query_string = new { query = Escape(x), fields = new[] { "object_name", "object_path", "account", "process", "user", "namespace" } } }).ToArray(); var body = new Dictionary<string, object?> { { "size", Math.Clamp(request.PageSize, 1, 500) }, { "query", new { @bool = new { filter = filters, must = terms } } }, { "sort", new object[] { new { observed_at = new { order = "desc" } }, new { event_id = new { order = "desc" } } } } }; if (!string.IsNullOrWhiteSpace(request.Cursor)) body["search_after"] = JsonSerializer.Deserialize<object[]>(TenantCursor.Unprotect(tenant, request.Cursor)); using var response = await _client.PostAsJsonAsync($"{Alias}/_search", body, ct); response.EnsureSuccessStatusCode(); using var document = JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct)); var list = new List<PersistenceObservation>(); string? cursor = null; foreach (var hit in document.RootElement.GetProperty("hits").GetProperty("hits").EnumerateArray()) { list.Add(JsonSerializer.Deserialize<PersistenceObservation>(hit.GetProperty("_source").GetProperty("event_data").GetRawText(), Json)!); cursor = TenantCursor.Protect(tenant, hit.GetProperty("sort").GetRawText()); } return new(list, cursor); }
    public async Task<bool> HealthAsync(CancellationToken ct) { try { using var response = await _client.GetAsync("_cluster/health", ct); return response.IsSuccessStatusCode; } catch (HttpRequestException) { return false; } }
    static object Doc(string tenant, PersistenceObservation value) => new { tenant_id = tenant, endpoint_id = value.EndpointId, event_id = value.EventId, object_kind = value.ObjectKind.ToString(), event_type = value.Kind.ToString(), entity_id = value.Service?.EntityId ?? value.ScheduledTask?.EntityId ?? value.Configuration?.EntityId, object_name = value.Service?.Name ?? value.ScheduledTask?.Name ?? value.Configuration?.Name, object_path = value.Service?.BinaryPath ?? value.ScheduledTask?.Path ?? value.Configuration?.RegistryPath ?? value.Configuration?.FilePath, account = value.Service?.Account ?? value.ScheduledTask?.Principal ?? value.Configuration?.Principal, state = value.Service?.State ?? value.ScheduledTask?.ExecutionResult ?? value.Configuration?.CurrentState, object_type = value.Service?.ServiceType ?? value.ScheduledTask?.Triggers.FirstOrDefault()?.Type ?? value.Configuration?.Subtype, process = value.Service?.Process?.ProcessEntityId ?? value.ScheduledTask?.Process?.ProcessEntityId, user = value.AssociatedUser, category = value.Configuration?.Category, subtype = value.Configuration?.Subtype, scope = value.Configuration?.Scope, @namespace = value.Configuration?.NamespaceOrLocation, consumer_type = value.Configuration?.ConsumerMetadata, data_quality = value.DataQualityFlags, observed_at = value.ObservedAt, event_data = value };
    static Dictionary<string, object> Properties() => new() { { "tenant_id", new { type = "keyword" } }, { "endpoint_id", new { type = "keyword" } }, { "event_id", new { type = "keyword" } }, { "object_kind", new { type = "keyword" } }, { "event_type", new { type = "keyword" } }, { "entity_id", new { type = "keyword" } }, { "object_name", new { type = "wildcard" } }, { "object_path", new { type = "wildcard" } }, { "account", new { type = "keyword" } }, { "state", new { type = "keyword" } }, { "object_type", new { type = "keyword" } }, { "process", new { type = "keyword" } }, { "user", new { type = "keyword" } }, { "category", new { type = "keyword" } }, { "subtype", new { type = "keyword" } }, { "scope", new { type = "keyword" } }, { "namespace", new { type = "wildcard" } }, { "consumer_type", new { type = "keyword" } }, { "data_quality", new { type = "keyword" } }, { "observed_at", new { type = "date" } }, { "event_data", new { type = "object", enabled = false } } };
    static object MappingUpdate() => new { properties = Properties() };
    static object Definition() => new { settings = new { index = new { number_of_shards = 1, number_of_replicas = 0 } }, mappings = new { dynamic = "strict", properties = Properties() } };
    static string Escape(string? value) => string.Concat((value ?? "").Take(256).Select(c => char.IsLetterOrDigit(c) || char.IsWhiteSpace(c) || c is '.' or '_' or '-' or '/' or '\\' or ':' ? c : ' '));
}
