using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using OpenSecurityPlatform.Foundation;
namespace OpenSecurityPlatform.Infrastructure;
public sealed class OpenSearchIdentityProjection : IIdentityProjection
{
    public const string Alias = "platform-identity-events"; static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web); readonly HttpClient _client;
    public OpenSearchIdentityProjection(HttpClient client, string url, string? user, string? password) { client.BaseAddress = new(url); client.Timeout = TimeSpan.FromSeconds(15); if (!string.IsNullOrWhiteSpace(user)) client.DefaultRequestHeaders.Authorization = new("Basic", Convert.ToBase64String(Encoding.UTF8.GetBytes($"{user}:{password}"))); _client = client; }
    public async Task EnsureAsync(CancellationToken ct) { using var found = await _client.GetAsync($"_alias/{Alias}", ct); if (!found.IsSuccessStatusCode) { var index = $"{Alias}-v1"; using (var create = await _client.PutAsJsonAsync(index, Definition(), ct)) create.EnsureSuccessStatusCode(); using var alias = await _client.PostAsJsonAsync("_aliases", new { actions = new[] { new { add = new { index, alias = Alias } } } }, ct); alias.EnsureSuccessStatusCode(); } using var mapping = await _client.PutAsJsonAsync($"{Alias}/_mapping", Mapping(), ct); mapping.EnsureSuccessStatusCode(); }
    public async Task UpsertAsync(string tenant, IdentityObservation value, CancellationToken ct) { using var response = await _client.PutAsJsonAsync($"{Alias}/_doc/{tenant}-{value.EventId}", Doc(tenant, value), ct); response.EnsureSuccessStatusCode(); }
    public async Task<IdentityEventPage> SearchAsync(string tenant, IdentitySearchRequest r, CancellationToken ct) { var f = new List<object> { new { term = new { tenant_id = tenant } } }; if (r.EndpointId is { } endpoint) f.Add(new { term = new { endpoint_id = endpoint } }); if (r.Sid is { } sid) f.Add(new { term = new { account_sid = sid } }); if (r.LogonType is { } type) f.Add(new { term = new { logon_type = type } }); if (r.Result is { } result) f.Add(new { term = new { result } }); if (r.SourceIp is { } ip) f.Add(new { term = new { source_ip = ip } }); if (r.RemoteSession is { } remote) f.Add(new { term = new { remote_session = remote } }); if (r.SessionId is { } session) f.Add(new { term = new { session_id = session } }); if (r.IntegrityLevel is { } integrity) f.Add(new { term = new { integrity_level = integrity } }); if (r.ElevatedToken is { } elevated) f.Add(new { term = new { elevated_token = elevated } }); if (r.Privilege is { } privilege) f.Add(new { term = new { privileges = privilege } }); if (r.Process is { } process) f.Add(new { term = new { process_entity_id = process } }); if (r.Kind is { } kind) f.Add(new { term = new { event_type = kind.ToString() } }); if (r.From is not null || r.To is not null) f.Add(new { range = new { observed_at = new { gte = r.From, lte = r.To } } }); var must = new[] { r.Account, r.Domain }.Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => (object)new { simple_query_string = new { query = Escape(x), fields = new[] { "account_name", "domain_name" } } }).ToArray(); var body = new Dictionary<string, object?> { { "size", Math.Clamp(r.PageSize, 1, 500) }, { "query", new { @bool = new { filter = f, must } } }, { "sort", new object[] { new { observed_at = new { order = "desc" } }, new { event_id = new { order = "desc" } } } } }; if (!string.IsNullOrWhiteSpace(r.Cursor)) body["search_after"] = JsonSerializer.Deserialize<object[]>(TenantCursor.Unprotect(tenant, r.Cursor)); using var response = await _client.PostAsJsonAsync($"{Alias}/_search", body, ct); response.EnsureSuccessStatusCode(); using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct)); var list = new List<IdentityObservation>(); string? cursor = null; foreach (var hit in doc.RootElement.GetProperty("hits").GetProperty("hits").EnumerateArray()) { list.Add(JsonSerializer.Deserialize<IdentityObservation>(hit.GetProperty("_source").GetProperty("event_data").GetRawText(), Json)!); cursor = TenantCursor.Protect(tenant, hit.GetProperty("sort").GetRawText()); } return new(list, cursor); }
    public async Task<bool> HealthAsync(CancellationToken ct) { try { using var r = await _client.GetAsync("_cluster/health", ct); return r.IsSuccessStatusCode; } catch (HttpRequestException) { return false; } }
    static object Doc(string tenant, IdentityObservation v) => new { tenant_id = tenant, endpoint_id = v.EndpointId, event_id = v.EventId, event_type = v.Kind.ToString(), entity_id = v.Logon?.EntityId ?? v.Session?.EntityId ?? v.Token?.EntityId ?? v.Process?.ProcessEntityId, account_sid = v.Account?.Sid, account_name = v.Account?.Name, domain_name = v.Account?.Domain, logon_id = v.Logon?.LogonId, logon_type = v.Logon?.NativeLogonType, result = v.Logon?.Result, source_ip = v.Logon?.SourceIp, remote_session = v.Session?.Remote, session_id = v.Session?.SessionId ?? v.Token?.SessionId, integrity_level = v.Token?.IntegrityLevel, elevated_token = v.Token?.Elevated, process_entity_id = v.Process?.ProcessEntityId, privileges = v.Privileges.Select(x => x.Name).ToArray(), data_quality = v.DataQualityFlags, observed_at = v.ObservedAt, event_data = v };
    static Dictionary<string, object> Properties() => new() { { "tenant_id", new { type = "keyword" } }, { "endpoint_id", new { type = "keyword" } }, { "event_id", new { type = "keyword" } }, { "event_type", new { type = "keyword" } }, { "entity_id", new { type = "keyword" } }, { "account_sid", new { type = "keyword" } }, { "account_name", new { type = "wildcard" } }, { "domain_name", new { type = "wildcard" } }, { "logon_id", new { type = "keyword" } }, { "logon_type", new { type = "integer" } }, { "result", new { type = "keyword" } }, { "source_ip", new { type = "ip", ignore_malformed = false } }, { "remote_session", new { type = "boolean" } }, { "session_id", new { type = "integer" } }, { "integrity_level", new { type = "keyword" } }, { "elevated_token", new { type = "boolean" } }, { "process_entity_id", new { type = "keyword" } }, { "privileges", new { type = "keyword" } }, { "data_quality", new { type = "keyword" } }, { "observed_at", new { type = "date" } }, { "event_data", new { type = "object", enabled = false } } };
    static object Mapping() => new { properties = Properties() }; static object Definition() => new { settings = new { index = new { number_of_shards = 1, number_of_replicas = 0 } }, mappings = new { dynamic = "strict", properties = Properties() } };
    static string Escape(string? value) => string.Concat((value ?? "").Take(256).Select(c => char.IsLetterOrDigit(c) || char.IsWhiteSpace(c) || c is '.' or '_' or '-' or '/' or '\\' or ':' ? c : ' '));
}
