using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresDnsPolicyRepository(string connectionString) : IDnsPolicyRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly NpgsqlDataSource _data = NpgsqlDataSource.Create(connectionString);
    public async Task<IReadOnlyList<DnsPolicyVersion>> ListAsync(string tenant, CancellationToken ct)
    { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT id,tenant_id::text,name,version,policy,sha256,status,created_at,created_by FROM platform.dns_policy_versions WHERE tenant_id=$1 ORDER BY name,version DESC", c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); var list = new List<DnsPolicyVersion>(); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(new(r.GetGuid(0), r.GetString(1), r.GetString(2), r.GetInt32(3), JsonSerializer.Deserialize<DnsTelemetryPolicy>(r.GetString(4), Json)!, r.GetString(5), r.GetString(6), r.GetFieldValue<DateTimeOffset>(7), r.GetString(8))); return list; }
    public async Task<DnsPolicyVersion> CreateAsync(string tenant, string actor, string name, DnsTelemetryPolicy p, CancellationToken ct)
    { var errors = DnsPolicyValidation.Validate(p); if (errors.Count > 0) throw new EnrollmentConflictException("DNS_POLICY_INVALID", string.Join(' ', errors.SelectMany(x => x.Value))); var id = Guid.NewGuid(); var hash = DnsEvidence.CanonicalSha256(p); await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("INSERT INTO platform.dns_policy_versions(id,tenant_id,name,version,policy,sha256,status,created_by) SELECT $1,$2,$3,COALESCE(max(version),0)+1,$4,$5,'active',$6 FROM platform.dns_policy_versions WHERE tenant_id=$2 AND name=$3 RETURNING version,created_at", c); cmd.Parameters.AddWithValue(id); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); cmd.Parameters.AddWithValue(name); cmd.Parameters.Add(new NpgsqlParameter { Value = JsonSerializer.Serialize(p, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); cmd.Parameters.AddWithValue(hash); cmd.Parameters.AddWithValue(actor); await using var r = await cmd.ExecuteReaderAsync(ct); await r.ReadAsync(ct); return new(id, tenant, name, r.GetInt32(0), p, hash, "active", r.GetFieldValue<DateTimeOffset>(1), actor); }
    public async Task AssignAsync(string tenant, Guid id, Guid? endpoint, string actor, CancellationToken ct)
    { await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); await using (var check = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.dns_policy_versions WHERE tenant_id=$1 AND id=$2)", c, tx)) { check.Parameters.AddWithValue(Guid.Parse(tenant)); check.Parameters.AddWithValue(id); if ((bool)(await check.ExecuteScalarAsync(ct) ?? false) == false) throw new EnrollmentConflictException("DNS_POLICY_NOT_FOUND", "DNS policy was not found in this tenant."); } await using var cmd = new NpgsqlCommand("INSERT INTO platform.dns_policy_assignments(tenant_id,endpoint_id,policy_id,assigned_by) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,assigned_at=now(),assigned_by=EXCLUDED.assigned_by", c, tx); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); cmd.Parameters.AddWithValue(endpoint ?? (object)DBNull.Value); cmd.Parameters.AddWithValue(id); cmd.Parameters.AddWithValue(actor); await cmd.ExecuteNonQueryAsync(ct); await tx.CommitAsync(ct); }
    public async Task<EffectiveDnsPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct)
    { await using var c = await _data.OpenConnectionAsync(ct); const string sql = "SELECT p.id,p.name,p.version,p.policy,p.sha256,p.status,p.created_at,p.created_by,a.endpoint_id IS NOT NULL,k.applied,k.version,k.validation_error,k.acknowledged_at FROM platform.dns_policy_assignments a JOIN platform.dns_policy_versions p ON p.id=a.policy_id AND p.tenant_id=a.tenant_id LEFT JOIN platform.dns_policy_acknowledgements k ON k.tenant_id=a.tenant_id AND k.endpoint_id=$2 WHERE a.tenant_id=$1 AND (a.endpoint_id=$2 OR a.endpoint_id IS NULL) ORDER BY a.endpoint_id NULLS LAST LIMIT 1"; await using var cmd = new NpgsqlCommand(sql, c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); cmd.Parameters.AddWithValue(endpoint); await using var r = await cmd.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) { var p = new DnsTelemetryPolicy(); var v = new DnsPolicyVersion(Guid.Empty, tenant, "safe-default", 1, p, DnsEvidence.CanonicalSha256(p), "default", DateTimeOffset.UnixEpoch, "system"); return new(v, "default", endpoint, null, null, null, null, true); } var policy = new DnsPolicyVersion(r.GetGuid(0), tenant, r.GetString(1), r.GetInt32(2), JsonSerializer.Deserialize<DnsTelemetryPolicy>(r.GetString(3), Json)!, r.GetString(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetString(7)); var has = !r.IsDBNull(9); var applied = has && r.GetBoolean(9); var version = has ? r.GetInt32(10) : (int?)null; return new(policy, r.GetBoolean(8) ? "endpoint" : "tenant", endpoint, has ? r.GetFieldValue<DateTimeOffset>(12) : null, applied ? version : null, has && !applied ? version : null, has && !r.IsDBNull(11) ? r.GetString(11) : null, !has || !applied || version != policy.Version); }
    public async Task AcknowledgeAsync(string tenant, Guid endpoint, DnsPolicyAcknowledgement a, CancellationToken ct)
    { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("INSERT INTO platform.dns_policy_acknowledgements(tenant_id,endpoint_id,policy_id,version,applied,validation_error,acknowledged_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,version=EXCLUDED.version,applied=EXCLUDED.applied,validation_error=EXCLUDED.validation_error,acknowledged_at=EXCLUDED.acknowledged_at", c); object?[] v = [Guid.Parse(tenant), endpoint, a.PolicyId, a.Version, a.Applied, a.ValidationError, a.AcknowledgedAt]; foreach (var x in v) cmd.Parameters.AddWithValue(x ?? DBNull.Value); await cmd.ExecuteNonQueryAsync(ct); }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
