using System.Text.Json;
using Npgsql;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresAiEngineeringRepository : IAiEngineeringRepository, IAsyncDisposable
{
    readonly NpgsqlDataSource data;
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public PostgresAiEngineeringRepository(string connectionString) => data = NpgsqlDataSource.Create(connectionString);

    public async Task<AiHuntProposal> SaveHuntAsync(AiHuntProposal value, CancellationToken ct)
    {
        await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.ai_hunt_proposals(tenant_id,proposal_id,proposal_hash,state,proposal_data,created_at,updated_at) VALUES($1,$2,$3,$4,$5::jsonb,$6,now()) ON CONFLICT(tenant_id,proposal_id) DO UPDATE SET proposal_hash=EXCLUDED.proposal_hash,state=EXCLUDED.state,proposal_data=EXCLUDED.proposal_data,updated_at=now()", c); q.Parameters.AddWithValue(Guid.Parse(value.TenantId)); q.Parameters.AddWithValue(value.ProposalId); q.Parameters.AddWithValue(value.ProposalHash); q.Parameters.AddWithValue(value.State.ToString()); q.Parameters.AddWithValue(JsonSerializer.Serialize(value, Json)); q.Parameters.AddWithValue(value.CreatedAt); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public Task<AiHuntProposal?> HuntAsync(string tenant, Guid id, CancellationToken ct) => One<AiHuntProposal>("SELECT proposal_data::text FROM platform.ai_hunt_proposals WHERE tenant_id=$1 AND proposal_id=$2", tenant, id, ct);
    public async Task<IReadOnlyList<AiHuntProposal>> HuntsAsync(string tenant, int limit, CancellationToken ct) => await Many<AiHuntProposal>("SELECT proposal_data::text FROM platform.ai_hunt_proposals WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", tenant, Math.Clamp(limit, 1, 200), ct);
    public async Task<AiHuntProposal> UpdateHuntAsync(string tenant, Guid id, Func<AiHuntProposal, AiHuntProposal> update, CancellationToken ct) => await SaveHuntAsync(update(await HuntAsync(tenant, id, ct) ?? throw new KeyNotFoundException()), ct);

    public async Task<AiRuleDraft> SaveDraftAsync(AiRuleDraft value, CancellationToken ct)
    {
        await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.ai_rule_drafts(tenant_id,draft_id,draft_hash,draft_kind,state,draft_data,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,now()) ON CONFLICT(tenant_id,draft_id) DO UPDATE SET draft_hash=EXCLUDED.draft_hash,state=EXCLUDED.state,draft_data=EXCLUDED.draft_data,updated_at=now()", c); q.Parameters.AddWithValue(Guid.Parse(value.TenantId)); q.Parameters.AddWithValue(value.DraftId); q.Parameters.AddWithValue(value.DraftHash); q.Parameters.AddWithValue(value.Kind.ToString()); q.Parameters.AddWithValue(value.State.ToString()); q.Parameters.AddWithValue(JsonSerializer.Serialize(value, Json)); q.Parameters.AddWithValue(value.CreatedAt); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public Task<AiRuleDraft?> DraftAsync(string tenant, Guid id, CancellationToken ct) => One<AiRuleDraft>("SELECT draft_data::text FROM platform.ai_rule_drafts WHERE tenant_id=$1 AND draft_id=$2", tenant, id, ct);
    public async Task<IReadOnlyList<AiRuleDraft>> DraftsAsync(string tenant, int limit, CancellationToken ct) => await Many<AiRuleDraft>("SELECT draft_data::text FROM platform.ai_rule_drafts WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", tenant, Math.Clamp(limit, 1, 200), ct);
    public async Task<AiRuleDraft> UpdateDraftAsync(string tenant, Guid id, Func<AiRuleDraft, AiRuleDraft> update, CancellationToken ct) => await SaveDraftAsync(update(await DraftAsync(tenant, id, ct) ?? throw new KeyNotFoundException()), ct);
    public async Task SaveSimulationAsync(AiHistoricalSimulation value, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.ai_rule_simulations(tenant_id,simulation_id,draft_id,simulation_data,completed_at) VALUES($1,$2,$3,$4::jsonb,$5)", c); q.Parameters.AddWithValue(Guid.Parse(value.TenantId)); q.Parameters.AddWithValue(value.SimulationId); q.Parameters.AddWithValue(value.DraftId); q.Parameters.AddWithValue(JsonSerializer.Serialize(value, Json)); q.Parameters.AddWithValue(value.CompletedAt); await q.ExecuteNonQueryAsync(ct); }
    public Task<AiHistoricalSimulation?> SimulationAsync(string tenant, Guid id, CancellationToken ct) => One<AiHistoricalSimulation>("SELECT simulation_data::text FROM platform.ai_rule_simulations WHERE tenant_id=$1 AND simulation_id=$2", tenant, id, ct);
    public async Task SaveComparisonAsync(AiRuleComparison value, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.ai_rule_comparisons(tenant_id,comparison_id,draft_id,comparison_data,completed_at) VALUES($1,$2,$3,$4::jsonb,$5)", c); q.Parameters.AddWithValue(Guid.Parse(value.TenantId)); q.Parameters.AddWithValue(value.ComparisonId); q.Parameters.AddWithValue(value.DraftId); q.Parameters.AddWithValue(JsonSerializer.Serialize(value, Json)); q.Parameters.AddWithValue(value.CompletedAt); await q.ExecuteNonQueryAsync(ct); }
    public async Task RecordAuditAsync(AiEngineeringAudit value, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.ai_engineering_audit(tenant_id,audit_id,actor,action,object_type,object_id,object_hash,occurred_at,detail) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)", c); q.Parameters.AddWithValue(Guid.Parse(value.TenantId)); q.Parameters.AddWithValue(value.AuditId); q.Parameters.AddWithValue(value.Actor); q.Parameters.AddWithValue(value.Action); q.Parameters.AddWithValue(value.ObjectType); q.Parameters.AddWithValue(value.ObjectId); q.Parameters.AddWithValue(value.ObjectHash); q.Parameters.AddWithValue(value.OccurredAt); q.Parameters.AddWithValue(JsonSerializer.Serialize(value.Detail, Json)); await q.ExecuteNonQueryAsync(ct); }
    public async Task<IReadOnlyList<AiEngineeringAudit>> AuditAsync(string tenant, int limit, CancellationToken ct) => await Many<AiEngineeringAudit>("SELECT jsonb_build_object('auditId',audit_id,'tenantId',tenant_id,'actor',actor,'action',action,'objectType',object_type,'objectId',object_id,'objectHash',object_hash,'occurredAt',occurred_at,'detail',detail)::text FROM platform.ai_engineering_audit WHERE tenant_id=$1 ORDER BY occurred_at DESC LIMIT $2", tenant, Math.Clamp(limit, 1, 500), ct);

    async Task<T?> One<T>(string sql, string tenant, Guid id, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); return await q.ExecuteScalarAsync(ct) is string json ? JsonSerializer.Deserialize<T>(json, Json) : default; }
    async Task<IReadOnlyList<T>> Many<T>(string sql, string tenant, int limit, CancellationToken ct) { var list = new List<T>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(limit); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) if (JsonSerializer.Deserialize<T>(reader.GetString(0), Json) is { } value) list.Add(value); return list; }
    public async ValueTask DisposeAsync() => await data.DisposeAsync();
}
