using System.Text.Json;
using Npgsql;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresAdministrationStateStore : IAdministrationStateStore, IAsyncDisposable
{
    readonly NpgsqlDataSource data; static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public PostgresAdministrationStateStore(string connection) => data = NpgsqlDataSource.Create(connection);
    public async Task<AdministrationState> LoadAsync(string tenant, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT revision,state_data::text FROM platform.administration_states WHERE tenant_id=$1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? JsonSerializer.Deserialize<AdministrationState>(r.GetString(1), Json)! with { Revision = r.GetInt64(0) } : new(0, [], [], [], [], [], [], []); }
    public async Task SaveAsync(string tenant, long expected, AdministrationState state, IReadOnlyList<AdministrativeAuditEvent> audit, CancellationToken ct)
    {
        await using var c = await data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); var next = state with { Revision = expected + 1 }; int changed;
        if (expected == 0) { await using var q = new NpgsqlCommand("INSERT INTO platform.administration_states(tenant_id,revision,state_data,updated_at) VALUES($1,1,$2::jsonb,now()) ON CONFLICT DO NOTHING", c, tx); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(JsonSerializer.Serialize(next, Json)); changed = await q.ExecuteNonQueryAsync(ct); }
        else { await using var q = new NpgsqlCommand("UPDATE platform.administration_states SET revision=$3,state_data=$4::jsonb,updated_at=now() WHERE tenant_id=$1 AND revision=$2", c, tx); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(expected); q.Parameters.AddWithValue(expected + 1); q.Parameters.AddWithValue(JsonSerializer.Serialize(next, Json)); changed = await q.ExecuteNonQueryAsync(ct); }
        if (changed != 1) throw new EnrollmentConflictException("ADMINISTRATION_STALE_VERSION", "Administrative state changed; reload and retry.");
        foreach (var a in audit) { await using var q = new NpgsqlCommand("INSERT INTO platform.administration_audit(tenant_id,audit_id,occurred_at,actor,action,resource_type,resource_id,before_hash,after_hash,reason,request_id,approval_id,result,event_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb)", c, tx); object?[] values = [Guid.Parse(a.TenantId), a.AuditId, a.OccurredAt, a.Actor, a.Action, a.ResourceType, a.ResourceId, a.BeforeHash, a.AfterHash, a.Reason, a.RequestId, a.ApprovalId, a.Result, JsonSerializer.Serialize(a, Json)]; foreach (var value in values) q.Parameters.AddWithValue(value ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
        await tx.CommitAsync(ct);
    }
    public async Task<StoredApiCredential?> CredentialAsync(Guid id, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT metadata::text,secret_hash FROM platform.administration_api_credentials WHERE credential_id=$1", c); q.Parameters.AddWithValue(id); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(JsonSerializer.Deserialize<ApiCredentialMetadata>(r.GetString(0), Json)!, r.GetString(1)) : null; }
    public async Task PutCredentialAsync(StoredApiCredential credential, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.administration_api_credentials(tenant_id,credential_id,principal_id,version,prefix,secret_hash,expires_at,revoked_at,last_used_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) ON CONFLICT(credential_id) DO UPDATE SET version=EXCLUDED.version,secret_hash=EXCLUDED.secret_hash,expires_at=EXCLUDED.expires_at,revoked_at=EXCLUDED.revoked_at,last_used_at=EXCLUDED.last_used_at,metadata=EXCLUDED.metadata", c); var m = credential.Metadata; object?[] values = [Guid.Parse(m.TenantId), m.CredentialId, m.PrincipalId, m.Version, m.Prefix, credential.SecretHash, m.ExpiresAt, m.RevokedAt, m.LastUsedAt, JsonSerializer.Serialize(m, Json)]; foreach (var value in values) q.Parameters.AddWithValue(value ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
    public async Task TouchCredentialAsync(Guid id, DateTimeOffset at, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.administration_api_credentials SET last_used_at=$2,metadata=jsonb_set(metadata,'{lastUsedAt}',to_jsonb($2::timestamptz),true) WHERE credential_id=$1 AND revoked_at IS NULL AND expires_at>now()", c); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(at); await q.ExecuteNonQueryAsync(ct); }
    public async Task<IReadOnlyList<AdministrativeAuditEvent>> AuditAsync(string tenant, AdministrativeAuditQuery x, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data::text FROM platform.administration_audit WHERE tenant_id=$1 AND($2::timestamptz IS NULL OR occurred_at>=$2) AND($3::timestamptz IS NULL OR occurred_at<=$3) AND($4::text IS NULL OR actor=$4) AND($5::text IS NULL OR action ILIKE '%'||$5||'%') AND($6::text IS NULL OR resource_id ILIKE '%'||$6||'%') AND($7::text IS NULL OR resource_type=$7) AND($8::text IS NULL OR result=$8) AND($9::uuid IS NULL OR approval_id=$9) ORDER BY occurred_at DESC,audit_id DESC LIMIT $10", c); object?[] values = [Guid.Parse(tenant), x.From, x.To, x.Principal, x.Action, x.Resource, x.Subsystem, x.Result, x.ApprovalId, Math.Clamp(x.Limit, 1, 1000)]; foreach (var value in values) q.Parameters.AddWithValue(value ?? DBNull.Value); var list = new List<AdministrativeAuditEvent>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<AdministrativeAuditEvent>(r.GetString(0), Json)!); return list; }
    public async Task<long> AuditCountAsync(string tenant, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT count(*) FROM platform.administration_audit WHERE tenant_id=$1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); return (long)(await q.ExecuteScalarAsync(ct))!; }
    public ValueTask DisposeAsync() => data.DisposeAsync();
}
