using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;
namespace OpenSecurityPlatform.Infrastructure;
public sealed class PostgresModulePolicyRepository(string cs) : IModulePolicyRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web); readonly NpgsqlDataSource _d = NpgsqlDataSource.Create(cs);
    public async Task<IReadOnlyList<ModulePolicyVersion>> ListAsync(string t, CancellationToken ct) { await using var c = await _d.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT id,name,version,policy,sha256,status,created_at,created_by FROM platform.module_policy_versions WHERE tenant_id=$1 ORDER BY name,version DESC", c); q.Parameters.AddWithValue(Guid.Parse(t)); var l = new List<ModulePolicyVersion>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) l.Add(new(r.GetGuid(0), t, r.GetString(1), r.GetInt32(2), JsonSerializer.Deserialize<ModuleTelemetryPolicy>(r.GetString(3), Json)!, r.GetString(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetString(7))); return l; }
    public async Task<ModulePolicyVersion> CreateAsync(string t, string actor, string name, ModuleTelemetryPolicy p, CancellationToken ct) { var e = ModulePolicyValidation.Validate(p); if (e.Count > 0) throw new EnrollmentConflictException("MODULE_POLICY_INVALID", string.Join(' ', e.SelectMany(x => x.Value))); var all = await ListAsync(t, ct); var v = new ModulePolicyVersion(Guid.NewGuid(), t, name, all.Where(x => x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1, p, ModuleEvidence.Sha256(p), "active", DateTimeOffset.UtcNow, actor); await using var c = await _d.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.module_policy_versions VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", c); object[] x = [v.Id, Guid.Parse(t), name, v.Version, JsonSerializer.Serialize(p, Json), v.Sha256, v.Status, v.CreatedAt, actor]; for (int i = 0; i < x.Length; i++) if (i == 4) q.Parameters.Add(new() { Value = x[i], NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(x[i]); await q.ExecuteNonQueryAsync(ct); return v; }
    public async Task AssignAsync(string t, Guid id, Guid? e, string actor, CancellationToken ct) { await using var c = await _d.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.module_policy_assignments VALUES($1,$2,$3,now(),$4) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,assigned_at=now(),assigned_by=EXCLUDED.assigned_by", c); q.Parameters.AddWithValue(Guid.Parse(t)); q.Parameters.AddWithValue(e ?? (object)DBNull.Value); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(actor); try { await q.ExecuteNonQueryAsync(ct); } catch (PostgresException) { throw new EnrollmentConflictException("MODULE_POLICY_ASSIGNMENT_INVALID", "Policy assignment is invalid for this tenant."); } }
    public async Task<EffectiveModulePolicy> EffectiveAsync(string t, Guid e, CancellationToken ct) { var all = await ListAsync(t, ct); await using var c = await _d.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT policy_id FROM platform.module_policy_assignments WHERE tenant_id=$1 AND (endpoint_id=$2 OR endpoint_id IS NULL) ORDER BY endpoint_id NULLS LAST LIMIT 1", c); q.Parameters.AddWithValue(Guid.Parse(t)); q.Parameters.AddWithValue(e); var id = await q.ExecuteScalarAsync(ct); var v = id is Guid g ? all.First(x => x.Id == g) : new ModulePolicyVersion(Guid.Empty, t, "safe-default", 0, new(), ModuleEvidence.Sha256(new ModuleTelemetryPolicy()), "default", DateTimeOffset.UnixEpoch, "system"); return new(v, id is null ? "default" : "assigned", e, null, null, null, null, true); }
    public async Task AcknowledgeAsync(string t, Guid e, ModulePolicyAcknowledgement a, CancellationToken ct) { await using var c = await _d.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.module_policy_acknowledgements VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,version=EXCLUDED.version,applied=EXCLUDED.applied,validation_error=EXCLUDED.validation_error,acknowledged_at=EXCLUDED.acknowledged_at", c); object?[] v = [Guid.Parse(t), e, a.PolicyId, a.Version, a.Applied, a.ValidationError, a.AcknowledgedAt]; foreach (var x in v) q.Parameters.AddWithValue(x ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
    public ValueTask DisposeAsync() => _d.DisposeAsync();
}
