using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;
namespace OpenSecurityPlatform.Infrastructure;
public sealed class PostgresIdentityPolicyRepository(string connectionString) : IIdentityPolicyRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web); readonly NpgsqlDataSource _data = NpgsqlDataSource.Create(new NpgsqlConnectionStringBuilder(connectionString) { Pooling = true, MaxPoolSize = 3, Timeout = 5, CommandTimeout = 20 }.ConnectionString);
    public async Task<IReadOnlyList<IdentityPolicyVersion>> ListAsync(string tenant, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT id,name,version,policy,sha256,status,created_at,created_by FROM platform.identity_policy_versions WHERE tenant_id=$1 ORDER BY name,version DESC", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); var list = new List<IdentityPolicyVersion>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(new(r.GetGuid(0), tenant, r.GetString(1), r.GetInt32(2), JsonSerializer.Deserialize<IdentityTelemetryPolicy>(r.GetString(3), Json)!, r.GetString(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetString(7))); return list; }
    public async Task<IdentityPolicyVersion> CreateAsync(string tenant, string actor, string name, IdentityTelemetryPolicy policy, CancellationToken ct) { var errors = IdentitySafety.Validate(policy); if (errors.Count > 0) throw new EnrollmentConflictException("IDENTITY_POLICY_INVALID", string.Join(' ', errors.SelectMany(x => x.Value))); var all = await ListAsync(tenant, ct); var value = new IdentityPolicyVersion(Guid.NewGuid(), tenant, name, all.Where(x => x.Name == name).Select(x => x.Version).DefaultIfEmpty().Max() + 1, policy, IdentitySafety.EvidenceHash(policy), "active", DateTimeOffset.UtcNow, actor); await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.identity_policy_versions VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", c); object[] values = [value.Id, Guid.Parse(tenant), name, value.Version, JsonSerializer.Serialize(policy, Json), value.Sha256, value.Status, value.CreatedAt, actor]; for (var i = 0; i < values.Length; i++) if (i == 4) q.Parameters.Add(new() { Value = values[i], NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(values[i]); await q.ExecuteNonQueryAsync(ct); return value; }
    public async Task AssignAsync(string tenant, Guid policyId, Guid? endpoint, string actor, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.identity_policy_assignments VALUES($1,$2,$3,now(),$4) ON CONFLICT(tenant_id,COALESCE(endpoint_id,'00000000-0000-0000-0000-000000000000'::uuid)) DO UPDATE SET policy_id=EXCLUDED.policy_id,assigned_at=now(),assigned_by=EXCLUDED.assigned_by", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint ?? (object)DBNull.Value); q.Parameters.AddWithValue(policyId); q.Parameters.AddWithValue(actor); try { await q.ExecuteNonQueryAsync(ct); } catch (PostgresException) { throw new EnrollmentConflictException("IDENTITY_POLICY_ASSIGNMENT_INVALID", "Identity policy assignment is invalid for this tenant."); } }
    public async Task<EffectiveIdentityPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct) { var all = await ListAsync(tenant, ct); await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT policy_id FROM platform.identity_policy_assignments WHERE tenant_id=$1 AND(endpoint_id=$2 OR endpoint_id IS NULL) ORDER BY endpoint_id NULLS LAST LIMIT 1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint); var id = await q.ExecuteScalarAsync(ct); var value = id is Guid g ? all.First(x => x.Id == g) : new IdentityPolicyVersion(Guid.Empty, tenant, "safe-default", 0, new(), IdentitySafety.EvidenceHash(new IdentityTelemetryPolicy()), "default", DateTimeOffset.UnixEpoch, "system"); await using var ack = new NpgsqlCommand("SELECT version,applied,validation_error,acknowledged_at FROM platform.identity_policy_acknowledgements WHERE tenant_id=$1 AND endpoint_id=$2", c); ack.Parameters.AddWithValue(Guid.Parse(tenant)); ack.Parameters.AddWithValue(endpoint); await using var reader = await ack.ExecuteReaderAsync(ct); if (!await reader.ReadAsync(ct)) return new(value, id is null ? "default" : "assigned", endpoint, null, null, null, null, true); var version = reader.GetInt32(0); var applied = reader.GetBoolean(1); return new(value, id is null ? "default" : "assigned", endpoint, reader.GetFieldValue<DateTimeOffset>(3), applied ? version : null, applied ? null : version, reader.IsDBNull(2) ? null : reader.GetString(2), !applied || version != value.Version); }
    public async Task AcknowledgeAsync(string tenant, Guid endpoint, IdentityPolicyAcknowledgement a, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.identity_policy_acknowledgements VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,version=EXCLUDED.version,applied=EXCLUDED.applied,validation_error=EXCLUDED.validation_error,acknowledged_at=EXCLUDED.acknowledged_at", c); object?[] values = [Guid.Parse(tenant), endpoint, a.PolicyId, a.Version, a.Applied, a.ValidationError, a.AcknowledgedAt]; foreach (var v in values) q.Parameters.AddWithValue(v ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
