using System.Data;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresIdentityTelemetryRepository(string connectionString) : IIdentityTelemetryRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly NpgsqlDataSource _data = NpgsqlDataSource.Create(new NpgsqlConnectionStringBuilder(connectionString) { Pooling = true, MaxPoolSize = 5, Timeout = 5, CommandTimeout = 20 }.ConnectionString);
    public async Task<IdentityIngestResult> IngestAsync(string tenantText, IdentityEventBatch batch, IdentityTelemetryHealth health, CancellationToken ct)
    {
        var tenant = Guid.Parse(tenantText); await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct);
        await using (var identity = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.agents a JOIN platform.endpoints e ON e.tenant_id=a.tenant_id AND e.id=a.endpoint_id WHERE a.tenant_id=$1 AND a.id=$2 AND a.endpoint_id=$3 AND a.instance_id=$4 AND a.status='active' AND e.status NOT IN('disabled','revoked'))", c, tx)) { identity.Parameters.AddWithValue(tenant); identity.Parameters.AddWithValue(batch.AgentId); identity.Parameters.AddWithValue(batch.EndpointId); identity.Parameters.AddWithValue(batch.InstallationId); if (!(bool)(await identity.ExecuteScalarAsync(ct) ?? false)) throw new EnrollmentConflictException("IDENTITY_IDENTITY_INVALID", "Identity telemetry enrollment identity is invalid."); }
        await using (var command = new NpgsqlCommand("INSERT INTO platform.identity_batches VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now()) ON CONFLICT DO NOTHING", c, tx)) { object[] values = [tenant, batch.BatchId, batch.EndpointId, batch.AgentId, batch.InstallationId, batch.FirstSequence, batch.LastSequence, batch.Events.Count, batch.ContentSha256]; foreach (var value in values) command.Parameters.AddWithValue(value); await command.ExecuteNonQueryAsync(ct); }
        var accepted = new List<Guid>(); var duplicates = new List<Guid>(); var rejected = new Dictionary<Guid, string>(); long acknowledged = 0;
        foreach (var source in batch.Events.OrderBy(x => x.Sequence))
        {
            var value = source with { ReceivedAt = DateTimeOffset.UtcNow, IngestedAt = DateTimeOffset.UtcNow, Late = source.ObservedAt < DateTimeOffset.UtcNow.AddMinutes(-5) };
            var entity = value.Logon?.EntityId ?? value.Session?.EntityId ?? value.Token?.EntityId ?? value.Process?.ProcessEntityId;
            if (!IdentitySafety.ValidObservation(value, batch.EndpointId, batch.AgentId, batch.InstallationId)) { rejected[value.EventId] = "invalid-event"; continue; }
            var json = JsonSerializer.Serialize(value, Json); int inserted;
            await using (var q = new NpgsqlCommand("INSERT INTO platform.identity_events(tenant_id,event_id,batch_id,endpoint_id,agent_id,event_type,entity_id,account_sid,account_name,domain_name,logon_id,logon_type,result,source_ip,remote_session,session_id,integrity_level,elevated_token,process_entity_id,privilege_names,sequence,observed_at,data_quality_flags,event_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::inet,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24) ON CONFLICT DO NOTHING", c, tx))
            { object?[] values = [tenant, value.EventId, batch.BatchId, value.EndpointId, value.AgentId, value.Kind.ToString(), entity, value.Account?.Sid, value.Account?.Name, value.Account?.Domain, value.Logon?.LogonId, value.Logon?.NativeLogonType, value.Logon?.Result, value.Logon?.SourceIp, value.Session?.Remote, value.Session?.SessionId ?? value.Token?.SessionId, value.Token?.IntegrityLevel, value.Token?.Elevated, value.Process?.ProcessEntityId, value.Privileges.Select(x => x.Name).ToArray(), value.Sequence, value.ObservedAt, value.DataQualityFlags, json]; for (var i = 0; i < values.Length; i++) if (i == 23) q.Parameters.Add(new() { Value = values[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(values[i] ?? DBNull.Value); inserted = await q.ExecuteNonQueryAsync(ct); }
            if (inserted == 0) { await using var check = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.identity_events WHERE tenant_id=$1 AND event_id=$2)", c, tx); check.Parameters.AddWithValue(tenant); check.Parameters.AddWithValue(value.EventId); if ((bool)(await check.ExecuteScalarAsync(ct) ?? false)) duplicates.Add(value.EventId); else rejected[value.EventId] = "sequence-collision"; continue; }
            accepted.Add(value.EventId); acknowledged = Math.Max(acknowledged, value.Sequence); await UpsertEntities(c, tx, tenant, value, json, ct);
            await using var outbox = new NpgsqlCommand("INSERT INTO platform.outbox(id,tenant_id,topic,subject,message,trace_id) VALUES($1,$2,'identity.changed','identity.telemetry.v1',$3,'')", c, tx); outbox.Parameters.AddWithValue(Guid.NewGuid()); outbox.Parameters.AddWithValue(tenant); outbox.Parameters.Add(new() { Value = JsonSerializer.Serialize(new { tenantId = tenantText, eventId = value.EventId, endpointId = value.EndpointId }, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await outbox.ExecuteNonQueryAsync(ct);
        }
        var updated = health with { QueueDepth = Math.Max(0, health.QueueDepth - accepted.Count - duplicates.Count), LastAcceptedEvent = accepted.Count > 0 ? batch.Events.Where(x => accepted.Contains(x.EventId)).Max(x => x.ObservedAt) : health.LastAcceptedEvent, LastSequence = Math.Max(acknowledged, health.LastSequence) };
        await using (var q = new NpgsqlCommand("INSERT INTO platform.identity_telemetry_health VALUES($1,$2,$3,now()) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET health_data=EXCLUDED.health_data,updated_at=now()", c, tx)) { q.Parameters.AddWithValue(tenant); q.Parameters.AddWithValue(batch.EndpointId); q.Parameters.Add(new() { Value = JsonSerializer.Serialize(updated, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await q.ExecuteNonQueryAsync(ct); }
        await tx.CommitAsync(ct); return new(new(batch.BatchId, accepted, duplicates, rejected, acknowledged, false), accepted.Count, duplicates.Count, rejected.Count, 0);
    }
    static async Task UpsertEntities(NpgsqlConnection c, NpgsqlTransaction tx, Guid tenant, IdentityObservation value, string json, CancellationToken ct)
    {
        if (value.Logon is { } logon) { await using var q = new NpgsqlCommand("INSERT INTO platform.logon_session_entities VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(tenant_id,endpoint_id,logon_entity_id) DO UPDATE SET last_observed=GREATEST(platform.logon_session_entities.last_observed,EXCLUDED.last_observed),ended_at=COALESCE(EXCLUDED.ended_at,platform.logon_session_entities.ended_at),incomplete=EXCLUDED.incomplete,latest_event=CASE WHEN EXCLUDED.last_observed>=platform.logon_session_entities.last_observed THEN EXCLUDED.latest_event ELSE platform.logon_session_entities.latest_event END", c, tx); object?[] v = [tenant, value.EndpointId, logon.EntityId, logon.LogonId, value.Account?.Sid, logon.FirstObserved, logon.LastObserved, logon.StartedAt, logon.EndedAt, logon.IncompleteLifecycle, json]; for (var i = 0; i < v.Length; i++) if (i == 10) q.Parameters.Add(new() { Value = v[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(v[i] ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
        if (value.Session is { } session) { await using var q = new NpgsqlCommand("INSERT INTO platform.windows_session_entities VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(tenant_id,endpoint_id,session_entity_id) DO UPDATE SET last_observed=GREATEST(platform.windows_session_entities.last_observed,EXCLUDED.last_observed),ended_at=COALESCE(EXCLUDED.ended_at,platform.windows_session_entities.ended_at),state=EXCLUDED.state,latest_event=CASE WHEN EXCLUDED.last_observed>=platform.windows_session_entities.last_observed THEN EXCLUDED.latest_event ELSE platform.windows_session_entities.latest_event END", c, tx); object?[] v = [tenant, value.EndpointId, session.EntityId, session.SessionId, session.Generation, session.FirstObserved, session.LastObserved, session.CreatedAt, session.EndedAt, session.State, json]; for (var i = 0; i < v.Length; i++) if (i == 10) q.Parameters.Add(new() { Value = v[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(v[i] ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
        if (value.Token is { } token) { await using var q = new NpgsqlCommand("INSERT INTO platform.token_entities VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,endpoint_id,token_entity_id) DO UPDATE SET last_observed=GREATEST(platform.token_entities.last_observed,EXCLUDED.last_observed),latest_state=CASE WHEN EXCLUDED.last_observed>=platform.token_entities.last_observed THEN EXCLUDED.latest_state ELSE platform.token_entities.latest_state END", c, tx); object?[] v = [tenant, value.EndpointId, token.EntityId, value.Process?.ProcessEntityId, value.Account?.Sid, token.FirstObserved, token.LastObserved, token.Provenance, JsonSerializer.Serialize(token, Json)]; for (var i = 0; i < v.Length; i++) if (i == 8) q.Parameters.Add(new() { Value = v[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(v[i] ?? DBNull.Value); await q.ExecuteNonQueryAsync(ct); }
        foreach (var privilege in value.Privileges) { await using var q = new NpgsqlCommand("INSERT INTO platform.identity_privilege_observations VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING", c, tx); object[] v = [tenant, value.EventId, value.EndpointId, value.Token?.EntityId ?? (object)DBNull.Value, value.Process?.ProcessEntityId ?? (object)DBNull.Value, privilege.Name, privilege.State, value.ObservedAt, JsonSerializer.Serialize(privilege, Json)]; for (var i = 0; i < v.Length; i++) if (i == 8) q.Parameters.Add(new() { Value = v[i], NpgsqlDbType = NpgsqlDbType.Jsonb }); else q.Parameters.AddWithValue(v[i]); await q.ExecuteNonQueryAsync(ct); }
        if (value.Process is { } process) { await using var q = new NpgsqlCommand("INSERT INTO platform.identity_process_relationships VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING", c, tx); object[] v = [tenant, value.EventId, value.EndpointId, process.ProcessEntityId, value.Logon?.EntityId ?? (object)DBNull.Value, value.Session?.EntityId ?? (object)DBNull.Value, value.Token?.EntityId ?? (object)DBNull.Value, process.Mechanism, process.Confidence, value.ObservedAt]; foreach (var x in v) q.Parameters.AddWithValue(x); await q.ExecuteNonQueryAsync(ct); }
    }
    public async Task<IdentityEventPage> SearchAsync(string tenant, IdentitySearchRequest r, CancellationToken ct) { const string sql = "SELECT event_data FROM platform.identity_events WHERE tenant_id=$1 AND ($2::uuid IS NULL OR endpoint_id=$2) AND ($3='' OR account_name ILIKE '%'||$3||'%') AND ($4='' OR account_sid=$4) AND ($5='' OR domain_name ILIKE '%'||$5||'%') AND ($6::int IS NULL OR logon_type=$6) AND ($7='' OR result=$7) AND ($8='' OR host(source_ip)=$8) AND ($9::bool IS NULL OR remote_session=$9) AND ($10::int IS NULL OR session_id=$10) AND ($11='' OR integrity_level=$11) AND ($12::bool IS NULL OR elevated_token=$12) AND ($13='' OR $13=ANY(privilege_names)) AND ($14='' OR process_entity_id=$14) AND ($15='' OR $15=ANY(data_quality_flags)) AND ($16='' OR event_type=$16) AND ($17::timestamptz IS NULL OR observed_at>=$17) AND ($18::timestamptz IS NULL OR observed_at<=$18) ORDER BY observed_at DESC,event_id DESC LIMIT $19"; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); object?[] values = [Guid.Parse(tenant), r.EndpointId, r.Account ?? "", r.Sid ?? "", r.Domain ?? "", r.LogonType, r.Result ?? "", r.SourceIp ?? "", r.RemoteSession, r.SessionId, r.IntegrityLevel ?? "", r.ElevatedToken, r.Privilege ?? "", r.Process ?? "", r.Quality ?? "", r.Kind?.ToString() ?? "", r.From, r.To, Math.Clamp(r.PageSize, 1, 500)]; foreach (var v in values) q.Parameters.AddWithValue(v ?? DBNull.Value); var list = new List<IdentityObservation>(); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<IdentityObservation>(reader.GetString(0), Json)!); return new(list, null); }
    public async Task<IdentityObservation?> GetAsync(string tenant, Guid eventId, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data FROM platform.identity_events WHERE tenant_id=$1 AND event_id=$2", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(eventId); var value = await q.ExecuteScalarAsync(ct); return value is null ? null : JsonSerializer.Deserialize<IdentityObservation>((string)value, Json); }
    public async Task<IdentityEventPage> EntityHistoryAsync(string tenant, Guid endpoint, string entity, int limit, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data FROM platform.identity_events WHERE tenant_id=$1 AND endpoint_id=$2 AND entity_id=$3 ORDER BY observed_at DESC,event_id DESC LIMIT $4", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint); q.Parameters.AddWithValue(entity); q.Parameters.AddWithValue(Math.Clamp(limit, 1, 500)); var list = new List<IdentityObservation>(); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<IdentityObservation>(reader.GetString(0), Json)!); return new(list, null); }
    public async Task<IdentityTelemetryHealth?> HealthAsync(string tenant, Guid endpoint, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT health_data FROM platform.identity_telemetry_health WHERE tenant_id=$1 AND endpoint_id=$2", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint); var value = await q.ExecuteScalarAsync(ct); return value is null ? null : JsonSerializer.Deserialize<IdentityTelemetryHealth>((string)value, Json); }
    public async Task<IReadOnlyList<IdentityObservation>> ListAllAsync(CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data FROM platform.identity_events ORDER BY observed_at,event_id", c); var list = new List<IdentityObservation>(); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<IdentityObservation>(reader.GetString(0), Json)!); return list; }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
