using System.Text.Json;
using Npgsql;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresAlertIncidentRepository : FileAlertIncidentRepository, IAsyncDisposable
{
    readonly NpgsqlDataSource _data;
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public PostgresAlertIncidentRepository(string connectionString) => _data = NpgsqlDataSource.Create(connectionString);

    protected override async Task<IReadOnlyList<AlertRecord>> LoadAlertsAsync(string tenant, CancellationToken ct)
    {
        var values = new List<AlertRecord>(); await using var connection = await _data.OpenConnectionAsync(ct); await using var command = new NpgsqlCommand("SELECT alert_data::text FROM platform.alerts WHERE tenant_id=$1 ORDER BY last_seen DESC,alert_id LIMIT 20000", connection); command.Parameters.AddWithValue(Guid.Parse(tenant)); await using var reader = await command.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) if (JsonSerializer.Deserialize<AlertRecord>(reader.GetString(0), Json) is { } value) values.Add(value); return values;
    }
    protected override async Task<IReadOnlyList<IncidentRecord>> LoadIncidentsAsync(string tenant, CancellationToken ct)
    {
        var values = new List<IncidentRecord>(); await using var connection = await _data.OpenConnectionAsync(ct); await using var command = new NpgsqlCommand("SELECT incident_data::text FROM platform.triage_incidents WHERE tenant_id=$1 ORDER BY updated_at DESC,incident_id LIMIT 10000", connection); command.Parameters.AddWithValue(Guid.Parse(tenant)); await using var reader = await command.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) if (JsonSerializer.Deserialize<IncidentRecord>(reader.GetString(0), Json) is { } value) values.Add(value); return values;
    }
    protected override async Task<IReadOnlyList<SavedTriageFilter>> LoadFiltersAsync(string tenant, string actor, CancellationToken ct)
    {
        var values = new List<SavedTriageFilter>(); await using var connection = await _data.OpenConnectionAsync(ct); await using var command = new NpgsqlCommand("SELECT filter_data::text FROM platform.saved_triage_filters WHERE tenant_id=$1 AND owner=$2 ORDER BY name", connection); command.Parameters.AddWithValue(Guid.Parse(tenant)); command.Parameters.AddWithValue(actor); await using var reader = await command.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) if (JsonSerializer.Deserialize<SavedTriageFilter>(reader.GetString(0), Json) is { } value) values.Add(value); return values;
    }
    protected override async Task PersistAlertAsync(AlertRecord alert, LifecycleAuditEvent audit, CancellationToken ct)
    {
        await using var connection = await _data.OpenConnectionAsync(ct); await using var tx = await connection.BeginTransactionAsync(ct); await using (var command = new NpgsqlCommand("INSERT INTO platform.alerts(tenant_id,alert_id,deduplication_key,status,disposition,severity,priority,assignee,team,first_seen,last_seen,alert_version,alert_data,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14,now()) ON CONFLICT(tenant_id,alert_id) DO UPDATE SET status=EXCLUDED.status,disposition=EXCLUDED.disposition,severity=EXCLUDED.severity,priority=EXCLUDED.priority,assignee=EXCLUDED.assignee,team=EXCLUDED.team,first_seen=LEAST(platform.alerts.first_seen,EXCLUDED.first_seen),last_seen=GREATEST(platform.alerts.last_seen,EXCLUDED.last_seen),alert_version=EXCLUDED.alert_version,alert_data=EXCLUDED.alert_data,updated_at=now()", connection, tx)) { command.Parameters.AddWithValue(Guid.Parse(alert.TenantId)); command.Parameters.AddWithValue(alert.AlertId); command.Parameters.AddWithValue(alert.DeduplicationKey); command.Parameters.AddWithValue(alert.CurrentStatus.ToString()); command.Parameters.AddWithValue(alert.Disposition.ToString()); command.Parameters.AddWithValue(alert.Severity); command.Parameters.AddWithValue(alert.Priority); command.Parameters.AddWithValue((object?)alert.Assignee ?? DBNull.Value); command.Parameters.AddWithValue((object?)alert.Team ?? DBNull.Value); command.Parameters.AddWithValue(alert.FirstSeen); command.Parameters.AddWithValue(alert.LastSeen); command.Parameters.AddWithValue(alert.Version); command.Parameters.AddWithValue(JsonSerializer.Serialize(alert, Json)); command.Parameters.AddWithValue(alert.CreatedAt); await command.ExecuteNonQueryAsync(ct); }
        await InsertAudit(connection, tx, audit, ct); if (alert.Comments.FirstOrDefault(x => x.AuditId == audit.AuditId) is { } note) await InsertNote(connection, tx, note, ct); await tx.CommitAsync(ct);
    }
    protected override async Task PersistIncidentAsync(IncidentRecord incident, LifecycleAuditEvent audit, CancellationToken ct)
    {
        await using var connection = await _data.OpenConnectionAsync(ct); await using var tx = await connection.BeginTransactionAsync(ct); await using (var command = new NpgsqlCommand("INSERT INTO platform.triage_incidents(tenant_id,incident_id,status,disposition,severity,priority,owner,assignee,team,incident_version,alert_ids,incident_data,created_at,updated_at,closed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15) ON CONFLICT(tenant_id,incident_id) DO UPDATE SET status=EXCLUDED.status,disposition=EXCLUDED.disposition,severity=EXCLUDED.severity,priority=EXCLUDED.priority,assignee=EXCLUDED.assignee,team=EXCLUDED.team,incident_version=EXCLUDED.incident_version,alert_ids=EXCLUDED.alert_ids,incident_data=EXCLUDED.incident_data,updated_at=EXCLUDED.updated_at,closed_at=EXCLUDED.closed_at", connection, tx)) { command.Parameters.AddWithValue(Guid.Parse(incident.TenantId)); command.Parameters.AddWithValue(incident.IncidentId); command.Parameters.AddWithValue(incident.Status.ToString()); command.Parameters.AddWithValue(incident.Disposition.ToString()); command.Parameters.AddWithValue(incident.Severity); command.Parameters.AddWithValue(incident.Priority); command.Parameters.AddWithValue(incident.Owner); command.Parameters.AddWithValue((object?)incident.Assignee ?? DBNull.Value); command.Parameters.AddWithValue((object?)incident.Team ?? DBNull.Value); command.Parameters.AddWithValue(incident.Version); command.Parameters.AddWithValue(incident.AlertIds); command.Parameters.AddWithValue(JsonSerializer.Serialize(incident, Json)); command.Parameters.AddWithValue(incident.CreatedAt); command.Parameters.AddWithValue(incident.UpdatedAt); command.Parameters.AddWithValue((object?)incident.ClosedAt ?? DBNull.Value); await command.ExecuteNonQueryAsync(ct); }
        await InsertAudit(connection, tx, audit, ct); if (incident.Comments.FirstOrDefault(x => x.AuditId == audit.AuditId) is { } note) await InsertNote(connection, tx, note, ct); await tx.CommitAsync(ct);
    }
    protected override async Task PersistFilterAsync(SavedTriageFilter filter, CancellationToken ct)
    {
        await using var connection = await _data.OpenConnectionAsync(ct); await using var command = new NpgsqlCommand("INSERT INTO platform.saved_triage_filters(tenant_id,filter_id,owner,name,filter_version,filter_data,created_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(tenant_id,filter_id) DO UPDATE SET name=EXCLUDED.name,filter_version=platform.saved_triage_filters.filter_version+1,filter_data=EXCLUDED.filter_data", connection); command.Parameters.AddWithValue(Guid.Parse(filter.TenantId)); command.Parameters.AddWithValue(filter.FilterId); command.Parameters.AddWithValue(filter.Owner); command.Parameters.AddWithValue(filter.Name); command.Parameters.AddWithValue(filter.Version); command.Parameters.AddWithValue(JsonSerializer.Serialize(filter, Json)); command.Parameters.AddWithValue(filter.CreatedAt); await command.ExecuteNonQueryAsync(ct);
    }
    static async Task InsertAudit(NpgsqlConnection connection, NpgsqlTransaction tx, LifecycleAuditEvent audit, CancellationToken ct)
    {
        await using var command = new NpgsqlCommand("INSERT INTO platform.lifecycle_audit(tenant_id,audit_id,object_type,object_id,object_version,action,actor,occurred_at,before_data,after_data,reason,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11,$12) ON CONFLICT DO NOTHING", connection, tx); command.Parameters.AddWithValue(Guid.Parse(audit.TenantId)); command.Parameters.AddWithValue(audit.AuditId); command.Parameters.AddWithValue(audit.ObjectType); command.Parameters.AddWithValue(audit.ObjectId); command.Parameters.AddWithValue(audit.ObjectVersion); command.Parameters.AddWithValue(audit.Action); command.Parameters.AddWithValue(audit.Actor); command.Parameters.AddWithValue(audit.OccurredAt); command.Parameters.AddWithValue(JsonSerializer.Serialize(audit.Before, Json)); command.Parameters.AddWithValue(JsonSerializer.Serialize(audit.After, Json)); command.Parameters.AddWithValue(audit.Reason); command.Parameters.AddWithValue(audit.Provenance); await command.ExecuteNonQueryAsync(ct);
    }
    static async Task InsertNote(NpgsqlConnection connection, NpgsqlTransaction tx, AnalystNote note, CancellationToken ct)
    {
        await using var command = new NpgsqlCommand("INSERT INTO platform.analyst_notes(tenant_id,note_id,object_type,object_id,note_kind,author,note_version,content,note_data,created_at,audit_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) ON CONFLICT DO NOTHING", connection, tx); command.Parameters.AddWithValue(Guid.Parse(note.TenantId)); command.Parameters.AddWithValue(note.NoteId); command.Parameters.AddWithValue(note.ObjectType); command.Parameters.AddWithValue(note.ObjectId); command.Parameters.AddWithValue(note.Kind.ToString()); command.Parameters.AddWithValue(note.Author); command.Parameters.AddWithValue(note.Version); command.Parameters.AddWithValue(note.Content); command.Parameters.AddWithValue(JsonSerializer.Serialize(note, Json)); command.Parameters.AddWithValue(note.CreatedAt); command.Parameters.AddWithValue(note.AuditId); await command.ExecuteNonQueryAsync(ct);
    }
    public override async Task<TriageHealth> HealthAsync(string tenant, CancellationToken ct)
    {
        var memory = await base.HealthAsync(tenant, ct); await using var connection = await _data.OpenConnectionAsync(ct); await using var command = new NpgsqlCommand("SELECT (SELECT count(*) FROM platform.alerts WHERE tenant_id=$1),(SELECT count(*) FROM platform.lifecycle_audit WHERE tenant_id=$1 AND action='alert.deduplicated'),(SELECT count(*) FROM platform.alerts WHERE tenant_id=$1 AND status='Closed'),(SELECT count(*) FROM platform.lifecycle_audit WHERE tenant_id=$1 AND action='alert.status.changed' AND before_data->>'status'='Closed'),(SELECT count(*) FROM platform.triage_incidents WHERE tenant_id=$1),(SELECT count(*) FROM platform.triage_incidents WHERE tenant_id=$1 AND status='Closed'),(SELECT count(*) FROM platform.lifecycle_audit WHERE tenant_id=$1 AND action='incident.created')", connection); command.Parameters.AddWithValue(Guid.Parse(tenant)); await using var reader = await command.ExecuteReaderAsync(ct); await reader.ReadAsync(ct); return memory with { AlertsCreated = reader.GetInt64(0), AlertsDeduplicated = reader.GetInt64(1), AlertsClosed = reader.GetInt64(2), AlertsReopened = reader.GetInt64(3), IncidentsCreated = reader.GetInt64(4), IncidentsClosed = reader.GetInt64(5), GroupingExecutions = reader.GetInt64(6), UpdatedAt = DateTimeOffset.UtcNow };
    }
    public async ValueTask DisposeAsync() { await _data.DisposeAsync(); Dispose(); GC.SuppressFinalize(this); }
}
