using System.Text.Json;
using Npgsql;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresLiveResponseRepository : FileLiveResponseRepository, IAsyncDisposable
{
    readonly NpgsqlDataSource _data; static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public PostgresLiveResponseRepository(string connectionString) => _data = NpgsqlDataSource.Create(connectionString);
    protected override async Task<IReadOnlyList<LiveSessionRecord>> LoadAsync(string tenant, CancellationToken ct) { var values = new List<LiveSessionRecord>(); await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT session_data::text FROM platform.live_response_sessions WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 5000", c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) if (JsonSerializer.Deserialize<LiveSessionRecord>(r.GetString(0), Json) is { } x) values.Add(x); return values; }
    protected override async Task<IReadOnlyList<LiveSessionRecord>> LoadAllAsync(CancellationToken ct) { var values = new List<LiveSessionRecord>(); await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT session_data::text FROM platform.live_response_sessions ORDER BY created_at DESC LIMIT 10000", c); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) if (JsonSerializer.Deserialize<LiveSessionRecord>(r.GetString(0), Json) is { } x) values.Add(x); return values; }
    protected override async Task PersistAsync(LiveSessionRecord value, IReadOnlyList<LiveTranscriptEvent> audit, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct);
        await using (var cmd = new NpgsqlCommand("INSERT INTO platform.live_response_sessions(tenant_id,session_id,endpoint_id,agent_id,agent_installation_id,analyst_id,state,capability_hash,nonce,created_at,expires_at,absolute_expires_at,session_revision,session_data,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,now()) ON CONFLICT(tenant_id,session_id) DO UPDATE SET state=EXCLUDED.state,session_revision=EXCLUDED.session_revision,session_data=EXCLUDED.session_data,updated_at=now()", c, tx)) { object[] p = [Guid.Parse(value.TenantId), value.SessionId, value.EndpointId, value.AgentId, value.AgentInstallationId, value.AnalystId, value.State.ToString(), value.CapabilityHash, value.Nonce, value.CreatedAt, value.ExpiresAt, value.AbsoluteExpiresAt, value.Version, JsonSerializer.Serialize(value, Json)]; foreach (var x in p) cmd.Parameters.AddWithValue(x); await cmd.ExecuteNonQueryAsync(ct); }
        foreach (var command in value.Commands) { await using var cmd = new NpgsqlCommand("INSERT INTO platform.live_response_commands(tenant_id,session_id,command_id,state,input_hash,nonce,requested_at,command_data,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,now()) ON CONFLICT(tenant_id,command_id) DO UPDATE SET state=EXCLUDED.state,command_data=EXCLUDED.command_data,updated_at=now()", c, tx); object[] p = [Guid.Parse(value.TenantId), value.SessionId, command.CommandId, command.State.ToString(), command.InputHash, command.Nonce, command.RequestedAt, JsonSerializer.Serialize(command, Json)]; foreach (var x in p) cmd.Parameters.AddWithValue(x); await cmd.ExecuteNonQueryAsync(ct); foreach (var artifact in command.Result?.Artifacts ?? []) { await using var ac = new NpgsqlCommand("INSERT INTO platform.live_response_artifacts(tenant_id,artifact_id,session_id,command_id,object_id,manifest_object_id,name,media_type,size_bytes,sha256,native_identity,consistent,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT DO NOTHING", c, tx); object[] ap = [Guid.Parse(value.TenantId), artifact.ArtifactId, value.SessionId, artifact.CommandId, artifact.ObjectId, artifact.ManifestObjectId, artifact.Name, artifact.MediaType, artifact.Size, artifact.Sha256, artifact.NativeIdentity, artifact.Consistent, artifact.CreatedAt, artifact.ExpiresAt]; foreach (var x in ap) ac.Parameters.AddWithValue(x); await ac.ExecuteNonQueryAsync(ct); } }
        foreach (var a in audit) { await using var cmd = new NpgsqlCommand("INSERT INTO platform.live_response_transcript(tenant_id,event_id,session_id,command_id,object_version,event_type,actor,occurred_at,integrity_hash,summary,metadata,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12) ON CONFLICT DO NOTHING", c, tx); object[] p = [Guid.Parse(a.TenantId), a.EventId, a.SessionId, (object?)a.CommandId ?? DBNull.Value, a.ObjectVersion, a.EventType, a.Actor, a.OccurredAt, a.IntegrityHash, a.Summary, JsonSerializer.Serialize(a.Metadata, Json), a.Provenance]; foreach (var x in p) cmd.Parameters.AddWithValue(x); await cmd.ExecuteNonQueryAsync(ct); }
        await tx.CommitAsync(ct);
    }
    public async ValueTask DisposeAsync() { await _data.DisposeAsync(); Dispose(); GC.SuppressFinalize(this); }
}
