using System.Data;
using System.Net;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresDnsTelemetryRepository(string connectionString) : IDnsTelemetryRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly NpgsqlDataSource _data = NpgsqlDataSource.Create(new NpgsqlConnectionStringBuilder(connectionString) { Pooling = true, MinPoolSize = 1, MaxPoolSize = 8, ConnectionIdleLifetime = 30, ConnectionPruningInterval = 5, Timeout = 5, CommandTimeout = 20 }.ConnectionString);
    public async Task<DnsIngestResult> IngestAsync(string tenantId, DnsEventBatch batch, DnsTelemetryHealth health, CancellationToken ct)
    {
        var tenant = Guid.Parse(tenantId); await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct);
        await using (var bind = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.agents a JOIN platform.endpoints e ON e.tenant_id=a.tenant_id AND e.id=a.endpoint_id WHERE a.tenant_id=$1 AND a.id=$2 AND a.endpoint_id=$3 AND a.instance_id=$4 AND a.status='active' AND e.status NOT IN('disabled','revoked'))", c, tx)) { bind.Parameters.AddWithValue(tenant); bind.Parameters.AddWithValue(batch.AgentId); bind.Parameters.AddWithValue(batch.EndpointId); bind.Parameters.AddWithValue(batch.InstallationId); if ((bool)(await bind.ExecuteScalarAsync(ct) ?? false) == false) throw new EnrollmentConflictException("DNS_IDENTITY_INVALID", "DNS telemetry identity is invalid or disabled."); }
        await using (var cmd = new NpgsqlCommand("INSERT INTO platform.dns_batches(tenant_id,batch_id,endpoint_id,agent_id,installation_id,first_sequence,last_sequence,event_count,content_sha256,schema_version,compression,uncompressed_bytes,compressed_bytes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT DO NOTHING", c, tx)) { object[] v = [tenant, batch.BatchId, batch.EndpointId, batch.AgentId, batch.InstallationId, batch.FirstSequence, batch.LastSequence, batch.Events.Count, batch.ContentSha256, batch.SchemaVersion, batch.Compression, batch.UncompressedBytes, batch.CompressedBytes]; foreach (var x in v) cmd.Parameters.AddWithValue(x); await cmd.ExecuteNonQueryAsync(ct); }
        long previous = 0; await using (var cmd = new NpgsqlCommand("SELECT COALESCE((health_data->>'lastSequence')::bigint,0) FROM platform.dns_telemetry_health WHERE tenant_id=$1 AND endpoint_id=$2 FOR UPDATE", c, tx)) { cmd.Parameters.AddWithValue(tenant); cmd.Parameters.AddWithValue(batch.EndpointId); previous = (long?)await cmd.ExecuteScalarAsync(ct) ?? 0; }
        var accepted = new List<Guid>(); var duplicates = new List<Guid>(); var rejected = new Dictionary<Guid, string>(); var gaps = 0;
        foreach (var source in batch.Events.OrderBy(x => x.Sequence))
        {
            var now = DateTimeOffset.UtcNow; var x = source with { ReceivedAt = now, IngestedAt = now, Late = source.ObservedAt < now.AddMinutes(-5) };
            if (x.EndpointId != batch.EndpointId || x.AgentId != batch.AgentId || x.InstallationId != batch.InstallationId) { rejected[x.EventId] = "identity-mismatch"; continue; }
            if (!Valid(x, out var error)) { rejected[x.EventId] = error; continue; }
            var addresses = x.Answers.Select(a => a.ResolvedAddress).Where(a => IPAddress.TryParse(a, out _)).Select(a => IPAddress.Parse(a!)).ToArray();
            var relationships = await NetworkRelationships(c, tx, tenant, x, addresses, ct);
            if (relationships.Count > 0) x = x with { NetworkRelationships = relationships };
            int inserted; await using (var cmd = new NpgsqlCommand("INSERT INTO platform.dns_events(tenant_id,event_id,batch_id,endpoint_id,agent_id,transaction_entity_id,event_type,sequence,observed_at,schema_version,normalization_version,collector_source,collector_version,native_provider,native_event_id,raw_sha256,policy_version,original_query_name,canonical_query_name,record_type,response_code,resolver_address,process_entity_id,resolved_addresses,data_quality_flags,late,out_of_order,event_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28) ON CONFLICT DO NOTHING", c, tx))
            { object?[] v = [tenant, x.EventId, batch.BatchId, x.EndpointId, x.AgentId, x.TransactionEntityId, DbKind(x.Kind), x.Sequence, x.ObservedAt, x.SchemaVersion, x.NormalizationVersion, x.CollectorSource, x.CollectorVersion, x.NativeProvider, x.NativeEventId, x.RawSha256, health.PolicyVersion, x.OriginalQueryName, x.CanonicalQueryName, x.RecordType, x.ResponseCode, x.ResolverAddress is null ? null : IPAddress.Parse(x.ResolverAddress), x.Process?.ProcessEntityId, addresses, x.DataQualityFlags, x.Late, x.OutOfOrder, JsonSerializer.Serialize(x, Json)]; for (var i = 0; i < v.Length; i++) if (i == 27) cmd.Parameters.Add(new NpgsqlParameter { Value = v[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else if (i == 21) cmd.Parameters.Add(new NpgsqlParameter { Value = v[i] ?? DBNull.Value, NpgsqlDbType = NpgsqlDbType.Inet }); else if (i == 23) cmd.Parameters.Add(new NpgsqlParameter { Value = v[i]!, NpgsqlDbType = NpgsqlDbType.Array | NpgsqlDbType.Inet }); else cmd.Parameters.AddWithValue(v[i] ?? DBNull.Value); inserted = await cmd.ExecuteNonQueryAsync(ct); }
            if (inserted == 0) { await using var collision = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.dns_events WHERE tenant_id=$1 AND event_id=$2)", c, tx); collision.Parameters.AddWithValue(tenant); collision.Parameters.AddWithValue(x.EventId); if ((bool)(await collision.ExecuteScalarAsync(ct) ?? false)) duplicates.Add(x.EventId); else rejected[x.EventId] = "sequence-collision"; continue; }
            accepted.Add(x.EventId); if (previous > 0 && x.Sequence > previous + 1) gaps += (int)Math.Min(int.MaxValue, x.Sequence - previous - 1); previous = Math.Max(previous, x.Sequence);
            for (var i = 0; i < x.Answers.Count; i++) { await using var answer = new NpgsqlCommand("INSERT INTO platform.dns_answer_records(tenant_id,event_id,ordinal,answer_data) VALUES($1,$2,$3,$4)", c, tx); answer.Parameters.AddWithValue(tenant); answer.Parameters.AddWithValue(x.EventId); answer.Parameters.AddWithValue(i); answer.Parameters.Add(new NpgsqlParameter { Value = JsonSerializer.Serialize(x.Answers[i], Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await answer.ExecuteNonQueryAsync(ct); }
            foreach (var relationship in relationships) { await using var relation = new NpgsqlCommand("INSERT INTO platform.dns_network_relationships(tenant_id,dns_event_id,network_event_id,relationship_data) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING", c, tx); relation.Parameters.AddWithValue(tenant); relation.Parameters.AddWithValue(x.EventId); relation.Parameters.AddWithValue(relationship.NetworkEventId); relation.Parameters.Add(new NpgsqlParameter { Value = JsonSerializer.Serialize(relationship, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await relation.ExecuteNonQueryAsync(ct); }
            if (x.TransactionEntityId is not null) { await using var entity = new NpgsqlCommand("INSERT INTO platform.dns_transactions(tenant_id,endpoint_id,transaction_entity_id,canonical_query_name,record_type,first_observed,last_observed,query_event_id,response_event_id,state,transaction_confidence,process_entity_id,latest_event) VALUES($1,$2,$3,$4,$5,$6,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(tenant_id,endpoint_id,transaction_entity_id) DO UPDATE SET first_observed=LEAST(platform.dns_transactions.first_observed,EXCLUDED.first_observed),last_observed=GREATEST(platform.dns_transactions.last_observed,EXCLUDED.last_observed),query_event_id=COALESCE(platform.dns_transactions.query_event_id,EXCLUDED.query_event_id),response_event_id=COALESCE(EXCLUDED.response_event_id,platform.dns_transactions.response_event_id),state=CASE WHEN EXCLUDED.last_observed>=platform.dns_transactions.last_observed THEN EXCLUDED.state ELSE platform.dns_transactions.state END,latest_event=CASE WHEN EXCLUDED.last_observed>=platform.dns_transactions.last_observed THEN EXCLUDED.latest_event ELSE platform.dns_transactions.latest_event END", c, tx); object?[] v = [tenant, x.EndpointId, x.TransactionEntityId, x.CanonicalQueryName, x.RecordType, x.ObservedAt, x.Kind == DnsEventKind.QueryObserved ? x.EventId : null, x.Kind is DnsEventKind.ResponseObserved or DnsEventKind.TransactionObserved ? x.EventId : null, x.State.ToString().ToLowerInvariant(), x.TransactionConfidence, x.Process?.ProcessEntityId, JsonSerializer.Serialize(x, Json)]; for (var i = 0; i < v.Length; i++) if (i == 11) entity.Parameters.Add(new NpgsqlParameter { Value = v[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else entity.Parameters.AddWithValue(v[i] ?? DBNull.Value); await entity.ExecuteNonQueryAsync(ct); }
            await using var outbox = new NpgsqlCommand("INSERT INTO platform.outbox(id,tenant_id,topic,subject,message,trace_id) VALUES($1,$2,'dns.changed','dns.telemetry.v1',$3,'')", c, tx); outbox.Parameters.AddWithValue(Guid.NewGuid()); outbox.Parameters.AddWithValue(tenant); outbox.Parameters.Add(new NpgsqlParameter { Value = JsonSerializer.Serialize(new { tenantId, eventId = x.EventId, endpointId = x.EndpointId, transactionEntityId = x.TransactionEntityId, observedAt = x.ObservedAt }, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await outbox.ExecuteNonQueryAsync(ct);
        }
        var remaining = Math.Max(0, health.QueueDepth - accepted.Count - duplicates.Count); var h = health with { QueueDepth = remaining, OldestQueuedSeconds = remaining == 0 ? 0 : health.OldestQueuedSeconds, SequenceGaps = health.SequenceGaps + gaps, LastSequence = Math.Max(previous, health.LastSequence), LastAcceptedEvent = accepted.Count == 0 ? health.LastAcceptedEvent : batch.Events.Where(x => accepted.Contains(x.EventId)).Max(x => x.ObservedAt) };
        await using (var cmd = new NpgsqlCommand("INSERT INTO platform.dns_telemetry_health(tenant_id,endpoint_id,health_data) VALUES($1,$2,$3) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET health_data=EXCLUDED.health_data,updated_at=now()", c, tx)) { cmd.Parameters.AddWithValue(tenant); cmd.Parameters.AddWithValue(batch.EndpointId); cmd.Parameters.Add(new NpgsqlParameter { Value = JsonSerializer.Serialize(h, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await cmd.ExecuteNonQueryAsync(ct); }
        await tx.CommitAsync(ct); return new(new(batch.BatchId, accepted, duplicates, rejected, previous, gaps > 0), accepted.Count, duplicates.Count, rejected.Count, gaps);
    }
    static bool Valid(DnsObservation x, out string error)
    { error = DnsObservationValidation.Error(x, DateTimeOffset.UtcNow) ?? ""; return error.Length == 0; }
    static string DbKind(DnsEventKind k) => k switch { DnsEventKind.QueryObserved => "query_observed", DnsEventKind.ResponseObserved => "response_observed", DnsEventKind.QueryFailed => "query_failed", _ => "transaction_observed" };
    static async Task<IReadOnlyList<DnsNetworkRelationship>> NetworkRelationships(NpgsqlConnection c, NpgsqlTransaction tx, Guid tenant, DnsObservation x, IPAddress[] addresses, CancellationToken ct)
    {
        if (addresses.Length == 0) return [];
        await using var cmd = new NpgsqlCommand("SELECT event_id,host(remote_address),process_entity_id FROM platform.network_events WHERE tenant_id=$1 AND endpoint_id=$2 AND remote_address=ANY($3) AND observed_at BETWEEN $4 AND $5 ORDER BY observed_at,event_id LIMIT 100", c, tx);
        cmd.Parameters.AddWithValue(tenant); cmd.Parameters.AddWithValue(x.EndpointId); cmd.Parameters.Add(new NpgsqlParameter { Value = addresses, NpgsqlDbType = NpgsqlDbType.Array | NpgsqlDbType.Inet }); cmd.Parameters.AddWithValue(x.ObservedAt.AddSeconds(-5)); cmd.Parameters.AddWithValue(x.ObservedAt.AddMinutes(5));
        var values = new List<DnsNetworkRelationship>(); await using var r = await cmd.ExecuteReaderAsync(ct);
        while (await r.ReadAsync(ct)) { var processMatch = x.Process?.ProcessEntityId is { } p && !r.IsDBNull(2) && r.GetString(2) == p; values.Add(new(r.GetGuid(0), r.GetString(1), "dns-answer-ip+bounded-network-event", 300, processMatch, true, processMatch ? "medium" : "low", true, x.ObservedAt.AddMinutes(5))); }
        return values;
    }
    public async Task<DnsEventPage> SearchAsync(string tenant, DnsSearchRequest q, CancellationToken ct)
    { const string sql = "SELECT event_data FROM platform.dns_events WHERE tenant_id=$1 AND ($2::uuid IS NULL OR endpoint_id=$2) AND ($3::timestamptz IS NULL OR observed_at>=$3) AND ($4::timestamptz IS NULL OR observed_at<=$4) AND ($5='' OR canonical_query_name=$5) AND ($6='' OR canonical_query_name=$6 OR canonical_query_name LIKE '%.'||$6) AND ($7='' OR record_type=$7) AND ($8='' OR response_code=$8) AND ($9='' OR $9::inet=ANY(resolved_addresses)) AND ($10='' OR process_entity_id=$10 OR event_data#>>'{process,image}' ILIKE '%'||$10||'%') AND ($11='' OR event_data->>'user'=$11) AND ($12='' OR host(resolver_address)=$12) AND ($13='' OR collector_source=$13) AND ($14='' OR $14=ANY(data_quality_flags)) ORDER BY observed_at DESC,event_id DESC LIMIT $15"; await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand(sql, c); object?[] v = [Guid.Parse(tenant), q.EndpointId, q.From, q.To, q.QueryName?.TrimEnd('.').ToLowerInvariant() ?? "", q.Suffix?.TrimStart('.').TrimEnd('.').ToLowerInvariant() ?? "", q.RecordType?.ToUpperInvariant() ?? "", q.ResponseCode ?? "", q.ResolvedAddress ?? "", q.Process ?? "", q.User ?? "", q.Resolver ?? "", q.Collector ?? "", q.Quality ?? "", Math.Clamp(q.PageSize, 1, 500)]; foreach (var x in v) cmd.Parameters.AddWithValue(x ?? DBNull.Value); var list = new List<DnsObservation>(); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<DnsObservation>(r.GetString(0), Json)!); return new(list, null); }
    public async Task<DnsObservation?> GetEventAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT event_data FROM platform.dns_events WHERE tenant_id=$1 AND event_id=$2", c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); cmd.Parameters.AddWithValue(id); var v = await cmd.ExecuteScalarAsync(ct); return v is null ? null : JsonSerializer.Deserialize<DnsObservation>((string)v, Json); }
    async Task<DnsEventPage> History(string tenant, Guid endpoint, string predicate, string id, DateTimeOffset from, DateTimeOffset to, int limit, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand($"SELECT event_data FROM platform.dns_events WHERE tenant_id=$1 AND endpoint_id=$2 AND observed_at BETWEEN $3 AND $4 AND {predicate}=$5 ORDER BY observed_at,event_id LIMIT $6", c); object[] v = [Guid.Parse(tenant), endpoint, from, to, id, Math.Clamp(limit, 1, 500)]; foreach (var x in v) cmd.Parameters.AddWithValue(x); var list = new List<DnsObservation>(); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<DnsObservation>(r.GetString(0), Json)!); return new(list, null); }
    public Task<DnsEventPage> HistoryAsync(string t, Guid e, string id, DateTimeOffset f, DateTimeOffset to, int l, CancellationToken ct) => History(t, e, "transaction_entity_id", id, f, to, l, ct);
    public Task<DnsEventPage> ProcessDnsAsync(string t, Guid e, string id, DateTimeOffset f, DateTimeOffset to, int l, CancellationToken ct) => History(t, e, "process_entity_id", id, f, to, l, ct);
    public async Task<DnsTelemetryHealth?> HealthAsync(string t, Guid e, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT health_data FROM platform.dns_telemetry_health WHERE tenant_id=$1 AND endpoint_id=$2", c); cmd.Parameters.AddWithValue(Guid.Parse(t)); cmd.Parameters.AddWithValue(e); var v = await cmd.ExecuteScalarAsync(ct); return v is null ? null : JsonSerializer.Deserialize<DnsTelemetryHealth>((string)v, Json); }
    public async Task<IReadOnlyList<DnsObservation>> ListAllAsync(CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT event_data FROM platform.dns_events ORDER BY observed_at,event_id", c); var list = new List<DnsObservation>(); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<DnsObservation>(r.GetString(0), Json)!); return list; }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
