using System.Data;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;
namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresPersistenceTelemetryRepository(string connectionString) : IPersistenceTelemetryRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly NpgsqlDataSource _data = NpgsqlDataSource.Create(new NpgsqlConnectionStringBuilder(connectionString) { Pooling = true, MaxPoolSize = 8, ConnectionIdleLifetime = 30, ConnectionPruningInterval = 5, Timeout = 5, CommandTimeout = 20 }.ConnectionString);
    public async Task<PersistenceIngestResult> IngestAsync(string tenantText, PersistenceEventBatch batch, PersistenceTelemetryHealth health, CancellationToken ct)
    {
        var tenant = Guid.Parse(tenantText); await using var connection = await _data.OpenConnectionAsync(ct); await using var transaction = await connection.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct);
        await using (var identity = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.agents a JOIN platform.endpoints e ON e.tenant_id=a.tenant_id AND e.id=a.endpoint_id WHERE a.tenant_id=$1 AND a.id=$2 AND a.endpoint_id=$3 AND a.instance_id=$4 AND a.status='active' AND e.status NOT IN('disabled','revoked'))", connection, transaction)) { identity.Parameters.AddWithValue(tenant); identity.Parameters.AddWithValue(batch.AgentId); identity.Parameters.AddWithValue(batch.EndpointId); identity.Parameters.AddWithValue(batch.InstallationId); if (!(bool)(await identity.ExecuteScalarAsync(ct) ?? false)) throw new EnrollmentConflictException("PERSISTENCE_IDENTITY_INVALID", "Service/task telemetry identity is invalid."); }
        await using (var command = new NpgsqlCommand("INSERT INTO platform.persistence_batches VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now()) ON CONFLICT DO NOTHING", connection, transaction)) { object[] values = [tenant, batch.BatchId, batch.EndpointId, batch.AgentId, batch.InstallationId, batch.FirstSequence, batch.LastSequence, batch.Events.Count, batch.ContentSha256]; foreach (var value in values) command.Parameters.AddWithValue(value); await command.ExecuteNonQueryAsync(ct); }
        var accepted = new List<Guid>(); var duplicates = new List<Guid>(); var rejected = new Dictionary<Guid, string>(); long acknowledged = 0;
        foreach (var source in batch.Events.OrderBy(x => x.Sequence))
        {
            var value = source with { ReceivedAt = DateTimeOffset.UtcNow, IngestedAt = DateTimeOffset.UtcNow, Late = source.ObservedAt < DateTimeOffset.UtcNow.AddMinutes(-5) };
            if (value.Configuration is { } unresolved)
            {
                var resolved = await ResolveEvidence(connection, transaction, tenant, value.EndpointId, value.ObservedAt, unresolved, ct);
                var flags = value.DataQualityFlags.Where(x => x != "raw-evidence-reference-resolution-pending").ToList();
                if (resolved.RelationshipAmbiguous) flags.Add("raw-evidence-reference-not-observed");
                value = value with { Configuration = resolved, DataQualityFlags = flags.Distinct(StringComparer.Ordinal).ToArray(), QualityState = flags.Count == 0 ? "complete" : "partial" };
            }
            var entity = value.Service?.EntityId ?? value.ScheduledTask?.EntityId ?? value.Configuration?.EntityId; var name = value.Service?.Name ?? value.ScheduledTask?.Name ?? value.Configuration?.Name; var path = value.Service?.BinaryPath ?? value.ScheduledTask?.Path ?? value.Configuration?.RegistryPath ?? value.Configuration?.FilePath;
            if (value.SchemaVersion != "persistence-event.v1" || value.EndpointId != batch.EndpointId || value.AgentId != batch.AgentId || value.InstallationId != batch.InstallationId || entity?.Length != 64 || !PersistenceSafety.SafeName(name, 32767) || value.EvidenceSha256.Length != 64) { rejected[value.EventId] = "invalid-event"; continue; }
            var json = JsonSerializer.Serialize(value, Json); int inserted;
            await using (var command = new NpgsqlCommand("INSERT INTO platform.persistence_events(tenant_id,event_id,batch_id,endpoint_id,agent_id,object_kind,event_type,entity_id,object_name,object_path,account_name,state,object_type,process_entity_id,sequence,observed_at,data_quality_flags,event_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT DO NOTHING", connection, transaction)) { object?[] values = [tenant, value.EventId, batch.BatchId, value.EndpointId, value.AgentId, value.ObjectKind.ToString(), value.Kind.ToString(), entity, name, path, value.Service?.Account ?? value.ScheduledTask?.Principal ?? value.Configuration?.Principal, value.Service?.State ?? value.ScheduledTask?.ExecutionResult ?? value.Configuration?.CurrentState, value.Service?.ServiceType ?? value.ScheduledTask?.Triggers.FirstOrDefault()?.Type ?? value.Configuration?.Subtype, value.Service?.Process?.ProcessEntityId ?? value.ScheduledTask?.Process?.ProcessEntityId, value.Sequence, value.ObservedAt, value.DataQualityFlags, json]; for (var index = 0; index < values.Length; index++) if (index == 17) command.Parameters.Add(new() { Value = values[index]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else command.Parameters.AddWithValue(values[index] ?? DBNull.Value); inserted = await command.ExecuteNonQueryAsync(ct); }
            if (inserted == 0) { await using var check = new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM platform.persistence_events WHERE tenant_id=$1 AND event_id=$2)", connection, transaction); check.Parameters.AddWithValue(tenant); check.Parameters.AddWithValue(value.EventId); if ((bool)(await check.ExecuteScalarAsync(ct) ?? false)) duplicates.Add(value.EventId); else rejected[value.EventId] = "sequence-collision"; continue; }
            accepted.Add(value.EventId); acknowledged = Math.Max(acknowledged, value.Sequence);
            if (value.Service is { } service) await UpsertService(connection, transaction, tenant, value, service, json, ct); else if (value.ScheduledTask is { } task) await UpsertTask(connection, transaction, tenant, value, task, json, ct); else if (value.Configuration is { } configuration) await UpsertConfiguration(connection, transaction, tenant, value, configuration, json, ct);
            await using var outbox = new NpgsqlCommand("INSERT INTO platform.outbox(id,tenant_id,topic,subject,message,trace_id) VALUES($1,$2,'persistence.changed','persistence.telemetry.v1',$3,'')", connection, transaction); outbox.Parameters.AddWithValue(Guid.NewGuid()); outbox.Parameters.AddWithValue(tenant); outbox.Parameters.Add(new() { Value = JsonSerializer.Serialize(new { tenantId = tenantText, eventId = value.EventId, endpointId = value.EndpointId }, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await outbox.ExecuteNonQueryAsync(ct);
        }
        var updatedHealth = health with { QueueDepth = Math.Max(0, health.QueueDepth - accepted.Count - duplicates.Count), LastAcceptedEvent = accepted.Count > 0 ? batch.Events.Where(x => accepted.Contains(x.EventId)).Max(x => x.ObservedAt) : health.LastAcceptedEvent, LastSequence = Math.Max(acknowledged, health.LastSequence) };
        await using (var command = new NpgsqlCommand("INSERT INTO platform.persistence_telemetry_health VALUES($1,$2,$3,now()) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET health_data=EXCLUDED.health_data,updated_at=now()", connection, transaction)) { command.Parameters.AddWithValue(tenant); command.Parameters.AddWithValue(batch.EndpointId); command.Parameters.Add(new() { Value = JsonSerializer.Serialize(updatedHealth, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await command.ExecuteNonQueryAsync(ct); }
        await transaction.CommitAsync(ct); return new(new(batch.BatchId, accepted, duplicates, rejected, acknowledged, false), accepted.Count, duplicates.Count, rejected.Count, 0);
    }
    static async Task UpsertService(NpgsqlConnection c, NpgsqlTransaction tx, Guid tenant, PersistenceObservation value, ServiceEvidence service, string json, CancellationToken ct)
    { await using (var command = new NpgsqlCommand("INSERT INTO platform.service_entities VALUES($1,$2,$3,$4,$5,$5,$6,$7,$8) ON CONFLICT(tenant_id,endpoint_id,service_entity_id) DO UPDATE SET last_observed=GREATEST(platform.service_entities.last_observed,EXCLUDED.last_observed),deleted_at=COALESCE(EXCLUDED.deleted_at,platform.service_entities.deleted_at),latest_event=CASE WHEN EXCLUDED.last_observed>=platform.service_entities.last_observed THEN EXCLUDED.latest_event ELSE platform.service_entities.latest_event END", c, tx)) { object?[] values = [tenant, value.EndpointId, service.EntityId, service.Name, value.ObservedAt, service.CreatedAt, service.DeletedAt, json]; for (var i = 0; i < values.Length; i++) if (i == 7) command.Parameters.Add(new() { Value = values[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else command.Parameters.AddWithValue(values[i] ?? DBNull.Value); await command.ExecuteNonQueryAsync(ct); } if (value.Kind is PersistenceEventKind.ServiceCreated or PersistenceEventKind.ServiceConfigurationChanged) { await using var history = new NpgsqlCommand("INSERT INTO platform.service_configuration_history VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING", c, tx); object[] values = [tenant, value.EndpointId, service.EntityId, value.EventId, value.ObservedAt, JsonSerializer.Serialize(service, Json)]; for (var i = 0; i < values.Length; i++) if (i == 5) history.Parameters.Add(new() { Value = values[i], NpgsqlDbType = NpgsqlDbType.Jsonb }); else history.Parameters.AddWithValue(values[i]); await history.ExecuteNonQueryAsync(ct); } }
    static async Task UpsertTask(NpgsqlConnection c, NpgsqlTransaction tx, Guid tenant, PersistenceObservation value, ScheduledTaskEvidence task, string json, CancellationToken ct)
    { await using (var command = new NpgsqlCommand("INSERT INTO platform.scheduled_task_entities VALUES($1,$2,$3,$4,$5,$5,$6,$7,$8) ON CONFLICT(tenant_id,endpoint_id,task_entity_id) DO UPDATE SET last_observed=GREATEST(platform.scheduled_task_entities.last_observed,EXCLUDED.last_observed),deleted_at=COALESCE(EXCLUDED.deleted_at,platform.scheduled_task_entities.deleted_at),latest_event=CASE WHEN EXCLUDED.last_observed>=platform.scheduled_task_entities.last_observed THEN EXCLUDED.latest_event ELSE platform.scheduled_task_entities.latest_event END", c, tx)) { object?[] values = [tenant, value.EndpointId, task.EntityId, task.Path, value.ObservedAt, task.RegisteredAt, task.DeletedAt, json]; for (var i = 0; i < values.Length; i++) if (i == 7) command.Parameters.Add(new() { Value = values[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else command.Parameters.AddWithValue(values[i] ?? DBNull.Value); await command.ExecuteNonQueryAsync(ct); } if (value.Kind is PersistenceEventKind.ScheduledTaskRegistered or PersistenceEventKind.ScheduledTaskUpdated) { await using var history = new NpgsqlCommand("INSERT INTO platform.scheduled_task_configuration_history VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING", c, tx); object[] values = [tenant, value.EndpointId, task.EntityId, value.EventId, value.ObservedAt, JsonSerializer.Serialize(task, Json)]; for (var i = 0; i < values.Length; i++) if (i == 5) history.Parameters.Add(new() { Value = values[i], NpgsqlDbType = NpgsqlDbType.Jsonb }); else history.Parameters.AddWithValue(values[i]); await history.ExecuteNonQueryAsync(ct); } if (value.Kind is PersistenceEventKind.ScheduledTaskExecutionStarted or PersistenceEventKind.ScheduledTaskExecutionCompleted) { await using var execution = new NpgsqlCommand("INSERT INTO platform.scheduled_task_execution_instances VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING", c, tx); object?[] values = [tenant, value.EndpointId, task.EntityId, value.EventId, task.InstanceId, task.Process?.ProcessEntityId, task.ExecutionResult, value.ObservedAt, json]; for (var i = 0; i < values.Length; i++) if (i == 8) execution.Parameters.Add(new() { Value = values[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else execution.Parameters.AddWithValue(values[i] ?? DBNull.Value); await execution.ExecuteNonQueryAsync(ct); } }
    static async Task UpsertConfiguration(NpgsqlConnection c, NpgsqlTransaction tx, Guid tenant, PersistenceObservation value, PersistenceConfigurationEvidence item, string json, CancellationToken ct)
    { await using (var command = new NpgsqlCommand("INSERT INTO platform.persistence_configuration_entities(tenant_id,endpoint_id,persistence_entity_id,category,subtype,native_identity,object_name,first_observed,last_observed,created_at,deleted_at,generation,current_state,latest_event) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,$9,$10,$11,$12,$13) ON CONFLICT(tenant_id,endpoint_id,persistence_entity_id) DO UPDATE SET last_observed=GREATEST(platform.persistence_configuration_entities.last_observed,EXCLUDED.last_observed),deleted_at=COALESCE(EXCLUDED.deleted_at,platform.persistence_configuration_entities.deleted_at),current_state=EXCLUDED.current_state,latest_event=CASE WHEN EXCLUDED.last_observed>=platform.persistence_configuration_entities.last_observed THEN EXCLUDED.latest_event ELSE platform.persistence_configuration_entities.latest_event END", c, tx)) { object?[] values = [tenant, value.EndpointId, item.EntityId, item.Category, item.Subtype, item.NativeObjectIdentity, item.Name, value.ObservedAt, item.CreatedAt, item.DeletedAt, item.Generation, item.CurrentState, json]; for (var i = 0; i < values.Length; i++) if (i == 12) command.Parameters.Add(new() { Value = values[i]!, NpgsqlDbType = NpgsqlDbType.Jsonb }); else command.Parameters.AddWithValue(values[i] ?? DBNull.Value); await command.ExecuteNonQueryAsync(ct); } await using (var history = new NpgsqlCommand("INSERT INTO platform.persistence_configuration_history(tenant_id,endpoint_id,persistence_entity_id,event_id,observed_at,configuration) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING", c, tx)) { object[] values = [tenant, value.EndpointId, item.EntityId, value.EventId, value.ObservedAt, JsonSerializer.Serialize(item, Json)]; for (var i = 0; i < values.Length; i++) if (i == 5) history.Parameters.Add(new() { Value = values[i], NpgsqlDbType = NpgsqlDbType.Jsonb }); else history.Parameters.AddWithValue(values[i]); await history.ExecuteNonQueryAsync(ct); } if (item.Category == "wmi-binding") { await using var binding = new NpgsqlCommand("INSERT INTO platform.persistence_wmi_relationships(tenant_id,endpoint_id,persistence_entity_id,event_id,filter_identity,consumer_identity,state,observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING", c, tx); object?[] values = [tenant, value.EndpointId, item.EntityId, value.EventId, item.FilterIdentity, item.ConsumerIdentity, item.CurrentState, value.ObservedAt]; foreach (var v in values) binding.Parameters.AddWithValue(v ?? DBNull.Value); await binding.ExecuteNonQueryAsync(ct); } }

    static async Task<PersistenceConfigurationEvidence> ResolveEvidence(NpgsqlConnection c, NpgsqlTransaction tx, Guid tenant, Guid endpoint, DateTimeOffset observed, PersistenceConfigurationEvidence item, CancellationToken ct)
    {
        var ids = new List<string>(); string? registryEntity = null, fileEntity = null;
        if (item.RegistryPath is { } registryPath)
        {
            var normalized = registryPath.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase) ? registryPath[5..] : registryPath.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase) ? registryPath[5..] : registryPath;
            await using var q = new NpgsqlCommand("SELECT event_id::text,key_entity_id FROM platform.registry_events WHERE tenant_id=$1 AND endpoint_id=$2 AND lower(right(event_data->>'keyPath',length($3)))=lower($3) AND (($5='com-registration' AND coalesce(event_data->>'valueName','')='') OR ($5<>'com-registration' AND coalesce(event_data->>'valueName','')=CASE WHEN $6='(Default)' THEN '' ELSE $6 END)) AND observed_at BETWEEN $4-interval '2 minutes' AND $4+interval '2 minutes' ORDER BY abs(extract(epoch from(observed_at-$4))) LIMIT 1", c, tx); q.Parameters.AddWithValue(tenant); q.Parameters.AddWithValue(endpoint); q.Parameters.AddWithValue(normalized); q.Parameters.AddWithValue(observed); q.Parameters.AddWithValue(item.Category); q.Parameters.AddWithValue(item.Name); await using var reader = await q.ExecuteReaderAsync(ct); if (await reader.ReadAsync(ct)) { ids.Add(reader.GetString(0)); registryEntity = reader.GetString(1); }
        }
        if (item.FilePath is { } filePath)
        {
            await using var q = new NpgsqlCommand("SELECT event_id::text,file_entity_id FROM platform.file_events WHERE tenant_id=$1 AND endpoint_id=$2 AND lower(event_data->>'currentPath')=lower($3) AND observed_at BETWEEN $4-interval '2 minutes' AND $4+interval '2 minutes' ORDER BY abs(extract(epoch from(observed_at-$4))) LIMIT 1", c, tx); q.Parameters.AddWithValue(tenant); q.Parameters.AddWithValue(endpoint); q.Parameters.AddWithValue(filePath); q.Parameters.AddWithValue(observed); await using var reader = await q.ExecuteReaderAsync(ct); if (await reader.ReadAsync(ct)) { ids.Add(reader.GetString(0)); fileEntity = reader.GetString(1); }
        }
        return item with { RawEvidenceEventIds = ids.ToArray(), RegistryEntityId = registryEntity, FileEntityId = fileEntity, RelationshipConfidence = ids.Count > 0 ? "high" : item.RelationshipConfidence, RelationshipAmbiguous = ids.Count == 0 && (item.RegistryPath is not null || item.FilePath is not null) };
    }
    public async Task<int> ReconcileEvidenceAsync(int limit, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct);
        var candidates = new List<(Guid Tenant, PersistenceObservation Event)>();
        await using (var q = new NpgsqlCommand("SELECT tenant_id,event_data FROM platform.persistence_events WHERE object_kind='PersistenceConfiguration' AND jsonb_array_length(COALESCE(event_data#>'{configuration,rawEvidenceEventIds}','[]'::jsonb))=0 AND (event_data#>>'{configuration,registryPath}' IS NOT NULL OR event_data#>>'{configuration,filePath}' IS NOT NULL) ORDER BY observed_at DESC LIMIT $1 FOR UPDATE SKIP LOCKED", c, tx))
        { q.Parameters.AddWithValue(Math.Clamp(limit, 1, 500)); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) candidates.Add((reader.GetGuid(0), JsonSerializer.Deserialize<PersistenceObservation>(reader.GetString(1), Json)!)); }
        var changed = 0;
        foreach (var candidate in candidates)
        {
            var resolved = await ResolveEvidence(c, tx, candidate.Tenant, candidate.Event.EndpointId, candidate.Event.ObservedAt, candidate.Event.Configuration!, ct);
            if (resolved.RawEvidenceEventIds.Length == 0) continue;
            var flags = candidate.Event.DataQualityFlags.Where(x => x is not "raw-evidence-reference-resolution-pending" and not "raw-evidence-reference-not-observed").Distinct(StringComparer.Ordinal).ToArray();
            var value = candidate.Event with { Configuration = resolved with { RelationshipAmbiguous = false }, DataQualityFlags = flags, QualityState = flags.Length == 0 ? "complete" : "partial" };
            var json = JsonSerializer.Serialize(value, Json); var configuration = JsonSerializer.Serialize(value.Configuration, Json);
            await using (var update = new NpgsqlCommand("UPDATE platform.persistence_events SET event_data=$1,data_quality_flags=$2 WHERE tenant_id=$3 AND event_id=$4", c, tx))
            { update.Parameters.Add(new() { Value = json, NpgsqlDbType = NpgsqlDbType.Jsonb }); update.Parameters.AddWithValue(flags); update.Parameters.AddWithValue(candidate.Tenant); update.Parameters.AddWithValue(value.EventId); await update.ExecuteNonQueryAsync(ct); }
            await using (var updateHistory = new NpgsqlCommand("UPDATE platform.persistence_configuration_history SET configuration=$1 WHERE tenant_id=$2 AND event_id=$3", c, tx))
            { updateHistory.Parameters.Add(new() { Value = configuration, NpgsqlDbType = NpgsqlDbType.Jsonb }); updateHistory.Parameters.AddWithValue(candidate.Tenant); updateHistory.Parameters.AddWithValue(value.EventId); await updateHistory.ExecuteNonQueryAsync(ct); }
            await using (var updateEntity = new NpgsqlCommand("UPDATE platform.persistence_configuration_entities SET latest_event=$1 WHERE tenant_id=$2 AND endpoint_id=$3 AND persistence_entity_id=$4 AND latest_event->>'eventId'=$5", c, tx))
            { updateEntity.Parameters.Add(new() { Value = json, NpgsqlDbType = NpgsqlDbType.Jsonb }); updateEntity.Parameters.AddWithValue(candidate.Tenant); updateEntity.Parameters.AddWithValue(value.EndpointId); updateEntity.Parameters.AddWithValue(value.Configuration!.EntityId); updateEntity.Parameters.AddWithValue(value.EventId.ToString()); await updateEntity.ExecuteNonQueryAsync(ct); }
            await using var outbox = new NpgsqlCommand("INSERT INTO platform.outbox(id,tenant_id,topic,subject,message,trace_id) VALUES($1,$2,'persistence.changed','persistence.telemetry.v1',$3,'')", c, tx); outbox.Parameters.AddWithValue(Guid.NewGuid()); outbox.Parameters.AddWithValue(candidate.Tenant); outbox.Parameters.Add(new() { Value = JsonSerializer.Serialize(new { tenantId = candidate.Tenant, eventId = value.EventId, endpointId = value.EndpointId }, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); await outbox.ExecuteNonQueryAsync(ct); changed++;
        }
        await tx.CommitAsync(ct); return changed;
    }
    public async Task<PersistenceEventPage> SearchAsync(string tenant, PersistenceSearchRequest request, CancellationToken ct) { const string sql = "SELECT event_data FROM platform.persistence_events WHERE tenant_id=$1 AND ($2='' OR object_kind=$2) AND ($3::uuid IS NULL OR endpoint_id=$3) AND ($4='' OR object_name ILIKE '%'||$4||'%') AND ($5='' OR object_path ILIKE '%'||$5||'%') AND ($6='' OR account_name ILIKE '%'||$6||'%') AND ($7='' OR state=$7) AND ($8='' OR object_type=$8) AND ($9='' OR process_entity_id=$9) AND ($10='' OR event_data->>'associatedUser'=$10) AND ($11='' OR $11=ANY(data_quality_flags)) AND ($12::timestamptz IS NULL OR observed_at>=$12) AND ($13::timestamptz IS NULL OR observed_at<=$13) AND ($15='' OR event_data#>>'{configuration,category}'=$15) AND ($16='' OR event_data#>>'{configuration,subtype}'=$16) AND ($17='' OR event_data#>>'{configuration,scope}'=$17) AND ($18='' OR event_data#>>'{configuration,namespaceOrLocation}' ILIKE '%'||$18||'%') AND ($19='' OR event_data#>>'{configuration,consumerMetadata}' ILIKE '%'||$19||'%') ORDER BY observed_at DESC,event_id DESC LIMIT $14"; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); object?[] values = [Guid.Parse(tenant), request.ObjectKind?.ToString() ?? "", request.EndpointId, request.Name ?? "", request.Path ?? "", request.Account ?? "", request.State ?? "", request.Type ?? "", request.Process ?? "", request.User ?? "", request.Quality ?? "", request.From, request.To, Math.Clamp(request.PageSize, 1, 500), request.Category ?? "", request.Subtype ?? "", request.Scope ?? "", request.Namespace ?? "", request.ConsumerType ?? ""]; foreach (var value in values) q.Parameters.AddWithValue(value ?? DBNull.Value); var list = new List<PersistenceObservation>(); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<PersistenceObservation>(reader.GetString(0), Json)!); return new(list, null); }
    public async Task<PersistenceObservation?> GetAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data FROM platform.persistence_events WHERE tenant_id=$1 AND event_id=$2", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); var value = await q.ExecuteScalarAsync(ct); return value is null ? null : JsonSerializer.Deserialize<PersistenceObservation>((string)value, Json); }
    public async Task<PersistenceEventPage> EntityHistoryAsync(string tenant, Guid endpoint, string entityId, int limit, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data FROM platform.persistence_events WHERE tenant_id=$1 AND endpoint_id=$2 AND entity_id=$3 ORDER BY observed_at DESC,event_id DESC LIMIT $4", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint); q.Parameters.AddWithValue(entityId); q.Parameters.AddWithValue(Math.Clamp(limit, 1, 500)); var list = new List<PersistenceObservation>(); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<PersistenceObservation>(reader.GetString(0), Json)!); return new(list, null); }
    public async Task<PersistenceTelemetryHealth?> HealthAsync(string tenant, Guid endpoint, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT health_data FROM platform.persistence_telemetry_health WHERE tenant_id=$1 AND endpoint_id=$2", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint); var value = await q.ExecuteScalarAsync(ct); return value is null ? null : JsonSerializer.Deserialize<PersistenceTelemetryHealth>((string)value, Json); }
    public async Task<IReadOnlyList<PersistenceObservation>> ListAllAsync(CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT event_data FROM platform.persistence_events ORDER BY observed_at,event_id", c); var list = new List<PersistenceObservation>(); await using var reader = await q.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<PersistenceObservation>(reader.GetString(0), Json)!); return list; }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
