using System.Data;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresDetectionRepository : IDetectionRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly NpgsqlDataSource _data;
    public PostgresDetectionRepository(string connectionString) => _data = NpgsqlDataSource.Create(new NpgsqlConnectionStringBuilder(connectionString) { Pooling = true, MaxPoolSize = 8, Timeout = 5, CommandTimeout = 30 }.ConnectionString);

    public async Task<IReadOnlyList<DetectionDefinition>> ListRulesAsync(string tenant, CancellationToken ct)
    {
        const string sql = "SELECT v.definition,v.status,v.validation_passed,v.activated_at,v.deactivated_at,v.validation_result FROM platform.detection_definitions d JOIN platform.detection_definition_versions v ON v.tenant_id=d.tenant_id AND v.detection_id=d.detection_id AND v.detection_version=d.current_version WHERE d.tenant_id=$1 ORDER BY d.name";
        return await ReadRules(tenant, sql, null, ct);
    }
    public async Task<IReadOnlyList<DetectionDefinition>> RuleHistoryAsync(string tenant, Guid id, CancellationToken ct)
    {
        const string sql = "SELECT definition,status,validation_passed,activated_at,deactivated_at,validation_result FROM platform.detection_definition_versions WHERE tenant_id=$1 AND detection_id=$2 ORDER BY detection_version DESC";
        return await ReadRules(tenant, sql, id, ct);
    }
    public async Task<DetectionDefinition?> GetRuleAsync(string tenant, Guid id, int? version, CancellationToken ct)
    {
        var values = await RuleHistoryAsync(tenant, id, ct); return version is null ? values.Count == 0 ? null : values[0] : values.FirstOrDefault(x => x.DetectionVersion == version);
    }
    async Task<IReadOnlyList<DetectionDefinition>> ReadRules(string tenant, string sql, Guid? id, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); q.Parameters.AddWithValue(Guid.Parse(tenant)); if (id is not null) q.Parameters.AddWithValue(id.Value); var list = new List<DetectionDefinition>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) { var value = JsonSerializer.Deserialize<DetectionDefinition>(r.GetString(0), Json)!; using var validation = JsonDocument.Parse(r.GetString(5)); var validatedAt = validation.RootElement.TryGetProperty("validatedAt", out var at) && at.TryGetDateTimeOffset(out var parsed) ? parsed : (DateTimeOffset?)null; list.Add(value with { Status = Enum.Parse<DetectionRuleStatus>(r.GetString(1), true), Enabled = r.GetString(1).Equals("Active", StringComparison.OrdinalIgnoreCase), LastValidationPassed = r.GetBoolean(2), LastValidatedAt = validatedAt, ActivatedAt = r.IsDBNull(3) ? null : r.GetFieldValue<DateTimeOffset>(3), DeactivatedAt = r.IsDBNull(4) ? null : r.GetFieldValue<DateTimeOffset>(4) }); }
        return list;
    }
    public async Task<DetectionDefinition> CreateRuleAsync(string tenant, string actor, DetectionDefinition definition, CancellationToken ct)
    {
        var id = definition.DetectionId == Guid.Empty ? Guid.NewGuid() : definition.DetectionId; return await InsertVersion(tenant, actor, definition, id, 1, true, ct);
    }
    public async Task<DetectionDefinition> CreateVersionAsync(string tenant, string actor, Guid id, DetectionDefinition definition, CancellationToken ct)
    {
        var history = await RuleHistoryAsync(tenant, id, ct); if (history.Count == 0) throw new KeyNotFoundException(); return await InsertVersion(tenant, actor, definition, id, history.Max(x => x.DetectionVersion) + 1, false, ct);
    }
    async Task<DetectionDefinition> InsertVersion(string tenant, string actor, DetectionDefinition input, Guid id, int version, bool create, CancellationToken ct)
    {
        var now = DateTimeOffset.UtcNow; var value = input with { SchemaVersion = "detection-rule.v1", TenantId = tenant, DetectionId = id, DetectionVersion = version, Status = DetectionRuleStatus.Draft, Enabled = false, Author = actor, CreatedAt = now, UpdatedAt = now, LastValidationPassed = false, LastValidatedAt = null, ActivatedAt = null, DeactivatedAt = null }; var json = JsonSerializer.Serialize(value, Json); var hash = DetectionDsl.Hash(value);
        await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(IsolationLevel.Serializable, ct);
        if (create) { await using var d = new NpgsqlCommand("INSERT INTO platform.detection_definitions VALUES($1,$2,$3,$4,'Draft',false,$5,$5)", c, tx); object[] values = [Guid.Parse(tenant), id, value.Name, version, now]; foreach (var x in values) d.Parameters.AddWithValue(x); try { await d.ExecuteNonQueryAsync(ct); } catch (PostgresException e) when (e.SqlState == PostgresErrorCodes.UniqueViolation) { throw new EnrollmentConflictException("DETECTION_EXISTS", "Detection identity or name already exists in this tenant."); } }
        else { await using var d = new NpgsqlCommand("UPDATE platform.detection_definitions SET current_version=$3,name=$4,status='Draft',enabled=false,updated_at=$5 WHERE tenant_id=$1 AND detection_id=$2", c, tx); object[] values = [Guid.Parse(tenant), id, version, value.Name, now]; foreach (var x in values) d.Parameters.AddWithValue(x); if (await d.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); }
        await using (var q = new NpgsqlCommand("INSERT INTO platform.detection_definition_versions(tenant_id,detection_id,detection_version,status,definition,definition_sha256,created_at,created_by) VALUES($1,$2,$3,'Draft',$4,$5,$6,$7)", c, tx)) { q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(version); AddJson(q, json); q.Parameters.AddWithValue(hash); q.Parameters.AddWithValue(now); q.Parameters.AddWithValue(actor); await q.ExecuteNonQueryAsync(ct); }
        await Audit(c, tx, tenant, actor, create ? "detection.created" : "detection.version.created", id, version, ct); await tx.CommitAsync(ct); return value;
    }
    public async Task<DetectionDefinition> RecordValidationAsync(string tenant, Guid id, int version, IReadOnlyDictionary<string, string[]> errors, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.detection_definition_versions SET validation_passed=$4,validation_result=$5,status=$6 WHERE tenant_id=$1 AND detection_id=$2 AND detection_version=$3", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(version); q.Parameters.AddWithValue(errors.Count == 0); AddJson(q, JsonSerializer.Serialize(new { errors, validatedAt = DateTimeOffset.UtcNow }, Json)); q.Parameters.AddWithValue(errors.Count == 0 ? "Testing" : "Draft"); if (await q.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); return (await GetRuleAsync(tenant, id, version, ct))!;
    }
    public async Task RecordTestsAsync(string tenant, Guid id, int version, IReadOnlyList<(DetectionRuleTestCase Test, DetectionRuleTestResult Result)> tests, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); foreach (var pair in tests) { await using var q = new NpgsqlCommand("INSERT INTO platform.detection_rule_tests VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(tenant_id,detection_id,detection_version,fixture_name) DO UPDATE SET passed=EXCLUDED.passed,expected_findings=EXCLUDED.expected_findings,actual_findings=EXCLUDED.actual_findings,result=EXCLUDED.result,completed_at=EXCLUDED.completed_at", c, tx); object[] values = [Guid.Parse(tenant), id, version, pair.Test.Name, pair.Test.Kind, "detection-fixture.v1", pair.Result.Passed, pair.Result.ExpectedFindings, pair.Result.ActualFindings]; foreach (var x in values) q.Parameters.AddWithValue(x); AddJson(q, JsonSerializer.Serialize(pair.Result, Json)); q.Parameters.AddWithValue(pair.Result.CompletedAt); await q.ExecuteNonQueryAsync(ct); }
        await tx.CommitAsync(ct);
    }
    public async Task<IReadOnlyList<(string Name, string Kind, DetectionRuleTestResult Result)>> ListTestsAsync(string tenant, Guid id, int version, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT fixture_name,fixture_kind,result FROM platform.detection_rule_tests WHERE tenant_id=$1 AND detection_id=$2 AND detection_version=$3 ORDER BY fixture_name", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(version); var list = new List<(string, string, DetectionRuleTestResult)>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add((r.GetString(0), r.GetString(1), JsonSerializer.Deserialize<DetectionRuleTestResult>(r.GetString(2), Json)!)); return list;
    }
    public async Task<DetectionDefinition> ActivateAsync(string tenant, string actor, Guid id, int version, CancellationToken ct)
    {
        var rule = await GetRuleAsync(tenant, id, version, ct) ?? throw new KeyNotFoundException(); var tests = await ListTestsAsync(tenant, id, version, ct); string[] required = rule.Suppression.DurationMinutes > 0 ? ["positive", "negative", "boundary", "missing-field", "exclusion", "suppression"] : ["positive", "negative", "boundary", "missing-field", "exclusion"]; if (!rule.LastValidationPassed || required.Any(kind => !tests.Any(x => x.Kind == kind && x.Result.Passed)) || tests.Any(x => !x.Result.Passed)) throw new EnrollmentConflictException("DETECTION_ACTIVATION_BLOCKED", "Validation and every required fixture must pass before activation.");
        var now = DateTimeOffset.UtcNow; await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(IsolationLevel.Serializable, ct); await using (var old = new NpgsqlCommand("UPDATE platform.detection_definition_versions SET status='Disabled',deactivated_at=$3 WHERE tenant_id=$1 AND detection_id=$2 AND status='Active'", c, tx)) { old.Parameters.AddWithValue(Guid.Parse(tenant)); old.Parameters.AddWithValue(id); old.Parameters.AddWithValue(now); await old.ExecuteNonQueryAsync(ct); }
        await using (var q = new NpgsqlCommand("UPDATE platform.detection_definition_versions SET status='Active',activated_at=$4,deactivated_at=NULL WHERE tenant_id=$1 AND detection_id=$2 AND detection_version=$3 AND validation_passed=true", c, tx)) { q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(version); q.Parameters.AddWithValue(now); if (await q.ExecuteNonQueryAsync(ct) == 0) throw new EnrollmentConflictException("DETECTION_ACTIVATION_BLOCKED", "Validated rule version was not found."); }
        await using (var d = new NpgsqlCommand("UPDATE platform.detection_definitions SET current_version=$3,status='Active',enabled=true,updated_at=$4 WHERE tenant_id=$1 AND detection_id=$2", c, tx)) { Parameters(d, Guid.Parse(tenant), id, version, now); await d.ExecuteNonQueryAsync(ct); }
        await Audit(c, tx, tenant, actor, "detection.activated", id, version, ct); await tx.CommitAsync(ct); return (await GetRuleAsync(tenant, id, version, ct))!;
    }
    public async Task<DetectionDefinition> DisableAsync(string tenant, string actor, Guid id, CancellationToken ct)
    {
        var now = DateTimeOffset.UtcNow; await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); await using (var q = new NpgsqlCommand("UPDATE platform.detection_definition_versions SET status='Disabled',deactivated_at=$3 WHERE tenant_id=$1 AND detection_id=$2 AND status='Active'", c, tx)) { q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(id); q.Parameters.AddWithValue(now); await q.ExecuteNonQueryAsync(ct); }
        await using (var d = new NpgsqlCommand("UPDATE platform.detection_definitions SET status='Disabled',enabled=false,updated_at=$3 WHERE tenant_id=$1 AND detection_id=$2", c, tx)) { Parameters(d, Guid.Parse(tenant), id, now); if (await d.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); }
        await Audit(c, tx, tenant, actor, "detection.disabled", id, null, ct); await tx.CommitAsync(ct); return (await GetRuleAsync(tenant, id, null, ct))!;
    }
    public async Task<DetectionAssignment> AssignAsync(string tenant, string actor, DetectionAssignment input, CancellationToken ct)
    {
        var value = input with { Id = input.Id == Guid.Empty ? Guid.NewGuid() : input.Id, TenantId = tenant, CreatedAt = DateTimeOffset.UtcNow, CreatedBy = actor }; await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.detection_assignments VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", c, tx); object?[] values = [Guid.Parse(tenant), value.Id, value.DetectionId, value.DetectionVersion, value.EndpointId, value.EndpointGroupId, value.Enabled, value.CreatedAt, actor]; foreach (var x in values) q.Parameters.AddWithValue(x ?? DBNull.Value); try { await q.ExecuteNonQueryAsync(ct); } catch (PostgresException) { throw new EnrollmentConflictException("DETECTION_ASSIGNMENT_INVALID", "Rule version or target is invalid for this tenant."); }
        await Audit(c, tx, tenant, actor, "detection.assignment.created", value.DetectionId, value.DetectionVersion, ct); await tx.CommitAsync(ct); return value;
    }
    public async Task<DetectionExclusion> CreateExclusionAsync(string tenant, string actor, DetectionExclusion input, CancellationToken ct)
    {
        FileDetectionRepository.ValidateExclusion(input); if (!Enum.GetValues<DetectionDomain>().SelectMany(DetectionDsl.AllowedFields).Contains(input.Field, StringComparer.Ordinal)) throw new EnrollmentConflictException("DETECTION_EXCLUSION_FIELD_INVALID", "Exclusion field is not allowlisted."); var value = input with { Id = input.Id == Guid.Empty ? Guid.NewGuid() : input.Id, TenantId = tenant, Version = 1, CreatedBy = actor }; await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.detection_exclusions(tenant_id,id,version,name,field_name,field_value,case_insensitive,starts_at,ends_at,reason,created_by,elevated_match_all_confirmation) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)", c, tx); object[] values = [Guid.Parse(tenant), value.Id, value.Version, value.Name, value.Field, value.Value, value.CaseInsensitive, value.StartsAt, value.EndsAt, value.Reason, actor, value.ElevatedMatchAllConfirmation]; foreach (var x in values) q.Parameters.AddWithValue(x); await q.ExecuteNonQueryAsync(ct); await Audit(c, tx, tenant, actor, "detection.exclusion.created", value.Id, 1, ct); await tx.CommitAsync(ct); return value;
    }
    public async Task<IReadOnlyList<DetectionExclusion>> ListExclusionsAsync(string tenant, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT id,version,name,field_name,field_value,case_insensitive,starts_at,ends_at,reason,created_by,elevated_match_all_confirmation,match_count FROM platform.detection_exclusions WHERE tenant_id=$1 ORDER BY created_at DESC", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); var list = new List<DetectionExclusion>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(new(r.GetGuid(0), tenant, r.GetInt32(1), r.GetString(2), r.GetString(3), r.GetString(4), r.GetBoolean(5), r.GetFieldValue<DateTimeOffset>(6), r.GetFieldValue<DateTimeOffset>(7), r.GetString(8), r.GetString(9), r.GetBoolean(10), r.GetInt64(11))); return list;
    }

    public async Task<DetectionEvaluationResult> EvaluateAsync(string tenant, DetectionEvidenceEvent evidence, DetectionExecutionMode mode, Guid? id, int? version, Guid? runId, bool production, CancellationToken ct)
    {
        if (tenant != evidence.TenantId) throw new EnrollmentConflictException("DETECTION_TENANT_MISMATCH", "Evidence tenant binding is invalid."); var rules = (id is null ? await ActiveRules(tenant, evidence.EndpointId, ct) : (await RuleHistoryAsync(tenant, id.Value, ct)).Where(x => version is null || x.DetectionVersion == version).Take(1).ToArray()).Where(x => x.Domain == evidence.Domain).ToArray();
        if (rules.Length == 0) return new(false, false, false, new(false, [], [], "none"), null, "no-applicable-rule");
        var evaluations = rules.Select(rule => (Rule: rule, Evaluation: DetectionDsl.Evaluate(rule, evidence))).ToArray();
        if (id is null && evaluations.All(x => !x.Evaluation.Matched))
            return await RecordNonMatches(tenant, evidence, mode, runId, evaluations, ct);
        DetectionEvaluationResult? last = null; foreach (var rule in rules) last = await EvaluateRule(tenant, rule, evidence, mode, runId, production, ct); return last!;
    }
    async Task<DetectionEvaluationResult> RecordNonMatches(string tenant, DetectionEvidenceEvent evidence, DetectionExecutionMode mode, Guid? runId, (DetectionDefinition Rule, DetectionEvaluation Evaluation)[] values, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct); var inserted = 0; var run = runId ?? Guid.Empty;
        foreach (var value in values) await using (var duplicate = new NpgsqlCommand("INSERT INTO platform.detection_processed_events(tenant_id,detection_id,detection_version,event_id,mode,run_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING", c, tx)) { Parameters(duplicate, Guid.Parse(tenant), value.Rule.DetectionId, value.Rule.DetectionVersion, evidence.EventId, mode.ToString(), run); inserted += await duplicate.ExecuteNonQueryAsync(ct); }
        if (inserted > 0) await HealthIncrement(c, tx, tenant, inserted, inserted, 0, 0, 0, 0, values.Sum(x => x.Evaluation.MissingFields.Length), inserted * (evidence.MissingTelemetry?.Length ?? 0), ct);
        await tx.CommitAsync(ct); var evaluation = values[^1].Evaluation; return new(inserted == 0, false, false, evaluation, null, inserted == 0 ? "duplicate-event" : "conditions-not-matched");
    }
    async Task<IReadOnlyList<DetectionDefinition>> ActiveRules(string tenant, Guid? endpoint, CancellationToken ct)
    {
        const string sql = "SELECT DISTINCT v.definition,v.status,v.validation_passed,v.activated_at,v.deactivated_at FROM platform.detection_definition_versions v JOIN platform.detection_assignments a ON a.tenant_id=v.tenant_id AND a.detection_id=v.detection_id AND a.detection_version=v.detection_version AND a.enabled WHERE v.tenant_id=$1 AND v.status='Active' AND(a.endpoint_id IS NULL OR a.endpoint_id=$2)"; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(endpoint ?? (object)DBNull.Value); var list = new List<DetectionDefinition>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) { var value = JsonSerializer.Deserialize<DetectionDefinition>(r.GetString(0), Json)!; list.Add(value with { Status = DetectionRuleStatus.Active, Enabled = true, LastValidationPassed = true, ActivatedAt = r.IsDBNull(3) ? null : r.GetFieldValue<DateTimeOffset>(3) }); }
        return list;
    }
    async Task<DetectionEvaluationResult> EvaluateRule(string tenant, DetectionDefinition rule, DetectionEvidenceEvent evidence, DetectionExecutionMode mode, Guid? runId, bool production, CancellationToken ct)
    {
        const int maximumAttempts = 8;
        for (var attempt = 1; ; attempt++)
        {
            try
            {
                return await EvaluateRuleOnce(tenant, rule, evidence, mode, runId, production, ct);
            }
            catch (PostgresException exception) when (exception.SqlState == "40001" && attempt < maximumAttempts)
            {
                // Keep a bounded retry for transient database serialization
                // failures outside the rule-scoped evaluation lock.
                var ceiling = Math.Min(250, 1 << attempt);
                await Task.Delay(Random.Shared.Next(1, ceiling + 1), ct);
            }
        }
    }
    async Task<DetectionEvaluationResult> EvaluateRuleOnce(string tenant, DetectionDefinition rule, DetectionEvidenceEvent evidence, DetectionExecutionMode mode, Guid? runId, bool production, CancellationToken ct)
    {
        var evaluation = DetectionDsl.Evaluate(rule, evidence); await using var c = await _data.OpenConnectionAsync(ct);
        await using var tx = await c.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct);
        var run = runId ?? Guid.Empty;
        await using (var duplicate = new NpgsqlCommand("INSERT INTO platform.detection_processed_events(tenant_id,detection_id,detection_version,event_id,mode,run_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING", c, tx)) { Parameters(duplicate, Guid.Parse(tenant), rule.DetectionId, rule.DetectionVersion, evidence.EventId, mode.ToString(), run); if (await duplicate.ExecuteNonQueryAsync(ct) == 0) { await tx.RollbackAsync(ct); return new(true, false, false, evaluation, null, "duplicate-event"); } }
        if (!evaluation.Matched) { await HealthIncrement(c, tx, tenant, 1, 1, 0, 0, 0, 0, evaluation.MissingFields.Length, evidence.MissingTelemetry?.Length ?? 0, ct); await tx.CommitAsync(ct); return new(false, false, false, evaluation, null, "conditions-not-matched"); }
        // Only matched rules touch shared threshold/suppression state. Taking the
        // rule-scoped lock for every non-match serialized unrelated telemetry and
        // made durable replay unbounded without adding correctness.
        await using (var gate = new NpgsqlCommand("SELECT pg_advisory_xact_lock(hashtextextended($1,0))", c, tx))
        {
            gate.Parameters.AddWithValue($"{tenant}:{rule.DetectionId:D}");
            await gate.ExecuteNonQueryAsync(ct);
        }
        var exclusion = await MatchingExclusion(c, tx, tenant, rule, evidence, ct); if (exclusion is not null) { await using var u = new NpgsqlCommand("UPDATE platform.detection_exclusions SET match_count=match_count+1 WHERE tenant_id=$1 AND id=$2", c, tx); Parameters(u, Guid.Parse(tenant), exclusion.Id); await u.ExecuteNonQueryAsync(ct); await HealthIncrement(c, tx, tenant, 1, 1, 1, 0, 0, 1, evaluation.MissingFields.Length, evidence.MissingTelemetry?.Length ?? 0, ct); await tx.CommitAsync(ct); return new(false, true, false, evaluation, null, exclusion.Reason); }
        var scope = $"{mode}:{run:D}"; var expiry = evidence.EventTime.AddSeconds(Math.Max(1, rule.WindowSeconds)); if (rule.RuleType == DetectionRuleType.Threshold) await using (var w = new NpgsqlCommand("INSERT INTO platform.detection_window_events(tenant_id,detection_id,detection_version,evaluation_scope,group_key,event_id,event_time,distinct_value,evidence,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING", c, tx)) { Parameters(w, Guid.Parse(tenant), rule.DetectionId, rule.DetectionVersion, scope, evaluation.GroupKey, evidence.EventId, evidence.EventTime, rule.DistinctField is null ? DBNull.Value : evidence.Fields.GetValueOrDefault(rule.DistinctField) ?? (object)DBNull.Value); AddJson(w, JsonSerializer.Serialize(evidence, Json)); w.Parameters.AddWithValue(expiry); await w.ExecuteNonQueryAsync(ct); }
        await using (var clean = new NpgsqlCommand("DELETE FROM platform.detection_window_events WHERE tenant_id=$1 AND expires_at<$2", c, tx)) { Parameters(clean, Guid.Parse(tenant), evidence.EventTime); await clean.ExecuteNonQueryAsync(ct); }
        var candidates = new List<DetectionEvidenceEvent>(); if (rule.RuleType == DetectionRuleType.Threshold) await using (var select = new NpgsqlCommand("SELECT evidence FROM platform.detection_window_events WHERE tenant_id=$1 AND detection_id=$2 AND detection_version=$3 AND evaluation_scope=$4 AND group_key=$5 AND event_time BETWEEN $6 AND $7 ORDER BY event_time,event_id", c, tx)) { Parameters(select, Guid.Parse(tenant), rule.DetectionId, rule.DetectionVersion, scope, evaluation.GroupKey, evidence.EventTime.AddSeconds(-Math.Max(1, rule.WindowSeconds)), evidence.EventTime); await using var r = await select.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) candidates.Add(JsonSerializer.Deserialize<DetectionEvidenceEvent>(r.GetString(0), Json)!); } else candidates.Add(evidence);
        var count = rule.DistinctCount ? candidates.Select(x => x.Fields.GetValueOrDefault(rule.DistinctField!)).Where(x => x is not null).Distinct(StringComparer.Ordinal).Count() : candidates.Count; if (count != rule.Threshold) { await HealthIncrement(c, tx, tenant, 1, 1, 1, 0, 0, 0, evaluation.MissingFields.Length, evidence.MissingTelemetry?.Length ?? 0, ct); await tx.CommitAsync(ct); return new(false, false, false, evaluation, null, "threshold-not-crossed"); }
        var prior = await SuppressedBy(c, tx, tenant, rule, evidence, ct); var suppressed = prior is not null; var ids = candidates.Select(x => x.EventId).ToArray(); var findingId = DetectionDsl.DeterministicId($"{tenant}:{rule.DetectionId}:{rule.DetectionVersion}:{mode}:{evaluation.GroupKey}:{string.Join(',', ids)}"); var finding = new DetectionFinding(findingId, tenant, rule.DetectionId, rule.DetectionVersion, rule.Name, rule.Severity, rule.Confidence, candidates[0].EventTime, candidates[^1].EventTime, count, evaluation.GroupKey, evidence.EndpointId, evidence.ProcessEntityId, evidence.EntityId, ids, candidates.Select(x => x.EvidenceReference).ToArray(), evaluation.Conditions.Where(x => x.Matched).ToArray(), suppressed, suppressed ? "bounded-duplicate-suppression" : null, prior?.FindingId, false, null, DetectionDsl.EngineVersion, mode, candidates.SelectMany(x => x.Quality ?? []).Distinct().ToArray(), evaluation.MissingFields.Concat(candidates.SelectMany(x => x.MissingTelemetry ?? [])).Distinct().ToArray(), DateTimeOffset.UtcNow);
        var persist = production && mode is DetectionExecutionMode.Live or DetectionExecutionMode.HistoricalReplay; if (persist) { var json = JsonSerializer.Serialize(finding, Json); await using (var insert = new NpgsqlCommand("INSERT INTO platform.detection_findings VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,1) ON CONFLICT DO NOTHING", c, tx)) { object?[] values = [Guid.Parse(tenant), finding.FindingId, finding.DetectionId, finding.DetectionVersion, finding.Severity, finding.Confidence, finding.FirstSeen, finding.LastSeen, finding.EventCount, finding.GroupKey, finding.EndpointId, finding.ProcessEntityId, finding.EntityId, finding.Suppressed, finding.Excluded, finding.ExecutionMode.ToString()]; foreach (var x in values) insert.Parameters.AddWithValue(x ?? DBNull.Value); AddJson(insert, json); insert.Parameters.AddWithValue(finding.CreatedAt); await insert.ExecuteNonQueryAsync(ct); } await using (var history = new NpgsqlCommand("INSERT INTO platform.detection_finding_history(tenant_id,finding_id,action,actor,occurred_at,data) VALUES($1,$2,'created','system:detection-engine',now(),$3)", c, tx)) { Parameters(history, Guid.Parse(tenant), finding.FindingId); AddJson(history, json); await history.ExecuteNonQueryAsync(ct); } await using (var outbox = new NpgsqlCommand("INSERT INTO platform.outbox(id,tenant_id,topic,subject,message,trace_id) VALUES($1,$2,'finding.changed','detection.finding.v1',$3,'')", c, tx)) { outbox.Parameters.AddWithValue(Guid.NewGuid()); outbox.Parameters.AddWithValue(Guid.Parse(tenant)); AddJson(outbox, JsonSerializer.Serialize(new { tenantId = tenant, findingId = finding.FindingId, endpointId = finding.EndpointId }, Json)); await outbox.ExecuteNonQueryAsync(ct); } }
        await HealthIncrement(c, tx, tenant, 1, 1, 1, persist ? 1 : 0, suppressed ? 1 : 0, 0, evaluation.MissingFields.Length, evidence.MissingTelemetry?.Length ?? 0, ct); await tx.CommitAsync(ct); return new(false, false, suppressed, evaluation, finding, suppressed ? "suppressed" : null);
    }
    static async Task<DetectionExclusion?> MatchingExclusion(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, DetectionDefinition rule, DetectionEvidenceEvent evidence, CancellationToken ct)
    {
        if (rule.ExclusionReferences.Length == 0) return null; await using var q = new NpgsqlCommand("SELECT id,version,name,field_name,field_value,case_insensitive,starts_at,ends_at,reason,created_by,elevated_match_all_confirmation,match_count FROM platform.detection_exclusions WHERE tenant_id=$1 AND id=ANY($2) AND starts_at<=$3 AND ends_at>=$3", c, tx); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(rule.ExclusionReferences); q.Parameters.AddWithValue(evidence.EventTime); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) { var value = new DetectionExclusion(r.GetGuid(0), tenant, r.GetInt32(1), r.GetString(2), r.GetString(3), r.GetString(4), r.GetBoolean(5), r.GetFieldValue<DateTimeOffset>(6), r.GetFieldValue<DateTimeOffset>(7), r.GetString(8), r.GetString(9), r.GetBoolean(10), r.GetInt64(11)); if (DetectionDsl.MatchesExclusion(value, evidence, evidence.EventTime)) return value; }
        return null;
    }
    static async Task<DetectionFinding?> SuppressedBy(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, DetectionDefinition rule, DetectionEvidenceEvent evidence, CancellationToken ct)
    {
        if (rule.Suppression.DurationMinutes <= 0) return null; var field = rule.Suppression.Scope switch { "detection+process" => "process_entity_id", "detection+entity" => "entity_id", _ => "endpoint_id::text" }; var scope = rule.Suppression.Scope switch { "detection+process" => evidence.ProcessEntityId, "detection+entity" => evidence.EntityId, _ => evidence.EndpointId?.ToString("D") }; if (scope is null) return null; await using var q = new NpgsqlCommand($"SELECT finding_data FROM platform.detection_findings WHERE tenant_id=$1 AND detection_id=$2 AND {field}=$3 AND created_at>=$4 ORDER BY created_at DESC LIMIT 1", c, tx); q.Parameters.AddWithValue(Guid.Parse(tenant)); q.Parameters.AddWithValue(rule.DetectionId); q.Parameters.AddWithValue(scope); q.Parameters.AddWithValue(evidence.EventTime.AddMinutes(-rule.Suppression.DurationMinutes)); var result = await q.ExecuteScalarAsync(ct); return result is string json ? JsonSerializer.Deserialize<DetectionFinding>(json, Json) : null;
    }
    static async Task HealthIncrement(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, int events, int rules, int matches, int findings, int suppressed, int excluded, int missingFields, int missingTelemetry, CancellationToken ct)
    {
        await using var q = new NpgsqlCommand("INSERT INTO platform.detection_health VALUES($1,$2,now()) ON CONFLICT(tenant_id) DO UPDATE SET health_data=jsonb_build_object('eventsEvaluated',COALESCE((platform.detection_health.health_data->>'eventsEvaluated')::bigint,0)+$3,'rulesEvaluated',COALESCE((platform.detection_health.health_data->>'rulesEvaluated')::bigint,0)+$4,'matches',COALESCE((platform.detection_health.health_data->>'matches')::bigint,0)+$5,'findings',COALESCE((platform.detection_health.health_data->>'findings')::bigint,0)+$6,'suppressed',COALESCE((platform.detection_health.health_data->>'suppressed')::bigint,0)+$7,'excluded',COALESCE((platform.detection_health.health_data->>'excluded')::bigint,0)+$8,'missingFields',COALESCE((platform.detection_health.health_data->>'missingFields')::bigint,0)+$9,'missingTelemetry',COALESCE((platform.detection_health.health_data->>'missingTelemetry')::bigint,0)+$10),updated_at=now()", c, tx); q.Parameters.AddWithValue(Guid.Parse(tenant)); AddJson(q, "{}"); Parameters(q, events, rules, matches, findings, suppressed, excluded, missingFields, missingTelemetry); await q.ExecuteNonQueryAsync(ct);
    }
    public async Task<DetectionFindingPage> SearchFindingsAsync(string tenant, DetectionFindingQuery query, CancellationToken ct)
    {
        if (!string.IsNullOrWhiteSpace(query.Cursor)) throw new EnrollmentConflictException("DETECTION_CURSOR_INVALID", "Finding cursor is invalid or unsupported.");
        const string sql = "SELECT finding_data FROM platform.detection_findings WHERE tenant_id=$1 AND($2::uuid IS NULL OR detection_id=$2) AND($3::uuid IS NULL OR endpoint_id=$3) AND($4::int IS NULL OR severity>=$4) AND($5::boolean IS NULL OR suppressed=$5) AND($6='' OR execution_mode=$6) AND($7::timestamptz IS NULL OR created_at>=$7) AND($8::timestamptz IS NULL OR created_at<=$8) ORDER BY created_at DESC,finding_id DESC LIMIT $9"; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); object?[] values = [Guid.Parse(tenant), query.DetectionId, query.EndpointId, query.MinimumSeverity, query.Suppressed, query.Mode?.ToString() ?? "", query.From, query.To, Math.Clamp(query.PageSize, 1, 500)]; foreach (var x in values) q.Parameters.AddWithValue(x ?? DBNull.Value); var list = new List<DetectionFinding>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<DetectionFinding>(r.GetString(0), Json)!); return new(list, null);
    }
    public async Task<DetectionFinding?> GetFindingAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT finding_data FROM platform.detection_findings WHERE tenant_id=$1 AND finding_id=$2", c); Parameters(q, Guid.Parse(tenant), id); var value = await q.ExecuteScalarAsync(ct); return value is string json ? JsonSerializer.Deserialize<DetectionFinding>(json, Json) : null; }
    public async Task<IReadOnlyList<DetectionFindingHistory>> FindingHistoryAsync(string tenant, Guid id, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct);
        await using var q = new NpgsqlCommand("SELECT sequence,action,actor,occurred_at,data FROM platform.detection_finding_history WHERE tenant_id=$1 AND finding_id=$2 ORDER BY sequence", c);
        Parameters(q, Guid.Parse(tenant), id);
        var values = new List<DetectionFindingHistory>();
        await using var r = await q.ExecuteReaderAsync(ct);
        while (await r.ReadAsync(ct)) values.Add(new(r.GetInt64(0), r.GetString(1), r.GetString(2), r.GetFieldValue<DateTimeOffset>(3), JsonSerializer.Deserialize<DetectionFinding>(r.GetString(4), Json)!));
        return values;
    }
    public async Task<DetectionRun> CreateRunAsync(string tenant, DetectionRun run, DetectionDefinition snapshot, CancellationToken ct)
    {
        if (run.TenantId != tenant || run.To <= run.From || run.To - run.From > TimeSpan.FromDays(7)) throw new EnrollmentConflictException("DETECTION_REPLAY_BOUNDS", "Replay must be tenant-bound and no longer than seven days."); await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.detection_runs(tenant_id,id,detection_id,detection_version,mode,from_time,to_time,status,events_total,events_evaluated,matches,findings,production_findings,created_at,definition_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)", c); Parameters(q, Guid.Parse(tenant), run.Id, run.DetectionId, run.DetectionVersion, run.Mode.ToString(), run.From, run.To, run.Status, run.EventsTotal, run.EventsEvaluated, run.Matches, run.Findings, run.ProductionFindings, run.CreatedAt); AddJson(q, JsonSerializer.Serialize(snapshot, Json)); await q.ExecuteNonQueryAsync(ct); return run;
    }
    public async Task<DetectionRun> CompleteRunAsync(string tenant, Guid id, long evaluated, long matches, long findings, string status, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.detection_runs SET status=$3,events_evaluated=$4,matches=$5,findings=$6,completed_at=now() WHERE tenant_id=$1 AND id=$2", c); Parameters(q, Guid.Parse(tenant), id, status, evaluated, matches, findings); if (await q.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); return (await GetRunAsync(tenant, id, ct))!; }
    public async Task<DetectionRun?> GetRunAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT detection_id,detection_version,mode,from_time,to_time,status,events_total,events_evaluated,matches,findings,production_findings,created_at,completed_at,error FROM platform.detection_runs WHERE tenant_id=$1 AND id=$2", c); Parameters(q, Guid.Parse(tenant), id); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(id, tenant, r.GetGuid(0), r.GetInt32(1), Enum.Parse<DetectionExecutionMode>(r.GetString(2)), r.GetFieldValue<DateTimeOffset>(3), r.GetFieldValue<DateTimeOffset>(4), r.GetString(5), r.GetInt64(6), r.GetInt64(7), r.GetInt64(8), r.GetInt64(9), r.GetBoolean(10), r.GetFieldValue<DateTimeOffset>(11), r.IsDBNull(12) ? null : r.GetFieldValue<DateTimeOffset>(12), r.IsDBNull(13) ? null : r.GetString(13)) : null; }
    public async Task<DetectionRun> CancelRunAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.detection_runs SET cancel_requested=true,status=CASE WHEN status IN('queued','running') THEN 'cancelling' ELSE status END WHERE tenant_id=$1 AND id=$2", c); Parameters(q, Guid.Parse(tenant), id); if (await q.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); return (await GetRunAsync(tenant, id, ct))!; }
    public async Task<DetectionHealth> HealthAsync(string tenant, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT health_data,updated_at,(SELECT count(*) FROM platform.detection_runs WHERE tenant_id=$1 AND status IN('queued','running','cancelling')) FROM platform.detection_health WHERE tenant_id=$1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) return new(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, DateTimeOffset.UtcNow); using var doc = JsonDocument.Parse(r.GetString(0)); long Get(string name) => doc.RootElement.TryGetProperty(name, out var value) ? value.GetInt64() : 0; return new(Get("eventsEvaluated"), Get("rulesEvaluated"), Get("matches"), Get("findings"), Get("suppressed"), Get("excluded"), Get("evaluationFailures"), Get("compileFailures"), Get("missingFields"), Get("missingTelemetry"), r.GetInt64(2), 0, 0, 0, r.GetFieldValue<DateTimeOffset>(1));
    }
    static void AddJson(NpgsqlCommand command, string value) => command.Parameters.Add(new() { Value = value, NpgsqlDbType = NpgsqlDbType.Jsonb });
    static void Parameters(NpgsqlCommand command, params object?[] values) { foreach (var value in values) command.Parameters.AddWithValue(value ?? DBNull.Value); }
    static async Task Audit(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, string actor, string action, Guid id, int? version, CancellationToken ct) { await using var q = new NpgsqlCommand("INSERT INTO platform.audit_events(id,tenant_id,occurred_at,actor,action,resource,decision,outcome,request_id,data) VALUES($1,$2,now(),$3,$4,$5,'allow','success',$6,$7)", c, tx); q.Parameters.AddWithValue(Guid.NewGuid()); q.Parameters.AddWithValue(Guid.Parse(tenant)); AddJson(q, JsonSerializer.Serialize(new { subject = actor }, Json)); q.Parameters.AddWithValue(action); AddJson(q, JsonSerializer.Serialize(new { type = "detection", id, version }, Json)); q.Parameters.AddWithValue(Guid.NewGuid().ToString("D")); AddJson(q, "{}"); await q.ExecuteNonQueryAsync(ct); }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
