using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;
namespace OpenSecurityPlatform.Infrastructure;
public sealed class PostgresNetworkPolicyRepository(string connectionString) : INetworkPolicyRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web); readonly NpgsqlDataSource _data = NpgsqlDataSource.Create(connectionString);
    public async Task<IReadOnlyList<NetworkPolicyVersion>> ListAsync(string tenant, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("SELECT id,tenant_id::text,name,version,policy::text,sha256,status,created_at,created_by FROM platform.network_policy_versions WHERE tenant_id=$1 ORDER BY name,version DESC", c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); var list = new List<NetworkPolicyVersion>(); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(Read(r)); return list; }
    public async Task<NetworkPolicyVersion> CreateAsync(string tenantId, string actor, string name, NetworkTelemetryPolicy policy, CancellationToken ct) { if (NetworkPolicyValidation.Validate(policy).Count > 0) throw new EnrollmentConflictException("NETWORK_POLICY_INVALID", "Network policy validation failed."); var tenant = Guid.Parse(tenantId); await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); int version; await using (var q = new NpgsqlCommand("SELECT COALESCE(max(version),0)+1 FROM platform.network_policy_versions WHERE tenant_id=$1 AND name=$2", c, tx)) { q.Parameters.AddWithValue(tenant); q.Parameters.AddWithValue(name); version = (int)(await q.ExecuteScalarAsync(ct) ?? 1); } var value = policy with { Version = $"network-policy.v{version}" }; var hash = NetworkEvidence.CanonicalSha256(value); var id = Guid.NewGuid(); await using (var cmd = new NpgsqlCommand("INSERT INTO platform.network_policy_versions(id,tenant_id,name,version,policy,sha256,status,created_by) VALUES($1,$2,$3,$4,$5,$6,'active',$7)", c, tx)) { cmd.Parameters.AddWithValue(id); cmd.Parameters.AddWithValue(tenant); cmd.Parameters.AddWithValue(name); cmd.Parameters.AddWithValue(version); cmd.Parameters.Add(new NpgsqlParameter { Value = JsonSerializer.Serialize(value, Json), NpgsqlDbType = NpgsqlDbType.Jsonb }); cmd.Parameters.AddWithValue(hash); cmd.Parameters.AddWithValue(actor); await cmd.ExecuteNonQueryAsync(ct); } await Audit(c, tx, tenant, actor, "network.policy.version.create", id, hash, ct); await tx.CommitAsync(ct); return new(id, tenantId, name, version, value, hash, "active", DateTimeOffset.UtcNow, actor); }
    public async Task AssignAsync(string tenantId, Guid id, Guid? endpoint, string actor, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("INSERT INTO platform.network_policy_assignments(tenant_id,endpoint_id,policy_id,assigned_by) SELECT $1,$2,id,$3 FROM platform.network_policy_versions WHERE tenant_id=$1 AND id=$4 ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,assigned_at=now(),assigned_by=EXCLUDED.assigned_by", c); cmd.Parameters.AddWithValue(Guid.Parse(tenantId)); cmd.Parameters.AddWithValue((object?)endpoint ?? DBNull.Value); cmd.Parameters.AddWithValue(actor); cmd.Parameters.AddWithValue(id); if (await cmd.ExecuteNonQueryAsync(ct) == 0) throw new EnrollmentConflictException("NETWORK_POLICY_NOT_FOUND", "Network policy not found."); await Audit(c, null, Guid.Parse(tenantId), actor, "network.policy.assign", id, endpoint?.ToString(), ct); }
    public async Task<EffectiveNetworkPolicy> EffectiveAsync(string tenant, Guid endpoint, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); const string sql = "SELECT v.id,v.tenant_id::text,v.name,v.version,v.policy::text,v.sha256,v.status,v.created_at,v.created_by,a.endpoint_id,k.policy_id,k.acknowledged_at,k.version,k.applied,k.validation_error FROM platform.network_policy_assignments a JOIN platform.network_policy_versions v ON v.tenant_id=a.tenant_id AND v.id=a.policy_id LEFT JOIN platform.network_policy_acknowledgements k ON k.tenant_id=a.tenant_id AND k.endpoint_id=$2 WHERE a.tenant_id=$1 AND (a.endpoint_id=$2 OR a.endpoint_id IS NULL) ORDER BY a.endpoint_id NULLS LAST LIMIT 1"; await using var cmd = new NpgsqlCommand(sql, c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); cmd.Parameters.AddWithValue(endpoint); await using var r = await cmd.ExecuteReaderAsync(ct); if (await r.ReadAsync(ct)) { var v = Read(r); var assigned = !r.IsDBNull(9); var matches = !r.IsDBNull(10) && r.GetGuid(10) == v.Id; DateTimeOffset? at = !matches || r.IsDBNull(11) ? null : r.GetFieldValue<DateTimeOffset>(11); int? av = !matches || r.IsDBNull(12) ? null : r.GetInt32(12); var applied = matches && !r.IsDBNull(13) && r.GetBoolean(13); return new(v, assigned ? "endpoint" : "tenant-default", endpoint, at, applied ? av : null, !applied ? av : null, !matches || r.IsDBNull(14) ? null : r.GetString(14), !matches || !applied || av != v.Version); } var fallback = new NetworkPolicyVersion(Guid.Empty, tenant, "safe-default", 1, new(), new string('0', 64), "implicit", DateTimeOffset.UnixEpoch, "system"); return new(fallback, "implicit-default", endpoint, null, null, null, null, true); }
    public async Task AcknowledgeAsync(string tenant, Guid endpoint, NetworkPolicyAcknowledgement a, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand("INSERT INTO platform.network_policy_acknowledgements(tenant_id,endpoint_id,policy_id,version,applied,validation_error,acknowledged_at) SELECT $1,$2,id,$4,$5,$6,$7 FROM platform.network_policy_versions WHERE tenant_id=$1 AND id=$3 ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,version=EXCLUDED.version,applied=EXCLUDED.applied,validation_error=EXCLUDED.validation_error,acknowledged_at=EXCLUDED.acknowledged_at", c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); cmd.Parameters.AddWithValue(endpoint); cmd.Parameters.AddWithValue(a.PolicyId); cmd.Parameters.AddWithValue(a.Version); cmd.Parameters.AddWithValue(a.Applied); cmd.Parameters.AddWithValue((object?)a.ValidationError ?? DBNull.Value); cmd.Parameters.AddWithValue(a.AcknowledgedAt); if (await cmd.ExecuteNonQueryAsync(ct) == 0) throw new EnrollmentConflictException("NETWORK_POLICY_NOT_FOUND", "Network policy not found."); }
    public async Task<NetworkPolicyVersion> RollbackAsync(string tenant, Guid id, int version, string actor, CancellationToken ct) { var source = (await ListAsync(tenant, ct)).SingleOrDefault(x => x.Id == id && x.Version == version) ?? throw new EnrollmentConflictException("NETWORK_POLICY_NOT_FOUND", "Rollback version not found."); return await CreateAsync(tenant, actor, source.Name, source.Policy, ct); }
    static NetworkPolicyVersion Read(NpgsqlDataReader r) => new(r.GetGuid(0), r.GetString(1), r.GetString(2), r.GetInt32(3), JsonSerializer.Deserialize<NetworkTelemetryPolicy>(r.GetString(4), Json)!, r.GetString(5), r.GetString(6), r.GetFieldValue<DateTimeOffset>(7), r.GetString(8));
    static async Task Audit(NpgsqlConnection c, NpgsqlTransaction? tx, Guid tenant, string actor, string action, Guid id, string? after, CancellationToken ct) { await using var cmd = new NpgsqlCommand("INSERT INTO platform.audit_events(id,tenant_id,occurred_at,actor,action,resource,decision,outcome,request_id,after_hash,data) VALUES($1,$2,now(),jsonb_build_object('subject',$3),$4,jsonb_build_object('type','network-policy','id',$5),'allow','success',$6,$7,'{}'::jsonb)", c, tx); cmd.Parameters.AddWithValue(Guid.NewGuid()); cmd.Parameters.AddWithValue(tenant); cmd.Parameters.AddWithValue(actor); cmd.Parameters.AddWithValue(action); cmd.Parameters.AddWithValue(id.ToString("D")); cmd.Parameters.AddWithValue(Guid.NewGuid().ToString("N")); cmd.Parameters.AddWithValue((object?)after ?? DBNull.Value); await cmd.ExecuteNonQueryAsync(ct); }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
