using System.Text.Json;
using Npgsql;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresFleetUpdateRepository : FileFleetUpdateRepository, IAsyncDisposable
{
    readonly NpgsqlDataSource data; static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public PostgresFleetUpdateRepository(string connectionString) => data = NpgsqlDataSource.Create(connectionString);
    async Task<IReadOnlyList<T>> Load<T>(string sql, string tenant, CancellationToken ct) { var values = new List<T>(); await using var c = await data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand(sql, c); cmd.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await cmd.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) if (JsonSerializer.Deserialize<T>(r.GetString(0), Json) is { } x) values.Add(x); return values; }
    async Task Exec(string sql, object[] values, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var cmd = new NpgsqlCommand(sql, c); foreach (var x in values) cmd.Parameters.AddWithValue(x); await cmd.ExecuteNonQueryAsync(ct); }
    protected override Task<IReadOnlyList<FleetEndpointMetadata>> LoadMetadataAsync(string t, CancellationToken ct) => Load<FleetEndpointMetadata>("SELECT data::text FROM platform.fleet_endpoint_metadata WHERE tenant_id=$1", t, ct);
    protected override Task<IReadOnlyList<FleetGroup>> LoadGroupsAsync(string t, CancellationToken ct) => Load<FleetGroup>("SELECT data::text FROM platform.fleet_groups WHERE tenant_id=$1", t, ct);
    protected override Task<IReadOnlyList<DeploymentRingPolicy>> LoadRingsAsync(string t, CancellationToken ct) => Load<DeploymentRingPolicy>("SELECT data::text FROM platform.deployment_ring_policies WHERE tenant_id=$1 ORDER BY version DESC", t, ct);
    protected override Task<IReadOnlyList<SignedAgentUpdatePackage>> LoadPackagesAsync(string t, CancellationToken ct) => Load<SignedAgentUpdatePackage>("SELECT data::text FROM platform.agent_update_packages WHERE tenant_id=$1", t, ct);
    protected override Task<IReadOnlyList<AgentUpdatePolicy>> LoadPoliciesAsync(string t, CancellationToken ct) => Load<AgentUpdatePolicy>("SELECT data::text FROM platform.agent_update_policies WHERE tenant_id=$1 ORDER BY version DESC", t, ct);
    protected override Task<IReadOnlyList<FleetRollout>> LoadRolloutsAsync(string t, CancellationToken ct) => Load<FleetRollout>("SELECT data::text FROM platform.agent_update_rollouts WHERE tenant_id=$1", t, ct);
    protected override Task<IReadOnlyList<EndpointUpdateAssignment>> LoadAssignmentsAsync(string t, CancellationToken ct) => Load<EndpointUpdateAssignment>("SELECT data::text FROM platform.agent_update_assignments WHERE tenant_id=$1", t, ct);
    protected override Task<IReadOnlyList<FleetAuditEvent>> LoadAuditsAsync(string t, CancellationToken ct) => Load<FleetAuditEvent>("SELECT data::text FROM platform.fleet_update_audit WHERE tenant_id=$1 ORDER BY occurred_at DESC LIMIT 10000", t, ct);
    protected override Task PersistMetadataAsync(FleetEndpointMetadata x, CancellationToken ct) => Exec("INSERT INTO platform.fleet_endpoint_metadata(tenant_id,endpoint_id,installation_id,ring_id,eligibility,updated_at,data) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT(tenant_id,endpoint_id) DO UPDATE SET installation_id=EXCLUDED.installation_id,ring_id=EXCLUDED.ring_id,eligibility=EXCLUDED.eligibility,updated_at=EXCLUDED.updated_at,data=EXCLUDED.data", [Guid.Parse(x.TenantId), x.EndpointId, x.InstallationId, x.RingId, x.Eligibility.ToString(), x.UpdatedAt, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistGroupAsync(FleetGroup x, CancellationToken ct) => Exec("INSERT INTO platform.fleet_groups(tenant_id,group_id,version,group_hash,updated_at,data) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(tenant_id,group_id) DO UPDATE SET version=EXCLUDED.version,group_hash=EXCLUDED.group_hash,updated_at=EXCLUDED.updated_at,data=EXCLUDED.data", [Guid.Parse(x.TenantId), x.GroupId, x.Version, x.GroupHash, x.UpdatedAt, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistRingsAsync(DeploymentRingPolicy x, CancellationToken ct) => Exec("INSERT INTO platform.deployment_ring_policies(tenant_id,policy_id,version,policy_hash,created_at,data) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT DO NOTHING", [Guid.Parse(x.TenantId), x.PolicyId, x.Version, x.PolicyHash, x.CreatedAt, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistPackageAsync(string tenant, SignedAgentUpdatePackage x, CancellationToken ct) => Exec("INSERT INTO platform.agent_update_packages(tenant_id,package_id,target_version,platform_name,architecture,manifest_hash,package_hash,revoked,expires_at,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) ON CONFLICT(tenant_id,package_id) DO UPDATE SET revoked=EXCLUDED.revoked,data=EXCLUDED.data", [Guid.Parse(tenant), x.Manifest.PackageId, x.Manifest.TargetVersion, x.Manifest.Platform, x.Manifest.Architecture, x.Manifest.ManifestSha256, x.Manifest.PackageSha256, x.Revoked, x.Manifest.ExpiresAt, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistPolicyAsync(AgentUpdatePolicy x, CancellationToken ct) => Exec("INSERT INTO platform.agent_update_policies(tenant_id,policy_id,version,policy_hash,created_at,data) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT DO NOTHING", [Guid.Parse(x.TenantId), x.PolicyId, x.Version, x.PolicyHash, x.CreatedAt, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistRolloutAsync(FleetRollout x, CancellationToken ct) => Exec("INSERT INTO platform.agent_update_rollouts(tenant_id,rollout_id,package_id,state,current_ring,updated_at,data) VALUES($1,$2,$3,$4,$5,now(),$6::jsonb) ON CONFLICT(tenant_id,rollout_id) DO UPDATE SET state=EXCLUDED.state,current_ring=EXCLUDED.current_ring,updated_at=now(),data=EXCLUDED.data", [Guid.Parse(x.TenantId), x.RolloutId, x.PackageId, x.State.ToString(), x.CurrentRing, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistAssignmentAsync(EndpointUpdateAssignment x, CancellationToken ct) => Exec("INSERT INTO platform.agent_update_assignments(tenant_id,assignment_id,rollout_id,endpoint_id,installation_id,package_id,state,updated_at,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(tenant_id,assignment_id) DO UPDATE SET state=EXCLUDED.state,updated_at=EXCLUDED.updated_at,data=EXCLUDED.data", [Guid.Parse(x.TenantId), x.AssignmentId, x.RolloutId, x.EndpointId, x.InstallationId, x.PackageId, x.State.ToString(), x.UpdatedAt, JsonSerializer.Serialize(x, Json)], ct);
    protected override Task PersistAuditAsync(FleetAuditEvent x, CancellationToken ct) => Exec("INSERT INTO platform.fleet_update_audit(tenant_id,audit_id,object_type,object_id,action,actor,occurred_at,object_hash,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT DO NOTHING", [Guid.Parse(x.TenantId), x.AuditId, x.ObjectType, x.ObjectId, x.Action, x.Actor, x.OccurredAt, x.ObjectHash, JsonSerializer.Serialize(x, Json)], ct);
    public async ValueTask DisposeAsync() { await data.DisposeAsync(); Dispose(); GC.SuppressFinalize(this); }
}
