using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresCorrelationRepository : ICorrelationRepository, IAsyncDisposable
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    readonly NpgsqlDataSource _data;
    public PostgresCorrelationRepository(string connectionString) => _data = NpgsqlDataSource.Create(new NpgsqlConnectionStringBuilder(connectionString) { Pooling = true, MaxPoolSize = 8, CommandTimeout = 30 }.ConnectionString);

    public async Task<IReadOnlyList<CorrelationPack>> ListPacksAsync(string tenant, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT DISTINCT ON(pack_id) pack_data FROM platform.correlation_packs WHERE tenant_id=$1 ORDER BY pack_id,version DESC", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); return await ReadJson<CorrelationPack>(q, ct);
    }
    public async Task<CorrelationPack?> GetPackAsync(string tenant, Guid id, int? version, CancellationToken ct) => (await PackHistoryAsync(tenant, id, ct)).Where(x => version is null || x.Version == version).MaxBy(x => x.Version);
    public async Task<IReadOnlyList<CorrelationPack>> PackHistoryAsync(string tenant, Guid id, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT pack_data FROM platform.correlation_packs WHERE tenant_id=$1 AND pack_id=$2 ORDER BY version DESC", c); Params(q, Guid.Parse(tenant), id); return await ReadJson<CorrelationPack>(q, ct);
    }
    public async Task<CorrelationPack> PutPackAsync(string tenant, string actor, CorrelationPack input, CancellationToken ct)
    {
        var history = input.PackId == Guid.Empty ? [] : await PackHistoryAsync(tenant, input.PackId, ct); var id = input.PackId == Guid.Empty ? Guid.NewGuid() : input.PackId; var version = history.Count == 0 ? Math.Max(1, input.Version) : history.Max(x => x.Version) + 1; var value = input with { PackId = id, Version = version, TenantId = tenant, Enabled = false, CreatedAt = DateTimeOffset.UtcNow, CreatedBy = actor }; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.correlation_packs(tenant_id,pack_id,version,pack_data,validation_passed,enabled,created_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", c); Params(q, Guid.Parse(tenant), id, version); AddJson(q, JsonSerializer.Serialize(value, Json)); Params(q, value.ValidationPassed, false, value.CreatedAt, actor); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public async Task<CorrelationPack> SetPackEnabledAsync(string tenant, string actor, Guid id, int version, bool enabled, CancellationToken ct)
    {
        var pack = await GetPackAsync(tenant, id, version, ct) ?? throw new KeyNotFoundException(); if (enabled && !pack.ValidationPassed) throw new EnrollmentConflictException("CORRELATION_PACK_INVALID", "Pack validation must pass before activation."); var value = pack with { Enabled = enabled }; await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); await using (var q = new NpgsqlCommand("UPDATE platform.correlation_packs SET enabled=$4,pack_data=$5 WHERE tenant_id=$1 AND pack_id=$2 AND version=$3", c, tx)) { Params(q, Guid.Parse(tenant), id, version, enabled); AddJson(q, JsonSerializer.Serialize(value, Json)); await q.ExecuteNonQueryAsync(ct); }
        await Audit(c, tx, tenant, actor, enabled ? "correlation.pack.activate" : "correlation.pack.disable", id, version, ct); await tx.CommitAsync(ct); return value;
    }
    public async Task<CorrelationAssignment> AssignPackAsync(string tenant, string actor, CorrelationAssignment input, CancellationToken ct)
    {
        if (await GetPackAsync(tenant, input.PackId, input.PackVersion, ct) is null) throw new EnrollmentConflictException("CORRELATION_ASSIGNMENT_INVALID", "Pack version is not in this tenant."); var value = input with { Id = input.Id == Guid.Empty ? Guid.NewGuid() : input.Id, TenantId = tenant, CreatedAt = DateTimeOffset.UtcNow, CreatedBy = actor }; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.correlation_assignments VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", c); Params(q, Guid.Parse(tenant), value.Id, value.PackId, value.PackVersion, value.EndpointId, value.EndpointGroupId, value.Enabled, value.CreatedAt, actor); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public async Task<IReadOnlyList<CorrelationRule>> ListRulesAsync(string tenant, Guid? packId, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT DISTINCT ON(correlation_rule_id) definition FROM platform.correlation_rules WHERE tenant_id=$1 AND($2::uuid IS NULL OR pack_id=$2) ORDER BY correlation_rule_id,version DESC", c); Params(q, Guid.Parse(tenant), packId); return await ReadJson<CorrelationRule>(q, ct);
    }
    public async Task<CorrelationRule?> GetRuleAsync(string tenant, Guid id, int? version, CancellationToken ct) => (await RuleHistoryAsync(tenant, id, ct)).Where(x => version is null || x.Version == version).MaxBy(x => x.Version);
    public async Task<IReadOnlyList<CorrelationRule>> RuleHistoryAsync(string tenant, Guid id, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT definition FROM platform.correlation_rules WHERE tenant_id=$1 AND correlation_rule_id=$2 ORDER BY version DESC", c); Params(q, Guid.Parse(tenant), id); return await ReadJson<CorrelationRule>(q, ct);
    }
    public async Task<CorrelationRule> PutRuleAsync(string tenant, string actor, CorrelationRule input, bool newVersion, CancellationToken ct)
    {
        var history = input.CorrelationRuleId == Guid.Empty ? [] : await RuleHistoryAsync(tenant, input.CorrelationRuleId, ct); if (!newVersion && history.Count > 0) throw new EnrollmentConflictException("CORRELATION_RULE_EXISTS", "Rule already exists."); var id = input.CorrelationRuleId == Guid.Empty ? Guid.NewGuid() : input.CorrelationRuleId; var version = history.Count == 0 ? Math.Max(1, input.Version) : history.Max(x => x.Version) + 1; var now = DateTimeOffset.UtcNow; var value = input with { SchemaVersion = "correlation-rule.v1", CorrelationRuleId = id, Version = version, TenantId = tenant, Status = CorrelationStatus.Draft, Enabled = false, ValidationPassed = false, ValidatedAt = null, CreatedAt = now, CreatedBy = actor, ActivatedAt = null, DeactivatedAt = null }; var bytes = JsonSerializer.SerializeToUtf8Bytes(value, Json); var hash = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(); await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.correlation_rules(tenant_id,correlation_rule_id,version,pack_id,pack_version,status,enabled,validation_passed,definition,definition_sha256,created_at,created_by) VALUES($1,$2,$3,$4,$5,'Draft',false,false,$6,$7,$8,$9)", c); Params(q, Guid.Parse(tenant), id, version, value.PackId, value.PackVersion); AddJson(q, Encoding.UTF8.GetString(bytes)); Params(q, hash, now, actor); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public async Task<CorrelationRule> ValidateRuleAsync(string tenant, Guid id, int version, IReadOnlyDictionary<string, string[]> errors, CancellationToken ct)
    {
        var rule = await GetRuleAsync(tenant, id, version, ct) ?? throw new KeyNotFoundException(); var now = DateTimeOffset.UtcNow; var value = rule with { ValidationPassed = errors.Count == 0, ValidatedAt = now, Status = errors.Count == 0 ? CorrelationStatus.Testing : CorrelationStatus.Draft }; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.correlation_rules SET validation_passed=$4,validation_result=$5,status=$6,definition=$7 WHERE tenant_id=$1 AND correlation_rule_id=$2 AND version=$3", c); Params(q, Guid.Parse(tenant), id, version, value.ValidationPassed); AddJson(q, JsonSerializer.Serialize(new { errors, validatedAt = now }, Json)); q.Parameters.AddWithValue(value.Status.ToString()); AddJson(q, JsonSerializer.Serialize(value, Json)); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public async Task RecordTestsAsync(string tenant, Guid id, int version, IReadOnlyList<CorrelationTestResult> tests, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); foreach (var test in tests) await using (var q = new NpgsqlCommand("INSERT INTO platform.correlation_rule_tests VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,correlation_rule_id,version,fixture_name) DO UPDATE SET passed=excluded.passed,result=excluded.result,completed_at=excluded.completed_at", c)) { Params(q, Guid.Parse(tenant), id, version, test.Name, test.Kind, test.Passed); AddJson(q, JsonSerializer.Serialize(test, Json)); q.Parameters.AddWithValue(test.CompletedAt); await q.ExecuteNonQueryAsync(ct); }
    }
    public async Task<IReadOnlyList<CorrelationTestResult>> ListTestsAsync(string tenant, Guid id, int version, CancellationToken ct)
    {
        await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT result FROM platform.correlation_rule_tests WHERE tenant_id=$1 AND correlation_rule_id=$2 AND version=$3 ORDER BY fixture_name", c); Params(q, Guid.Parse(tenant), id, version); return await ReadJson<CorrelationTestResult>(q, ct);
    }
    public async Task<CorrelationRule> SetRuleEnabledAsync(string tenant, string actor, Guid id, int version, bool enabled, CancellationToken ct)
    {
        var rule = await GetRuleAsync(tenant, id, version, ct) ?? throw new KeyNotFoundException(); var tests = await ListTestsAsync(tenant, id, version, ct); if (enabled && (!rule.ValidationPassed || tests.Count < 3 || tests.Any(x => !x.Passed || !x.Deterministic || !x.TenantIsolated || !x.ResourceCostPassed))) throw new EnrollmentConflictException("CORRELATION_ACTIVATION_BLOCKED", "Validation, fixtures, determinism, isolation and resource cost must pass."); var now = DateTimeOffset.UtcNow; var value = rule with { Enabled = enabled, Status = enabled ? CorrelationStatus.Active : CorrelationStatus.Disabled, ActivatedAt = enabled ? now : rule.ActivatedAt, DeactivatedAt = enabled ? null : now }; await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); if (enabled) await using (var old = new NpgsqlCommand("UPDATE platform.correlation_rules SET status='Disabled',enabled=false,deactivated_at=now() WHERE tenant_id=$1 AND correlation_rule_id=$2 AND status='Active'", c, tx)) { Params(old, Guid.Parse(tenant), id); await old.ExecuteNonQueryAsync(ct); }
        await using (var q = new NpgsqlCommand("UPDATE platform.correlation_rules SET status=$4,enabled=$5,activated_at=$6,deactivated_at=$7,definition=$8 WHERE tenant_id=$1 AND correlation_rule_id=$2 AND version=$3", c, tx)) { Params(q, Guid.Parse(tenant), id, version, value.Status.ToString(), enabled, value.ActivatedAt, value.DeactivatedAt); AddJson(q, JsonSerializer.Serialize(value, Json)); await q.ExecuteNonQueryAsync(ct); }
        await Audit(c, tx, tenant, actor, enabled ? "correlation.rule.activate" : "correlation.rule.disable", id, version, ct); await tx.CommitAsync(ct); return value;
    }

    public async Task<CorrelationEvaluationResult> EvaluateAsync(string tenant, CorrelationObservation observation, DetectionExecutionMode mode, Guid? ruleId, int? version, Guid? runId, bool production, CancellationToken ct)
    {
        if (observation.TenantId != tenant) throw new EnrollmentConflictException("CORRELATION_TENANT_MISMATCH", "Observation tenant does not match authenticated tenant."); await using (var c = await _data.OpenConnectionAsync(ct)) await using (var ledger = new NpgsqlCommand("INSERT INTO platform.correlation_observations(tenant_id,observation_id,event_time,observation) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING", c)) { Params(ledger, Guid.Parse(tenant), observation.ObservationId, observation.EventTime); AddJson(ledger, JsonSerializer.Serialize(observation, Json)); await ledger.ExecuteNonQueryAsync(ct); }
        var rules = ruleId is null ? (await ActiveRules(tenant, observation.EndpointId, ct)).Where(r => r.Steps.Any(s =>
            s.InputKind == observation.Kind
            && (s.Domain is null || s.Domain == observation.Domain)
            && (s.DetectionId is null || s.DetectionId == observation.DetectionId)
            && CorrelationDsl.Matches(r, s, observation, out _))).ToArray() : [(await GetRuleAsync(tenant, ruleId.Value, version, ct)) ?? throw new KeyNotFoundException()]; CorrelationEvaluationResult? last = null; CorrelationEvaluationResult? completedResult = null; foreach (var rule in rules) { last = await EvaluateRule(tenant, rule, observation, mode, runId, production, ct); if (last.Finding is not null) completedResult = last; }
        return completedResult ?? last ?? new(false, false, false, false, "none", [], null, "no-applicable-rule");
    }
    public async Task<IReadOnlyList<CorrelationObservation>> LoadObservationsAsync(string tenant, DateTimeOffset from, DateTimeOffset until, int maximum, CancellationToken ct) { if (until <= from || until - from > TimeSpan.FromDays(7) || maximum is < 1 or > 100_000) throw new EnrollmentConflictException("CORRELATION_REPLAY_BOUNDS", "Authoritative replay query is out of bounds."); await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT observation FROM platform.correlation_observations WHERE tenant_id=$1 AND event_time BETWEEN $2 AND $3 ORDER BY event_time,observation_id LIMIT $4", c); Params(q, Guid.Parse(tenant), from, until, maximum); return await ReadJson<CorrelationObservation>(q, ct); }
    async Task<CorrelationEvaluationResult> EvaluateRule(string tenant, CorrelationRule rule, CorrelationObservation observation, DetectionExecutionMode mode, Guid? runId, bool production, CancellationToken ct)
    {
        var started = DateTimeOffset.UtcNow; var run = runId ?? Guid.Empty; var key = CorrelationDsl.Key(rule, observation); await using var c = await _data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct);
        await using (var processed = new NpgsqlCommand("INSERT INTO platform.correlation_processed_observations VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT DO NOTHING", c, tx)) { Params(processed, Guid.Parse(tenant), rule.CorrelationRuleId, rule.Version, mode.ToString(), run, observation.ObservationId); if (await processed.ExecuteNonQueryAsync(ct) == 0) { await Health(c, tx, tenant, duplicate: 1, ct: ct); await tx.CommitAsync(ct); return new(true, false, false, false, key, [], null, "duplicate-observation"); } }
        var exclusions = await Exclusions(c, tx, tenant, rule, observation, ct); if (exclusions is not null) { await Health(c, tx, tenant, excluded: 1, ct: ct); await tx.CommitAsync(ct); return new(false, false, true, false, key, [], null, exclusions.Reason); }
        var scope = $"{mode}:{run:D}"; await using (var state = new NpgsqlCommand("INSERT INTO platform.correlation_state_observations VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING", c, tx)) { Params(state, Guid.Parse(tenant), rule.CorrelationRuleId, rule.Version, scope, key, observation.ObservationId, observation.EventTime, observation.EventTime.AddSeconds(rule.WindowSeconds)); AddJson(state, JsonSerializer.Serialize(observation, Json)); await state.ExecuteNonQueryAsync(ct); }
        long expired; await using (var clean = new NpgsqlCommand("WITH d AS(DELETE FROM platform.correlation_state_observations WHERE tenant_id=$1 AND expires_at<$2 RETURNING 1) SELECT count(*) FROM d", c, tx)) { Params(clean, Guid.Parse(tenant), observation.EventTime.AddSeconds(-rule.WindowSeconds)); expired = Convert.ToInt64(await clean.ExecuteScalarAsync(ct), System.Globalization.CultureInfo.InvariantCulture); }
        var values = new List<CorrelationObservation>(); await using (var select = new NpgsqlCommand("SELECT observation FROM platform.correlation_state_observations WHERE tenant_id=$1 AND correlation_rule_id=$2 AND version=$3 AND evaluation_scope=$4 AND correlation_key=$5 AND event_time BETWEEN $6 AND $7 ORDER BY event_time,observation_id", c, tx)) { Params(select, Guid.Parse(tenant), rule.CorrelationRuleId, rule.Version, scope, key, observation.EventTime.AddSeconds(-rule.WindowSeconds), observation.EventTime.AddSeconds(rule.WindowSeconds)); await using var reader = await select.ExecuteReaderAsync(ct); while (await reader.ReadAsync(ct)) values.Add(JsonSerializer.Deserialize<CorrelationObservation>(reader.GetString(0), Json)!); }
        CorrelatedFinding? prior = null; if (rule.Suppression.DurationMinutes > 0) await using (var previous = new NpgsqlCommand("SELECT finding_data FROM platform.correlated_findings WHERE tenant_id=$1 AND correlation_rule_id=$2 AND correlation_key=$3 AND created_at>=$4 ORDER BY created_at DESC LIMIT 1", c, tx)) { Params(previous, Guid.Parse(tenant), rule.CorrelationRuleId, key, observation.EventTime.AddMinutes(-rule.Suppression.DurationMinutes)); if (await previous.ExecuteScalarAsync(ct) is string json) prior = JsonSerializer.Deserialize<CorrelatedFinding>(json, Json); }
        var finding = CorrelationDsl.Complete(rule, values, mode, prior); var missing = rule.Steps.Where(s => s.Required && !values.Any(v => CorrelationDsl.Matches(rule, s, v, out _))).Select(s => s.Id).ToArray(); if (finding is not null && production && mode is DetectionExecutionMode.Live or DetectionExecutionMode.HistoricalReplay) { var json = JsonSerializer.Serialize(finding, Json); await using (var insert = new NpgsqlCommand("INSERT INTO platform.correlated_findings(tenant_id,correlated_finding_id,correlation_rule_id,correlation_rule_version,pack_id,pack_version,endpoint_id,severity,confidence,first_seen,last_seen,correlation_key,suppressed,excluded,execution_mode,finding_data,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT DO NOTHING", c, tx)) { Params(insert, Guid.Parse(tenant), finding.CorrelatedFindingId, finding.CorrelationRuleId, finding.CorrelationRuleVersion, finding.PackId, finding.PackVersion, finding.EndpointId, finding.Severity, finding.Confidence, finding.FirstSeen, finding.LastSeen, finding.CorrelationKey, finding.Suppressed, finding.Excluded, finding.ExecutionMode.ToString()); AddJson(insert, json); insert.Parameters.AddWithValue(finding.CreatedAt); await insert.ExecuteNonQueryAsync(ct); } await using (var history = new NpgsqlCommand("INSERT INTO platform.correlated_finding_history(tenant_id,correlated_finding_id,action,actor,occurred_at,data) VALUES($1,$2,'created','system:correlation-engine',now(),$3)", c, tx)) { Params(history, Guid.Parse(tenant), finding.CorrelatedFindingId); AddJson(history, json); await history.ExecuteNonQueryAsync(ct); } await using (var outbox = new NpgsqlCommand("INSERT INTO platform.outbox(id,tenant_id,topic,subject,message,trace_id) VALUES($1,$2,'correlation.finding.changed','correlation.finding.v1',$3,'')", c, tx)) { Params(outbox, Guid.NewGuid(), Guid.Parse(tenant)); AddJson(outbox, JsonSerializer.Serialize(new { tenantId = tenant, correlatedFindingId = finding.CorrelatedFindingId, endpointId = finding.EndpointId }, Json)); await outbox.ExecuteNonQueryAsync(ct); } }
        await Health(c, tx, tenant, evaluated: 1, active: values.Count, expired: expired, completed: finding is null ? 0 : 1, incomplete: finding is null ? 1 : 0, late: observation.Late ? 1 : 0, missing: observation.MissingTelemetry?.Length ?? 0, suppressed: finding?.Suppressed == true ? 1 : 0, latency: (DateTimeOffset.UtcNow - started).TotalMilliseconds, ct: ct); await tx.CommitAsync(ct); return new(false, finding is not null, false, finding?.Suppressed ?? false, key, missing, finding, finding is null ? "sequence-incomplete" : "all-required-steps-satisfied");
    }
    async Task<IReadOnlyList<CorrelationRule>> ActiveRules(string tenant, Guid? endpoint, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT DISTINCT r.definition FROM platform.correlation_rules r JOIN platform.correlation_packs p ON p.tenant_id=r.tenant_id AND p.pack_id=r.pack_id AND p.version=r.pack_version AND p.enabled JOIN platform.correlation_assignments a ON a.tenant_id=p.tenant_id AND a.pack_id=p.pack_id AND a.pack_version=p.version AND a.enabled WHERE r.tenant_id=$1 AND r.status='Active' AND r.enabled AND(a.endpoint_id IS NULL OR a.endpoint_id=$2)", c); Params(q, Guid.Parse(tenant), endpoint); return await ReadJson<CorrelationRule>(q, ct); }

    public async Task<CorrelatedFindingPage> SearchFindingsAsync(string tenant, CorrelatedFindingQuery x, CancellationToken ct)
    {
        if (!string.IsNullOrWhiteSpace(x.Cursor)) throw new EnrollmentConflictException("CORRELATION_CURSOR_INVALID", "Cursor is invalid or unsupported."); const string sql = "SELECT finding_data FROM platform.correlated_findings WHERE tenant_id=$1 AND($2::uuid IS NULL OR correlation_rule_id=$2) AND($3::uuid IS NULL OR pack_id=$3) AND($4::uuid IS NULL OR endpoint_id=$4) AND($5::int IS NULL OR severity>=$5) AND($6::boolean IS NULL OR suppressed=$6) AND($7='' OR execution_mode=$7) AND($8::timestamptz IS NULL OR created_at>=$8) AND($9::timestamptz IS NULL OR created_at<=$9) ORDER BY created_at DESC,correlated_finding_id DESC LIMIT $10"; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand(sql, c); Params(q, Guid.Parse(tenant), x.RuleId, x.PackId, x.EndpointId, x.MinimumSeverity, x.Suppressed, x.Mode?.ToString() ?? "", x.From, x.To, Math.Clamp(x.PageSize, 1, 500)); return new(await ReadJson<CorrelatedFinding>(q, ct), null);
    }
    public async Task<CorrelatedFinding?> GetFindingAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT finding_data FROM platform.correlated_findings WHERE tenant_id=$1 AND correlated_finding_id=$2", c); Params(q, Guid.Parse(tenant), id); return await q.ExecuteScalarAsync(ct) is string json ? JsonSerializer.Deserialize<CorrelatedFinding>(json, Json) : null; }
    public async Task<IReadOnlyList<CorrelationExclusion>> ListExclusionsAsync(string tenant, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT id,version,pack_id,correlation_rule_id,field_name,field_value,starts_at,ends_at,reason,created_by,match_count FROM platform.correlation_exclusions WHERE tenant_id=$1 ORDER BY created_at", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); var list = new List<CorrelationExclusion>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(new(r.GetGuid(0), r.GetInt32(1), tenant, r.IsDBNull(2) ? null : r.GetGuid(2), r.IsDBNull(3) ? null : r.GetGuid(3), r.GetString(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetFieldValue<DateTimeOffset>(7), r.GetString(8), r.GetString(9), r.GetInt64(10))); return list; }
    public async Task<CorrelationExclusion> PutExclusionAsync(string tenant, string actor, CorrelationExclusion x, CancellationToken ct) { if (string.IsNullOrWhiteSpace(x.Field) || x.Value.Trim() is "*" or "**" || x.EndsAt <= x.StartsAt || x.EndsAt - x.StartsAt > TimeSpan.FromDays(90)) throw new EnrollmentConflictException("CORRELATION_EXCLUSION_INVALID", "Exclusion must be exact and bounded to 90 days."); var value = x with { Id = x.Id == Guid.Empty ? Guid.NewGuid() : x.Id, Version = Math.Max(1, x.Version), TenantId = tenant, CreatedBy = actor }; await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.correlation_exclusions(tenant_id,id,version,pack_id,correlation_rule_id,field_name,field_value,starts_at,ends_at,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT DO NOTHING", c); Params(q, Guid.Parse(tenant), value.Id, value.Version, value.PackId, value.RuleId, value.Field, value.Value, value.StartsAt, value.EndsAt, value.Reason, actor); await q.ExecuteNonQueryAsync(ct); return value; }
    static async Task<CorrelationExclusion?> Exclusions(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, CorrelationRule rule, CorrelationObservation observation, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT id,version,pack_id,correlation_rule_id,field_name,field_value,starts_at,ends_at,reason,created_by,match_count FROM platform.correlation_exclusions WHERE tenant_id=$1 AND starts_at<=$2 AND ends_at>=$2 AND(pack_id IS NULL OR pack_id=$3) AND(correlation_rule_id IS NULL OR correlation_rule_id=$4)", c, tx); Params(q, Guid.Parse(tenant), observation.EventTime, rule.PackId, rule.CorrelationRuleId); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) { var value = new CorrelationExclusion(r.GetGuid(0), r.GetInt32(1), tenant, r.IsDBNull(2) ? null : r.GetGuid(2), r.IsDBNull(3) ? null : r.GetGuid(3), r.GetString(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetFieldValue<DateTimeOffset>(7), r.GetString(8), r.GetString(9), r.GetInt64(10)); if (string.Equals(CorrelationDsl.Value(observation, value.Field), value.Value, StringComparison.OrdinalIgnoreCase)) return value; } return null; }

    public async Task<CorrelationRun> PutRunAsync(string tenant, CorrelationRun run, CorrelationRule rule, CancellationToken ct) { if (run.To <= run.From || run.To - run.From > TimeSpan.FromDays(7) || run.TenantId != tenant) throw new EnrollmentConflictException("CORRELATION_REPLAY_BOUNDS", "Replay must be tenant-bound and at most seven days."); await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.correlation_runs(tenant_id,id,correlation_rule_id,rule_version,pack_id,pack_version,mode,from_time,to_time,status,observations_total,production_findings,rule_snapshot,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)", c); Params(q, Guid.Parse(tenant), run.Id, run.RuleId, run.RuleVersion, run.PackId, run.PackVersion, run.Mode.ToString(), run.From, run.To, run.Status, run.ObservationsTotal, run.ProductionFindings); AddJson(q, JsonSerializer.Serialize(rule, Json)); q.Parameters.AddWithValue(run.CreatedAt); await q.ExecuteNonQueryAsync(ct); return run; }
    public async Task<CorrelationRun?> GetRunAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT correlation_rule_id,rule_version,pack_id,pack_version,mode,from_time,to_time,status,observations_total,observations_evaluated,findings,production_findings,created_at,completed_at FROM platform.correlation_runs WHERE tenant_id=$1 AND id=$2", c); Params(q, Guid.Parse(tenant), id); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(id, tenant, r.GetGuid(0), r.GetInt32(1), r.GetGuid(2), r.GetInt32(3), Enum.Parse<DetectionExecutionMode>(r.GetString(4)), r.GetFieldValue<DateTimeOffset>(5), r.GetFieldValue<DateTimeOffset>(6), r.GetString(7), r.GetInt64(8), r.GetInt64(9), r.GetInt64(10), r.GetBoolean(11), r.GetFieldValue<DateTimeOffset>(12), r.IsDBNull(13) ? null : r.GetFieldValue<DateTimeOffset>(13)) : null; }
    public async Task<CorrelationRun> CompleteRunAsync(string tenant, Guid id, long evaluated, long findings, string status, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.correlation_runs SET observations_evaluated=$3,findings=$4,status=$5,completed_at=now() WHERE tenant_id=$1 AND id=$2", c); Params(q, Guid.Parse(tenant), id, evaluated, findings, status); if (await q.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); return (await GetRunAsync(tenant, id, ct))!; }
    public async Task<CorrelationRun> CancelRunAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.correlation_runs SET cancel_requested=true,status=CASE WHEN status IN('queued','running') THEN 'cancelling' ELSE status END WHERE tenant_id=$1 AND id=$2", c); Params(q, Guid.Parse(tenant), id); if (await q.ExecuteNonQueryAsync(ct) == 0) throw new KeyNotFoundException(); return (await GetRunAsync(tenant, id, ct))!; }
    public async Task<CorrelationHealth> HealthAsync(string tenant, CancellationToken ct) { await using var c = await _data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT health_data,updated_at,(SELECT count(*) FROM platform.correlation_state_observations WHERE tenant_id=$1),(SELECT count(*) FROM platform.correlation_runs WHERE tenant_id=$1 AND status IN('queued','running','cancelling')) FROM platform.correlation_health WHERE tenant_id=$1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) return new(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, DateTimeOffset.UtcNow); using var doc = JsonDocument.Parse(r.GetString(0)); long L(string n) => doc.RootElement.TryGetProperty(n, out var x) ? x.GetInt64() : 0; double D(string n) => doc.RootElement.TryGetProperty(n, out var x) ? x.GetDouble() : 0; return new(L("evaluated"), r.GetInt64(2), L("expired"), L("completed"), L("incomplete"), L("late"), L("duplicate"), D("stateLatency"), D("evaluationLatency"), D("replayLatency"), L("failures"), L("missing"), L("suppressed"), L("excluded"), r.GetInt64(3), r.GetFieldValue<DateTimeOffset>(1)); }
    public async Task<IReadOnlyList<MitreCoverageRow>> CoverageAsync(string tenant, CancellationToken ct) { var rules = await ListRulesAsync(tenant, null, ct); var rows = new List<MitreCoverageRow>(); foreach (var g in rules.GroupBy(x => new { x.MitreTactic, x.MitreTechnique, x.MitreSubTechnique })) { var tested = true; foreach (var rule in g) tested &= (await ListTestsAsync(tenant, rule.CorrelationRuleId, rule.Version, ct)).All(x => x.Passed); rows.Add(new(g.Key.MitreTactic, g.Key.MitreTechnique, g.Key.MitreSubTechnique, g.Select(x => x.Name).ToArray(), g.SelectMany(x => x.RequiredTelemetry).Distinct().ToArray(), true, true, tested, g.Any(x => x.Status == CorrelationStatus.Active && x.Enabled))); } return rows; }

    static async Task Health(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, long evaluated = 0, long active = 0, long expired = 0, long completed = 0, long incomplete = 0, long late = 0, long duplicate = 0, long failures = 0, long missing = 0, long suppressed = 0, long excluded = 0, double latency = 0, CancellationToken ct = default) { await using var q = new NpgsqlCommand("INSERT INTO platform.correlation_health VALUES($1,$2,now()) ON CONFLICT(tenant_id) DO UPDATE SET health_data=jsonb_build_object('evaluated',COALESCE((correlation_health.health_data->>'evaluated')::bigint,0)+$3,'expired',COALESCE((correlation_health.health_data->>'expired')::bigint,0)+$4,'completed',COALESCE((correlation_health.health_data->>'completed')::bigint,0)+$5,'incomplete',COALESCE((correlation_health.health_data->>'incomplete')::bigint,0)+$6,'late',COALESCE((correlation_health.health_data->>'late')::bigint,0)+$7,'duplicate',COALESCE((correlation_health.health_data->>'duplicate')::bigint,0)+$8,'failures',COALESCE((correlation_health.health_data->>'failures')::bigint,0)+$9,'missing',COALESCE((correlation_health.health_data->>'missing')::bigint,0)+$10,'suppressed',COALESCE((correlation_health.health_data->>'suppressed')::bigint,0)+$11,'excluded',COALESCE((correlation_health.health_data->>'excluded')::bigint,0)+$12,'stateLatency',$13,'evaluationLatency',$13),updated_at=now()", c, tx); q.Parameters.AddWithValue(Guid.Parse(tenant)); AddJson(q, "{}"); Params(q, evaluated, expired, completed, incomplete, late, duplicate, failures, missing, suppressed, excluded, latency); await q.ExecuteNonQueryAsync(ct); }
    static async Task<IReadOnlyList<T>> ReadJson<T>(NpgsqlCommand q, CancellationToken ct) { var list = new List<T>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) list.Add(JsonSerializer.Deserialize<T>(r.GetString(0), Json)!); return list; }
    static void AddJson(NpgsqlCommand q, string value) => q.Parameters.Add(new() { Value = value, NpgsqlDbType = NpgsqlDbType.Jsonb });
    static void Params(NpgsqlCommand q, params object?[] values) { foreach (var value in values) q.Parameters.AddWithValue(value ?? DBNull.Value); }
    static async Task Audit(NpgsqlConnection c, NpgsqlTransaction tx, string tenant, string actor, string action, Guid id, int version, CancellationToken ct) { await using var q = new NpgsqlCommand("INSERT INTO platform.audit_events(id,tenant_id,occurred_at,actor,action,resource,decision,outcome,request_id,data) VALUES($1,$2,now(),$3,$4,$5,'allow','success',$6,$7)", c, tx); Params(q, Guid.NewGuid(), Guid.Parse(tenant)); AddJson(q, JsonSerializer.Serialize(new { subject = actor }, Json)); q.Parameters.AddWithValue(action); AddJson(q, JsonSerializer.Serialize(new { type = "correlation", id, version }, Json)); q.Parameters.AddWithValue(Guid.NewGuid().ToString("D")); AddJson(q, "{}"); await q.ExecuteNonQueryAsync(ct); }
    public ValueTask DisposeAsync() => _data.DisposeAsync();
}
