using System.Security.Cryptography;
using System.Text.Json;
using Npgsql;
using OpenSecurityPlatform.Foundation;

namespace OpenSecurityPlatform.Infrastructure;

public sealed class PostgresCapacityRetentionRepository : ICapacityRetentionRepository, IAsyncDisposable
{
    readonly NpgsqlDataSource data; static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public PostgresCapacityRetentionRepository(string connectionString) => data = NpgsqlDataSource.Create(connectionString);

    public async Task<RetentionPolicy> PutPolicyAsync(string tenant, string actor, Guid? policyId, RetentionPolicyRequest request, CancellationToken ct)
    {
        CapacityRetentionSafety.Validate(request); var id = policyId ?? Guid.NewGuid(); var prior = (await PoliciesAsync(tenant, ct)).Where(x => x.PolicyId == id).OrderByDescending(x => x.Version).FirstOrDefault(); var now = DateTimeOffset.UtcNow;
        var value = new RetentionPolicy(id, tenant, (prior?.Version ?? 0) + 1, request.Category, request.AuthorityDays, request.ProjectionDays, request.BatchSize, request.ArchiveBeforeDelete, request.Enabled, now, actor, prior?.PolicyHash ?? "", "");
        value = value with { PolicyHash = CapacityRetentionSafety.Hash(value with { PolicyHash = "", CreatedAt = default, CreatedBy = "" }) };
        await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.retention_policies(tenant_id,policy_id,version,category,authority_days,projection_days,batch_size,archive_before_delete,enabled,created_at,created_by,previous_hash,policy_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)", c); Add(q, Guid.Parse(tenant), id, value.Version, value.Category, value.AuthorityDays, value.ProjectionDays, value.BatchSize, value.ArchiveBeforeDelete, value.Enabled, now, actor, value.PreviousHash, value.PolicyHash); await q.ExecuteNonQueryAsync(ct); return value;
    }
    public async Task<IReadOnlyList<RetentionPolicy>> PoliciesAsync(string tenant, CancellationToken ct)
    { var x = new List<RetentionPolicy>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT policy_id,version,category,authority_days,projection_days,batch_size,archive_before_delete,enabled,created_at,created_by,previous_hash,policy_hash FROM platform.retention_policies WHERE tenant_id=$1 ORDER BY category,version DESC", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), tenant, r.GetInt32(1), r.GetString(2), r.GetInt32(3), r.GetInt32(4), r.GetInt32(5), r.GetBoolean(6), r.GetBoolean(7), r.GetFieldValue<DateTimeOffset>(8), r.GetString(9), r.GetString(10), r.GetString(11))); return x; }
    public async Task<RetentionHold> PutHoldAsync(string tenant, string actor, RetentionHoldRequest request, CancellationToken ct)
    { var now = DateTimeOffset.UtcNow; CapacityRetentionSafety.Validate(request, now); var x = new RetentionHold(Guid.NewGuid(), tenant, request.HoldType, request.Category, request.TargetId, request.Reason, true, now, request.ExpiresAt, actor); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.retention_holds(tenant_id,hold_id,hold_type,category,target_id,reason,active,created_at,expires_at,created_by) VALUES($1,$2,$3,$4,$5,$6,true,$7,$8,$9)", c); Add(q, Guid.Parse(tenant), x.HoldId, x.HoldType, x.Category, x.TargetId, x.Reason, x.CreatedAt, x.ExpiresAt, x.CreatedBy); await q.ExecuteNonQueryAsync(ct); return x; }
    public async Task<IReadOnlyList<RetentionHold>> HoldsAsync(string tenant, CancellationToken ct)
    { var x = new List<RetentionHold>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT hold_id,hold_type,category,target_id,reason,active,created_at,expires_at,created_by FROM platform.retention_holds WHERE tenant_id=$1 ORDER BY created_at DESC", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), tenant, r.GetString(1), r.GetString(2), r.IsDBNull(3) ? null : r.GetString(3), r.GetString(4), r.GetBoolean(5), r.GetFieldValue<DateTimeOffset>(6), r.IsDBNull(7) ? null : r.GetFieldValue<DateTimeOffset>(7), r.GetString(8))); return x; }
    public async Task<RetentionHold> ReleaseHoldAsync(string tenant, Guid holdId, CancellationToken ct)
    { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("UPDATE platform.retention_holds SET active=false WHERE tenant_id=$1 AND hold_id=$2 AND active RETURNING hold_type,category,target_id,reason,created_at,expires_at,created_by", c); Add(q, Guid.Parse(tenant), holdId); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new KeyNotFoundException(); return new(holdId, tenant, r.GetString(0), r.GetString(1), r.IsDBNull(2) ? null : r.GetString(2), r.GetString(3), false, r.GetFieldValue<DateTimeOffset>(4), r.IsDBNull(5) ? null : r.GetFieldValue<DateTimeOffset>(5), r.GetString(6)); }
    public async Task<RetentionPreview> PreviewAsync(string tenant, Guid policyId, string scope, CancellationToken ct)
    {
        if (scope != "qualification-fixture") throw new EnrollmentConflictException("RETENTION_SCOPE_PREVIEW_ONLY", "This release permits destructive execution only in the isolated qualification-fixture scope; production data remains preview-only.");
        var p = (await PoliciesAsync(tenant, ct)).Where(x => x.PolicyId == policyId).OrderByDescending(x => x.Version).FirstOrDefault() ?? throw new KeyNotFoundException(); if (!p.Enabled) throw new EnrollmentConflictException("RETENTION_POLICY_DISABLED", "Retention policy is disabled."); var now = DateTimeOffset.UtcNow; var cutoff = now.AddDays(-p.AuthorityDays);
        await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("""
            SELECT count(*) FILTER(WHERE NOT active_reference AND NOT EXISTS(
              SELECT 1 FROM platform.retention_holds h WHERE h.tenant_id=f.tenant_id AND h.category=f.category AND h.active AND (h.expires_at IS NULL OR h.expires_at>now()) AND (h.target_id IS NULL OR h.target_id=f.record_id::text))),
              coalesce(sum(payload_bytes) FILTER(WHERE NOT active_reference AND NOT EXISTS(
              SELECT 1 FROM platform.retention_holds h WHERE h.tenant_id=f.tenant_id AND h.category=f.category AND h.active AND (h.expires_at IS NULL OR h.expires_at>now()) AND (h.target_id IS NULL OR h.target_id=f.record_id::text))),0),
              count(*) FILTER(WHERE active_reference OR EXISTS(SELECT 1 FROM platform.retention_holds h WHERE h.tenant_id=f.tenant_id AND h.category=f.category AND h.active AND (h.expires_at IS NULL OR h.expires_at>now()) AND (h.target_id IS NULL OR h.target_id=f.record_id::text)))
            FROM platform.retention_fixture_records f WHERE tenant_id=$1 AND category=$2 AND occurred_at<$3
            """, c); Add(q, Guid.Parse(tenant), p.Category, cutoff); await using var r = await q.ExecuteReaderAsync(ct); await r.ReadAsync(ct); var created = DateTimeOffset.UtcNow; var x = new RetentionPreview(Guid.NewGuid(), tenant, p.PolicyId, p.Version, scope, cutoff, r.GetInt64(0), r.GetInt64(1), r.GetInt64(2), "", created, created.AddMinutes(10)); x = x with { PreviewHash = CapacityRetentionSafety.Hash(x with { PreviewHash = "", CreatedAt = default, ExpiresAt = default }) }; await r.DisposeAsync(); await using var save = new NpgsqlCommand("INSERT INTO platform.retention_previews(tenant_id,preview_id,policy_id,policy_version,scope,cutoff,eligible_rows,estimated_bytes,held_rows,preview_hash,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)", c); Add(save, Guid.Parse(tenant), x.PreviewId, x.PolicyId, x.PolicyVersion, x.Scope, x.Cutoff, x.EligibleRows, x.EstimatedBytes, x.HeldRows, x.PreviewHash, x.CreatedAt, x.ExpiresAt); await save.ExecuteNonQueryAsync(ct); return x;
    }
    public async Task<RetentionRun> ExecuteAsync(string tenant, string actor, Guid previewId, string previewHash, bool dryRun, CancellationToken ct)
    {
        await using var c = await data.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); RetentionPreview preview; await using (var q = new NpgsqlCommand("SELECT policy_id,policy_version,scope,cutoff,eligible_rows,estimated_bytes,held_rows,preview_hash,created_at,expires_at FROM platform.retention_previews WHERE tenant_id=$1 AND preview_id=$2 FOR UPDATE", c, tx)) { Add(q, Guid.Parse(tenant), previewId); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new KeyNotFoundException(); preview = new(previewId, tenant, r.GetGuid(0), r.GetInt32(1), r.GetString(2), r.GetFieldValue<DateTimeOffset>(3), r.GetInt64(4), r.GetInt64(5), r.GetInt64(6), r.GetString(7), r.GetFieldValue<DateTimeOffset>(8), r.GetFieldValue<DateTimeOffset>(9)); }
        if (preview.ExpiresAt <= DateTimeOffset.UtcNow || !CryptographicOperations.FixedTimeEquals(System.Text.Encoding.ASCII.GetBytes(preview.PreviewHash), System.Text.Encoding.ASCII.GetBytes(previewHash.ToLowerInvariant()))) throw new EnrollmentConflictException("RETENTION_PREVIEW_BINDING", "Retention preview is expired or its exact hash does not match.");
        RetentionPolicy policy; await using (var q = new NpgsqlCommand("SELECT category,authority_days,projection_days,batch_size,archive_before_delete,enabled,created_at,created_by,previous_hash,policy_hash FROM platform.retention_policies WHERE tenant_id=$1 AND policy_id=$2 AND version=$3", c, tx)) { Add(q, Guid.Parse(tenant), preview.PolicyId, preview.PolicyVersion); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new KeyNotFoundException(); policy = new(preview.PolicyId, tenant, preview.PolicyVersion, r.GetString(0), r.GetInt32(1), r.GetInt32(2), r.GetInt32(3), r.GetBoolean(4), r.GetBoolean(5), r.GetFieldValue<DateTimeOffset>(6), r.GetString(7), r.GetString(8), r.GetString(9)); }
        var candidates = new List<(Guid Id, string Hash, int Bytes, DateTimeOffset At)>(); await using (var q = new NpgsqlCommand("""SELECT f.record_id,f.content_hash,f.payload_bytes,f.occurred_at FROM platform.retention_fixture_records f WHERE f.tenant_id=$1 AND f.category=$2 AND f.occurred_at<$3 AND NOT f.active_reference AND NOT EXISTS(SELECT 1 FROM platform.retention_holds h WHERE h.tenant_id=f.tenant_id AND h.category=f.category AND h.active AND (h.expires_at IS NULL OR h.expires_at>now()) AND (h.target_id IS NULL OR h.target_id=f.record_id::text)) ORDER BY f.occurred_at,f.record_id LIMIT $4 FOR UPDATE""", c, tx)) { Add(q, Guid.Parse(tenant), policy.Category, preview.Cutoff, policy.BatchSize); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) candidates.Add((r.GetGuid(0), r.GetString(1), r.GetInt32(2), r.GetFieldValue<DateTimeOffset>(3))); }
        long deleted = 0, archived = 0; if (!dryRun && candidates.Count > 0) { if (policy.ArchiveBeforeDelete) { var manifest = CapacityRetentionSafety.Hash(candidates.Select(x => new { x.Id, x.Hash, x.Bytes, x.At }).ToArray()); await using var a = new NpgsqlCommand("INSERT INTO platform.archive_jobs(tenant_id,archive_id,policy_id,policy_version,scope,from_time,to_time,record_count,schema_versions,manifest_hash,state,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'Completed',now())", c, tx); Add(a, Guid.Parse(tenant), Guid.NewGuid(), policy.PolicyId, policy.Version, preview.Scope, candidates.Min(x => x.At), candidates.Max(x => x.At), candidates.Count, new[] { "retention-fixture.v1" }, manifest); await a.ExecuteNonQueryAsync(ct); archived = candidates.Count; } await using var d = new NpgsqlCommand("DELETE FROM platform.retention_fixture_records WHERE tenant_id=$1 AND record_id=ANY($2)", c, tx); Add(d, Guid.Parse(tenant), candidates.Select(x => x.Id).ToArray()); deleted = await d.ExecuteNonQueryAsync(ct); }
        var now = DateTimeOffset.UtcNow; var run = new RetentionRun(Guid.NewGuid(), tenant, previewId, policy.PolicyId, policy.Version, dryRun ? "Previewed" : "Completed", dryRun, deleted, archived, preview.HeldRows, now, now, actor, dryRun ? "No rows deleted" : "Bounded qualification fixture batch completed"); await using (var q = new NpgsqlCommand("INSERT INTO platform.retention_runs(tenant_id,run_id,preview_id,policy_id,policy_version,state,dry_run,deleted_rows,archived_rows,held_rows,started_at,completed_at,actor,detail) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)", c, tx)) { Add(q, Guid.Parse(tenant), run.RunId, previewId, policy.PolicyId, policy.Version, run.State, dryRun, deleted, archived, run.HeldRows, now, now, actor, run.Detail); await q.ExecuteNonQueryAsync(ct); }
        await using (var q = new NpgsqlCommand("INSERT INTO platform.cleanup_history(tenant_id,cleanup_id,category,item_count,bytes_reclaimed,held_items,state,occurred_at,actor,detail) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", c, tx)) { Add(q, Guid.Parse(tenant), Guid.NewGuid(), policy.Category, deleted, candidates.Where(x => !dryRun).Sum(x => (long)x.Bytes), preview.HeldRows, run.State, now, actor, run.Detail); await q.ExecuteNonQueryAsync(ct); }
        await using (var q = new NpgsqlCommand("INSERT INTO platform.ha_audit(audit_id,event_type,subject,actor,generation,occurred_at,detail) VALUES($1,'retention.completed',$2,$3,NULL,$4,$5)", c, tx)) { Add(q, Guid.NewGuid(), run.RunId.ToString("D"), actor, now, $"deleted={deleted};held={preview.HeldRows};dryRun={dryRun}"); await q.ExecuteNonQueryAsync(ct); }
        await tx.CommitAsync(ct); return run;
    }
    public Task<IReadOnlyList<RetentionRun>> RunsAsync(string tenant, CancellationToken ct) => Runs(tenant, ct);
    async Task<IReadOnlyList<RetentionRun>> Runs(string tenant, CancellationToken ct) { var x = new List<RetentionRun>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT run_id,preview_id,policy_id,policy_version,state,dry_run,deleted_rows,archived_rows,held_rows,started_at,completed_at,actor,detail FROM platform.retention_runs WHERE tenant_id=$1 ORDER BY started_at DESC LIMIT 200", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), tenant, r.GetGuid(1), r.GetGuid(2), r.GetInt32(3), r.GetString(4), r.GetBoolean(5), r.GetInt64(6), r.GetInt64(7), r.GetInt64(8), r.GetFieldValue<DateTimeOffset>(9), r.IsDBNull(10) ? null : r.GetFieldValue<DateTimeOffset>(10), r.GetString(11), r.GetString(12))); return x; }
    public async Task<IReadOnlyList<ArchiveJob>> ArchivesAsync(string tenant, CancellationToken ct) { var x = new List<ArchiveJob>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT archive_id,policy_id,policy_version,scope,from_time,to_time,record_count,schema_versions,manifest_hash,state,created_at FROM platform.archive_jobs WHERE tenant_id=$1 ORDER BY created_at DESC", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), tenant, r.GetGuid(1), r.GetInt32(2), r.GetString(3), r.GetFieldValue<DateTimeOffset>(4), r.GetFieldValue<DateTimeOffset>(5), r.GetInt64(6), r.GetFieldValue<string[]>(7), r.GetString(8), r.GetString(9), r.GetFieldValue<DateTimeOffset>(10))); return x; }
    public async Task<IReadOnlyList<CleanupHistory>> CleanupAsync(string tenant, CancellationToken ct) { var x = new List<CleanupHistory>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT cleanup_id,category,item_count,bytes_reclaimed,held_items,state,occurred_at,actor,detail FROM platform.cleanup_history WHERE tenant_id=$1 ORDER BY occurred_at DESC LIMIT 200", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), tenant, r.GetString(1), r.GetInt64(2), r.GetInt64(3), r.GetInt64(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetString(7), r.GetString(8))); return x; }
    public async Task<IReadOnlyList<StorageDomainUsage>> StorageAsync(string tenant, CancellationToken ct) { var map = new Dictionary<string, string> { { "process", "process_entities" }, { "file", "file_entities" }, { "registry", "registry_events" }, { "network", "network_events" }, { "dns", "dns_events" }, { "module", "module_events" }, { "persistence", "persistence_events" }, { "identity", "identity_events" }, { "execution", "execution_events" }, { "findings", "detection_findings" }, { "correlation", "correlated_findings" }, { "alerts", "alerts" }, { "incidents", "incidents" } }; var x = new List<StorageDomainUsage>(); await using var c = await data.OpenConnectionAsync(ct); foreach (var item in map) { await using var q = new NpgsqlCommand($"SELECT count(*),pg_total_relation_size('platform.{item.Value}') FROM platform.{item.Value} WHERE tenant_id=$1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); await r.ReadAsync(ct); x.Add(new(item.Key, r.GetInt64(0), r.GetInt64(1), 0, 0)); } return x; }
    public async Task<CapacitySample> RecordCapacityAsync(CapacitySample x, CancellationToken ct) { if (x.SampleId == Guid.Empty || x.DurationSeconds <= 0 || x.GeneratedEvents < 0 || x.AcceptedEvents < 0 || x.UnexplainedLoss < 0 || x.AcceptedEvents + x.RejectedEvents + x.DuplicateEvents + x.UnexplainedLoss != x.GeneratedEvents) throw new EnrollmentConflictException("CAPACITY_SAMPLE_INVALID", "Capacity sample counts or duration are invalid."); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.capacity_samples(sample_id,captured_at,platform_version,profile,duration_seconds,simulated_endpoints,native_agents,generated_events,accepted_events,rejected_events,duplicate_events,unexplained_loss,events_per_second,postgres_bytes,opensearch_bytes,minio_bytes,nats_bytes,environment,measurements) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb,$19::jsonb)", c); Add(q, x.SampleId, x.CapturedAt, x.PlatformVersion, x.Profile, x.DurationSeconds, x.SimulatedEndpoints, x.NativeAgents, x.GeneratedEvents, x.AcceptedEvents, x.RejectedEvents, x.DuplicateEvents, x.UnexplainedLoss, x.EventsPerSecond, x.PostgreSqlBytes, x.OpenSearchBytes, x.MinioBytes, x.NatsBytes, JsonSerializer.Serialize(x.Environment, Json), JsonSerializer.Serialize(x.Measurements, Json)); await q.ExecuteNonQueryAsync(ct); return x; }
    public async Task<IReadOnlyList<CapacitySample>> CapacityAsync(int limit, CancellationToken ct) { var x = new List<CapacitySample>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT sample_id,captured_at,platform_version,profile,duration_seconds,simulated_endpoints,native_agents,generated_events,accepted_events,rejected_events,duplicate_events,unexplained_loss,events_per_second,postgres_bytes,opensearch_bytes,minio_bytes,nats_bytes,environment::text,measurements::text FROM platform.capacity_samples ORDER BY captured_at DESC LIMIT $1", c); q.Parameters.AddWithValue(Math.Clamp(limit, 1, 200)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), r.GetFieldValue<DateTimeOffset>(1), r.GetString(2), r.GetString(3), r.GetDecimal(4), r.GetInt32(5), r.GetInt32(6), r.GetInt64(7), r.GetInt64(8), r.GetInt64(9), r.GetInt64(10), r.GetInt64(11), r.GetDecimal(12), r.GetInt64(13), r.GetInt64(14), r.GetInt64(15), r.GetInt64(16), JsonSerializer.Deserialize<Dictionary<string, string>>(r.GetString(17), Json)!, JsonSerializer.Deserialize<Dictionary<string, decimal>>(r.GetString(18), Json)!)); return x; }
    public async Task<CapacityOperationalMetrics> OperationalMetricsAsync(CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT (SELECT coalesce(sum(deleted_rows),0) FROM platform.retention_runs),(SELECT coalesce(sum(held_rows),0) FROM platform.retention_runs),(SELECT count(*) FROM platform.cleanup_history WHERE state='Failed'),(SELECT coalesce(sum(rejected_count),0) FROM platform.tenant_rate_windows),(SELECT coalesce(sum(payload_bytes),0) FROM platform.retention_fixture_records WHERE category='temporary-data'),(SELECT count(*) FROM platform.retention_holds WHERE active AND (expires_at IS NULL OR expires_at>now()))", c); await using var r = await q.ExecuteReaderAsync(ct); await r.ReadAsync(ct); return new(r.GetInt64(0), r.GetInt64(1), r.GetInt64(2), r.GetInt64(3), r.GetInt64(4), r.GetInt64(5)); }
    public async Task<TenantCapacityQuota> PutQuotaAsync(string tenant, string actor, TenantCapacityQuotaRequest request, CancellationToken ct) { CapacityRetentionSafety.Validate(request); var prior = await QuotaAsync(tenant, ct); var now = DateTimeOffset.UtcNow; var x = new TenantCapacityQuota(tenant, prior.Version + 1, request.IngestPerMinute, request.SearchPerMinute, request.ReplayPerMinute, request.ExportPerMinute, request.ForensicPerMinute, request.PlaybookPerMinute, request.UpdatePerMinute, request.MaxConcurrentForensic, request.MaxConcurrentPlaybooks, now, actor, ""); x = x with { PolicyHash = CapacityRetentionSafety.Hash(x with { PolicyHash = "", CreatedAt = default, CreatedBy = "" }) }; await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.tenant_capacity_quotas(tenant_id,version,ingest_per_minute,search_per_minute,replay_per_minute,export_per_minute,forensic_per_minute,playbook_per_minute,update_per_minute,max_concurrent_forensic,max_concurrent_playbooks,created_at,created_by,policy_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(tenant_id) DO UPDATE SET version=EXCLUDED.version,ingest_per_minute=EXCLUDED.ingest_per_minute,search_per_minute=EXCLUDED.search_per_minute,replay_per_minute=EXCLUDED.replay_per_minute,export_per_minute=EXCLUDED.export_per_minute,forensic_per_minute=EXCLUDED.forensic_per_minute,playbook_per_minute=EXCLUDED.playbook_per_minute,update_per_minute=EXCLUDED.update_per_minute,max_concurrent_forensic=EXCLUDED.max_concurrent_forensic,max_concurrent_playbooks=EXCLUDED.max_concurrent_playbooks,created_at=EXCLUDED.created_at,created_by=EXCLUDED.created_by,policy_hash=EXCLUDED.policy_hash", c); Add(q, Guid.Parse(tenant), x.Version, x.IngestPerMinute, x.SearchPerMinute, x.ReplayPerMinute, x.ExportPerMinute, x.ForensicPerMinute, x.PlaybookPerMinute, x.UpdatePerMinute, x.MaxConcurrentForensic, x.MaxConcurrentPlaybooks, now, actor, x.PolicyHash); await q.ExecuteNonQueryAsync(ct); return x; }
    public async Task<TenantCapacityQuota> QuotaAsync(string tenant, CancellationToken ct) { await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT version,ingest_per_minute,search_per_minute,replay_per_minute,export_per_minute,forensic_per_minute,playbook_per_minute,update_per_minute,max_concurrent_forensic,max_concurrent_playbooks,created_at,created_by,policy_hash FROM platform.tenant_capacity_quotas WHERE tenant_id=$1", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(tenant, r.GetInt32(0), r.GetInt32(1), r.GetInt32(2), r.GetInt32(3), r.GetInt32(4), r.GetInt32(5), r.GetInt32(6), r.GetInt32(7), r.GetInt32(8), r.GetInt32(9), r.GetFieldValue<DateTimeOffset>(10), r.GetString(11), r.GetString(12)) : CapacityRetentionSafety.DefaultQuota(tenant); }
    public async Task<TenantQuotaDecision> ConsumeAsync(string tenant, string category, int units, CancellationToken ct) { if (units is < 1 or > 10000) throw new EnrollmentConflictException("CAPACITY_QUOTA_UNITS", "Quota units are invalid."); var p = await QuotaAsync(tenant, ct); var limit = category switch { "ingest" => p.IngestPerMinute, "search" => p.SearchPerMinute, "replay" => p.ReplayPerMinute, "export" => p.ExportPerMinute, "forensic" => p.ForensicPerMinute, "playbook" => p.PlaybookPerMinute, "update" => p.UpdatePerMinute, _ => throw new EnrollmentConflictException("CAPACITY_QUOTA_CATEGORY", "Quota category is invalid.") }; var start = new DateTimeOffset(DateTimeOffset.UtcNow.Year, DateTimeOffset.UtcNow.Month, DateTimeOffset.UtcNow.Day, DateTimeOffset.UtcNow.Hour, DateTimeOffset.UtcNow.Minute, 0, TimeSpan.Zero); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO platform.tenant_rate_windows(tenant_id,category,window_start,request_count,rejected_count,updated_at) VALUES($1,$2,$3,$4,0,now()) ON CONFLICT(tenant_id,category,window_start) DO UPDATE SET request_count=platform.tenant_rate_windows.request_count+$4,updated_at=now() WHERE platform.tenant_rate_windows.request_count+$4<=$5 RETURNING request_count", c); Add(q, Guid.Parse(tenant), category, start, units, limit); var value = await q.ExecuteScalarAsync(ct); if (value is not null) return new(true, category, limit, Convert.ToInt32(value, System.Globalization.CultureInfo.InvariantCulture), start.AddMinutes(1)); await using var rejected = new NpgsqlCommand("UPDATE platform.tenant_rate_windows SET rejected_count=rejected_count+1,updated_at=now() WHERE tenant_id=$1 AND category=$2 AND window_start=$3", c); Add(rejected, Guid.Parse(tenant), category, start); await rejected.ExecuteNonQueryAsync(ct); return new(false, category, limit, limit, start.AddMinutes(1)); }
    public async Task SeedFixturesAsync(string tenant, IReadOnlyList<RetentionFixture> fixtures, CancellationToken ct) { if (fixtures.Count > 5000 || fixtures.Any(x => x.TenantId != tenant || x.PayloadBytes is < 1 or > 1048576 || x.ContentHash != CapacityRetentionSafety.Hash(x with { ContentHash = "" }))) throw new EnrollmentConflictException("RETENTION_FIXTURE_INVALID", "Qualification fixture is invalid or unbounded."); await using var c = await data.OpenConnectionAsync(ct); foreach (var x in fixtures) { await using var q = new NpgsqlCommand("INSERT INTO platform.retention_fixture_records(tenant_id,record_id,category,occurred_at,payload_bytes,active_reference,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,record_id) DO UPDATE SET category=excluded.category,occurred_at=excluded.occurred_at,payload_bytes=excluded.payload_bytes,active_reference=excluded.active_reference,content_hash=excluded.content_hash", c); Add(q, Guid.Parse(tenant), x.RecordId, x.Category, x.OccurredAt, x.PayloadBytes, x.ActiveReference, x.ContentHash); await q.ExecuteNonQueryAsync(ct); } }
    public async Task<IReadOnlyList<RetentionFixture>> FixturesAsync(string tenant, CancellationToken ct) { var x = new List<RetentionFixture>(); await using var c = await data.OpenConnectionAsync(ct); await using var q = new NpgsqlCommand("SELECT record_id,category,occurred_at,payload_bytes,active_reference,content_hash FROM platform.retention_fixture_records WHERE tenant_id=$1 ORDER BY occurred_at,record_id", c); q.Parameters.AddWithValue(Guid.Parse(tenant)); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(new(r.GetGuid(0), tenant, r.GetString(1), r.GetFieldValue<DateTimeOffset>(2), r.GetInt32(3), r.GetBoolean(4), r.GetString(5))); return x; }
    static void Add(NpgsqlCommand q, params object?[] values) { foreach (var x in values) q.Parameters.AddWithValue(x ?? DBNull.Value); }
    public async ValueTask DisposeAsync() { await data.DisposeAsync(); GC.SuppressFinalize(this); }
}
